### ISSUE TITLE
Revelation.yml

### ISSUE THREAD

**Issue by maucf7** [RoyaleAPI/family-config#1]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config and fill in the following information.

```yaml
name: Revelation Star
key: Revelation
color: red
emblem: Diamond_Star_03
info:
  logo: https://i.ibb.co/QC9VYDF/RSLOGO.png
  description: >
     **Revelation Star** Somos una familia de clanes fundada desde el 2017 , para promover los deportes 
     electronicos en latinoamerica , pero nos hemos expandido tanto desde entonces que ahora somos una 
     familia internacional, con equipo competitivo con mucha experiencia , al igual que nuestro clan 
      principal ha logrado estar muchas veces en el top global LADDER y aun seguiremos creciendo , si 
       quieres adentrarte en este mundo es tu momento de unirte y formar parte de nuestra familia , 
        REVELATION STAR DONDE NACEN LAS ESTRELLAS!
  social:
    - twitter: https://twitter.com/_RevelationStar
    - discord: https://discord.gg/tBV3SC7
    - youtube: https://www.youtube.com/user/maucf7
    - website: http://revelationstar.com
    - application: https://play.google.com/store/apps/details?id=com.revelationstar.revelationstar
    - email: mailto: revelationstarcr@gmail.com
clans:
  - name: Revelation Star
    tag: 92VJLV8P
  - name: Revelation TEAM
    tag: 8GCQC9VJ
  - name: Revelation Next
    tag: P2R0C8JY
  - name: Revelation live
    tag: PCYQV2RQ
  - name: EEB Esports
    tag: 8JRPYY0L
  - name: Ethernal Legends
    tag: 9RJ8L2R8
  - name: Union Mortal503
    tag: JGU2VP2
```
