### ISSUE TITLE
Nova EG Family Addition

### ISSUE THREAD

**Issue by WStrubert** [RoyaleAPI/family-config#100]
![Leo Discord SS](https://user-images.githubusercontent.com/31852228/61649986-9eb58b80-ac80-11e9-812c-2c70625679c2.png)
Hello I wanted to see if we can add a team to the Nova EG Family and make some edits to how the title is displayed. Also the discord link is expired.

Clan Name: Nova EG Leo
Clan Tag: 9UQ9URUL

Discord Link: discord.gg/C5m2hCd
Family Name display to include all 13 clans, We can change the description/info if need be.

![Royale API Leo](https://user-images.githubusercontent.com/31852228/61650183-213e4b00-ac81-11e9-84d4-4b5bfd29f53a.png)

**Comment by smlbiobot** [comment]
Please edit this file:

```yml
name: Nova EG
key: novaeg
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  description: >
    Official Nova eSports & CWA Clan|EG|Taurus|Lyra|Phoenix|Draco|
    Corona|Pegasus|Hydra|Octans|Aquila|Cygnus
  social:
    - discord: http://discord.gg/hYAZNTF
clans:
  - name: Nova EG
    tag: 8YLJ8UL2
  - name: Nova EG Cygnus
    tag: 8CRQRVJQ
  - name: Nova EG Taurus
    tag: 8J9QP82G
  - name: Nova EG Octans
    tag: 8UPGJ8LC
  - name: Nova EG Phoenix
    tag: 8VCUJU2C
  - name: Nova EG Hydra
    tag: 9PPRR8JC
  - name: Nova EG Lyra
    tag: 8U99P0Q8
  - name: Nova EG Draco
    tag: 8VJQPUC2
  - name: Nova EG Corona
    tag: 8JV9LVUL
  - name: Nova EG Pegasus
    tag: 990V0LJ8
  - name: Nova EG Aquila
    tag: 9Q9R9VCJ
  - name: Nova EG Orion
    tag: P2YJ0QC0
```

and post it here
