### ISSUE TITLE
[New]: Mero Family

### ISSUE THREAD

**Issue by silevrehelukhedu** [RoyaleAPI/family-config#1000]
### Family configuration

```yaml
name: Mero Family
key: meroclan
color: blue
emblem: Lotus_02
info:
  logo: /static/img/branding/badges/Lotus_02.png
  description: >
    **Mero Clan Family** an emerging clan with active and engaging players. War focused but friendly ties valued avobe all.
    
clans:
  - name: Mero Clan
    tag: G9RCJ9QY
  - name: Didi ko clan <3
    tag: QPURLRYU
  - name: Touching Grass
    tag: QLUULOG9
```

### Additional Info

new familiy, i might have tried creating one some hours ago but it had a problem?
so re doing.

**Comment by silevrehelukhedu** [comment]
So, how long does it usually take?

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Mero Family
key: meroclan
color: blue
emblem: Lotus_02
info:
  description: >
    **Mero Clan Family** an emerging clan with active and engaging players. War focused but friendly ties valued avobe all.
clans:
  - name: Mero Clan
    tag: G9RCJ9QY
  - name: Didi ko clan <3
    tag: QPURLRYU
  - name: Touching Grass
    tag: QLUUL0G9

```
