### ISSUE TITLE
[New]: Anfaenger Family

### ISSUE THREAD

**Issue by tschogge** [RoyaleAPI/family-config#1002]
### Family configuration

```yaml
name: Anfänger Family
key: anfaenger
color: red
emblem: Tower_02
sort: trophy
info:
  logo: https://cdn.discordapp.com/attachments/1119620158072307793/1182358881712746620/Gxnh2MNzZ3L7a6SP9OBY--1--x5yev.png?ex=65846884&is=6571f384&hm=f49a2cc93405786a206e9f766dd45b2368a1dc4c43ab6c5e9063a5287b16c536&
  descriptioon: >
    We are a Clanwar oriented Clanfamily from Austria.
    Our Clanfamily consists of 6 top war clans.
    We also have a very active discord and monthly tournaments.
  social:
    - tiktok: https://www.tiktok.com/@anfaenger.clanfamilie?_t=8hzM5ql6jar&_r=1
  clans:
    - name: Anfänger 
      tag: YRVVQG9
    - name: Anfänger Lager
      tag: 9JUP02JL
    - name: AUT Fighters
      tag: 90RGVR2R
    - name: We're Austria 
      tag: PY9Q9CPY
    - name: Knusperelite
      tag: VL020
    - name: 24/7 Saufen
      tag: 9LJQJRVQ
```

### Additional Info

[our logo](https://cdn.discordapp.com/attachments/1119620158072307793/1182358881712746620/Gxnh2MNzZ3L7a6SP9OBY--1--x5yev.png?ex=65846884&is=6571f384&hm=f49a2cc93405786a206e9f766dd45b2368a1dc4c43ab6c5e9063a5287b16c536&)

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Anfänger Family
key: anfaenger
color: red
emblem: Tower_02
sort: trophy
info:
  logo: anfaenger.png
  descriptioon: >
    We are a Clanwar oriented Clanfamily from Austria.
    Our Clanfamily consists of 6 top war clans.
    We also have a very active discord and monthly tournaments.
  social:
    - tiktok: https://www.tiktok.com/@anfaenger.clanfamilie
clans:
  - name: Anfänger 
    tag: YRVVQG9
  - name: Anfänger Lager
    tag: 9JUP02JL
  - name: AUT Fighters
    tag: 90RGVR2R
  - name: We're Austria 
    tag: PY9Q9CPY
  - name: Knusperelite
    tag: VL020
  - name: 24/7 Saufen
    tag: 9LJQJRVQ

```

**Comment by smlbiobot** [comment]
This clan currently exist in their own family. Would you please let me know which family they should exist in?

```
    - name: We're Austria 
      tag: PY9Q9CPY
```

**Comment by therxbbse-code** [comment]
I am not sure i understand the Question. This Clan is part of the Anfänger Clanfamily since years and nothing changed since then

**Comment by tschogge** [comment]
@smlbiobot

**Comment by smlbiobot** [comment]
This clan currently exists in another clan family called “We’re Austria”

```yml
  - name: We're Austria 
    tag: PY9Q9CPY
```

As they are clearly called “We’re Austria”, I’m inclined to think that they’re the rightful owner of this family. You’ll need to ask the Leader of the clan to go on our Discord server, verify their account and to say that they want to move into your family if you want to continue.

```yml
name: WE'RE AUSTRIA Family
key: austria
color: purple
emblem: Traditional_Star_05
info:
  logo: /static/img/brands/logo/austria.png
  description: "**TOP Clan Family in Austria - #1 Clan local** We are a goal-driven\
    \ family out of 4 clans. Our clans are constantly growing and developing day by\
    \ day. We are always looking for active Clashers who want to join our family.\
    \ **~ Come together and play together ~**\n"
  social:
  - discord: https://discord.gg/5ptFqn
  - instagram: https://www.instagram.com/were_austria/
clans:
- name: ⭐WE'RE AUSTRIA⭐
  tag: Y9GCCYR8
- name: WE'RE AUSTRIA
  tag: PY9Q9CPY
- name: WE'RE AUSTRIA 2
  tag: 9VRQ08GC

```
