### ISSUE TITLE
[Update]:  DUDES UNITED FAMILY

### ISSUE THREAD

**Issue by robotdoggo** [RoyaleAPI/family-config#1004]
### Family name

Dudes United

### Family URL

https://royaleapi.com/clan/family/dudesunited/clans

### Family configuration

```yaml
name: Dudes United
key: dudesunited
color: black
emblem: Skull_06
info:
  description: >
    We're looking for international, English speaking players that want to grow with the
    family. apply on discord 

clans:
- name: Dudes Reunited
  tag: L0PQ2ULQ
- name: Dudes academy
  tag: GQYY2R82
- name: #awesomesauce
  tag: R2QLR8
- name: 'overlord'
  tag: L2LJ22JR
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Dudes United
key: dudesunited
color: black
emblem: Skull_06
info:
  description: >
    We're looking for international, English speaking players that want to grow with the
    family. apply on discord

clans:
  - name: Dudes Reunited
    tag: L0PQ2ULQ
  - name: Dudes academy
    tag: GQYY2R82
  - name: "#awesomesauce"
    tag: R2QLR8
  - name: "overlord"
    tag: L2LJ22JR

```
