### ISSUE TITLE
The Legends - Clan Family

### ISSUE THREAD

**Issue by CapsChess** [RoyaleAPI/family-config#1005]
### Family configuration

```yaml
name: The Legends
key: clashlegends
color: red
emblem: Crown_04
info:
   description: >
   "The Legends" are a clan family established in April 2023, with our first and main clan, "Clash Legends". 
   As the main clan grew bigger and bigger, we decided to keep that clan as a war-focused clan, as it had already reached more than 1,300 War Trophies. 
   The second and third clans, "Ladder Legends" and "Future Legends", were created on New Year's Day of 2024, and are built for different purposes. 
   The goal of  "Ladder Legends" is to host members looking to push for trophy growth rather than playing wars, whereas "Future Legends" is meant for the members returning to the game, who don't meet the 3,000 trophies requirement needed to join the main two.
   social: 
   - discord: https://discord.gg/zFUtSEWDYZ
clans:
   - name: Clash Legends
     tag: GQV08L0J
   - name: Ladder Legends
      tag: QLRPVGQU
   - name: Future Legends
      tag: QQ928PLJ

```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: The Legends
key: clashlegends
color: red
emblem: Crown_04
info:
  description: >
    "The Legends" are a clan family established in April 2023, with our first and main clan, "Clash Legends". 
    As the main clan grew bigger and bigger, we decided to keep that clan as a war-focused clan, as it had already reached more than 1,300 War Trophies. 
    The second and third clans, "Ladder Legends" and "Future Legends", were created on New Year's Day of 2024, and are built for different purposes. 
    The goal of  "Ladder Legends" is to host members looking to push for trophy growth rather than playing wars, whereas "Future Legends" is meant for the members returning to the game, who don't meet the 3,000 trophies requirement needed to join the main two.
  social: 
  - discord: https://discord.gg/zFUtSEWDYZ
clans:
  - name: Clash Legends
    tag: GQV08L0J
  - name: Ladder Legends
    tag: QLRPVGQU
  - name: Future Legends
    tag: QQ928PLJ
```
