### ISSUE TITLE
 I NORRENI - Clan Family

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#1006]

**Comment by Zaop7** [comment]
> [!NOTE]
> The logo link is unreachable.

> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: I NORRENI
key: norreni
color: red
emblem: Lotus_01
info:
  description: >
    **| NORRENI** is a Clash Royale War Family that offers a welcoming space with a supportive community for players 
    of all skill levels. | NORRENI strives to help members grow to improve their gameplay with a positive experience 
    and achieve success in Clan Wars. We have a total of 5+ clans. Check out our Discord to Apply!
  social:
    - website: https://linktr.ee/norreni
    - twitter: https://twitter.com/bay_nr_
    - twitter: https://twitter.com/NORRI_GG
    - discord: https://dsc.gg/norreni
clans:
  - name: I NORRENI
    tag: L9QCGY28
  - name: Game Over
    tag: YJ8YC08G
  - name: Training Ground
    tag: QLCGQUVC
  - name: NORRIv2
    tag: G8Y9CG20
  - name: NORRI.oP
    tag: QLVU99GJ

```

**Comment by WhizGaming360** [comment]
name: I NORRENI
key: norreni
color: red
emblem: Lotus_01
info:
  logo: https://i.ibb.co/ZSS6938/NORRENI.png
  description: >
    **| NORRENI** is a Clash Royale War Family that offers a welcoming space with a supportive community for players 
    of all skill levels. | NORRENI strives to help members grow to improve their gameplay with a positive experience 
    and achieve success in Clan Wars. We have a total of 5+ clans. Check out our Discord to Apply!
  social:
    - website: https://linktr.ee/norreni
    - twitter: https://twitter.com/bay_nr_
    - twitter: https://twitter.com/NORRI_GG
    - discord: https://dsc.gg/norreni
clans:
  - name: I NORRENI
    tag: L9QCGY28
  - name: Game Over
    tag: YJ8YC08G
  - name: Training Ground
    tag: QLCGQUVC
  - name: YT:CR Professor
    tag: QGJYR8R2
  - name: NORRIv2
    tag: G8Y9CG20
  - name: NORRI.oP
    tag: QLVU99GJ

**Comment by WhizGaming360** [comment]
@Zaop7 I updated the logo link and added YT:CR Professor clan.

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: I NORRENI
key: norreni
color: red
emblem: Lotus_01
info:
  logo: norreni.png
  description: >
    **| NORRENI** is a Clash Royale War Family that offers a welcoming space with a supportive community for players 
    of all skill levels. | NORRENI strives to help members grow to improve their gameplay with a positive experience 
    and achieve success in Clan Wars. We have a total of 5+ clans. Check out our Discord to Apply!
  social:
    - website: https://linktr.ee/norreni
    - twitter: https://twitter.com/bay_nr_
    - twitter: https://twitter.com/NORRI_GG
    - discord: https://dsc.gg/norreni
clans:
  - name: I NORRENI
    tag: L9QCGY28
  - name: Game Over
    tag: YJ8YC08G
  - name: Training Ground
    tag: QLCGQUVC
  - name: YT:CR Professor
    tag: QGJYR8R2
  - name: NORRIv2
    tag: G8Y9CG20

```
