### ISSUE TITLE
Midwinter clan family update

### ISSUE THREAD

**Issue by nickytee626** [RoyaleAPI/family-config#101]
```yaml
name: Midwinter Clan Family
key:midwinter
color:blue
emblem:Freeze_01
info:
  logo:
  description: >
    Midwinter is Coming!


   social:
    - twitter: http://twitter.com/midwinterCR
    - discord: http://discord.gg/CVNrEpD

clans:
  - name: Midwinter™️
    tag: 2LVRQ29
  - name: Midwinter Elite
    tag: YYG29P90
  - name: MidwinterEX
    tag: 2GL2QPPL
  -name: Midwinter NeXt
    tag: 2Q9Y8RG
  -name: Midwinter Fire
    tag: 29J9V9PU
  - name: Midwinter Frost
    tag: 8GG2GG9U
  - name: Midwinter Ice
    tag: YRR9L9VL
  - name: Midwinter Night
    tag: 2P922YL0
```
