### ISSUE TITLE
French Purple Family

### ISSUE THREAD

**Issue by MaxFax-creator** [RoyaleAPI/family-config#1010]
### Family configuration

```yaml
name: Purple & Co ⚛️
key: frenchpurple
color: purple
emblem: Star_Shine_03
sort: trophy
info:
  logo: /static/img/brands/logo/French_Purple.png
  description: >
    Bienvenue chez Purple & Co ⚛️, en arrivant chez nous vous pourrez y trouver 4 clans accès sur les guerres de clan ( French Purple, French Touch, Carpi et French Purple 2 ),
    nous accueillons des joueurs de tout niveau. Nous organisons également tous les mardis un tournoi de 21h à 23h en mode duel,
    ouvert à tout les clans français, l'objectif principal est de s'améliorer tous ensemble dans un même but commun 
  social:
    - discord: https://discord.gg/zEbKQjTkqS
clans:
  - name: French Purple
    tag: PGOQJ2V9
  - name: French Touch
    tag: PCQ2U98
  - name: Carpi
    tag: GVYL2J
  - name: French Purple 2
    tag: GP92VLJQ
```

### Additional Info

![French_Purple](https://github.com/RoyaleAPI/family-config/assets/68083354/b320deed-e165-4a3c-a292-2d3f006ec3dc)

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Purple & Co ⚛️
key: frenchpurple
color: purple
emblem: Star_Shine_03
info:
  logo: frenchpurple.png
  description: >
    Bienvenue chez Purple & Co ⚛️, en arrivant chez nous vous pourrez y trouver 4 clans accès sur les guerres de clan ( French Purple, French Touch, Carpi et French Purple 2 ),
    nous accueillons des joueurs de tout niveau. Nous organisons également tous les mardis un tournoi de 21h à 23h en mode duel,
    ouvert à tout les clans français, l'objectif principal est de s'améliorer tous ensemble dans un même but commun 
  social:
    - discord: https://discord.gg/zEbKQjTkqS
clans:
  - name: French Purple
    tag: PG0QJ2V9
  - name: French Touch
    tag: PCQ2U98
  - name: Carpi
    tag: GVYL2J
  - name: French Purple 2
    tag: GP92VLJQ
sort: trophy

```
