### ISSUE TITLE
The Yeah Fam

### ISSUE THREAD

**Issue by johnwebe** [RoyaleAPI/family-config#1013]
```yaml
name: The Yeah Fam
key: yeah
color: blue
  description: >
    Yo what's up it's your boy biggie cheese. Nah, not really. We are actually the yeah clan family. We consist of 3 clans that are just here to war. I mean what else can you do in this game? Have fun? Nuh uh. We keep our nose to the grinder and dominate whoever comes in our way. Check us out on our links and join our discord server. Most of the information or announcements are found on the discord. We use twitter for announcements and whatever we think is worth sharing into this world. The main clan is yeah, then Nah, then Active Royale 2. All of us are intertwined and connected to each other like a clan family should. So come and check us out. Hang out on our discord. Join the yeah clan or any other clans in the network. 
  social:
    - discord: https://discord.gg/GZDym6grxU
    - twitter: https://twitter.com/Yeah_5000
    - email: theyeahclan50@gmail.com
clans:
  - name: yeah
    tag: YV0222VJ
  - name: Nah
    tag: GCG2RJP0
  - name: Active Royale 2
    tag: GPVUVJ28
  - name: Bad Boyz Club
    tag: LJ0GQQCP
  ```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: The Yeah Fam
key: yeah
color: blue
emblem: Arrow_03
info:
  description: >
    Yo what's up it's your boy biggie cheese. Nah, not really. We are actually the yeah clan family. We consist of 3 clans that are just here to war. I mean what else can you do in this game? Have fun? Nuh uh. We keep our nose to the grinder and dominate whoever comes in our way. Check us out on our links and join our discord server. Most of the information or announcements are found on the discord. We use twitter for announcements and whatever we think is worth sharing into this world. The main clan is yeah, then Nah, then Active Royale 2. All of us are intertwined and connected to each other like a clan family should. So come and check us out. Hang out on our discord. Join the yeah clan or any other clans in the network.
  social:
    - discord: https://discord.gg/GZDym6grxU
    - twitter: https://twitter.com/Yeah_5000
    - email: mailto:theyeahclan50@gmail.com
clans:
  - name: yeah
    tag: YV0222VJ
  - name: Nah
    tag: GCG2RJP0
  - name: Active Royale 2
    tag: GPVUVJ28

```
