### ISSUE TITLE
[Update]: Kings of Fire War Family

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#1014]
### Family name

Kings of Fire War Family

### Family URL

https://royaleapi.com/clan/family/kings-of-fire/clans

### Family configuration

```yaml
name: Kings of Fire War Family
key: kings-of-fire
color: black
emblem: Crown_04
info:
  logo: /static/img/family/logo/kings-of-fire.gif
  description: >
    🔥WAR⚔️MACHINES⚔️ONLY🔥

  social:
  - discord: https://discord.gg/KOFcr

clans:
- name: Galactic Kings
  tag: Y9202P9U
- name: Crying Fire
  tag: 8Y2LVVQ9
- name: StillLegendary
  tag: 9CGYVG92
- name: Thunder Buddies
  tag: GL0J0R
- name: 102% Canadian
  tag: LGCYVUCJ
- name: M for mature
  tag: 2909VP
- name: League of Kings
  tag: L09UQL9Y
- name: Crying Fire™
  tag: LQQJQULG
- name: Bonecrushers
  tag: 20YLRYU
- name: Fiery Embers
  tag: QCC9C8UR
- name: Crying Fire 2
  tag: GYUJYJJP
- name: Crying Fire 3
  tag: Q0PL9VRR
- name: Embers of Fire
  tag: Q8QQ90L0
- name: L Ξ G I O N
  tag: Q0UYQUC8
- name: Tears of Fire
  tag: QCPGQCQV
- name: RedStorm
  tag: 2Q8JGYP
- name: Bench
  tag: PUJ00YQJ
- name: Second.2.None
  tag: Q2VCPVGV
- name: The Revolution
  tag: PJ82LVCG
- name: Newbie Farm
  tag: RGJC28
- name: NIGHT FEAR
  tag: LPRJQP
- name: Blood N Bones
  tag: 2PQY2VQR
- name: Elixir Thieves™
  tag: YG2LUQLC
```

### Additional Info

please see #1009 as well

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Kings of Fire War Family
key: kings-of-fire
color: black
emblem: Crown_04
info:
  logo: /static/img/family/logo/kings-of-fire.gif
  description: >
    🔥WAR⚔️MACHINES⚔️ONLY🔥
  social:
    - discord: https://discord.gg/KOFcr
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: StillLegendary
    tag: 9CGYVG92
  - name: Thunder Buddies
    tag: GL0J0R
  - name: 102% Canadian
    tag: LGCYVUCJ
  - name: M for mature
    tag: 2909VP
  - name: League of Kings
    tag: L09UQL9Y
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Bonecrushers
    tag: 20YLRYU
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Crying Fire 2
    tag: GYUJYJJP
  - name: Crying Fire 3
    tag: Q0PL9VRR
  - name: Embers of Fire
    tag: Q8QQ90L0
  - name: L Ξ G I O N
    tag: Q0UYQUC8
  - name: Tears of Fire
    tag: QCPGQCQV
  - name: RedStorm
    tag: 2Q8JGYP
  - name: Bench
    tag: PUJ00YQJ
  - name: Second.2.None
    tag: Q2VCPVGV
  - name: The Revolution
    tag: PJ82LVCG
  - name: Newbie Farm
    tag: RGJC28
  - name: NIGHT FEAR
    tag: LPRJQP
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Elixir Thieves™
    tag: YG2LUQLC

```
