### ISSUE TITLE
[Update]: 

### ISSUE THREAD

**Issue by AKTGuto** [RoyaleAPI/family-config#1015]
### Family name

Furia Royale II

### Family URL

Copy the link (Uhttps://instagram.com/furiaroyale2?igshid=NzZhOTFlYzFmZQ==RL address) from your browser and paste it here.

### Family configuration

```yaml
name: Furia Royale II
key: Furia
color: Black
emblem: Bambu_04
info:
  logo: 
  description: >
    Clans de Guerra!
    Somos uma familia competitiva, venha fazer parte desse grande time!
    FR2/AKT/MGs/SPT/BDH    
  social:
    - instagram: https://instagram.com/furiaroyale2?igshid=NzZhOTFlYzFmZQ==
clans:
  - name: Furia Royale II
    tag: 9CVJ9CLJ
  - name: Akatsuki Br
    tag: 928VR909
  - name: MG Stars ©®
    tag: 98YVQ22R
  - name: SPARTAN ROYALE
    tag: PLY802LU
  - name:  FR II
    tag: QYJ9800C
  - name: Bloodyhands 
    tag: 9CVVG9
```

**Comment by AKTGuto** [comment]
Por favor, atualizar

**Comment by AKTGuto** [comment]
Por favor, atualize

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Furia Royale II
key: frii
color: Black
emblem: Bamboo_04
info:
  description: >
    Clans de Guerra!
    Somos uma familia competitiva, venha fazer parte desse grande time!
    FR2/AKT/MGs/SPT/BDH
  social:
    - instagram: https://instagram.com/furiaroyale2
clans:
  - name: Furia Royale II
    tag: 9CVJ9CLJ
  - name: Akatsuki Br
    tag: 928VR909
  - name: MG Stars ©®
    tag: 98YVQ22R
  - name: SPARTAN ROYALE
    tag: PLY802LU
  - name: FR II
    tag: QYJ9800C
  - name: Bloodyhands
    tag: 9CVVG9

```
