### ISSUE TITLE
Familia Martillo Helado

### ISSUE THREAD

**Issue by BugsRab** [RoyaleAPI/family-config#1016]
```yaml
name: Martillo Helado 
key: familiamartillohelado
color: blue
emblem: Hammer_01
info:
  description: >
  Hola, somos la familia **Martillo Helado** , todos nuestros clanes están enfocados a la guerra. ¡Únete!
  social:
    - discord: https://discord.gg/dphXNBnz3G
clans:
  - name: Martillo Helado
    tag: QV2LLQG0
  - name:MartilloHelado2
    tag: QVLP28C9

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Martillo Helado
key: martillo
color: blue
emblem: A_Char_Hammer_01
info:
  description: >
    Hola, somos la familia **Martillo Helado** , todos nuestros clanes están enfocados a la guerra. ¡Únete!
  social:
    - discord: https://discord.gg/dphXNBnz3G
clans:
  - name: Martillo Helado
    tag: QV2LLQG0
  - name: MartilloHelado2
    tag: QVLP28C9

```
