### ISSUE TITLE
[Update]: AlphaGo Family

### ISSUE THREAD

**Issue by LuminousForMe** [RoyaleAPI/family-config#1017]
### Family name

AlphaGo Family

### Family URL

https://royaleapi.com/clan/family/AlphaGo/clans

### Family configuration

```yaml
name: AlphaGo Family
key: AlphaGo
color: blue
emblem: Crown_03
info:
  logo: https://st.depositphotos.com/32634758/53029/v/450/depositphotos_530299196-stock-illustration-logo-monogram-triangle-hexagon-shape.jpg
  description: >
    Welcome to AlphaGo Family. We are the best clans in Korea.

  social:
    - twitter: https://twitter.com/egestone99?s=21&t=Pp5twR9pkh_3k_k-OJoTuA
    - youtube: https://youtube.com/channel/UCaECad3wyre_fRToi8EN52A
    - kakaotalk: https://open.kakao.com/o/ssrNvCAc
    - application: https://open.kakao.com/o/g4JMIzvc

clans:
  - name: AlphaGo
    tag: 2QG8QQR
  - name: BetaGo
    tag: QUR8QYVG
  - name: BetaGo+
    tag: Q9G9RJGQ
  - name: ZetaGo 
    tag: Q8VC9CRJ
  - name: AlphaGo 쉼터
    tag: L8R90VCP
```

### Additional Info

Update request issued on December 29th, 2023, no answers / comments yet. Same as before.

BetaGo tag was changed; BetaGo+ was added.

Contact me for any problems and questions: forme1098@gmail.com
