### ISSUE TITLE
[Update]: 巅峰大家庭 TOP-CLAN、add three clan

### ISSUE THREAD

**Issue by as953211272** [RoyaleAPI/family-config#1018]
CAN YOU HELP ME? THANK YOU

hello, I am so sad and inconsolable that one guy destroyed my clan, I accidentally gave leader to this guy, but he kicked all people and he left, so the clan haven't people that close,I can't come in,how can I get back my clan? my clan label is #Q208JY90,this guy destoryed my clan IKun #U0U0Y0URG

### Family name

巅峰大家庭

### Family URL

https://royaleapi.com/clan/family/top-clan/clans

### Family configuration

```yaml
Paste your YAML config here

name: 巅峰大家庭
key: top
color: red
emblem: Traditional_Star_04
info:
  logo: https://pbs.twimg.com/media/FygqoE5akAMEkTn?format=jpg&name=small
  description: >
    **縱橫馳騁任征途，巔峰巍峨志不枯！**

    欢迎您加入我们**巅峰大家庭**，我们国际服有9个部落2个友盟，国服有3个部落。
    这里汇聚志同道合的伙伴，携手追求卓越。巅峰，不仅是目标，更是起点，我们共同走向成功巅峰的征程。让我们一起学习、成长、共享，创造无限可能，迎接光辉未来！

     **Q群734478032**，欢迎各位小伙伴的加入！！
     
     **巅峰！！所向披靡！！！**    
  social:
    - website: https://space.bilibili.com/24292931
clans:
  - name: 巅峰丿圣域
    tag: YQUUP89V
  - name: 巅峰丿神域
    tag: Q22UYJG2
  - name: 巅峰丿阖域
    tag: QCR9QQQG
  - name: 巅峰丿煙域
    tag: Q8QJRJ8G
  - name: 巅峰丿龍域
    tag: GRGGU9RR
  - name: 巅峰丿禹域
    tag: ROCPYRYU
  - name: 巅峰丿皇域
    tag: QGVL9J0L
  - name: 巅峰丿極域
    tag: GPPJRGQU
  - name: 巅峰丿華域
    tag: QQGY92JY
```

### Additional Info

hello, I want to add 3 clan
thank you very much

**Comment by Zaop7** [comment]
Hi, we are not able to help you with your lost clan here. You can try to contact Supercell support directly in game. I wish you good luck!

Also, only a-z letters are allowed in the key. Can you please update it?

**Comment by as953211272** [comment]
Thank you, I already update my configuration, please update it in website

**Comment by as953211272** [comment]
> Thank you, I already update my configuration, please update it in website

Thank you, I already update my configuration, please update it in website

**Comment by as953211272** [comment]
> Hi, we are not able to help you with your lost clan here. You can try to contact Supercell support directly in game. I wish you good luck!
> 
> Also, only a-z letters are allowed in the key. Can you please update it?

Thank you, I already update my configuration, please update it in website

**Comment by Zaop7** [comment]
Got it. Once was enough, but never mind. 😅 And letters a-z doesn't include letters A-Z. Don't worry about it, I can handle that ;) Thanks for the update!

**Comment by as953211272** [comment]
> Got it. Once was enough, but never mind. 😅 And letters a-z doesn't include letters A-Z. Don't worry about it, I can handle that ;) Thanks for the update!

sorry, I already update it, please update in website, thank you

**Comment by as953211272** [comment]
> Got it. Once was enough, but never mind. 😅 And letters a-z doesn't include letters A-Z. Don't worry about it, I can handle that ;) Thanks for the update!

can you update it? thank you

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: 巅峰大家庭
key: top-clan
color: red
emblem: Traditional_Star_04
info:
  logo: /static/img/family/logo/top-clan-v2.jpg
  description: >
    **縱橫馳騁任征途，巔峰巍峨志不枯！**

    欢迎您加入我们**巅峰大家庭**，我们国际服有9个部落2个友盟，国服有3个部落。
    这里汇聚志同道合的伙伴，携手追求卓越。巅峰，不仅是目标，更是起点，我们共同走向成功巅峰的征程。让我们一起学习、成长、共享，创造无限可能，迎接光辉未来！

     **Q群734478032**，欢迎各位小伙伴的加入！！
     
     **巅峰！！所向披靡！！！**
  social:
    - website: https://space.bilibili.com/24292931
clans:
  - name: 巅峰丿圣域
    tag: YQUUP89V
  - name: 巅峰丿神域
    tag: Q22UYJG2
  - name: 巅峰丿阖域
    tag: QCR9QQQG
  - name: 巅峰丿煙域
    tag: Q8QJRJ8G
  - name: 巅峰丿龍域
    tag: GRGGU9RR
  - name: 巅峰丿禹域
    tag: R0CPYRYU
  - name: 巅峰丿皇域
    tag: QGVL9J0L
  - name: 巅峰丿極域
    tag: GPPJRGQU
  - name: 巅峰丿華域
    tag: QQGY92JY

```
