### ISSUE TITLE
[New]: Hevon

### ISSUE THREAD

**Issue by Maki776** [RoyaleAPI/family-config#1022]
### Family configuration

```yaml
name: Hevon
key: Hevon
color: blue
emblem: heart_04
info:
  description: >
    The **Hevon Clan Family** is a war family, consisting of 6 clans. Players are involved in Discord and CR activities!
  social:
    - discord: https://discord.gg/qsxKepCM3z
clans:
  - name: GrannyPunchers2
    tag: L9UPCUGY
  - name: TEAM KNOCKOUTS
    tag: YQJPR2V9
  - name: Indian Helix
    tag: QQRYRP8G
  - name: Hevon
    tag: GVVCUP9P
  - name: Hevie
    tag: QYPV9LPQ
  - name: Shogun
    tag: GGU29GLQ
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Hevon
key: hevon
color: blue
emblem: Heart_04
info:
  description: >
    The **Hevon Clan Family** is a war family, consisting of 6 clans. Players are involved in Discord and CR activities!
  social:
    - discord: https://discord.gg/qsxKepCM3z
clans:
  - name: GrannyPunchers2
    tag: L9UPCUGY
  - name: TEAM KNOCKOUTS
    tag: YQJPR2V9
  - name: Indian Helix
    tag: QQRYRP8G
  - name: Hevon
    tag: GVVCUP9P
  - name: Hevie
    tag: QYPV9LPQ
  - name: Shogun
    tag: GGU29GLQ

```
