### ISSUE TITLE
Familia Comunidad Lunar

### ISSUE THREAD

**Issue by Criswolf3654** [RoyaleAPI/family-config#1023]
```
name: CL | Comunidad Lunar™
key: lunar
color: blue
emblem: Fugi_03
sort: trophy
info:
  description: >
Comunidad Venezolana aspirante a llegar a lo más grande

clans:
  - name: cueva negra
    tag: QP9GVJRC
  - name: Villa Lunar
    tag: GCRUQ2OQ
  - name: Luz Nocturna
    tag: ROQ9CQ2G
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: CL | Comunidad Lunar™
key: lunar
color: blue
emblem: Fugi_03
sort: trophy
info:
  description: >
    Comunidad Venezolana aspirante a llegar a lo más grande
clans:
  - name: cueva negra
    tag: QP9GVJRC
  - name: Villa Lunar
    tag: GCRUQ20Q
  - name: Luz Nocturna
    tag: R0Q9CQ2G

```
