### ISSUE TITLE
[New]: Fight Club Family config

### ISSUE THREAD

**Issue by deagzgaming** [RoyaleAPI/family-config#1024]
### Family configuration

```yaml
name: Fight Club Family
key: fcf
color: red
emblem: Arrow_04
info:
  logo: https://imgur.com/a/CjC3pKH
  description: >
    ## Fight Club Family
    
    **Become a part of the Fight Club Family - a competitive and friendly
    Clash Royale community!** Led by active and supportive leaders,
    our clan family offers a vibrant Discord community where you can chat, play,
    and learn from other players. You can also enjoy our regular tournaments,
    diamond pass rewards, coaching sessions, war deck advice, voice chats, and game nights.
    
    Whether you are a member of one of our clans, a guest or a VIP,
    you will always feel welcome and valued in our community.
  social:
    - discord: https://invite.fightclubusa.io/
    - website: https://disboard.org/server/1178325397486702652
clans:
  - name: FIGHT CLUB USA
    tag: JGU2YLR
  - name: "#Destructium"
    tag: Q0VQLQ9R
  - name: FIGHT CLUB USA2
    tag: 8YG988CQ
  - name: Clash Vikings
    tag: QJ8RL9Y2
```

### Additional Info

Fight Club USA (#JGU2YLR) is currently associated with adfamily. Please remove references to JGU2YLR from the adfamily (and any other) config as they are no longer valid. Thanks.

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Fight Club Family
key: fcf
color: red
emblem: Arrow_04
info:
  logo: fcf.png
  description: >
    ## Fight Club Family
    
    **Become a part of the Fight Club Family - a competitive and friendly
    Clash Royale community!** Led by active and supportive leaders,
    our clan family offers a vibrant Discord community where you can chat, play,
    and learn from other players. You can also enjoy our regular tournaments,
    diamond pass rewards, coaching sessions, war deck advice, voice chats, and game nights.
    
    Whether you are a member of one of our clans, a guest or a VIP,
    you will always feel welcome and valued in our community.
  social:
    - discord: https://discord.com/invite/eNwbKw9QeU
clans:
  - name: FIGHT CLUB USA
    tag: JGU2YLR
  - name: "#Destructium"
    tag: Q0VQLQ9R
  - name: FIGHT CLUB USA2
    tag: 8YG988CQ
  - name: Clash Vikings
    tag: QJ8RL9Y2

```
