### ISSUE TITLE
[Update]: Aliança Lusa Family

### ISSUE THREAD

**Issue by cubernix** [RoyaleAPI/family-config#1025]
### Family name

Aliança Lusa Family

### Family URL

https://royaleapi.com/clan/family/aliancalusa/clans

### Family configuration

```yaml
Family name
Aliança Lusa

Family URL
https://royaleapi.com/clan/family/aliancalusa/clans

Family configuration
name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_04
info:
  logo: aliancalusa-v2.png
  description: >
    A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022, o segundo
    a 21/10/2022, e o terceiro a 22/06/2023, está já no TOPO do Ranking de Portugal
    no que toca a troféus e ligas. Temos também um clã para férias, o Aliança Lusa Ⓡ!
    Somos também clã ATIVO de guerra, com Discord, grupo no Whatsapp e com constantes
    Torneios Internos com prémios! ATREVE-TE! 

    The Aliança Lusa Family, whose main clan was created on 09/18/2022, the second
    on 10/21/2022, and the third on 06/22/2023, is already at the TOP of the Portugal
    Ranking in terms of trophies and leagues. We also have a vacation clan, the Aliança Lusa Ⓡ!
    We are also an ACTIVE war clan, with Discord, Whatsapp group and constant
    Internal Tournaments with prizes! DARE TO JOIN US!

  social:
    - discord: https://discord.gg/SqtyGHAzQN

clans:
  - name: Aliança Lusa
    tag: Q0R08YLJ
  - name: Aliança Lusa 2
    tag: Q20GUCV8
  - name: Aliança Lusa 3
    tag: GC92VYJP
  - name: Aliança Lusa Ⓡ
    tag: QQ9QP9JJ
…
```

### Additional Info

3rd time I try too update :(
