### ISSUE TITLE
[New]: The_Last_Of_Us 

### ISSUE THREAD

**Issue by ghost** [RoyaleAPI/family-config#1026]
### Family configuration

```yaml
name: The_Last_Of_Us Family Clan
key: thelastofus
color: blue
emblem: flag_h_02
info:
  logo: https://drive.google.com/file/d/1G4cRIzU-FemsfAeeP2bVc8SvEqmsjU0O/view?usp=sharing
  description: >
    **The_Last_Of_Us Family Clan** is mainly conformed by  The_Last_Of_Us clan and The_Last_Of_Us2 clan. Both clans are emerging clans composed by active and engaging players from Colombia. We are war focused but friendly ties valued above all. We have Whatsapp groups where we get in contact with our integrants. Every week we create a "Friendly tournament" which is free. We try to upgrade members to veterans and veterans to coleaders every season taking into account their performance during this one.   
    
clans:
  - name: The_Last_Of_US
    tag: Q8RQ2CJY
  - name: The_Last_Of_Us2
    tag: QVRR90VC
```
