### ISSUE TITLE
[Update]: JonkaWonka's and Vlaamse Duivels

### ISSUE THREAD

**Issue by MelihOzcanPXL** [RoyaleAPI/family-config#1028]
### Family name

JonkaWonka's & vlaamse duivels Family

### Family URL

https://royaleapi.com/clan/family/jonkawonka/clans

### Family configuration

```yaml
name: JonkaWonka's & vlaamse duivels Family
key: jonkawonka
color: yellow
emblem: flag_k_02
info:
  description: >
    The **JonkaWonka's & vlaamse duivels Family**


    Little presentation of our JonkaWonka's & vlaamse duivels Family because it is important that everyone knows our story! And if you ever want to change clans or try something else in agreement with your leaders, that's possible! We are a family of 4 clans!
    Our family fosters an environment where casual and competitive styles of play can both flourish
  social:
    - discord: https://discord.gg/2MGYJEY
clans:
  - name: "JonkaWonka's"
    tag: 82829Y2V
  - name: vlaamse duivels
    tag: PQ229
  - name: "JonkaWonka's 2"
    tag: Q9YC29V8
  - name: Belgium | Elite
    tag: GGLLR8J0
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: JonkaWonka's & vlaamse duivels Family
key: jonkawonka
color: yellow
emblem: flag_k_02
info:
  description: >
    The **JonkaWonka's & vlaamse duivels Family**


    Little presentation of our JonkaWonka's & vlaamse duivels Family because it is important that everyone knows our story! And if you ever want to change clans or try something else in agreement with your leaders, that's possible! We are a family of 4 clans!
    Our family fosters an environment where casual and competitive styles of play can both flourish
  social:
    - discord: https://discord.gg/2MGYJEY
clans:
  - name: "JonkaWonka's"
    tag: 82829Y2V
  - name: vlaamse duivels
    tag: PQ229
  - name: "JonkaWonka's 2"
    tag: Q9YC29V8
  - name: Belgium | Elite
    tag: GGLLR8J0

```
