### ISSUE TITLE
Family config 

### ISSUE THREAD

**Issue by LtsLotus** [RoyaleAPI/family-config#1029]
```yaml
name: StarCommunity
key: Star
color: yellow
emblem: Traditional_Star_04.png
info:
  logo: Traditional_Star_04.png
  description: >
   Star community is one of the oldest and biggest families in Clash Royale
    with our 200 members and 5 clans!
    **Join the Community. Become a Star! **
  social:
    - discord: https://discord.gg/FzpzsYmEKn
    - twitter: https://x.com/LtsLotus?t=rcVaJuthNnMx5RJWArTI4Q&s=09
    - facebook: https://www.facebook.com/dth.lotus.1
clans:
  - name: StarAlliance RO
    tag: PUVY2PUY
  - name: StarAcademy RO
    tag: LLJV20QR
  - name: StarAlliance RO
    tag: QQR2YJUQ
  - name: StarAlliance DX
    tag: GCJC80JP
  - name: StarAcademy RO2
    tag: LQ2VPQGG
```

**Comment by LtsLotus** [comment]
[Group final apk.docx](https://github.com/RoyaleAPI/family-config/files/14437537/Group.final.apk.docx)

**Comment by LtsLotus** [comment]
```yaml
name: StarCommunity
key: Star
color: yellow
emblem: Traditional_Star_04.png
info:
  logo: Traditional_Star_04.png
  description: >
   Star community is one of the oldest and biggest families in Clash Royale
    with our 200 members and 5 clans!
    **Join the Community. Become a Star! **
  social:
    - discord: https://discord.gg/FzpzsYmEKn
    - twitter: https://x.com/LtsLotus?t=rcVaJuthNnMx5RJWArTI4Q&s=09
    - facebook: https://www.facebook.com/dth.lotus.1
clans:
  - name: StarAlliance RO
    tag: PUVY2PUY
  - name: StarAcademy RO
    tag: LLJV20QR
  - name: StarAlliance RO
    tag: QQR2YJUQ
  - name: StarAlliance DX
    tag: GCJC80JP
  - name: StarAcademy RO2
    tag: LQ2VPQGG
…
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: StarCommunity
key: star
color: yellow
emblem: Traditional_Star_04
info:
  description: >
   Star community is one of the oldest and biggest families in Clash Royale
    with our 200 members and 5 clans!
    **Join the Community. Become a Star! **
  social:
    - discord: https://discord.gg/FzpzsYmEKn
    - twitter: https://x.com/LtsLotus
    - facebook: https://www.facebook.com/dth.lotus.1
clans:
  - name: StarAlliance RO
    tag: PUVY2PUY
  - name: StarAcademy RO
    tag: LLJV20QR
  - name: StarAlliance RO
    tag: QQR2YJUQ
  - name: StarAlliance DX
    tag: GCJC80JP
  - name: StarAcademy RO2
    tag: LQ2VPQGG

```
