### ISSUE TITLE
QLASH Family

### ISSUE THREAD

**Issue by matteo16799** [RoyaleAPI/family-config#103]
```yaml
name: QLASH Italian clans 1
key: QLASH1
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:
  - name: QLASH Chaos
    tag: 9U2QUL8U
  - name: QLASH Chaos2
    tag: 922RP8GL
  - name: QLASH Chaos3
    tag: 92QRY8G0
  - name: QLASH Chaos4
    tag: 9QCUPGQP
  - name: QLASH Danger
    tag: 98PL02LC
  - name: QLASH Danger2
    tag: P02LULUR
  - name: QLASH Eclipse
    tag: P0LLG9RG
  - name: QLASH Eclipse2
    tag: 9QRVUQ8Y
  - name: QLASH Eclipse3
    tag: 9vvujlgp
  - name: QLASH Hades
    tag: 9U2UYRQU
  - name: QLASH Hades2
    tag: P08288YG
  - name: QLASH ITLegends
    tag: 9QJURCQ0
  - name: QLASH Itc
    tag: P0C28V0C
  - name: QLASH Itc2
    tag: PLVLLRVP
  - name: QLASH Itc3
    tag: 9UQCLRGV
  - name: QLASH Itc4
    tag: 9CYL929Q
```

**Comment by matteo16799** [comment]
```yaml
name: QLASH Italian clans 2
key: QLASH2
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:

  - name: QLASH Revenge
    tag: PYV0PQYJ
  - name: QLASH Revenge2
    tag: PLU0JJL8
  - name: QLASH Sentry
    tag: 9QY9JG09
  - name: QLASH Sentry2
    tag: 92URLJYG
  - name: QLASH Sentry3
    tag: 99LQJ8GY
  - name: QLASH Sentry4
    tag: 90QVQRCU
  - name: QLASH Sentry5
    tag: 98Y9VRYP
  - name: QLASH Top Clan
    tag: 9989JURU
  - name: QLASH Void
    tag: 9QCVCGQU
  - name: QLASH Void2
    tag: 9QV2P0CR
  - name: QLASH Void3
    tag: 9QVJJ9GJ
  - name: QLASH Superbia
    tag: PLL0QYQP
  - name: QLASH Superbia2
    tag: Y80L82JQ
```

**Comment by matteo16799** [comment]
```yaml
name: QLASH Internationals clans
key: QLASH3
color: Teal
emblem: Flame_04
info:
  logo: http://i66.tinypic.com/14kb4o4.png
  description: >
    **QLASH** is an International Esports Organization. Competitive Pro Teams in: StarCraft2, Clash Royale, Brawlstars, FIFA, Fortnite, Overwatch, Heartstone, League of Legends, CS:GO, Tekken and Call of Duty #WeAreQLASH
  social:
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHcr
    - instagram:  https://www.instagram.com/qlash_clashroyale/
    - discord: http://discord.gg/qlash-clashroyale
    - twitch:  https://www.twitch.tv/QLASH_IT
    - youtube: https://www.youtube.com/channel/UCC4BUTrLaGrcIhSwVhPgMOA
    - website: https://qlash.gg/en

clans:


  - name: QLASH Egypt
    tag: PLJJQ0Y9
  - name: QLASH Egypt II
    tag: plcujrp2
  - name: QLASH Egypt III
    tag: PLCPRPY0
  - name: QLASH Egypt IV
    tag: P0L28C0R
  - name: QLASH Egypt V
    tag: P902VV0J
  - name: QLASH Egypt VI
    tag: PYV2QVGV
  - name: QLASH Egypt VII
    tag: PLC8JJ2G
  - name: QLASH GSD
    tag: 9QJGQ9P2
  - name: QLASH GSD1
    tag: P0J8RGU8
  - name: QLASH GSD2
    tag: 9R8CG2LG
  - name: QLASH GSD3
    tag: 9QJU89RV
  - name: QLASH Trident
    tag: 9L8R8G98
  - name: QLASH Algeria
    tag: YQY2800U
  - name: QLASH Algeria2
    tag: Y9L2PQQY
  - name: QLASH Algeria3
    tag: YGGJQLQQ
  - name: QLASH Shadows
    tag: YYR8LG0P
```
