### ISSUE TITLE
Fig Family

### ISSUE THREAD

**Issue by rehlbot** [RoyaleAPI/family-config#1030]
```yaml
name: Fig Family
key: SOF
color: Purple
emblem: Elixir_02
info:
  logo: https://i.imgur.com/nqIzfaP.png
  description: >
   Fig Family is a group of elite war clans grouped into a strong community with a place for any warrior looking to succeed. From our top clans, Same Ol' Fig & Academy Elite, the family founders, both current top 1% global war clans competing in the highest league, all the way down to bronze league clans and more casual warring clans, we have a place for any player. Whether you are a seasoned veteran looking for a place to compete in the top ranks and play for prizes, or a newbie to clan wars looking to learn the ropes from pros, Fig Family has a place for you! Join our family to experience what Clash Royale clan wars are truly about. 

  social:
    - twitter: 
    - discord: https://discord.gg/pTqJ6vDfBT
    - website: 
clans:
  - name: Same Ol' Fig (SOF)
    tag: 8R002CU9
  - name: Academy Elite (AE)
    tag: 20UYRRQ
  - name: ELITE SC0RPI0NS (ES)
    tag: 8CVP2P0P
  - name: Academy of Fig (AOF)
    tag: GPVL0YJJ
  - name: Same Ol' Elites (SOE)
    tag: QYUP8JRQ
    
    …
```

**Comment by Zaop7** [comment]
> [!NOTE]
> The logo link is unreachable.

> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Fig Family
key: fig
color: Purple
emblem: Elixir_02
info:
  description: >
    Fig Family is a group of elite war clans grouped into a strong community with a place for any warrior looking to succeed. From our top clans, Same Ol' Fig & Academy Elite, the family founders, both current top 1% global war clans competing in the highest league, all the way down to bronze league clans and more casual warring clans, we have a place for any player. Whether you are a seasoned veteran looking for a place to compete in the top ranks and play for prizes, or a newbie to clan wars looking to learn the ropes from pros, Fig Family has a place for you! Join our family to experience what Clash Royale clan wars are truly about.
  social:
    - discord: https://discord.gg/pTqJ6vDfBT
clans:
  - name: Same Ol' Fig (SOF)
    tag: 8R002CU9
  - name: Academy Elite (AE)
    tag: 20UYRRQ
  - name: ELITE SC0RPI0NS (ES)
    tag: 8CVP2P0P
  - name: Academy of Fig (AOF)
    tag: GPVL0YJJ
  - name: Same Ol' Elites (SOE)
    tag: QYUP8JRQ

```
