### ISSUE TITLE
new Family Clan (Flying Pandas)

### ISSUE THREAD

**Issue by Landru1970** [RoyaleAPI/family-config#1032]
```yaml
name: Flying Panda Family
key: panda
color: teal
emblem: YingYang_01
info:
    Die Flying Pandas gib es seit dem Beginn von Clash Royale!
    Wir sind ein reiner CW Clan. Wer CW Pflicht nicht versteht, der ist hier Falsch!
    Die Flying Pandas und Flying Sloths haben eine CW Pflicht.
    Die Fyling Koalas sind der Urlaub- und Chill-Clan.
    **Join the Pandas!!**
social:
      
clans:
  - name: Flying Pandas
    tag: 29LY00Y2
  - name: Flying Sloths
    tag: QC8Y08YJ
  - name: Flying Koalas
    tag: Q9URP9RR

```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Flying Panda Family
key: panda
color: teal
emblem: YingYang_01
info:
  description: >
    Die Flying Pandas gib es seit dem Beginn von Clash Royale!
    Wir sind ein reiner CW Clan. Wer CW Pflicht nicht versteht, der ist hier Falsch!
    Die Flying Pandas und Flying Sloths haben eine CW Pflicht.
    Die Fyling Koalas sind der Urlaub- und Chill-Clan.
    **Join the Pandas!!**

clans:
  - name: Flying Pandas
    tag: 29LY00Y2
  - name: Flying Sloths
    tag: QC8Y08YJ
  - name: Flying Koalas
    tag: Q9URP9RR

```
