### ISSUE TITLE
[Update]: Purjehdus Community

### ISSUE THREAD

**Issue by HexHeikki** [RoyaleAPI/family-config#1033]
### Family name

Purjehdus Community

### Family URL

https://royaleapi.com/clan/family/purjehdus/clans

### Family configuration

```yaml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is a Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus
    **War Clans:** NC Finland, Laivanupotus, hikipaatti
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: NC Finland
  tag: 8LP0Y9YP
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP
```

### Additional Info

Couple of clans removed.

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is a Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus
    **War Clans:** NC Finland, Laivanupotus, hikipaatti
  social:
  - discord: https://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: NC Finland
  tag: 8LP0Y9YP
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP

```
