### ISSUE TITLE
[Update]: 鬼滅の刃 Clan Family

### ISSUE THREAD

**Issue by xShadow12GH** [RoyaleAPI/family-config#1034]
### Family name

鬼滅の刃 Clan Family

### Family URL
https://royaleapi/.com/clan/family/kny/clans

### Family configuration

```yaml
Name: 鬼滅の刃 Clan Family
Key: kny
Color: purple
Emblem: Twin_Peaks_01
Info:
  Logo: /static/img/badge/Twin_Peaks_01.png
  Description: >
    The **鬼滅の刃 Clan Family** (鬼滅の刃CF)
    Is a group of clans dedicated to Kimetsu no Yaiba fans who want a clan family dedicated to it. 
Anyone can join to any of the clans if the rules are followed.
  Social:
    - discord: https://discord.gg/N4jQHYcx
Clans:
-	Name: 鬼滅の刃 | Clan
    Tag: LLUYGCRR
-	Name: 鬼滅の刃 | 竈門 炭治郎
    Tag: LV2C299J
-	Name: 鬼滅の刃 | Lvl 1
    Tag: GP2LYPYG
-	Name: ボット
    Tag: UQCY8P8
-	Name: スーパーセル | Lvl 1
    Tag: L9LJ89VY
```

### Additional Info

https://royaleapi.com/clan/family/kny/clans

**Comment by Zaop7** [comment]
> [!NOTE]
> The logo link is invalid.

> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: 鬼滅の刃 Clan Family
key: kny
color: purple
emblem: Twin_Peaks_01
info:
  description: >
    The **鬼滅の刃 Clan Family** (鬼滅の刃CF)
    Is a group of clans dedicated to Kimetsu no Yaiba’s fans who wants a clan family dedicated to it. 
    Anyone can join to any of the clans if the rules are followed.
  social:
    - discord: https://discord.com/invite/GBZeykPQ
clans:
  - name: 鬼滅の刃 | Clan
    tag: LLUYGCRR
  - name: 鬼滅の刃 | 竈門 炭治郎
    tag: LV2C299J
  - name: 鬼滅の刃 | Lvl 1
    tag: GP2LYPYG
  - name: ボット
    tag: UQCY8P8
  - name: スーパーセル | Lvl 1
    tag: L9LJ89VY

```
