### ISSUE TITLE
Siła i Honor clan

### ISSUE THREAD

**Issue by p4-3l** [RoyaleAPI/family-config#1035]
```yaml
name: Siła i Honor Family
key: sih
color: black
emblem: flag_f_02
info:
  logo: 
  description: >
    PL/ENG **Najlepszy klan wojenny w Polsce**, wszyscy aktywni i ambitni gracze w jednym miejscu! / **The best war clan in Poland**, all active and ambitious players in one place!
  social:
    - twitter: https://twitter.com/sila_i_honor
    - discord: utn.pl/Sih
clans:
  - name: Siła i Honor
    tag: 88GU8GP8
  - name: Siła i Honor 2
    tag: L22UPRQ2
  - name: Siła i Honor 3
    tag: G92802U8
  - name: Siła i Honor 4
    tag: GGP2J0GL
```
![Untitled87_20240319105545.png](https://github.com/RoyaleAPI/family-config/assets/163923247/f5408344-3e54-4aa4-96e6-442e8fcf3e1a)

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Siła i Honor Family
key: sih
color: black
emblem: flag_f_02
info:
  logo: sih.png
  description: >
    PL/ENG **Najlepszy klan wojenny w Polsce**, wszyscy aktywni i ambitni gracze w jednym miejscu! / **The best war clan in Poland**, all active and ambitious players in one place!
  social:
    - twitter: https://twitter.com/sila_i_honor
clans:
  - name: Siła i Honor
    tag: 88GU8GP8
  - name: Siła i Honor 2
    tag: L22UPRQ2
  - name: Siła i Honor 3
    tag: G92802U8
  - name: Siła i Honor 4
    tag: GGP2J0GL

```
