### ISSUE TITLE
[New]: Add new clan

### ISSUE THREAD

**Issue by SzeregowyCieply** [RoyaleAPI/family-config#1037]
### Family configuration

```yaml
name: FightClub PL Team
key: fightclubpl
color: red
emblem: Sword_01
info:
  logo: https://i.imgur.com/iVeP16b.png
  description: >
    **Witaj w naszej rodzinie FightClub.**
    Najlepsza rodzina klanów w polsce
    • **FC1** - Klan stricte ladder, CW bez obligo!
    • **FC2** - Klan uniwersalny, stawiamy na rozwój cw oraz ladder.
    • **FC3** - Klan wojenny, arena bez limitu.
    • **FC4** - Klan feeder możliwość awansu FC1/FC2/FC3.
    • **FC5** - Klan ladder pod rozwój słabszych kony.
  social:
    - twitter: https://twitter.com/FightclubPl
clans:
  - name: FightClub PL 1
    tag: 90UUC92Y
  - name: FightClub PL 2
    tag: 9V8JVVVJ
  - name: FightClub PL 3
    tag: LVQYCUQJ
  - name: FightClub PL 4
    tag: GUP090RR
  - name: FightClub PL 5
    tag: QLJ2Q8UV
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: FightClub PL Team
key: fightclubpl
color: red
emblem: Sword_01
info:
  logo: fightclubpl.png
  description: >
    **Witaj w naszej rodzinie FightClub.**
    Najlepsza rodzina klanów w polsce
    • **FC1** - Klan stricte ladder, CW bez obligo!
    • **FC2** - Klan uniwersalny, stawiamy na rozwój cw oraz ladder.
    • **FC3** - Klan wojenny, arena bez limitu.
    • **FC4** - Klan feeder możliwość awansu FC1/FC2/FC3.
    • **FC5** - Klan ladder pod rozwój słabszych kony.
  social:
    - twitter: https://twitter.com/FightclubPl
clans:
  - name: FightClub PL 1
    tag: 90UUC92Y
  - name: FightClub PL 2
    tag: 9V8JVVVJ
  - name: FightClub PL 3
    tag: LVQYCUQJ
  - name: FightClub PL 4
    tag: GUP090RR
  - name: FightClub PL 5
    tag: QLJ2Q8UV

```
