### ISSUE TITLE
DBZ Family

### ISSUE THREAD

**Issue by Mvsselz** [RoyaleAPI/family-config#1038]
```yaml
name: DBZ Family
key: dbz
color: purple
emblem: Elixir_01
info:
  logo: /static/img/badge/Elixir_01.png
  description: >
    DBZ Family - Home to DBZ Clans - #1 Australia.
    Active & mandatory war clans in DBZ Saiyans, DBZ Genesis, DBZ Mars with Feeder clans.
    Casual clans: DBZ HTC, DBZ Ares, DBZ Phoenix
social:  
  - discord: https://discord.gg/xYcvrvN
clans:
  - name: DBZ Saiyans
    tag: 89YVRV
  - name: DBZ Genesis
    tag: 9CUUPGCC
  - name: DBZ Mars
    tag: Y2C8YLLG
  - name: DBZ Mars II
    tag: GP8G2JRQ
  - name: DBZ Mars III
    tag: R209GYCV
  - name: DBZ Mars IV
    tag: GV0RLV8P
  - name: DBZ HTC
    tag: Q29UJ0Y
  - name: DBZ Phoenix
    tag: PRCQQQYQ
  - name: DBZ Omega
    tag: LYC9YC2U
  - name: DBZ Ares
    tag: 9V0URJR9
  - name: DBZ Shadow
    tag: Y2UC0YLL
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: DBZ Family
key: dbz
color: purple
emblem: Elixir_01
info:
  logo: /static/img/badge/Elixir_01.png
  description: >
    DBZ Family - Home to DBZ Clans - #1 Australia.
    Active & mandatory war clans in DBZ Saiyans, DBZ Genesis, DBZ Mars with Feeder clans.
    Casual clans: DBZ HTC, DBZ Ares, DBZ Phoenix
  social:
  - discord: https://discord.gg/xYcvrvN
clans:
  - name: DBZ Saiyans
    tag: 89YVRV
  - name: DBZ Genesis
    tag: 9CUUPGCC
  - name: DBZ Mars
    tag: Y2C8YLLG
  - name: DBZ Mars II
    tag: GP8G2JRQ
  - name: DBZ Mars III
    tag: R209GYCV
  - name: DBZ Mars IV
    tag: GV0RLV8P
  - name: DBZ HTC
    tag: Q29UJ0Y
  - name: DBZ Phoenix
    tag: PRCQQQYQ
  - name: DBZ Omega
    tag: LYC9YC2U
  - name: DBZ Ares
    tag: 9V0URJR9
  - name: DBZ Shadow
    tag: Y2UC0YLL

```
