### ISSUE TITLE
Vanguard clan family list on Royale API site update

### ISSUE THREAD

**Issue by Quentinw9281** [RoyaleAPI/family-config#104]
### Idea/request:
  1. Hey, Quentin here speaking and I am speaking on behalf of Vanguard regarding some old data on the family clans page of Vanguard on the Royale API site. 

### Request Details:

Since our data on clans has not been updated since forever. 
I would like to update it now. Here by you can take he following clans off the site: Vanguard NL (#99LRCLR0), Vanguard Rogue (#9QG8QUC8), Vanguard Team (#8YQ8UCGV), Vanguard™ Agoge (#9QU8QVYQ) and Vanguard Light (#920YJ20P). 
Also add the following clan "Vanguard PUB (#9UCJUCP0)" to the clanslist. Thank you in advance already!

**Comment by smlbiobot** [comment]
I have moved your issue to the correct repo. What you need to do is edit and update this configuration file:

```yml
name: Vanguard Family
key: vanguard
color: violet
emblem: flag_n_04
sort: trophy
info:
  logo: /static/img/brands/logo/vanguard.png
  description: >
    **Vanguard™** is a grass roots organization. We are striving to compete with the best on a daily basis, with heavy emphasis in esports we provide a environment for players to learn, laugh and compete at all levels for the casual players and the pros. Please join us at *discord.io/vanguardteam* to apply for a clan or tryout for a team.
  social:
    - discord: http://discord.gg/vanguardteam
    - website: https://vanguardesports.org/
    - twitter: https://twitter.com/VanguardTeamCR
    - twitch: https://twitch.tv/ohryantv
    - youtube: https://www.youtube.com/GamingwithNeph
clans:
  - name: Vanguard Team
    tag: 8YQ8UCGV
  - name: Vanguard™ Alpha
    tag: 9RQ2UPRG
  - name: Vanguard™ Light
    tag: 920YJ20P
  - name: Vanguard™ Chaos
    tag: 9UP8RPGG
  - name: Vanguard Matrix
    tag: 9UVCLLUG
  - name: Vanguard™ Void
    tag: 9VQL8YCU
  - name: Vanguard™ Dawn
    tag: 9JYPP0UC
  - name: Vanguard™️ NL
    tag: 99LRCLR0
  - name: Vanguard™️ Dark
    tag: 982V2GRL
  - name: Vanguard™ Agoge
    tag: 9QU8QVYQ
  - name: Vanguard Plasma
    tag: 9UCG0RU9
  - name: Vanguard™️ Dusk
    tag: 9JLP9C20
  - name: Vanguard Voodoo
    tag: PY98LY0J
  - name: Vanguard Rogue
    tag: 9QG8QUC8
```

You can post to this thread if you want.
