### ISSUE TITLE
[New]: ARMATA ROZZA family

### ISSUE THREAD

**Issue by velenrodriguez** [RoyaleAPI/family-config#1040]
### Family configuration

```yaml
name: ARMATA ROZZA FAM
key: armata rozza
color: purple
emblem: moon_03
info:
  logo: "C:\Users\NTB HP\Desktop\AR LOGO.jpg"
  description: >
  ROZZI SINCE 2019, grande famiglia italiana di clan war. 
  Il rozzume non si crea, il rozzume non si distrugge,
  il rozzume si trasforma. 

clans:
  - name: ARMATA ROZZA
    tag: P2UQP9CJ
  - name: CE MAGNAMM
    tag: L08VGUJ9
  - name: I Tori Feroci
    tag: YC89P002
  - name: DOG RIDER
    tag: RP889JU
  - name: PesciolinoRozzo
    tag: LQCPJLC0
  - name: The Emperors
    tag: 2JU8G2
  - name: BabyRozza
    tag: QCQPJ90R
  - name: mini bombarolo
    tag: PJG0R00
  - name: BRIGATA ROZZA TM
    tag: Q8G2QR2P
  - name: PelleRozza TM
    tag: QPPYLVGV
  - name: AllenaRozzi TM
    tag: QQYPUJY2Y
  - name: GuLAg rOzZo TM
    tag: R0GPY22L
  - name: GhEttO RoZzO TM
    tag: QYYRRJP2
  - name: Approdo Rozzo TM
    tag: GURVCVCU
  - name: TaSSoRoZZo TM
    tag: GUR8QRY2
  - name: TerraDiRozzo TM
    tag: QGU8P2YL
```

**Comment by Zaop7** [comment]
> [!NOTE]
> The logo link is invalid. Please post image here as an attachment.

**Comment by velenrodriguez** [comment]
![AR LOGO](https://github.com/RoyaleAPI/family-config/assets/166223593/2165fab7-497a-4607-9966-a2effa74bba3)

**Comment by velenrodriguez** [comment]
please update

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: ARMATA ROZZA FAM
key: armata-rozza
color: purple
emblem: Moon_03
info:
  logo: "armata-rozza.png"
  description: >
    ROZZI SINCE 2019, grande famiglia italiana di clan war. 
    Il rozzume non si crea, il rozzume non si distrugge,
    il rozzume si trasforma.
clans:
  - name: ARMATA ROZZA
    tag: P2UQP9CJ
  - name: CE MAGNAMM
    tag: L08VGUJ9
  - name: I Tori Feroci
    tag: YC89P002
  - name: DOG RIDER
    tag: RP889JU
  - name: PesciolinoRozzo
    tag: LQCPJLC0
  - name: The Emperors
    tag: 2JU8G2
  - name: BabyRozza
    tag: QCQPJ90R
  - name: mini bombarolo
    tag: PJG0R00
  - name: BRIGATA ROZZA TM
    tag: Q8G2QR2P
  - name: PelleRozza TM
    tag: QPPYLVGV
  - name: AllenaRozzi TM
    tag: QQYPUJY2Y
  - name: GuLAg rOzZo TM
    tag: R0GPY22L
  - name: GhEttO RoZzO TM
    tag: QYYRRJP2
  - name: Approdo Rozzo TM
    tag: GURVCVCU
  - name: TaSSoRoZZo TM
    tag: GUR8QRY2
  - name: TerraDiRozzo TM
    tag: QGU8P2YL
```
cani-rozzi family deleted
