### ISSUE TITLE
[New]: Elite Energies

### ISSUE THREAD

**Issue by Cami0so** [RoyaleAPI/family-config#1043]
### Family configuration

```yaml
name: Elite Energies
key: eliteenergies
color: purple
emblem: Star_Shine_03
info:
  description: >
    The Elite Energies clan is an up-and-coming war giant with the family only acting as security, 
    not expansion. War focused. Join us on this path to glory!
  social:
    - instagram: https://www.instagram.com/elitecrclans
clans:
  - name: Elite Energies
    tag: LQPLRR2G
  - name: EEn Bench
    tag: QRJY2Q9J
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Elite Energies
key: eliteenergies
color: purple
emblem: Star_Shine_03
info:
  description: >
    The Elite Energies clan is an up-and-coming war giant with the family only acting as security, 
    not expansion. War focused. Join us on this path to glory!
  social:
    - instagram: https://www.instagram.com/elitecrclans
clans:
  - name: Elite Energies
    tag: LQPLRR2G
  - name: EEn Bench
    tag: QRJY2Q9J

```
