### ISSUE TITLE
[Update]: PressPinpinte Family

### ISSUE THREAD

**Issue by Merluchon** [RoyaleAPI/family-config#1044]
### Family name

PressPinpinte

### Family URL

https://royaleapi.com/clan/family/presspinpinte/clans

### Family configuration

```yaml
name: PressPinpinte
key: ppt
color: red
emblem: A_Char_Pekka_02
info:
  logo: https://i.ibb.co/wJWKRk8/press3.png
  description: >
  La **Presspinpinte** est une communauté familiale. Composés de 9 clans, ceux-ci ont différents objectifs. La Pression, FrenchBlood, PerlinPinpinte et les Spartiates sont axés Guerres de Clans. RushPinpinte est notre clan ladder. PinpinteAcademy et BabyPinpinte sont nos clans école. ChillPinpinte est notre clan repos. Nous organisons un tournoi interclans chaque mois ainsi que de nombreux autres évènements ! Les meilleurs guerriers sont récompensés en goodies et pass Clash Royale. Rejoignez-nous vite sur Discord ! https://discord.gg/g4d5p9zSP4
  social:
    - discord: https://discord.gg/g4d5p9zSP4
    - website: https://la-presspinpinte.hubside.fr/
    - instagram: https://www.instagram.com/presspinpinte_clash/
    - facebook: https://www.facebook.com/dylan.presspinpinte
    - twitch: https://www.twitch.tv/presspinpinte
    - youtube: https://www.youtube.com/channel/UCTSlG4PNy7v_nA57d1A75Pw
    - tiktok: https://www.tiktok.com/@presspinpintecr
clans:
  - name: la PRESSION
    tag: 9VL9L9YQ
  - name: FrenchBlood
    tag: 9VJ0J9
  - name: perlinpinpinte
    tag: P2RUP90G
  - name: Les spartiates
    tag: YL2GJ9PY
  - name: Spartoo
    tag: R88J8PYL
  - name: PinpinteAcademy
    tag: QG20999U
  - name: BabyPinpinte
    tag: G0UR08JY
  - name: RushPinpinte
    tag: L82YYGCU
  - name: Chillpinpinte
    tag: LGVJU0RY
```

**Comment by Cami0so** [comment]
Bro isn't this taking forever? I did mine a day before you

**Comment by Merluchon** [comment]
> Bro isn't this taking forever? I did mine a day before you

that's insane...

**Comment by Merluchon** [comment]
> > Bro isn't this taking forever? I did mine a day before you
> 
> that's insane...

I know they were hiring guys to update families a few months ago, I wanted to help but no answers... Let's hope we won't have to modify our families clans just after they apply these changes.

**Comment by Cami0so** [comment]
> > > Bro isn't this taking forever? I did mine a day before you
> > 
> > 
> > that's insane...
> 
> I know they were hiring guys to update families a few months ago, I wanted to help but no answers... Let's hope we won't have to modify our families clans just after they apply these changes.

Yeah that really is the main fear. If it gets to a year I'll probably make an ironic birthday post for it on Reddit, hopefully then it'll get traction. It probably won't

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: PressPinpinte
key: presspinpinte
color: red
emblem: A_Char_Pekka_02
info:
  logo: presspinpinte.png
  description: >
    La **Presspinpinte** est une communauté familiale. Composés de 9 clans, ceux-ci ont différents objectifs. La Pression, FrenchBlood, PerlinPinpinte et les Spartiates sont axés Guerres de Clans. RushPinpinte est notre clan ladder. PinpinteAcademy et BabyPinpinte sont nos clans école. ChillPinpinte est notre clan repos. Nous organisons un tournoi interclans chaque mois ainsi que de nombreux autres évènements ! Les meilleurs guerriers sont récompensés en goodies et pass Clash Royale. Rejoignez-nous vite sur Discord ! https://discord.gg/g4d5p9zSP4
  social:
    - discord: https://discord.gg/g4d5p9zSP4
    - website: https://la-presspinpinte.hubside.fr/
    - instagram: https://www.instagram.com/presspinpinte_clash/
    - facebook: https://www.facebook.com/dylan.presspinpinte
    - twitch: https://www.twitch.tv/presspinpinte
    - youtube: https://www.youtube.com/channel/UCTSlG4PNy7v_nA57d1A75Pw
    - tiktok: https://www.tiktok.com/@presspinpintecr
clans:
  - name: la PRESSION
    tag: 9VL9L9YQ
  - name: FrenchBlood
    tag: 9VJ0J9
  - name: perlinpinpinte
    tag: P2RUP90G
  - name: Les spartiates
    tag: YL2GJ9PY
  - name: Spartoo
    tag: R88J8PYL
  - name: PinpinteAcademy
    tag: QG20999U
  - name: BabyPinpinte
    tag: G0UR08JY
  - name: RushPinpinte
    tag: L82YYGCU
  - name: Chillpinpinte
    tag: LGVJU0RY

```
