### ISSUE TITLE
[NEW] War Thieves Family

### ISSUE THREAD

**Issue by s4mik** [RoyaleAPI/family-config#1045]
```yaml
name: War Thieves Family
key royaleapi.com/clan/PVC8PU
color: green
emblem: Lotus_01
info:
  logo: -
  description: >
The War Thieves family is the strongest CW family in CIS region, which is home to 4 clans and 150 members! Since creation 4 years ago, we as a family and individual players have grown immensely and continue conquering new heights to this day!
We proudly became a home to lots of professional players, while also welcoming players from all around the globe. Join our ranks to conquer the leaderboards together!
  social:
    - discord: https://discord.com/invite/RFbyB6Wc4N
    - telegram https://t.me/WarThievesFamily
clans:
  - name: War Thieves
    tag: #PVC8PU
  - name: Sunrise
    tag: #YRP22G0V
  - name: Lost Heaven
    tag: #QUYC0GR0
  - name: ŠŦŖÃŇĠĘ ĖMĘŘÅŁĐ
    tag: #QJGRVYG8
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: War Thieves Family
key: war-thieves
color: green
emblem: Lotus_01
info:
  description: >
    The War Thieves family is the strongest CW family in CIS region, which is home to 4 clans and 150 members! Since creation 4 years ago, we as a family and individual players have grown immensely and continue conquering new heights to this day!
    We proudly became a home to lots of professional players, while also welcoming players from all around the globe. Join our ranks to conquer the leaderboards together!
  social:
    - discord: https://discord.com/invite/RFbyB6Wc4N
    - telegram: https://t.me/WarThievesFamily
clans:
  - name: War Thieves
    tag: PVC8PU
  - name: Sunrise
    tag: YRP22G0V
  - name: Lost Heaven
    tag: QUYC0GR0
  - name: ŠŦŖÃŇĠĘ ĖMĘŘÅŁĐ
    tag: QJGRVYG8

```
