### ISSUE TITLE
New clan family

### ISSUE THREAD

**Issue by kaiserjh23** [RoyaleAPI/family-config#1047]
```yaml
name: Fig Fam
key: figfam
color: purple
emblem: Elixir_02
sort: trophy
  social:
    - discord: tinyurl.com/figfam
clans:
  - name: Same Ol’ Fig
    tag: 8R002CU9
  - name: Academy Elite
    tag: 20UYRRQ
  - name: ELITE SC0PRI0NS
    tag: 8CVP2P0P
  - name: Academy of Fig
    tag: GPVL0YJJ
  - name: Same Ol’ Elites
    tag: QYUP8JRQ
  - name: Academy Elite 2
    tag: GUCRPLRY
  - name: Academy Elite 3
    tag: QL0QUCRC
…
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Fig Fam
key: fig
color: purple
emblem: Elixir_02
info:
  social:
    - discord: https://discord.gg/pTqJ6vDfBT
clans:
  - name: Same Ol’ Fig
    tag: 8R002CU9
  - name: Academy Elite
    tag: 20UYRRQ
  - name: ELITE SC0PRI0NS
    tag: 8CVP2P0P
  - name: Academy of Fig
    tag: GPVL0YJJ
  - name: Same Ol’ Elites
    tag: QYUP8JRQ
  - name: Academy Elite 2
    tag: GUCRPLRY
  - name: Academy Elite 3
    tag: QL0QUCRC
sort: trophy

```
