### ISSUE TITLE
[New]: !Baked! Family of Clans

### ISSUE THREAD

**Issue by Bull0715** [RoyaleAPI/family-config#1049]
### Family configuration

```yaml
name: !Baked! Family of Clans
key: !baked!
color: olive
emblem: Skull_06
info:
 logo: https://cablehouse.net/!Baked!.png
 description:
War clan family that is solely focused on war.  We strive to offer a fun, competitive, toxic free environment. As you travel through the clans, you'll find different stages of difficulties If you need a relaxing war clan, we have that too.  All clans are run with similar mindsets so what you come to love in one clan, you'll find in all of our clans and each will feel like home.

social:
 - discord: https://discord.gg/tGJRuxaCgB

clans:
  - name: !Baked! 2.0
    tag: YRVC9QVJ
  - name: !Baked! 1.5
    tag: LUCQVPRV
  - name: !Baked! 2.5
    tag: G9LRRP82
  - name: !Baked! 1.0
    tag: GURCRRY9
```

**Comment by Bull0715** [comment]
Is there anything else I need to do?

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Baked Family of Clans
key: baked
color: olive
emblem: Skull_06
info:
  description:
    War clan family that is solely focused on war.  We strive to offer a fun, competitive, toxic free environment. As you travel through the clans, you'll find different stages of difficulties If you need a relaxing war clan, we have that too.  All clans are run with similar mindsets so what you come to love in one clan, you'll find in all of our clans and each will feel like home.
  social:
    - discord: https://discord.gg/tGJRuxaCgB
clans:
  - name: "!Baked! 2.0"
    tag: YRVC9QVJ
  - name: "!Baked! 1.5"
    tag: LUCQVPRV
  - name: "!Baked! 2.5"
    tag: G9LRRP82
  - name: "!Baked! 1.0"
    tag: GURCRRY9

```
