### ISSUE TITLE
HANOI HUNTER FAMILY CLAN

### ISSUE THREAD

**Issue by andaden** [RoyaleAPI/family-config#105]
```yaml
name: HA NOI HUNTER Family
key: hanoihunter
color: green
emblem: Traditional_Star_04
info:
  logo: https://scontent.fdad3-1.fna.fbcdn.net/v/t1.0-9/19989353_1731957683485836_6198706880160565150_n.jpg?_nc_cat=110&_nc_oc=AQmrGVZV5eTnwdUNXQptE7la5J-0bE31F5MX371UYTbnDjLC1Gc-aQq-n8ItMe_rzF2Wtie6fzOKygZtZO274kgH&_nc_ht=scontent.fdad3-1.fna&oh=d8a2c96de7355dc9c0c96b231261ff1e&oe=5DA398CE
  description: >
    Cộng đồng CR vui vẻ,tâm huyết. Of hàng tháng,tour hàng tuần top1 500 gem. K đủ yêu cầu rq HNH 2 and 3. FB:Hanoi Hunter
  social:
    - facebook: https://www.facebook.com/groups/1400098776732915
    - discord: https://discord.royaleapi.com
    - website: https://fam.royaleapi.com
clans:
  - name: HA NOI HUNTER
    tag: 2JVLQ2U8
  - name: HA NOI HUNTER 2
    tag: 2JVLQ2U8
  - name: HA NOI HUNTER 3
    tag: YJ0GC0VC
```
