### ISSUE TITLE
[New]: Royal Legends Family

### ISSUE THREAD

**Issue by Ika2508** [RoyaleAPI/family-config#1050]
### Family configuration

```yaml
name: Royal Legends Family
key: royallegends
color: red
emblem: Crown_04
sort: trophy
info:
  logo: https://clashvania.de/wp-content/uploads/2024/03/royal_legends_logo_transparent.png

  description: >
Herzlich willkommen in der Royal Legends Family – dem ultimativen Zuhause für Clash Royale-Enthusiasten! Egal, ob du ein erfahrener Spieler oder gerade erst in die Welt des Spiels eingetaucht bist, hier findest du Gleichgesinnte, spannende Diskussionen und jede Menge Unterstützung. Wir sind nicht nur eine Clan-Gemeinschaft, sondern eine Familie von Clash Royale-Spielern, die sich gegenseitig inspirieren und unterstützen. Unsere breite Palette von Clans bietet für jedes Level und jede Spielweise das passende Zuhause. Egal, ob du nach einer entspannten Atmosphäre oder intensiven Clan-Kriegen suchst, hier wirst du fündig!

  social:
    - discord: https://discord.gg/EdY9uEdJ
    - TikTok: https://www.tiktok.com/@royale_legends?_t=8qc3pIbKN8a&_r=1
    - Instagram: https://www.instagram.com/royal.legends_family?igsh=aXdrZThhYnA4cGZy
    
clans:
  - name: die aktiven
    tag: PV82JJYQ
  - name: gelber blitz
    tag: QCPCJ9Y0
  - name: Liebe Freunde
    tag: 82JQVVQQ
  - name: die aktiven 2
    tag: LVPPYPQP
  - name: die aktiven 3
     tag: R02CP0PR
  - name: die aktiven 50
    tag: Q8RVYJ2G
  - name: Penta Force
    tag: YCGY8JG9
  - name: DieUntauglichen
    tag: RPGY98UQ


### Additional Info

die aktiven , #Liebe Freunde, gelber Blitz are no longer part of the Alpenkommando Family, can you please Remove us.
Thx & Best Regards
RL Ika00

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Royal Legends Family
key: royallegends
color: red
emblem: Crown_04
sort: trophy
info:
  logo: royallegends.png
  description: >
    Herzlich willkommen in der Royal Legends Family – dem ultimativen Zuhause für Clash Royale-Enthusiasten! Egal, ob du ein erfahrener Spieler oder gerade erst in die Welt des Spiels eingetaucht bist, hier findest du Gleichgesinnte, spannende Diskussionen und jede Menge Unterstützung. Wir sind nicht nur eine Clan-Gemeinschaft, sondern eine Familie von Clash Royale-Spielern, die sich gegenseitig inspirieren und unterstützen. Unsere breite Palette von Clans bietet für jedes Level und jede Spielweise das passende Zuhause. Egal, ob du nach einer entspannten Atmosphäre oder intensiven Clan-Kriegen suchst, hier wirst du fündig!
  social:
    - discord: https://discord.gg/EdY9uEdJ
    - tiktok: https://www.tiktok.com/@royale_legends
    - instagram: https://www.instagram.com/royal.legends_family
  
clans:
  - name: die aktiven
    tag: PV82JJYQ
  - name: gelber blitz
    tag: QCPCJ9Y0
  - name: Liebe Freunde
    tag: 82JQVVQQ
  - name: die aktiven 2
    tag: LVPPYPQP
  - name: die aktiven 3
    tag: R02CP0PR
  - name: die aktiven 50
    tag: Q8RVYJ2G
  - name: Penta Force
    tag: YCGY8JG9
  - name: DieUntauglichen
    tag: RPGY98UQ

```
