### ISSUE TITLE
Family Congo

### ISSUE THREAD

**Issue by Charlieluna717** [RoyaleAPI/family-config#1053]
```yaml
name: Overlord family
key: Overird
color: red
emblem: A_Char_Rocket_02
…
```
