### ISSUE TITLE
Overlord family

### ISSUE THREAD

**Issue by Charlieluna717** [RoyaleAPI/family-config#1054]
```yaml
name: Overlord family
key: overlord 
color: red
emblem: Cherry_Blossom_01
sort: trophy
info:
  logo: https://media.discordapp.net/attachments/1224110910818484274/1229162758663307275/image.png?ex=6641cbc6&is=66407a46&hm=1c5818e65ad80a26def140a2c8fcf7af113ab01c473a31a3706e864f92440fba&
  description: >
 Looking for war machines only
  social:
    - discord: https://discord.gg/PRKjjfQe5a
    Clans:
  - name: Overlord
    tag: L2LJ22JR
  - name: Champions 3.0
    tag: 28UVG00Y
  - name: Fighting illni
    tag: LGL0GV8L
  - name: M commando
    tag: LLU2PCV2
```

**Comment by Zaop7** [comment]
> [!note]
> Please format your request as yaml file and attach it as an code in your request. Also make sure to follow the given structure. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from closed issues.

**Comment by smlbiobot** [comment]
Logo is no longer available - otherwise, added. 

http://royaleapi.com/f/overlord

```yaml
name: Overlord family
key: overlord
color: red
emblem: Cherry_Blossom_01
sort: trophy
info:
  description: >
    Looking for war machines only
  social:
    - discord: https://discord.gg/PRKjjfQe5a
clans:
- name: Overlord
  tag: L2LJ22JR
- name: Champions 3.0
  tag: 28UVG00Y
- name: Fighting illni
  tag: LGL0GV8L
- name: M commando
  tag: LLU2PCV2
```
