### ISSUE TITLE
Big Igloo Empire

### ISSUE THREAD

**Issue by Edgified** [RoyaleAPI/family-config#1055]
```yaml
name: Big Igloo Empire
key: bigigloo
color: blue
emblem: Freeze_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    The **Big Igloo Empire** is a clan founded by Tsar. The clan family is home to 10 clans, Big Igloo-Big Igloo X. We have many highly ranked players, and are ranked top 100 locally in Australia/U.S.
  social:
    - discord: https://discord.gg/ZhwEU9EfeN
clans:
  - name: Big Igloo
    tag: YY0YU92V
  - name: Big Igloo II
    tag: LCCPV2LG
  - name: Big Igloo III
    tag: L90V2L9G
  - name: Big Igloo IV
    tag: R0Q0VG2P
  - name: Big Igloo V
    tag: Q8VLR9JV
  - name: Big Igloo VI
    tag: G2YYYPRC
  - name: Big Igloo VII
    tag: R2L9GU22
  - name: Big Igloo VIII
    tag: QQ29RLU9
  - name: Big Igloo IX
    tag: QQUY920L
  - name: Big Igloo X
    tag: QQYJJYVC
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Big Igloo Empire
key: big-igloo
color: blue
emblem: Freeze_01
info:
  description: >
    The **Big Igloo Empire** is a clan founded by Tsar. The clan family is home to 10 clans, Big Igloo-Big Igloo X. We have many highly ranked players, and are ranked top 100 locally in Australia/U.S.
  social:
    - discord: https://discord.gg/ZhwEU9EfeN
clans:
  - name: Big Igloo
    tag: YY0YU92V
  - name: Big Igloo II
    tag: LCCPV2LG
  - name: Big Igloo III
    tag: L90V2L9G
  - name: Big Igloo IV
    tag: R0Q0VG2P
  - name: Big Igloo V
    tag: Q8VLR9JV
  - name: Big Igloo VI
    tag: G2YYYPRC
  - name: Big Igloo VII
    tag: R2L9GU22
  - name: Big Igloo VIII
    tag: QQ29RLU9
  - name: Big Igloo IX
    tag: QQUY920L
  - name: Big Igloo X
    tag: QQYJJYVC

```
