### ISSUE TITLE
The Garry Empire

### ISSUE THREAD

**Issue by OrangeNinja623** [RoyaleAPI/family-config#1056]
### Family configuration

```yaml
name: The Garry Empire
key: garry
color: orange
emblem: Fugi_01
info: 
description: >
🗻 The Vast Empire of Garryman. We are united in one simple goal; To win every war. Join and become part of an elite army dedicated to climbing the ranks of the global leaderboard. Apply on our discord. And remember “Only the Strongest Survive.” 🗻
social: 
- discord: https://discord.gg/KwXWUQycR3
clans: 
- name: Garry Empire
tag: LLGPQ2GR
- name: Garry Empire II
tag: Q8G02JCJ
- name: BWABlueDreamin
tag: YP0C922J
- name: Funyun's Cove
tag: GCPQUGVL
- name: xtremeteam
tag: 2P2JL8LP

…
```
