### ISSUE TITLE
[Update]: Trêfle Family

### ISSUE THREAD

**Issue by mecuoh** [RoyaleAPI/family-config#1057]
### Family name

Trêfle Family

### Family URL

https://royaleapi.com/clan/family/trefle/clans

### Family configuration

```yaml
name: Trêfle Family
key: tf
color: green
emblem: Clover_01
info:
  logo: https://media.discordapp.net/attachments/1151172977145155715/1243279772264566894/TREFLE_FAMILY_LOGO-4-2.png?ex=6650e604&is=664f9484&hm=05b05f1695621a9d618db85050aecd5c02bb45b3474ed44b982558366f124ad6&=&format=webp&quality=lossless
  description: >
    La **Trêfle Family** (TF) est un groupe de 7 clans connu pour combiner une ambiance familiale avec 
    une gestion sérieuse. Aucune hiérarchie entre les clans, chacun sa spécialité: vous trouverez 
    forcément votre bonheur !
  social:
    - twitter: https://x.com/FamilyTrefle
    - discord:https://discord.com/invite/kqCcmvb5c6
clans:
  - name: Roi de Trêfle
    tag: 20R0LGYC
  - name: Dame de Trêfle
    tag: YGP9P2Y0
  - name: Trêfle Academy
    tag: Y0C9P9RU
  - name: Valet de Trêfle
    tag: LLLJJ9PC
  - name: As de Trêfle
    tag: R92P020J
  - name: Trêfle Apéro☘️
    tag: LVQLVV08
  - name: TF Brownie
    tag: QUPY8GP9
```

**Comment by karol-clash** [comment]
Hello, I'm a new family-config collaborator. Your yaml seems valid, but it looks like the image has been deleted or moved by the discord. Can you send a new URL or upload the logo directly here?

**Comment by mecuoh** [comment]
@karol-clash 

<img width="573" height="573" alt="Image" src="https://github.com/user-attachments/assets/75d3d6ae-cdf2-466d-a344-96fd206b3eb7" />

**Comment by karol-clash** [comment]
Your family config has been updated. 
```yaml
name: Trêfle Family
key: trefle
color: green
emblem: Clover_01
info:
  logo: /static/img/brands/logo/trefle.png

  description: >
    La **Trêfle Family** (TF) est un groupe de 7 clans connu pour combiner une ambiance familiale avec 
    une gestion sérieuse. Aucune hiérarchie entre les clans, chacun sa spécialité: vous trouverez 
    forcément votre bonheur !
  social:
  - twitter: https://x.com/FamilyTrefle
  - discord: https://discord.com/invite/kqCcmvb5c6
clans:
- name: Roi de Trêfle
  tag: 20R0LGYC
- name: Dame de Trêfle
  tag: YGP9P2Y0
- name: Trêfle Academy
  tag: Y0C9P9RU
- name: Valet de Trêfle
  tag: LLLJJ9PC
- name: As de Trêfle
  tag: R92P020J
- name: Trêfle Apéro☘️
  tag: LVQLVV08
- name: TF Brownie
  tag: QUPY8GP9
```

It might take about an hour before the changes will go live
