### ISSUE TITLE
Blizzard Family

### ISSUE THREAD

**Issue by kooperblizzard** [RoyaleAPI/family-config#1059]
name: Blizzard Family
key: Blizzard
color: blue
emblem: Freeze_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    The Blizzard Family was originally known as the Blizzard Beasts Clan. We are home to dedicated and passionate players who strive for excellence in every game. Our family fosters an environment where both casual and competitive styles of play can thrive.
Blizzard Beasts: This is our primary clan where we expect high levels of activity and commitment. Every member is required to participate in every clan war and use all their attacks. We aim to constantly improve and achieve victories together. Teamwork and dedication are the keys to our success.
Blizzard Jr: Our second clan offers a more relaxed atmosphere for players who prefer a slower pace. Here, it's perfectly fine to take a break or go on vacation for up to two weeks without needing to play. Blizzard Jr is ideal for members who want to enjoy the game without the pressure of constant activity.
Whether you choose to join Blizzard Beasts or Blizzard Jr, you'll be part of a great community that supports each other and helps everyone get the most out of the game. Join us and become a part of the Blizzard Family!
clans:
  - name: Blizzard Beasts
    tag: 9QYRUGPY
  - name: Blizzard Jr
    tag: QJQ9V2U8
    
    ![Blizzard Beasts](https://github.com/RoyaleAPI/family-config/assets/157121538/08207328-5dbd-470a-8001-1deb71344f25)

**Comment by Zaop7** [comment]
> [!note]
> Please format your request as yaml file and attach it as an code in your request. Also make sure to follow the given structure. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from closed issues.

**Comment by smlbiobot** [comment]
btw this is not a format issue if you hit edit and grab it…

```yaml
name: Blizzard Family
key: Blizzard
color: blue
emblem: Freeze_01
info:
  description: >
    The Blizzard Family was originally known as the Blizzard Beasts Clan. We are home to dedicated and passionate players who strive for excellence in every game. Our family fosters an environment where both casual and competitive styles of play can thrive.
Blizzard Beasts: This is our primary clan where we expect high levels of activity and commitment. Every member is required to participate in every clan war and use all their attacks. We aim to constantly improve and achieve victories together. Teamwork and dedication are the keys to our success.
Blizzard Jr: Our second clan offers a more relaxed atmosphere for players who prefer a slower pace. Here, it's perfectly fine to take a break or go on vacation for up to two weeks without needing to play. Blizzard Jr is ideal for members who want to enjoy the game without the pressure of constant activity.
Whether you choose to join Blizzard Beasts or Blizzard Jr, you'll be part of a great community that supports each other and helps everyone get the most out of the game. Join us and become a part of the Blizzard Family!
clans:
  - name: Blizzard Beasts
    tag: 9QYRUGPY
  - name: Blizzard Jr
    tag: QJQ9V2U8

```

**Comment by smlbiobot** [comment]
This logo is highly questionable and we can’t accept it: https://github.com/RoyaleAPI/family-config/assets/157121538/08207328-5dbd-470a-8001-1deb71344f25

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/blizzard

Can’t use your provided image as logo. If you want to use an actual logo, upload a logo that is not an ad image.

```yaml
name: Blizzard Family
key: blizzard
color: blue
emblem: Freeze_01
info:
  description: >
    The Blizzard Family was originally known as the Blizzard Beasts Clan. We are home to dedicated and passionate players who strive for excellence in every game. Our family fosters an environment where both casual and competitive styles of play can thrive.
    
    
    - Blizzard Beasts: This is our primary clan where we expect high levels of activity and commitment. Every member is required to participate in every clan war and use all their attacks. We aim to constantly improve and achieve victories together. Teamwork and dedication are the keys to our success.
    
    
    - Blizzard Jr: Our second clan offers a more relaxed atmosphere for players who prefer a slower pace. Here, it's perfectly fine to take a break or go on vacation for up to two weeks without needing to play. Blizzard Jr is ideal for members who want to enjoy the game without the pressure of constant activity.
    
    
    Whether you choose to join Blizzard Beasts or Blizzard Jr, you'll be part of a great community that supports each other and helps everyone get the most out of the game. Join us and become a part of the Blizzard Family!
clans:
  - name: Blizzard Beasts
    tag: 9QYRUGPY
  - name: Blizzard Jr
    tag: QJQ9V2U8
```
