### ISSUE TITLE
[Update]: Bitons family clan

### ISSUE THREAD

**Issue by yossikatan** [RoyaleAPI/family-config#1061]
### Family name

Bitons family clan

### Family URL

https://royaleapi.com/clan/family/bitons/clans

### Family configuration

```yaml
name: Bitons Family
key: bitons
color: blue
emblem: Fugi_03
info:
  logo: https://ibb.co/MfTyGfH
  description: >
   Welcome to the family  clans of the biton's and the leading family's clan in Israel .
   we are  group of eight clans whose primary focus is war domination. our moto is be humen before trophies , we are preforming 
   tournaments for pass royals all over the year, each clan has whatsApp group and we are working as one hand to maximize the win in 
   wars.
  social:
clans:
  - name: הביטונים
    tag: 8RRP28RL
  - name: Biton Feed ™️
    tag: P8P9YRQ2
  - name: biton feed 2
    tag: Y2LJ9Q29a
  - name: biton feed 3
    tag: PGQPP9GY
  - name: biton hotel
    tag: YCLC8VR0
  - name: OneManArmy
    tag: LYPRU8CR
  - name: Biton Trade
    tag: LR8QRRYQ
  - name: biton trade 2.0
    tag: QJ88JYYG
  - name: biton rest
    tag: Q900JYVG
```
