### ISSUE TITLE
[Update]: War Seekers Clan Family

### ISSUE THREAD

**Issue by modesta3** [RoyaleAPI/family-config#1062]
### Family name

War Seekers Clan Family

### Family URL

https://royaleapi.com/clan/family/warseekers/clans

### Family configuration

```yaml
name: War Seekers Clan Family
key: warseekers
color: pink
emblem: Bolt_01
info:
  logo: https://cdn.discordapp.com/attachments/1118316432762089523/1160006046081876059/WSPanther_Static.jpg
  description: >
    War Seekers is a club of Tutti Frutti clans from far and wide. We strive to provide a unique, positive, competitive and fun Clash Royale experience; safe for players of all ages. Globally and locally ranked in both ladder and clan wars. Join our tournaments and eSports events! Use our coaches for guidance in game play and deck building. We also provide support for other SuperCell games including Clash of Clans, Brawl Stars and Squad Busters.
  social:
    - website: https://warseekers.org/
    - discord: https://discord.gg/warseekers
    - twitter: https://x.com/WarSeekersCR
    - instagram: https://www.instagram.com/warseekersofficial
    - email: warseekersfam@gmail.com
clans:
  - name: High Seekers
    tag: PGY8GY2
  - name: 204 boy scouts 
    tag: JGQPU8Q
  - name: Anarchy 
    tag: Q9JJJRLR
  - name: Hail Dooms
    tag: 2090YG9J
  - name: Epic Elite
    tag: PJ2YR2P2
  - name: Blessed worthy
    tag: YR0UYR2L
  - name: AmericanEaglets
    tag: YYGV92UQ
  - name: BingePlayers 
    tag: L92JJ9Q0
  - name: Royal City
    tag: LGCRRRCQ
  - name: #WeTheNorth B
    tag: PVJGYLRP
  - name: Clan Canada
    tag: Q08P92VP
  - name: DAUNTLESS 
    tag: QV2C2R9U
  - name: WS eSports
    tag: QPU2YU9L
  - name: Arca
    tag: YRLG82L2
  - name: Atomic
    tag: QL9GU2JP
```

### Additional Info

Please remove the following entries:
  - name: K.O. Team 
    tag: 8CQPRYVV
  - name: the goods
    tag: Q9GVGLCC
  - name: 90% Anarchy 
    tag: QYUPPVVV
  - name: Canada Inc
    tag: 992YUL
  - name: Doom Seekers
    tag: QJPRGVLV
