### ISSUE TITLE
[Update]: EXCLUSÃO/INCLUSÃO DE CLAN DA FAMILIA ILLUMINATI

### ISSUE THREAD

**Issue by Rhuivao** [RoyaleAPI/family-config#1067]
### Family name

FAMILIA ILLUMINATI

### Family URL

https://royaleapi.com/clan/family/illuminati/clans

### Family configuration

```yaml
name: ILLUMINATI
key: illuminati
color: purple
emblem: Star_Shine_03
info:
description: >
**Bem-vindo(a) à Família ILLUMINATI!** O nosso foco é a guerra de clãs. Os clãs da família são formados por jogadores comprometidos com o jogo e que prezam pelo respeito, união e amizade. Vamos crescer juntos? Se junte a nós.
social:
- discord: https://discord.gg/TtKuSemW
clans:
- name: ILLUMINATI
  tag: CUPQC88
- name: SALVADORES
  tag: VYLGYC2
- name: Flangos Brasil
  tag: 2PUPRVRQ
- name: ILLUMINATI 2.0
  tag: YV8JLPC2
- name: THE KING CLASH
  tag: 98RVCPLJ
- name: Coalizão Brasil
  tag: JV0V8LQ
```

### Additional Info

INCLUSAO DO CLAN: [THE KING CLASH](https://royaleapi.com/clan/98RVCPLJ)

EXCLUSÃO DO CLAN: [Winterfell_BR](https://royaleapi.com/clan/PRP2UCY8)

EXCLUSÃO DO CLAN: [Pr0gamers](https://royaleapi.com/clan/CL9Y0U)

**Comment by Rhuivao** [comment]
EXISTEM DUAS FAMILIAS CRIADAS:

https://royaleapi.com/clan/family/illuminate/clans       -       (ERRADA - EXCLUIR ESTA FAMILIA POR FAVOR)

https://royaleapi.com/clan/family/illuminati/clans         -      (CORRETA)

**Comment by smlbiobot** [comment]
Updated

```yaml
name: ILLUMINATI
key: illuminati
color: purple
emblem: Star_Shine_03
info:
  description: >
    **Bem-vindo(a) à Família ILLUMINATI!** O nosso foco é a guerra de clãs. Os clãs da família são formados por jogadores comprometidos com o jogo e que prezam pelo respeito, união e amizade. Vamos crescer juntos? Se junte a nós.
  social:
  - discord: https://discord.gg/TtKuSemW
clans:
- name: ILLUMINATI
  tag: CUPQC88
- name: SALVADORES
  tag: VYLGYC2
- name: Flangos Brasil
  tag: 2PUPRVRQ
- name: ILLUMINATI 2.0
  tag: YV8JLPC2
- name: Coalizão Brasil
  tag: JV0V8LQ

```

https://royaleapi.com/clan/family/illuminati/clans

**Comment by Rhuivao** [comment]
<img width="857" height="470" alt="Image" src="https://github.com/user-attachments/assets/5449a9c7-4c67-42cc-ab10-e3db0e76f19e" />

Hello,

There are two remaining issues to be resolved.

1. The Clan *[*"The King Clash"*](https://royaleapi.com/clan/98RVCPLJ)* was not included in our ILLUMINATI family registration.

Please check, as this inclusion was requested in the initial order.

2. PLEASE DELETE the entire illuminat**E** family registration.

This ILLUMINAT**E** family, with the letter **"E"** at the end, does not exist, okay?

[[](https://royaleapi.com/clan/family/illuminate/clans)](https://royaleapi.com/clan/family/illuminate/clans)

because it is a duplicate.


**OBSERVAÇÃO:**

THE ONLY CORRECT FAMILY IS:

ILLUMINAT**I** FAMILY
https://royaleapi.com/clan/family/illuminati/clans

THE ONE THAT ENDS WITH THE LETTER "I" AT THE END OF THE NAME

**Comment by smlbiobot** [comment]
Please check this config:

```yml
name: ILLUMINATI
key: illuminati
color: purple
emblem: Star_Shine_03
info:
  description: >
    **Bem-vindo(a) à Família ILLUMINATI!** O nosso foco é a guerra de clãs. Os clãs da família são formados por jogadores comprometidos com o jogo e que prezam pelo respeito, união e amizade. Vamos crescer juntos? Se junte a nós.
  social:
  - discord: https://discord.gg/TtKuSemW
clans:
- name: ILLUMINATI
  tag: CUPQC88
- name: SALVADORES
  tag: VYLGYC2
- name: Flangos Brasil
  tag: 2PUPRVRQ
- name: ILLUMINATI 2.0
  tag: YV8JLPC2
- name: THE KING CLASH
  tag: 98RVCPLJ
- name: Coalizão Brasil
  tag: JV0V8LQ

```
