### ISSUE TITLE
[Update]: Crying Fire Dynasty™️ removal from Kings of Fire Family clans

### ISSUE THREAD

**Issue by cfdsirluke** [RoyaleAPI/family-config#1068]
### Family name

Crying Fire Dynasty™️

### Family URL

https://royaleapi.com/clan/family/crying-fire/clans

### Family configuration

```yaml
name: Crying Fire Dynasty™
key: crying-fire
color: blue
emblem: Flame_04
info:
  logo: https://cdn.discordapp.com/emojis/1048269457627299930.png
  description: > **Crying Fire Dynasty™**🔥 has been dominating Clash Royale since July 2017. We strive for ultimate Clan Wars success and run one of the top War clans in America: **Crying Fire**🔥. 


Our goal is to be one of the most successful local and global War Clan families in Clash Royale.  We are committed to teamwork and player development and try to help make everyone more successful in the Clan Wars.  You will enjoy Clan Wars again with us. 😉


🔥Join now to become a Crying Fire Legend with us!!**🔥
  social:
    - discord: https://discord.gg/c7WhggVTsW
clans:
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Crying Fire 2
    tag: GYUJYJJP
  - name: Crying Fire 3
    tag: Q0PL9VRR
  - name: Tears of Fire
    tag: QCPGQCQV
  - name: Embers of Fire
    tag: Q8QQ90L0
  - name: Glimmer of Fire
    tag: QY0GQJ88
  - name: Fire Thieves™
    tag: R2RRJQQU
```

### Additional Info

please remove all of these clans from the Kings of Fire Family listing as needed and restore the Crying Fire Dynasty™ family back to how it was before with these 9 clans listed above.

[cfd.txt](https://github.com/user-attachments/files/16200352/cfd.txt)
