### ISSUE TITLE
A-Team Family

### ISSUE THREAD

**Issue by jkenshinn** [RoyaleAPI/family-config#107]
```yaml
name: A-Team
key: ateam
color: red
emblem: Twin_Peaks_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    A-Team family clan

  social:
    - discord: http://discord.gg/GNg3Nn4

clans:
  - name: A-Team
    tag: LGVJYR
  - name: A-Force
    tag: P0JL89PV
  - name: Unknown Heroes
    tag: P2YQUYRC
```
