### ISSUE TITLE
New family

### ISSUE THREAD

**Issue by Wild0it** [RoyaleAPI/family-config#1070]
### Family configuration

```yaml
name: AMA | Army Mixa Auron
key: ama
color: Red
emblem: https://cdn.discordapp.com/attachments/881109884412784640/1258545761743015957/20240705_020516_0000-removebg-preview.png?ex=6698ea54&is=669798d4&hm=dba6016246e85fc9d28fe239be08b7ca5dbac49d5a0972ebc9f6cb9834c08ddd&
info:
  logo: Skull_03
  description: 
  - social: 
    - tiktok: https://www.tiktok.com/@ama.clash.royale?_t=8kh8CGa50CW&_r=1
    - youtube: https://www.youtube.com/@AMA_ClashRoyale
    - instagram: https://www.instagram.com/ama_clashroyale?igsh=ZmU0c3Y0N3Bwend6
    - twitter: https://x.com/Alliance_AMA?t=uKJzpGmibT7LLUdn-ivrnQ&s=09
    - discord: https://discord.gg/M5GnqEyYx2
clans:sort : war trophies
  - name: "Mixaholic"
    tag: JVCUP
  - name: FFR-Auron
    tag: PCY8LQP2
  - name:'QLF' ARMY
    tag: C9LRQRJ 
  - name: FFR-Wakka
    tag: PJGRRRUC
  - name:  "QLF" LEGION
    tag: Q2JR22RQ
  - name: 'QLF' BATTALION
    tag: #G0R9L9GQ
  - name: FFR-Rikku
    tag: PYP9Y0J2  
  - name: FFR-Lumina
    tag: YULGVGGQ
  - name: Born to Clash 
    tag: PJUR8CJG
  - name:  'QLF' COMPAGNY
    tag: Y8JGJL90  
  - name: "Mixaholic"n4
    tag: G8UP2YQL
```

### Additional Info

this is a new clan family bringing together several already existing families, you can remove FFR-Reborn and famille 'qlf' 

I also put sorted by war trophies, if it’s not posible put in the other one of the list
