### ISSUE TITLE
PNR Royale

### ISSUE THREAD

**Issue by MassimoPNR** [RoyaleAPI/family-config#1073]
```yaml
name: PNR Royale
key: pnr
color: purple
emblem: badges/flag_j_03
info:
  logo: https://www.pngall.com/wp-content/uploads/11/Clash-Royale-PNG-Image-HD.png
  description: >
    **PNR Royale: sei un PNR Legends o un PNR Rookies?**
    PNR Legends è il clan dove la competizione in guerra è fondamentale. Unisciti a noi per conquistare il campo di battaglia e dimostrare che Leggenda non è solo un nome, ma uno stile di vita. 
    PNR Rookies è il clan secondario. Qui gli attacchi in guerra sono facoltativi, sfruttalo per farti notare: se farai bene potrai diventare tu una prossima Leggenda.
  social:
    - email: mailto:pnrroyale@gmail.com
clans:
  - name: PNR Legends
    tag: QJ8G99LR
  - name: PNR Rookies
    tag: GY2999LQ
```

**Comment by karol-clash** [comment]
This is your corrected family config.

https://royaleapi.com/clan/family/pnr/clans

```yaml
name: PNR Royale
key: pnr
color: purple
emblem: flag_k_04
info:
  description: >
    **PNR Royale: sei un PNR Legends o un PNR Rookies?**
    PNR Legends è il clan dove la competizione in guerra è fondamentale. Unisciti a noi per conquistare il campo di battaglia e dimostrare che Leggenda non è solo un nome, ma uno stile di vita. 
    PNR Rookies è il clan secondario. Qui gli attacchi in guerra sono facoltativi, sfruttalo per farti notare: se farai bene potrai diventare tu una prossima Leggenda.
  social:
    - email: mailto:pnrroyale@gmail.com
clans:
- name: PNR Legends
  tag: QJ8G99LR
- name: PNR Rookies
  tag: GY2999LQ
```
