### ISSUE TITLE
MZ Boww

### ISSUE THREAD

**Issue by marczhong** [RoyaleAPI/family-config#1080]
```yaml
name: MZ Boww
key: mzb
color: black
emblem: flag_n_06.png

clans:
  - name: MZ Boww
    tag: QG2LC2CG
  - name: MZ Boww EU
    tag: RYGJJPJ2

…
```
