### ISSUE TITLE
submission of our clan family Aerial SPIRITS Family

### ISSUE THREAD

**Issue by akx-dev** [RoyaleAPI/family-config#1084]
```yaml
name: Aerial SPIRITS Family
key: aerial
color: blue
emblem: flag_j_02
info:
  logo: https://drive.google.com/file/d/1eOL2B65bpTQnpSskG_h6vFPcqY1fHcEq/view?usp=sharing
  description: >
    The **Aerial SPIRITS Family** is former no.1 war clan in Bangladesh.
    Here we are like a family we have a messenger group with every single clan member. 
    We always have fun and play tournament's between clan members.
  social:
    - facebook: https://www.facebook.com/groups/314571786220139
clans:
  - name: Aerial SPIRITS™
    tag: G929QVLY
  - name: Aerial AURAS™
    tag: QQVP0YLR
```

**Comment by karol-clash** [comment]
Hello. I was unable to download your logo. Can you send it directly here or send a new URL?

**Comment by karol-clash** [comment]
This is your final config
```yaml
name: Aerial SPIRITS Family
key: aerial
color: blue
emblem: flag_j_02
info:
  description: >
    The **Aerial SPIRITS Family** is former no.1 war clan in Bangladesh.
    Here we are like a family we have a messenger group with every single clan member. 
    We always have fun and play tournament's between clan members.
  social:
    - facebook: https://www.facebook.com/groups/314571786220139
clans:
  - name: Aerial SPIRITS™
    tag: G929QVLY
  - name: Aerial AURAS™
    tag: QQVP0YLR
```

Feel free to upload your logo in the future 🙂
