### ISSUE TITLE
BANGLADESH CLAN NETWORK FAMILY

### ISSUE THREAD

**Issue by muktabhai** [RoyaleAPI/family-config#1086]
### Family configuration

```yaml
name:BANGLADESH CLAN NETWORK FAMILY
key: bangladesh
color: green
emblem: Flame_03
info:
  logo: badges/A_Char_Goblin_01.png
  description: >
   The Bangladesh Clan is one of the oldest clans in clash royale. EMERGING NUMBER ONE CLAN OF BANGLADESH. ◐◡◑
We have a network of 500+ players with regular tournament prizes for network clans and big seasonal country tournament. ◐◡◑    Every season CASH awards are given to ladder toppers, War toppers and global rankers. We are going huge. 
*****As per reports from players Golem Muktadir may be their clan head and RAIN their Leader*****
    **Join the Family. Become a Legend. **
  social:
    - facebook:  https://www.facebook.com/profile.php?id=61559660840771&mibextid=ZbWKwL
    - clan logo:  https://drive.google.com/file/d/1M2TebFDJyn8JKTilA5hRmk5srXU_38Mr/view?usp=drivesdk
clans:
  - name: BANGLADESH
    tag: YCP20P9U
  - name: The Invincibles
    tag: Q2R9VR02
  - name: Bangladesh 2.0
    tag: R0Q8VLGC
  - name: uttara
     tag: GY2QRP82
  - name: uttara 2.0
    tag: GUJPUYVU
  - name: Dark-Side
     tag: Q9QU8RCY
```
