### ISSUE TITLE
TIGER CUB CLAN

### ISSUE THREAD

**Issue by muktabhai** [RoyaleAPI/family-config#1087]
### Family configuration

```yaml
name: TIGER CUB BD (NAFI+EMMA)
key: love us
color: red
emblem: Sword_02
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    The **BD TIGER CUB** was originally known as
    BD TIGERS is a Clan of top players created by Nafi- "The Great" and Emma - "The Highness" .
    "mora zabo bisser kule loia tuma logo"
    Our sons are Lucky prince and prince Kavi. come and join us for fun, love, free-mixing.
 
clans:
  - name: BD TIGERS
    tag: 2LGR8
  - name: Clamp Clash
    tag: YLQGG8PP
  - name: Devils' Eye
    tag: L82L8R2R
  - name: All inactive
    tag: G8GLCPYC
  - name: Royal Town
    tag: Q2RU8YLG
  - name: BD TIGERS
    tag: YG20LYJQ
  - name: BANGLADESH
    tag: 9ULCLRRQ
```
