### ISSUE TITLE
[Update]: Royal Family

### ISSUE THREAD

**Issue by JackClack** [RoyaleAPI/family-config#1088]
### Family name

Royal Family

### Family URL

https://royaleapi.com/clan/family/royal/clans

### Family configuration

```yaml
name: Royal Family
key: royal
color: black
emblem: Diamond_Star_01
info:
  logo: https://ibb.co/NVHzxGd
  description: >
   **Royal Family** является самым масштабным сообществом Clash Royale в Украине, также и самой большой семьёй кланов.
Призовые на турнирах - _3 000$+_. Розыгрыши, челленджи на _1 000$+_. Множество других проектов, как десятки стикерпаков и не только, можно найти в наших социальных медиа.
**Присоединяйтесь к Королевской Семье!**
  social:
    - telegram: https://t.me/royal_HSUM
    - tiktok: https://www.tiktok.com/@royal_family_cr?_t=8fUdb860q8b&_r=1
    - discord: https://discord.gg/XdJZvYyXGf
    - youtube: https://youtube.com/@royal_family_cr?si=_rEUsYZonOz_foLh
    - twitter: https://x.com/royal_family_cr?s=21&t=7JY5Vsz37fPEfdixyi5Igw
    - twitch: https://twitch.tv/royal_family_cr
    - vk: https://vk.com/royal_harmony
    - email: mailto:royal.family.cl.ro@gmail.com
clans:
  - name: Royal Harmony
    tag: QUVCQ9
  - name: Royal Symphony
    tag: LQ0VYV0P
  - name: Royal Unity
    tag: YV22QG9V
  - name: Royal Melody
    tag: YV8Q002R
  - name: Royal Legacy
    tag: R9R88999
  - name: Royal Destiny
    tag: QUPGC88R
  - name: Royal Victory
    tag: QCPGPR0L
  - name: Royal Fantasy
    tag: RG0LQVYU
  - name: Royal Infinity
    tag: G20Q0GPC
  - name: Royal Glory
    tag: G2UYUJU0
  
```
