### ISSUE TITLE
bones-brigade

### ISSUE THREAD

**Issue by gregbeddor** [RoyaleAPI/family-config#109]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: purple
- `key`: bones-brigade
- `emblem`: Skull_05
- `description` and `links`: the bones crew
- `tag`:  bones

Fill in the configuration below:

```yaml
name: bones-brigade
key: bones-brigade
color: purple
emblem: Skull_05
info: the bones crew
  logo: Skull_05
  description: >
    the bones crew

clans:
  - name: B O N E Y A R D
    tag: URRLPL2
  - name: Bones Brigade
    tag: LLYVPC2
```

**Comment by smlbiobot** [comment]
we don’t support single clans, sorry. we will look into if we will in the future.

**Comment by gregbeddor** [comment]
We fave 4 clans but I only listed 2

**Comment by smlbiobot** [comment]
ok

**Comment by gregbeddor** [comment]
clans:
name: B O N E Y A R D
tag: URRLPL2
 
name: Bones Brigade
tag: LLYVPC2

name: BONEYARD U.K
tag: #20YV0YJL

name: Bone Mountain
tag: 3LUJCJO

- THOSE O'S COULD ZEROS / 0

**Comment by gregbeddor** [comment]
Thanks, I've listed out all 4.

Let me know if there's anything else we need to provide.

**Comment by smlbiobot** [comment]
- clan tags are always number `0`
- can you update the config with the new clans included and also escape your config?

**Comment by smlbiobot** [comment]
```yml
name: bones-brigade
key: bones-brigade
color: purple
emblem: Skull_05
info:
  logo: /static/img/badge/Skull_05.png
  description: >
    the bones crew
clans:
  - name: B O N E Y A R D
    tag: URRLPL2
  - name: Bones Brigade
    tag: LLYVPC2
  - name: BONEYARD U.K
    tag: 20YV0YJL
  - name: Bone Mountain
    tag: LUJCJ0
```
