### ISSUE TITLE
[Update]: Nova QC

### ISSUE THREAD

**Issue by niibz** [RoyaleAPI/family-config#1090]
### Family name

Nova QC

### Family URL

https://royaleapi.com/clan/family/nova-qc/clans

### Family configuration

```yaml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: https://github.com/RoyaleAPI/family-config/assets/93715501/c5c984be-0cde-4f2a-b258-0bb40e6910af
  description: >
    Nova QC est la plus grande organisation sur Clash Royale, avec plus de 2 500 membres actifs répartis dans 51 clans.
    Nos valeurs sont simples : respect et intégrité.
    Nous misons sur la puissance, la cohésion et l'entraide pour avancer.
    En constante croissance, Nova QC est une communauté forte, orientée vers l'élite et l'excellence.
    Nous formons une véritable dynastie, avec un seul objectif : la domination totale. Facebook/Messenger/Discord.

    Nova QC is the largest organization on Clash Royale, with over 2,500 active members across 51 clans.
    Our values are simple: respect and integrity.
    We focus on strength, cohesion, and mutual support to move forward.
    In constant growth, Nova QC is a strong community, geared towards elite performance and excellence.
    We are a true dynasty, with one goal: total domination. Facebook/Messenger/Discord.
  social:
    - discord: https://discord.gg/J66DCmhR
    - facebook: https://www.facebook.com/groups/546237565896704
clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
  - name: Nova QC ☆ 7
    tag: LCQJRP2Q
  - name: Nova QC ☆ 8
    tag: QP8G8LLR
  - name: Nova QC ☆ 9
    tag: G0GVRCR8
  - name: Nova QC ☆ 10
    tag: LUQP0UG8
  - name: Nova QC ☆ 11
    tag: Q2ULYQRY
  - name: Nova QC ☆ 12
    tag: QJCJ989C
  - name: Nova QC ☆ 13
    tag: QJ2R229R
  - name: Nova QC ☆ 14
    tag: GJ9L9VJQ
  - name: Nova QC ☆ 15
    tag: QLJ00U8V
  - name: Nova QC ☆ 16
    tag: QC02V2VP
  - name: Nova QC ☆ 17
    tag: GQJVV0RL
  - name: Nova QC ☆ 18
    tag: GJYQ9PCU
  - name: Nova QC ☆ 19
    tag: Q2LPURYR
  - name: Nova QC ☆ 20
    tag: Q08CJR0G
  - name: Nova QC ☆ 21
    tag: QJ9RPLGQ
  - name: Nova QC ☆ 22
    tag: GQUVJQJ0
  - name: Nova QC ☆ 23
    tag: Q99V0JV9
  - name: Nova QC ☆ 24
    tag: Q808JUJ0
  - name: Nova QC ☆ 25
    tag: GU8VUQCG
  - name: Nova QC ☆ 26
    tag: GRR80Y2R
  - name: Nova QC ☆ 27
    tag: Q898JQVJ
  - name: Nova QC ☆ 28
    tag: GQLLULCP
  - name: Nova QC ☆ 29
    tag: QV22QRRC
  - name: Nova QC ☆ 30
    tag: Q890PGQC
  - name: Nova QC ☆ 31
    tag: Q88CCGRJ
  - name: Nova QC ☆ 32
    tag: QGCRJRLY
  - name: Nova QC ☆ 33
    tag: R0RUUGL0
  - name: Nova QC ☆ 34
    tag: QC0URPRR
  - name: Nova QC ☆ 35
    tag: QRJVL92C
  - name: Nova QC ☆ 36
    tag: RYJYQ90R
  - name: Nova QC ☆ 37
    tag: QJP9YQLR
  - name: Nova QC ☆ 38
    tag: GLQ0P880
  - name: Nova QC ☆ 39
    tag: QJVLRY0Y
  - name: Nova QC ☆ 40
    tag: QC2LV8UQ
  - name: Nova QC ☆ 41
    tag: RYJJYYCG
  - name: Nova QC ☆ Libre
    tag: Q02RJLYR
  - name: Nova QC ☆ L1
    tag: QUYLJUR2
  - name: Nova QC ☆ L2
    tag: Q8L80889
  - name: Nova QC ☆ L3
    tag: QR0PL8PC
  - name: Nova QC ☆ L4
    tag: QPL0Q0Y9
  - name: Nova QC ☆ L5
    tag: Q9PYVPJQ
  - name: Nova QC ☆ L6
    tag: Q9PG9RVL
  - name: N☆QC丨❤️
    tag: GJ9UC2C8
  - name: N☆QC丨Daniel
    tag: QPLUJRR8
  - name: N☆QC丨1337
    tag: QUR8Q820
```
