### ISSUE TITLE
Maratonci family-config

### ISSUE THREAD

**Issue by Merlin260677** [RoyaleAPI/family-config#1093]
```yaml
name: Maratonci
key: MARAT
color: purple
emblem: A_Char_Rocket_02
info:
    logo: /static/img/branding/cr-api-logo.png
    description: >
        The Maratonci (MARAT) was formed 8 years ago
        Home to best players in Balkans
        We are 100% war clan, but serious about pushing ladder and path
    social:
discord: https://discord.gg/Vb8dr8Y5
clans:
    -   name: Maratonci
        tag: '#9LJJJRVC'
    -   name: Maratonci 2
        tag: '#QYJ2YQR8'
    -   name: Maratonci 3
        tag: '#RYPUUC8L'
```
