### ISSUE TITLE
[Update]: Fusion of Doom family

### ISSUE THREAD

**Issue by ReaperCR** [RoyaleAPI/family-config#1094]
### Family name

Fusion of Doom Empire

### Family URL

https://royaleapi.com/clan/family/fod/clans

### Family configuration

```yaml
name: Fusion of Doom Empire
key: fod
color: black
emblem: flame_04
info:
description: >
The Fusion of Doom Empire is a clan family focused almost entirely on winning our wars. Our first clan, Fusion of Doom, was established in September of 2021, and rose up the ranks super fast, getting to Legendary II, and ending up within the top 25 war clans in all of Canada after just over 2 years. After the first clan retired, we started focusing on multiple other projects, which are all consistently able to place well in wars. If you are willing to participate in our wars daily, and use all 4 decks (& kick ass cuz it’s fun), then feel free to join our Discord. (Or just join one of our active clans upfront).
social: 
discord:
https://discord.gg/gRSyrFUvZx
clans:
- name: Fusion of doom
  tag: L8UV9JQQ
- name: Velvet Room
  tag: GCQU8R9C
- name: Exodus
  tag: GP2J2Y2C
- name: Nohrian Knights
  tag: QGLPQ29U
```
