### ISSUE TITLE
New Family Clan

### ISSUE THREAD

**Issue by nunosiii** [RoyaleAPI/family-config#1095]
```yaml
name: Jesus is Risen
key: jir
color: blue
emblem: flag_d_04
info:
  logo: 
  description: >
   💥 #1 Global Christian Clan 💥 https://discord.gg/2KD5DzswYR 💥 Top 25 Global 💥 Jesus is Risen2, Jesus is Risen3, & Jesus is Risen4 💥 Jesus is Lord!  JIR is focused on being a top Clan for Ladder and Path of Legends, JIR2 focused on Clan Wars (war is mandatory), JIR3 is an all-purpose clan for those people trying to get into JIR or JIR2, and JIR4 for more relaxed/casual players.
  social:
    - discord: https://discord.gg/2KD5DzswYR
clans:
  - name: Jesus is Risen
    tag: 8L0CRRL
  - name: Jesus is Risen2
    tag: YG0VV0LC
  - name: Jesus is Risen3
    tag: YJ0RPUGQ
  - name: Jesus is Risen4 
    tag: LYLYLQJQ
```
