### ISSUE TITLE
Clan Family Update: Mage Knights

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#1098]
```yaml
name: Mage Knights
key: mageknights
color: violet
emblem: Sword_04
info:
  description: >
    **Welcome to the Mage Knights Clan Family!** Our main clan is dedicated to war, but we believe there’s always room 
    for improvement. Join us as we strive together!
clans:
  - name: Mage Knights
    tag: 2V28Y88Q
  - name: Mage Knights 2
    tag: YR00L2LY
```
