### ISSUE TITLE
[Family] Invincible Eyes

### ISSUE THREAD

**Issue by korjaw** [RoyaleAPI/family-config#11]
```yaml
name: Invincible Eyes Family
key: Invi
color: blue
emblem: Sword_01
info:
  logo: invieyes.pl/logo.png
  description: >
    Welcome to the  **INVI EYES** Family :) 

**There are heroes, there are superheroes and we are.. Invi** - Poland team


     Invi were founded by Korjaw in August 2017.


  social:
    - twitter: https://twitter.com/eyes_invincible
    - discord: http://discord.gg/yTKRn6z
    - facebook: https://www.facebook.com/InvincibleEyesPL
    - website: http://invieyes.pl
    - email: contact@invieyes.pl
clans:
  - name: Invincible Eyes
    tag: 8QUPU00P
  - name: Invi Eyes AK
    tag: 9P2Q02GY
  - name: InvincibleEyes2
    tag: PQYJP2VC
```

**Comment by smlbiobot** [comment]
```yml
name: Invincible Eyes Family
key: Invi
color: blue
emblem: Sword_01
info:
  logo: /static/img/brands/logo/invincible-eyes.png
  description: >
    Welcome to the  **INVI EYES** Family :)


    **There are heroes, there are superheroes and we are.. Invi** - Poland team


    Invi were founded by Korjaw in August 2017.


  social:
    - twitter: https://twitter.com/eyes_invincible
    - discord: http://discord.gg/yTKRn6z
    - facebook: https://www.facebook.com/InvincibleEyesPL
    - website: http://invieyes.pl
    - email: mailtocontact@invieyes.pl
clans:
  - name: Invincible Eyes
    tag: 8QUPU00P
  - name: Invi Eyes AK
    tag: 9P2Q02GY
  - name: InvincibleEyes2
    tag: PQYJP2VC
```
