### ISSUE TITLE
Sea Monsters Esports

### ISSUE THREAD

**Issue by madmax91310** [RoyaleAPI/family-config#110]
```yaml
name: Sea Monsters Esports
key: SeaM
color: blue
emblem: Skull_05.png
info: Sea Monsters Esports est une organisation française de 3 clans sur Clash Royale, et d'une équipe esport. 
  logo:
  description: 
    


   
  social:
    - twitter: http://twitter.com/SeaM-eSports
    - https://discord.gg/7ZsNXen

clans:
  - name: Cthulhu Esports
    tag: 82Q0VRRU
  - name: Lusca Esports
    tag: PY9R00UP
  - name: Poulpe Esports
    tag: Y8QCJYL0
```
