### ISSUE TITLE
[New]: Noob Nation Family Config

### ISSUE THREAD

**Issue by midhun20** [RoyaleAPI/family-config#1101]
### Family configuration

```yaml
name: N00b Nation
key: noob-nation
color: green  
emblem: Clover_02
sort: trophy
info:
  description: >
    Welcome to **N00b Nation** – where strategy is optional and *Oops!* is our battle cry! 
    If you’ve ever missed a Fireball, zapped the wrong troop, or thought “Wait, what does this card do?” – 
    you’ll fit right in. Winning is cool, but spectacular fails are even cooler. 
    Join us, and let’s make questionable plays together!

    **Hate Noobs**: ironically, a safe space for all noobs who just want to spam emotes, 
    drop random cards, and accidentally rage quit. Winning? Meh. 
    Having a blast? Guaranteed.

clans:
  - name: Hate Noobs
    tag: G9GP0P2R
```
