### ISSUE TITLE
[New]: Eternal Realms

### ISSUE THREAD

**Issue by Praeliux** [RoyaleAPI/family-config#1105]
### Family configuration

```yaml
name: Eternal Realms
key: eternalrealms
color: red
emblem: A_Char_Hammer_02
info:
  logo: https://i.ibb.co/0yJd3G1/ETN-Fenix-RED-ANIMATION-ACTUAL.png
  description: **Eternal Realms** (ETN) was founded in August of 2024, our war group has developed an environment where casual and competitive styles of play can both flourish. Each of ours clans are in different war leagues meaning there's a place for everyone here!

Our group communicates effectively through Discord, Feel free to join us!

  social:
    - discord: https://discord.com/invite/ytgZ3Xjyhh
clans:
  - name: Clash of Realms
    tag: L9JV99PP 
  - name: Snickers
    tag: G28U0PLR
  - name: Lord of Realms
    tag: RYG288QL
```

**Comment by karol-clash** [comment]
I fixed your config. The changes should get live in about an hour
```yaml
name: Eternal Realms
key: eternalrealms
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/eternalrealms.png
  description: >
    **Eternal Realms** (ETN) was founded in August of 2024, our war group has developed an environment where casual and competitive styles of play can both flourish. Each of ours clans are in different war leagues meaning there's a place for everyone here!
    Our group communicates effectively through Discord, Feel free to join us!

  social:
  - discord: https://discord.com/invite/ytgZ3Xjyhh
clans:
- name: Clash of Realms
  tag: L9JV99PP 
- name: Snickers
  tag: G28U0PLR
- name: Lord of Realms
  tag: RYG288QL
```
