### ISSUE TITLE
New Family of clans - Thé Winners Family

### ISSUE THREAD

**Issue by Zenomium** [RoyaleAPI/family-config#1106]
```yaml
name: "Thé Winners Family"
key: thewinners
color: red
emblem: Crown_01
info:
  logo: https://i.postimg.cc/NjyXNYdk/The-winners.png
  description: >
    Bienvenue chez Thé Winners !
    Fondée en 2024, notre famille repose sur le respect, la bonne humeur et la passion du jeu. Un serveur Discord très 
    actif et des tournois hebdomadaires vous y attendent !

    Nous avons des clans pour chaque style de jeu : guerres de clans, ladder ou chill.

    Rejoins-nous sur Discord et trouve ta place dans la famille Thé Winners !
social:
  - discord: https://discord.gg/N3ugsZdg3q
clans:
  - name: Thé Winners
    tag: LJPPLRJV
  - name: Thé Winners 2.0
    tag: GLG08LCY
  - name: Thé Winners 3.0
    tag: G8JVVJ0J
  - name: Pegasus du ciel
    tag: RPJPV0
  - name: Gourmandise
    tag: GY2GG9GQ
  - name: D E S T I N Y
    tag: QY8Y2RCV
  - name: TAMOUL
    tag: QGVC28L9 
  - name: Lutins des bois
    tag: 29U0Q0R
  - name: le Klub
    tag: RL00QLRV
  - name: Infinity Castle
    tag: GRGPGUUV
  - name: ReleaseD
    tag: G0VLQG9Y
  - name: Lutin d Bois II
    tag: QVGVVYY8
  - name: Les Gars du 85
    tag: GGUQL8Q0
  - name: D E S T I N Y 2
    tag: RRVCR28G
```
