### ISSUE TITLE
[Update]:  add logo, social, clan and update Description

### ISSUE THREAD

**Issue by RicosoSoft** [RoyaleAPI/family-config#1107]
### Family name

☆. La Resistance

### Family URL

https://royaleapi.com/clan/family/la_resistance/clans

### Family configuration

```yaml
name: ☆. La Resistance
key: la_resistance
color: orange
emblem: Traditional_Star_01.png
info:
  logo: https://cdn.discordapp.com/attachments/958343965730570290/1305464545996701786/LOGO_ETOILE3.png?ex=6733201a&is=6731ce9a&hm=30e7b88f030d3c1bbb1fe895484bfe5889ba1979cdedd9c9680030b851479a14&
  description: >
    **☆. La Resistance** famille de 4 clans orientés GDC avec pour ambition de progresser dans le top monde. 
Bonne humeur obligatoire !!!
  social:
    - discord: https://discord.gg/kPdQN8zfjM
    - instagram: https://www.instagram.com/laresistance_cr
    - tiktok: https://www.tiktok.com/@resistance_cr
    - youtube: https://www.youtube.com/@LaResistance_CR
clans:
  - name: La Resistance
    tag: Y8JUPC9C
  - name: Les Resistants
    tag: LRQP20V9
  - name: Les Revoltes
    tag: QU9UQJRL
  - name: La Treve
    tag: QUV220GJ
```
