### ISSUE TITLE
Clashers

### ISSUE THREAD

**Issue by LocdOut** [RoyaleAPI/family-config#1108]
```yaml
name: Clashers
key: clashers
color: black
emblem: Flag_J_03
info:
  description: >
    Est. 2021. English War and Casual Clans.
  social:
    - discord: https://discord.gg/PXCv3BbUkC
clans:
  - name: United Clashers
    tag: QCJ9GG8G
  - name: Sub-Clashers
    tag: QJ8LJQL8
  - name: Idle Clashers
    tag: G2L8JPPU
```
