### ISSUE TITLE
The Royal Order

### ISSUE THREAD

**Issue by Deyvidox** [RoyaleAPI/family-config#1109]
```yaml
name: The Royal Order
key: L2P8009Y
color: red and yellow
emblem: A_Char_King_01.png
sort: trophy
![image](https://github.com/user-attachments/assets/78bd2376-5626-457e-b0b4-b3065a83667e)
instagram: https://www.instagram.com/theroyalorder_oficial?igsh=MXZ2cDAyMHd0cGducQ==



…
```
