### ISSUE TITLE
Update - Family clan Liverpool 

### ISSUE THREAD

**Issue by Liverpool-Clan** [RoyaleAPI/family-config#1110]
### Family name

Liverpool

### Family URL

https://royaleapi.com/clan/family/liverpool/clans

### Family configuration

```yaml
name: Liverpool Family Clans
key: liverpool
color: red
emblem: flag_f_02
info:
  description: >
    This is Anfield. We are Liverpool. Global International Liverpool F.C. supporters into Clash Royale. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!
  social:
    - email: mailto:crownprinceakacp@gmail.com
clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool
    tag: QR28PUPC
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
  - name: Liverpool Spion
    tag: GJVG2V82
  - name: Liverpool Chile
    tag: R89VYCVL
  - name: Liverpool
    tag: QRVVJCRL
```
