### ISSUE TITLE
[Update]: extension GPAS family

### ISSUE THREAD

**Issue by CaneSciortoGPAS** [RoyaleAPI/family-config#1111]
### Family name

GPAS FAMILY

### Family URL

https://royaleapi.com/clan/family/gpas/clans

### Family configuration

```yaml
name: GPAS FAMILY
key: gpas
color: orange
emblem: flag_k_04
info:
 logo: https://postimg.cc/zHhCR7J8
 description: >
	La Famiglia **GPAS**, creata il **02/06/2018**, è costituita da 6 clan fondati da _CaneSciorto_ su solide basi e veri valori quali unione, fratellanza ed educazione.
	La War è il nostro principale obbiettivo, con ottimi risultati raggiunti nella storia del primo glorioso clan: Top **#3** Italia e Top **#48** Globale.
	A disposizione ci sono gruppi _Telegram_ dedicati ai clan, canale _Telegram_ ed il server _Discord_ per rimanere sempre aggiornati sull'andamento dei clan e sulle nostre iniziative.
	Eventi e tornei a premi sempre ben organizzati, per poter mostrare le proprie abilità e competere con top player.
	Premi per i migliori in war ogni season!!!
	Fondamentale il rispetto del regolamento, affinché si mantenga il clima di **FAMIGLIA** che ci ha sempre contraddistinto.
	Per entrare anche tu a far parte della Famiglia **GPAS** contatta i link qui sotto...ti aspettiamo!
 social:	
  - application: https://t.me/ReclutamentoGPAS
  - telegram: https://t.me/CaneSciorto
  - telegram: https://t.me/LumonGPAS
  - discord: https://discord.gg/PwDZFzFX8J
 clans:	
  - name: GPAS
    tag: 9GP22VLG
  - name: GPAS ACADEMY
    tag: L8LRGQCJ
  - name: GPAS ACADEMY 2
    tag: QQQLGRVQ
   -name: GPAS ACADEMY 3
    tag: GYJU2GC2
  - name: GPAS RESORT
    tag: GCY8J8P0
  - name: Italiani Veri
    tag: QCQGL000
…
```
