### ISSUE TITLE
[Update]:  Clan Family Polish Soldiers Clans

### ISSUE THREAD

**Issue by dzionas74** [RoyaleAPI/family-config#1112]
### Family name

Polish Soldiers Clans

### Family URL

https://royaleapi.com/clan/family/polishsoldiers/clans

### Family configuration

```yaml
name: Polish Soldiers Clans
key: polishsoldiers
color: black
emblem: Flame_03
info:
  logo: https://psold.pl/images/psold_logo.jpg
  description: >
    Polski / English. 
    Dołącz do największej i najbardziej zgranej grupy Klanów Wojennych w Polsce. 
    Kultura, wiedza, Discord - dobra zabawa! Join us to share experience, 
    communicate on Discord and have lots of fun playing the best Clan Wars ever.
  social:
    - discord: https://discord.gg/Z9TRYA4z7V
    - website: https://psold.pl
clans:
  - name: Polish Soldiers
    tag: 2CVY8GUG
  - name: PS2 AKADEMIA
    tag: P0RU2CL8
  - name: PS3 AKADEMIA
    tag: QPLCJPGV
  - name: PS4  AKADEMIA
    tag: LVJLJRVJ
  - name: PS5 AKADEMIA
    tag: QO9QOQY2
  - name: PS6 AKADEMIA
    tag: LLCPCGVG
  - name: PS7 AKADEMIA
    tag: QPUYVJV2
  - name: PS8 AKADEMIA
    tag: GQ099YP2
  - name: PS MINI
    tag: QJY9PUQL
  - name: PS TECH
    tag: RPV9J9C9
```
