### ISSUE TITLE
[New]: Add UKRAINE Clan Family

### ISSUE THREAD

**Issue by romanorieshyn** [RoyaleAPI/family-config#1113]
### Family configuration

```yaml
Paste your YAML confiname:  UKRAINE
 key: ukraine8848
 color:  blue
 emblem:  A_Char_Rocket_02
 info: 
  description:   >
    Сім'я кланів "UKRAINE" об'єднує найкращих гравців із України. Ми прагнемо
    досягти нових висот у грі та представляти нашу країну з гордістю.
    Ласкаво просимо до нашої спільноти!
 clans:
  - name:  Україна
    tag:  GLPVG90
  - name:  KIEV
    tag:  YUJ208
 sort:  activity
```
