### ISSUE TITLE
Add Green Team Family

### ISSUE THREAD

**Issue by maiconjulian0** [RoyaleAPI/family-config#1118]
```yaml
name: Green Team BR
key: greenteam
color: green
emblem: Pine_03
info:
  logo: https://greenteambr.com/wp-content/uploads/2024/12/GREEN-TEAM-FT.gif
  description: >
    The **GREEN TEAM** It is a professional war clan that continues to grow.
  social:
    - website: https://greenteambr.com
    - twitter: https://x.com/green_bras30011
    - facebook: https://www.facebook.com/GreenTeamBrasil
    - instagram: https://www.instagram.com/green_teambr
    - youtube: https://www.youtube.com/@greenteambr
    - email: suporte@greenteambr.com
clans:
  - name: Green Team
    tag: 29P2RYP
  - name: GT2 Brasil
    tag: YV0920RJ
  - name: GT3 Brasil
    tag: QJCY2RR9

```
