### ISSUE TITLE
走遍万罪星空

### ISSUE THREAD

**Issue by arshtyi** [RoyaleAPI/family-config#1119]
```yml
name: 走遍万罪星空
key: 走遍万罪星空
color: blue
emblem: Arrow_01
info:
  description: >
    中国人为主的部落，欢迎各方朋友加入，主要交流频道为QQ群：939160021
    A clan mainly composed of Chinese people, welcoming friends from all sides to join. The main communication channel is QQ group: 939160021
clans:
  - name: 零度轩辕
    tag: QRL0PYQL
  - name: 勾指起誓
    tag: R8RJYCCU
  - name: 啟明星之夢
    tag: GQPV9Y2R
```
