### ISSUE TITLE
Elite Runners family

### ISSUE THREAD

**Issue by Project-Account-lab** [RoyaleAPI/family-config#112]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Elite Runners family
key: elite
color: red
emblem: A_Char_Pekka_02
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Elite Runners 1
    tag: 9JP0JG9R
  - name: Elite Runners 2
    tag: Y0CQJVGV
  - name: ER WORLD TEAM
    tag: YQ8PYJUU
```

**Comment by smlbiobot** [comment]
pls remove irrelevant configs in the future:
we have to change your key because there is already another family using `elite` as their key

```yml
name: Elite Runners family
key: elite-runners
color: red
emblem: A_Char_Pekka_02
clans:
  - name: Elite Runners 1
    tag: 9JP0JG9R
  - name: Elite Runners 2
    tag: Y0CQJVGV
  - name: ER WORLD TEAM
    tag: YQ8PYJUU
```
