### ISSUE TITLE
Update family info

### ISSUE THREAD

**Issue by Campaner2001** [RoyaleAPI/family-config#1120]
``` yaml
Name: Familia AlmasDeFuego
key: AlmasDeFuego
color: red
emblem: Flame_01
info:
description: >
La familia de clanes AlmasDeFuego es un referente dentro del juego, habiendo logrado ser top 1 global en copas,
con jugadores de alto nivel y diversificación en los diferentes aspectos dentro del juego. 
Teniendo a nuestra disposición un clan de liga donde se juega guerra, un clan de liga sin guerras, tres clanes
expresamente para guerras y un último clan de descanso, ofrecemos a cualquier jugador un clan de alto nivel
adecuado a las necesidades personales. 
Si buscas una familia acogedora y de alto nivel, no dudes en solicitar entrar.
social:
-twitter: https://x.com/_AlmasDeFuego
clans:
- name: AlmasDeFuego
tag: GGU8QY
- name: Almasdefuego2
tag: P2YU8U2
- name: Almasdefuego3
tag: YQUJ09L0
- name: Almasdefuego4
tag: LLCCRCL0
- name: Almasdefuego5
tag: QCJU8R2L
- name: Almasdefuego6
tag: GQ2VVQ0Y
```
