### ISSUE TITLE
[New]: New Clan Family - Aura Legion Clan Family

### ISSUE THREAD

**Issue by kurbit06** [RoyaleAPI/family-config#1121]
### Family configuration

```yaml
name: 	Aura Legion
key: 	aura
color: 	purple
emblem: Arrow_02.png
info:
  logo: https://github.com/user-attachments/assets/5e3c9fc3-f9e8-4ec6-899b-aef653731363.png
  description: >
    ☆ Aura Legion Family ☆

    "Fear the Legion, Respect the Aura"

    Thrive in War, Relax in Chill, Competitive in Ladder.

    Ready to build bonds that won't be broken!
  social:
    - discord: https://discord.gg/kukQrCRbYp
clans: 	
  - name: NightWrath
    tag: GLP08UR8
  - name: Clashers
    tag: R9C9Y2VL
  - name: awoken ghosts
    tag: R90GVYPP
  - name: Aura Academy
    tag: G9Y2GV9C
sort: trophy
```

### Additional Info

![AuraLegionLogo](https://github.com/user-attachments/assets/5e3c9fc3-f9e8-4ec6-899b-aef653731363)
