### ISSUE TITLE
OG々INFERNO Family

### ISSUE THREAD

**Issue by Usmankhan1098** [RoyaleAPI/family-config#1122]
### Family configuration

```yaml
name: OG々INFERNO Family
key: inferno
color: purple
emblem: Clover_02
info:
  logo: https://razi-del.github.io/img-heist/static/img/branding/OG%20INFERNO-logo.png
  description: >
    The **OG々INFERNO** Family Comprises of 5 main clans that are based on clan war. We have experience of 5,000 war league & we have incredible management team and players. A proper esports team to deal with competitive tournaments and scrims.

  social:
    - discord: https://discord.gg/yTjndNJEjX
    ‐ twitter: https://twitter.com/usmanskhan87

clans:
  - name: peace in world
    tag: YG20YV2L
  - name: pakistan
    tag: PGCCGV22
  - name: Pak Pro Team
    tag: 9G2QUL29
  - name: PAK ARMY!
    tag: Q0LR9GRV
  - name: Muslim legends.
    tag: R0RYGJ2P
  - name: The Rebels
    tag: L0V8CVUQ
  - name: IŃFĘŘÑØ々P.P.T
    tag: R0LVJRJY
  - name: ÔĞ々IŃFĘŘÑØ
    tag: GRQJYVJC
```

**Comment by Usmankhan1098** [comment]
@smlbiobot 
@Zaop7 
Hey guys, this is my 2nd time opening an issue. The last issue was open for around 90 days then, i renewed it so you can review and close this issue. It would be appreciated if you do this quickly.

Regards.

**Comment by smlbiobot** [comment]
you have no key set

**Comment by smlbiobot** [comment]
also complete messed up characters that have nothing to do with your family. We don’t want things that look like a virus on our site. either change it to english or denied.

**Comment by Usmankhan1098** [comment]
Made some changes, Let me know if it's still invalid. Thanks for your time.

**Comment by Usmankhan1098** [comment]
@smlbiobot

**Comment by Usmankhan1098** [comment]
Kindly complete and close this before the end of this month. It's appreciated that how much hard work you guys do

**Comment by Usmankhan1098** [comment]
@smlbiobot

**Comment by Usmankhan1098** [comment]
@Zaop7 
@smlbiobot 
Kindly complete this issue and close this. I've been waiting here for months. It's appreciated.

**Comment by Usmankhan1098** [comment]
@smlbiobot 
@Zaop7

**Comment by Usmankhan1098** [comment]
@Zaop7 it has been 4 months.....

**Comment by Usmankhan1098** [comment]
@smlbiobot kindly brother finish this issue. I've been waiting for more than 5 months.

**Comment by Usmankhan1098** [comment]
@Zaop7 
@smlbiobot 
It's a sincere request to complete this issue. It has been more than 6 months. Everything here is perfectly fine just get it going. Thanks!

**Comment by Usmankhan1098** [comment]
@smlbiobot 
@Zaop7

**Comment by Usmankhan1098** [comment]
Hi See-Ming-Lee, It's a request to look into the configuration tagged in
the email and execute it. It has been around 7-8 Months since the issue was
created. I know you're a busy person but kindly close this issue as soon as
possible.

Yours sincerely,
Usman.

**Comment by LukasIsLost** [comment]
@Usmankhan1098 
Sorry for the late reply and the inconvenience. 
Unfortunately, I can't download the logo. This link gives me a “404 page not found” error. I need a new link for the download or, ideally, the file itself here in the issue.

<img width="641" height="382" alt="Image" src="https://github.com/user-attachments/assets/9fb927e8-ebfa-4660-93f7-b5e59ba45993" />

**Comment by Usmankhan1098** [comment]
@LukasIsLost brother i can send you the image but Don't know how to convert it into the code.

I got that image code from a friend, He helped me.

![20250330_172525.jpg](https://github.com/user-attachments/assets/e0d98a21-cd09-4323-845d-f38524002308)

**Comment by LukasIsLost** [comment]
Done. It may take up to an hour for it to appear on the site due to cache.

This is your final yml.
````yaml
name: OG々INFERNO Family
key: inferno
color: purple
emblem: Clover_02
info:
  logo: /static/img/team/logo/inferno.png
  description: >
    The **OG々INFERNO** Family Comprises of 5 main clans that are based on clan war. We have experience of 5,000 war league & we have incredible management team and players. A proper esports team to deal with competitive tournaments and scrims.
  social:
  - discord: https://discord.gg/yTjndNJEjX
  - x: https://x.com/usmanskhan87
clans:
  - name: peace in world
    tag: YG20YV2L
  - name: pakistan
    tag: PGCCGV22
  - name: Pak Pro Team
    tag: 9G2QUL29
  - name: PAK ARMY!
    tag: Q0LR9GRV
  - name: Muslim legends.
    tag: R0RYGJ2P
  - name: The Rebels
    tag: L0V8CVUQ
  - name: IŃFĘŘÑØ々P.P.T
    tag: R0LVJRJY
  - name: ÔĞ々IŃFĘŘÑØ
    tag: GRQJYVJC
````
