### ISSUE TITLE
[New]: Familia TitanesDelCaos

### ISSUE THREAD

**Issue by Cesarbc02** [RoyaleAPI/family-config#1124]
### Family configuration

```yaml
name: TitanesDelCaos
key: TdC
color: orange
emblem: Skull_03
info:
  description: >
    ⚔️ ¡Bienvenidos a TitanesDelCaos! ⚔️
    🔥 Una familia de clanes donde la estrategia, el compañerismo y la diversión son la clave para la victoria. 🔥
    
    🎯 Requisitos:
    🕒 Participación activa en guerras de clanes y donaciones.
    🤝 Respeto y buen ambiente entre todos los miembros.
    
    👑 Lo que ofrecemos:
    🎉 Una comunidad activa y amigable.
    💡 Estrategias y consejos para mejorar tu juego.
    🏆 Recompensas épicas en guerras de clanes.
    📢 ¡Únete a TitanesDelCaos y demuestra que tienes lo necesario para ser el mejor! 💪
clans:
  - name: Pesca4t
    tag: LPCJL9P0
  - name: Pesca4t 2
    tag: G8LUVVYG
  - name: TitanesDelCaos
    tag: GLV89CRV
```

**Comment by karol-clash** [comment]
This is your corrected yaml
```yaml
name: TitanesDelCaos
key: titanesdelcaos
color: orange
emblem: Skull_03
info:
  description: >
    ⚔️ ¡Bienvenidos a TitanesDelCaos! ⚔️ 🔥 Una familia de clanes donde
    la estrategia, el compañerismo y la diversión son la clave para la victoria.
    🔥

    🎯 Requisitos: 🕒 Participación activa en guerras de clanes y donaciones. 🤝 Respeto y buen ambiente entre todos los miembros.

    👑 Lo que ofrecemos: 🎉 Una comunidad activa y amigable. 💡 Estrategias y consejos para mejorar tu juego. 🏆 Recompensas épicas en guerras de clanes. 📢 ¡Únete a TitanesDelCaos y demuestra que tienes lo necesario para ser el mejor! 💪
clans:
  - name: Pesca4t
    tag: LPCJL9P0
  - name: Pesca4t 2
    tag: G8LUVVYG
  - name: TitanesDelCaos
    tag: GLV89CRV
```

Your family config should be live in about an 30 minutes.
