### ISSUE TITLE
New Family request - Aliança BOTAEBIRA

### ISSUE THREAD

**Issue by TiagoNovais7** [RoyaleAPI/family-config#1125]
```yaml
name: Aliança BOTAEBIRA
key: botaebira
color: orange
emblem: Skull_05
sort: trophy
info:
  logo: https://www.canva.com/design/DAE58K8ZATg/sBZ3hxuaLwJY01gCQtl4AA/view?utm_content=DAE58K8ZATg&utm_campaign=designshare&utm_medium=link&utm_source=viewer
  description: >
Aliança BOTAEBIRA is dynamic Clash Royale community built on teamwork and a shared passion for the game. With a structured system of specialized clans, we offer something for every type of player. Together, we’ll rise to the top! **Apply in our Discord server!**
  social:
    - website: https://botaebira.pt
    - discord: https://discord.gg/H82um699rw
clans:
  - name: BOTAEBIRA
    tag: YCVJVGQU
  - name: BOTAEBIRA DOME
    tag: R899Y8PJ
  - name: BOTAEBIRA DOJO
    tag: QC0QQ0YC
```

**Comment by karol-clash** [comment]
I'm very impressed with your logo. However I was unable to download it. Please export it to .jpg or .png and send it directly here

**Comment by TiagoNovais7** [comment]
![Image](https://github.com/user-attachments/assets/023916c3-0715-41b1-a170-46e7ed1b10cc)

**Comment by TiagoNovais7** [comment]
Hi @karol-clash, are you able to download this one? Thank you!!

**Comment by karol-clash** [comment]
The changes should be live in about an hour

**Comment by TiagoNovais7** [comment]
The description bugged out - I already edited the yaml above. Is it possible for you to resubmit the changes?

**Comment by TiagoNovais7** [comment]
I made the needed changes in the yaml file above 👍

**Comment by karol-clash** [comment]
>  Is it possible for you to resubmit the changes?

Of course

**Comment by karol-clash** [comment]
This is your updated family config. It should be live in about an hour.
```yaml
name: Aliança BOTAEBIRA
key: botaebira
color: black
emblem: Skull_01
info:
  logo: botaebira.jpg
  description: >
    Aliança BOTAEBIRA is dynamic Clash Royale community built on teamwork and a shared passion for the game. With a structured system of specialized clans, we offer something for every type of player. Together, we’ll rise to the top! **Apply in our Discord server!**
  social:
    - website: https://botaebira.pt
clans:
  - name: BOTAEBIRA
    tag: YCVJVGQU
  - name: BOTAEBIRA DOME
    tag: R899Y8PJ
  - name: BOTAEBIRA DOJO
    tag: QC0QQ0YC
```
