### ISSUE TITLE
[New]: Otiv Family

### ISSUE THREAD

**Issue by manents** [RoyaleAPI/family-config#1130]
### Family configuration

```yaml
name: Otiv Family
key: otiv
color: purple
emblem: Lotus_02
sort: trophy
info:
  logo: 
  description: 
    **Top Italian Clan**
Otiv family number one in Italy and in the world, 17 clan that 17 Clans Aiming for the Top
social:
    - instagram: https://www.instagram.com/ot_manents?igsh=MWRsaDFyM3Y5NDdsMA%3D%3D&utm_source=qr
    - youtube:
https://youtube.com/@ot_alastor?si=1z1x3mKAgcUM5wJY
    - telegram:
https://t.me/+flqKGJfOnqE3Njc0

clans:
  - name: Otiv 
    tag: 890C9RJV
  - name: Otiv2
    tag: 9L2VLJLP
  - name: Otiv3
    tag: GRCJPL9R
  - name: Otiv4
    tag: 9VVUGQ8P
  - name: Otiv5
    tag: GVYJLC9J
  - name: Otiv6
    tag: QGUUPPYU
  - name: Otiv7
    tag: QL0R0VR8
  - name: Otiv8
    tag: QRP2JPGR
  - name: Otiv9
    tag: GYRU2VJQ
  - name: Otiv10
    tag: G89UC0L0
  - name: Otiv11
    tag: QRV0C8GJ
  - name: Otiv12
    tag: GYUCYJQV
  - name: Otiv13
    tag: G8J0VRC9
  - name: Otiv14
    tag: R9RCVQCV
  - name: Otiv15
    tag: QJPPCJV8
  - name: Otiv16
    tag: GQPYCJ0L
  - name: Otiv17
    tag: QCGGPYJ8
```

**Comment by karol-clash** [comment]
This is a corrected yaml config
```yaml
name: Otiv Family
key: otiv
color: purple
emblem: Lotus_02
sort: trophy
info:
  description: >
    **Top Italian Clan**
    Otiv family number one in Italy and in the world, 17 clan that 17 Clans Aiming for the Top
  social:
    - instagram: https://www.instagram.com/ot_manents
    - youtube: https://youtube.com/@ot_alastor
    - telegram: https://t.me/+flqKGJfOnqE3Njc0

clans:
  - name: Otiv 
    tag: 890C9RJV
  - name: Otiv2
    tag: 9L2VLJLP
  - name: Otiv3
    tag: GRCJPL9R
  - name: Otiv4
    tag: 9VVUGQ8P
  - name: Otiv5
    tag: GVYJLC9J
  - name: Otiv6
    tag: QGUUPPYU
  - name: Otiv7
    tag: QL0R0VR8
  - name: Otiv8
    tag: QRP2JPGR
  - name: Otiv9
    tag: GYRU2VJQ
  - name: Otiv10
    tag: G89UC0L0
  - name: Otiv11
    tag: QRV0C8GJ
  - name: Otiv12
    tag: GYUCYJQV
  - name: Otiv13
    tag: G8J0VRC9
  - name: Otiv14
    tag: R9RCVQCV
  - name: Otiv15
    tag: QJPPCJV8
  - name: Otiv16
    tag: GQPYCJ0L
  - name: Otiv17
    tag: QCGGPYJ8
```

Your family config should be live in about 30 minutes.
