### ISSUE TITLE
equality family

### ISSUE THREAD

**Issue by hawkeye-mukans** [RoyaleAPI/family-config#1131]
```yaml
name: eQuality Family
key: equality
color: blue
emblem: gold-1
info:
  logo: https://drive.google.com/file/d/1xJzCKRQBsNIxvTDc7F9U108X1ELS81mh/view?usp=drive_link
  description: >
    eQualtity community , top ladder/ranked clans , tournaments reward 
  social:
    - twitch: https://twitch.tv/collinz_tv
    - instagram: https://www.instagram.com/equality_clash_royale
    - telegram: https://t.me/ClashRoyaleeQuality
    - facebook: https://www.facebook.com/groups/263503500726487/
    - facebook: https://www.facebook.com/groups/clashroyaleofficials/?ref=share
    - web: https://linktr.ee/eQuality_clash_royale?utm_source=linktree_profile_share&ltsid=4329542b-f384-4966-a322-a3799a829514
    - ticktock: https://www.tiktok.com/@equalityclashroyale
clans:
  - name: eQuality ELITE
    tag: Q2CU82VC
  - name: eQuality Army
    tag: Q0CCCLUR
  - name: eQuality Empire
    tag: Q8J2YGJ2
  - name: eQuality GAME™️
    tag: QC20YGYQ
  - name: eQuality love
    tag: QQC09JQC
  - name: eQuality Aidan✨
    tag: LVV8LCRC
  - name: eQuality levia
    tag: QJJC9GQR
…
```
