### ISSUE TITLE
CapitãesDeAbril Family

### ISSUE THREAD

**Issue by ClaudjihoCosta** [RoyaleAPI/family-config#1133]
```yaml
name: CapitãesDeAbril 
key: capitaes
color: orange 
emblem: Fugi_01
info:
  logo: https://i.pinimg.com/736x/9d/7d/98/9d7d98ec45cca5c3c444aeff7a11de79.jpg
  description: >
    Os CapitãesDeAbril são uma família recente mas muito unida, o nosso foco são as guerras de clãs, e caminhamos juntos para conquistar a tuga
  social:
    - discord: https://discord.gg/NvPEUekA
clans:
  - name: CapitãesDeAbril
    tag: QQYPJR2Q
  - name: LaCantera
    tag: QJCP2PLQ
  ```
