### ISSUE TITLE
[New]: Request to add Jesus Christ Clan Family

### ISSUE THREAD

**Issue by belang-games** [RoyaleAPI/family-config#1134]
### Family configuration

```yaml
Pastname: Jesus Christ
key: ccrm
color: purple
emblem: flag_d_02
sort: trophy
info:
  logo: https://ccrm.us.to/images/theCrossBlood.svg
  description: >
"So whether you eat or drink or whatever you do, do it all for the glory of God."
                     1 Cor 10:31

**Missions**

Faith · Hope · Charity

We play in Christ's name and for His glory. Our mission is to become one of the leading Christian clans in the world. United in faith, we play for each other, striving to be a source of pride for all Christians in Clash Royale.


**The Teams:**
☆ 🟪 War Clan
☆ 🟥 Ladder Clan
☆ 🟦 Community Clan

“Teacher, which is the greatest commandment in the Law?” Jesus replied: “ ‘Love the Lord your God with all your heart and with all your soul and with all your mind.’ This is the first and greatest commandment. And the second is like it: ‘Love your neighbor as yourself.’ All the Law and the Prophets hang on these two commandments.” 
                     Matthew 22:36-40

  social:
    - website: https://ccrm.us.to
    - discord: https://discord.gg/c7WhggVTsW
clans:
  - name: Jesus Christ
    tag: Q8L02V8PC
  - name: Jesus Christ
    tag: QG8YQVRR
  - name: Jesus Christ
    tag: G2LQQG0Je
```

### Additional Info

![Image](https://github.com/user-attachments/assets/ff8b0963-7f85-4056-b2a0-b4cdffad31d6)
