### ISSUE TITLE
[New]: add clan family ChronicClashers 

### ISSUE THREAD

**Issue by Jo-chronicclashers** [RoyaleAPI/family-config#1135]
### Family configuration

```yaml
name: ChronicClashers  
key: chronicclashers  
color: yellow  
emblem: Shield_04  
info:  
  description: >  
    ChronicClashers Australian War Family, created day 1.  
  social:  
    - discord: https://discord.gg/XRwZFyPaSN
clans:  
  - name: ChronicClashers  
    tag: PRPQ  
  - name: lil chronics  
    tag: QCOLYJ9Q  
  - name: ChronicClasher2
    tag: RL90U9C9

sort: trophy
```

**Comment by Jo-chronicclashers** [comment]
Hello wondering if there was an update on this kindly

**Comment by LukasIsLost** [comment]
@Jo-chronicclashers 
Final revision of yaml. May take up to an hour to display due to cache.
```` yaml
name: ChronicClashers
key: chronicclashers
color: yellow
emblem: flag_b_03
sort: trophy
info:
  description: >  
    ChronicClashers Australian War Family, created day 1.
  social:
    - discord: https://discord.gg/XRwZFyPaSN
clans:
  - name: ChronicClashers
    tag: PRPQ
  - name: lil chronics
    tag: QCOLYJ9Q
  - name: ChronicClasher2
    tag: RL90U9C9
````
