### ISSUE TITLE
[Update]: Update Configuration for Mukans Family

### ISSUE THREAD

**Issue by Pimat13** [RoyaleAPI/family-config#1136]
### Family name

Mukans Family

### Family URL

https://royaleapi.com/clan/family/mukans/clans

### Family configuration

```yaml
name: Mukans Family
key: mukans
color: red
emblem: flag_k_04
info:
  logo: https://github.com/user-attachments/assets/3cc9cb75-a4c1-46d4-bde2-e318d28f4f31
  description: >
    Cerchiamo talenti attivi in war, pronti ad essere guidati e sostenuti dal nostro team di appassionati dediti al clan. 
    La nostra comunità si basa su valori come rispetto, serietà, dedizione e competitività. 
    Se anche tu ti rispecchi in questi valori e ambisci ad essere al TOP, allora è giunto il momento di staccarsi dal gregge e diventare anche tu un toro come noi! 
    **Che si vinca o che si perda, Forza Mukans! ...e Mede Merda!**
  social:
    - twitter: https://twitter.com/mukans6
    - instagram: https://www.instagram.com/mukans_official
    - facebook: https://www.facebook.com/Mukans_official
clans:
  - name: '#MuUuKaNs!!'
    tag: 8UJ2UUJ8
  - name: MuKaNs Darkness
    tag: LV2CLY8U
  - name: MuKaNs!Academy!
    tag: 9G00R8RR
  - name: MuKaNs Legends
    tag: Q9C9QJQ9
```

### Additional Info

![Image](https://github.com/user-attachments/assets/3cc9cb75-a4c1-46d4-bde2-e318d28f4f31)
