### ISSUE TITLE
[New] Los Serios

### ISSUE THREAD

**Issue by Javi-00** [RoyaleAPI/family-config#1137]
I can't drop a .yml file. This is the content:

```
name: Los Serios
key: serios
color: red
emblem: Crown_01
info:
  logo:
  description: >
    **Los Serios** es una familia de clanes competitivos en guerra. Tenemos dos clanes en la liga legendaria y una academia en la que puedes crecer rápidamente hasta poder pasar a uno de los clanes principales. Te esperamos!!!!
  social:
clans:
  - name: Los Serios
    tag: 9p9qvlcv
  - name: Los Serios 2
    tag: YLCRVUGQ
  - name: Serios Academy
    tag: GG02C8UY
```

**Comment by Javi-00** [comment]
Is there anything else that needs to be done to register the clan family?

**Comment by LukasIsLost** [comment]
@Javi-00 Final revision of yaml. May take up to an hour to display due to cache.

````yaml
name: Los Serios
key: serios
color: red
emblem: Crown_01
info:
  logo:
  description: >
    **Los Serios** es una familia de clanes competitivos en guerra. Tenemos dos clanes en la liga legendaria y una academia en la que puedes crecer rápidamente hasta poder pasar a uno de los clanes principales. Te esperamos!!!!
clans:
  - name: Los Serios
    tag: 9p9qvlcv
  - name: Los Serios 2
    tag: YLCRVUGQ
  - name: Serios Academy
    tag: GG02C8UY
````
