### ISSUE TITLE
[New]: CR.IN Family

### ISSUE THREAD

**Issue by SirLouen** [RoyaleAPI/family-config#1138]
### Family configuration

```yaml
name: Clash Royale International
key: crin
color: purple
emblem: Skull_01
info:
  logo: https://i.imgur.com/sFNUTqf.png
  description: >
    The Clash Royale International (CR.IN) Family is a group of clans entirely
    designed to reach the Top in Clan Wars Rankings. 
    Established in 2024, we have three things that make us unique: 
    1. 100% of our members are in our Discord. Discord activity is mandatory
    2. We have an Internal League with Prizes. We don't believe in CW prizes. 
    3. We target to win war perpetually. Everything is designed for this purpose.
  social:
    - discord: https://discord.gg/crin
clans:
  - name: CR.IN
    tag: Q8U2V8VJ
  - name: Awoken Ghosts
    tag: R90GVYPP
  - name: M.A.D
    tag: Q0RY2UR0
sort: trophy
```
