### ISSUE TITLE
[New] Montería family

### ISSUE THREAD

**Issue by breiner16** [RoyaleAPI/family-config#1140]
```yaml
name: Montería Arriba
key: Montería
color: yellow
emblem: Bamboo_04
info:
  logo: /static/img/branding/monteria.png
  description: >
Tratando de posicionar clanes de Montería en lo alto de CR
  social:
     
clans:
  - name: MACHIN
    tag: Q8P0RCCL
  - name: Elite Montería 
    tag: G2QQQLUY
```

**Comment by LukasIsLost** [comment]
@breiner16 Final revision of yaml. May take up to an hour to display due to cache.
````yaml
name: Montería Arriba
key: monteria
color: yellow
emblem: Bamboo_04
info:
  description: >
    Tratando de posicionar clanes de Montería en lo alto de CR

clans:
  - name: MACHIN
    tag: Q8P0RCCL
  - name: Elite Montería
    tag: G2QQQLUY
````
