### ISSUE TITLE
KOM Family YAML issue submission

### ISSUE THREAD

**Issue by gnitcellocpmats** [RoyaleAPI/family-config#1141]
'''Yaml
name: Kings Of Might War Family
key: KingsOfMight
color: orange
emblem: Flame_03
info:
  logo: https://imgur.com/a/ghj7F5F
  description: >
    The Kings of Might (KOM) was built on the standard of adversity and the building of doing what is right no matter the cost. We are an active family with many different clans for all types of gamers. We have current just over 1,200 members in our discord that is active every day. We also offer rewards for some of our clans!
  social:
    - discord: https://discord.gg/kom-family
clans:
  - name: Wow
    tag: Y2VCUUC92
  - name: Crying Fire
    tag: 8Y2LVVQ9 
  - name: Hawaiian Beast
    tag: P2RPJQ9R 
  - name: FUBAR
    tag: PGG2CYPG
  - name: dementiods
    tag: LJYJLPPQ
  - name: His Highness
    tag: P2UVLGU
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Love Ys Dior
    tag: G8J28GPL
  - name: Steriods gang
    tag: QRJ0VRY8
'''

**Comment by LukasIsLost** [comment]
@gnitcellocpmats Hi — multiple clans are currently in existing families.

Have leaders from all the following clans to confirm for this transfer by verifying their profile on the RoyaleAPI Discord server.
````
name: Crying Fire
tag: 8Y2LVVQ9

name: FUBAR
tag: PGG2CYPG

name: dementiods
tag: LJYJLPPQ

name: Clash Legends
tag: Q2QUQC2C
`````

RoyaleAPI Discord server: https://discord.royaleapi.com/

Go to the Discord server
Run !cr verify and follow instructions
Once every leader of these 6 clans have verified their profile on Discord and can confirm that they want to join your family, we will proceed with the change.
Thanks!

**Comment by daedalus214** [comment]
hi there!   So I am the Owner of "Kings of Might" clan family this is the list of clans and tags associated with "Kings of Might"
Wow #Y2VCUC92
Crying Fire #8Y2LVVQ9
Hawaiian Beast #P2RPJQ9R
Love Ys Dior #G8J28GPL
#Mercury09 #9U9QG890
Legends #LYP0VR2C
Sacred Dusk #R8UL0VL2
Star Shooters #G0YQQU0U
KoM L2W #GRQ0LYCQ

**Comment by LukasIsLost** [comment]
@daedalus214 Final yaml pls save for later editing
```` yaml
name: Kings Of Might War Family
key: kingsofmight
color: orange
emblem: Flame_03
info:
    logo: /static/img/brands/logo/kings-of-might.png
    description: >
      The Kings of Might (KOM) was built on the standard of adversity and the building of doing what is right no matter the cost. We are an active family with many different clans for all types of gamers. We have current just over 3000 members in our discord that is active every day. We also offer rewards for some of our clans!
    social:
      - discord: https://discord.gg/kom-family
clans:
  - name: Wow
    tag: Y2VCUC92
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Hawaiian Beast
    tag: P2RPJQ9R
  - name: Love Ys Dior
    tag: G8J28GPL
  - name: "#Mercury09"
    tag: 9U9QG890
  - name: LEGENDS
    tag: LYP0VR2C
  - name: Sacred Dusk
    tag: R8UL0VL2
  - name: star shooters
    tag: G0YQQU0U
  - name: KoM L2W
    tag: GRQ0LYCQ
````
