### ISSUE TITLE
[Update]: Aliança Lusa

### ISSUE THREAD

**Issue by cubernix** [RoyaleAPI/family-config#1143]
### Family name

Aliança Lusa Family

### Family URL

Copy the link (URL address) fromhttps://royaleapi.com/clan/family/aliancalusa/clans your browser and paste it here.

### Family configuration

```yaml
Family name
Aliança Lusa

Family URL
https://royaleapi.com/clan/family/aliancalusa/clans

Family configuration
name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_04
info:
  logo: https://limewire.com/d/3796b104-2b8a-477e-b669-91ef80795e07#mMZpZX1iYNmirmSaNsJzXTIzPjOJyCnzxqSet1HTSx8
  description: >
    A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022, o segundo a 21/10/2022 e o terceiro a 22/06/2023, já está no topo do ranking de Portugal em troféus e ligas. Além disso, contamos com um clã de férias, o Aliança Lusa Ⓡ, para quem precisa de uma pausa sem sair da comunidade. Somos um clã extremamente ativo em guerras, com comunicação constante via Discord e WhatsApp, além de realizarmos torneios internos frequentes com prémios incríveis. Se procuras um clã competitivo, organizado e com espírito de equipa, esta é a tua oportunidade. Atreve-te a juntar-te a nós! 

    The Aliança Lusa Family, whose main clan was created on 09/18/2022, the second on 10/21/2022, and the third on 06/22/2023, is already at the top of the Portugal ranking in trophies and leagues. We also have a vacation clan, Aliança Lusa Ⓡ, for those who need a break without leaving the community. We are an extremely active war clan, with constant communication via Discord and WhatsApp, as well as frequent internal tournaments with amazing prizes. If you are looking for a competitive, organized clan with a strong team spirit, this is your chance. Dare to join us!

  social:
    - discord: https://discord.gg/SqtyGHAzQN

clans:
  - name: Aliança Lusa
    tag: Q0R08YLJ
  - name: Aliança Lusa 2
    tag: Q20GUCV8
  - name: Aliança Lusa 3
    tag: GC92VYJP
  - name: Aliança Lusa Ⓡ
    tag: QQ9QP9JJ
```

### Additional Info

The update it to change description and logo. Thanks!
