### ISSUE TITLE
[Update]: !Baked! Family update

### ISSUE THREAD

**Issue by Bull0715** [RoyaleAPI/family-config#1144]
### Family name

Put your the current name here

### Family URL

Copy the link (URL address) from your browser and paste it here.

### Family configuration

```yaml
name: Baked Family of Clans
key: baked
color: olive
emblem: Skull_06
info:
  description:
    War clan family that is solely focused on war.  We strive to offer a fun, competitive, toxic free environment. As you travel through the clans, you'll find different stages of difficulties If you need a relaxing war clan, we have that too.  All clans are run with similar mindsets so what you come to love in one clan, you'll find in all of our clans and each will feel like home.
  social:
    - discord: https://discord.gg/tGJRuxaCgB
clans:
  - name: "!Baked! 2.0"
    tag: YRVC9QVJ
  - name: "!Baked! 1.5"
    tag: LUCQVPRV
  - name: "BBN"
    tag: QLUUVQ
  - name: "!Baked! 2.5"
    tag: G9LRRP82
  - name: "!Baked! 1.0"
    tag: GURCRRY9
  - name: "!Baked! 3.0"
    tag: QJU8P80C
  - name: "!Baked! 3.5"
    tag: QVY92JLV
  - name: "!Baked! 4.0"
    tag: QVLYR0P8
ML config here
```
