### ISSUE TITLE
Integrating our new family clan "Les Bots"

### ISSUE THREAD

**Issue by youssef-lecodeur** [RoyaleAPI/family-config#1145]
Hello, I am Youssef, I am the Leader and the Administrator of the family clan Les Bots in French, if it's possible I want to integrate it in RoyaleAPI, and you can find in the Google Drive link the YAML file that contains all info of our family clan (the logo is a Google Drive link, you can download it, it's open).
Thanks for your attention
Youssef Ben Mrad and LaFraudeDu59
Link of the YAML file (Google Drive) : 
[YAML](https://drive.google.com/file/d/1OAu5vH0kEML1SUwGV2rr5qI1tonceJQs/view?usp=sharing)
Link of the icon file (JPG, Google Drive) : 
[Icon](https://drive.google.com/file/d/18pUn7qhIExGra-hUE9oGJ7nHtkgEkJuh/view?usp=sharing)
Link of the folder (Google Drive) : 
[Folder](https://drive.google.com/drive/folders/1_q3yv6KzWj9VSY-_sD-Y0DT3uRThYibz?usp=sharing)
YAML file : 
```yaml
name: Les Bots
key: les-bots
color: yellow
emblem: A_Char_Barbarian_03
info:
  logo: https://drive.google.com/file/d/18pUn7qhIExGra-hUE9oGJ7nHtkgEkJuh/view?usp=sharing
  description: >
    Une famille de clans composée de 4 clans -> Les Bots, 1Ciel,
    Team FR et Les Clovis. Nous sommes un groupe de joueurs amicaux,
    actifs et compétitifs. Nous jouons en duel et participons à la GDC. 
    Nous recherchons des joueurs actifs, calmes et amicaux pour rejoindre notre famille. 
    Discord requis.
  social: 
    - discord: https://discord.gg/RjtBkE9w
clans: 
  - name: ★les bots™★ A
    tag: QCPY9UCR
  - name: TEAM FR
    tag: Q0VQ9J0Y
  - name: 1Ciel
    tag: G9GJC229
  - name: Les Clovis
    tag: QCQ2CVV9
sort: trophy
```
