### ISSUE TITLE
4/4/2025 - Please add new family

### ISSUE THREAD

**Issue by TwitchTvAbeLaia** [RoyaleAPI/family-config#1147]
```yaml
name: Twitch.Tv/AbeLaia
key: twitchtvabelaia
color: yellow
emblem: Skull_01
info:
  description: >
    Step 1: Create 50 clans
    Step 2: Organize Tournaments
    Step 3: ???
    Step 4: CONQUER THE WORLD!!
clans:
  - name: TwitchTvAbeLaia
    tag: QULLRGLG
  - name: TwitchTvAbeLaia
    tag: GQQLLVCG
  - name: TwitchTvAbeLaia
    tag: QCRVGJUU
  - name: TwitchTvAbeLaia
    tag: GPP90GYP
```
