### ISSUE TITLE
Getting listed in RoyaleApi.com

### ISSUE THREAD

**Issue by avivcr2010** [RoyaleAPI/family-config#1149]
```yaml
name: Stinky Feet Family
key: Stinky Feet
color:Blue & White
emblem: flag_g_01.png
Clans:
- name: Stinky Feet 2
   tag: #G8CC8QC0

```
