### ISSUE TITLE
RoyaleAPI.com

### ISSUE THREAD

**Issue by avivcr2010** [RoyaleAPI/family-config#1150]
### Family configuration

```yaml
name: Stinky Feet Family
key: Stinky Feet
color: blue 
emblem: flag_g_01
Clans:
- name: Stinky Feet 2
   tag: G8CC8QC0
```
