### ISSUE TITLE
[New]: Clan ORŁY OSOWA

### ISSUE THREAD

**Issue by walaszek10** [RoyaleAPI/family-config#1151]
### Family configuration

```yaml
name: ORŁY OSOWA
key: OSOWA
color: blue
emblem: Tower_01
info:
  logo: https://www.google.com/url?sa=i&url=http%3A%2F%2Fksosowa.futbolowo.pl%2F%3Fmobiledetection%3D0&psig=AOvVaw3SrxnJRiQPHvrYswTcJ8hU&ust=1744986649945000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKDi7_uj34wDFQAAAAAdAAAAABAE
  description: >
    **Grać cw kurwy**
    Tylko aktywni
    Za pierwsze miejsce w cw elder.
  social:
    - instagram: https://www.instagram.com/orly_osowa
clans:
  - name: ORŁY OSOWA
    tag: QCRCCG8U
```
