### ISSUE TITLE
British Army family

### ISSUE THREAD

**Issue by yeetlord1710** [RoyaleAPI/family-config#1153]
```yaml
name: British Army family
key: BritishArmyCR
color: white
emblem: Flag_D_02.png
info:
  logo: badges/flag_d_02.png
  description: 🇬🇧 British Army 🇬🇧
Top 25 UK — where Hog Riders salute and Golems queue in formation.

We clash hard, BM harder, and always have a cheeky Fireball ready for that overconfident Elixir Collector.
Deck diversity? Immaculate. Skill level? Untouchable. Tea consumption? Worrying.

Proud HQ of the British Army Family - 9 clans strong and growing faster than a Rage-boosted Lumberjack.
One of our kin is also Top 75 UK, because we don’t just win — we multiply.

We’re the oldest clan in the game. Seriously — we’ve been here since Clash was in nappies. Our first war was fought over dial-up. One member still logs in from a Nokia. We don’t just have history — we are the museum.

War beasts, ladder sweats, emote spammers — all welcome (as long as you’ve got the chops).
Join us or get 3-crowned trying. 💂‍♂️🔥
  social:
    - discord: https://discord.gg/CmqZenUwn3
clans:
  - name: British Army
    tag: 2G0UJY
  - name: British Army™️
    tag: GG09CP20
  - name: British Army TA
    tag: GY2V99VL
  - name: British Army 1
    tag: R0CJGJ0U
  - name: British Army 2
    tag: 2LL8LC2R
  - name: British Army 3
    tag: R0QG2LVU
  - name: British Army 5
    tag: R28YVJQ0
  - name: British Army 6
    tag: R9C2820Q
  - name: British Army 7
    tag: RPYR28GJ
  - name: British Army 8
    tag: QU2PLYPG
```

**Comment by LukasIsLost** [comment]
Done. May take up to an hour to display due to cache.
````yaml
name: British Army family
key: britisharmycr
color: white
emblem: flag_d_02
info:
  description: >
    🇬🇧 British Army 🇬🇧
    Top 25 UK — where Hog Riders salute and Golems queue in formation.
    
    We clash hard, BM harder, and always have a cheeky Fireball ready for that overconfident Elixir Collector.
    Deck diversity? Immaculate. Skill level? Untouchable. Tea consumption? Worrying.
    
    Proud HQ of the British Army Family - 9 clans strong and growing faster than a Rage-boosted Lumberjack.
    One of our kin is also Top 75 UK, because we don’t just win — we multiply.
    
    We’re the oldest clan in the game. Seriously — we’ve been here since Clash was in nappies. Our first war was fought over dial-up. One member still logs in from a Nokia. We don’t just have history — we are the museum.
    
    War beasts, ladder sweats, emote spammers — all welcome (as long as you’ve got the chops).
    Join us or get 3-crowned trying. 💂‍♂️🔥
  social:
    - discord: https://discord.gg/CmqZenUwn3
clans:
  - name: British Army
    tag: 2G0UJY
  - name: British Army™️
    tag: GG09CP20
  - name: British Army TA
    tag: GY2V99VL
  - name: British Army 1
    tag: R0CJGJ0U
  - name: British Army 2
    tag: R0P8RPJ0
  - name: British Army 3
    tag: R0QG2LVU
  - name: British Army 5
    tag: R28YVJQ0
  - name: British Army 6
    tag: R9C2820Q
  - name: British Army 7
    tag: RPYR28GJ
  - name: British Army 8
    tag: QU2PLYPG
````
