### ISSUE TITLE
[New]: BRAZURK BR FAMÍLIA

### ISSUE THREAD

**Issue by netord7** [RoyaleAPI/family-config#1154]
### Family configuration

```yaml
Paste your YAMLname: FAMÍLIA BRAZURK BR
key: BRAZURK-BR
color: orange
emblem: Skull_01
info:
  logo: https://imgur.com/a/0RoTksC
  description: >
    Bem-Vindos a Familia BZK - Clã Focado em Guerras - Pontuação mínima em Guerras 1600pts - Em Breve Top Global! Code:RoyaleAPI
  social:
    - tiktok: https://www.tiktok.com/@brazurkzwar?_t=ZM-8vm936oQ0xT&_r=1

clans:
  - name: BRAZURK BR
    tag: GQVU9QVQ
```
