### ISSUE TITLE
Bonjour Ajout d'une nouvelle famille french, merci

### ISSUE THREAD

**Issue by NijiGLB** [RoyaleAPI/family-config#1155]
```yaml
name: Famille French-
key: family-french
color: orange
emblem: flag_k_01.png
info:
  logo: /static/img/brands/logo/orangejuice.png
  description: >
    ** Comment ils font les chasseurs pour savoir si c'est un canard à l'orange ?"

    🇫🇷 Famille des Clans French- 🇫🇷. 
    💥 GDC obligatoire 💥 
    Exigence ⚠️ et Respect 
    
    discord
    [https://discord.com/invite/yyMy762S7X](https://discord.com/invite/yyMy762S7X)
  social:
    - discord: https://discord.com/invite/yyMy762S7X
clans:
  - name: French-Spirit
    tag: GOUVGP
  - name: French-Legend
    tag: QL0JCVCR
  - name: French-mans
    tag: QCRRPYCU
```

**Comment by LukasIsLost** [comment]
Done. May take up to an hour to display due to cache.

````yaml
name: Famille French-
key: family-french
color: orange
emblem: flag_k_01.png
info:
  logo: /static/img/brands/logo/orangejuice.png
  description: >
    ** Comment ils font les chasseurs pour savoir si c'est un canard à l'orange ?"

    🇫🇷 Famille des Clans French- 🇫🇷. 
    💥 GDC obligatoire 💥 
    Exigence ⚠️ et Respect 

  social:
    - discord: https://discord.com/invite/yyMy762S7X
clans:
  - name: French-Spirit
    tag: GOUVGP
  - name: French-Legend
    tag: QL0JCVCR
  - name: French-mans
    tag: QCRRPYCU
````
