### ISSUE TITLE
[NUEVO] Agregar familia tds3

### ISSUE THREAD

**Issue by BluNr** [RoyaleAPI/family-config#1157]
```yaml
name: The dark side 3
key: darkside3
color: red
emblem: Cherry_Blossom_03
sort: trophy
info:
  description: >
    Clan de la bruja madre kary

clans:
  - name: the dark side 3
    tag: 88PRJYJY
  - name: the dark side 3
    tag: QRPJJY8
```
