### ISSUE TITLE
[Update]: Add Clans, Change Logo

### ISSUE THREAD

**Issue by BlablablaMart** [RoyaleAPI/family-config#1158]
### Family name

Blablabla Familie

### Family URL

https://royaleapi.com/clan/family/blablabla/clans

### Family configuration

```yaml
name: Blablabla Familie
key: blablabla_familie
color: black
emblem: 
  logo: ![Image](https://github.com/user-attachments/assets/d4947a0c-406d-4703-95f0-9f0c1b05fb78)
  description: >
    Willkommen bei  Blablabla. In unseren 7 unterschiedlichen Clans findet jeder leidenschaftliche Spieler das passende Zuhause. Als Team zu Sieg. Zusammenhalt und Spaß am Spiel werden bei uns GROSS geschrieben. Wir bieten zB. DC, Turniere,  Duos und Pass Royale. Wechsel innerhalb der Familie möglich. Das klingt gut? Unser Main Clan gehört zu den besten Kriegsclans in Deutschland oder doch lieber unsere gechillte Clanoase? Wir freuen uns über jeden aktiven Spieler
clans:
  - name: Blablabla
    tag: 98RVLCUY
  - name: Blablabla#2
    tag: LJGJV9YY
  - name: Blablabla#3
    tag: GL0JQR88
  - name: Blablabla4ever
    tag: QYR92VC8
  - name: BBB Legends^TM
    tag: GGRYVVU0 
  - name: Die Starken
    tag: LUQ8P8Y
  - name: Gentleman Jack
    tag: 9VLJRY2J
```

### Additional Info

![Image](https://github.com/user-attachments/assets/d4947a0c-406d-4703-95f0-9f0c1b05fb78)

**Comment by LukasIsLost** [comment]
Done. May take up to an hour to display due to cache.
````yaml
name: Blablabla Familie
key: blablabla_familie
color: black
emblem: Flame_04
info:
  logo: /static/img/brands/logo/blablabla.jpg
  description: >
    Willkommen bei  Blablabla. In unseren 7 unterschiedlichen Clans findet jeder leidenschaftliche Spieler das passende Zuhause. Als Team zu Sieg. Zusammenhalt und Spaß am Spiel werden bei uns GROSS geschrieben. Wir bieten zB. DC, Turniere,  Duos und Pass Royale. Wechsel innerhalb der Familie möglich. Das klingt gut? Unser Main Clan gehört zu den besten Kriegsclans in Deutschland oder doch lieber unsere gechillte Clanoase? Wir freuen uns über jeden aktiven Spieler
clans:
  - name: Blablabla
    tag: 98RVLCUY
  - name: Blablabla#2
    tag: LJGJV9YY
  - name: Blablabla#3
    tag: GL0JQR88
  - name: Blablabla4ever
    tag: QYR92VC8
  - name: BBB Legends^TM
    tag: GGRYVVU0
  - name: Die Starken
    tag: LUQ8P8Y
  - name: Gentleman Jack
    tag: 9VLJRY2J
````
