### ISSUE TITLE
[Update] Elites Royale - LaTroncoFamiglia

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#1160]
Hi, since we merged "elites royale" family with "la troncofamiglia" family we want to keep just elites royale's page.
Thanks for your service as always.

```yaml

name: Elites⚡️Royale
key: elites
color: green
emblem: flag_k_04
info:
  description: >
  **Benvenuti nella
famiglia Elites Royale!

Insieme a Porci Dannati ed
alla Troncofamiglia per
un ambiente sempre più
positivo e competitivo.**


No comportamenti infantili,
no spam, no bestemmie
e NESSUN tipo di
discriminazione religiosa,
razziale o di genere.

Per info, o per entrare a
far parte della famiglia,
contattarci sui social
presenti qui sotto

discord distra_itsme ;
telegram @lupo_05 , @pytosclashroyale ;
whatsapp +393293516711 ,
+393358257031.

social:
  - discord: https://discord.com/users/333707110821134347
  - telegram: https://t.me/lupo05
  - telegram: https://t.me/pytosclashroyale
  - whatsapp: https://wa.me/393293516711
  - whatsapp: https://wa.me/393358257031

clans:
  - name: Elites⚡Royale™
    tag: LLGQQ8C2
  - name: Porci Dannati
    tag: 2VUJ0YQJ
  - name: Elites⚡Royale2™
    tag: LLU8RGQ8
  - name: ELITES⚡LEGION™
    tag: QRQG202Y
  - name: porci accsdemy
    tag: LCC0LJU2
  - name: La Troncoradice
    tag: YV2UJ0GV
  - name: Elites⚡️Family
    tag: Q92LYQJL
  - name: Elites⚡️Patata
    tag: GCY0LJ0C
  - name: Elites In Ciabt
    tag: GJQPL29P
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoseme
    tag: QQLVQ20V
  - name: La Troncospizio
    tag: L229VYRG

```

**Comment by LukasIsLost** [comment]
Hi — multiple clans are currently in an existing family

Please have all leaders from the following clans to confirm for this transfer by verifying their profile on the RoyaleAPI Discord server.
````
name: La Troncoradice
tag: YV2UJ0GV

name: La Nuova Tronco
tag: LVVQQ2L8

name: La Troncoseme
tag: QQLVQ20V
````
RoyaleAPI Discord server: https://discord.royaleapi.com/

Go to the Discord server
Run ````!cr verify```` and follow instructions
Once every leader of these 3 clans have verified their profile on Discord and can confirm that they want to join your family, we will proceed with the change.

The following clans were not included because they have 0 members.
````
name: La SuperTronco
tag: L8YVLJG8

name: La Troncopoli
tag: LYV0PGR9

name: La Troncobase
tag: QR9Y8028

 name: La Troncospizio
tag: L229VYRG
````

This is the final yaml for now.
````yaml
name: Elites⚡️Royale
key: elites
color: green
emblem: flag_k_04
info:
  logo_cdn: /static/img/family/logo/elites-royale.jpg
  description: >
    **Benvenuti nella
    famiglia Elites Royale!
    
    Insieme a Porci Dannati ed
    alla Troncofamiglia per
    un ambiente sempre più
    positivo e competitivo.**
    
    
    No comportamenti infantili,
    no spam, no bestemmie
    e NESSUN tipo di
    discriminazione religiosa,
    razziale o di genere.
    
    Per info, o per entrare a
    far parte della famiglia,
    contattarci sui social
    presenti qui sotto
    
    discord distra_itsme ;
    telegram @lupo_05 , @pytosclashroyale ;
    whatsapp +393293516711 ,
    +393358257031.

  social:
  - discord: https://discord.com/users/333707110821134347
  - telegram: https://t.me/lupo05
  - telegram: https://t.me/pytosclashroyale
  - whatsapp: https://wa.me/393293516711
  - whatsapp: https://wa.me/393358257031

clans:
- name: Elites⚡Royale™
  tag: LLGQQ8C2
- name: Porci Dannati
  tag: 2VUJ0YQJ
- name: Elites⚡Royale2™
  tag: LLU8RGQ8
- name: ELITES⚡LEGION™
  tag: QRQG202Y
- name: porci accsdemy
  tag: LCC0LJU2
- name: Elites⚡️Family
  tag: Q92LYQJL
- name: Elites⚡️Patata
  tag: GCY0LJ0C
- name: Elites In Ciabt
  tag: GJQPL29P
````

**Comment by LaTronco** [comment]
Hi, I've just did it, is everything ok? Thanks!

Also I've seen an error in the description
I think "distra_itsme and @Lupo_05" needs to be written with a backslash before the 2 underscores to prevent from being seen as italic markdown
Thanks and sorry for my mistake

**Comment by LukasIsLost** [comment]
Yes, everything is fine. I have now added the three clans and added the two Backslashes.
````yaml
name: Elites⚡️Royale
key: elites
color: green
emblem: flag_k_04
info:
  logo_cdn: /static/img/family/logo/elites-royale.jpg
  description: >
    **Benvenuti nella
    famiglia Elites Royale!
    
    Insieme a Porci Dannati ed
    alla Troncofamiglia per
    un ambiente sempre più
    positivo e competitivo.**
    
    
    No comportamenti infantili,
    no spam, no bestemmie
    e NESSUN tipo di
    discriminazione religiosa,
    razziale o di genere.
    
    Per info, o per entrare a
    far parte della famiglia,
    contattarci sui social
    presenti qui sotto
    
    discord distra\_itsme ;
    telegram @lupo\_05 , @pytosclashroyale ;
    whatsapp +393293516711 ,
    +393358257031.

  social:
  - discord: https://discord.com/users/333707110821134347
  - telegram: https://t.me/lupo05
  - telegram: https://t.me/pytosclashroyale
  - whatsapp: https://wa.me/393293516711
  - whatsapp: https://wa.me/393358257031

clans:
- name: Elites⚡Royale™
  tag: LLGQQ8C2
- name: Porci Dannati
  tag: 2VUJ0YQJ
- name: Elites⚡Royale2™
  tag: LLU8RGQ8
- name: ELITES⚡LEGION™
  tag: QRQG202Y
- name: porci accsdemy
  tag: LCC0LJU2
- name: La Troncoradice
  tag: YV2UJ0GV
- name: Elites⚡️Family
  tag: Q92LYQJL
- name: Elites⚡️Patata
  tag: GCY0LJ0C
- name: Elites In Ciabt
  tag: GJQPL29P
- name: La Nuova Tronco
  tag: LVVQQ2L8
- name: La Troncoseme
  tag: QQLVQ20V**
````
