### ISSUE TITLE
please add a new clan family "Juggernaut"

### ISSUE THREAD

**Issue by Nail2000** [RoyaleAPI/family-config#1163]
```yaml
name: JUGGERNAUT Clan Family
key: juggernaut
color: green
emblem: Skull_05
info:
 logo: https://drive.google.com/file/d/1N8qkSo-FjVbFO2TfJgr4meZyws13yjwI/view?usp=drivesdk
  description: >
 The Juggernaut family is one of the oldest and biggest families in Clash Royale with our best players  and 5 clans!
    Since creation, we as a family and individual players have grown immensely and continue to today.
    We believe that’s the reason why we have come so far.
    The family is a place for everyone, as our members come from all around the world, from casual to competitive players, old to young, active to very active and so on.
    We all share a fellow passion for the game, are friendly, help each other out with the same goal: to always improve our skills and have a great time!
    Join the Family. Become a Legend!
  social:
 - telegram: https://t.me/Jugger66
clans:
 - name: "Juggernaut"
    tag: 8CUQYQGY
 - name: FrostLegion
    tag: 2YUJJJQY
 - name: MARKO
    tag: 2LC2Y208
 - name: HeaveN-NatioN™
    tag: 8RQPULLG
 - name: Fight Club
    tag: G28GPPV9
 - name: Steel Warriors
    tag: PVQYR8R8
```
