### ISSUE TITLE
[New]: GLI SPARTANI

### ISSUE THREAD

**Issue by Antonio-muk** [RoyaleAPI/family-config#1165]
### Family configuration

```yaml
yaml
name: Spartan Family
description: Una famiglia di clan unita dalla forza e dalla strategia.
color: red
emblem: star_shine_03
clans:
  - tag: #GRR9CLLP
    name: Gli Spartani 4
  - tag: #QPPVVUVU
    name: Gli Spartani 1
  - tag: #GLCL8U29
    name: Gli Spartani 2
  - tag: #Q8PPRY28
    name: Gli Spartani 10
  - tag: #QR8GUQ9Y
    name: Gli Spartani 14
  - tag: #QJ9929YU
    name: Gli Spartani 12
  - tag: #L8CY999L
    name: Gli Spartani 8
```
