### ISSUE TITLE
[New]: Les Broyeurs Family

### ISSUE THREAD

**Issue by Walix74200** [RoyaleAPI/family-config#1171]
### Family configuration

```yaml
name: Les Broyeurs Family
key: lesbroyeurs
color: blue
emblem: Bolt_03
sort: trophy
info:
  logo: https://i.imgur.com/3Hi0WcV.png
  description: >
    **Force, stratégie et entraide au cœur des Alpes suisses.**
    Les Broyeurs Family est une organisation née en Suisse, rassemblant deux clans soudés par la passion du jeu et l’esprit d’équipe.
    Depuis notre création, nous visons à offrir un environnement compétitif mais bienveillant, où chaque joueur peut progresser à son rythme.
    Rejoindre Les Broyeurs, c’est faire partie d’une famille où la communication, l’entraide et l’honneur sont les maîtres-mots.

    Nous participons régulièrement aux guerres de clans et encourageons nos membres à atteindre l'excellence, que ce soit en ladder ou en compétition.
    Ouverts à tous les niveaux, nous offrons un foyer stable pour les joueurs actifs cherchant une vraie structure, mais aussi une ambiance détendue et francophone.
clans:
  - name: Les Broyeurs
    tag: 22PVRQC
  - name: Les Broyeurs 2
    tag: GPL9JORJ
```
