### ISSUE TITLE
Bacon Burgers

### ISSUE THREAD

**Issue by charliej344** [RoyaleAPI/family-config#1174]
```yaml
name: Bacon Burger Family
key: BaconBurgerFamily
color: yellow
emblem: Orange_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    The Bacon Burger Family is a family that houses one competitive and friendly clan called bacon burgers. Everyone is welcome in the clan and we are looking for other players who are pushing to become on the leaderboard and grow together.
clans:
  - name: Bacon Burgers
    tag: GGGCVLRO
```
