### ISSUE TITLE
New family clan

### ISSUE THREAD

**Issue by alcyares** [RoyaleAPI/family-config#1175]
```yaml
name: UNDERWORLD
key: underworld
color: black
emblem: flag_j_03
info:
  logo: https://celinepicard.fr/royaleapi/underworld.png
  description: >
 The **UNDERWORLD Clan Family (UCF)** consists of two clans: **UNDERGROUND**, dedicated to intense clan wars, and **UNDERCONTROL**, designed for rest and donations.
 UCF is a welcoming place for everyone! Our members come from all over the world and represent a wide range of profiles: from casual players to fierce competitors, young to experienced, moderately active to highly involved. We're all united by a shared passion for the game, friendliness, generosity in donations, and constant mutual support.
  social:
    - discord: https://discord.gg/MtTcrcxbNe
clans:
  - name: UNDERGROUND
    tag: Q92V8PJQ
  - name: UNDERCONTROL
    tag: QUVVLYP8
```
