### ISSUE TITLE
[Update]: 鬼滅の刃 Clan Family #1048

### ISSUE THREAD

**Issue by xShadow12GH** [RoyaleAPI/family-config#1176]
### Family name

Name: 鬼滅の刃 Clan Family

### Family URL

https://royaleapi/.com/clan/family/kny/clans

### Family configuration

```yaml
Name: 鬼滅の刃 Clan Family
Key: kny
Color: purple
Emblem: Twin_Peaks_01
Info:
  Logo: /static/img/brands/logo/KNY.png
  Description: >
    The **鬼滅の刃 Clan Family** (鬼滅の刃CF)
    is a group of clans related to Kimetsu no Yaiba fans who want a clan family dedicated to themselves.
Anyone can join to any of the clans if the rules are followed.
  Social:
    - discord: https://discord.gg/YddcySU5B
Clans:
-	Name: 鬼滅の刃 | Clan
    Tag: LLUYGCRR
-	Name: 鬼滅の刃 | 竈門 炭治郎
    Tag: LV2C299J
-	Name: 鬼滅の刃 | Lvl 1
    Tag: GP2LYPYG
-	Name: ボット
    Tag: UQCY8P8
-	Name: スーパーセル | Lvl 1
    Tag: RLLLULL0

### Additional Info

https://royaleapi.com/clan/family/kny/clans
royaleapi.yml
```
