### ISSUE TITLE
Famille Mac Leod

### ISSUE THREAD

**Issue by Kristeauf** [RoyaleAPI/family-config#1178]
```yaml
name: Famille Mac Leod
key: Mac Leod
color: blue
emblem: Sword_03
info:
  logo: /static/img/branding/ml-logo.png
  description: >
   A toi qui es un vrai guerrier...qui ne lâches jamais rien?... et qui survit à toutes les guerres de clan? Rejoins les immortels.




  social:
    
    - discord: https://discord.gg/VMy49RyXWS
    
clans:
  - name: Mac Leod
    tag: 22QCGUCU
  - name: Mac Leod II
    tag: LJ0R82VG
  - name: Mac Leod III
    tag: GYYL0YYL
  ```

![Image](https://github.com/user-attachments/assets/acd46afc-31ae-469f-8a54-8a55b5a6e63c)
