### ISSUE TITLE
让我们一起上分

### ISSUE THREAD

**Issue by avengerforever** [RoyaleAPI/family-config#118]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:让我们一起上分
key:学生党
color:purple
emblem:none
info:trophy
  logo:/static/img/brands/logo/freeze
  description: >
    none.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:让我们一起鱼死网破
    tag:PLPQRYYR
  - name:让我们一起学猫叫(●—●)
    tag:PURPQ8QC
```

**Comment by smlbiobot** [comment]
```yml
name: 让我们一起上分
key: student
color: purple
clans:
  - name: 让我们一起鱼死网破
    tag: PLPQRYYR
  - name: 让我们一起学猫叫(●—●)
    tag: PURPQ8QC
```
