### ISSUE TITLE
[New]:

### ISSUE THREAD

**Issue by Kristeauf** [RoyaleAPI/family-config#1180]
### Family configuration

```yaml
Paste 
name: Famille Mac Leod
key: mac leod
color: blue
emblem: Sword_03
info:
  logo: /static/img/branding/ml-logo.png
  description: >
   A toi qui es un vrai guerrier...qui ne lâches jamais rien?... et qui survit à toutes les guerres de clan? Rejoins les immortels.




  social:
    
    - discord: https://discord.gg/VMy49RyXWS
    
clans:
  - name: Mac Leod
    tag: 22QCGUCU
  - name: Mac Leod II
    tag: LJ0R82VG
  - name: Mac Leod III
    tag: GYYL0YYL
```

### Additional Info

![Image](https://github.com/user-attachments/assets/8d46c3fb-32a8-468e-a581-4d7d79b187ac)
