### ISSUE TITLE
[New]: Famille Mac Leod

### ISSUE THREAD

**Issue by Kristeauf** [RoyaleAPI/family-config#1183]
### Family configuration

```yaml
name: Famille Mac Leod
key: mac leod
color: blue
emblem: Sword_03
info:
  logo: /static/img/branding/ml-logo.png
  description: >
   A toi qui es un vrai guerrier...qui ne lâches jamais rien?... et qui survit à toutes les guerres de clan? Rejoins les immortels.




  social:
    
    - discord: https://discord.gg/VMy49RyXWS
    
clans:
  - name: Mac Leod
    tag: 22QCGUCU
  - name: Mac Leod II
    tag: LJ0R82VG
  - name: Mac Leod III
    tag: GYYL0YYL
```

### Additional Info

![Image](https://github.com/user-attachments/assets/55a4cc2b-6ac5-49f4-9e51-8ddcc1c82c51)
