### ISSUE TITLE
[New]: Famille Mac Leod

### ISSUE THREAD

**Issue by Kristeauf** [RoyaleAPI/family-config#1184]
### Family configuration

```yaml
name: Famille Mac Leod
key: mac leod
color: blue
emblem: Sword_03
info:
  logo: /static/img/branding/ml-logo.png
  description: >
   A toi qui es un vrai guerrier...qui ne lâches jamais rien?... et qui survit à toutes les guerres de clan? Rejoins les immortels.




  social:
    
    - discord: https://discord.gg/VMy49RyXWS
    
clans:
  - name: Mac Leod
    tag: 22QCGUCU
  - name: Mac Leod II
    tag: LJ0R82VG
  - name: Mac Leod III
    tag: GYYL0YYL
```

### Additional Info

![Image](https://github.com/user-attachments/assets/bd75f89e-7f40-4cd4-84c0-6e24ad664220)

**Comment by Kristeauf** [comment]
Hello , is everything alright for thé code? Tks for the work👍

**Comment by karol-clash** [comment]
This is your final yaml config
```yaml
name: Famille Mac Leod
key: mac-leod
color: blue
emblem: Sword_03
info:
  logo: ml-logo.png
  description: >
   A toi qui es un vrai guerrier...qui ne lâches jamais rien?... et qui survit à toutes les guerres de clan? Rejoins les immortels.
  social:
    - discord: https://discord.gg/VMy49RyXWS
clans:
  - name: Mac Leod
    tag: 22QCGUCU
  - name: Mac Leod II
    tag: LJ0R82VG
  - name: Mac Leod III
    tag: GYYL0YYL
```

Changes should be live in about 30 minutes
