### ISSUE TITLE
[New]: De Raad van Oranje

### ISSUE THREAD

**Issue by Daafduif** [RoyaleAPI/family-config#1186]
### Family configuration

```yaml
name: Raad van oranje
key: de raad
color: white
emblem: Skull_06
sort: trophy
info:
  logo: https://imgur.com/a/9YRNE6z
  description: >
    De Raad van Oranje bestond origineel alleen uit de Hoge Raad, opgericht door Maurits, deze clan staat momenteel top 40 van Nederland, en we zijn goed op weg naar de top, ook internationaal willen we doorbreken, daarom hebben wij laatst een toevoeging gemaakt aan de hoge raad: De Lage Raad, hier ontvangen wij alle mensen die de Hoge Raad nog niet in kunnen, als er in de Lage Raad inzet wordt getoond in de war (en er een plekje vrij komt in de Hoge Raad) is er zomaar een kans dat een speler van de Lage Raad promotie naar de Hoge Raad boekt, dat is nou toch eens leuk! 

  social:
    - discord: https://discord.gg/Sk5F3b4gfz 
clans:
  - name: De Hoge Raad
    tag: PVUPGG90
  - name: De Lage Raad
    tag: G098YJ22
```
