### ISSUE TITLE
[New]: Clanarchy

### ISSUE THREAD

**Issue by jakesandersx** [RoyaleAPI/family-config#1187]
### Family configuration

```yaml
name: Clanarchy Clan Family
key: clanarchy
color: purple
emblem: A_Char_Goblin_01
info:
  description: >
    **Clanarchy** was originally created with the founding of 
    Dark Knights, our leader clan, back in 2018. Since then,
    we have branched out into 14 clans, where any player, casual 
    or competitive, can flourish! 
    Join the discord and join our family today!
  social:
    - discord: https://discord.gg/2eRNGF4hST
clans:
  - name: Dark Knights
    tag: JC0YVU
  - name: Fishmell
    tag: J2PGY0
  - name: Goblin Thugs
    tag: PY9RGY0R
  - name: DaBoize 
    tag: Q0QJUYQR
  - name: FishBoize 
    tag: G92JJL9P
  - name: Pittsburgh A
    tag: 2RGUUV
  - name: da Fishmell fam
    tag: GCPRRY29
  - name: The Voiid 
    tag: G98V2G0C
  - name: Fishmell Nights
    tag: QPYL22L9
  - name: For The Knights 
    tag: GU82P0R0
  - name: Fishmell Prime
    tag: GV00UYGQ
  - name: pittsburgh B 
    tag: L8YGUR9P
  - name: #Riptide
    tag: GP89LJPP
  - name: Fishmell Boize
    tag: QGV88C8G
```
