### ISSUE TITLE
The Kingdom new (old) family

### ISSUE THREAD

**Issue by JEDIIy2k** [RoyaleAPI/family-config#119]
```yaml
name: The Kingdom
key: thekingdom
color: orange
emblem: Heart_03
info:
  logo: /static/img/branding/the-kingdom.png
  description: >
    From the whimsical mind of Clash Tutor was born a family of colorful creatures!
    We are a family of clans who war together and help each other grow.


  social:
    - discord: https://discord.gg/VGHEPtZ
    - youtube: https://www.youtube.com/channel/UC0cUo3z16Oaa1U-XFS7xN-g
clans:
  - name: White Whales
    tag: 9URJR8
  - name: Silver Sharks
    tag: RQUR9R
  - name: orange otters
    tag: RLUVPJ
  - name: Violet Vipers
    tag: L2YYUGR8
```
![the-kingdom](https://user-images.githubusercontent.com/55586297/65325486-f9823b00-db7c-11e9-9201-83e414dabf62.png)
