### ISSUE TITLE
[Family] Born On Ice

### ISSUE THREAD

**Issue by bornonicefamily** [RoyaleAPI/family-config#12]
```yaml
name: Born On Ice
key: bornonice
color: teal
emblem: Fugi_03
info:
  logo: https://postimg.cc/rz8DdY8p
  description: >
    Welcome to the **Born On Ice** Family! We are dedicated clan members aged 19 and over and all ages, with competitive and casual clans to fit your needs. We have experts that will help you with your decks and battles, so come on in, we're made of friendly people. Join our Discord to apply.
  social:
    - discord: https://discord.gg/H3ueGPS
    - instagram: https://instagram.com/bornonicefamily
    - email: mailto: bornonicefamily@gmail.com
clans:
  - name: Born On Ice
    tag: VGV0RP8
  - name: Livin' On Ice
    tag: 82JLJ2VP
```
