### ISSUE TITLE
Gold’s GYM

### ISSUE THREAD

**Issue by staarsun** [RoyaleAPI/family-config#121]
```yaml
name: Gold´s GYM
key: GG
color: yellow
emblem: skull_01

info:
  logo: https://en.wikipedia.org/wiki/Gold%27s_Gym
  description: >
    Die Gold's GYM Clan Familie ist eine der stärksten Community's in Clash Royal. Muskeln sind
    vielleicht stark, aber der Zusammenhalt bei uns ist am stärksten. Wir sind nicht ohne
    Grund einer der besten Kriegsclans lokal.

    Veni. Vidi. Vici


clans:
  - name: Gold's GYM
    tag: 8902RQR
  - name: Gold's GYM 2
    tag: 20LYYGP9
  - name: Gold's GYM 3
    tag: PQJY2VUG
…
```
