### ISSUE TITLE
[Update] Born On Ice Family

### ISSUE THREAD

**Issue by bornonicefamily** [RoyaleAPI/family-config#123]
```yaml
name: Born On Ice Family
key: bornonice
color: blue
emblem: Fugi_03
info:
  logo: https://postimg.cc/rz8DdY8p
  description: >
All ages welcome, with trophy requirements ranging from 5000 to 3000 trophies, you have Born On Ice Family! From competitive and casual clans, the first part and second part of the Born On Ice Family. Looking for members dedicated to wars, donations, and just being a lovely bunch overall. *Join us, and become... Officially Born On Ice Family!*
  social:
    - discord: https://discord.gg/H3ueGPS
clans:
  - name: Born On Ice
    tag: VGV0RP8
  - name: Livin' On Ice
    tag: 82JLJ2VP
```
