### ISSUE TITLE
PNW Royale

### ISSUE THREAD

**Issue by voldengen** [RoyaleAPI/family-config#125]
```yaml
name: PWN Royale
color: green
emblem: Pine_02
info:
  description: >
    Pacific Northwest Clash Royale!
clans:
  - name: PNW Royale
    tag: UCQLY9
```
