### ISSUE TITLE
Rebel Riot Gaming - Clan family to add

### ISSUE THREAD

**Issue by AwfyAlba** [RoyaleAPI/family-config#127]
```yaml
name: Rebel Riot Gaming
key: rebelriot
color: red
emblem: skull_06
info:
  logo: https://i.postimg.cc/ydmynDG9/rebel-riot-source-PNG.png
  description: >
    The **Rebel Riot Family** are a highly active and organized international English speaking clan family. Adults preferred. Maturity and respect required. 


There are several different clans available to suit a wide range of members from casual to competitive. Active discord server available. Join the **riot!**
  social:
    - discord: https://discord.gg/pgJVfau
    - reddit: https://www.reddit.com/message/compose/?to=Rebel_Riot_Gaming
    - email: mailto:rebelriotgaming@outlook.com
clans:
  - name: Rebel Riot Club
    tag: PPRJ8RPQ
  - name: Rebel Riot APEX
    tag: PUQ99L0R
  - name: Rebel Riot Jr
    tag: PUG80CJR
…  
```

**Comment by smlbiobot** [comment]
```yml
name: Rebel Riot Gaming
key: rebelriot
color: red
emblem: skull_06
info:
  logo: /static/img/brands/logo/rebel-riot.png
  description: >
    The **Rebel Riot Family** are a highly active and organized international English speaking clan family. Adults preferred. Maturity and respect required.


    There are several different clans available to suit a wide range of members from casual to competitive. Active discord server available. Join the **riot!**
  social:
    - discord: https://discord.gg/pgJVfau
    - reddit: https://www.reddit.com/message/compose/?to=Rebel_Riot_Gaming
    - email: mailto:rebelriotgaming@outlook.com
clans:
  - name: Rebel Riot Club
    tag: PPRJ8RPQ
  - name: Rebel Riot APEX
    tag: PUQ99L0R
  - name: Rebel Riot Jr
    tag: PUG80CJR
```
