### ISSUE TITLE
Italian Indie Clans

### ISSUE THREAD

**Issue by RetterKampf** [RoyaleAPI/family-config#129]
```yaml
name: Italian Indie Clans
key: italianindieclans
color: Violet
emblem: Star_Shine_03
info:
sort: trophy
  logo: ![IIC](https://user-images.githubusercontent.com/56153171/66206019-16eff280-e6af-11e9-81b8-f3737c8bf540.jpg)
  description: >
    Una famiglia per Clan indipendenti che rifiutano un modello di gioco ultra competitivo e, da veri appassionati di Clash Royale, si dedicano anima e corpo a creare una community coesa e vivace dove poter scambiare pareri, consigli e tattiche di gioco nel pieno rispetto reciproco. Unisciti a noi e allarga la famiglia!!!
social:
    - website: https://royaleapi.com/clan/family/italianindieclans/clans
clans:
  - name: 404Error
    tag: 20GYL2C
  - name: 808Error
    tag: PQP0V0GU
  - name: THE SHIELD
    tag: PQ9V20YY
  - name: The last Time
    tag: 2CPY2JV
  - name: L'ultima Torre
    tag: Y9L9LLJR
  - name: tsunamITA
    tag: 9CYJ2LGP
```
