### ISSUE TITLE
[Family] Holzfäller Family

### ISSUE THREAD

**Issue by Freeder1k** [RoyaleAPI/family-config#13]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Holzfäller Family
key: holzfäller
color: green
emblem: Sword_01
info:
  logo: https://i.imgur.com/Mfv1eX1.png
  description: >
    The **Holzfäller Family** is a clan family from germany.
    The first two clans are active and the third clan was recently created for lower or inactive players.
    The main clan was originally founded as a class clan in school but has switched leaders once and is now mainly focused on trophies and rank.
clans:
  - name: HOLZFÄLLER
    tag: R09Q0RU
  - name: Holzfäller 2
    tag: 99Y2U22P
  - name: Holzfäller 3
    tag: P0Y8VP88
```

**Comment by smlbiobot** [comment]
- I realize that this is not ideal and probably wrong to your eyes but we can’t use accented characterrs in the URL so I have to update your key:

```yml
name: Holzfäller Family
key: holzfaller
color: green
emblem: Sword_01
info:
  logo: /static/img/brands/logo/holzfaller.png
  description: >
    The **Holzfäller Family** is a clan family from germany.
    The first two clans are active and the third clan was recently created for lower or inactive players.
    The main clan was originally founded as a class clan in school but has switched leaders once and is now mainly focused on trophies and rank.
clans:
  - name: HOLZFÄLLER
    tag: R09Q0RU
  - name: Holzfäller 2
    tag: 99Y2U22P
  - name: Holzfäller 3
    tag: P0Y8VP88
```
