### ISSUE TITLE
Aussie Royale Family

### ISSUE THREAD

**Issue by aresportsteam** [RoyaleAPI/family-config#130]
```yaml
name: Aussie Royale Family
emblem: flag_b_03
key: aussieroyale
color: green
track: true
info:
  logo: ![AR_logo](https://user-images.githubusercontent.com/56501573/66713896-43b0b200-edf3-11e9-8a98-e55ee9955f9c.png)
  description: >
    **Aussie Royale** was founded at the launch of the game by Tyson in January 2016. The clan immediately saw popularity and rose to the top of the Australian leaderboards.
    Today we are well established in the top 3 of the Australian leaderboards with all 6 clans in the top 200.   
    Our eSport team compete in the Australian and international scene and exist as the friendly home to the Australian community.
  social:
    - discord: http://discord.gg/hgaCY2e
clans:
  - name: Aussie Royale
    tag: LY9U2C
  - name: Aussie Royale 2
    tag: G0YPR0U
  - name: Aussie Royale 3
    tag: Q9QLR99
  - name: Aussie Royale 4
    tag: 8JLUYLR0
  - name: Aussie Royale 5
    tag: 92Y90UUL
  - name: Aussie Royale 6
    tag: 9Y8CV9YQ
```
