### ISSUE TITLE
Aussie Royale

### ISSUE THREAD

**Issue by aresportsteam** [RoyaleAPI/family-config#132]
```yaml
name: Aussie Royale Family
emblem: flag_b_03
key: aussieroyale
color: green
track: true
info:
  logo: ![AR_logo](https://user-images.githubusercontent.com/56501573/66714078-3eecfd80-edf5-11e9-9b7d-95b299ac0c00.png)
  description: >
    **Aussie Royale** was founded at the launch of the game by Tyson in January 2016. The clan immediately saw popularity and rose to the top of the Australian leaderboards.
    Today we are well established in the top 2 of the Australian leaderboards with all six clans in the top 200.   
    The Aussie Royale eSport team are competitive in Australian and international tournaments.  Our six clans and eSport culture provide a friendly and supportive home for national and international players.
   social:
    - discord: https://discord.gg/hgaCY2e
    - twitter: https://twitter.com/AussieRoyale
    - email: mailto:aresportsteam@gmail.com
clans:
  - name: Aussie Royale
    tag: LY9U2C
  - name: Aussie Royale 2
    tag: G0YPR0U
  - name: Aussie Royale 3
    tag: Q9QLR99
  - name: Aussie Royale 4
    tag: 8JLUYLR0
  - name: Aussie Royale 5
    tag: 92Y90UUL
  - name: Aussie Royale 6
    tag: 9Y8CV9YQ
```
