### ISSUE TITLE
从COC到CR

### ISSUE THREAD

**Issue by hxchen** [RoyaleAPI/family-config#133]
```yaml
name: 从COC到CR
key: fromCOCtoCR
color: orange
emblem: Orange_01
info:
  logo: https://user-images.githubusercontent.com/3330014/66764419-56eb7c80-eedc-11e9-8952-a526e5ab6364.png
  description: >
    从COC到CR，我们是一群欢乐的小伙伴，欢迎您的加入~
clans:
  - name: 从COC到CR
    tag: 8RCCQC
  - name: 从coc到cr预备队
    tag: PPPYP99R
```
