### ISSUE TITLE
xQlusive Family

### ISSUE THREAD

**Issue by heinvolks** [RoyaleAPI/family-config#134]
```yaml
name: xQlusive
key: xq
color: purple
emblem: flag_h_03.png
info:
  logo: N/A
  description: >
   **xQlusive** is the result of a bold move to abandon the clan ARS United in favour of a new family of clans with one specific goal in mind: **each clan is tailored for a specific Clan War Readiness.** 
   This way a whole clan operates on a similar Card Level advantage and are equally ready for War Battles. And by levelling up your Card Levels, you advance to a higher Clan! 


  social: N/A
clans:
  - name: xQlusive Gold
    tag: P0UUL80C
  - name: xQlusive Silver
    tag: 9JQC8GVQ
  - name: xQlusive Bronze
    tag: 9R0UCQYJ
  - name: xQlusive Casual
    tag: PL08R8JY
```
