### ISSUE TITLE
DBZ Family - Update

### ISSUE THREAD

**Issue by aaronaqua** [RoyaleAPI/family-config#137]
```yaml
name: DBZ Family
key: dbz
color: purple
emblem: Elixir_01
info:
  logo: /static/img/badge/Elixir_01.png
  description: >
    DBZ Family -  **Home to #1 Local clan DBZ Saiyans.** We are the largest clan family in Australia with 8 active clans with back to back wars. War leagues and trophy requirements to suit all players. Please join our discord server using the link below if you are interested in joining us.
  social:
    - discord: https://discord.gg/xYcvrvN
clans:
  - name: DBZ Saiyans
    tag: 89YVRV
  - name: DBZ HTC
    tag: Q29UJ0Y
  - name: DBZ Genesis
    tag: 9CUUPGCC
  - name: DBZ Fusion
    tag: 82G9C220
  - name: DBZ Ares
    tag: 9V0URJR9
  - name: DBZ Solar
    tag: P9RG9CQU
  - name: DBZ Shadow
    tag: Y2UC0YLL
  - name: DBZ Phoenix
    tag: PRCQQQYQ 
…
```
