### ISSUE TITLE
Qianlong Family

### ISSUE THREAD

**Issue by zachuu** [RoyaleAPI/family-config#139]
```yaml
name: 潜龙家族
key: qianlong
color: Purple
emblem: Star_Shine_03
info:
  logo: 
  description: >
潜龙在渊，腾必九天！
欢迎加入潜龙部落家族, 广邀专注部落战的朋友, 开心游戏, 享受生活。
QQ群：596953567
  social:
    - email: mailto:jbenjbenjben1@gmail.com
clans:
  - name: 潜龙在渊
    tag: PGQLL8VG
  - name: 潜龙2团
    tag: PQCURVGR
```
