### ISSUE TITLE
Family Config - Czech Eagles

### ISSUE THREAD

**Issue by jazby** [RoyaleAPI/family-config#14]
```yaml
name: Czech Eagles Family
key: CzechEagles
color: red
emblem: Flame_01
info:
  logo: /static/img/badge/Flame_01.png
  description: >
    ** Czech Eagles ** is a new Czech clan group with a very active community. Adult and experienced management, cool team.
    **Join us in the family and help us together. **

  social:
    - facebook: https://facebook.com/groups/CzechEagles
    - messenger: https://bit.ly/CzechEagles
clans:
  - name: Czech Eagles
    tag: 9YYVYC9J
  - name: Czech Eagles 2
    tag: PV8J9RGU
```
