### ISSUE TITLE
Panda Familie

### ISSUE THREAD

**Issue by FPIMotylek** [RoyaleAPI/family-config#140]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Panda Familie
key: pandafamilie
color: black
emblem: Bamboo_03.png
info:
  logo: https://gabrychfotografie.de/wp-content/uploads/2019/10/pandafamilie.jpg
  description: >
    Wir begannen vor langer Zeit unsere Clash Royale Laufbahn als ein 12 Mitglieder großer Clan Namens „Public Enemy EL“, welcher der Eliteclan von Public Enemy war. Wir wuchsen relativ schnell und wurden, aufgrund harter Arbeit, sehr schnell groß und unabhängig.

Zum Ende hin waren wir bereits 23 Mitglieder und schafften es in die Legendäre Arena, bis wir gemeinsam beschlossen haben, dass unsere Unabhängigkeit erst zur Wirklichkeit wird, wenn auch unser Name sich ändert und somit ebenfalls unabhängig wird.

Dies war der Beginn der „Flow Pandas“.

Wir wussten, dass halbe Sachen nicht funktionieren würden und wir beschlossen die Pandas „richtig“ und zu 100 Prozent aufzubauen. Ein Logo, ein Konzept und Regeln waren, neben einer Internetseite, der Grundstein für den Durchbruch unserer Familie.

Nach dem Erreichen der Legendären Arena unter dem Namen „Flow Pandas“ waren wir bereits über 40 Mitglieder und wir entschlossen uns dazu, zu Expandieren.


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/R2a6Pa
    - youtube: https://www.youtube.com/channel/UCYybMr8FcNQ3taBjiYUWJSw
    - website: https://gabrychfotografie.de/
    - facebook: https://www.facebook.com/pandafamilie/
    - email: mailto: FPIMotylek@gmx.de
clans:
  - name: Flow Pandas
    tag: P2GUC2L0
  - name: Nano Pandas
    tag: Y0YV0Q8J
  - name: Carbon Pandas
    tag: PQQ9922P
  - name: ToXic Pandas
    tag: PRQJLQLC
```
