### ISSUE TITLE
Family Edit (Addition of one Clan into existing Family)

### ISSUE THREAD

**Issue by doongmiin** [RoyaleAPI/family-config#141]
```yaml

name: SirTagCR
key: sirtagcr
color: black
emblem: Lotus_01
info:
  logo: https://drive.google.com/file/d/1Fy4EZZ32ev3qAdnQFUSD0L7cA-QxjWdb/view?usp=sharing
  description: >
    Saucin' out a good luck, going hard in the paint, and that's how you assert dominance.

    Instructions to join the SirTagCR clan family on the how-to-join-a-clan channel on Discord.

    Discord.gg/SirTag or follow the link below.
    
  social:
    - Discord: https://discordapp.com/invite/SirTag
    - Twitch: https://www.twitch.tv/sirtagcr
    - Youtube: https://www.youtube.com/channel/UCvje1_OaZUZVZDzxeyOFf6A
    - Twitter: https://twitter.com/sirtagcr
    - Instagram: https://www.instagram.com/sirtagcr/?hl=en
   
clans:
  - name: Twitch SirTagCR
    tag: 29YU089C
  - name: Chivalrous Sirs
    tag: 9G2PUJ8V
  - name: Superior Sirs
    tag: 9J9VG8LC
  - name: Society of Sirs
    tag: PP08RGGL
  - name: Sly Sirs
    tag: P9LP0JP9
  - name: Relentless Sirs
    tag: L828P9RL

…
```
