### ISSUE TITLE
Clan Configuration

### ISSUE THREAD

**Issue by GBAnjos** [RoyaleAPI/family-config#143]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: green
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: EliteBrasil
key: elb
color: green
emblem: Brazilian Flag
info: Seja bem vindo, clã recém criado. Buscamos jogadores ativos e que queiram crescer junto com a gente. Guerras obrigatórias.
  logo: 
![images (1)](https://user-images.githubusercontent.com/28555535/68631011-e7ab7d00-04c7-11ea-8643-89a739ba740d.jpg)

  description: > Seja bem vindo, clã recém criado. Buscamos jogadores ativos e que queiram crescer junto com a gente. Guerras obrigatórias.
    


clans:
  - name: EliteBrasil
    tag: PC8LQP2J
 
```
