### ISSUE TITLE
Aussie Aces

### ISSUE THREAD

**Issue by ryancampbelludovic** [RoyaleAPI/family-config#148]
```yaml
name: Aussie Aces
key: aussieaces
color: red
emblem: Diamond_03
info:
  description: >
    Aussie Aces family of clans. Donate regularly, participate in clan wars. Swearing and toxicity not welcome. 
clans:
  - name: Aussie Aces 2.0
    tag: 8JCUP8VV
  - name: Aussie Aces 3.0
    tag: 90YLG2PJ
  - name: Aussie Aces 1.0
    tag: PQPQVLRP
  - name: Aussie Aces lv1
    tag: 9J8229PY
  - name: Aussie Aces
    tag: PY2PQL
sort: trophy
```
