### ISSUE TITLE
Gavetas  

### ISSUE THREAD

**Issue by opaidofarm** [RoyaleAPI/family-config#15]
name: Gavetas Universe
key: gavetas
color: red
emblem: A_Char_Goblin_02
info:
logo: /static/img/brands/logo/gavetas.png
description: >
Gavetas is a Portuguese organization focused on the community aspect of the game. We provide a home for the competitive and casual player. We have our own League, competitions and live events with prizes. We have a spot for you as long as you play the game.
social:

twitter: https://twitter.com/GavetaseSports
discord: https://discord.gg/4QYZFys
clans:
name: Gavetas Team
tag: 2QG8V2C9
name: Gavetas Bravo
tag: 9QPRPCJQ
name: Gavetas Charlie
tag: 8ULQJG0G
name: Gavetas Delta
tag: 8VLRRC28
name: Gavetas Echo
tag: 9C9VCRUQ
name: Gavetas Foxtrot
tag: 9UPGVU8G
name: Gavetas Golf
tag: 9CL90JVJ
name: Gavetas Hotel
tag: 9LU2Y8LU
name: Gavetas Índia
tag: 9CGQ29LR
name: Gavetas Mike
tag: Y0RC9CRJ
name Gavetas Quebec
tag: PQQURYYP
name Gavetas Tango
tag: P9Q9L89P
name: Gavetas X-Ray
tag: P8JYVYGJ
name: Gavetas Whiskey
tag: PJV8900L
name Gavetas Yankee
tag: 9URL0G8U
name Gavetas Zen
tag: P0RGGR20
name Gavetas Zulu
tag: P0V9YQGU

**Comment by smlbiobot** [comment]
seriously — can you pls use the config format and escape this??? I have to add punctuations and formatting for you very often. (nearly every time)

**Comment by smlbiobot** [comment]
```yml
name: Gavetas Universe
key: gavetas
color: red
emblem: A_Char_Goblin_02
info:
  logo: /static/img/brands/logo/gavetas.png
  description: >
    Gavetas is a Portuguese organization focused on the community aspect of the game. We provide a home for the competitive and casual player. We have our own League, competitions and live events with prizes. We have a spot for you as long as you play the game.
  social:
    - twitter: https://twitter.com/GavetaseSports
    - discord: https://discord.gg/4QYZFys
clans:
  - name: Gavetas Team
    tag: 2QG8V2C9
  - name: Gavetas Bravo
    tag: 9QPRPCJQ
  - name: Gavetas Charlie
    tag: 8ULQJG0G
  - name: Gavetas Delta
    tag: 8VLRRC28
  - name: Gavetas Echo
    tag: 9C9VCRUQ
  - name: Gavetas Foxtrot
    tag: 9UPGVU8G
  - name: Gavetas Golf
    tag: 9CL90JVJ
  - name: Gavetas Hotel
    tag: 9LU2Y8LU
  - name: Gavetas Índia
    tag: 9CGQ29LR
  - name: Gavetas Mike
    tag: Y0RC9CRJ
  - name: Gavetas Quebec
    tag: PQQURYYP
  - name: Gavetas Tango
    tag: P9Q9L89P
  - name: Gavetas X-Ray
    tag: P8JYVYGJ
  - name: Gavetas Whiskey
    tag: PJV8900L
  - name: Gavetas Yankee
    tag: 9URL0G8U
  - name: Gavetas Zen
    tag: P0RGGR20
  - name: Gavetas Zulu
    tag: P0V9YQGU


```
