### ISSUE TITLE
Evolve Family

### ISSUE THREAD

**Issue by WStrubert** [RoyaleAPI/family-config#151]
```yaml
name: Evolve eSports
key: evolve
color: Black
emblem: Gem_01
info:
  logo: https://twitter.com/cr_evolve/status/1204829688239185922/photo/1
  description:
Evolve eSports was created for members that want to advance within a family unit. Our slogan "Work - Overcome - Evolve" is to portray one's effort, challenges, and determination to better themselves in Clash Royale and in life. We boast a range of competitive and casual players; All are welcome within the Evolve family!
----------------------------------------------------------
Family amenities include:
     -  Seasonal Performance Awards
     -  Prize Tournaments
     -  Prize Challenges
     -  Giveaways
     -  Coaching
     -  eSports
----------------------------------------------------------
Are you ready to Evolve? Join us! Apply or hang out at https://discord.gg/5yAWKDZ and Twitter @cr_evolve
social:
    - twitter: https://twitter.com/cr_evolve
    - discord: https://discord.gg/5yAWKDZ
clans:
  - name: Evolve eSports
    tag: L9UPC209
  - name: Evolve I Ignis
    tag: PRULUG90
  - name: Evolve I Terra
    tag: L8P0V8YY
```

**Comment by smlbiobot** [comment]
I can’t give you evolve as url key because someone else is already using it.

```yml
name: Evolve eSports
key: evolve-esports
color: Black
emblem: Gem_01
info:
  logo: /static/img/brands/logo/evolve-esports.jpg
  description: >
    Evolve eSports was created for members that want to advance within a family unit. Our slogan "Work - Overcome - Evolve" is to portray one's effort, challenges, and determination to better themselves in Clash Royale and in life. We boast a range of competitive and casual players; All are welcome within the Evolve family!


    Family amenities include:


      - Seasonal Performance Awards
      - Prize Tournaments
      - Prize Challenges
      - Giveaways
      - Coaching
      - eSports


    Are you ready to Evolve? Join us! Apply or hang out at [https://discord.gg/5yAWKDZ](https://discord.gg/5yAWKDZ) and Twitter [@cr_evolve](https://cr_evolve)
  social:
    - twitter: https://twitter.com/cr_evolve
    - discord: https://discord.gg/5yAWKDZ
clans:
  - name: Evolve eSports
    tag: L9UPC209
  - name: Evolve I Ignis
    tag: PRULUG90
  - name: Evolve I Terra
    tag: L8P0V8YY
```
