### ISSUE TITLE
Gummybear Fam request

### ISSUE THREAD

**Issue by kennethnjl** [RoyaleAPI/family-config#152]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: GummyBear & TeddyBear
key: gmb
color: pink
emblem: A_Char_Prince_03.png
info:
  logo:
![gummies v2](https://user-images.githubusercontent.com/58913755/70866382-fa701080-1fa3-11ea-8591-2bfe0bafe126.jpg)

  description: >
    The **GMB family** was founded back in 2016 but matured in 2018. A proud Singapore clan consists of chill yet decent clashers who chats more than just a game; about life and everything else. TEDDYBEAR is our sub-clan for friends and family consisting of players who just set off for the game or players taking a break. Our family fosters an environment where casual and competitive styles of play can both flourish. Do join us by contacting Haribo's instagram or email!


    Add new line with 2 line breaks as above.
  social:
    - instagram: https://instagram.com/knjl_
    - email: mailto: bluedragon505@hotmail.com
clans:
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: TEDDYBEAR
    tag: PLJ9CL9R
  - name:
    tag:
```
