### ISSUE TITLE
Weedhouse Family

### ISSUE THREAD

**Issue by JJaruszewski** [RoyaleAPI/family-config#154]
```yaml
name: Weedhouse Family
key: weedhouse
color: green
emblem: Clover_02
info:
  logo:
  description: >
**The Power of Weed.** The Weedhouse Family is a chill community for everyone ready to give
their best on war days. We are looking for new talents as we grow bigger everyday.
Our passionate team takes care of everyone and is interested in improving you. If you want to
climb the global Clan ladder ..light it up and join us.

social:
    - discord: http://discord.gg/DTRHJtb
clans:
  - name: Weedhouse Clan
    tag: 2L0YQPU9
  - name: WHC Academy
    tag: YL89C2RL
```
