### ISSUE TITLE
Rockets Family

### ISSUE THREAD

**Issue by RL-Royal** [RoyaleAPI/family-config#155]
```yaml
name: Rockets Familie
key: rockets
color: blue
emblem: A_Char_Rocket_01
info: Rocket‘s Familie🚀rockets-cr.de🚀Top DE Clan 🚀Bewerbung via Line: funnyfox2🚀dennis-rockets🚀 Rockets eSports🚀home Rockets League🚀
  logo:
  description: >Die Clanfamilie ist für alle die perfekt, die in eine Clanfamilie wollen, wo ZUSAMMENHALT groß geschrieben wird, und die gerne CW spielen.

    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
 
    - website: rockets-cr.de
    - application: pls apply via LINE

clans:
  - name: Rocket's
    tag: 28V2QQ9C
  - name: Rocket Academy
    tag: 9R2R28JL
  - name: nokidsclan
    tag: 9JCUVP
  - name: Rocket's Wing
    tag: 2V0JL0L9 

```

**Comment by smlbiobot** [comment]
revised

```yml
name: Rockets Familie
key: rockets
color: blue
emblem: A_Char_Rocket_01
info:
  logo:
  description: >
    Die Clanfamilie ist für alle die perfekt, die in eine Clanfamilie wollen, wo ZUSAMMENHALT groß geschrieben wird, und die gerne CW spielen.


    Rocket‘s Familie🚀rockets-cr.de🚀Top DE Clan 🚀Bewerbung via Line: funnyfox2🚀dennis-rockets🚀 Rockets eSports🚀home Rockets League🚀
  social:
    - website: http://rockets-cr.de

clans:
  - name: Rocket's
    tag: 28V2QQ9C
  - name: Rocket Academy
    tag: 9R2R28JL
  - name: nokidsclan
    tag: 9JCUVP
  - name: Rocket's Wing
    tag: 2V0JL0L9
```
