### ISSUE TITLE
#FightClub family addition

### ISSUE THREAD

**Issue by neopenguin** [RoyaleAPI/family-config#158]
```yaml
name: #FightClub Family
key: fightclub
color: purple
emblem: Skull_01
info:
  description: >
    A drama free group of fun loving folks, focused on warring.
    From casual to competitive, there's something for everyone!
clans:
  - name: #FightClub
    tag: 8JP082C
  - name: #FightClub2
    tag: 2CLVG9V9
  - name: #FightClub3
    tag: 9YVJ98CV
  - name: #FightClub4
    tag: PJYPUVGJ
  
```
