### ISSUE TITLE
#FresherThanYou Family Update

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/family-config#159]
```yaml
name: #FresherThanYou Family
key: FTY
color: black
emblem: 
        Freeze_01
info:
  logo: https://imgur.com/gallery/Ha66fS1
description: >
We are a very active german Clash Royale Clan focused on clan wars.
   The main language in our chat is german.

**Loyalität, Fleiß und Zuverlässigkeit sind die Grundpfeiler der #FresherThanYou Clan Familie.** Daraus hat sich aus einem einzelnen Clan eine ganze Clan Familie entwickelt. Wir sind eine sehr aktive Familie, die sich primär auf Clan Wars fokussiert hat.
Innerhalb der Familie nutzen wir ein Rankingsystem, welches basierend auf Skill, Winrate und Kartenressourcen, die Mitglieder in die jeweiligen passenden Clans verteilt. Unser Rotationssystem ermöglicht es, das volle Potential der Familie auszuschöpfen.
Das Ziel ist eine interne Topliste zu formen, die es unseren stärksten und ehrgeizigsten Mitgliedern der Familie ermöglicht, wettbewerbsfähig in der CW Liga sich durchzusetzen.
Der Clan-Alltag ist bei uns klar strukturiert und in einem Regelwerk festgehalten.
Wenn du kein Einzelgänger, sondern ein Teamspieler bist und in der CW Liga etwas bewirken möchtest, bewirb dich auf unserem Discord Server und werde ein Teil der Familie!
  social:
    - discord: https://discord.gg/sCrryNy
    - twitter: https://twitter.com/FresherthanyouC
    - email: FresherThanYou-SocialMedia@web.de
clans:
  - name: #FresherThanYou (I)
    tag: GJ9G9R
  - name: FresherThanYou (II)
    tag: P009PY9C 
  - name: #SmarterThanYou (III)
    tag: Y0VV9YR8
- name: SmarterThanYou (IV)
    tag: LYLC89PR
```

**Comment by Maxigon** [comment]
@smlbiobot i hope everything is correct

**Comment by smlbiobot** [comment]
```yml
name: "#FresherThanYou Family"
key: FTY
color: black
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/fresher-than-you.jpg
  description: >
    We are a very active German Clash Royale Clan focused on clan wars.
    The main language in our chat is german.


    **Loyalty, diligence and reliability are the cornerstones of the # FresherThanYou clan family.**

    From this a whole clan family has developed from a single clan. We are a very active family that primarily focused on Clan Wars.
    Within the family, we use a ranking system, which distributes the members into the appropriate clans based on skill, win rate and map resources. Our rotation system enables the full potential of the family to be exploited.
    The goal is to form an internal top list that enables our strongest and most ambitious members of the family to assert themselves competitively in the CW league.
    The everyday life of the clan is clearly structured and set out in a set of rules.
    If you are not a loner, but a team player and want to make a difference in the CW League, apply on our Discord Server and become part of the family!
  social:
    - discord: https://discord.gg/sCrryNy
    - twitter: https://twitter.com/FresherthanyouC
    - email: FresherThanYou-SocialMedia@web.de
clans:
  - name: "# FresherThanYou (I)"
    tag: GJ9G9R
  - name: FresherThanYou (II)
    tag: P009PY9C
  - name: "# SmarterThanYou (III)"
    tag: Y0VV9YR8
  - name: SmarterThanYou (IV)
    tag: LYLC89PR
```
