### ISSUE TITLE
CFF Royale Clan Family

### ISSUE THREAD

**Issue by MrLlama12345** [RoyaleAPI/family-config#16]
```yaml
name: Clash Files Royale
key: CFF
color: black
emblem: A_Char_Knight_02
info:
  logo: ![kw9xr7vo_400x400](https://user-images.githubusercontent.com/47618318/52759435-40ee8a80-2fe2-11e9-8fec-b4147029ac54.jpg)

  description: >
    CFF Royale is a Mature Clash Royale Clan Family Devoted to their love of Pizza... 
    just joking, we do love pizza but we love clash royale more. While we push in war
    we encourage growth and communication throughout both of our clans and want players to
    better themselves while feeling at home with family. We keep it cheesy and saucy! 

  social:
    - discord: http://discord.gg/adDyDTa
    - website: https://theclashfiles.com/
    - instagram: https://www.instagram.com/CFF_Royale
    - twitter: http://twitter.com/TheClashFiles
clans:
  - name: CFF Thin Crust
    tag: J8PVYG2
  - name: CFF Deep Deep Dish 
    tag: U99QLCO
 
```

**Comment by smlbiobot** [comment]
- wrong clan tag

```yml
name: Clash Files Royale
key: CFF
color: black
emblem: A_Char_Knight_02
info:
  logo: /static/img/brands/logo/cff.jpg

  description: >
    CFF Royale is a Mature Clash Royale Clan Family Devoted to their love of Pizza...
    just joking, we do love pizza but we love clash royale more. While we push in war
    we encourage growth and communication throughout both of our clans and want players to
    better themselves while feeling at home with family. We keep it cheesy and saucy!

  social:
    - discord: http://discord.gg/adDyDTa
    - website: https://theclashfiles.com/
    - instagram: https://www.instagram.com/CFF_Royale
    - twitter: http://twitter.com/TheClashFiles
clans:
  - name: CFF Thin Crust
    tag: J8PVYG2
  - name: CFF Deep Deep Dish
    tag: U99QLV0
```
