### ISSUE TITLE
Berrões eSports Community and Club appliance to CR api Family

### ISSUE THREAD

**Issue by iTzWasy** [RoyaleAPI/family-config#160]
```yaml
name: Berrões eSports Community and Club
key: berroes
color: grey
emblem: Skull_05
info:
   social:
     - discord: https://discord.gg/PTWqjDT
   clans:
     - name: Berroes
     - tag: PC9LL8QL
```
