### ISSUE TITLE
FriendsForLife

### ISSUE THREAD

**Issue by SethFalcor** [RoyaleAPI/family-config#161]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: `red and black`
- `key`: `https://royaleapi.com/clan/GYGY88`
- `emblem`: do not include the file extension `.png`
- `description` and `links`: `Clãs de Guerra FriendsForLife`
- `tag`:  `GYGY88``9JCJUP98``PUYJ0QV2`

Fill in the configuration below:

```yaml
name: FriendsForLife
key:
color: red and black
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```
