### ISSUE TITLE
Royale Moscow Family

### ISSUE THREAD

**Issue by Talakin** [RoyaleAPI/family-config#162]
```yaml
name: Royale Moscow Family
key: RM
color: red
emblem: flag_h_01
info:
  logo: 
  description: >
    Royale Moscow clan has been created at 01.06.2016! We are friendly and would be happy to accept new players and find more friends. We dont have players under age of 18. So would be great to meet new adult players. Become part of our family!

  social:
    - twitch: https://www.twitch.tv/detal

clans:
  - name: Royale Moscow
    tag: PRU90PL
  - name: Royale Moscow J
    tag: PCPQQGP8

…
```
