### ISSUE TITLE
Team CMC Update

### ISSUE THREAD

**Issue by lukefiasco** [RoyaleAPI/family-config#163]
```yaml
name: Team CMC
key: cmc
color: red
emblem: Fugi_04
info:
  logo: 
![Team CMC Logo](https://user-images.githubusercontent.com/50858245/72700718-a8fd0780-3b87-11ea-8af5-1d8dbfdaf7d4.jpeg)

  description: >
    **Team CMC (Chan Mali Chan)** is the home of teamcmcbot, royalepros.com, and is a competitive team representing Singapore. We take pride as a family of 8 clans that lasted the test of time and in playing respectfully. Join us and check out our internal CMCompetitions (CMChampionship and CMCup).


  social:
    - website: https://royalepros.com
    - twitter: https://twitter.com/teamcmcbot
    - twitter: https://twitter.com/TeamCMCGG
    - facebook: https://www.facebook.com/TeamChanMaliChan
    - instagram: https://www.instagram.com/teamchanmalichan
    - application: https://royalepros.com/join
clans:
  - name: CMC Blizzard
    tag: 98R8GU2R
  - name: CMC Quake
    tag: 9RG9G98Q
  - name: CMC Tempest
    tag: P0UGY9Y0
  - name: CMC Blaze
    tag: 98R0JV0Q
  - name: CMC Whirlwind
    tag: 9L2UC9Y9
  - name: CMC Breeze
    tag: PPJCQRCJ
  - name: CMC Sandstorm
    tag: L9LL0QQC
  - name: CMC Zephyr
    tag: PV8QCJ28
```
