### ISSUE TITLE
Camp HoBo

### ISSUE THREAD

**Issue by HoBo883** [RoyaleAPI/family-config#164]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: RoyaleAPI Camp HoBo
key: royaleapi
color: red
emblem: Goblin_02
info:
  logo:
 
clans:
   - name: Camp HoBo
    tag: Y8U28YYY
  
```
