### ISSUE TITLE
[UPDATE] #CWR

### ISSUE THREAD

**Issue by heinvolks** [RoyaleAPI/family-config#165]
```yaml
name: #CWR
key: cwr
color: purple
emblem: flag_h_03
info:
  logo: 
  description: >
   **#CWR** is een clanfamilie met een aantal interessante kenmerken:
   - De clanindeling is afgestemd op **Clan War Readiness**, waardoor er effectiever gestreden kan worden tijdens de Clan Wars 
   - Goede spelers die simpelweg de kaartlevels nog niet zo hoog hebben, hoeven bij ons niet gestraft/gekickt te worden, vanwege deze unieke indeling
   Op onze website en Discord vind je meer informatie:


  social:
    - website: https://cwr.gg
    - discord: https://discord.gg/sf7A3rF
clans:
  - name: #CWR Legendary
    tag: L8C9J0UL
  - name: #CWR Gold
    tag: PUJCP0VV
  - name: #CWR Silver
    tag: YPGVJ0C0
  - name: #CWR Bronze
    tag: YG80QGVP
  - name: xQlusive Silver
    tag: 9JQC8GVQ
  - name: xQlusive Bronze
    tag: 9R0UCQYJ
```
