### ISSUE TITLE
0 PONTE CREW 0

### ISSUE THREAD

**Issue by Rocciflav1** [RoyaleAPI/family-config#167]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 0 Ponte Crew 0
key: 0 Ponte Crew 0
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.

clans: 
  - name: Ponte Crew
    tag: 2JQJLQCR
  - name: Ponte Academy 
    tag: 9UQVY2PR
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
Sorry but we won’t be adding `0`s to your name just so you can be sorted in the beginning.

```yml
name: Ponte Crew
key: ponte-crew
color: blue
emblem: Diamond_Star_03
clans:
  - name: Ponte Crew
    tag: 2JQJLQCR
  - name: Ponte Academy
    tag: 9UQVY2PR
```
