### ISSUE TITLE
Family Config: OneHive Family

### ISSUE THREAD

**Issue by pmaiya** [RoyaleAPI/family-config#169]
```yaml
name: OneHive Family
key: onehive
color: orange
emblem: flag_a_03
info:
  logo: https://cdn.discordapp.com/attachments/225847487364202496/254131529431646210/IMG_0528.JPG
  description: >
    The **OneHive Family** consists of 2 clans OneHive and OneHive Alpha
    We are a War focused clan and currently in the top 10 Local Clan Wars
    We are looking for loyal, active and competitive players to join our family and progress as a top clan in Clash Royale!
    We use discord for communications, announcements, discuss decks, stratergies etc
    **Take your next step and join the OneHive Family**
  social:
    - discord: https://discord.me/ohcr
    - twitter: https://twitter.com/OneHiveCR
    - email: mailto:onehivealphaclash@gmail.com
clans:
  - name: OneHive
    tag: 8RUY
  - name: OneHive Alpha
    tag: 92YG980
```

**Comment by smlbiobot** [comment]
Copy-edited with full sentences. The block won’t look good if they have 5 separate lines. Also fixed your typo

```yml
name: OneHive Family
key: onehive
color: orange
emblem: flag_a_03
info:
  logo: /static/img/brands/logo/one-hive.jpg
  description: >
    The **OneHive Family** consists of 2 clans OneHive and OneHive Alpha
    We are a War focused clan and currently in the top 10 Local Clan Wars,,
    We are looking for loyal, active and competitive players to join our family and progress as a top clan in Clash Royale!
    We use discord for communications, announcements, discuss decks, strategies etc.
    **Take your next step and join the OneHive Family**
  social:
    - discord: https://discord.me/ohcr
    - twitter: https://twitter.com/OneHiveCR
    - email: mailto:onehivealphaclash@gmail.com
clans:
  - name: OneHive
    tag: 8RUY
  - name: OneHive Alpha
    tag: 92YG980
```
