### ISSUE TITLE
[Family Update] Code Enigma Family

### ISSUE THREAD

**Issue by Herram** [RoyaleAPI/family-config#17]
```yaml
name: Code Enigma Clan Family
key: CEF
color: black
emblem: flag_b_01
sort: trophy
info:
  logo: /static/img/brands/logo/code-enigma.png
  description: >
    **Code Enigma** has a long history as an online community, with branches in Clash Royale, Clash of Clans, Brawl Stars, and PUBG.
    The clans below form the **Code Enigma Family**, which provides homes for the most competitive progression players and developmental and/or social players alike. All Code Enigma clans are happy to accept talented and engaged players, who understand that we win together or lose together.
    Our joined-at-the-hip communication channels ensure that we can maintain relationships across the entire family's clan rosters.


  social:
    - discord: http://discord.gg/4CxbefS
    - facebook: https://www.facebook.com/groups/2146080352387975/
clans:
  - name: Code Enigma
    tag: UJULVJ
  - GGG Saiyans
    tag: 8VQQR20U
  - name: CLASH PROS™
    tag: 2VGGQCGQ
  - name: <Own It>
    tag: 90V8YP0
  - name: Code Alpha
    tag: PRUJRRG2
```

**Comment by smlbiobot** [comment]
- missing key
```yml
name: Code Enigma Clan Family
key: CEF
color: black
emblem: flag_b_01
sort: trophy
info:
  logo: /static/img/brands/logo/code-enigma.png
  description: >
    **Code Enigma** has a long history as an online community, with branches in Clash Royale, Clash of Clans, Brawl Stars, and PUBG.
    The clans below form the **Code Enigma Family**, which provides homes for the most competitive progression players and developmental and/or social players alike. All Code Enigma clans are happy to accept talented and engaged players, who understand that we win together or lose together.
    Our joined-at-the-hip communication channels ensure that we can maintain relationships across the entire family's clan rosters.


  social:
    - discord: http://discord.gg/4CxbefS
    - facebook: https://www.facebook.com/groups/2146080352387975/
clans:
  - name: Code Enigma
    tag: UJULVJ
  - name: GGG Saiyans
    tag: 8VQQR20U
  - name: CLASH PROS™
    tag: 2VGGQCGQ
  - name: <Own It>
    tag: 90V8YP0
  - name: Code Alpha
    tag: PRUJRRG2
```
