### ISSUE TITLE
Lotus Family

### ISSUE THREAD

**Issue by Alpha-Jam** [RoyaleAPI/family-config#170]
```yaml
name: Lotus Family
key: lotus
color: black
emblem: Lotus_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    Australian Clan Family
  social:
    - discord: http://discord.gg/XUSP55K
clans:
  - name: Black Lotus
    tag: PCVYYYYY
  - name: White Lotus
    tag: PCOU2222
```
