### ISSUE TITLE
Family Update: TeamDemonic

### ISSUE THREAD

**Issue by TeamDemonic** [RoyaleAPI/family-config#171]
```yaml
name: Team Demonic
key: TeamDemonic
color: red
track: true
emblem:Skull_06
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Team Demonic** : Located in Italian Area.
Demonic Elite: The Clan of the strongest in wars; Demonic Pride: mother clan  ; Demonic 4.0: Academy of Demonic Pride; Demonic 2.0: Academy of Demonic 4.0;  Demonic 3.0: Ex Academy, Lost
  
 clans:
  - name: Demonic Elite
    tag: P082G990
  - name: Demonic Pride
    tag: 2G8LYY0R  
  - name: Demonic 4.0
    tag: 9VG89LG9
  - name: Demonic 2.0
    tag: Y0PC28PG
  - name: Demonic 3.0
    tag: 9LU2LG0C


  
```
