### ISSUE TITLE
上海 OP (Shanghai OP Clan Family)

### ISSUE THREAD

**Issue by GeorgeZhou0422** [RoyaleAPI/family-config#174]
Fill in the configuration below:

```yaml
name: 上海 OP
key: shanghaiop
color: red
emblem: Flame_01
info:
  logo: https://1drv.ms/u/s!Alrhqyh282aBgZIG91jVQ11pjvjNVA
  description: >
    欢迎加入上海 OP大家庭！旗下共30分部，中国最老部落之一，建于2016年1月11日。
    加入QQ审核群571664674。每周举办千人赛现金奖。
 
clans:
  - name: 上海 OP Elite
    tag: 8G9VY92
  - name: 上海 OP Elite2
    tag: 29RJL8QC
  - name: 上海 OP
    tag: V98R8
  - name: 上海 OP Chopper
    tag: 2J02VG
  - name: 上海 OP 复兴社
    tag: 2Q08QQL0
  - name: 上海 OP 复兴社『天时』
    tag: PPP8PQ9L
  - name: 上海 OP 复兴社『地利』
    tag: YR2C9CYU
  - name: 上海 OP Commando
    tag: LRCU80
  - name: 上海 OP Luffy
    tag: QG2VVG
  - name: 上海 OP Sanji
    tag: CC0GJJ
  - name: 上海 OP Zoro
    tag: QJRCQJ
  - name: 上海 OP Tony
    tag: 2QJPRPY
  - name: 上海 OP Nami
    tag: UCCR2Q
  - name: 上海 OP Brook
    tag: PGCVVG9L
  - name: 上海 OP 千阳号
    tag: 2GP0L09
  - name: 上海 OP Robin
    tag: 88YPQYR
  - name: 上海 OP Usopp
    tag: 8U9YVLQ
  - name: 上海 OP 托儿所
    tag: 990PUUQ
  - name: 上海 OP 梅利号
    tag: PUJLJPUJ
  - name: 上海 OP Usoppll
    tag: 2UY8RVC
  - name: 上海 OP Rayleigh
    tag: 9P8QQPJ
  - name: 上海 OP Franky
    tag: 9U2C28C
  - name: 上海 OP Lafitte
    tag: PQJUCYY
  - name: 上海 OP GOL.D
    tag: PYP9RQ0
  - name: 上海 OP Ace
    tag: PJ9UPQP
  - name: 上海 OP Shanks
    tag: 2CYVP9RJ
  - name: 上海 OP 雷利·风行
    tag: LVLL2VP
  - name: 上海 OP Hawk Eye
    tag: PGCG882Y
```
