### ISSUE TITLE
The dark Empire

### ISSUE THREAD

**Issue by TdEHundekuchen** [RoyaleAPI/family-config#176]
```yaml
name: The dark Empire
key: TdE
color: violet
emblem: Elixir_02
info: 
 logo: https://cdn.discordapp.com/attachments/583616146591318017/651049902692106271/Esportslogo _The_dark_Empire_weier_Rand.png
 description: >
  Herzlich willkommen bei der **The dark Empire Clanfamilie**! Wir sind eine Clanfamilie bestehend 
  aus 6 Clash Royale Clans,einem Brawl Stars Club, sowie einem Clash Royale und Brawl Stars 
  Esportsteam. Was uns auszeichnet sind Aktivität, unsere Treue, sowie unser Wissen und Können. 
  Wenn ihr euch verbessern möchtet seid ihr bei uns an der richtigen Adresse! So haben wir
  in jedem unserer Clans Profis welche euch mit Tipps und spezifischen Training zur Seite stehen. Die 
  clanübergreifende Kommunikation unter unseren Mitgliedern ist uns besonders wichtig - So haben 
  wir einen professionellen Discordserver aufgebaut. Wir freuen uns auf dich!
  Kontaktinformationen: Line: hundekuchen123 Discord: Hundekuchen#0819 Discordserver: 
  https://discord.gg/QRgz4zP
 social: 
   - discord: https://discord.gg/QRgz4zP
   - instagram: https://www.instagram.com/the_dark_empire.clanfamilie?r=nametag
clans: 
   - name: The dark knight
     tag: RPPQPOR
   - name: The dark guard
     tag: PYCP8GQL
   - name: The dark path
     tag: Y9Q9RRYO
   - name: The dark viking 
     tag: Y2P99UL8
   - name: The dark castle
     tag: PRRYOVCJ
   name: The dark forest
     tag: LPPRVOVC
```
