### ISSUE TITLE
\H/ Alliance

### ISSUE THREAD

**Issue by JesusCDA** [RoyaleAPI/family-config#178]
`color`: green
`key`: Hulk
`emblem`: Diamond_Star_02
`description`: Hulk Esmaga tem uma grande historia, começamos como o oitavo clã brasileiro e temos orgulho disso, ao longo da nossa jornada crescemos, nos juntamos a outros clãs e nos tornamos cada vez mais fortes, como guerreiros, juntem-se a nós na nossa aliança.

clans:
  - name: Hulk Esmaga
    tag: 2U0YV
  - name: The Warriors
    tag: 2JVQ2QY2
  - name: Blood Alliance
    tag: PCPQQVR0  
- name: HULK\H/ALLIANCE
    tag: YL90C9YU

```

**Comment by smlbiobot** [comment]
In the future, please use the family config repo for these: https://github.com/RoyaleAPI/family-config

**Comment by smlbiobot** [comment]
name of the family is unclear. what about this:

```yml
name: HULK\H/ALLIANCE
color: green
key: hulk
emblem: Diamond_Star_02
description: Hulk Esmaga tem uma grande historia, começamos como o oitavo clã brasileiro e temos orgulho disso, ao longo da nossa jornada crescemos, nos juntamos a outros clãs e nos tornamos cada vez mais fortes, como guerreiros, juntem-se a nós na nossa aliança.
clans:
  - name: Hulk Esmaga
    tag: 2U0YV
  - name: The Warriors
    tag: 2JVQ2QY2
  - name: Blood Alliance
    tag: PCPQQVR0
  - name: HULK\H/ALLIANCE
    tag: YL90C9YU

```
