### ISSUE TITLE
FriendsForLife

### ISSUE THREAD

**Issue by SethFalcor** [RoyaleAPI/family-config#179]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `black`:
- `friendsforlife`:
- `emblem`:
- `Família FFL` and `https://royaleapi.com/clan/GYGY88 `:
- `GYGY88`:

Fill in the configuration below:

```yaml
name:FriendsForLife
key:FFL
color: black
emblem:
info:
  logo:
  description: >Clans de Guerra FFL


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:seth.games.project@gmail.com
clans:
  - name:•ANIQUILADORES•
    tag:9JCJU98
  - name:༄FFL࿐єχρєяιєи¢є
    tag:PUYJ0QV2
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
clan tag is wrong. Fixed it for you:

```yml
name: FriendsForLife
key: FFL
color: black
emblem:
info:
  logo:
  description: >
    Clans de Guerra FFL
  social:
    - email: mailto:seth.games.project@gmail.com
clans:
  - name: •ANIQUILADORES•
    tag: 9JCJUP98
  - name: ༄FFL࿐єχρєяιєи¢є
    tag: PUYJ0QV2

```
