### ISSUE TITLE
King Killers Family YAML

### ISSUE THREAD

**Issue by KKCaptainCR** [RoyaleAPI/family-config#18]
```yaml
name: King Killers Family
key: KK
color: grey
emblem: Skeleton_06
info:
  description: >
    The King Killers Family is an 8 Clan Family Looking for MORE!! Our clans range from Arena 4 to Arena 13 meaning anyone can fit in! 


Currently, our top Clan is on the edge of Legendary League and needs your help to stay there! It is highly Active, constantly in wars and led really well by the talented Family Owner KK Cami! 


All of our clans have great potential and are on their way up slowly! We frequently host Tournaments and Clan Versus Clan Events to boost our Members' skills and we are happy to do that for anyone wishing to join us! 


Sometimes, our Tournaments are opened up to Challengers too, you can find out about these Tournaments in our discord. You can find a link below! 


Our discord is small but us friendly and the hub to all our operations! We let people know our plans and information from it! 


We are working on building an eSports team so, get into our Clan Family to get the chance of a place in it! 


We ask that all our members push up with us allowing for opportunities of new clans and promotions! 


The Leaders to all of our clans are highly talented and are high level either on that account or on an alternative account meaning you will always be in knowledgable hands! 


Make sure that you are a part of our expanding, friendly, active family now! 
  social:
    - discord: https://discord.gg/NyFvdSD
clans:
  - name: King Killers
    tag: 9J9VVUP2
  - name: King Killers 2
    tag: 9V9R2988
  - name: King Killers 3
    tag: P8YPUUPV
  - name: King Killers 4
    tag: PL08QVRU
  - name: King Killers 5
    tag: 9U990PU9
  - name: King Killers 6
    tag: PYQ8J2VU
  - name: King Killers 7
    tag: 9VYGRJYL
  - name: King Killers 8
    tag: P2JCC992
```

**Comment by smlbiobot** [comment]
```yml
name: King Killers Family
key: KK
color: grey
emblem: Skeleton_06
info:
  description: >
    The King Killers Family is an 8 Clan Family Looking for MORE!! Our clans range from Arena 4 to Arena 13 meaning anyone can fit in!


    Currently, our top Clan is on the edge of Legendary League and needs your help to stay there! It is highly Active, constantly in wars and led really well by the talented Family Owner KK Cami!


    All of our clans have great potential and are on their way up slowly! We frequently host Tournaments and Clan Versus Clan Events to boost our Members' skills and we are happy to do that for anyone wishing to join us!


    Sometimes, our Tournaments are opened up to Challengers too, you can find out about these Tournaments in our discord. You can find a link below!


    Our discord is small but us friendly and the hub to all our operations! We let people know our plans and information from it!


    We are working on building an eSports team so, get into our Clan Family to get the chance of a place in it!


    We ask that all our members push up with us allowing for opportunities of new clans and promotions!


    The Leaders to all of our clans are highly talented and are high level either on that account or on an alternative account meaning you will always be in knowledgable hands!


    Make sure that you are a part of our expanding, friendly, active family now!
  social:
    - discord: https://discord.gg/NyFvdSD
clans:
  - name: King Killers
    tag: 9J9VVUP2
  - name: King Killers 2
    tag: 9V9R2988
  - name: King Killers 3
    tag: P8YPUUPV
  - name: King Killers 4
    tag: PL08QVRU
  - name: King Killers 5
    tag: 9U990PU9
  - name: King Killers 6
    tag: PYQ8J2VU
  - name: King Killers 7
    tag: 9VYGRJYL
  - name: King Killers 8
    tag: P2JCC992
```

- indent blocks
