### ISSUE TITLE
APG Esports config

### ISSUE THREAD

**Issue by J3H4M970N** [RoyaleAPI/family-config#181]
```yaml
name: [APG Esports]
key: [APG Esports]
color: blue
emblem: Crown_03
info:
  logo: https://ibb.co/xgssTY6
  description: >
    **"Join the Pride, greatness lies within."**

    **Apex Predator Gaming [APG Esports]**, founded in 2016, is an Esports coalition focused on cultivating best-in-class talent to deliver ourstanding results. We have one goal: **Building an Esports legacy.**

[APG Esports] thrives on challenging the status quo and doing things **on our terms.** We are committed to our athletes, to our community and to our craft.

We owe a deep debt of gratitude to each and every member of our community — we could not have come as far as we have without the unconditional dedication and true hard work of our gamers.

    
  social:
    - discord: https://discord.me/apg-esports/
    - reddit: https://www.reddit.com/u/APGEsports?utm_medium=android_app&utm_source=share/
    - youtube: https://www.youtube.com/channel/UC4VCvb6lVjIZNjmRyMQn8mA/
    - email: mailto: j.hamptonprofessional@gmail.com
clans:
  - name: The Lions
    tag: 2Q2ULLQ
  - name: The Lions II
    tag: YL0LUYYG
  - name: APG Level 1
    tag: L9V9PLQU
```
