### ISSUE TITLE
Atualização Família FriendsForLife 

### ISSUE THREAD

**Issue by SethFalcor** [RoyaleAPI/family-config#182]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

black:
friendsforlife:
emblem:
Família FFL and https://royaleapi.com/clan/GYGY88 :
GYGY88:
Fill in the configuration below:

name:FriendsForLife
key:FFL
color: black
emblem:
info:
  logo:
  description: >Bem Vindos à Família FriendsForLife, estamos entre os Top 5 Brasil de Guerras de Clãs, trabalhando incansavelmente para chegar no próximo objetivo que é o Top 3 Brasil. Acesso a FriendsForLife somente pelo WhatsApp +55 11 98999 7919 ou pelo nossos clãs de acesso •ANIQUILADORES• TAG 9JCJUP98 ou pela FFL єχρєяιєи¢є TAG PUYJ0QV2.

    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:seth.games.project@gmail.com
clans:

  - name:FriendsForLife
    tag:GYGY88
  - name:•ANIQUILADORES•
    tag:9JCJU98
  - name:༄FFL࿐єχρєяιєи¢є
    tag:PUYJ0QV2

**Comment by smlbiobot** [comment]
```yml
name: FriendsForLife
key: FFL
color: black
emblem: Skull_01
info:
  description: >
    Bem Vindos à Família FriendsForLife, estamos entre os Top 5 Brasil de Guerras de Clãs, trabalhando incansavelmente para chegar no próximo objetivo que é o Top 3 Brasil. Acesso a FriendsForLife somente pelo WhatsApp +55 11 98999 7919 ou pelo nossos clãs de acesso •ANIQUILADORES• TAG 9JCJUP98 ou pela FFL єχρєяιєи¢є TAG PUYJ0QV2.

  social:
    - email: mailto:seth.games.project@gmail.com
clans:
  - name: FriendsForLife
    tag: GYGY88
  - name: •ANIQUILADORES•
    tag: 9JCJUP98
  - name: ༄FFL࿐єχρєяιєи¢є
    tag: PUYJ0QV2
```
