### ISSUE TITLE
Hogg Riders Family

### ISSUE THREAD

**Issue by ehogg19** [RoyaleAPI/family-config#188]
```yaml
name: Hogg Riders Family
key: hoggriders
color: red
emblem: A_Char_Hammer_01.png
info:
  logo:
  description: >
    The **Hogg Riders Family** was established with it's main clan HoggRiders & Co on 4th October 2019.
    We are a friendly New Zealand based clan family whose goal is to be the best.
    We have 3 clans so feel free to join. 
  social:
    - discord: https://discord.gg/7KkW85G
    - instagram: https://www.instagram.com/hoggriders/
    - youtube: https://www.youtube.com/channel/UCOAaWHD4Gqf649P9DZsYmDw
clans:
  - name: HoggRiders & Co
    tag: YP0YL000
  - name: KIWI GODS
    tag: PUC9UCP8
  - name: LadderOnStrings
    tag: LRQQJ2QQ
```
