### ISSUE TITLE
Threat Level edit

### ISSUE THREAD

**Issue by duanegtr** [RoyaleAPI/family-config#189]
name: Threat Level
key: threatlevel
color: blue
emblem: Fugi_03
info:
  logo: https://media.discordapp.net/attachments/681561228707233890/681593782411722762/TL_-_gradient_color.png
  description: >
    Threat Level Clan Family was established by the players, for the players. 
    Our goal was to establish an organization that was both fun and friendly yet
    offers our players the chance to advance their gameplay through our coaching system
    and our eSports partner, Instinct eSports.
  social:
    - discord: https://discord.gg/BDyfHu6
clans:
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Cyclone
    tag: 9QVYYYV0
  - name: TL Titans
    tag: PGPQQ8UV
  - name: TL Nitro
    tag: 9YYLQ99L
  - name: TL Chill
    tag: PPCG80G0
  - name: TL Plasma
    tag: PGQY9Q9C
  - name: TL Justice
    tag: LR9CY9VQ
  - name: Baba Yaga
    tag: YPUYYPP9
    ```

**Comment by smlbiobot** [comment]
assuming that only logo is added and emblem is changed, please in the future edit this config instead:

```yml
name: Threat Level
key: threatlevel
color: blue
emblem: Fugi_03
info:
  logo: /static/img/brands/logo/threat-level.png
  description: >
    Threat Level Clan Family was established by the players, for the players.
    Our goal was to establish an organization that was both fun and friendly yet
    offers our players the chance to advance their gameplay through our coaching system
    and our eSports partner, Instinct eSports.
  social:
    - discord: https://discord.gg/BDyfHu6
clans:
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL Cyclone
    tag: 9QVYYYV0
  - name: TL Titans
    tag: PGPQQ8UV
  - name: TL Nitro
    tag: 9YYLQ99L
  - name: TL Chill
    tag: PPCG80G0
  - name: Baba Yaga
    tag: YPUYYPP9
```
