### ISSUE TITLE
Hoops Squad Family

### ISSUE THREAD

**Issue by HotShot-730** [RoyaleAPI/family-config#190]
```yaml
name: Hoops Squad Family
key: Hoops Squad
color: blue
emblem: Traditional_Star_05
info:
  logo:
  description: >
Hoops Squad has been around since the fall of 2016. 
We are a top 150 USA clan and run Clan Wars 24/7.
Promotions are earned through high activity and encouragement of other members.
Join us as we push to become a top global clan. 


clans:
  - name: Hoops Squad
    tag: Q02UGGQ
  - name: Hoops Squad Jr.
    tag: LQCGJP20
  - name: Hoops Squad 3
    tag: YR2YCRQQ
```

**Comment by smlbiobot** [comment]
keys cannot have spaces

```yml
name: Hoops Squad Family
key: hoops-squad
color: blue
emblem: Traditional_Star_05
info:
  description: >
    Hoops Squad has been around since the fall of 2016.
    We are a top 150 USA clan and run Clan Wars 24/7.
    Promotions are earned through high activity and encouragement of other members.
    Join us as we push to become a top global clan.
clans:
  - name: Hoops Squad
    tag: Q02UGGQ
  - name: Hoops Squad Jr.
    tag: LQCGJP20
  - name: Hoops Squad 3
    tag: YR2YCRQQ
```
