### ISSUE TITLE
Samurai.PT Family

### ISSUE THREAD

**Issue by CristianoCruzSD** [RoyaleAPI/family-config#194]
```yaml
name: Samurai.PT Family
key: samuraipt
color: Yellow
emblem: Traditional_Star_06.png

info:
  logo: https://photos.app.goo.gl/rBcgxfr11RNjeu7m7

  description: >
    **Samurai.PT** is a _Portuguese_ team, that was founded in the 4th of December 2018.
From the very beginning we've always been an united clan with great ambition. As a team we aspire to be one of the best and the most feared team in Portugal! 
We also aim to participate in national Clash Royale tournaments.


  social:
    - twitter: https://www.twitter.com/SamuraiPT1
    - discord: https://discord.gg/EWxfsGq
    - twitch: http://www.twitch.tv/teamsamuraipt
    - reddit: https://www.reddit.com/u/TeamSamuraiPT
    - youtube: https://www.youtube.com/channel/
    - website: https://samurai-pt0.webnode.pt/
    - OmletArcade: https://omlet.gg/profile/samurai.pt
    - instagram: https://www.instagram.com/teamsamurai.pt/
    - facebook: https://m.facebook.com/SamuraiPt
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://samuraipt.teamapp.com/
    - email: teamsamurai.pt@gmail.com
clans:
  - name: Samurai.PT 
    tag: 9VVR0VQP
  - name: Samurai.PT 2
    tag: PG89V9CP
  - name: Samurai.PT 3
    tag: Y0C2P8GG
```

**Comment by CristianoCruzSD** [comment]
> ```yaml
> nome : Samurai.PT 
> Chave da família : SamuraiPT 
> cor : Emblema amarelo
>  : Traditional_Star_06.png
> 
> info :
>    logo : https://images.app.goo.gl/sPbJwVPEij82FQKA8
> 
>   description : > 
>     ** Samurai.PT ** é uma equipe _Portuguese_, fundada em 4 de dezembro de 2018.
> Desde o início, sempre fomos um clã unido com grande ambição. Como equipa, aspiramos ser uma das melhores e mais temidas equipas de Portugal! 
> Também pretendemos participar de torneios nacionais de Clash Royale.
> 
> 
>   social :
>     - twitter : https://www.twitter.com/SamuraiPT1 
>     - discórdia : https://discord.gg/EWxfsGq 
>     - twitch : http://www.twitch.tv/teamsamuraipt 
>     - reddit : https: //www.reddit .com / u / TeamSamuraiPT 
>     - youtube : https://www.youtube.com/channel/ 
>     - site : https://samurai-pt0.webnode.pt/ 
>     - instagram : https://www.instagram.com/teamsamurai .pt / 
>     - facebook : https://m.facebook.com/SamuraiPt 
>     - twitch: https://twitch.tv/ 
>     - youtube : https://www.youtube.com/channel/ 
>     - aplicativo : https://samuraipt.teamapp.com/ 
>     - e - mail : teamsamurai.pt@gmail.com 
> clãs :
>   - nome : Samurai.PT 
>     tag : 9VVR0VQP 
>   - nome : Samurai.PT 2 
>     tag : PG89V9CP
> ```

Excuse me.  I closed unintentionally.  Confirm when to update please

**Comment by smlbiobot** [comment]
```yml
name: "Samurai.PT Family"
key: samuraipt
color: Yellow
emblem: Traditional_Star_06
info:
  logo: /static/img/brands/logo/samaraipt.png

  description: >
    **Samurai.PT** is a _Portuguese_ team, that was founded in the 4th of December 2018.


    From the very beginning we've always been an united clan with great ambition. As a team we aspire to be one of the best and the most feared team in Portugal!


    We also aim to participate in national Clash Royale tournaments.


  social:
    - twitter: https://www.twitter.com/SamuraiPT1
    - discord: https://discord.gg/EWxfsGq
    - twitch: http://www.twitch.tv/teamsamuraipt
    - reddit: https://www.reddit.com/u/TeamSamuraiPT
    - website: https://samurai-pt0.webnode.pt/
    - omlet: https://omlet.gg/profile/samurai.pt
    - instagram: https://www.instagram.com/teamsamurai.pt/
    - facebook: https://m.facebook.com/SamuraiPt
    - application: https://samuraipt.teamapp.com/
    - email: teamsamurai.pt@gmail.com
clans:
  - name: Samurai.PT
    tag: 9VVR0VQP
  - name: Samurai.PT 2
    tag: PG89V9CP
  - name: Samurai.PT 3
    tag: Y0C2P8GG
```

**Comment by smlbiobot** [comment]
added

**Comment by CristianoCruzSD** [comment]
```yaml
name: Samurai.PT Family
key: samuraipt
color: yellow
emblem: Traditional_Star_06.png

info: Recrutamentos apenas por Facebook ou Discord
  logo: https://photos.app.goo.gl/rBcgxfr11RNjeu7m7

  description: >
    **Samurai.PT** is a _Portuguese_ team, that was founded in the **4th of December 2018**.
From the very beginning we've always been an united clan with great ambition. As a team we aspire to be one of the best and the most feared team in **Portugal**! 
We also aim to participate in national Clash Royale tournaments.
  Se achas que tens o perfil para te juntares a nossa família, envia-nos mensagem pela nossa página facebook ou Discord. 

  social:
    - twitter: https://www.twitter.com/SamuraiPT1
    - discord: https://discord.gg/EWxfsGq
    - twitch: http://www.twitch.tv/teamsamuraipt
    - reddit: https://www.reddit.com/u/TeamSamuraiPT
    - youtube: https://www.youtube.com/channel/
    - website: https://samurai-pt0.webnode.pt/
    - OmletArcade: https://omlet.gg/profile/samurai.pt
    - instagram: https://www.instagram.com/teamsamurai.pt/
    - facebook: https://m.facebook.com/SamuraiPt
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://samuraipt.teamapp.com/
    - email: teamsamurai.pt@gmail.com
clans:
  - name: Samurai.PT 
    tag: 9VVR0VQP
  - name: Samurai.PT 2
    tag: PG89V9CP
  - name: Samurai.PT 3
    tag: Y0C2P8GG
```

update please:
-color
-info
-description
-email "link error"
thank you :)
