### ISSUE TITLE
Opsters Empire

### ISSUE THREAD

**Issue by opster3-0** [RoyaleAPI/family-config#195]
name: Opsters Empire
Key: Opsters
Color: Blue
emblem: flag_j_03.png
Info:
Logo: https://scontent.flhr3-1.fna.fbcdn.net/v/t1.0-9/89789722_611371819719964_2299453729964818432_n.jpg?_nc_cat=103&_nc_sid=8024bb&_nc_ohc=PenOO-bLK_wAX8Nkdcu&_nc_ht=scontent.flhr3-1.fna&oh=d497ec6589899fd146cc92b84cabbc2c&oe=5E927C19
Description: >
The **Opsters Empire** Is a family of clans throughout multiple different games. 
We first started the Opstwes clans in early 2018 when we made Opsters. 
Ever since then we have made Opsters2 Clash Royale, Opsters5 Clash Roayle, Opsters Dormant Clash Royale, Opsters Brawl Stars, Opsters Clash Of Clans, OpstersArmy Cod Mobile. 
Opsters has reached top 30 UK in the last year and Opster2 reached top 200 UK. We previously had an Opsters4 but we merged it into Opsters5 which has now reached top 500 UK.
We are also top 100 UK in the Brawl Stars and very successful in other games as well. 
We also have a discord server where players of all clans and games can interact with one another.

Social:
Discord: Opsters Empire, link provided in clans
Clans:
Name: Opsters
Tag: #9VRJ028J
Name: Opsters2
Tag: #PLUCUJ9J
Name: Opsters5
Tag: #L8Y0Y0V0
Name: Opsters Dormant
Tag: #YGJJJ2LU
Name: Opsters4
Tag: #PQRUQ88U

**Comment by smlbiobot** [comment]
please don’t remove spaces.keep formatting

```yml
name: Opsters Empire
key: opsters
color: Blue
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/opsters.jpg
  description: >
    The **Opsters Empire** Is a family of clans throughout multiple different games.
    We first started the Opstwes clans in early 2018 when we made Opsters.
    Ever since then we have made Opsters2 Clash Royale, Opsters5 Clash Roayle, Opsters Dormant Clash Royale, Opsters Brawl Stars, Opsters Clash Of Clans, OpstersArmy Cod Mobile.
    Opsters has reached top 30 UK in the last year and Opster2 reached top 200 UK. We previously had an Opsters4 but we merged it into Opsters5 which has now reached top 500 UK.
    We are also top 100 UK in the Brawl Stars and very successful in other games as well.
    We also have a discord server where players of all clans and games can interact with one another.


clans:
  - name: Opsters
    tag: 9VRJ028J
  - name: Opsters2
    tag: PLUCUJ9J
  - name: Opsters5
    tag: L8Y0Y0V0
  - name: Opsters Dormant
    tag: YGJJJ2LU
  - name: Opsters4
    tag: PQRUQ88U

```
