### ISSUE TITLE
 The Straw hats family

### ISSUE THREAD

**Issue by Mrt313** [RoyaleAPI/family-config#197]
name: the straw hats + mini wheats 
key: strawhats mini wheats
color: blue
emblem: A_char_pekka_01

  social:
   - discord: http://discord.gg/UKvjJXS
    
 -facebook: https://facebook.com/groups/589994975125344/
clans:
  - name: The straw hats
    tag: VGV0LQ9
  - name: mini wheats
    tag: YQRGR2PV
```

**Comment by smlbiobot** [comment]
- keys can’t have space in them

```yml
name: the straw hats + mini wheats
key: strawhats-mini-wheats
color: blue
emblem: A_char_pekka_01
info:
  social:
   - discord: http://discord.gg/UKvjJXS
   - facebook: https://facebook.com/groups/589994975125344/
clans:
  - name: The straw hats
    tag: VGV0LQ9
  - name: mini wheats
    tag: YQRGR2PV
```
