### ISSUE TITLE
Jedi Clan Family

### ISSUE THREAD

**Issue by ClashAlex** [RoyaleAPI/family-config#199]
```yaml
name: Jedi Clan Family
key: Jedi
color: blue
emblem: Fugi_02
info:
  logo: 
  description: >
    Originally formed on the first day of the beta testing, one of the oldest clan families in the game. 
  social:
    - discord: https://discord.me/jedifamily
clans:
  - name: Jedi Masters
    tag: P9C0UG0J
  - name: Jedi Order
    tag: 9UGQ0LRY
  - name: Jedi Knights
    tag: 8Q8GPU
```

**Comment by smlbiobot** [comment]
```yml
name: Jedi Clan Family
key: jedi
color: blue
emblem: Fugi_02
info:
  logo:
  description: >
    Originally formed on the first day of the beta testing, one of the oldest clan families in the game.
  social:
    - discord: https://discord.me/jedifamily
clans:
  - name: Jedi Masters
    tag: P9C0UG0J
  - name: Jedi Order
    tag: 9UGQ0LRY
  - name: Jedi Knights
    tag: 8Q8GPU
```
