### ISSUE TITLE
Rocket´s Family

### ISSUE THREAD

**Issue by RL-Royal** [RoyaleAPI/family-config#201]
name: Rockets Familie
key: rockets
color: blue
emblem: A_Char_Rocket_01
info: Rocket‘s Familie🚀rockets-cr.de🚀Top DE Clan 🚀Bewerbung via Line: funnyfox2🚀dennis-rockets🚀 Rockets eSports🚀home Rockets League🚀
  logo:
  description: Die Clanfamilie ist für alle die perfekt, die in eine Clanfamilie wollen, wo ZUSAMMENHALT groß geschrieben wird, und die gerne CW spielen. 

    Long paragraphs with markdown syntax.

    Add new line with 2 line breaks as above.
  social:
 
    - website: rockets-cr.de
    - application: pls apply via LINE

clans:
  - name: Rocket's
    tag: 28V2QQ9C
  - name: Rocket Academy
    tag: 9R2R28JL
  - name: Rocket's Wing
    tag: 2V0JL0L9
  - name: Rocket Schmiede
    tag: LGJLGG99

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
```yml
name: Rockets Familie
key: rockets
color: blue
emblem: A_Char_Rocket_01
info:
  description: >
    Rocket‘s Familie🚀rockets-cr.de🚀Top DE Clan 🚀Bewerbung via Line: funnyfox2🚀dennis-rockets🚀 Rockets eSports🚀home Rockets League🚀
    Die Clanfamilie ist für alle die perfekt, die in eine Clanfamilie wollen, wo ZUSAMMENHALT groß geschrieben wird, und die gerne CW spielen.
  social:
    - website: http://rockets-cr.de

clans:
  - name: Rocket's
    tag: 28V2QQ9C
  - name: Rocket Academy
    tag: 9R2R28JL
  - name: Rocket's Wing
    tag: 2V0JL0L9
  - name: Rocket Schmiede
    tag: LGJLGG99
```
