### ISSUE TITLE
青岛 Tsingtao

### ISSUE THREAD

**Issue by hongyang0717** [RoyaleAPI/family-config#203]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 青岛 Tsingtao
key: qingdao
color: Red
emblem: Cherry_Blossom_06
info:
  logo:
  description: >
    【Set up】2016.05.29
    【Location】Qingdao, Shandong, China
    【WeChat】383369805

  social:
    - email: mailto: hongyang0717@hotmail.com
clans:
  - name: 青岛 Tsingtao
    tag: PVLCGYQ
  - name: 青岛 Tsingtao^
    tag: QQ0UQPV 
  - name: 青岛 Tsingtao^^
    tag: VUPQ8CU
  - name: 青岛 Tsingtao^^^
    tag: 20U0888Q
```
