### ISSUE TITLE
Rebel Riot - Update/ Add New Clans

### ISSUE THREAD

**Issue by AwfyAlba** [RoyaleAPI/family-config#204]
name: Rebel Riot Family
key: rebelriot
color: red
emblem: Diamond_02
info:
logo: https://i.postimg.cc/c4NDfLxV/rebel-riot-source-snap.png
description: >
🛡 **𝕽𝖊𝖇𝖊𝖑 𝕽𝖎𝖔𝖙** 🛡 part of **𝐭𝐞𝐚𝐦𝐑𝐃𝐘𝐊.com** - A vibrant Supercell gaming community. Highly active, war focused clans for competitive players.  **Discord:** VpR3BRq
social:
- discord: https://discord.gg/VpR3BRq
- reddit: https://www.reddit.com/message/compose/?to=Rebel_Riot_Gaming
- email: mailto:rebelriotgaming@outlook.com
clans:

name: Rebel Riot Club
tag: PPRJ8RPQ
name: Rebel Riot APEX
tag: PUQ99L0R
name: Rebel Riot ONYX
tag: YJRGCUUL
name: Rebel Riot ZERO
tag: Y289LP00
…

**Comment by AwfyAlba** [comment]
Changed the name.
Changed the emblem.
Changed description.
Removed 1 clan.
Added 2 clans.

**Comment by Qing-guap** [comment]
invalid e

**Comment by Qing-guap** [comment]
...

**Comment by smlbiobot** [comment]
```yml
name: Rebel Riot Family
key: rebelriot
color: red
emblem: Diamond_02
info:
  logo: /static/img/brands/logo/rebel-riot-source-snap.png
  description: >
    🛡 **𝕽𝖊𝖇𝖊𝖑 𝕽𝖎𝖔𝖙** 🛡 part of **𝐭𝐞𝐚𝐦𝐑𝐃𝐘𝐊.com** - A vibrant Supercell gaming community. Highly active, war focused clans for competitive players.  **Discord:** VpR3BRq
  social:
    - discord: https://discord.gg/VpR3BRq
    - reddit: https://www.reddit.com/message/compose/?to=Rebel_Riot_Gaming
    - email: mailto:rebelriotgaming@outlook.com
clans:
  - name: Rebel Riot Club
    tag: PPRJ8RPQ
  - name: Rebel Riot APEX
    tag: PUQ99L0R
  - name: Rebel Riot ONYX
    tag: YJRGCUUL
  - name: Rebel Riot ZERO
    tag: Y289LP00

```
