### ISSUE TITLE
We're Austria Family

### ISSUE THREAD

**Issue by LiquidStarch** [RoyaleAPI/family-config#205]
``` yaml
name: WE'RE AUSTRIA Family
key: austria
color: purple
emblem: Traditional_Star_05
info:
  logo: https://user-images.githubusercontent.com/62908413/77958856-fc04e080-72d5-11ea-843d-b96edf0d4f62.jpg
  description: >
**TOP Clan Family in Austria - #1 Clan local**
We are a goal-driven family out of 4 clans. Our clans are constantly growing and developing day by day. We are always looking for active Clashers who want to join our family.
**~ Come together and play together ~**
    Long paragraphs with markdown syntax.


  social:
    - discord: https://discord.gg/5ptFqn
    - instagram: https://www.instagram.com/were_austria/

clans:
  - name: ⭐WE'RE AUSTRIA⭐
    tag: Y9GCCYR8
  - name: WE'RE AUSTRIA
    tag: PY9Q9CPY
  - name: WE'RE AUSTRIA 2
    tag: 9VRQO8GC
  - name; WE'RE AUSTRIA 3
    tag: 9VRQ9QGJ

```

**Comment by smlbiobot** [comment]
```yml
name: WE'RE AUSTRIA Family
key: austria
color: purple
emblem: Traditional_Star_05
info:
  logo: /static/img/brands/logo/austria.png
  description: >
    **TOP Clan Family in Austria - #1 Clan local**
    We are a goal-driven family out of 4 clans. Our clans are constantly growing and developing day by day. We are always looking for active Clashers who want to join our family.
    **~ Come together and play together ~**

  social:
    - discord: https://discord.gg/5ptFqn
    - instagram: https://www.instagram.com/were_austria/

clans:
  - name: ⭐WE'RE AUSTRIA⭐
    tag: Y9GCCYR8
  - name: WE'RE AUSTRIA
    tag: PY9Q9CPY
  - name: WE'RE AUSTRIA 2
    tag: 9VRQO8GC
  - name: WE'RE AUSTRIA 3
    tag: 9VRQ9QGJ
```
