### ISSUE TITLE
Soaring Death的部落

### ISSUE THREAD

**Issue by soaringdeath** [RoyaleAPI/family-config#206]
```yaml
name: Soaring Death的部落
key: TEAM REMSS
color: red
emblem: Cherry_Blossom_07
info: 
  logo: Cherry_Blossom_07
  description: >这是一个隐居的小部落。欢迎加入，来的都是朋友。TEAM REMSS 为总部，欢迎各路人马加入我们和谐的大家庭。在我们的大家庭中，部落战的重要性排在首位，其次是捐赠。如果7天不上线/骂人/不打部落战/50捐赠以下会直接被踢。这个家庭的首领为AWM扫荡者（#9CVCRGGLP）和BL｜RayJiao焦雷兄（#28829JGQ）。主要招华人玩家。English also welcome!


  social:
      - discord: http://discord.gg/soaring death#7637
    - email: mailto: edricmeng@gmail.com
clans:
  - name: TEAM REMSS
    tag: YUV2V8LG
  - name: TEAM REMSS 鹰潭
    tag: LPLUCJCQ
  - name: 先摸菊花后闻手
    tag: YY9YVP0Q 
- name: SOARING DEATH
    tag: YLCYRQL8
```

**Comment by smlbiobot** [comment]
Your discord link is wrong — it needs to be linking to a server. (should be the server invite link)

**Comment by smlbiobot** [comment]
also changed your family key:

```yml
name: Soaring Death的部落
key: team-remss
color: red
emblem: Cherry_Blossom_07
info:
  logo: Cherry_Blossom_07
  description: >
    这是一个隐居的小部落。欢迎加入，来的都是朋友。TEAM REMSS 为总部，欢迎各路人马加入我们和谐的大家庭。在我们的大家庭中，部落战的重要性排在首位，其次是捐赠。如果7天不上线/骂人/不打部落战/50捐赠以下会直接被踢。这个家庭的首领为AWM扫荡者（#9CVCRGGLP）和BL｜RayJiao焦雷兄（#28829JGQ）。主要招华人玩家。English also welcome!


  social:
    - email: mailto:edricmeng@gmail.com
clans:
  - name: TEAM REMSS
    tag: YUV2V8LG
  - name: TEAM REMSS 鹰潭
    tag: LPLUCJCQ
  - name: 先摸菊花后闻手
    tag: YY9YVP0Q
  - name: SOARING DEATH
    tag: YLCYRQL8
```
