### ISSUE TITLE
UnderWorld Family

### ISSUE THREAD

**Issue by Feliniacr** [RoyaleAPI/family-config#207]
```yaml

name: UnderWorld (UW)
color: purple
emblem: Elixir_02.png
info: 
logo: https://yt3.ggpht.com/a/AATXAJxzKR0LMgEdB0zF0FuEX9vaQt-7F2umjX7XnA=s288-c-k-c0xffffffff-no-rj-mo
description: The UnderWorld (UW) Clan Family consists of 6 clans. We have a friendly, competitive focus and work hard to help each other improve. Our clans’ members are from 28 countries and 6 continents. Over 1000 people enjoy our Discord-based community server which features channels for strategy assistance and events.
social: 
-discord: https://discord.gg/m6WKDFz
-twitter: https://twitter.com/UnderWorldCR
clans: 
name: Underated
tag: #222VGJ
name: UnderSiege
tag:#PPY2LPYU
name: UnderCover
tag:#9VY89UC2
name: HeroHaven
tag:#P2JRCPR2
name: Adderall Addicts
tag:#YCUP889G
name: Kings Landing
tag: #JRQJ0
```

**Comment by smlbiobot** [comment]
```yml
name: UnderWorld (UW)
key: underworld
color: purple
emblem: Elixir_02.png
info: 
  logo: /static/img/brands/logo/underworld.png
  description: The UnderWorld (UW) Clan Family consists of 6 clans. We have a friendly, competitive focus and work hard to help each other improve. Our clans’ members are from 28 countries and 6 continents. Over 1000 people enjoy our Discord-based community server which features channels for strategy assistance and events.
  social: 
  - discord: https://discord.gg/m6WKDFz
  - twitter: https://twitter.com/UnderWorldCR
clans: 
 - name: Underated
   tag: 222VGJ
 - name: UnderSiege
   tag: PPY2LPYU
 - name: UnderCover
   tag: 9VY89UC2
 - name: HeroHaven
   tag: P2JRCPR2
 - name: Adderall Addicts
   tag: YCUP889G
 - name: Kings Landing
   tag: JRQJ0
```
