### ISSUE TITLE
win盟

### ISSUE THREAD

**Issue by 000fy000** [RoyaleAPI/family-config#209]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: WIN盟
key: winleague
color: red
emblem: Heart_04.png
info:
  description: >
      这是一个创建于2020年2月20日，有着11个成员部落的，欣欣向荣的部落联盟。
      我们欢迎每一个成员加入这个大家庭——无论是刚出训练营的新人还是在排行榜上留下姓名的大佬。
      我们的QQ群：972976967，欢迎各路人马前来加入我们的大家庭。
clans:
  - name: 沈婷婷我爱你
    tag: PLPCC0QG
  - name: coincidence
    tag: LYLR20LU
  - name: coincidence②
    tag: PU8V20VQ
  - name: coincidence③hxy
    tag: L9RJJJ82
  - name: coincidence④
    tag: LGJ0JJJJ
  - name: coincidence⑤stt
    tag: PUL8COVR
  - name: ☆冰☆
    tag: 8YQU0JPP
  - name:  
    tag: YGJRYGJU
  - name: vv的城堡
    tag: YYVPQ0UV
  - name: 划船唔洗浆
    tag: YY9L9U82
  - name: 只谈生不逢时矣
    tag: YLGJ9PL2
```
[win.yml.txt](https://github.com/RoyaleAPI/family-config/files/4420556/win.yml.txt)

**Comment by smlbiobot** [comment]
the “clever” name of one of your clan created an issue on the UI. There’s no way around it, I’m afraid…

**Comment by smlbiobot** [comment]
```yml
name: WIN盟
key: winleague
color: red
emblem: Heart_04
info:
  description: >
      这是一个创建于2020年2月20日，有着11个成员部落的，欣欣向荣的部落联盟。
      我们欢迎每一个成员加入这个大家庭——无论是刚出训练营的新人还是在排行榜上留下姓名的大佬。
      我们的QQ群：972976967，欢迎各路人马前来加入我们的大家庭。
clans:
  - name: 沈婷婷我爱你
    tag: PLPCC0QG
  - name: coincidence
    tag: LYLR20LU
  - name: coincidence②
    tag: PU8V20VQ
  - name: coincidence③hxy
    tag: L9RJJJ82
  - name: coincidence④
    tag: LGJ0JJJJ
  - name: coincidence⑤stt
    tag: PUL8COVR
  - name: ☆冰☆
    tag: 8YQU0JPP
  - name: _
    tag: YGJRYGJU
  - name: vv的城堡
    tag: YYVPQ0UV
  - name: 划船唔洗浆
    tag: YY9L9U82
  - name: 只谈生不逢时矣
    tag: YLGJ9PL2
```
