### ISSUE TITLE
#Neptune09 family

### ISSUE THREAD

**Issue by TeoMannis** [RoyaleAPI/family-config#21]
```yaml
name: Neptune09 family
key: Neptune09
color: Red
emblem: Diamond_Star_03
info:
  description: Started by a sole earthling guy in 2017, the family has been expanding ever since its first interstellar travel up to setting colonies in Neptune, Mars, Mercury and Venus. Planning to conquer the whole SolarSystem and then off to new galaxies!
clans:
  - name: Neptune09
    tag: 22UUQ8CP
  - name: Mars09
    tag: 9LVRGYR9
  - name: Mercury09
    tag: 9U9QG890
  - name: Venus09
    tag: PUQ0GJCC
```
