### ISSUE TITLE
From Korea Family clans

### ISSUE THREAD

**Issue by david-464** [RoyaleAPI/family-config#210]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: From Korea
key: Korea
color: yellow
emblem: flag_c_02
info: N/A
  logo: https://www.google.com/search?q=red+and+blue+clan+badge+clash+royale&tbm=isch&ved=2ahUKEwjCg7zGvM3oAhWNHt8KHbUMBiMQ2-cCegQIABAA&oq=red+and+blue+clan+badge+clash+royale&gs_lcp=CgNpbWcQA1C2d1injwFg4KsBaABwAHgBgAGuB4gB1iySAQ0wLjEuMS4yLjMuMS4zmAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img&ei=Kc-HXoLLLo29_Aa1mZiYAg&bih=657&biw=1366#imgrc=Z8MqAd8TkK8DfM
  description: >

 esports discord // no pr but ty // imagine using magic archer // 6: 00pm sp. ox guap // clan tournament every monday 11: 00am // monthlymvp

  social:
 
    - discord: https://discord.gg/WW3Dxn
    - twitch: https://www.twitch.tv/sk_david_
    - instagram: @davidyoung_46
    
  
clans:
  - name: From Korea
    tag: PGUGLGCC
  - name: from korea mini
    tag: Y2RV2Y2Y

```

**Comment by smlbiobot** [comment]
```yml
name: From Korea
key: korea
color: yellow
emblem: flag_c_02
info:
  logo: /static/img/badge/flag_c_02.png
  description: >
    esports discord // no pr but ty // imagine using magic archer // 6: 00pm sp. ox guap // clan tournament every monday 11: 00am // monthlymvp

  social:
    - discord: https://discord.gg/WW3Dxn
    - twitch: https://www.twitch.tv/sk_david_
    - instagram: https://instagram.com/davidyoung_46
clans:
  - name: From Korea
    tag: PGUGLGCC
  - name: from korea mini
    tag: Y2RV2Y2Y
```
