### ISSUE TITLE
Request to family in royals api

### ISSUE THREAD

**Issue by Qing-guap** [RoyaleAPI/family-config#211]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do noet include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 皇室部落family
key: 皇室部落
color: blue
emblem: A_Char_King_03.png
sort: trophy
info:
   logo: https://android-artworks.25pp.com/fs08/2019/08/20/8/110_54ada0b72702cfb014aefa187c027f7e_con.png
  description: >
    ⚪️欢迎来到 “皇室部落family”   😃     🇨🇳
    ⚫️QQ群：6️⃣9️⃣1️⃣6️⃣5️⃣2️⃣0️⃣8️⃣1️⃣ 🤝 👥
    🔴享受游戏，享受健康生活 👍🏻
    🔵欢迎各高手加入! ✅
     👉🏻Clash Royale - RoyaleApi💪🏻
      🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
  social:
    - email：juegocai@gmail.com
clans:
  - name: 皇室部落clan
    tag: 8U99GPGU
  - name: 皇室精英队
    tag: PYVLGRQU
  - name: 皇室雷霆队
    tag: YCQYQ0QR
    ```

**Comment by Qing-guap** [comment]
If this logoi isn’t valid, please use the next (https://pm1.narvii.com/6437/6a0e829ada05882b27390839926f40ebb55627df_hq.jpg)
If this neither valid use (https://android-artworks.25pp.com/fs08/2019/08/20/8/110_54ada0b72702cfb014aefa187c027f7e_con.png)
please and thank!

**Comment by smlbiobot** [comment]
Can’t give you chinese url keys (it may have unexpected behaviors on our servers). So I just call it `crclan` — if you want it to be something else, let me know

```yml
name: 皇室部落family
key: crclan
color: blue
emblem: A_Char_King_03.png
sort: trophy
info:
  logo: /static/img/brands/logo/crclan.png
  description: >
    ⚪️欢迎来到 “皇室部落family”   😃     🇨🇳


    ⚫️QQ群：6️⃣9️⃣1️⃣6️⃣5️⃣2️⃣0️⃣8️⃣1️⃣ 🤝 👥


    🔴享受游戏，享受健康生活 👍🏻


    🔵欢迎各高手加入! ✅

    
     👉🏻Clash Royale - RoyaleApi💪🏻
      🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
  social:
    - email: mailto:juegocai@gmail.com
clans:
  - name: 皇室部落clan
    tag: 8U99GPGU
  - name: 皇室精英队
    tag: PYVLGRQU
  - name: 皇室雷霆队
    tag: YCQYQ0QR
```
