### ISSUE TITLE
Crown Clown Family

### ISSUE THREAD

**Issue by slip2cc** [RoyaleAPI/family-config#214]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: CrownClowns
key: CrownClowns
color: blue
emblem: Crown_02
info:
  logo:
  description: > 3CrownClowns - 2CrownClowns - 1CrownClowns - 0CrownClowns Network. 50+ level 11+ cards to join. Est 09/06/18
  
  
  social:
    - email: crownclownfamily@gmail.com 
clans:
  - name: 3CrownClowns
    tag: P02Q8JUR
  - name: 2CrownClowns
    tag: PY08VYRY
  - name: 1CrownClowns
    tag: PP9VG9CL
  - name: 0CrownClowns
    tag: YJJUV0L8
```
