### ISSUE TITLE
Lotus

### ISSUE THREAD

**Issue by Alpha-Jam** [RoyaleAPI/family-config#215]
```yaml
name: :Lotus
key: lotus
color: black
emblem: Lotus_01
info:
  logo: https://imgur.com/a/LfhIIhv
  description: >
**Black Lotus** and **White Lotus**
  social:
    - discord: http://discord.gg/XUSP55K
clans:
  - name: Black Lotus
    tag: PCVYYYYY
  - name: White Lotus
    tag: PCOU2222
```
