### ISSUE TITLE
Avalanche: update

### ISSUE THREAD

**Issue by juanvaq** [RoyaleAPI/family-config#216]
Hi, I'd like to add one more clan to the Avalanche Family. I've already written the code but I don't know if I should open a new issue like the first time or there is another method.
Thanks in advance

**Comment by juanvaq** [comment]
```yaml
name: Avalanche Family
key: Avl_Fam
color: teal
emblem: Twin_PEAKS_01
info:
  logo: Avalanche-fam/4AA28BA8-C59A-4E3E-AA70-5BBCB2A6F198.jpeg
  description: >
    **Avalanche Family** is a friendly and mature group of people with a lot of experience in the game.
    We have 4 clans of different levels and a very active discord server.
    We care about our players and try to get them to their max potential through our clans.
    The family is focused in war and ladder.
    Avalanche is our best clan for top ladder and war players
    Blitzkrieg is for competitive war players that aren't already maxed but can compete at legendary war league
    Fatality is for active and competitive players that want to increase their levels before moving to Avalanche
    Star Lords is our casual clan for more relaxed players.
  social:
    -discord: https://discord.gg/thqNfdY
  clans:
    -name: Avalanche
    tag: 9QRYQ9YR
    -name: Blitzkrieg
    tag: CQQY89
    -name: Fatality
    tag: YR8UJ
    -name: Star Lords
    tag: UVQ88Q
```
