### ISSUE TITLE
The True Family Clans

### ISSUE THREAD

**Issue by Kelvin-AZ** [RoyaleAPI/family-config#219]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: The True Family Clans
key: discord.gg/FRXbGXk
color: violet
emblem: elixir_01
info:
  logo: Elixir
  description: >
    Long paragraphs with markdown syntax.
Clans range from competitive to social.  Find the clan that fits your play style.

    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: True Spirit
    tag: 8vlc2rq8
  - name: True Peace
    tag: 9v8qjp0
  - name: True Heart
    tag: 2r8lpvq8
  - name: True Brew
    tag: pypyvl9l
  - name: True Shot
    tag: 9vyj2yvu
```
