### ISSUE TITLE
S-Tier

### ISSUE THREAD

**Issue by SUSHI-CR** [RoyaleAPI/family-config#221]
```yaml
name: S-Tier Family
key: S-Tier
color: blue
emblem: Star_Shine_02
info:
  description: >
    S-Tier family is a new clan family for low arena players. We give rewards for players who excel in clan wars and host 
    mini tourlements every season.
clans:
  - name: S-Tier SG
    tag: PV8JQGY0 
  - name: S-Tier ACE
    tag: YQ8QCQQ9
 ```
