### ISSUE TITLE
RoyaleAPI.com

### ISSUE THREAD

**Issue by nitin007-k** [RoyaleAPI/family-config#222]
```yaml
name: RoyaleAPI Clan Family
key: royaleapi
color: red
emblem: sword_2
info:
  logo: 
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application:  
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name: EŁECŤRÍÝ CÍTÝ
    tag: 9RV2LOUQ
```
