### ISSUE TITLE
KING_hzgh

### ISSUE THREAD

**Issue by 1227301688** [RoyaleAPI/family-config#224]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: KING皇族公会
key: KING_hzgh
color: yellow
emblem: Star_Shine_03
info:
  logo: https://ibb.co/5Fc3V6q
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。本部落只招收：主堡12级、拥有至少20张12级和50张11级主流卡牌、均衡养卡的部落战玩家！在养成均衡牌库之前禁止成员养满级卡牌，理念不合请绕道而行！


  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: 800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING皇室精英
    tag: PL0V9PRV
  - name: Chivalry
    tag: 8JYCUCR8
```

**Comment by smlbiobot** [comment]
```yml
name: KING皇族公会
key: KING_hzgh
color: yellow
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/king_hzgh.jpg
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。本部落只招收：主堡12级、拥有至少20张12级和50张11级主流卡牌、均衡养卡的部落战玩家！在养成均衡牌库之前禁止成员养满级卡牌，理念不合请绕道而行！


  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: 800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING皇室精英
    tag: PL0V9PRV
  - name: Chivalry
    tag: 8JYCUCR8
```
