### ISSUE TITLE
Grown up Sweden

### ISSUE THREAD

**Issue by Dennann** [RoyaleAPI/family-config#225]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Grown up Sweden
key: GrownupSweden
color: blue
emblem: flag_d_03
info:
  logo: ![image](https://user-images.githubusercontent.com/64095599/80094610-d7172c80-8566-11ea-9dca-8a3ae71175f8.png)
  description: >
Grown up Sweden - Sveriges bästa klanfamilj! Vi består av tre olika klaner och du kan ansöka på Clash Royale eller Discord. Gå till discord.gg/vmmnCR7 eller klicka på Discord-loggan här nedanför.
  social:
    - discord: http://discord.gg/vmmnCR7
clans:
  - name: Grown up Sweden
    tag: L9YY8R
  - name: Grown up Swe 2
    tag: LPJ8PYJU
  - name: Grown up Swe 3
    tag: YRCYYY08
```
