### ISSUE TITLE
KING Royale Family

### ISSUE THREAD

**Issue by FrancescoQiu** [RoyaleAPI/family-config#226]
Hi, I'd like to make some correction to the imformation added yesterday, where there was a typo in the clan tag of one in our family.

```yml
name: KING皇族公会
key: KING_royale_family
color: yellow
emblem: Star_Shine_03
info:
  logo: https://ibb.co/5Fc3V6q
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。


  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: Y800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING皇室精英
    tag: PL0V9PRV
  - name: Chivalry
    tag: 8JYCUCR8

```

**Comment by smlbiobot** [comment]
What correction are you talking about? this is the first time I have seen your config created.

**Comment by FrancescoQiu** [comment]
> What correction are you talking about? this is the first time I have seen your config created.

The config was created yesterday by another co-leader in our clan (issue #224): https://github.com/RoyaleAPI/family-config/issues/224

Corrections: 
1. replace
`name: KING乱世王者
tag: 800CRQ0`
 with
`name: KING乱世王者
tag: Y800CRQ0`
2. I hope to shorten the description
`description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。`

thanks a lot :)

**Comment by smlbiobot** [comment]
ok well your KEYS are different. which key do  you want to use then?

your original config uses `KING_hzgh` and this one uses `KING_royale_family`:

```
name: KING皇族公会
key: KING_hzgh
color: yellow
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/king_hzgh.jpg
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。本部落只招收：主堡12级、拥有至少20张12级和50张11级主流卡牌、均衡养卡的部落战玩家！在养成均衡牌库之前禁止成员养满级卡牌，理念不合请绕道而行！


  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: 800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING皇室精英
    tag: PL0V9PRV
  - name: Chivalry
    tag: 8JYCUCR8
```

**Comment by smlbiobot** [comment]
I can update to use your current config but your URL will change.

**Comment by FrancescoQiu** [comment]
> ok well your KEYS are different. which key do you want to use then?
> 
> your original config uses `KING_hzgh` and this one uses `KING_royale_family`:
> 
> ```yaml
> name: KING皇族公会
> key: KING_hzgh
> color: yellow
> emblem: Star_Shine_03
> info:
>   logo: /static/img/brands/logo/king_hzgh.jpg
>   description: >
>     这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。本部落只招收：主堡12级、拥有至少20张12级和50张11级主流卡牌、均衡养卡的部落战玩家！在养成均衡牌库之前禁止成员养满级卡牌，理念不合请绕道而行！
> 
> 
>   social:
>     - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
> clans:
>   - name: KING乱世王者
>     tag: 800CRQ0
>   - name: KING皇战传奇
>     tag: Y2YV22UV
>   - name: KING皇室精英
>     tag: PL0V9PRV
>   - name: Chivalry
>     tag: 8JYCUCR8
> ```

the new one, `KING_royale_family`, thanks :)

**Comment by FrancescoQiu** [comment]
> I can update to use your current config but your URL will change.

OK, no problem.

**Comment by smlbiobot** [comment]
updated. if you want to edit config in the future, please use this:

```yml
name: KING皇族公会
key: king_royale_family
color: yellow
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/king_hzgh.jpg
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。
  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: Y800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING皇室精英
    tag: PL0V9PRV
  - name: Chivalry
    tag: 8JYCUCR8
```
