### ISSUE TITLE
The dark Empire 

### ISSUE THREAD

**Issue by TdEHundekuchen** [RoyaleAPI/family-config#227]
```yaml
name: The dark Empire
key: TdE
color: violet
emblem: Elixir_02
info:
 logo: https://cdn.discordapp.com/attachments/583639750347325449/698472022011019304/Esportslogo_The_dark_Empire_Esports_weier_Rand-1_2-Wiederhergestellt.png
  description: > 
       Herzlich willkommen bei der **The dark Empire Clanfamilie**!
       Wir sind eine deutsche Clanfamilie bestehend aus 7 Clash Royale Clans, zwei Brawl Stars Clubs, 
       sowie zwei erfolgreichen Esportsteams in den Bereichen Clash Royale und Brawl Stars.
       Was uns besonders auszeichnet sind unsere Aktivität, unsere Treue, sowie unsere 
       Professionalität. 
       Spaß am Spiel hat bei uns oberste Priorität, daher versorgen wir unsere Mitglieder regelmäßig 
       mit Angeboten in Form von Events und Turnieren.
       Auch Erfolge sind ein wichtiger Teil von uns, so sind wir immer gewollt 110% zu geben um den 
       nächsten Meilstenstein zu erreichen. 
    
  social:
    - twitter: http://twitter.com/TdEClanfamilie?s=09
    - discord: http://discord.gg/QRgz4zP
    - instagram: https://instagram.com/the_dark_empire_.clanfamilie?r=nametag
   
clans:
  - name: The dark knight
    tag: RPPQPOR
  - name: The dark guard 
    tag: PYCP8GQL
  - name: The dark path
    tag: Y9Q9RRYO
  - name: The dark viking
    tag: Y2P99UL8
  - name: The dark castle
    tag: PRRYOVCJ
  - name: The dark forest
    tag: LPPRVOVC
  - name: The dark lake
    tag: Y0UVYGRJ
```
