### ISSUE TITLE
Adding another clan and change some stuff

### ISSUE THREAD

**Issue by SUSHI-CR** [RoyaleAPI/family-config#228]
```yaml
name: S-Tier Family
key: S-Tier
color: Violet
emblem: Star_Shine_03

social:
 https://discord.gg/QbWkNpQ
clans:
  - name: S-Tier SG
    tag: PV8JQGY0
  - name: The Identity
    tag: Y022CCPV
  - name: S-Tier ACE
    tag: YQ8QCQQ9
```
