### ISSUE TITLE
SWEDEN BOYS Family Config

### ISSUE THREAD

**Issue by HuggeK** [RoyaleAPI/family-config#23]
```yaml
name: SWEDEN BOYS 
key: SB
color: blue
emblem: flag_j_03.png
info:
  description: >
**SWEDEN BOYS** är en klanfamilj i Sverige med klaner i top 10 & 50 skiktet. 
Klanfamiljen har funnits länge. 
Vi har en skön sammanhållning i & mellan klanerna och vi består av medlemmar i alla åldrar. 
Sweden boys 1 är lite mer för den mer aktiva och erfarna spelaren, både i doneringar och war-deltagande.
Sweden boys 2 är för aktiva spelare som inte satsar lika stenhårt som SB1. 
**Välkommen att gå med!**
  social:
    - website: http://swedenboys.home.blog
clans:
  - name: SWEDEN BOYS
    tag: 8LLQV00
  - name: SWEDEN BOYS 2
    tag: 929QQ2RC
  - name: SWEDEN BOYS 3
    tag: 908JVUCU
```

**Comment by HuggeK** [comment]
Sorry for posting under wrong category, I’m new to GitHub. Is is ok now?

**Comment by smlbiobot** [comment]
it’s fine — I have moved it

**Comment by smlbiobot** [comment]
- spacing

```yml
name: SWEDEN BOYS
key: SB
color: blue
emblem: flag_j_03.png
info:
  description: >
    **SWEDEN BOYS** är en klanfamilj i Sverige med klaner i top 10 & 50 skiktet.
    Klanfamiljen har funnits länge.
    Vi har en skön sammanhållning i & mellan klanerna och vi består av medlemmar i alla åldrar.
    Sweden boys 1 är lite mer för den mer aktiva och erfarna spelaren, både i doneringar och war-deltagande.
    Sweden boys 2 är för aktiva spelare som inte satsar lika stenhårt som SB1.
    **Välkommen att gå med!**
  social:
    - website: http://swedenboys.home.blog
clans:
  - name: SWEDEN BOYS
    tag: 8LLQV00
  - name: SWEDEN BOYS 2
    tag: 929QQ2RC
  - name: SWEDEN BOYS 3
    tag: 908JVUCU
```

**Comment by smlbiobot** [comment]
added

**Comment by HuggeK** [comment]
If I want to update a clans tag to a new one, where do I do that?

**Comment by smlbiobot** [comment]
post a new config here

**Comment by HuggeK** [comment]
name: SWEDEN BOYS
key: SB
color: blue
emblem: flag_j_03.png
info:
  description: >
    **SWEDEN BOYS** är en klanfamilj i Sverige med klaner i top 10 & 50 skiktet.
    Klanfamiljen har funnits länge.
    Vi har en skön sammanhållning i & mellan klanerna och vi består av medlemmar i alla åldrar.
    Sweden boys 1 är lite mer för den mer aktiva och erfarna spelaren, både i doneringar och war-deltagande.
    Sweden boys 2 är för aktiva spelare som inte satsar lika stenhårt som SB1.
    **Välkommen att gå med!**
  social:
    - website: http://swedenboys.home.blog
clans:
  - name: SWEDEN BOYS
    tag: 8LLQV00
  - name: SWEDEN BOYS 2
    tag: 929QQ2RC
  - name: SWEDEN BOYS 3
    tag: PYPQLGG9

**Comment by smlbiobot** [comment]
updated

**Comment by HuggeK** [comment]
```yaml
name: SWEDEN BOYS
key: SB
color: green
emblem: flag_j_03.png
info:
  description: >
  **SWEDEN BOYS** är en klanfamilj i Sverige med klaner i top 10 & 50 skiktet. Klanfamiljen har funnits länge. Vi har en skön sammanhållning i & mellan klanerna och vi består av medlemmar i alla åldrar & nivåer av sitt spelande. Sweden boys 1 är lite mer för den mer aktiva och erfarna spelaren, både i doneringar och war-deltagande. Sweden boys 2 är för aktiva spelare som inte satsar lika stenhårt som SB1. Sweden Boys 3 är för mindre aktiva spelare som vill ha mindre krav. (Läs beskrivningen av klanerna för krav) **Ta & kolla in vår hemsida!** Där du bl.a. hittar SB-bladet (klanfamiljens nyhetsbrev) & inbjudan till vår fina Discordserver för medlemmar. **Välkommen att gå med!**
  social:
    - website: http://swedenboys.home.blog
    - discord: https://discordapp.com/invite/Fa3bX42
clans:
  - name: SWEDEN BOYS
    tag: 8LLQV00
  - name: SWEDEN BOYS 2
    tag: 929QQ2RC
  - name: SWEDEN BOYS 3
    tag: PYPQLGG9
  - name: SWEDEN BOYS 4
   tag: #PQ8LLCGP
```
