### ISSUE TITLE
[Update] Team Liquid EU Issue #61

### ISSUE THREAD

**Issue by FullFrontage** [RoyaleAPI/family-config#230]
```yml
name: Team Liquid EU
key: liquideu
color: blue
emblem: flag_d_04
info:
  logo: https://drive.google.com/file/d/1zu8TGP3caDZPqO-ud4caeL5iybpExIUe/view?usp=sharing
  description: >
    *Join us in [discord](https://tl.gg/mobile) for an active environment, tournaments, events, and more!*


    With **more than 40 top clans across the globe**, Team Liquid has established itself as one of the most prominent clan families in Clash Royale. Our broad approach to the game allows all kinds of players to enjoy our activities; even Brawl Stars, Critical Ops and other game's fans have a spot in our community! **#LetsGoLiquid**
  social:
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - discord: https://tl.gg/mobile
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - instagram: https://www.instagram.com/teamliquid/
    - facebook: https://www.facebook.com/teamliquid/
    - twitter: https://twitter.com/TeamLiquid
clans:
  - name: TeamLiquid FR
    tag: 98PYR0VJ
  - name: TL Solid
    tag: P888QQQ9
  - name: TeamLiquid RO
    tag: 9JUCLVCV
  - name: TeamLiquid HE
    tag: P2V0PQPQ
  - name: TeamLiquid HE 2
    tag: 9VJQQP0J
  - name: TeamLiquid HE 3
    tag: 9ULCQQ9R
  - name: TeamLiquid HU
    tag: P09YPG9V
  - name: TeamLiquid HU 2
     tag: Y8C8828G
  - name: TeamLiquid BL
    tag: P0YJ0P2V
  - name: Team Liquid ITA
    tag: 9QRU02GR
  - name: Team Liquid IT2
    tag: 9U82UYLJ
  - name: Team Liquid IT3
    tag: P0P2G8YQ
  - name: Team Liquid IT4
    tag: 9JJJP229
 - name: Team Liquid FIN 
    tag: Y2CVV80P
```
