### ISSUE TITLE
Update Gavetas Gaming Family

### ISSUE THREAD

**Issue by FelixTheWoof** [RoyaleAPI/family-config#234]
name: Gavetas Universe
key: gavetasgaming
color: red
emblem: A_Char_Goblin_02
info:
 logo: //imgur.com/gallery/pT6Iz2X
  description: 
Entre outros jogos, o Gavetas Gaming é uma comunidade portuguesa de Clash Royale. 
Somos casa de jogadores competitivos e amadores. Temos as nossas próprias Ligas, 
competições, e criamos torneios a nível Nacional. Temos um lugar para ti, num ambiente
positivo e amigável. Vem jogar connosco! 

  social:
    - twitter: https://twitter.com/GavetaseSports
    - discord: https://discordapp.com/invite/9NuCTn4
    - instagram: https://www.instagram.com/gavetasesports/
    - facebook: https://www.facebook.com/GavetasGamingWorld/
    - email: gavetas.info@gmail.com
clans:
  - name: Gavetas Team
    tag: 2QG8V2C9
  - name: Gavetas Romeo
    tag: L8JGY8YC
  - name: Gavetas Delta
    tag: 8VLRRC28
  - name: Gavetas Golf
    tag: 9CL90JVJ
  - name: Gavetas Hotel
    tag: 9LU2Y8LU
  - name: Gavetas Echo
    tag: 9C9VCRUQ
  - name: Gavetas India
    tag: 9CGQ29LR
  - name: Gavetas Whiskey
    tag: PJV8900L
  - name: Gavetas Papa
    tag: LP20RYLV
  - name: Gavetas X-Ray
    tag: P8JYVYGJ
  - name: Gavetas Quebec
    tag: PQQURYYP
  - name: Gavetas Mike
    tag: Y0RC9CRJ

**Comment by smlbiobot** [comment]
```yml
name: Gavetas Universe
key: gavetasgaming
color: red
emblem: A_Char_Goblin_02
info:
  logo: /static/img/brands/logo/gavetas.png
  description: >
    Entre outros jogos, o Gavetas Gaming é uma comunidade portuguesa de Clash Royale.
    Somos casa de jogadores competitivos e amadores. Temos as nossas próprias Ligas,
    competições, e criamos torneios a nível Nacional. Temos um lugar para ti, num ambiente
    positivo e amigável. Vem jogar connosco!

  social:
    - twitter: https://twitter.com/GavetaseSports
    - discord: https://discordapp.com/invite/9NuCTn4
    - instagram: https://www.instagram.com/gavetasesports/
    - facebook: https://www.facebook.com/GavetasGamingWorld/
    - email: mailto:gavetas.info@gmail.com
clans:
  - name: Gavetas Team
    tag: 2QG8V2C9
  - name: Gavetas Romeo
    tag: L8JGY8YC
  - name: Gavetas Delta
    tag: 8VLRRC28
  - name: Gavetas Golf
    tag: 9CL90JVJ
  - name: Gavetas Hotel
    tag: 9LU2Y8LU
  - name: Gavetas Echo
    tag: 9C9VCRUQ
  - name: Gavetas India
    tag: 9CGQ29LR
  - name: Gavetas Whiskey
    tag: PJV8900L
  - name: Gavetas Papa
    tag: LP20RYLV
  - name: Gavetas X-Ray
    tag: P8JYVYGJ
  - name: Gavetas Quebec
    tag: PQQURYYP
  - name: Gavetas Mike
    tag: Y0RC9CRJ
```
