### ISSUE TITLE
Add Städfirman Family

### ISSUE THREAD

**Issue by Stadfirman** [RoyaleAPI/family-config#236]
name: TEAM Städfirman ™️
key: Städfirman
color: black
emblem: Flame_03.png
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    Firman för dig med höga ambitioner 🔥 Top 1 in Sweden.  
clans:
  - name: Städfirman
    tag: #2p8cog
  - name: Städfirman 2
    tag: #P0JGJUGL
  - name: Städfirman 3
    tag: #Y0GJP2YL

**Comment by Stadfirman** [comment]
Remove the "TM" I you guys doesn´t able to put that emoji after "Team Städfirman"

**Comment by Stadfirman** [comment]
Thanks in advance / Team Städfirman

**Comment by smlbiobot** [comment]
please note all the mistakes which had been corrected. edit this if you want to update in the future:

```yml
name: TEAM Städfirman ™️
key: stadfirman
color: black
emblem: Flame_03
info:
  description: >
    Firman för dig med höga ambitioner 🔥 Top 1 in Sweden.
clans:
  - name: Städfirman
    tag: 2P8COG
  - name: Städfirman 2
    tag: P0JGJUGL
  - name: Städfirman 3
    tag: Y0GJP2YL

```
