### ISSUE TITLE
Family clan request: 圣鹿家族

### ISSUE THREAD

**Issue by 709894332** [RoyaleAPI/family-config#238]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 圣鹿家族
key: 圣鹿
color: purple
emblem: Cherry_Blossom_01
info:
  logo: https://github.com/709894332/-/blob/master/yg.png
  description: >
    欢迎加入圣鹿family，旗下设有圣鹿野格、圣鹿旺仔和圣鹿与海三个部落，“朝而往，暮而归，四时之景不同，而乐亦无穷也。”加首领微信mao930627联系我们!

clans:
  - name: 圣鹿野格
    tag: Y2UR89
  - name: 圣鹿旺仔
    tag: LYV2VJGG
  - name: 圣鹿与海
    tag:YJV9VJJY
```

**Comment by smlbiobot** [comment]
We don’t support chinese characters as keys. Here’s your new config:

```yml
name: 圣鹿家族
key: sheng-lu
color: purple
emblem: Cherry_Blossom_01
info:
  logo: /static/img/brands/logo/sheng-lu.png
  description: >
    欢迎加入圣鹿family，旗下设有圣鹿野格、圣鹿旺仔和圣鹿与海三个部落，“朝而往，暮而归，四时之景不同，而乐亦无穷也。”加首领微信mao930627联系我们!

clans:
  - name: 圣鹿野格
    tag: Y2UR89
  - name: 圣鹿旺仔
    tag: LYV2VJGG
  - name: 圣鹿与海
    tag: YJV9VJJY
```

and it is now visible at https://royaleapi.com/f/sheng-lu
