### ISSUE TITLE
TheBoganFamily

### ISSUE THREAD

**Issue by k3lv1n90** [RoyaleAPI/family-config#244]
```yaml
name: The Bogan Family
key: theboganfamily
color: yellow
emblem: Moon_03
info: 
  logo: https://i.imgur.com/MfJnkfj.png
  description: >
    **The Bogan Family** is currently home to 4 eminent clans; **Auckland Bogans, Baby Bogans,** 
    **Majestic Beast and Crystal Flames.**
    Here, there is an opportunity prevailing for every player to learn and grow along side 
    many other avid players. 
    Take part in various inter-clan tournaments hosted by us, get detailed coaching from our top
    players and take your skills to another level by joining our eSports team, **Bogan eSports!**
    Whether you're a casual player, competitive player or anything in-between, 
    there's a space for you in The Bogan Family!
  social:
    - twitter: https://twitter.com/BoganEsports
    - discord: http://discord.gg/23ehpkJ
    - youtube: https://www.youtube.com/channel/UCKNRaWUf-rNC36Luww4NtIg
    - email: mailto:boganesports@gmail.com
clans:
  - name: Auckland bogans
    tag: 28Y99Y
  - name: majestic Beast
    tag: CL8J0
  - name: Crystal Flames
    tag: YLJ220JG
  - name: Baby Bogans
    tag: PJJ9J2C8
```
