### ISSUE TITLE
Update Banana Warriors Fam

### ISSUE THREAD

**Issue by DaDa101** [RoyaleAPI/family-config#245]
Hello, thanks in advance for update. And sorry for any mistakes in formating. Iam a little bit limited with my cellphone.

```yaml
name: Banana Warriors 
key: bw 
color: yellow 
emblem: Skull_01 
sort: trophy 
info: 
  logo: https://bananenclan.de/wp-content/uploads/2018/06/banana_warriors192x150.png 
  description: > Die *Banana Warriors* bestehen aus 7 Clans. In den ClanWars sind wir mittlerweile nicht mehr unter Gold III unterwegs. Kontinuität zahlt sich eben aus. Unter uns befinden sich auch einige erfolgreiche Turnier-Spieler und nicht zuletzt Streamer, die in ClashRoyal aktiv sind. Bei unseren Mitgliedern legen wir wert auf Aktivität im ClanWar, Freundlichkeit im Umgang mit Anderen, sowie Spass im und am Spiel. 
  social: 
    - discord: https://discord.me/bananawarriors 
    - twitch: https://www.twitch.tv/neonvimes 
    - youtube: https://www.youtube.com/channel/UCfflejvqiFHxyRjPk1aMHoQ 
    - website: http://bananawarriors.de/ 
clans: 
  - name: Platin Bananen 
    tag: 8GUPGYVY 
  - name: Radium Bananen 
    tag: 8Q8JRPQV 
  - name: Neon Bananen 
    tag: 8PRPP00J 
  - name: Chrom Bananen 
    tag: 8CLJQPR0 
  - name: Cyan Bananen 
    tag: YP2URPRY
```
