### ISSUE TITLE
Add a league family

### ISSUE THREAD

**Issue by sgi779** [RoyaleAPI/family-config#247]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:A League family
key:alf
color:black
emblem:flame_03
info:  logo:https://www.instagram.com/p/CAh9Tm-HWyk/?utm_source=ig_web_copy_link
  description: We allows only PRO's and play war is must also we have to go long lasting
  social:
    - instagram: https://instagram.com/@jurassic_crclan
    - email: mailto:iamfromclankingsgi@gmail.com
clans:
  - name:『JURASSIC™』
    tag: LRVL9CJR
```
