### ISSUE TITLE
create apple leagends

### ISSUE THREAD

**Issue by sgi779** [RoyaleAPI/family-config#248]
```yaml
name:  ApPlEs legend
key:aplep
color:red
emblem: Flame_03
info: 
sort: trophy
  logo:
  description: >
 We are playing clash Royale for creating best community.we lives to eat apple but we love more clash Royale. We needed pro for have long lasting like plastic.
  social:
   
    
  
    - reddit: https://www.reddit.com/user/Sgi7792ndid/
    - youtube: https://www.youtube.com/account
    - instagram: https://www.instagram.com/applefamclash/
    - youtube: https://www.youtube.com/account
    - email: mailto: minigamersgi11@gmail.com
clans:
  - name: 『JURASSIC™』
    tag: LRVL9CJR
```
