### ISSUE TITLE
Create quickly the apple family

### ISSUE THREAD

**Issue by sgi779** [RoyaleAPI/family-config#249]
ADD THIS FAMILY QUICKLY I WAS GIVE TOO MANY ISSUES FROM MAY 26 AND CLOSED THAT. SORRY BUT IT IS LAST
```yaml
name:  APPLE legends
key:  apl
color:  black
emblem: flame_03
info: 
sort: trophy
  logo: https://www.instagram.com/p/CAruLxBnaMa/?utm_source=ig_web_copy_link
  description: >
We are the legends we loves iOS. We also like to eat the apple. We also loves e-sports frequent torneys. Play and win promotion.  We have needed only PRO's if you pro then join.
  social:
    - reddit: https://www.reddit.com/user/Sgi7792ndid/
    - youtube: https://www.youtube.com/account
    - instagram: https://www.instagram.com/applefamclash/
    - email: mailto: minigamersgi11@gmail.com
clans:
  - name: 『JURASSIC™』
    tag: LRVL9CJR
```
