### ISSUE TITLE
Add the apple legends

### ISSUE THREAD

**Issue by sgi779** [RoyaleAPI/family-config#250]
I am  known that I have given too many attempts . I am sorry for that I have closed that because of some mistakes in config. It is last.
```yaml
name: APPLE LEGENDS
key: apple
color: red
emblem: flame_03
info: 
sort: trophy
  logo: https://www.instagram.com/p/CAruLxBnaMa/?utm_source=ig_web_copy_link.png
  description: >
pro players are our crush.  join us to be pro.we likes esports so we host tournament regularly.we likes iOS. and also to eat apple.  we are not partial to any one . so all are can join.so get it out now. play Jurassic.play better.play partial.play party.
  social:
    - reddit: https://www.reddit.com/user/Sgi7792ndid/
    - youtube: https://www.youtube.com/channel/UCzuvhbKbj1qU7Bb8OyVvCYg
    - instagram: https://www.instagram.com/applefamclash/
    - youtube: https://www.youtube.com/channel/UCzuvhbKbj1qU7Bb8OyVvCYg
    - email: mailto: iamfromclankingsgi@gmail.com
clans:
  - name: 『JURASSIC™』
    tag: LRVL9CJR
  - name:
    tag:
  - name:
    tag:
```
