### ISSUE TITLE
Add clan family apple legends

### ISSUE THREAD

**Issue by sgi779** [RoyaleAPI/family-config#251]
Now I have given two but it is not random you can verify us.sorry for giving invalid last time.plzz create it as fast as you can.ok.thx in advance.

```yaml
name: APPLE FAMILY
key: aple
color: red
emblem: Flame_03
info: 
sort: trophy
  logo: https://www.instagram.com/p/CAscQNsHPzy/?utm_source=ig_web_copy_link .png
  description: > 
pro players are our crush.  join us to be pro.we likes esports so we host tournament regularly.we likes iOS. and also to eat apple.  we are not partial to any one . so all are can join.so get it out now. play Jurassic.play better.
  social:
    - discord: https://discord.gg/2qrBwMk
    - reddit: https://www.reddit.com/user/Sgi7792ndid/
    - youtube: https://www.youtube.com/channel/UCzuvhbKbj1qU7Bb8OyVvCYg
    - instagram: https://www.instagram.com/applefamclash/
    - youtube: https://www.youtube.com/channel/UCzuvhbKbj1qU7Bb8OyVvCYg
    - email: mailto: minigamersgi11@gmail.com
clans:
  - name: 『JURASSIC™』
    tag: LRVL9CJR
  - name: Apple LEGENDS.
    tag: Y8LCQR9Y 
```
