### ISSUE TITLE
Mage Knights Family 

### ISSUE THREAD

**Issue by luckyleopard664** [RoyaleAPI/family-config#252]
```yaml
name: Mage Knights
key: mageknights
color: violet
emblem: Knight_01
info:
  logo: https://user-images.githubusercontent.com/66153116/83319251-c499ae00-a20a-11ea-8be4-c3f9a1541d96.png
  description: >
    The **Mage Knights** are a family of clans which is primarily war-focused.  We value the entire card collection, not just your ladder deck, but our family accepts players of all skill and card levels.
    We also value practice and constructive criticism; there is always room for improvement.
    _Mage Knights’ main clan is currently top 100 in U.S. clan war rankings._


  social:
    - discord: http://discord.gg/33vr58D
    - youtube: https://www.youtube.com/channel/UC1R-b1AET3-eLGQNed6TYzA
clans:
  - name: Mage Knights
    tag: 2V28Y88Q
  - name: Mage Knights 2
    tag: YR00L2LY
  - name: Mage Knights 3
    tag: YLRJ8LUP
```
