### ISSUE TITLE
Epic Family NZ

### ISSUE THREAD

**Issue by nelly-jay** [RoyaleAPI/family-config#254]
```yaml
name: -Epic- Clan Family
key: -epic-
color: black
emblem: Skull_03
sort: trophy
info:
description: >
Epic is family of 4 clans in New Zealand but with members
from around the world.  We all share a passion for the game,
we’re a friendly bunch with a happy vibe. The Epic way is
about both casual and competitive playing styles
and we value both. Show us what you got.
clans:
 - name: -Epic-
   tag: LGGVV
 - name: -Epic- Thunder
   tag: 2U0QJLQR 
 - name: -Epic- Bootcamp
   tag: P8UJG9L 
 - name: -Epic- Empire
   tag: Y0Q9VLYC  
```

**Comment by smlbiobot** [comment]
Can’t begin family key with hypens:

```yml
name: -Epic- Clan Family
key: epic
color: black
emblem: Skull_03
sort: trophy
info:
  description: >
    Epic is family of 4 clans in New Zealand but with members
    from around the world.  We all share a passion for the game,
    we’re a friendly bunch with a happy vibe. The Epic way is
    about both casual and competitive playing styles
    and we value both. Show us what you got.
clans:
- name: -Epic-
  tag: LGGVV
- name: -Epic- Thunder
  tag: 2U0QJLQR
- name: -Epic- Bootcamp
  tag: P8UJG9L
- name: -Epic- Empire
  tag: Y0Q9VLYC
```
