### ISSUE TITLE
InvictumGG Family

### ISSUE THREAD

**Issue by ClydexGG** [RoyaleAPI/family-config#262]
```yaml
name: InvictumGG Family
key: invictumgg
color: blue
emblem: A_Char_King_02
info:
  logo: /static/img/team/logo/invictumgg.png
  description: >
    𝐈𝐧𝐯𝐢𝐜𝐭𝐮𝐦𝐆𝐆 is a multi-regional professional esports team based in Lithuania that was founded in 2016.
  social:
    - twitter: https://twitter.com/InvictumCR
    - discord: https://discord.gg/8dtcaJC
clans:
  - name: InvictumGG
    tag: YJL0QUUQ
  - name: InvictumGG Mini
    tag: Y9V22CPR
```
