### ISSUE TITLE
The Hot Box Family

### ISSUE THREAD

**Issue by KeeganAM** [RoyaleAPI/family-config#263]
```yaml
name: The Hot Box Family
key: hotbox
color: red
emblem: Lotus_02
info:
  logo: https://postimg.cc/mcckDnV0
  description: >
    **The Hot Box Family** is a chill tight-knit group of active, semi-competitive players always 
    looking to improve our game and have a fun time doing so. While US-based, we have members 
    from all over the world. Come and rise with us!
  social:
    - discord: http://discord.gg/uv4QT3E
    - twitch: https://twitch.tv/Lobsman
    - twitch: https://twitch.tv/Cedricttv
    - twitch: https://twitch.tv/dubiesdojo
    - twitch: https://twitch.tv/Insanity
clans:
  - name: The Hot Box
    tag: YJQ8R0QJ
  - name: The Ice Box
    tag: Y89Y0V8U
```
