### ISSUE TITLE
OKS Family of Clans Update

### ISSUE THREAD

**Issue by oksd2k** [RoyaleAPI/family-config#265]
```YAML
name: OKS Family of Clans YT
key: oks
color: green
emblem: pine_03
info:
  logo: https://photos.app.goo.gl/uoX3i3NuSLKL4dZx9
  description: >
    **OKS Family of Clans YT** prides itself in providing a positive, fun, and competitive environment for players of all levels of experience and activity. Monthly gift card prize tournaments, weekly YT videos showcasing our players stats and replays. Founded in June 2018 and looking to grow into 2020!

   
  social:
    - instagram: https://instagram.com/oksfamilyofclans?igshid=19y4g51fpbnmr
    - twitter: http://twitter.com/oksfamilyclans
    - discord: https://discord.gg/x77EaTq
    - OmletArcade: https://omlet.gg/profile/oksd2k
    - youtube: https://www.youtube.com/channel/508D2K
    
    - application: https://url/
    - email: mailto: dmartinho24@gmail.com
clans:
  - name: Kush Squad
    tag: 9G2LYURV
  - name: Kush2TheLimit
    tag: PQ989RC8
  - name: KushIsMyCologne
    tag: PL9V2RJQ
  - name: Clash4Kush
    tag: PRVYVCG8
  - name: 5-0!HideTheKush
    tag: YLUULLOY
  - name: OKS 6 God
    tag: YRYJYYOP
  - name: 24/7 Kush
    tag: PRY92VJY
  - name: OKS 8-Ball Kush
    tag: PCPPUCR8
  - name: OKS Cloud 9
    tag: LGYYRR88
  - name: OKSFamofClansYT
    tag: YRUOQJ99
 ```
