### ISSUE TITLE
changing the clan name

### ISSUE THREAD

**Issue by salmonfitswellwithsushi** [RoyaleAPI/family-config#266]
```yaml
name:The Identity
key: Identity
color: Violet
emblem: Star_Shine_03

clans:
  - name: The identity
    tag: Y022CCPV
- name:S-Tier ACE
    tag:YQ8QCQQ9
```
