### ISSUE TITLE
Megalendários

### ISSUE THREAD

**Issue by MinoCosmik** [RoyaleAPI/family-config#267]
```yaml
name: Família Megalendários
key: mega
color: purple
emblem: flag_n_06
info:
  logo: http://prnt.sc/t3zq6z
  description: >
    ✨RESSURGINDO DAS CINZAS✨A UNIÃO ACIMA DE TUDO ✨ SÓ OS DE VERDADE✨ JUNTOS SOMOS MAIS FORTES ✨.
  social:
    - youtube: https://www.youtube.com/channel/UC9IPSzQ1ZSYXEkpm5c6LcJw
    - discord: https://discord.gg/zm86tD3
    - facebook: https://www.facebook.com/rafael.perdames/
    - application: https://api.whatsapp.com/send?1=pt_BR&phone=+5521991621993
    - application: https://api.whatsapp.com/send?1=pt_BR&phone=+5511951788012
    - website: https://omlet.gg/profile/rf_destruction/
clans:
  - name: megalendários
    tag: 9GUJYGUC
  - name: Megalendários 2
    tag: Y99YLC8Q
  - name: Megalendários 3
    tag: YUVJ0RVU
  - name: Megalendários 4
    tag: Y8LCP8UY
  - name: Megalendários 5
    tag: LV20Y0GG
```

**Comment by smlbiobot** [comment]
```yml
name: Família Megalendários
key: mega
color: purple
emblem: flag_n_06
info:
  logo: /static/img/brands/logo/mega.png
  description: >
    ✨RESSURGINDO DAS CINZAS✨A UNIÃO ACIMA DE TUDO ✨ SÓ OS DE VERDADE✨ JUNTOS SOMOS MAIS FORTES ✨.
  social:
    - youtube: https://www.youtube.com/channel/UC9IPSzQ1ZSYXEkpm5c6LcJw
    - discord: https://discord.gg/zm86tD3
    - facebook: https://www.facebook.com/rafael.perdames/
    - application: https://api.whatsapp.com/send?1=pt_BR&phone=+5521991621993
    - application: https://api.whatsapp.com/send?1=pt_BR&phone=+5511951788012
    - website: https://omlet.gg/profile/rf_destruction/
clans:
  - name: megalendários
    tag: 9GUJYGUC
  - name: Megalendários 2
    tag: Y99YLC8Q
  - name: Megalendários 3
    tag: YUVJ0RVU
  - name: Megalendários 4
    tag: Y8LCP8UY
  - name: Megalendários 5
    tag: LV20Y0GG
```
