### ISSUE TITLE
VRau / Real Society

### ISSUE THREAD

**Issue by MinoCosmik** [RoyaleAPI/family-config#268]
```yaml
name: Real Society
key: vrau
color: purple
emblem: Skull_01
info:
  logo: https://cdn.royaleapi.com/static/img/badge/legendary/Skull_01.png
  description: >
    Somos um grupo de Clash Royale com foco em guerra e push, com jogadores de nível competitivo e amadores. Temos as nossas próprias regras, sistema organizacional e eventos. Temos um lugar para ti, em um ambiente positivo e amigável. Venha fazer parte deste time!
  social:
    - discord: https://discord.gg/DJEh7pS
clans:
  - name: Vraau Team
    tag: LU2VR2PV
  - name: PSICOPATAS ON
    tag: YCUUG8L9
```
