### ISSUE TITLE
Cosmos Family

### ISSUE THREAD

**Issue by MasterWill10** [RoyaleAPI/family-config#269]
```yaml
name: Cosmos Family
key: cosmos
color: purple
emblem: Star_Shine_03
sort: trophy
info: 
  logo: https://cdn.discordapp.com/avatars/471737037888815104/c8f31f57fd8a7b43b7b2582f6f2e3681.png?size=1024
  description: > 
The **Cosmos Family** is an established mobile gaming org that strives to form a unique community where players of all types feel welcome. Founded in August of 2019, we have worked hard to overcome many challenges, while maintaining a strong community. With over 20 clubs in Brawl Stars, Clash Royale, and Clash of Clans, along with multiple eSports teams in BS and CR, we have greatly exceeded our initial expectations. Join us on our journey to the top!

**#ExploreTheCosmos**
  social:
    - twitter: http://twitter.com/Cosmos_Family
    - discord: http://discord.gg/JN53wGs
    - twitch: https://www.twitch.tv/cosmosfamilygg
    - youtube: https://www.youtube.com/channel/UCGwy4BxETs3xlGO-c9NKi5g
    - website: https://sites.google.com/view/cosmosfamily/home
    - email: mailto:thecosmosfamily105@gmail.com
clans:
  - name: UnderMiners
    tag: 2UV822J0
  - name: 4N eSports
    tag: 9G8GGYUC
  - name: Miner League
    tag: PCP8PCLP
  - name: 4N eSports 2
    tag: LUPV9L82
  - name: Demon Stone
    tag: LUPUQY2Q
  - name: CF Zetro
    tag: Y9G0R0LL
```
