### ISSUE TITLE
LA Academy 

### ISSUE THREAD

**Issue by UDC3000** [RoyaleAPI/family-config#270]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:LA Academy 
key:laacademy
color:black
emblem: Flame_03
info:
  logo:

![](https://media.discordapp.net/attachments/713977759768248320/714690964051984394/image0.png)

  description: >
       LA FC-  LA Fight Club 

Purpose is to bring a place where our esports players can practice, have competitive events, and fun.  We will be partnering with CR clans and Esports teams and sponsors to provide a friendly place to grow as a player and as a person.

We have channels for teams to find scrimmages and for teams and esports staff to find each other.

Players with activity can place their twitter tags, and outside communities can sponsor prize tourneys as well.

Coaching- will have some sections for decks and will develop a private 1on1 program- planned for the future 

Social- it will be a friendly place to play and chat about the games

Streamers will be welcomed to help stream events.

Applications are accepted for staff positions. 




       social:
    - twitter: https://twitter.com/laesportsop
    - discord: http://discord.gg/d78zNRm
    - website: http://legendaryalliancegaming.com/
clans:
  - name: Suffolk’N’Good
    tag: PULJGUYJ 
  - name: Superfolk’NGood
    tag: L9OV8RY9
  - name:
    tag:
```
