### ISSUE TITLE
Soloman (MenShen) Clan Family request

### ISSUE THREAD

**Issue by yiji21** [RoyaleAPI/family-config#271]
```yaml
name: Soloman (MenShen) Clan Family
key: soloman
color: blue
emblem: Clover_01
info:
  logo:
  description: >
   The Soloman (MenShen) Clan Family is for the fan clans for professional CN CR player Soloman (MenShen). The first clan (门神的小朋友们) was established on Jan 14th, 2020 and the second (门神的甜蜜之家) was created on Mar 18th, 2020. 


   Please come and support Soloman's Live Steaming at Huya (see link in social->website)!
  social:
    - twitter: https://twitter.com/edgm_soloman
    - website: https://www.huya.com/240862
    - email: mailto: yiji21@gmail.com
clans:
  - name: 门神的小朋友们
    tag: L8PQJC8J
  - name: 门神的甜蜜之家
    tag: Y0UJQVGQ
```
