### ISSUE TITLE
Adding Nova UK to Royale API

### ISSUE THREAD

**Issue by Ahek** [RoyaleAPI/family-config#272]
```yaml
name: Nova UK
key: novauk
color: Purple
emblem: Star_Shine_03
info:
  logo: https://cdn.discordapp.com/attachments/691625325116784671/723538917244010766/nova_uk_clash_royale.png
  description: 
    The Nova UK clans are an official branch of Nova eSports, but an independent family. 
    Come join one of our clans!


    - discord: https://discord.gg/hWC7vxq
clans:
  - name: Nova | UK
    tag: 2JVJRYP
  - name: Nova UK 2
    tag: RY89JRY
  - name: Nova UK 3
    tag: PJYUC0CU
  - name: Nova UK 4
    tag: PVUG0GUP
```

**Comment by smlbiobot** [comment]
```yml
name: Nova UK
key: novauk
color: Purple
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/nova_uk_clash_royale.png
  description:
    The Nova UK clans are an official branch of Nova eSports, but an independent family.
    Come join one of our clans!

  social:
    - discord: https://discord.gg/hWC7vxq
clans:
  - name: Nova | UK
    tag: 2JVJRYP
  - name: Nova UK 2
    tag: RY89JRY
  - name: Nova UK 3
    tag: PJYUC0CU
  - name: Nova UK 4
    tag: PVUG0GUP
```
