### ISSUE TITLE
Black Aves 

### ISSUE THREAD

**Issue by juljoh** [RoyaleAPI/family-config#274]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Black Aves
key: blackaves
color: black
sort: trophy
emblem: flag_j_03
info: 
   logo: 
![6C0CFFF6-D54F-418A-A136-64D34BC2D203](https://user-images.githubusercontent.com/67442430/85829104-2c9bcf80-b78a-11ea-9987-a087ec98a865.jpeg)
   description: >
Die im September 2018 gegründete Black Aves Familie umfasst 6 Clans in fast jeder CW Liga - von Bronze bis Legendäre Liga ist alles dabei. Ob Anfänger im Einsteigerclan oder Profi im Top 200 Clan - bei uns findet jeder den Platz, der zu ihm passt. 
  social:
    - discord: http://discord.me/blackaves

clans:
  - name: Schwarzer Rabe
    tag: P0V0RP9G
  - name: Schwarze Eule
    tag: P2V8PYC2
  - name: Schwarzer Star
    tag: Y2QGL0GP
  - name: Schwarzer Falke
    tag: PJ8G20JJ
  - name: Schwarzer Adler
    tag: Y0P8LYVJ
  - name: Schwarzer Ara
    tag: YUQJP2PP
```
