### ISSUE TITLE
Apollo Legion

### ISSUE THREAD

**Issue by SoonYZ** [RoyaleAPI/family-config#275]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Apollo Empire
key: apollo legion
color: red
emblem: Crown_01
info: 
  logo:
  description: >
    Talent wins games, but teamwork and intelligence win championships. We are a newly established family that not only value
    talent, but also the mentality and morals to back it up.

  social:
    - email: mailto:apollolegionfamily@gmail.com

clans:
  - name: Apollo Legion
    tag:Y8PCLVCO
  - name: Apollo Legion 2 
    tag:Y9G982Q8
  - name: Apollo Legion 3
    tag:YJP2LVY8
  - name: Apollo Legion 4
    tag:YYR0JP9V
  - name: Apollo Legion 5
    tag:LCYUOOY9
```
