### ISSUE TITLE
Cosmos Family: Adding 2 new clans and resubmitting logo

### ISSUE THREAD

**Issue by MasterWill10** [RoyaleAPI/family-config#276]
```yaml
  logo: https://i.imgur.com/IK5kE5x.png?1

clans:
  - name: S-Tier SG
    tag: PV8JQGYO
  - name: Royale Vets
    tag: PLQ22C9P
```
