### ISSUE TITLE
KING Royale Family: Adding a new member and deleting an abolished one

### ISSUE THREAD

**Issue by FrancescoQiu** [RoyaleAPI/family-config#277]
Hello, I'd like to add a new member clan to our family, as well as delete an old one, which is abolished now. The config already exists and the following is my new edit.

```yaml
name: KING皇族公会
key: king_royale_family
color: yellow
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/king_hzgh.jpg
  description: >
    这里是「KING皇族」公会！公会官方Q群：816151043，公会理念：均衡养卡，全面发展。
  social:
    - website: https://jq.qq.com/?_wv=1027&k=5pS0OoS
clans:
  - name: KING乱世王者
    tag: Y800CRQ0
  - name: KING皇战传奇
    tag: Y2YV22UV
  - name: KING别无所球
    tag: YYCVVYVP
  - name: KING皇室精英
    tag: PL0V9PRV
  
```
