### ISSUE TITLE
Family ! Forteresse

### ISSUE THREAD

**Issue by ToiToines** [RoyaleAPI/family-config#278]
name  ! Forteresse
key: forteresse
color: violet
emblem: Sword_01 
info: 
  description:> Crée en décembre 2018, ! Forteresse ! est un clan adulte axé GDC. Il est désormais composé de 5 clans qui partagent les mêmes valeurs : esprit d'équipe et bonne humeur. Notre but ? La conquête du monde :)
  social:
    - discord: https://discord.gg/XVUD6k
clans:
  - name :! Forteresse !
    tag: PQ9GRCLR
  - name : ! Forteresse 2
    tag: P8QJR928
  - name: ! Forteresse 3
    tag: PLU8CR9Y 
  - name: ! Forteresse 4
    tag: Y09J88YP
  - name: !Forteresse 5
    tag: PGULJLQP

**Comment by smlbiobot** [comment]
```yml
name: "! Forteresse"
key: forteresse
color: violet
emblem: Sword_01
info:
  description: >
    Crée en décembre 2018, ! Forteresse ! est un clan adulte axé GDC. Il est désormais composé de 5 clans qui partagent les mêmes valeurs : esprit d'équipe et bonne humeur. Notre but ? La conquête du monde :)
  social:
    - discord: https://discord.gg/XVUD6k
clans:
  - name: "! Forteresse !"
    tag: PQ9GRCLR
  - name: "! Forteresse 2"
    tag: P8QJR928
  - name: "! Forteresse 3"
    tag: PLU8CR9Y
  - name: "! Forteresse 4"
    tag: Y09J88YP
  - name: "! Forteresse 5"
    tag: PGULJLQP
```
