### ISSUE TITLE
Synergy Family

### ISSUE THREAD

**Issue by RealAres1** [RoyaleAPI/family-config#279]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Synergy Clan Family
key: synergy
color: blue
emblem: Bamboo_04
info:
  logo: https://cdn.discordapp.com/attachments/443181493074919424/458778900969947137/Screenshot_2018-06-19-12-14-41-1.png
  description: >
    The Synergy clan Family is a group of competitive war, and ladder clans. The Synergy Family offers ladder rewards, cash tournaments, Pass Royale giveaways and a fun experience. In the Synergy Family we offer an experience like no other clan, as well as a discord with top/skilled players to talk to and take notes from. We hope to see you soon. Laugh, Learn, Compete!
  social:
    - twitter: https://twitter.com/CrSynergy
    - discord: https://discord.gg/kET4HTs
    - website: https://synergy-gaming.now.sh
    - facebook: https://www.facebook.com/synergygamingcr/
clans:
  - name: Synergy
    tag: 809R8PG8
  - name: Synergy Union
    tag: 8VVGG08G
  - name: Synergy Wrath
    tag: 9UG8LG0U
  - name: Synergy Reborn
    tag: 9LYPC809
  - name: Synergy Rising
    tag: P9UY2Y0U
  - name: Synergy Fusion
    tag: 8URQ0UR8
```
