### ISSUE TITLE
AlmasDeFuego Family

### ISSUE THREAD

**Issue by Campaner2001** [RoyaleAPI/family-config#28]
```yaml
name: AlmasDeFuego Family
key: Almas
color: red
emblem: Flame_01
info:
  description: >
We are an Spanish clan created three years ago. We have reached the top 150 in the Spanish rank in ladder and we have more than 5000 war trophies. We speak mostly Spanish, but we accept people from all over the world. Join us to improve together and become a well known player. We had people that gone to RoyaleConQueso, Nova and other famous clans after being with us. Join us and keep growing, and at the same time, have fun. 

Somos un clan español creado hace tres años. Hemos llegado a estar top 150 en el top local. Hablamos español pero también aceptamos a jugadores de cualquier lugar del mundo. Hemos tenido a jugadores que luego de estar con nosotras, han sido contactados por clanes famosos como RoyaleConQueso o Nova. Únete y sigue creciendo, para llegar a ser un jugador conocido. 
    
clans:
  - name: AlmasDeFuego
    tag: GGU8QY
  - name: Almasdefuego2
    tag: P2YU8U2 

```

**Comment by smlbiobot** [comment]
- note spacing

```yml
name: AlmasDeFuego Family
key: Almas
color: red
emblem: Flame_01
info:
  description: >
    We are an Spanish clan created three years ago. We have reached the top 150 in the Spanish rank in ladder and we have more than 5000 war trophies. We speak mostly Spanish, but we accept people from all over the world. Join us to improve together and become a well known player. We had people that gone to RoyaleConQueso, Nova and other famous clans after being with us. Join us and keep growing, and at the same time, have fun.

    Somos un clan español creado hace tres años. Hemos llegado a estar top 150 en el top local. Hablamos español pero también aceptamos a jugadores de cualquier lugar del mundo. Hemos tenido a jugadores que luego de estar con nosotras, han sido contactados por clanes famosos como RoyaleConQueso o Nova. Únete y sigue creciendo, para llegar a ser un jugador conocido.

clans:
  - name: AlmasDeFuego
    tag: GGU8QY
  - name: Almasdefuego2
    tag: P2YU8U2
```
