### ISSUE TITLE
welopenmetloot

### ISSUE THREAD

**Issue by Sebastiaan2002** [RoyaleAPI/family-config#280]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Welopenmetloot Clan Family
key: Welopenmetloot
color: red
emblem: A_Char_Goblin_02
info:
  logo:
  description: >The **Welopenmetloot Family**  is Home to professional players and casual players that al love the game.
We are al driven to be the best! The Welopenmetloot family is a casual but competitive family. We are thriving to be the best family in clash royale.
join us now in one of our clans and help us reach the top!!! 


 
clans:
  - name: welopenmetloop
    tag: YJ08JJ98
  - name:
    tag:
  - name:
    tag:
```
