### ISSUE TITLE
(Edits needed please!) Duck Alliance: New clan family

### ISSUE THREAD

**Issue by duckside** [RoyaleAPI/family-config#282]
```yaml
name: Duck Alliance
key: duckalliance
color: orange
emblem: A_Char_DarkPrince_04
info:
  logo: https://cdn.discordapp.com/attachments/678397493695741962/691342738062442526/Photo_1584899306066.png
  description: >
    Welcome to the dark side. Our values are friendship first, and asserting dominance second. We war seriously, and have an accomplished esports team. Join us today! (you can apply through our discord server 🌈)
  social:
    - discord: http://discord.gg/GgdfcAx
clans:
  - name: The Duckside
    tag: L00VVV2P
  - name: The Ducknight
    tag: YUJ9GQJV
  - name: The Duckclutch
    tag: L2YG0R80
  - name: The Ducksdream
    tag: YYLV0LCL
```
