### ISSUE TITLE
SG Munchking

### ISSUE THREAD

**Issue by getsomehelp** [RoyaleAPI/family-config#283]
```yaml
name: SG Munchking
key: sgmunchking
color: red
emblem: Diamond_02
info:
  logo: https://royaleapi.com/static/img/badge/legendary/Diamond_02.png
  description: >
    Established in 2016, **SG Munchking** is a proud Singaporean clan comprising passionate clashers who are active in war and on ladder. **SG Munchkins** is our sub clan created for players who just set off for the game or players taking a break. As our main clan is 'Invite Only', feel free to join us by simply hitting that request option! Welcome to our family and enjoy your stay!
  social:
clans:
  - name: SG Munchking
    tag: 8Y9P8992
  - name: SG Munchkins
    tag: 2992U0J
```
