### ISSUE TITLE
Vermont Liberty

### ISSUE THREAD

**Issue by MDKaron** [RoyaleAPI/family-config#286]
```yaml
name: Vermont Liberty
key:
color: green
emblem: Pine_01
info:
  logo:
  description: >


    Our casual clan is currently looking to grow new members and graduate them into our successful low-pressure war clan.
clans:
  - name: Vermont Liberty
    tag: RGULG0
  - name: Vermont Liberty
    tag: L0QLC89V
```
