### ISSUE TITLE
[Family Update] Kasalla

### ISSUE THREAD

**Issue by lemonixxx** [RoyaleAPI/family-config#29]
Update: 

- description of Family, please in german as it is 
- added Clan "GermanClasher" (9U2PQQ0G)
- added Clan "Welle Tsunami" (LVC8RL)

- delete Clan "i.9 eSports" (80ULQRLU )
- update instagram
- update logo

```yaml
name: Kasalla
key: kasalla
color: red
emblem: A_Char_Hammer_02
info:
  logo: https://ibb.co/mzHLSRN
  description: >
**Kasalla** ist eine der größten deutschsprachigen Clash Royale Clan Familien.
Wir haben eine eigene eSport Liga, die **RDKL**, sowie ein eigens eSport Team bei dem sich auch neue Mitglieder immer beweisen können!
Durch unsere Sponsoren ist es uns erlaubt regelmäßige Turniere mit Preisgeldern zu veranstalten.
Außerdem besitzen wir einen gut organisierten Discord Server(1600+ Mitglieder), mit eigenen Chaträumen für eSport, Turniere, Streaming usw. rund um Clash Royale.   
Aufgrund unserer vielen Clans ist Jeder Spieler bei uns willkommen und gut aufgehoben. 
Was willst du mehr? JOIN NOW!


  social:
    - discord: http://discord.me/crkasalla
    - instagram: https://www.instagram.com/kasallafamily
    - twitter: https://twitter.com/discordleague?lang=de

clans:
  - name: Kasalla
    tag: 9YQ9V0UQ
  - name: Kasalla Casual
    tag: P2CPLL8R
  - name: provocatione™
    tag: 9Y8YVJYP
  - name: Welle Tsunami
    tag: LVC8RL
  - name: Kasalla Swarm
    tag: 9JR0PJV2
  - name: BerlinciTy
    tag: 2R880VJV
  - name: GermanClasher
    tag: 9U2PQQ0G
  - name: Kasalla War
    tag: P0Q220PY
  - name: Kasalla Deluxe
    tag: 9CVCRP9L 
  - name: Kasalla Gala™
    tag: 9R99Y29L
```
