### ISSUE TITLE
UNT Gaming Family

### ISSUE THREAD

**Issue by Luca180405** [RoyaleAPI/family-config#290]
```yaml
name: UNG Gaming Family
key: untgaming
color: red
emblem: Flame_03
info:
  logo: https://imgur.com/a/R9vzIVZ
  description: >
    Welcome to UNT Gaming. We are an active Clanfamily with loyal and helpful members.
    Ladder Rewards. Contact us via instagram: cr_kayz or join ur discord.
  social:
    - instagram: https://www.instagram.com/cr_kayz/
    - discord: https://discord.gg/zBRfgSG
clans:
  - name: UNT Gaming
    tag: YLQQPPJC
  - name: UNT Gaming 2
    tag: LUY8QOCR
```
