### ISSUE TITLE
Welopenmetloot

### ISSUE THREAD

**Issue by Sebastiaan2002** [RoyaleAPI/family-config#291]
```yaml
name: Welopenmetloot Clan Family
key: Welopenmetloot
color: red
emblem: A_Char_Goblin_02
info:
  logo:
  description: >The **Welopenmetloot Family**  is Home to professional players and casual players that al love the game.
We are al driven to be the best! The Welopenmetloot family is a casual but competitive family. We are thriving to be the best family in clash royale.
join us now in one of our clans and help us reach the top!!! 

   


   
clans:
  - name: welopenmetloop
    tag: YJ08JJ98
  - name: welopenmetloot2
    tag: YY02JJLL
  - name:
    tag:
```
