### ISSUE TITLE
TGB Royale Family request 

### ISSUE THREAD

**Issue by Alsyapal** [RoyaleAPI/family-config#295]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml

name: TGB Royale
key: tgb
color: blue
emblem: A_Char_Hammer_02
info:
  logo: https://imgur.com/a/2ZsJvcL
  description: >
 TGB Royale clan family - Proud member 𝐭𝐞𝐚𝐦𝐑𝐃𝐘𝐊.com - A vibrant Supercell gaming community. Home of top 10 UK clan and UK league qualifiers ! Team GB !. Highly active, competitive clans for players who want to achieve something! Regular tournaments and scrims vs other top clans. 
  social:
    - discord: https://discord.gg/kG3GqZr
    
clans:
  - name: ! Team GB !
    tag: RCUR20
  - name: ! Team GB 2 !
    tag: LUPCV82J
  - name: Adult League
    tag: LGV28JU9

```

**Comment by smlbiobot** [comment]
```yml
name: TGB Royale
key: tgb
color: blue
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/tgb.png
  description: >
    TGB Royale clan family - Proud member 𝐭𝐞𝐚𝐦𝐑𝐃𝐘𝐊.com - A vibrant Supercell gaming community. Home of top 10 UK clan and UK league qualifiers ! Team GB !. Highly active, competitive clans for players who want to achieve something! Regular tournaments and scrims vs other top clans.
  social:
    - discord: https://discord.gg/kG3GqZr

clans:
  - name: "! Team GB !"
    tag: RCUR20
  - name: "! Team GB 2 !"
    tag: LUPCV82J
  - name: Adult League
    tag: LGV28JU9
```
