### ISSUE TITLE
Tim Time Team

### ISSUE THREAD

**Issue by doongmiin** [RoyaleAPI/family-config#296]
```yaml
name: Tim Time Team
key: itstimewithtim
color: red
emblem: A_Char_King_02
info: These are the clans in our Tim Time Team
  logo: https://imgur.com/a/nGIbrAc
  description: >
    Restoring the honor of your Family (and your cow) one match at a time.

This is the __clan family__ of **itstimewithTim**, namely: __**Tim Time Team**__!

Instructions about how to join any of our clans is available on our Discord Server.

Discord.gg/nfRJsph or follow the link below.


  social:
    - discord: http://discord.gg/nfRJsph
    - twitter: https://twitter.com/itstimewithtim
    - twitch: https://www.twitch.tv/itstimewithtim
    - youtube: https://www.youtube.com/channel/
    - email: mailto: itstimewithtim@gmail.com

clans:
  - name: ttv timewithTim
    tag: L2VCLRCY
  - name: Tim Time Team
    tag: YPVPQY29
```
