### ISSUE TITLE
Tricoldianxs

### ISSUE THREAD

**Issue by Juanin1892** [RoyaleAPI/family-config#297]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Tricoldianxs
key: Tricol
color: red
emblem: crown_01
info: 
  logo: 
![6bf6fbd7-1c6a-4294-b543-2fad6e76f37b](https://user-images.githubusercontent.com/69168296/89224317-478e0a80-d5a6-11ea-8080-b8283b8037e2.png)

  description: >
    Comunidad originaria de Chile en busca de los mejores jugadores hispanohablantes


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/Tricoldianxs?s=09
    - discord: https://discord.gg/RKJVcj
    - youtube: https://www.youtube.com/channel/UCRizBt_w0O7UoKl-qtg_PQA
    - instagram: https://instagram.com/tricoldianxs?igshid=15a2nlyza7plk
    - email: contacto.tricoldianxs@gmail.com
clans:
  - name: Tricoldianos
    tag: 8CLYVVQV
  - name: Tricoldiablxs
    tag: PLJ00L92
  - name: Tricoldianxs
    tag: LQ0C0PUQ
```
