### ISSUE TITLE
✴☆MST Academy☆✴

### ISSUE THREAD

**Issue by YosoyJove** [RoyaleAPI/family-config#298]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: ✴☆MST Academy☆✴
color: amarillo
emblem:
info:
  logo:
  description: > 🔺Pass Royale al 1ro y 2do en Guerras🔺Torneos🔺Equipo Competitivo 🔺Gpo de WhatsApp 🔺 Discord 🔺Liga Propia🔺 Prioridad GUERRA
Trophies
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/MST__Academy?s=09[https://twitter.com/MST__Academy?s=09](https://link.clashroyale.com/invite/clan/es?tag=Y88GY8CQ&token=r7bd2rks&platform=android) 
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: ✴☆MST Academy☆✴
    tag: #Y88GY8CQ
  - name:
    tag:
  - name:
    tag:
```
[https://twitter.com/MST__Academy?s=09]()
