### ISSUE TITLE
Undefined - Update

### ISSUE THREAD

**Issue by C00ls0ul** [RoyaleAPI/family-config#299]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: https://media.discordapp.net/attachments/296493772383191040/741071441331748904/Undefined_Logo.png
  description: >
    🌟🌟🌟Active, Loyal, & Respectful🌟🌟🌟<br/>

    ⭐Clan Family⭐Ladder Rewards⭐Esports Team⭐<br/>

    ⭐discord.gg/X55XZHD⭐twitch.tv/zachcr_⭐<br/>

    🌠4#1<br/>
  social:
    - discord: https://discord.gg/X55XZHD
    - twitch: https://www.twitch.tv/zachcr_
    - twitter: https://twitter.com/Undefined_CR
    - youtube: https://youtube.com/channel%2FUCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: 9RU2V2U9
  - name: Redefined
    tag: 9JJVUUUL
  - name: Predefined
    tag: 9VVLL09G
  - name: Misdefined
    tag: L28G2UV0
```
