### ISSUE TITLE
False logic clan family update

### ISSUE THREAD

**Issue by rox4lyfe** [RoyaleAPI/family-config#3]
```yaml
name: False Logic
key: false_logic
color: blue
emblem: Lotus_01
info:
  logo: 
  description: >
     Welcome to the **False Logic** Clan Family! We're a bunch of friendly, active people that 
     constantly chat and battle. Our players are always willing to assist you throughout all our clans, 
     ranging from tips to just socializing. We're all on a discord that houses over 300 of us, so there's an 
     easy way for all our members to communicate.
  social:
    - discord: https://discord.gg/8FAzF4U
    - reddit: https://reddit.com/message/compose/?to=mandrewjackson
clans:
  - name: False Logic
    tag: JVQJRV0
  - name: False Logic II
    tag: 20PYJVJQ
  - name: False Logic III
    tag: 2Y9RGYU2
  - name: False Logic IV
    tag: 2VYUQ0PU
  - name: False Logic V
    tag: 2CVRP2YQ
  - name: False Logic VI
    tag: 89C0JUQ0
  - name: False Logic VII
    tag: P2VQ9LYR
  - name: False Logic X
    tag: P0VVJ0U9
  - name: False Logic Farm
    tag: PY89J9GY
```
