### ISSUE TITLE
TheSupremeTeam

### ISSUE THREAD

**Issue by shivalsookay** [RoyaleAPI/family-config#30]
```yaml
name: TheSupremeTeam Family
key: supremeteam
color: blue
emblem: Sword_01
info:
  logo: https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/badges/Sword_01.png
  description: >
    Welcome to TheSupremeTeam Family! We are a family friendly community
    spread throughout Clash Royale and Brawl Stars. Hope to have you!
  social:
    - discord: https://discord.royaleapi.com
clans:
  - name: TheSupremeTeam
    tag: P9VUUPRV
  - name: SupremeTeam #2
    tag: P89C0VY0
  - name: ChildrenOfTime
    tag: 2U28QL0Q
```
