### ISSUE TITLE
Apply for Clan family

### ISSUE THREAD

**Issue by jesperfang** [RoyaleAPI/family-config#300]
name: 我愛瑪莉小羊家族
key: lms
color: Blue
emblem: Lotus_01.png
info:
  logo:
  description: >
    歡迎加入我愛瑪莉小羊大家庭
    我們共有15個部落，其中零部保持本地前三
    我們會不定期舉辦網聚聯絡感情
    我們會不定期舉辦聯歡比賽
    我們有各種套路高手
    我們有不定期牌庫健檢
    更重要的是有大Line群可聊天
    詳情可加入line群(jas1123gmail)
  social:
clans:
  - name: 我愛瑪莉小羊
    tag: 8YLLRCU
  - name: 我愛瑪莉小羊二部
    tag: 2GUCU9JR
  - name: 我愛瑪莉小羊皮-愛瑪仕柏金包
    tag: 2UL8J8RP
  - name: 我愛瑪莉小羊-琉璃仙境
    tag: 2ULR9GC8
  - name: 我愛瑪莉小羊 - 零
    tag: 8JPCJU0R
  - name: 我愛瑪莉小羊 - 小寶軍團
    tag: 90P22UPY
  - name: 我愛瑪莉小羊-餅乾好好吃
    tag: 90QPR9G0
  - name: 我愛瑪莉小羊-與神同行
    tag: 9C0Q2QQQ
  - name: 我愛瑪莉小羊 · 得閒飲茶
    tag: P09YCG9Y
  - name: 我愛瑪莉小羊 · 得閒奶茶
    tag: PQQR9YUG
  - name: 我愛瑪莉小羊 · 得閒抹茶
    tag: YQ28Q9RC
  - name: 我愛瑪莉小羊·婚逃賣暖蛋
    tag: YJUYYPV0
  - name: Black Hole 黑洞
    tag: 9VYGUCLL
  - name: 台灣啤酒
    tag: RJ8QVP
  - name: 台灣啤酒
    tag: 9G2QPP8
  - name: 台灣啤酒 CLASSIC!!
    tag: 9RU8RGG

**Comment by smlbiobot** [comment]
```yml
name: 我愛瑪莉小羊家族
key: lms
color: blue
emblem: Lotus_01
info:
  description: >
    歡迎加入我愛瑪莉小羊大家庭<br/>
    我們共有15個部落，其中零部保持本地前三<br/>
    我們會不定期舉辦網聚聯絡感情<br/>
    我們會不定期舉辦聯歡比賽<br/>
    我們有各種套路高手<br/>
    我們有不定期牌庫健檢<br/>
    更重要的是有大Line群可聊天<br/>
    詳情可加入line群(jas1123gmail)<br/>
clans:
  - name: 我愛瑪莉小羊
    tag: 8YLLRCU
  - name: 我愛瑪莉小羊二部
    tag: 2GUCU9JR
  - name: 我愛瑪莉小羊皮-愛瑪仕柏金包
    tag: 2UL8J8RP
  - name: 我愛瑪莉小羊-琉璃仙境
    tag: 2ULR9GC8
  - name: 我愛瑪莉小羊 - 零
    tag: 8JPCJU0R
  - name: 我愛瑪莉小羊 - 小寶軍團
    tag: 90P22UPY
  - name: 我愛瑪莉小羊-餅乾好好吃
    tag: 90QPR9G0
  - name: 我愛瑪莉小羊-與神同行
    tag: 9C0Q2QQQ
  - name: 我愛瑪莉小羊 · 得閒飲茶
    tag: P09YCG9Y
  - name: 我愛瑪莉小羊 · 得閒奶茶
    tag: PQQR9YUG
  - name: 我愛瑪莉小羊 · 得閒抹茶
    tag: YQ28Q9RC
  - name: 我愛瑪莉小羊·婚逃賣暖蛋
    tag: YJUYYPV0
  - name: Black Hole 黑洞
    tag: 9VYGUCLL
  - name: 台灣啤酒
    tag: RJ8QVP
  - name: 台灣啤酒
    tag: 9G2QPP8
  - name: 台灣啤酒 CLASSIC!!
    tag: 9RU8RGG
```
