### ISSUE TITLE
Bergclan Familie - first listing of clan family

### ISSUE THREAD

**Issue by TutEnAmum** [RoyaleAPI/family-config#302]
```yaml
name: Bergclan Familie
key: BERGCLANS
color: blue
emblem: Fugi_02
info:
  logo: https://cdn.discordapp.com/attachments/647029292634603521/648187855960670239/Bergclans-1.png
  description: >
    Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community mit Spielern 
    aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während einer Alpenüberquerung 
    von Freunden aus den drei Ländern, geht es uns um Gaming, Zusammenhalt und Spaß in einer 
    starken Community, über nationale, soziale, Alters- und alle übrigen Grenzen und Barrieren 
    hinweg. Wir haben 12 Clash Royale Clans, jeder mit eigenem Schwerpunkt: vom extrem 
    erfolgreichen Warclan für anspruchsvolle Fanatiker, über erfolgreichen, aber entpannten Warclan, 
    oder absolut Community-orientierten Clan, oder für Familien, oder junge Spieler, oder senior Gamer, 
    ..., bis zu den 4 aufeinander abgestimmten Ausbildungsclans (für Starter bis midlevel Player). 
    Neben Events wie Turnieren (Turnierpartnerschaft mit aktuell ca. 60 Clans, ab und an mit Prämien) 
    und einer familieninternen Liga bieten wir 2 Brawl Stars Clubs (Royal Fortress, top 100 BRD, 
    und Royal Fortress2) und einen Clash Of Clans Club (die Bergdrachen), sowie andere Games auf 
    auf Nachfrage in Subcommunities. Bei uns findet ihr eure passende Community. Und es tut sich 
    immer was; wir bleiben nicht stehen. Schaut mal auf unserem Discord Server vorbei. 
    Wir freuen uns auf euch, eure **Bergclans**.
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berglöwen
    tag: PPYYPUPU
  - name: Bergsee
    tag: PPYYPUPU
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
    ```

**Comment by TutEnAmum** [comment]
Thank you very much in advance to the team of royale api.

**Comment by smlbiobot** [comment]
```yml
name: Bergclan Familie
key: bergclans
color: blue
emblem: Fugi_02
info:
  logo: /static/img/brands/logo/bergclans.png
  description: >
    Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community mit Spielern
    aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während einer Alpenüberquerung
    von Freunden aus den drei Ländern, geht es uns um Gaming, Zusammenhalt und Spaß in einer
    starken Community, über nationale, soziale, Alters- und alle übrigen Grenzen und Barrieren
    hinweg. Wir haben 12 Clash Royale Clans, jeder mit eigenem Schwerpunkt: vom extrem
    erfolgreichen Warclan für anspruchsvolle Fanatiker, über erfolgreichen, aber entpannten Warclan,
    oder absolut Community-orientierten Clan, oder für Familien, oder junge Spieler, oder senior Gamer,
    ..., bis zu den 4 aufeinander abgestimmten Ausbildungsclans (für Starter bis midlevel Player).
    Neben Events wie Turnieren (Turnierpartnerschaft mit aktuell ca. 60 Clans, ab und an mit Prämien)
    und einer familieninternen Liga bieten wir 2 Brawl Stars Clubs (Royal Fortress, top 100 BRD,
    und Royal Fortress2) und einen Clash Of Clans Club (die Bergdrachen), sowie andere Games auf
    auf Nachfrage in Subcommunities. Bei uns findet ihr eure passende Community. Und es tut sich
    immer was; wir bleiben nicht stehen. Schaut mal auf unserem Discord Server vorbei.
    Wir freuen uns auf euch, eure **Bergclans**.
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berglöwen
    tag: PPYYPUPU
  - name: Bergsee
    tag: PPYYPUPU
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
```
