### ISSUE TITLE
The Reckoning Clan Family

### ISSUE THREAD

**Issue by ThreeReckoning** [RoyaleAPI/family-config#308]
```yaml
name: The Reckoning Clan Family
key: thereckoning
color: purple
emblem: Skull_05
info:
  description: >
    **The Reckoning** clan family is a small cluster of clans. We have a solid base of donations and wars and advanced players who see no problem in helping new ones.

clans:
  - name: The Reckoning
    tag: PUGJJ8UR
  - name: reckoning 2.0
    tag: YYJVY09Q
  - name: The Reckoning 3.0
    tag: YY9LG9YP
```
