### ISSUE TITLE
[Update] TheSupremeTeam Family

### ISSUE THREAD

**Issue by gray-sama** [RoyaleAPI/family-config#309]
```yaml
name: TheSupremeTeam
key: ST
color: black
emblem: Skull_05
info:
  logo: https://imgur.com/xDcPBoQ
  description: > 
**TheSupremeTeam** is a Discord server centred around 3 mobile games developed by Supercell: __Clash Royale, Brawl Stars and Clash of Clans!__ We offer a variety of features that we're sure you'll enjoy, including Clash Royale clans, Brawl Stars clubs, entertaining bots such as Dank Memer and Pokécord and in-game and Discord events!
  social:
    - discord: https://discord.gg/a7Htru4
clans:
  - name: TheSupremeTeam
    tag: P9VUUPRV
  - name: ST Inception
    tag: LVQUQ2PQ
  - name: SupremeTeam #2
    tag: P89C0VY0
```
