### ISSUE TITLE
Bergclan Familie - full exchange of family config

### ISSUE THREAD

**Issue by TutEnAmum** [RoyaleAPI/family-config#311]
```yaml
name: Bergclan Familie
key: BERGCLANS
color: blue
emblem: Fugi_02
emblem: Sword_02
info:
  logo: https://cdn.discordapp.com/attachments/647029292634603521/648187855960670239/Bergclans-1.png
  description: >
    Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community mit Spielern 
    aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während einer Alpenüberquerung 
    von Freunden aus den drei Ländern, geht es uns um Gaming, Spaß und Vernetzung in einer 
    starken Community, über nationale, soziale, Alters- und alle übrigen Grenzen und Barrieren 
    hinweg. Wir uns kontinuierlich verbessern: als Spieler in den Games, und das Angebot
    für unsere Player. 

    Wir bieten **14 Clash Royale Clans**, jeder mit eigenem Schwerpunkt: vom erfolgreichen Warclan für 
    anspruchsvolle und ladderorientierte Spieler, über erfolgreichen, aber entspannten Warclan, 
    absolut Community-orientierten Clan, für Familien, junge Spieler, senior Gamer und Familienurgesteine,
    mit Fokus auf ein Land, ... bis zu den aufeinander abgestimmten Ausbildungsclans (für Starter bis midlevel Player). 

    Auf unserem professionellem **Discord Server** findet ihr alles zu den Games und könnt euch vernetzen. In unserer gut 
    strukturierten **CR Waffenkammer** findet ihr bspw. die aktuellsten Metadecks (aktive Links zur Übernahme der 
    Decks in die CR App) nebst Tutorials, diverse Guides zu den Themen Profi Ladder, Pulling + Kiten, Cyceln, 
    und zu Decktypen wie Hog 2.6, X-Bow, Logbait, Golem, Graveyard, Bridgespam Royal Giant oder PEKKA Ram, ...
  
    Neben **eSports Events** wie Turnieren, ab und an mit Prämien, und einer CR Liga analog der CRL bieten wir 
    **2 Brawl Stars Clubs** (Royal Fortress, top 100 BRD,  und Royal Fortress2) und einen **Clash Of Clans Club** 
    (die Bergdrachen), sowie andere Games auf Nachfrage in Subcommunities. Bei uns findet ihr eure 
    passende Ecke. Und es tut sich immer was bei uns. Schaut mal auf unserem Discord Server vorbei, 
    es lohnt sich.

    Kontakt: gern, via Discord oder Line (tut-en-amum).
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Berglöwen
    tag: Y8JU0CPU
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergsee
    tag: PPYYPUPU
  - name: Bergziegen
    tag: L8V8GQ0C
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Bergliga
    tag: LVLURC0V
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
    ```

**Comment by smlbiobot** [comment]
I see what you are doing here but you can’t rename your clans this way. we will always return what is in-game and so if we use english names here it will be very confusing because it’d be different on the menu vs your actual names

**Comment by smlbiobot** [comment]
so this must stay as is:

```yml
name: Bergclan Familie
key: bergclans
color: blue
emblem: Fugi_02
info:
  logo: /static/img/brands/logo/bergclans.png
  description: >
    Welcome to the **Bergclan Family**, a gaming community with players
    from Germany, Austria and Switzerland. Founded in 2017 while
    friends from the three countries were crossing the Alps , we're all about gaming, fun and networking in one
    strong community, across national, social, age and all other borders and barriers
    . We are continuously improving: as a player in the games, and the offer
    for our players.


    We offer **14 Clash Royale clans**, each with its own focus: the successful Warclan for
    sophisticated and ladder oriented players on successful, but relaxed Warclan,
    completely community-oriented communities, for families, young players, senior gamers and family stalwarts,
    with Focus on one country ... up to the coordinated training clans (for starters to mid-level players).


    You can find everything about the games and network on our professional **Discord Server**. In our well-
    structured ** CR Armory ** you will find, for example, the latest meta decks (active links for transferring the
    decks to the CR app) along with tutorials, various guides on the topics of professional ladder, pulling + kiting, cycling,
    and deck types such as Hog 2.6, X-Bow, Logbait, Golem, Graveyard, Bridgespam Royal Giant or PEKKA Ram, ...


    In addition to **eSports events** such as tournaments, now and then with bonuses and a CR league analogous to the CRL, we offer
    **2 Brawl Stars Clubs** (Royal Fortress, top 100 BRD, and Royal Fortress2) and a **Clash Of Clans Club** (the mountain dragons),
    as well as other games on request in subcommunities. With us you will find the
    right corner. And there is always something going on with us. Take a look at our Discord server,
    it's worth it.

    Contact: gladly, via Discord or Line (tut-en-amum).
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berglöwen
    tag: Y8JU0CPU
  - name: Bergsee
    tag: PPYYPUPU
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
```

**Comment by TutEnAmum** [comment]
Good morning.

Sry, I don't quite understand the issues.

(1)
In the last description, there were several writing mistakes. So we agreed that I should send a complete new family config and ask for an complete exchange, as this would bei easier for you than looking for and exchanging single words. So I did.

(2) 
And we don't want an english description. We want our German one (as several other German - Austrian - Swiss clans / clan families already have here).

(3) 
In the script we didn't use names for the clans that differ from ingame names (?). We are growing, so we added two new clans and changed the clan order. I just checked clan names and tags. You can check them here:

https://clashroyaleforum.de/thread/7282-bergclan-familie-17-clans-clubs-clash-royale-ck-1-0-top-182-events-und-preisgeld/

(4) 
Your yaml "this must stay as is": we never sent you an english description. And the description as well as the clan list is outdated now.

So I'd prefer that you simply exchange the whole config yaml as sent by me, and everything should be fine.

Thanks you in advance.

Please let me know if there are any more issues.

**Comment by TutEnAmum** [comment]
Don't get me wrong, we really appreciate your work. But I just followed your suggestion in what I did, on my last attempt to update the config via complete exchange.

**Comment by smlbiobot** [comment]
hey so… I think what happened is that weirdly my browser changed your config to english and so I got very confused. I will update np.

**Comment by smlbiobot** [comment]
This is the final config I use.

- logo must be transformed to our notation
- I’ve removed one of your emblems (you had two)

```yml
name: Bergclan Familie
key: bergclans
color: blue
emblem: Fugi_02
info:
  logo: /static/img/brands/logo/bergclans.png
  description: >
    Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community mit Spielern
    aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während einer Alpenüberquerung
    von Freunden aus den drei Ländern, geht es uns um Gaming, Spaß und Vernetzung in einer
    starken Community, über nationale, soziale, Alters- und alle übrigen Grenzen und Barrieren
    hinweg. Wir uns kontinuierlich verbessern: als Spieler in den Games, und das Angebot
    für unsere Player.


    Wir bieten **14 Clash Royale Clans**, jeder mit eigenem Schwerpunkt: vom erfolgreichen Warclan für
    anspruchsvolle und ladderorientierte Spieler, über erfolgreichen, aber entspannten Warclan,
    absolut Community-orientierten Clan, für Familien, junge Spieler, senior Gamer und Familienurgesteine,
    mit Fokus auf ein Land, ... bis zu den aufeinander abgestimmten Ausbildungsclans (für Starter bis midlevel Player).


    Auf unserem professionellem **Discord Server** findet ihr alles zu den Games und könnt euch vernetzen. In unserer gut
    strukturierten **CR Waffenkammer** findet ihr bspw. die aktuellsten Metadecks (aktive Links zur Übernahme der
    Decks in die CR App) nebst Tutorials, diverse Guides zu den Themen Profi Ladder, Pulling + Kiten, Cyceln,
    und zu Decktypen wie Hog 2.6, X-Bow, Logbait, Golem, Graveyard, Bridgespam Royal Giant oder PEKKA Ram, ...


    Neben **eSports Events** wie Turnieren, ab und an mit Prämien, und einer CR Liga analog der CRL bieten wir
    **2 Brawl Stars Clubs** (Royal Fortress, top 100 BRD,  und Royal Fortress2) und einen **Clash Of Clans Club**
    (die Bergdrachen), sowie andere Games auf Nachfrage in Subcommunities. Bei uns findet ihr eure
    passende Ecke. Und es tut sich immer was bei uns. Schaut mal auf unserem Discord Server vorbei,
    es lohnt sich.


    Kontakt: gern, via Discord oder Line (tut-en-amum).
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Berglöwen
    tag: Y8JU0CPU
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergsee
    tag: PPYYPUPU
  - name: Bergziegen
    tag: L8V8GQ0C
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Bergliga
    tag: LVLURC0V
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
```
