### ISSUE TITLE
Pika! eSports

### ISSUE THREAD

**Issue by isc-jvillegas** [RoyaleAPI/family-config#312]
```yaml
name: Pika! eSports
key: Pk!
color: Yellow
emblem: Bolt_03
info: 
  logo: https://cdn.discordapp.com/attachments/748378368830996600/755805539262529623/logoPika_2020_v2.png
  description: >
    **Equipo Ladder y Competitivo.**
Somos un clan Mexicano que comenzó el 22 de Mayo del 2019 con la meta de llegar a ser top nacional.
Actualmente participamos en ligas y torneos amateurs para podernos dar a conocer y en un futuro llegar a tener un equipo
altamente competitivo. Contamos con Diseñadores, Staff y Entrenadores.
Si quieres formar parte de nuestro clan búscanos en nuestras redes sociales y contáctanos.
  social:
    - twitter: https://twitter.com/Pika_eSports
    - discord: https://discord.gg/nxHJDzk
    - facebook: https://www.facebook.com/PikaeSports
    - email: mailto: pktab3rna@gmail.com
clans:
  - name: Pika! eSports
    tag: Y2YV2C00 
  - name: Pika2! eSports
    tag: YY2LR0U2 

```
