### ISSUE TITLE
Clan inclusion request

### ISSUE THREAD

**Issue by Acidgirlcode** [RoyaleAPI/family-config#314]
```yaml
name: Familia Guerrilheiros
key: guerrilheiros
color: black
emblem: Skull_01.png
sort: trophy
info:
  logo: https://uploaddeimagens.com.br/imagens/Q-LoKxU
  description: >
    **Familia Guerrilheiros** é uma equipe da comunidade competindo no Brasil. fundado em 2016.
    
    O clã é um lugar para todos, especialmente para jogadores ativos, competitivos. 
    Todos nós compartilhamos uma paixão pelo jogo, somos amigáveis,
    sempre doamos e ajudamos uns aos outros com um objetivo comum em mente: melhorar nossas habilidades e nos divertir! 
    
    Junte-se à nos Guerrilheiro. Aproveite o jogo! =D
  social:
    - discord: https://discord.gg/p8qzy4J
    - website: https://clashroyale.com/pt/
    - youtube: https://www.youtube.com/clashroyale
    - instagram: https://www.instagram.com/ClashRoyale/
    - twitter: https://twitter.com/ClashRoyale
    - facebook: https://www.facebook.com/ClashRoyale

clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
```
