### ISSUE TITLE
CR小隊: Add 3rd clan to the existing two-clan family. Thanks!

### ISSUE THREAD

**Issue by crlittleteam** [RoyaleAPI/family-config#315]
```yaml
name: CR小隊
key: crlittleteam
color: purple
emblem: Crown_03
info: 
  logo: https://royaleapi.com/static/img/badge/legendary/Crown_03.png?t=1533013025.8310428
  description: >
    五大技巧，缺一不可（牌組，落位，觀念，反應，實戰）榮獲2019年香港最活躍公會，全年出戰友賽34場，全港最高勝率clan war，唯一discord牌組教學，聯絡Telegram dlam0823申請入會和你玩，我地真係好撚鐘意打CR🔥🔥
clans:
  - name: CR小隊
    tag: PY9PR822
  - name: CR小分隊
    tag: P9GJ2R8P
 - name: CR小小隊
    tag: YUJGY9GY
```
