### ISSUE TITLE
Bangtidy family

### ISSUE THREAD

**Issue by spongebob52916** [RoyaleAPI/family-config#316]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Bangtidy family
key: bangtidy
color: red 
emblem: pekka_02
info:
  logo:
  description: > the bangtidy family clans are a growing family looking for active members, who want to push and help each other reach new heights.
    Long paragraphs with markdown syntax.


    
clans:
  - name: Bangtidy
    tag: G0C28PP
  - name: bangtidy titans
    tag: YCVL9UVC
  - name:
    tag:
```
