### ISSUE TITLE
VIKINS

### ISSUE THREAD

**Issue by djx66** [RoyaleAPI/family-config#32]
```yaml
name: Vikings
key: vikings
color: blue
emblem: Char_Hammer
info:
  logo: https://www.vikingspolisport.com/wp-content/uploads/2019/03/logo-vikings-450x470.png
  description: >
    A.S.D. Associazione Vikings Italia Polisport in breve A.V.I.Pol, nasce a gennaio 2019 con lo scopo di aggregazione sportiva tramite giochi Esports da cellulare; Join us and fight for the Glory - VIKINGS
  social:
    - discord: https://discordapp.com/channels/532234962569527297/532234962569527299
    - website: https://www.vikingspolisport.com/
    - facebook: https://www.facebook.com/asdVikings/
clans:
  - name: Vikings
    tag: #8JQYPOPU
    - name: Vikings 2
    tag: #8UOL8U2V
    - name: Vikings 3
    tag: #P9C9C9LU
    - name: Vikings 4
    tag: #PVLQGLYP
    - name: #PPCROR89
    tag: #8JQYPOPU
    - name: Vikings 6
    tag: #9VGLOCGG
    - name: Vikings 7
    tag: #POL8C89Q
    - name: Vikings 8
    tag: #9VUJCRLV
    - name: Vikings 9
    tag: #Y0PU90PU
    - name: Vikings 10
    tag: #PGCLL2P8
    - name: Vikings Boom
    tag: #9GUQGCQL
    - name: Counting Stars
    tag: #8RPPP90P

```

**Comment by smlbiobot** [comment]
- Vikings 4 clan tag is wrong: 9VLQGLYP
- Vikings 10 clan tag is wrong but we can’t find a suitable replacement
- Vikings 5 clan config is wrong

Revised:
```yml
name: Vikings
key: vikings
color: blue
emblem: Char_Hammer
info:
  logo: https://www.vikingspolisport.com/wp-content/uploads/2019/03/logo-vikings-450x470.png
  description: >
    A.S.D. Associazione Vikings Italia Polisport in breve A.V.I.Pol, nasce a gennaio 2019 con lo scopo di aggregazione sportiva tramite giochi Esports da cellulare; Join us and fight for the Glory - VIKINGS
  social:
    - discord: https://discordapp.com/channels/532234962569527297/532234962569527299
    - website: https://www.vikingspolisport.com/
    - facebook: https://www.facebook.com/asdVikings/
clans:
  - name: Vikings
    tag: 8JQYPOPU
  - name: Vikings 2
    tag: 8UOL8U2V
  - name: Vikings 3
    tag: P9C9C9LU
  - name: Vikings 4
    tag: 9VLQGLYP
  - name: Vikings 5
    tag: PPCROR89
  - name: Vikings 6
    tag: 9VGLOCGG
  - name: Vikings 7
    tag: POL8C89Q
  - name: Vikings 8
    tag: 9VUJCRLV
  - name: Vikings 9
    tag: Y0PU90PU
  - name: Vikings Boom
    tag: 9GUQGCQL
  - name: Counting Stars
    tag: 8RPPP90P
```

**Comment by smlbiobot** [comment]
added but not for 10 so update my config above and decide what you want to do

**Comment by djx66** [comment]
sure... exuse me... the right tag for vikings 10 is: #PGCLL28P

thanx very much

**Comment by djx66** [comment]
please i don't see the "emblem" ... can you make the right configuration?

**Comment by djx66** [comment]
badges/A_Char_Hammer_01.png  this is the right emblem...   ;)

**Comment by djx66** [comment]
also if is possible put this modify in the description:

description: >
    A.S.D. Associazione Vikings Italia Polisport, in breve A.V.I.Pol, nasce a gennaio 2019 con lo scopo di aggregazione sportiva tramite giochi ESports da cellulare; Join us and fight for the Glory - VIKINGS

**Comment by smlbiobot** [comment]
can you update the config and post in this thread?

**Comment by smlbiobot** [comment]
```yml
name: Vikings
key: vikings
color: blue
emblem: A_Char_Hammer_01
info:
  logo: https://www.vikingspolisport.com/wp-content/uploads/2019/03/logo-vikings-450x470.png
  description: >
    A.S.D. Associazione Vikings Italia Polisport, in breve A.V.I.Pol, nasce a gennaio 2019 con lo scopo di aggregazione sportiva tramite giochi ESports da cellulare; Join us and fight for the Glory - VIKINGS
  social:
    - discord: https://discordapp.com/channels/532234962569527297/532234962569527299
    - website: https://www.vikingspolisport.com/
    - facebook: https://www.facebook.com/asdVikings/
clans:
  - name: Vikings
    tag: 8JQYPOPU
  - name: Vikings 2
    tag: 8UOL8U2V
  - name: Vikings 3
    tag: P9C9C9LU
  - name: Vikings 4
    tag: 9VLQGLYP
  - name: Vikings 5
    tag: PPCROR89
  - name: Vikings 6
    tag: 9VGLOCGG
  - name: Vikings 7
    tag: POL8C89Q
  - name: Vikings 8
    tag: 9VUJCRLV
  - name: Vikings 9
    tag: Y0PU90PU
  - name: Vikings 10
    tag: PGCLL28P
  - name: Vikings Boom
    tag: 9GUQGCQL
  - name: Counting Stars
    tag: 8RPPP90P
```
