### ISSUE TITLE
StormFamily 

### ISSUE THREAD

**Issue by TheSuperior1** [RoyaleAPI/family-config#320]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: StormFamily 
key: stormfamily
color: purple
emblem: 
![44E00CEC-4AF9-499F-AFE1-66DE9DA1F7F4](https://user-images.githubusercontent.com/71615045/93725897-c2c07580-fb80-11ea-948d-94228d46bcad)

info: A Family of clans founded in mid-2020


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/

    - discord: http://discord.gg/NAaKPRr

    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: FatalStorm 
    tag: YR9RJJLO 
  - name: Thunderstorm™️
    tag: LJ22YYLL 
  - name: Personal Space
    tag: YG8VJQGG
```

**Comment by smlbiobot** [comment]
- don’t have your emblem
- please upload logo again

```yml
name: StormFamily
key: stormfamily
color: purple
emblem:
info: 
  description: A Family of clans founded in mid-2020
  social:
    - discord: http://discord.gg/NAaKPRr
clans:
  - name: FatalStorm
    tag: YR9RJJLO
  - name: Thunderstorm™️
    tag: LJ22YYLL
  - name: Personal Space
    tag: YG8VJQGG
```
