### ISSUE TITLE
Family Deaf

### ISSUE THREAD

**Issue by caio7575** [RoyaleAPI/family-config#322]
```yml
nome : Deaf Family
chave : Deaf
cor : Blue
emblema : Crown_02
tipo : troféu
informação :
  logo : https://www.brandsoftheworld.com/logo/deficiencia-auditiva
  descrição : >
** Competitive excellence through values guided by the deaf community. **
     All clans are deaf, we are families from each country.

  social :
    - site : https://leaguedeaf.sport.blog/
    - instagram : https://www.instagram.com/esportscrdeaf/
    - youtube : https://www.youtube.com/channel/UChAQ7MoCnGMyeU7PkRHV2BA
    - email : mailto: esportscrsurdo@gmail.com
clãs :
  - nome : DEAF
    tag : RGL2C
  - nome : BRAOW ROYALE
    tag : 9VJJGJRR
  - nome : Deaf Elite
    tag : CRQR2
  - nome : DEAF 2
    tag : L0R2LUV9
  - nome : Egypt Deaf
    tag : 22JP2CV
  - nome : DEAF BASKANIM
    tag : PQ9JJ9UP
  - nome : DEAF IRAN
    tag : YG9U2PJ2
  - nome : Deaf Germany
    tag : Q9R0PL
  - nome : Deaf Caballeros
    tag : P9LP28UR
  - nome : Deaf korea
    tag : RC92JC
  - nome : Deaf Lightning
    tag : YRGYRUG8
  - nome : ITALY DEAF
    tag : PU8GVRC9
  - nome : Deaf Germany
    tag : Q9R0PL
  - nome : Ninja Silencio
    tag : Y098LYV2
  - nome : DeafWarriors
    tag : Y89GVC99
  - nome : "DEL POTRERO"
    tag : 9J28J0
```

**Comment by smlbiobot** [comment]
I have updated the config for you. Please copy + edit this config in the future:

```yml
name: Deaf Family
key: deaf
color: blue
emblem: Crown_02
sort: trophy
info:
  logo: /static/img/brands/logo/deaf.png
  description: >
    **Competitive excellence through values guided by the deaf community.**

    All clans are deaf, we are families from each country.

  social:
    - website: https://leaguedeaf.sport.blog/
    - instagram: https://www.instagram.com/esportscrdeaf/
    - youtube: https://www.youtube.com/channel/UChAQ7MoCnGMyeU7PkRHV2BA
    - email: mailto:esportscrsurdo@gmail.com
clans:
  - name: DEAF
    tag: RGL2C
  - name: BRAOW ROYALE
    tag: 9VJJGJRR
  - name: Deaf Elite
    tag: CRQR2
  - name: DEAF 2
    tag: L0R2LUV9
  - name: Egypt Deaf
    tag: 22JP2CV
  - name: DEAF BASKANIM
    tag: PQ9JJ9UP
  - name: DEAF IRAN
    tag: YG9U2PJ2
  - name: Deaf Germany
    tag: Q9R0PL
  - name: Deaf Caballeros
    tag: P9LP28UR
  - name: Deaf korea
    tag: RC92JC
  - name: Deaf Lightning
    tag: YRGYRUG8
  - name: ITALY DEAF
    tag: PU8GVRC9
  - name: Deaf Germany
    tag: Q9R0PL
  - name: Ninja Silencio
    tag: Y098LYV2
  - name: DeafWarriors
    tag: Y89GVC99
  - name: "DEL POTRERO"
    tag: 9J28J0
```
