### ISSUE TITLE
Veterans Èlite

### ISSUE THREAD

**Issue by Banita94** [RoyaleAPI/family-config#323]
```yaml
name: Veterans Èlite Family
key: veterans
color: blue
emblem: Traditional_Star_01
info: Top Italian Clan
  logo: https://vignette.wikia.nocookie.net/marvelcinematicuniverse/images/3/36/Captain_America_Shield.png
  description: >
The Veterans Family is one of the best clan families in Italy, formed by 5 clans and 250 players.
Best results 2nd place in the old war local leaderboard and stable top 5 local / top 25 global ladder. 
Main focuses war, ladder, team competitive, player growth and friendship. 
There are also monthly tournaments with different game modes and prizes.
  social:
    - twitch: twitch.com/banitagry
    - telegram: @Banita94, @olemrac92, 
clans:
  - name: Veterans Èlite
    tag: 8YVV9YUR
  - name: Veterans Élite 2
    tag: 8Y9U9U2P
  - name: Veterans Hush
    tag: PU98Y22J
  - name: Veterans Anon
    tag: PC90RLUR
  - name: Veterans Rising
    tag: L88ULUUJ

```

**Comment by smlbiobot** [comment]
```yml
name: Veterans Èlite Family
key: veterans
color: blue
emblem: Traditional_Star_01
info:
  logo: /static/img/brands/logo/veternas.png
  description: >
    The Veterans Family is one of the best clan families in Italy, formed by 5 clans and 250 players.
    Best results 2nd place in the old war local leaderboard and stable top 5 local / top 25 global ladder.
    Main focuses war, ladder, team competitive, player growth and friendship.
    There are also monthly tournaments with different game modes and prizes.
  social:
    - twitch: twitch.com/banitagry
    - telegram: https://telegram.me/Banita94
    - telegram: https://telegram.me/olemrac92
clans:
  - name: Veterans Èlite
    tag: 8YVV9YUR
  - name: Veterans Élite 2
    tag: 8Y9U9U2P
  - name: Veterans Hush
    tag: PU98Y22J
  - name: Veterans Anon
    tag: PC90RLUR
  - name: Veterans Rising
    tag: L88ULUUJ
```
