### ISSUE TITLE
G-Knights Clan Family Config

### ISSUE THREAD

**Issue by HertzJJ** [RoyaleAPI/family-config#324]
```yaml
name: G-Knights Clan Family
key: gknights
color: green
emblem: Diamond_Star_02
info:
  logo: https://lh3.googleusercontent.com/pw/ACtC-3funbSXZxRmVg4oysU-wzoMUh39sClPCpeXlBUnZtSbMaDVvvf78UJTECcJ3hVcnSZG7yrkaeBzTORHcoLRg6K_eMk4KkqKibYvMi2qLj25b5-1jCq-ZPmFdV7Ks31LHK5Yqkh1yM6GEB2Ffb79KSQ=s937-no?authuser=0
  description: >
    **Somos G-Knights**! una nueva familia y proyecto que nació en enero de 2020. 
    Nuestra comunidad es amigable, respetuosa y comprometida. Con gente de diversos países y edades.
    Estamos en constante crecimiento. **¡Hace la diferencia!**


  social:
    - twitter: https://twitter.com/ClanGKnights
    - discord: https://discord.gg/2TfzYD4
    - twitch: https://www.twitch.tv/HertzJJ

clans:
  - name: G-Knights
    tag: YLC0RCR9
  - name: argentina
    tag: PR8PJPJL
```
