### ISSUE TITLE
Changes & new Panda Family Clan

### ISSUE THREAD

**Issue by FPIMotylek** [RoyaleAPI/family-config#325]
name: Panda Family
key: pandafamilie
color: black
emblem: Bamboo_03.png
info:
logo: http://panda-family.de/wp-content/uploads/2020/09/PandaLogo-1.jpg
description: >
Wir begannen vor langer Zeit unsere Clash Royale Laufbahn als ein 12 Mitglieder großer Clan Namens „Public Enemy EL“, welcher der Eliteclan von Public Enemy war. Wir wuchsen relativ schnell und wurden, aufgrund harter Arbeit, sehr schnell groß und unabhängig.

Zum Ende hin waren wir bereits 23 Mitglieder und schafften es in die Legendäre Arena, bis wir gemeinsam beschlossen haben, dass unsere Unabhängigkeit erst zur Wirklichkeit wird, wenn auch unser Name sich ändert und somit ebenfalls unabhängig wird.

Dies war der Beginn der „Flow Pandas“.

Wir wussten, dass halbe Sachen nicht funktionieren würden und wir beschlossen die Pandas „richtig“ und zu 100 Prozent aufzubauen. Ein Logo, ein Konzept und Regeln waren, neben einer Internetseite, der Grundstein für den Durchbruch unserer Familie.

Nach dem Erreichen der Legendären Arena unter dem Namen „Flow Pandas“ waren wir bereits über 40 Mitglieder und wir entschlossen uns dazu, zu Expandieren.

Add new line with 2 line breaks as above.
social:
- discord: https://discord.gg/R2a6Pa
- youtube: https://www.youtube.com/channel/UCYybMr8FcNQ3taBjiYUWJSw
- website: http://panda-family.de
- facebook: https://www.facebook.com/pandafamilie/
- email: mailto: FPIMotylek@gmx.de
clans:

name: Flow Pandas
tag: P2GUC2L0
name: Nano Pandas
tag: Y0YV0Q8J
name: Carbon Pandas
tag: PQQ9922P
name: Little Pandas
tag: LYPLYC0L

Could you please chance/add the following data?:

1. Change
logo: http://panda-family.de/wp-content/uploads/2020/09/PandaLogo-1.jpg

2. Change 
email: mailto: kontakt@panda-family.de

3. Change
website: http://panda-family.de

4. Add
name: Black Pandas
tag: Q8Y8Y8J8

Thank you very much for your work!

**Comment by smlbiobot** [comment]
Please in the future use this for editing:


```yml
name: Panda Family
key: panda-family
color: black
emblem: Bamboo_03
info:
  logo: /static/img/brands/logo/pandafamilie.png
  description: >
    We started our clash a long time ago Royal career as a 12 member large clan called "Public Enemy EL", which was the elite clan of Public Enemy. We grew relatively quickly and grew very quickly and independently due to hard work.


    By the end, we were already 23 members and made it into the Legendary Arena until we decided together that our independence would only become a reality if our name changed and became independent.


    This was the beginning of the "Flow Pandas".


    We knew that half things would not work and we decided to build the pandas "correctly" and 100 percent. In addition to a website, a logo, a concept and rules were the cornerstone for our family's breakthrough.


    After reaching the Legendary Arena under the name "Flow Pandas" we were already over 40 members and we decided to expand.
  social:
  - discord: https://discord.gg/R2a6Pa
  - youtube: https://www.youtube.com/channel/UCYybMr8FcNQ3taBjiYUWJSw
  - website: https://panda-family.de
  - facebook: https://www.facebook.com/pandafamilie/
  - email: mailto:FPIMotylek@gmx.de
clans:
- name: Flow Pandas
  tag: P2GUC2L0
- name: Nano Pandas
  tag: Y0YV0Q8J
- name: Carbon Pandas
  tag: PQQ9922P
- name: Little Pandas
  tag: LYPLYC0L
- name: Black Pandas
  tag: Q8Y8Y8J8

```
