### ISSUE TITLE
Chess Royale Family

### ISSUE THREAD

**Issue by xKardio** [RoyaleAPI/family-config#326]
```yaml
name: Chess Royale Family
key: chessroyale
color: teal
emblem: Tower_01
info:
  logo: 
  description: >
    The **Chess Royale Family** is a ESP/ENG speaking, relatively new community, which has quickly grown up as one of the most friendly and loyal communities. We are focused on **improving our gameplay** by **sparring** and **analyzing games**, and with members from all over the world, some of them have jumped into competitive CR leagues.

clans:
  - name: Chess Royale
    tag: YY8JROG2
  - name: Lab Royale
    tag: YQGGOLV2
  - name: Academy Royale
    tag: YQR0TRQ8

```

**Comment by xKardio** [comment]
is this ok?

**Comment by smlbiobot** [comment]
that’s fine

**Comment by smlbiobot** [comment]
added https://royaleapi.com/f/chessroyale

**Comment by xKardio** [comment]
Hey, I edited my comment so to add a new clan of our Family. Will it update automatically on the page?

**Comment by smlbiobot** [comment]
If you want to edit things, you must either:

- reopen issue
- put your new config as comment

I won’t know what gets edited in the comments. Your configs aren’t tied to the live site. Because of the errors that we receive often, we manually put your config to the site.

**Comment by smlbiobot** [comment]
your clan tag is incorrect. In the future, copy it from our site:

```yml
name: Chess Royale Clan Family
key: chessroyale
color: teal
emblem: Tower_01
info:
  description: >
    The **Chess Royale Clan Family** is a ESP/ENG speaking, relatively new community, which has quickly grown up as one of the most friendly and loyal communities. We are focused on **improving our gameplay**, and with members from all over the world, some of them have jumped into competitive CR leagues.

clans:
  - name: Chess Royale
    tag: YY8JR0G2
  - name: Lab Royale
    tag: YQGG0LV2
  - name: Academy Royale
    tag: YQR0YRQ8
```
