### ISSUE TITLE
Clash Family

### ISSUE THREAD

**Issue by Tera-ClashFamily** [RoyaleAPI/family-config#327]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Clash Family
key: clash
color: black
emblem: Crown_04
info:
  logo:
  description: >
    Clash Family is a gamer run organization that offers well managed clans, knowledgeable & seasoned members, information & resources, and a friendly family community.


  social:
    - discord: https://discord.gg/pv3Y2ts


clans:
  - name: Clash Canada
    tag: V2U9JLY 
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clashy Dudes
    tag: YPJY9JVL
```
