### ISSUE TITLE
La Pontinha Company 

### ISSUE THREAD

**Issue by LaPontinha** [RoyaleAPI/family-config#329]
```yaml
nome : La Pontinha Company
chave : pontinha
cor : preto
emblema : A_Char_Goblin_01.png
sort : troféu
informação :
  logo : 
  descrição : >
    ** Venha fazer parte da maior familia do Clash Royale!!! Torneios e premiações internas!!!
Lideres de clã, junte seu clã na nossa família!!!
  social :
    - site : https://linktr.ee/lapontinha
    - twitter : 
    - instagram : https://instagram.com/lapontinha
    - facebook : 
    - twitch : 
    - youtube : 
    - aplicativo : 
    - email : mailto: clashofrages@gmail.com
clãs :
  - nome : La Pontinha
    tag : 98VGJQC0
  - nome : La Pontinha CMD
    tag : L9R0LP8L
  - nome : Metaleiros
    tag : PYJP82UP 
  - nome : Sanidade
    tag : YGRC0R98 
…
```
