### ISSUE TITLE
Inframundo clan - new Spanish clan

### ISSUE THREAD

**Issue by firegore2** [RoyaleAPI/family-config#33]
```yaml
name: "Inframundo"
key: "inframundo"
color: "Red"
emblem: "Skull_06"
info: 
  logo: "https://royaleapi.github.io/cr-api-assets/badges/Skull_06.png"
  description: "TELEGRAM : @royaleinframundo. ⚠️Ser activo en Guerra de clanes. ⚠️Practicar antes de los ataques. ⚠️Donad y se os donará."
  social: 
  - telegram: "https://t.me/royaleinframundo"
clans: 
- name: "Inframundo"
  tag: "YQ02QJ"
```
