### ISSUE TITLE
La Pontinha Company®

### ISSUE THREAD

**Issue by LaPontinha** [RoyaleAPI/family-config#331]
```yaml
nome : La Pontinha Company®
chave : pontinha
cor : preto
emblema : A_Char_Goblin_01.png
sort : troféu
informação :
  logo : 
  descrição : >
    ** Venha fazer parte da maior familia do Clash Royale!!! Torneios e premiações internas!!!
Lideres de clã, junte seu clã na nossa família!!!
  social :
    - site : https://linktr.ee/lapontinha
    - twitter : 
    - instagram : https://instagram.com/lapontinha
    - facebook : 
    - twitch : 
    - youtube : 
    - aplicativo : 
    - email : mailto: clashofrages@gmail.com
clãs :
  - nome : La Pontinha
    tag : 98VGJQC0
  - nome : La Pontinha CMD
    tag : L9R0LP8L
  - nome : Metaleiros
    tag : PYJP82UP 
  - nome : Sanidade
    tag : YGRC0R98 
…
```

**Comment by smlbiobot** [comment]
What are you trying to do? Are you looking to add a family or not?

**Comment by LaPontinha** [comment]
sim, estou querendo adicionar uma familia, mas não entendi direito como funciona, voce poderia me ajudar?

**Comment by smlbiobot** [comment]
Is the config done? Looks fine to m.e just don’t close the issue

**Comment by LaPontinha** [comment]
eu posso mudar depois? a logo da nossa familia vai ser feita ainda

**Comment by LaPontinha** [comment]
depois, mas bem depois mesmo

**Comment by smlbiobot** [comment]
please don’t translate config keys in the future:

```yml
name: La Pontinha Company®
key: pontinha
color: black
emblem: A_Char_Goblin_01
sort: trophy
info:
  description: >
    **Venha fazer parte da maior familia do Clash Royale!!!** Torneios e premiações internas!!!
    Lideres de clã, junte seu clã na nossa família!!!
  social:
    - website: https://linktr.ee/lapontinha
    - instagram: https://instagram.com/lapontinha
    - email: mailto:clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag: 98VGJQC0
  - name: La Pontinha CMD
    tag: L9R0LP8L
  - name: Metaleiros
    tag: PYJP82UP 
  - name: Sanidade
    tag: YGRC0R98 
```
