### ISSUE TITLE
Sons of Plop

### ISSUE THREAD

**Issue by Plop-Dos** [RoyaleAPI/family-config#332]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Sons of Plop
key: sonsofplop
color: purple
emblem: A_Char_Goblin_01
sort: trophy
info:
  logo: user-images.githubusercontent.com/72927970/96139338-1499b880-0eff-11eb-982d-9561343e3326.PNG


  description: >
    THE PLOP FAMILY IS ... 
‣ The  **SONS OF PLOP** (Record 6th French ladder, 31st in CW France) Historical clan, created at the launch of the game, here we push ladder and CW. For crazy of CR, connected H24, big clashollics who do not miss a CW stay in top French ladder ans top CW
‣ The  **KIDS of PLOP** Clan created 31.10.2018, now on CW legendary ligue, goal mounted in ladder at its own pace
‣ The  **SCHOOL of PLOP** School clan allows the addict in trouble to find solutions to evolve with his level.
‣ The **SoP_Gaming** the Plop Esport team
  social:
    - twitter: http://twitter.com/sonsofplop
    - discord: http://discord.gg/tgx69UC
    - email: mailto:sonsofplop@gmail.com
clans:
  - name: Sons of Plop
    tag: 22G2QYR
  - name: Kids of Plop
    tag: 9UGYURV8
  - name: School of Plop
    tag: PVUPVUJC
```
