### ISSUE TITLE
RoyaleAPI Family Config

### ISSUE THREAD

**Issue by HoBo883** [RoyaleAPI/family-config#333]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: RoyaleAPI clash family
key: royaleapi
color: blue
emblem: goblin_02
info: 
  logo:  /static/img/branding/cr-api-logo.png
  description: >RoyaleAPI Clan Family
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
       - discord: http://discord.gg/
  clans:
  - name: Camp HoBo
    tag: Y8U28YYY
  - name: sparkys
    tag: P029VJ8R
  - name:
    tag:
```
