### ISSUE TITLE
Clannabis clan family

### ISSUE THREAD

**Issue by iamanej** [RoyaleAPI/family-config#335]
```yaml
name: Clannabis clan family
key: Clannabis
color: green
emblem: Bolt_01
clans:
  - name: Clannabis
    tag: JJUYPV
  - name: Clannabis ll
    tag: 2VQ0CRRG
  - name: Clannabis lll
    tag: Y0GQG2JG
 - name: Clannabis IV
    tag: L022URCU
```

**Comment by iamanej** [comment]
Hello... Am I doing something wrong?

**Comment by iamanej** [comment]
@smlbiobot

**Comment by smlbiobot** [comment]
This is fine. It takes some time as we are often busy. I will let  you know when it is live!

**Comment by smlbiobot** [comment]
http://royaleapi.com/f/Clannabis

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/clannabis

Please be careful about spacing and format. Also changed casing to lowercase for the key — we don’t recommend using uppercase in URLs because it will fail on some search engines.

```yml
name: Clannabis clan family
key: clannabis
color: green
emblem: Bolt_01
clans:
  - name: Clannabis
    tag: JJUYPV
  - name: Clannabis ll
    tag: 2VQ0CRRG
  - name: Clannabis lll
    tag: Y0GQG2JG
  - name: Clannabis IV
    tag: L022URCU
```
