### ISSUE TITLE
G-Knights Update

### ISSUE THREAD

**Issue by HertzJJ** [RoyaleAPI/family-config#336]
modificaciones en la descripcion y social

```yaml
name: G-Knights Clan Family
key: gknights
color: green
emblem: Diamond_Star_02
info:
  logo: https://lh3.googleusercontent.com/pw/ACtC-3funbSXZxRmVg4oysU-wzoMUh39sClPCpeXlBUnZtSbMaDVvvf78UJTECcJ3hVcnSZG7yrkaeBzTORHcoLRg6K_eMk4KkqKibYvMi2qLj25b5-1jCq-ZPmFdV7Ks31LHK5Yqkh1yM6GEB2Ffb79KSQ=s937-no?authuser=0
  description: >
Somos G-Knights! una nueva familia y proyecto que nació en enero de 2020. 
Nuestra comunidad es amigable, respetuosa y comprometida. Con gente de diversos países y edades. 
Estamos en constante crecimiento. ¡Hace la diferencia!
Ingresa a nuestro servidor **https://discord.gg/2TfzYD4** o hace clic en el icono de Discord.

  social:
    - discord: https://discord.gg/2TfzYD4

clans:
  - name: G-Knights
    tag: YLC0RCR9
  - name: argentina
    tag: PR8PJPJL
```
