### ISSUE TITLE
Friends for Life -> Brazilian War Ship

### ISSUE THREAD

**Issue by SethFalcor** [RoyaleAPI/family-config#337]
```yaml
name: Brazilian War Ship
key: BWS
color: teal
emblem: [BWS Verde Escuro]
info :
   logo : ![BWS Verde Escuro](https://user-images.githubusercontent.com/59695290/96771925-bfefb500-13b8-11eb-820f-02aec3a3c1dc.jpg)

  description: >
Família FFL cresceu e virou BWS ( Brazilian War Ship ), a esquadra navega lado a lado e batalha juntas nossas guerras. Junte-se a família e faça parte da BWS.

 WhatsApp +5511989997919


    - email: mailto: seth.games.project@gmail.com
clans:
  - name: FriendsForLife
    tag: GYGY88
  - name: •ANIQUILADORES•
    tag: 9JCJUP98
  - name: -ANIQUILADORES-
    tag: 990YQ0
  - name: Brother's BR
    tag: 2GUPG002
  - name: ༄FFL࿐єχρєяιєи¢є
    tag: PUYJ0QV2
 - name: BrazilianStars™
    tag: YPPPR0G0

 
```

**Comment by SethFalcor** [comment]
sorry smlbiobot , thanks

**Comment by SethFalcor** [comment]
Ficou alguma coisa errada?

Nome : navio de guerra brasileiro 
chave : BWS 
cor : teal 
emblema : [BWS Verde Escuro] 
Informações :
    logotipo : ! [BWS Verde Escuro] (https://user-images.githubusercontent.com/59695290/96771925-bfefb500-13b8-11eb -820f-02aec3a3c1dc.jpg)

  descrição : >
Família FFL cresceu e virou BWS, a esquadra navega lado a lado e batalha juntas nossas guerras. Junte-se a família e faça parte do BWS.

 WhatsApp +5511989997919


    - email : mailto: seth.games.project@gmail.com 
clãs :
  - Nome : FriendsForLife 
    tag : GYGY88 
  - nome : • ANIQUILADORES • 
    tag : 9JCJUP98 
  - nome : -ANIQUILADORES- 
    tag : 990YQ0 
  - nome : BR do irmão 
    tag : 2GUPG002 
  - nome : FFL ࿐ єχρєяιєи ¢ є 
    tag : PUYJ0QV2 
 - nome : BrazilianStars ™ 
    tag : YPPPR0G0

**Comment by smlbiobot** [comment]
Hey I don’t know what you asked. I don’t read spanish. If possible write in english

**Comment by smlbiobot** [comment]
In the future if you want to rename your family, please don’t just submit request without mentioning it. Duplicate clans in families will result in volatile site.

**Comment by smlbiobot** [comment]
I now see that you did but you wrote in Spanish. Please in the future write in English instead.

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/BWS

```yml
name: Brazilian War Ship
key: BWS
color: teal
emblem: [BWS Verde Escuro]
info:
  logo: /static/img/brands/logo/brazilian-war-ship.png

  description: >
      Família FFL cresceu e virou BWS ( Brazilian War Ship ), a esquadra navega lado a lado e batalha juntas nossas guerras. Junte-se a família e faça parte da BWS.


      WhatsApp +5511989997919
  social:
    - email: mailto:seth.games.project@gmail.com
clans:
  - name: FriendsForLife
    tag: GYGY88
  - name: •ANIQUILADORES•
    tag: 9JCJUP98
  - name: -ANIQUILADORES-
    tag: 990YQ0
  - name: Brother's BR
    tag: 2GUPG002
  - name: ༄FFL࿐єχρєяιєи¢є
    tag: PUYJ0QV2
  - name: BrazilianStars™
    tag: YPPPR0G0
```
