### ISSUE TITLE
KatzClans | Gaming

### ISSUE THREAD

**Issue by Eriksor-KatzClans** [RoyaleAPI/family-config#338]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: KatzClans | Gaming™
key: katzclans
color: black
emblem: Bolt_01
info:
  logo:
![IMG_2302](https://user-images.githubusercontent.com/73300998/97116003-c9d32a00-16d0-11eb-9606-38e0cc170faf.PNG)
  description: >
**KATZCLANS | GAMING** is a **Multi-Platform English Speaking Gaming organization** built up of a number of communities and teams which all connect together to make up our growing network. We strive to build and develop teams in a wide variety of games including **Clash Royale** to encompass all levels of play in each game from casual to competitive. A FAT CAT is a political term originally describing a rich political donor, also called an angel or big money man.  A FAT CAT is usually a person that is SUCCESSFUL and POWERFUL just like us.
social:
    - twitter: https://twitter.com/KatzClans
    - discord: http://discord.gg/fzWXdWF
    - website: http://katzclans.wordpress.com
clans:
  - name: PhatKatz
    tag: G9LGQR
  - name: StrayKatz
    tag: LUVLQ92U
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/katzclans

```yml
name: KatzClans | Gaming™
key: katzclans
color: black
emblem: Bolt_01
info:
  logo: /static/img/brands/logo/katzclans.png
  description: >
    **KATZCLANS | GAMING** is a **Multi-Platform English Speaking Gaming organization** built up of a number of communities and teams which all connect together to make up our growing network. We strive to build and develop teams in a wide variety of games including **Clash Royale** to encompass all levels of play in each game from casual to competitive. A FAT CAT is a political term originally describing a rich political donor, also called an angel or big money man.  A FAT CAT is usually a person that is SUCCESSFUL and POWERFUL just like us.
  social:
    - twitter: https://twitter.com/KatzClans
    - discord: http://discord.gg/fzWXdWF
    - website: http://katzclans.wordpress.com
clans:
  - name: PhatKatz
    tag: G9LGQR
  - name: StrayKatz
    tag: LUVLQ92U
```
