### ISSUE TITLE
La Pontinha Company ATUALIZAÇÃO!

### ISSUE THREAD

**Issue by LaPontinha** [RoyaleAPI/family-config#339]
```
nome : La Pontinha
chave : pontinha
cor : preto
emblema : A_Char_Goblin_01.png
sort : troféu
informação :
  logo : 
  descrição : >
    ** Venha fazer parte da maior familia do Clash Royale!!! Torneios e premiações internas!!!
Lideres de clã, junte seu clã na nossa família!!!
  social :
    - site : https://linktr.ee/lapontinha
    - twitter : 
    - instagram : https://instagram.com/lapontinha
    - facebook : 
    - twitch : 
    - youtube : 
    - aplicativo : 
    - email : mailto: clashofrages@gmail.com
clãs :
  - nome : La Pontinha
    tag : 98VGJQC0
  - nome : La Pontinha CMD
    tag : L9R0LP8L
  - nome : Metaleiros
    tag : PYJP82UP 
  - nome : Sanidade
    tag : YGRC0R98 
  - nome : GDMSA
    tag : JJJUQP8 
```

**Comment by smlbiobot** [comment]
I can’t use this in a foreign language. Can you make sure that you don’t change the fields into another language? (unless your browser is doing this for you automatically and that’s why it’s giving you a non-english template)

**Comment by smlbiobot** [comment]
```yml
name: La Pontinha
chave: pontinha
color: black
emblem: A_Char_Goblin_01
sort: trophy
info:
  description: >
    ** Venha fazer parte da maior familia do Clash Royale!!! Torneios e premiações internas!!!

    Lideres de clã, junte seu clã na nossa família!!!
  social:
    - site: https://linktr.ee/lapontinha
    - instagram: https://instagram.com/lapontinha
    - email: mailto:clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag: 98VGJQC0
  - name: La Pontinha CMD
    tag: L9R0LP8L
  - name: Metaleiros
    tag: PYJP82UP
  - name: Sanidade
    tag: YGRC0R98
  - name: GDMSA
    tag: JJJUQP8 
```
