### ISSUE TITLE
UPDATE - BKCS FAMILY (Adding new clan)

### ISSUE THREAD

**Issue by Kiddy012** [RoyaleAPI/family-config#34]
```yaml
name: B Kindom Clan System
key: BKCS
color: blue
emblem: https://royaleapi.com/static/img/badge/legendary/Bolt_03.png?t=1533013025.8270428
info:
  logo: https://www.flickr.com/photos/163584490@N04/31909076037/in/dateposted-public/
  description: >
B kindom is a competitive clan pushing for top 200 US. Together with our two feeder clans, (Overmorrow, Overwillow and Oversparrow) we form a strong clan family where everyone can feel at home.
  social:
    - discord: http://discord.gg/gN8DhcB
clans:
  - name:  b kindom
    tag: JGLJR8L
  - name: overmorrow
    tag: 99U9QJRR
  - name: overwillow
    tag: 99LRYVQQ
  - name: oversparrow
    tag: PCOLOV29
```
