### ISSUE TITLE
Caverna do Guxo Family

### ISSUE THREAD

**Issue by CavernaDoGuxo** [RoyaleAPI/family-config#340]
```yaml
name : Caverna do Guxo Family 
key : cavernadoguxo
color : Black
emblem : Clover_02.png
info : (CG) 
   logo : https://photos.app.goo.gl/oseGHAYMiTuRYdm48
  description : > **Caverna do Guxo**
  
  A **6 de Setembro de 2019** nasceu o melhor clã Português!
Somos focados em **guerras!**
A competitividade está no sangue, por isso temos os nossos próprios torneios.

Se achas que tens o perfil para te juntares a nós, entra em contacto via discord.
    
  social :
    - discord : https://discord.gg/YNKpq45
clans :
  - Nome : Caverna do Guxo
    tag : YGCC9JJL
  - nome : guxos evo
    tag : LVCUQULY
```

**Comment by smlbiobot** [comment]
```yml
name: Caverna do Guxo Family
key: cavernadoguxo
color: black
emblem: Clover_02
info:
  logo: /static/img/brands/logo/cavernadoguxo
  description: >

    **Caverna do Guxo**

    A **6 de Setembro de 2019** nasceu o melhor clã Português!
    Somos focados em **guerras!**
    A competitividade está no sangue, por isso temos os nossos próprios torneios.

    Se achas que tens o perfil para te juntares a nós, entra em contacto via discord.

  social:
  - discord: https://discord.gg/YNKpq45
clans:
- name: Caverna do Guxo
  tag: YGCC9JJL
- name: guxos evo
  tag: LVCUQULY

```

please use this config if you need to edit in the future
