### ISSUE TITLE
The Andromeda Clan Family 

### ISSUE THREAD

**Issue by PaddyBern** [RoyaleAPI/family-config#341]
```yaml
name: The Andromeda Clan Family
key: andromeda
color: violet 
emblem: Star_Shine_03
info:
  logo: https //imgur.com/a/5iizjop
  description: >
 Andromeda is a 4 clan family built off a strong core and a love for gaming. With a mixture of casual and competitive players we have a home for everyone. We have many attractions to keep you busy in and out of the game, including an eSports team, fun and inclusive server, and ladder rewards! 


  social:
    - discord: http://discord.gg/Zxv6Nnh
    - twitch: https://www.twitch.tv/irishcr
    - instagram: https://instagram.com/andromedafamily

clans:
  - name: AM Aquarius
    tag: LUQ92YLL
  - name: AM Cancer 
    tag: YUYJUCJ9
  - name: AM Taurus
    tag: Y8LCU999
  - name: AM Virgo
    tag: L0PJLPCP
```

**Comment by smlbiobot** [comment]
```yml
name: The Andromeda Clan Family
key: andromeda
color: violet
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/andromeda.png
  description: >
    Andromeda is a 4 clan family built off a strong core and a love for gaming. With
    a mixture of casual and competitive players we have a home for everyone. We have
    many attractions to keep you busy in and out of the game, including an eSports
    team, fun and inclusive server, and ladder rewards!


  social:
  - discord: http://discord.gg/Zxv6Nnh
  - twitch: https://www.twitch.tv/irishcr
  - instagram: https://instagram.com/andromedafamily

clans:
- name: AM Aquarius
  tag: LUQ92YLL
- name: AM Cancer
  tag: YUYJUCJ9
- name: AM Taurus
  tag: Y8LCU999
- name: AM Virgo
  tag: L0PJLPCP

```
