### ISSUE TITLE
HoBo Clan

### ISSUE THREAD

**Issue by HoBo883** [RoyaleAPI/family-config#343]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: RoyaleAPI  HoBo  Clan
key: royaleapi
color: blue
emblem: goblin_02
info:
  logo:
  description: >RoyaleAPI  HoBo  Clan
   
      social:
       - discord: http://discord.gg/
 clans:
  - name: Camp HoBo
    tag: Y8U28YYY
  - name: sparkys
    tag: P029VJ8R
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
You need to define the key. What about Hobo?

You can’t use RoyaleAPI in the name. You can use HoBo instead.

If I don’t hear from you I will use hobo as your name and key.

**Comment by HoBo883** [comment]
Yes, please.
Thanks

**Comment by smlbiobot** [comment]
In the future please don’t leave empty fields

```yml
name: HoBo
key: hobo
color: blue
emblem: goblin_02
info:
  description:
clans:
- name: Camp HoBo
  tag: Y8U28YYY
- name: sparkys
  tag: P029VJ8R

```
