### ISSUE TITLE
Les Frérots

### ISSUE THREAD

**Issue by Shaman75** [RoyaleAPI/family-config#344]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:Les Frérots
key:Frerots 
color:Red
emblem:Crown_01
info:
  logo:![image](https://user-images.githubusercontent.com/73484864/97239622-5b838a00-17ec-11eb-9d32-684adf22fb0a.png)
  description: >
   Premier clan GDC français, 16ème monde en GDC 1, mais également Top FR en ladder.
Les Frérots sont une grande famille de 3 clans, sachant allier performance et convivialité.
Rejoignez nous sur notre Discord : https://discord.gg/g9mxQu5


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/g9mxQu5
    - twitter: http://twitter.com/
    - twitch: https://www.twitch.tv/
    - facebook: https://facebook.com/
  
clans:
  - name: Les Frerots
    tag: 8LUR0C0Y
  - name:~ Les Frerots ~
    tag: 8QJ009Y0
  - name:Les Frérots 3
    tag: LQR8G9QQ
```

**Comment by smlbiobot** [comment]
if you need to edit in the future please use this:

```yml
name: Les Frérots
key: frerots
color: red
emblem: Crown_01
info:
  logo: /static/img/brands/logo/frerots.png
  description: >
    Premier clan GDC français, 16ème monde en GDC 1, mais également Top FR en ladder.
     Les Frérots sont une grande famille de 3 clans, sachant allier performance et
    convivialité.
     Rejoignez nous sur notre Discord: [https://discord.gg/g9mxQu5](https://discord.gg/g9mxQu5)

  social:
  - discord: https://discord.gg/g9mxQu5

clans:
- name: Les Frerots
  tag: 8LUR0C0Y
- name: ~ Les Frerots ~
  tag: 8QJ009Y0
- name: Les Frérots 3
  tag: LQR8G9QQ

``` 

as it corrected a lot of the issues in  your submission
