### ISSUE TITLE
Zero Gemme Family

### ISSUE THREAD

**Issue by ToninoTT** [RoyaleAPI/family-config#347]
```yaml
name: Zero Gemme Family
key: zerogemme
color: green
emblem: Gem_01
info:
  logo:
  description: > 
Famiglia italiana di Zero Gemme. Il nostro obiettivo è creare un gruppo stabile e raggiungere risultati importanti sia in ladder sia nelle guerre. Siamo stabilmente nella top 100 italiana per entrambe le modalità
 
  social:
    - discord: http://discord.gg/WrNSmg
    - telegram: t.me/ZeroGemme

clans:
  - name: Zero Gemme
    tag: G8YVLJ
  - name: Zero Gemme 2.0
    tag: 2880RPVY
  - name: Zero Gemme 3.0
    tag: Q8UUVRUC
```
