### ISSUE TITLE
Elite Warriors

### ISSUE THREAD

**Issue by tomas-djk** [RoyaleAPI/family-config#348]
```yaml
name: The Elite Warrior Family

key: Elite Warriors

color: Rojo

emblem: A_Char_King_02


info:
  logo: //i.redd.it/yfpit80lfmm01.png
 
 description: >
"The Elite Warrior Family" (TEWF) es una familia de clanes, donde encontramos a los jugadores mas activos que desean mejorar tanto individual como grupalmente. Nos apoyamos para que todos tengamos una sola mira; una mira hacia lo mas alto.
  

clans:
  - name: Elite Warriors
    tag: LUUV8YJV
  - name: Elite Warriors2
    tag: YGPQU8QJ
```
