### ISSUE TITLE
Modification to KatzClans | Gaming

### ISSUE THREAD

**Issue by Eriksor-KatzClans** [RoyaleAPI/family-config#349]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: KatzClans | Gaming™
key: katzclans
color: black
emblem: Bolt_01
info:
  logo:
![gaming-clan-logo-template-featuring-an-emblem-with-stars-3757f 6](https://user-images.githubusercontent.com/73300998/97815591-1da7bb00-1c5d-11eb-8c25-86c5c64278fd.png)
  description: >
**KATZCLANS | GAMING** is a **Multi-Platform English Speaking Gaming organization** built up of a number of communities and teams which all connect together to make up our growing network. We build and develop teams in a wide variety of games including **Clash Royale** to encompass all levels of play from casual to competitive. __**Our vision**__: “We strive to be **Successful** and **Powerful**, to dominate any and all battlefields.”
  social:
    - twitter: http://twitter.com/KatzClans
    - discord: http://discord.gg/fzWXdWF 
    - website: https://katzclans.wordpress.com
clans:
  - name: PhatKatz
    tag: G9LGQR
  - name: StrayKatz
    tag: LUVLQ92U
  - name: AlleyKatz
    tag: YG8U2U8Q
```
