### ISSUE TITLE
La Pontinha Company® ATUALIZAÇÃO!

### ISSUE THREAD

**Issue by LaPontinha** [RoyaleAPI/family-config#352]
nome : La Pontinha
chave : pontinha
cor : preto
emblema : A_Char_Goblin_01.png
sort : troféu
informação :
  logo : 
  descrição : >
    ** Venha fazer parte da maior familia do Clash Royale!!! Torneios e premiações internas!!!
Lideres de clã, junte seu clã na nossa família!!!
  social :
    - site : https://linktr.ee/lapontinha
    - twitter : 
    - instagram : https://instagram.com/lapontinha
    - facebook : 
    - twitch : 
    - youtube : 
    - aplicativo : 
    - email : mailto: clashofrages@gmail.com
clãs :
  - nome : La Pontinha
    tag : 98VGJQC0
  - nome : La Pontinha CMD
    tag : L9R0LP8L
  - nome : Sanidade
    tag : YGRC0R98 
  - nome : GDMSA
    tag : JJJUQP8

**Comment by smlbiobot** [comment]
you’ve sent me configs in spanish again… please send them to me in English — I can’t use them if you send them to me in spanish

**Comment by smlbiobot** [comment]
Please use this file AS IS:

```yml
name: La Pontinha Company®
key: pontinha
color: black
emblem: A_Char_Goblin_01
sort: trophy
info:
  description: >
    **Venha fazer parte da maior familia do Clash Royale!!!** Torneios e premiações internas!!!
    Lideres de clã, junte seu clã na nossa família!!!
  social:
    - website: https://linktr.ee/lapontinha
    - instagram: https://instagram.com/lapontinha
    - email: mailto:clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag: 98VGJQC0
  - name: La Pontinha CMD
    tag: L9R0LP8L
  - name: Metaleiros
    tag: PYJP82UP 
  - name: Sanidade
    tag: YGRC0R98 
```

**Comment by smlbiobot** [comment]
To prevent google translate trying to translate the config, you can also just download this file here:

https://gist.github.com/smlbiobot/52b0654fc33277e48c364e9821b1ff0e

**Comment by smlbiobot** [comment]
```yml
name: La Pontinha Company®
key: pontinha
color: black
emblem: A_Char_Goblin_01
sort: trophy
info:
  description: >
    **Venha fazer parte da maior familia do Clash Royale!!!** Torneios e premiações internas!!!
    Lideres de clã, junte seu clã na nossa família!!!
  social:
    - website: https://linktr.ee/lapontinha
    - instagram: https://instagram.com/lapontinha
    - email: mailto:clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag: 98VGJQC0
  - name: La Pontinha CMD
    tag: L9R0LP8L
  - name: Sanidade
    tag: YGRC0R98
  - name: GDMSA
    tag: JJJUQP8
```
