### ISSUE TITLE
[Update #314] Guerrilheiros Family

### ISSUE THREAD

**Issue by Acidgirlcode** [RoyaleAPI/family-config#355]
```yaml
name: Familia Guerrilheiros
key: guerrilheiros
color: black
emblem: Skull_01.png
sort: trophy
info:
  logo: https://uploaddeimagens.com.br/imagens/Q-LoKxU
  description: >
    **Familia Guerrilheiros** é uma equipe da comunidade competindo no Brasil. fundado em 2016.
    
    O clã é um lugar para todos, especialmente para jogadores ativos, competitivos. 
    Todos nós compartilhamos uma paixão pelo jogo, somos amigáveis,
    sempre doamos e ajudamos uns aos outros com um objetivo comum em mente: melhorar nossas habilidades e nos divertir! 
    
    Junte-se à nos Guerrilheiro. Aproveite o jogo! =D
  social:
    - website: https://campsite.bio/guerrilheiros
    - discord: https://discord.gg/QUhmsvs
    - application: https://chat.whatsapp.com/FXTgqFGNSOZ4Lr7ysHxsIN
    - instagram: https://www.instagram.com/osguerrilheiros/

clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
  - name: Guerrilheiros 6
    tag: YQQRY2UU
  - name: Guerrilheiros 7
    tag: YQJV0LC9
  - name: Guerrilheiros 8
    tag: YG0C208Q
```

**Comment by smlbiobot** [comment]
```yml
name: Familia Guerrilheiros
key: guerrilheiros
color: black
emblem: Skull_01
sort: trophy
info:
  logo: /static/img/brands/logo/guerrilheiros.png
  description: >
    **Familia Guerrilheiros** é uma equipe da comunidade competindo no Brasil. fundado em 2016.


    O clã é um lugar para todos, especialmente para jogadores ativos, competitivos.
    Todos nós compartilhamos uma paixão pelo jogo, somos amigáveis,
    sempre doamos e ajudamos uns aos outros com um objetivo comum em mente: melhorar nossas habilidades e nos divertir!


    Junte-se à nos Guerrilheiro. Aproveite o jogo! =D
  social:
    - website: https://campsite.bio/guerrilheiros
    - discord: https://discord.gg/QUhmsvs
    - application: https://chat.whatsapp.com/FXTgqFGNSOZ4Lr7ysHxsIN
    - instagram: https://www.instagram.com/osguerrilheiros/

clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
  - name: Guerrilheiros 6
    tag: YQQRY2UU
  - name: Guerrilheiros 7
    tag: YQJV0LC9
  - name: Guerrilheiros 8
    tag: YG0C208Q
```

please edit this file in the future unless you have changed things

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/guerrilheiros

**Comment by Acidgirlcode** [comment]
Sorry, I believe it went out of order on the site.

Is it possible to make the adjustment? I noticed that I sent the clans in the correct order.

![image](https://user-images.githubusercontent.com/67425480/98482670-a1275600-21e1-11eb-9c80-7a16d0b2c2c2.png)

```yaml
clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
  - name: Guerrilheiros 6
    tag: YQQRY2UU
  - name: Guerrilheiros 7
    tag: YQJV0LC9
  - name: Guerrilheiros 8
    tag: YG0C208Q
```

Thanks,
![image](https://media.tenor.com/images/2a822d4aef43853def2abfeebb595828/tenor.gif)
