### ISSUE TITLE
SCG - New Family

### ISSUE THREAD

**Issue by SeniorBai** [RoyaleAPI/family-config#357]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: SCG Family
key: SCG
color: purple
emblem: Bamboo_01
info:
  description: >
    ** 欢迎热爱皇室的兄弟加入我们~我们共有三个部落~总有一款适合你~部落QQ群：127676618**
clans:
  - name: SCG004
    tag: 2YVQGQQ
  - name: scg-py会所
    tag: L8R2UYY
  - name: SCG乌托邦
    tag: YPRYGL88
```
