### ISSUE TITLE
Casual Gamer Innovations

### ISSUE THREAD

**Issue by LiamOnGitHub26** [RoyaleAPI/family-config#358]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Casual Gamer Innovations
key: casualgamerinnovations
color: blue
emblem: Traditional_Star_05
info:
  logo: https://media.discordapp.net/attachments/753741314712928326/772228633443041280/CGI.jpg?width=856&height=431
  description: > Casual Gamer Innovations (CGi) is a clan family with a long history. It started way back in the early 2000s as a small group of Call Of Duty players. That small group just happens to be the three original founders of CGi and one year they even made top 10 in the world! However, things eventually came to an end and they switched to mobile gaming...which was Supercell, even more specifically Clash Royale. They wanted to meet new friends...grow a family and so they did! CGi is now booming more than it ever has before! Their clans are set up as a training mechanism to breed up some of the greatest players who will eventually build their way to the top of the leaderboard. CGi is without a doubt the greatest family to be apart of!
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  

social:
- discord: http://discord.gg/sPvgJMD
    clans:
  - name: CGi GODS
    tag: YC2Q8P0V 
  - name: CGi KINGS
    tag: YQP9PP9L 
 ```
