### ISSUE TITLE
La Pontinha Company® UPDATE!!!!

### ISSUE THREAD

**Issue by LaPontinha** [RoyaleAPI/family-config#360]
name: _ᆕᆕ_ La Pontinha Company®
key: pontinha
color: preto
emblem: A_Char_Goblin_01.png
sort : troféu
info:
  logo : https://https://ibb.co/q7y8GpX
  description: >
    ** Venha fazer parte da maior família do Clash Royale!!! 
Torneios e premiações internas!!!
Lideres de clã, associe seu clã em nossa família!!!
Cada dia crescendo mais!! Oficialmente internacional, mais de 6 países.
4 torneios com prêmios e um ranking geral para saber quem é o melhor de todos os tempos!

  social :
    - site : https://linktr.ee/lapontinha
    - discord: https://discord.gg/pxxnzhU
    - twitter : 
    - instagram : https://instagram.com/lapontinha
    - facebook : https://www.facebook.com/rovak.seitoushi
    - twitch : https://www.twitch.tv/rovak_
    - youtube : https://youtube.com/channel/UCMfrpQALbqyfk-JAHlyZW-w
    - application : https://play.google.com/store/apps/details?id=com.copafacil
    - email : mailto: clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag : 98VGJQC0
  - name: La Pontinha CMD
    tag : L9R0LP8L
  - name: Sanidade
    tag : YGRC0R98 
  - name: GDMSA
    tag : JJJUQP8 
  - name: --RENEGADO--
    tag : PVYR0Y20
  - name: imperio
    tag : L0GQCCQ0

**Comment by smlbiobot** [comment]
Please I need config in ENGLISH

**Comment by LaPontinha** [comment]
=D finished, soo use the last edit =D

**Comment by smlbiobot** [comment]
please edit what i wrote HERE in the future:

```yml
name: La Pontinha Company®
key: pontinha
color: black
emblem: A_Char_Goblin_01
sort: trophy
info:
  logo: /static/img/brands/logo/pontinha.png
  description: >
    **Venha fazer parte da maior família do Clash Royale!!!**
    Torneios e premiações internas!!!
    Lideres de clã, associe seu clã em nossa família!!!
    Cada dia crescendo mais!! Oficialmente internacional, mais de 6 países.
    4 torneios com prêmios e um ranking geral para saber quem é o melhor de todos os tempos!
  social:
    - website: https://linktr.ee/lapontinha
    - discord: https://discord.gg/pxxnzhU
    - instagram: https://instagram.com/lapontinha
    - facebook: https://www.facebook.com/rovak.seitoushi
    - twitch: https://www.twitch.tv/rovak_
    - youtube: https://youtube.com/channel/UCMfrpQALbqyfk-JAHlyZW-w
    - application: https://play.google.com/store/apps/details?id=com.copafacil
    - email : mailto:clashofrages@gmail.com
clans:
  - name: La Pontinha
    tag : 98VGJQC0
  - name: La Pontinha CMD
    tag : L9R0LP8L
  - name: Sanidade
    tag : YGRC0R98
  - name: GDMSA
    tag : JJJUQP8
  - name: --RENEGADO--
    tag : PVYR0Y20
  - name: imperio
    tag : L0GQCCQ0
```
