### ISSUE TITLE
yemas

### ISSUE THREAD

**Issue by ggrage** [RoyaleAPI/family-config#361]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: ⚡Йёма's family⚓
key: yemas
color: green
emblem:  flag_j_01
info:
  logo: https://cdn.royaleapi.com/static/img/badge/silver-1/flag_j_01.png?t=e8e4efdf
  description: >
    Семейство, которое включает в себя на данный момент 2 клана: основной клан, который скоро войдёт в топ россии и второй клан, созданный недавно. Семейство основано:26.05.19. Когда мы едины - мы непобедимы!
  social:
    - instagram: https://instagram.com/gg.rage
clans:
  - name: ⚡Йёма's crew⚓
    tag: YQJ2RQ8P
  - name: ⚡Йёма's team⚓
    tag: PYPULLJV
```
