### ISSUE TITLE
Suisse Romande Update

### ISSUE THREAD

**Issue by Hentrax** [RoyaleAPI/family-config#364]
name: Suisse Romande
key: suisseromande
color: red
emblem: flag_d_01
info:
  logo: https://cdn.discordapp.com/attachments/572077902292582401/762324341467512832/logo-sr.png
  description: >
The **Suisse Romande** family is one of the largest Clash Royale communities in the French-speaking part of Switzerland. 
We have six clans that focus on player performance in ladder and clan wars. The eSport clan 'SR eSport'  is linked to our eSport team '**Empire Suisse Romande**', which is part of the community. 
The good team spirit within our clans is the key to success : we use a common discord between all clans and the eSport team, and organize frequent events together. 
  social:
    - website: https://utip.io/suisseromandecr
    - discord: https://discord.gg/QAjXquE
    - email: suisseromande.cr@gmail.com
    - twitter: https://twitter.com/SuisseRomandeCR
    - instagram: https://instagram.com/teamsuisseromandecr
    - twitch: https://www.twitch.tv/suisseromandecr
    - youtube: https://www.youtube.com/channel/UCLM6qFOK6uC1y95HTz3nFoQ
    - facebook: https://www.facebook.com/SuisseRomandeCR
clans:
  - name: Suisse Romande
    tag: 2QCYRPL2
  - name: Suisse Romande2
    tag: 9UPLYLCY
  - name: Suisse Romande3
    tag: RVY80CG
  - name: Suisse Romande4
    tag: PUPJ9GUL
  - name: Suisse Romande5
    tag: YGVRGQJQ
  - name: Suisse Romande6
    tag: YY808V99
  - name: SR eSport
    tag: LYVPJV9L

**Comment by smlbiobot** [comment]
corrected some of your config errors. please use this in the future:

- emails need mailto: prefix for linking
- logo converted to local for the site

```yml
name: Suisse Romande
key: suisseromande
color: red
emblem: flag_d_01
info:
  logo: /static/img/brands/logo/suisseromande.png
  description: >
    The **Suisse Romande** family is one of the largest Clash Royale communities in the French-speaking part of Switzerland.
    We have six clans that focus on player performance in ladder and clan wars. The eSport clan 'SR eSport'  is linked to our eSport team '**Empire Suisse Romande**', which is part of the community.
    The good team spirit within our clans is the key to success : we use a common discord between all clans and the eSport team, and organize frequent events together.
  social:
    - website: https://utip.io/suisseromandecr
    - discord: https://discord.gg/QAjXquE
    - email: mailto:suisseromande.cr@gmail.com
    - twitter: https://twitter.com/SuisseRomandeCR
    - instagram: https://instagram.com/teamsuisseromandecr
    - twitch: https://www.twitch.tv/suisseromandecr
    - youtube: https://www.youtube.com/channel/UCLM6qFOK6uC1y95HTz3nFoQ
    - facebook: https://www.facebook.com/SuisseRomandeCR
clans:
  - name: Suisse Romande
    tag: 2QCYRPL2
  - name: Suisse Romande2
    tag: 9UPLYLCY
  - name: Suisse Romande3
    tag: RVY80CG
  - name: Suisse Romande4
    tag: PUPJ9GUL
  - name: Suisse Romande5
    tag: YGVRGQJQ
  - name: Suisse Romande6
    tag: YY808V99
  - name: SR eSport
    tag: LYVPJV9L
```
