### ISSUE TITLE
Clash Family

### ISSUE THREAD

**Issue by Tera-ClashFamily** [RoyaleAPI/family-config#368]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Clash Family
key: clash
color: black
emblem: Crown_04
info:
  logo: 
  description: >
    The **Clash Family** is a cr clan family consisting of 5 clans. Our mission is to help members grow and reach their clash royale goals. We offer well managed clans, seasoned & knowledgeable members and a friendly online community. Join the family & let’s make some magic happen!


  social:
    - discord: https://discord.gg/pv3Y2ts


clans:
  - name: Clash Canada
    tag: V2U9JLY 
  - name: Clashy Dudes
    tag: YPJY9JVL
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clash Mortals
    tag: LVLCQR2C
  - name: Clash Rebels
    tag: LP9GRQ92

```
