### ISSUE TITLE
Family Config - Grim Family 

### ISSUE THREAD

**Issue by austinhanus** [RoyaleAPI/family-config#370]
Hey all. 

```yaml
name: Grim Family
key: grim
color: violet
emblem: Skull_05
info:
  logo:
  description: >
    The Grim Family is a growing community of focused adult players looking to progress, connect, and share 
our shameless addiction to the game we all love to hate, Clash Royale. Grim Tidings was ranked within 
the top 20 NA for CW1 and is currently the #1 NA clan in CW2. Our efforts to develop players, casual 
yet competitive atmosphere, and focus on loyalty and reliability have allowed us to grow our family 
clans with players from around the world. With clans for competitive to casual players, we have 
something for everyone and we’re continually growing. 

Have questions? Want to join our community? Hop in our discord and join the discussion!
  social:
    - discord: http://discord.gg/8Vsf6dr
clans:
  - name: Grim Tidings
    tag: 9YL2V82U
  - name: Grim Tidings 2
    tag: 9Q8P0CQR
  - name: Grim Tidings 3
    tag: L20P0PRC
```
