### ISSUE TITLE
DRAGONS Family Subscription

### ISSUE THREAD

**Issue by eabueno** [RoyaleAPI/family-config#371]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: DRAGONS
key: dragons
color: red
emblem: Flame_03
info:
  logo: https://bit.ly/dragonslogo
  description: >
    Os  **DRAGONS** é uma Familia Brasileira de CR e um clã bem organizado. Nossa história começou em Junho de 2016 e continua até hoje.
    **Amizade** e **Honestidade** são nossos valores.
    Uma vez Dragons, sempre Dragons.
    
    
    The **DRAGONS** are a Brazilian CR Family and very organized clan. Our history started at June 2016 and still goes on. 
    **Friendship** and **Honesty** are our values.
    Once Dragons, always Dragons.
  social:
    - twitter: https://twitter.com/DragonsCRTeam
    - discord: https://bit.ly/dragonscr
    - facebook: https://www.facebook.com/DRAGONSCR
    - youtube: https://bit.ly/dragonscryt
    - email: mailto:dragonsCRteamBR@gmail.com
    
clans:
  - name: Dragons
    tag: 9J9RQJR
  - name: Dragons 2
    tag: PGU9LRQ
  - name: Dragons 3
    tag: JC0L0UY
  - name: Dragons 4
    tag: Y22Y0RL0
```
