### ISSUE TITLE
Crucible of Sins Family Update

### ISSUE THREAD

**Issue by RobertKlohr** [RoyaleAPI/family-config#375]
This is an update to the existing family entry https://royaleapi.com/clan/family/crucible/clans.

We would like to update the key to crucibleofsins if possible.  If that is not possible then maintaining the current key of crucible.  We are also changing the domain name of the web site.  The old one has expired and we are in the process of standing up a new one.

We are working on a new logo so for now can we either use the emblem file as the logo or leave it blank.

```yaml
name: Crucible of Sins
key: crucibleofsins
color: red
emblem: Flame_01
info:
  description: >
    The **Crucible of Sins Clan Family** (CSCF) was established in 2011.
    Our family fosters an environment where casual and competitive
    styles of play can both flourish.

  - Competitive Clans
    - Crucible Pride 
    - Crucible Wrath

  - Casual Clans
    - Crucible Lust
    - Crucible Sloth

  - Rebuilding Clans
    - Crucible Envy
    - Crucible Rage

    No Merges | No Alliances | No Name Changes
  social:
    - line: https://line.me/
    - web: https://www.crucibleofsins.com/
clans:
  - name: Crucible Envy
    tag: 9GVV
  - name: Crucible Lust
    tag: PVG0G8Q
  - name: Crucible Pride 
    tag: 8889GR
  - name: Crucible Rage
    tag: 9JURC08L
  - name: Crucible Sloth
    tag: PR209CG9
  - name: Crucible Wrath
    tag: 2LRU2J
sort: trophy
```
