### ISSUE TITLE
The Irish Mob

### ISSUE THREAD

**Issue by BoogieManIrishMob** [RoyaleAPI/family-config#378]
```yaml
name: Irish Mob
key: The Irish Mob
color: Green
emblem: Clover_02
Info: The Irish Mob family of clans is a dedicated 
war based clan family that is looking for players
of ANY skill to join in our ranked family of clans. 
Highly competitive to casual players will fit into our system and can move up or down clans as leaders
and co leaders permit. 

Clans:
- Name: LetterKenyIrish 
Tag: PUOLVRGG 
- Name: Fighting Irish 
Tag: Q0RVJ9R2 
- Name: Drunken Irish 
Tag: QPVV0Q8G 
- Name: Lucky Irish 
Tag: YJ2RV8VV 
Sort: trophy
… 
```

**Comment by smlbiobot** [comment]
```yml
name: Irish Mob
key: irish-mob
color: Green
emblem: Clover_02
sort: trophy
info: 
  description: >
    The Irish Mob family of clans is a dedicated 
    war based clan family that is looking for players
    of ANY skill to join in our ranked family of clans. 
    Highly competitive to casual players will fit into our system and can move up or down clans as leaders
    and co leaders permit. 

clans:
- name: LetterKenyIrish 
  tag: PUOLVRGG 
- name: Fighting Irish 
  tag: Q0RVJ9R2 
- name: Drunken Irish 
  tag: QPVV0Q8G 
- name: Lucky Irish 
  tag: YJ2RV8VV 

```
