### ISSUE TITLE
TheDTSS Family

### ISSUE THREAD

**Issue by CookieGamer1** [RoyaleAPI/family-config#379]
```yaml
name: TheDTSS Family
key: thedtss
color: teal
emblem: Coin_03
info:
  logo: https://cdn.discordapp.com/attachments/479872177064116224/785698982038339584/TheDTSS_CR_Logo.png
  description: >
    TheDTSS is a friendly and growing environment for people to have a great time. What started out as a simple clan with a group of friends is now a clan family which is one of the nicest and most helpful ones out there. Dedicated to helping out everyone and leaving no one behind, we pride ourselves on making sure every member is satisfied even though we may not be the best. Based in Vancouver, TheDTSS is a great option for anyone who likes to chat and build new friendships while still enjoying the game they love: Clash Royale! Be selfless and humble: that is TheDTSS way!
  social:
    - twitter: http://twitter.com/thedtssfamily
    - discord: http://discord.gg/JMXnX3aCSY
    - youtube: https://www.youtube.com/channel/UCKtGFL63SuK8N50eNYyQDmw?
    - instagram: https://instagram.com/thedtssfamily
    - email: mailto:
clans:
  - name: TheDTSS
    tag: LL8P0GJY
  - name: TheDTSS Second
    tag: LPL9QPJU
  - name: Budski
    tag: YJPCJ9QQ
```

**Comment by smlbiobot** [comment]
```yml
name: TheDTSS Family
key: thedtss
color: teal
emblem: Coin_03
info:
  logo: /static/img/brands/logo/thedtss.png
  description: >
    TheDTSS is a friendly and growing environment for people to have a great time. What started out as a simple clan with a group of friends is now a clan family which is one of the nicest and most helpful ones out there. Dedicated to helping out everyone and leaving no one behind, we pride ourselves on making sure every member is satisfied even though we may not be the best. Based in Vancouver, TheDTSS is a great option for anyone who likes to chat and build new friendships while still enjoying the game they love: Clash Royale! Be selfless and humble: that is TheDTSS way!
  social:
    - twitter: http://twitter.com/thedtssfamily
    - discord: http://discord.gg/JMXnX3aCSY
    - youtube: https://www.youtube.com/channel/UCKtGFL63SuK8N50eNYyQDmw?
    - instagram: https://instagram.com/thedtssfamily
clans:
  - name: TheDTSS
    tag: LL8P0GJY
  - name: TheDTSS Second
    tag: LPL9QPJU
  - name: Budski
    tag: YJPCJ9QQ
```
