### ISSUE TITLE
Némésis Quebec Clan Family

### ISSUE THREAD

**Issue by RagnarLothbrok77** [RoyaleAPI/family-config#381]
```yml
name:   Némésis Quebec Clan Family
key: nemesisquebec
color: black
emblem: flag_j_03
info: 
logo: flag_j_03.png
description: >
Bienvenue dans la famille Némésis Québec   !
3 Clans où la guerre est Obligatoire.
Nous pouvons vous ajouter sur notre   groupe Messenger sur demande.
Welcome in the Némésis Québec Clan Family   !
3 Clans where war is mandatory.
We can add you on our  messenger group upon demand.
 
clans:
- name: Némésis Quebec
  tag: YU0JV9QV
- name: Némésis Qc2
  tag: YQURV2CR
- name: Némésis Qc3
  tag: YLGV9LGL
```

**Comment by smlbiobot** [comment]
```yml
name: Némésis Quebec Clan Family
key: nemesisquebec
color: black
emblem: flag_j_03
info:
  logo: /static/img/badge/bronze-1/flag_j_01.png
  description: >
    Bienvenue dans la famille Némésis Québec!
    3 Clans où la guerre est Obligatoire.
    Nous pouvons vous ajouter sur notre groupe Messenger sur demande.


    Welcome in the Némésis Québec Clan Family!
    3 Clans where war is mandatory.
    We can add you on our  messenger group upon demand.

clans:
- name: Némésis Quebec
  tag: YU0JV9QV
- name: Némésis Qc2
  tag: YQURV2CR
- name: Némésis Qc3
  tag: YLGV9LGL
```
