### ISSUE TITLE
Houwei t / Adragon69

### ISSUE THREAD

**Issue by Adragon69** [RoyaleAPI/family-config#383]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Houwei t
key: Adragon69
color: Bolt_02
emblem: Flame_02
info: 
  logo:
  description: >

Adragon69 offer Clash Royale players with many clans depending on your statistics. We also offer a friendly environment for all players across our clans and future clans as well. Our top clans are competitive but if you want to play casual, there will always be space in our lower clans. We play friendly battle with each other to grow together and practice. Hope you see you in one of our clans soon! Thanks you for reading!


  social:
    - discord: https://discord.gg/HWd7YmF
    - youtube: https://www.youtube.com/channel/UCh5BxJZbEobZ7ytfXIwAbDA

clans:
  - name: Houwei t
    tag: YJVVL88G
  - name: Houz t
    tag:LP20GC8P  
  - name: Call Of Psychos
    tag:YYVVP0P9  
  -name: Adragon69
    tag:Q0QJQCR0  
```
