### ISSUE TITLE
WeAreLithuania config

### ISSUE THREAD

**Issue by urjusa** [RoyaleAPI/family-config#384]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: WeAreLithuania Family
key: wal
color: green
emblem: Fugi_04
info:
  logo: http://92.61.36.115/images/WeAreLithuania.png
  description: >
    **WeAreLithuania** (WAL) - susijungę bendram tikslui, sukūrėme nepakartojamą bendruomenę.  
    Ja kiekvienas didžiuojamės, einame viso klano bei asmeninių pergalių link. 
    Šiuo metu turime tris klanus, kuriuose ir **Tu** rasi vietą sau. 
    Komandinis darbas ir ilgalaikė draugystė - mūsų vertybės, kurias puoselėdami sėkmingai laikomės ne tik Lietuvos topuose! 


    **WeAreLithuania** - mus jungia bendrystė ir kovingumas. PRISIJUNK PRIE MŪSŲ ir tapk didelės bei draugiškos bendruomenės dalimi!
  social:
    - facebook: https://www.facebook.com/groups/1755326847810921
clans:
  - name: WeAreLithuania
    tag: P0GJ8JLU
  - name: WeAreLithuania2
    tag: 9VQPY2J8
  - name: WeAreLithuania3
    tag: LV2RJLVQ
```
