### ISSUE TITLE
Fire Scale family YAML

### ISSUE THREAD

**Issue by fons-000** [RoyaleAPI/family-config#386]
```yaml
name: Fire Scale Family
key: firescale
color: red
emblem: Flame_01
info:
  logo: 
  description: >
Fire Scale E-sports was founded on the 20th of September 2019. 


We've achieved huge success and have branched out into multiple games such as Clash Royale, Brawl Stars, Super Smash Bros Ultimate, Overwatch and many more games. 


In Clash Royale, we have around 100-150 members with 4 clans! **We’re active, non-toxic and constantly on the grow and grind to achieve great things. 🔥** 


 __Are you looking for a positive and competitive environment? A place where you can grow and improve your Clash Royale skills? Join our clan and community.__
  social:
    - twitter: https://twitter.com/firescale_
    - discord: http://discord.gg/zffexuq
    - discord: https://discord.gg/DvAWtD8x67
    - twitch: https://www.twitch.tv/firescaleesports
    - reddit: https://www.reddit.com/r/RoyaleRecruit/comments/k2zi67/4000_fire_scale_y2y9j0jy_looking_for_players_and/
    - youtube: https://www.youtube.com/channel/UCUbNbUpVVOfSldQuTZqD3vQ
    - instagram: https://www.instagram.com/fire_scale.esports/
    - facebook: https://facebook.com/
    - trovo: https://trovo.live/Fire_Scale_Esports
clans:
  - name: Fire Scale
    tag: Y2Y9J0JY
  - name: FS Spark
    tag: LL9J8JYR
  - name: Phoenixes
    tag: YUGJQR29
  - name: LEBANESE CLAN
    tag: #L8G9VY8

```
Can you use this picture for the logo?
![FireScale_logo_discord](https://user-images.githubusercontent.com/55665983/102728954-cfdf3300-432e-11eb-920d-ad7f3cac8b9c.png)
