### ISSUE TITLE
Albiceleste family

### ISSUE THREAD

**Issue by llonger13** [RoyaleAPI/family-config#389]
```yaml
name:  Familia Albiceleste
key: Albiceleste
color: blue
emblem: 
info:
  logo: family-config/IMG-20201123-WA0028__1_-removebg-preview.png
  description: > 
    Mas que un clan, una familia.
    Top 4 Arg. en Wars I 
    Aquí es donde les contendremos
    Aquí es donde nosotros pelearemos
    Y aquí es donde ellos morirán
  social:
    - twitter: http://twitter.com/albicelesteCR
    - discord: https://discord.gg/5Ayk65kWs9
    - twitch: https://www.twitch.tv/albicelestecr
    - facebook: https://facebook.com/albicelesteCR
clans:
  - name: Albiceleste
    tag: LL92RRP
  - name: Albiceleste II
    tag: YGP0GJCC
 
```

**Comment by smlbiobot** [comment]
I assume that you do want your family config? don’t close it.

**Comment by llonger13** [comment]
Yes, i do

**Comment by smlbiobot** [comment]
can you post your logo as a comment?

**Comment by llonger13** [comment]
![m_IMG-20201123-WA0028__1_-removebg-preview](https://user-images.githubusercontent.com/76451566/103802554-15d60f80-502e-11eb-8f87-df66c8d53797.png)

**Comment by smlbiobot** [comment]
please use this for future edits:

```yml
name:  Familia Albiceleste
key: albiceleste
color: blue
emblem: Heart_04
info:
  logo: /static/img/brands/logo/albiceleste.png
  description: >
    Mas que un clan, una familia.<br>
    Top 4 Arg. en Wars I <br>
    Aquí es donde les contendremos<br>
    Aquí es donde nosotros pelearemos<br>
    Y aquí es donde ellos morirán<br>
  social:
    - twitter: http://twitter.com/albicelesteCR
    - discord: https://discord.gg/5Ayk65kWs9
    - twitch: https://www.twitch.tv/albicelestecr
    - facebook: https://facebook.com/albicelesteCR
clans:
  - name: Albiceleste
    tag: LL92RRP
  - name: Albiceleste II
    tag: YGP0GJCC
```
