### ISSUE TITLE
Adding clans to my existing clan family

### ISSUE THREAD

**Issue by Adragon69** [RoyaleAPI/family-config#391]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Adragon69
key: Adragon69
color: blue
emblem: Bolt_02
info:
  logo:
  description: > Adragon69 offers Clash Royale players with many clans depending on your statistics. We also offer a friendly environment for all players across our clans and future clans as well. Our top clans are competitive but if you want to play casual, there will always be space in our lower clans. We play friendly battle with each other to grow together and practice. Hope you see you in one of our clans soon! Thank you for reading!
   
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: https://discord.gg/HWd7YmF
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/UCh5BxJZbEobZ7ytfXIwAbDA
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Houwei t
    tag: YJVVL88G  
  - name: Houz t
    tag:LP20GC8P
  - name: Call Of Psychos
    tag:YYVVP0P9  
  - name: Adragon69
     tag: Q0QJQCR0  
  - name: Bdragon69
     tag: YRUQYQLR
   - name: Edragon69
     tag: Q0V088LJ  
```

**Comment by smlbiobot** [comment]
in the future, please edit THIS CONFIG:

```yml
name: Adragon69
key: Adragon69
color: red
emblem: Flame_02
info:
  description: >
    Adragon69 offer Clash Royale players with many clans depending on your statistics. We also offer a friendly environment for all players across our clans and future clans as well. Our top clans are competitive but if you want to play casual, there will always be space in our lower clans. We play friendly battle with each other to grow together and practice. Hope you see you in one of our clans soon! Thanks you for reading!
  social:
    - discord: https://discord.gg/HWd7YmF
    - youtube: https://www.youtube.com/channel/UCh5BxJZbEobZ7ytfXIwAbDA

clans:
  - name: Houwei t
    tag: YJVVL88G
  - name: Houz t
    tag: LP20GC8P
  - name: Call Of Psychos
    tag: YYVVP0P9
  - name: Adragon69
    tag: Q0QJQCR0
  - name: Bdragon69
    tag: YRUQYQLR
  - name: Edragon69
    tag: Q0V088LJ
```
