### ISSUE TITLE
Badge Family

### ISSUE THREAD

**Issue by ArmanJubayed** [RoyaleAPI/family-config#392]
name: Badge Family
key: badge
color: blue
emblem: Traditional_Star_05
info:
  logo:
  description:  Badge Family is the Largest, Strongest and Oldest Clash Royale Family in the the world with our 1000 members and 20 clans!
We started our journey before this game launched globally. Our journey started with 'Badge Of Honour'. Since than we are growing and now we have 20 official clans. Also we have more than 17 unofficial clans.
We believe in Brotherhood. We give equal priority to each and every members. We believe that’s the reason why we have come so far.
UNITY IS OUR STRENGTH.

***We host lots of monthly pass Royale family tournaments.
***Top family clans provide surprise ladder rewards and individual surprise clan based tournament.
***The family is a place for everyone, as our members come from all around the world, from casual to competitive players, old to young.
 ***If you join us, you will find the most friendly environment in clash Royale.
***JOIN US AND BE A PART OF OUR AWESOME FAMILY.
    - facebook: https://www.facebook.com/groups/392527513474/?ref=share
clans:
  -  name :  Badge OF Honour
      Tag :  2L9VUG
  -  name :  Badge Of Tigers
      Tag :  YPGYJP0Y
  -  name :  Badge Of Unity
      Tag :  LQQPU2UJ
  -  name :  Badge Of Magix
      Tag :  9YPVY928
  -  name :  Badge Of Magic
      Tag :  YG9UULOO
  -  name :  Badge Of Bro'S
      Tag :  8289UJCO
  -  name :  Badge Of Rise
      Tag :  Y2JVJVC9
  -  name :  Badge Of Friend
      Tag :  Y8GO9Y22
  -  name :  Badge Of Bangla
      Tag :  9POGUQ89
  -  name :  Badge Of Titans
      Tag :  P82OJQPL
  -  name :  Badge Of BD™
      Tag :  PGROLQJ2
  -  name :  Badge of Royal
      Tag :  LJPUVR9L
  -  name :  Badge Of Army
      Tag :  LUV92LYG
  -  name :  Badge Of Champs
      Tag :  YUJLOOR2
  -  name :  Badge Of Legend
      Tag :  Q99YUPYJ
  -  name :  Badge Of Lions
      Tag :  YRQYPQJC
  -  name :  Badge Of Love
      Tag :  L22UUPJ2
  -  name :  Badge Of Riders
      Tag :  P8GJLOCV
  -  name :  Badge Of Glory
      Tag :  QOC9U8VQ
  -  name :  Badge Of Icon
      Tag :  YRRLVUR9

**Comment by smlbiobot** [comment]
in the future:

- be careful about markdown
- don’t add extra spaces around colons
- copy and edit this config here:

```yml
name: Badge Family
key: badge
color: blue
emblem: Traditional_Star_05
info:
  description: >

    Badge Family is the Largest, Strongest and Oldest Clash Royale Family in the the world with our 1000 members and 20 clans!
    We started our journey before this game launched globally. Our journey started with 'Badge Of Honour'. Since than we are growing and now we have 20 official clans. Also we have more than 17 unofficial clans.
    We believe in Brotherhood. We give equal priority to each and every members. We believe that’s the reason why we have come so far.
    UNITY IS OUR STRENGTH.


    - We host lots of monthly pass Royale family tournaments.

    - Top family clans provide surprise ladder rewards and individual surprise clan based tournament.

    - The family is a place for everyone, as our members come from all around the world, from casual to competitive players, old to young.

    - If you join us, you will find the most friendly environment in clash Royale.
    
    - JOIN US AND BE A PART OF OUR AWESOME FAMILY.

  social:
    - facebook: https://www.facebook.com/groups/392527513474/?ref=share
clans:
  - name: Badge OF Honour
    tag: 2L9VUG
  - name: Badge Of Tigers
    tag: YPGYJP0Y
  - name: Badge Of Unity
    tag: LQQPU2UJ
  - name: Badge Of Magix
    tag: 9YPVY928
  - name: Badge Of Magic
    tag: YG9UULOO
  - name: Badge Of Bro'S
    tag: 8289UJCO
  - name: Badge Of Rise
    tag: Y2JVJVC9
  - name: Badge Of Friend
    tag: Y8GO9Y22
  - name: Badge Of Bangla
    tag: 9POGUQ89
  - name: Badge Of Titans
    tag: P82OJQPL
  - name: Badge Of BD™
    tag: PGROLQJ2
  - name: Badge of Royal
    tag: LJPUVR9L
  - name: Badge Of Army
    tag: LUV92LYG
  - name: Badge Of Champs
    tag: YUJLOOR2
  - name: Badge Of Legend
    tag: Q99YUPYJ
  - name: Badge Of Lions
    tag: YRQYPQJC
  - name: Badge Of Love
    tag: L22UUPJ2
  - name: Badge Of Riders
    tag: P8GJLOCV
  - name: Badge Of Glory
    tag: QOC9U8VQ
  - name: Badge Of Icon
    tag: YRRLVUR9

```
