### ISSUE TITLE
xQlusive Familie

### ISSUE THREAD

**Issue by labrero** [RoyaleAPI/family-config#393]
```yaml
name: xQlusive Familie
key: xQlusive
color: Teal
emblem: bamboo_04.png
info: 
logo: https://cdn.discord.me/server/28e3ff40bd14d54f2e2673a921cb983f085df0dd6ab3b5a2b20840da92da24e8/icon_5b6d1ee95a9a8c86720dd98e9bc1fbd4938a64437b4063ab8724e8acafb3cb18.jpg
description : **xQlusive** is een Clash Royale Familie met meerdere feeder clans. 
Join de server als je ***geïnteresseerd*** bent in ***Clash Royale***, andere spelers wilt ontmoeten en onderdeel wilt worden van een clan met top ambities.

Ben je nog niet de beste spelers, zijn nog niet je kaarten max maar wil je toch een leuke tijd hebben?
Dan is een van onze feeder clans wellicht iets voor jou. 
Op onze server komt je hierover alles te weten en geven we antwoorden op je vragen.

_**SEASON** REWARDS**_
social:
- discordme: https://discord.me/xqnl
- discord: https://discord.gg/Kj2JDYc

clans:
- name: xQlusive Gold
tag: P0UUL80C
- name: xQlusive Silver
tag: 9JQC8GVQ
- name: xQlusive Bronze
tag: 9R0UCQYJ
- name: CWR Startup
tag: PU080LLR
- name: CWR Startup 2
tag: LPRLGJRL
```

**Comment by smlbiobot** [comment]
edit this in the future:

```yml
name: xQlusive Familie
key: xqlusive
color: teal
emblem: bamboo_04
info:
  logo: /static/img/brands/logo/xqlusive.png
  description: >

    **xQlusive** is een Clash Royale Familie met meerdere feeder clans.

    Join de server als je ***geïnteresseerd*** bent in ***Clash Royale***, andere spelers wilt ontmoeten en onderdeel wilt worden van een clan met top ambities.

    Ben je nog niet de beste spelers, zijn nog niet je kaarten max maar wil je toch een leuke tijd hebben?<br>
    Dan is een van onze feeder clans wellicht iets voor jou. <br>
    Op onze server komt je hierover alles te weten en geven we antwoorden op je vragen.<br>

    _**SEASON** REWARDS**_
  social:
  - discord: https://discord.me/xqnl
  - discord: https://discord.gg/Kj2JDYc

clans:
- name: xQlusive Gold
  tag: P0UUL80C
- name: xQlusive Silver
  tag: 9JQC8GVQ
- name: xQlusive Bronze
  tag: 9R0UCQYJ
- name: CWR Startup
  tag: PU080LLR
- name: CWR Startup 2
  tag: LPRLGJRL
```
