### ISSUE TITLE
Invictus Family

### ISSUE THREAD

**Issue by Link471** [RoyaleAPI/family-config#394]
```yaml
name: Invictus Family
key: invictus
color: blue
emblem: Sword_01
info:
  logo: https://drive.google.com/file/d/1185jfvg1yaArEEl74fpQBpO1djU9wxvh/view?usp=drivesdk
  description: >
    "You are the Master of your fate, You are the Captain of your soul" With these words as our motto, Invictus clan family offers Weekly Cash Tournaments, our own League and Fun Events every week. We strive to offer the best for our community. Our community flourishes in both casual and competitive scenes.
  social:
    - twitter: https://twitter.com/Invictus_Clash?s=09
    - discord: https://discord.gg/aKcAew3
clans:
  - name: Invictus Gaming
    tag: YGU28VC2
 - name: Invictus Lyra
    tag: YQLC9J0J
   - name: Invictus Apollo
    tag: LUU2QUQG
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/invictus

**Comment by smlbiobot** [comment]
use this in the future:

```yml
name: Invictus Family
key: invictus
color: blue
emblem: Sword_01
info:
  logo: /static/img/brands/logo/invictus.png
  description: >
    "You are the Master of your fate, You are the Captain of your soul" With these words as our motto, Invictus clan family offers Weekly Cash Tournaments, our own League and Fun Events every week. We strive to offer the best for our community. Our community flourishes in both casual and competitive scenes.
  social:
    - twitter: https://twitter.com/Invictus_Clash?s=09
    - discord: https://discord.gg/aKcAew3
clans:
  - name: Invictus Gaming
    tag: YGU28VC2
  - name: Invictus Lyra
    tag: YQLC9J0J
  - name: Invictus Apollo
    tag: LUU2QUQG
```
