### ISSUE TITLE
Soul Star's Gaming Association 

### ISSUE THREAD

**Issue by ANINDA-P-ROY** [RoyaleAPI/family-config#396]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: **Soul Star's Gaming™**
key: **Soul Star's**
color: teal
emblem: flag_d_01
info:
logo: https://ibb.co/MPwRV05
description: 
**Soul Star's Gaming Association Was Founded On 3rd Of April 2017.** We decided to open an Organization After Most Of Our Experienced & Super Passionate Players Wanted To Try Out In The Competitive Scenario Of Clash Royale. **We Started Out Very Small And We Are Entirely Built On Our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since Then, Our Performances Have Spoken To Our Opponents, Clients in the CR World and Thus We Stand **Unique & Special** From Other's. **This family is a place FOR EVERYONE, as our members come from all around the world, from casual to competitive players, old to young, Very Active to Hyper Active and so on. Communication is NOT A BARRIER here.**


**WE HAVE TAKEN THE OATH TO BECOME ONE OF THE PROFFERS IN CLASH ROYALE. Join Us and SHINE LIKE A STAR !**


  social:
    - discord: http://discord.gg/65WmeZ2
    - email: mailto:anin.gamingmanager@gmail.com
    - twitter: http://twitter.com/SoulStarsGaming
    - reddit: http://www.reddit.com/user/CLASHMASTERanin
    - instagram: https://www.instagram.com/soulstarsgaming/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8

`
```
