### ISSUE TITLE
Fire Scale Family: Clans change - Lebanese clan removed

### ISSUE THREAD

**Issue by fons-000** [RoyaleAPI/family-config#397]
The YAML has only changed the clans key. 
Which is the following now:

`YAML

clans: 
  - name: Fire Scale
    tag: Y2Y9J0JY
  - name: FS Spark
    tag: LL9J8JYR
  - name: Phoenixes
    tag: YUGJQR29
`
Can this be updated for the Fire Scale's Family? Thanks 👌

**Comment by smlbiobot** [comment]
In the future mention the family name in the title — it was very confusing what needs changed until I search for it.

**Comment by smlbiobot** [comment]
```yml
name: Fire Scale Family
key: firescale
color: red
emblem: Flame_01
info:
  logo: /static/img/brands/logo/firescale.png
  description: >
    Fire Scale E-sports was founded on the 20th of September 2019.


    We've achieved huge success and have branched out into multiple games such as Clash Royale, Brawl Stars, Super Smash Bros Ultimate, Overwatch and many more games.


    In Clash Royale, we have around 100-150 members with 4 clans! **We’re active, non-toxic and constantly on the grow and grind to achieve great things.** 🔥


     _Are you looking for a positive and competitive environment? A place where you can grow and improve your Clash Royale skills? Join our clan and community._
  social:
    - twitter: https://twitter.com/firescale_
    - discord: https://discord.gg/zffexuq
    - discord: https://discord.gg/DvAWtD8x67
    - twitch: https://www.twitch.tv/firescaleesports
    - reddit: https://www.reddit.com/r/RoyaleRecruit/comments/k2zi67/4000_fire_scale_y2y9j0jy_looking_for_players_and/
    - youtube: https://www.youtube.com/channel/UCUbNbUpVVOfSldQuTZqD3vQ
    - instagram: https://www.instagram.com/fire_scale.esports/
    - trovo: https://trovo.live/Fire_Scale_Esports
clans:
  - name: Fire Scale
    tag: Y2Y9J0JY
  - name: FS Spark
    tag: LL9J8JYR
  - name: Phoenixes
    tag: YUGJQR29

```
