### ISSUE TITLE
Elysium Netzwerk

### ISSUE THREAD

**Issue by Elysium-Netzwerk** [RoyaleAPI/family-config#398]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Elysium Netzwerk
key: elysium
color: red
emblem: flag_k_03
info:
  logo: https://www.directupload.net/file/d/6060/lo5xbkfb_jpg.htm
  description: > Willkommen im **Elysium Netzwerk**. Einem der aktivsten Clash Royale Netzwerke im deutschsprachigen Raum. Wir sind seid den Anfängen von Clash Royale aktiv mit 3 Clans vertreten. Wenn ihr auf der Suche nach einem aktiven Clan mit einer tollen Community seid, dann habt ihr ihn hier gefunden. Schaut gerne auf unserem Discord oder Instagram Account vorbei, wenn wir Euer Interesse geweckt haben!   
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - discord: http://discord.gg/K5MY6a794S
    - instagram: https://instagram.com/elysium_netzwerk
    - email: mailto: elysiumnetzwerk.cr@gmail.com
clans:
  - name: Elysium
    tag: LOGO29
  - name: Elysium 2
    tag: 2G88PYY
  - name: Elysium 3
    tag: UULOU2C
```

**Comment by smlbiobot** [comment]
don’t close issues if you want it.

**Comment by smlbiobot** [comment]
fixed issues:

```yml
name: Elysium Netzwerk
key: elysium
color: red
emblem: flag_k_03
info:
  logo: /static/img/brands/logo/elysium.png
  description: >
    Willkommen im **Elysium Netzwerk**. Einem der aktivsten Clash Royale Netzwerke im deutschsprachigen Raum. Wir sind seid den Anfängen von Clash Royale aktiv mit 3 Clans vertreten. Wenn ihr auf der Suche nach einem aktiven Clan mit einer tollen Community seid, dann habt ihr ihn hier gefunden. Schaut gerne auf unserem Discord oder Instagram Account vorbei, wenn wir Euer Interesse geweckt haben!
  social:
    - discord: http://discord.gg/K5MY6a794S
    - instagram: https://instagram.com/elysium_netzwerk
    - email: mailto:elysiumnetzwerk.cr@gmail.com
clans:
  - name: Elysium
    tag: LOGO29
  - name: Elysium 2
    tag: 2G88PYY
  - name: Elysium 3
    tag: UULOU2C
```
