### ISSUE TITLE
Bergclan Familie - full exchange of family config please; new config as follows:

### ISSUE THREAD

**Issue by TutEnAmum** [RoyaleAPI/family-config#399]
```yaml
name: Bergclan Familie
key: BERGCLANS
color: blue
emblem: Fugi_02
info:
  logo: https://cdn.discordapp.com/attachments/647029292634603521/648187855960670239/Bergclans-1.png
  description: >
    Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community mit Spielern 
    aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während einer Alpenüberquerung 
    von Freunden aus den drei Ländern, geht es uns um Gaming, Spaß und Vernetzung in einer 
    starken Community, über nationale, soziale, Alters- und alle übrigen Grenzen und Barrieren 
    hinweg. Wir wollen uns kontinuierlich verbessern: als Spieler in den Games, und das Angebot
    für unsere Player. 

    Wir bieten **16 Clash Royale Clans**, jeder mit eigenem Schwerpunkt: vom erfolgreichen Warclan für 
    anspruchsvolle und ladderorientierte Spieler, über erfolgreiche, aber entspannte Warclans in der Legendären Liga, 
    absolut Community-orientierte Clans, für Familien, junge Spieler, senior Gamer und Familienurgesteine,
    mit Fokus auf ein Land, ... bis zu den beiden aufeinander abgestimmten Ausbildungsclans (für Starter und midlevel Player)
    und unseren no Clanwar - Clan für aktive Spieler, die keinen War mögen: Clan Bergruhe.

    Auf unserem professionellen **Discord Server** findet ihr alles zu den Games und könnt euch vernetzen. In unserer gut 
    strukturierten **CR Waffenkammer** findet ihr bspw. aktuelle Metadecks (aktive Links zur Übernahme der 
    Decks in die CR App) nebst Tutorials, diverse Guides zu den Themen Profi Ladder, Pulling + Kiten, Cyceln, ...
    und zu Decktypen wie Hog 2.6, X-Bow, Logbait, Golem, Graveyard, Bridgespam Royal Giant oder PEKKA Ram, starke 
    Wardecks, die YouTube Kanäle der bekannten Stars, ...
  
    Neben **eSports Events** wie Turnieren, ab und an mit Prämien, bieten wir **2 Brawl Stars Clubs**
    (Royal Fortress, top 100 BRD,  und Royal Fortress2, casual), einen **Clash Of Clans Club** 
    (die Bergdrachen), sowie andere Games auf Nachfrage in Subcommunities. Bei uns findet ihr eure 
    passende Ecke. Und es tut sich immer wieder was bei uns. Schaut mal auf unserem Discord Server vorbei, 
    es lohnt sich.

    Kontakt: gern, via Discord oder Line (tut-en-amum).
  social:
    - discord: https://discord.gg/cpX2Kqu
    - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
    - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
    - twitter: https://mobile.twitter.com/BergClans
    - facebook: https://m.facebook.com/bergclan.familia.7
clans:
  - name: Bergfeste
    tag: 2RGL0LLU
  - name: Bergspitze
    tag: 8VPPU2V9
  - name: Berglöwen
    tag: Y8JU0CPU
  - name: Bergwächter
    tag: PC8V90UG
  - name: Berghütte
    tag: PPR9RGQ2
  - name: Bergsee
    tag: PPYYPUPU
  - name: Bergpass
    tag: YQPP9R2R
  - name: Bergfried
    tag: PVVY98G9
  - name: Bergziegen
    tag: L8V8GQ0C
  - name: Bergwerk
    tag: YRJLPYQU
  - name: Bergcamp
    tag: PR20YYGV
  - name: Bergsteiger
    tag: Y8Y99RRR
  - name: Bergruhe
    tag: YQR90UJ2
  - name: Bergliga
    tag: LVLURC0V
  - name: Berglager
    tag: PCUY9GYC
  - name: Berglager 2
    tag: LVQRQVPC
    ```

**Comment by TutEnAmum** [comment]
Hello. As recommended here last time, instead of exchanging bits and bytes of our family config here and there, above please find the full family config of Berglcan Familie. Please replace the existing family config by the config above. Thanks in advance

**Comment by smlbiobot** [comment]
is the logo changed? if it’s not changed please don’t keep on referencing with a URL

**Comment by smlbiobot** [comment]
Please edit this config instead:

```yml
name: Bergclan Familie
key: bergclans
color: blue
emblem: Fugi_02
info:
  logo: /static/img/brands/logo/bergclans.png
  description: 'Herzlich willkommen bei der **Bergclan Familie**, einer Gaming Community
    mit Spielern aus Deutschland, Österreich und der Schweiz. Gegründet 2017 während
    einer Alpenüberquerung von Freunden aus den drei Ländern, geht es uns um Gaming,
    Spaß und Vernetzung in einer starken Community, über nationale, soziale, Alters-
    und alle übrigen Grenzen und Barrieren hinweg. Wir wollen uns kontinuierlich verbessern:
    als Spieler in den Games, und das Angebot für unsere Player.


    Wir bieten **14 Clash Royale Clans**, jeder mit eigenem Schwerpunkt: vom erfolgreichen
    Warclan für anspruchsvolle und ladderorientierte Spieler, über erfolgreichen,
    aber entspannten Warclan, absolut Community-orientierten Clan, für Familien, junge
    Spieler, senior Gamer und Familienurgesteine, mit Fokus auf ein Land, ... bis
    zu den aufeinander abgestimmten Ausbildungsclans (für Starter bis midlevel Player).


    Auf unserem professionellem **Discord Server** findet ihr alles zu den Games und
    könnt euch vernetzen. In unserer gut strukturierten **CR Waffenkammer** findet
    ihr bspw. die aktuellsten Metadecks (aktive Links zur Übernahme der Decks in die
    CR App) nebst Tutorials, diverse Guides zu den Themen Profi Ladder, Pulling +
    Kiten, Cyceln, und zu Decktypen wie Hog 2.6, X-Bow, Logbait, Golem, Graveyard,
    Bridgespam Royal Giant oder PEKKA Ram, ...


    Neben **eSports Events** wie Turnieren, ab und an mit Prämien, und einer CR Liga
    analog der CRL bieten wir **2 Brawl Stars Clubs** (Royal Fortress, top 100 BRD,  und
    Royal Fortress2) und einen **Clash Of Clans Club** (die Bergdrachen), sowie andere
    Games auf Nachfrage in Subcommunities. Bei uns findet ihr eure passende Ecke.
    Und es tut sich immer was bei uns. Schaut mal auf unserem Discord Server vorbei,
    es lohnt sich.


    Kontakt: gern, via Discord oder Line (tut-en-amum).

    '
  social:
  - discord: https://discord.gg/cpX2Kqu
  - website: https://clashroyaleforum.de/thread/7282-%F0%9F%8F%94%EF%B8%8Fbergclan-familie%F0%9F%97%BB-%F0%9F%87%A9%F0%9F%87%AA%F0%9F%87%A8%F0%9F%87%AD%F0%9F%87%A6%F0%9F%87%B9/
  - youtube: https://m.youtube.com/channel/UC4IV3RqDvZbGKNo8gJBSlNQ/videos
  - twitter: https://mobile.twitter.com/BergClans
  - facebook: https://m.facebook.com/bergclan.familia.7
clans:
- name: Bergfeste
  tag: 2RGL0LLU
- name: Bergspitze
  tag: 8VPPU2V9
- name: Berglöwen
  tag: Y8JU0CPU
- name: Bergwächter
  tag: PC8V90UG
- name: Berghütte
  tag: PPR9RGQ2
- name: Bergsee
  tag: PPYYPUPU
- name: Bergziegen
  tag: L8V8GQ0C
- name: Bergpass
  tag: YQPP9R2R
- name: Bergfried
  tag: PVVY98G9
- name: Bergcamp
  tag: PR20YYGV
- name: Bergsteiger
  tag: Y8Y99RRR
- name: Berglager
  tag: PCUY9GYC
- name: Berglager 2
  tag: LVQRQVPC
```
