### ISSUE TITLE
[Family Update] RoyalFlush Family Edit

### ISSUE THREAD

**Issue by royalflushcr** [RoyaleAPI/family-config#40]
```yaml
name: RoyalFlush™
key: RoyalFlush
color: black
emblem: flag_j_03
info:
  logo: https://i.imgur.com/OjX0vbN.jpg
  description: >
    **Welcome to the RoyalFlush Family!** 
    We are an Internationally based group of clans with members from all over the world. 
    We have a fun and relaxed atmosphere that values maturity and discourages toxic behaviour. 
    We are growing everyday and are looking for awesome Clashers to join our gaming organisation. 
    Our goal is to become a top Ladder and Clan Wars Clan.
    All our clans compete daily in Clan Wars with the main clan ranking top 4 Global. 
    So whether you are looking for a competitive clan, or just a casual atmosphere for active players, you’ll find it here at RoyalFlush!
  social:
    - twitter: http://twitter.com/RoyalFlushGG_
    - discord: http://discord.gg/3MBAD7c
    - twitch: https://www.twitch.tv/RoyalFlush_GG
    - instagram: http://www.instagram.com/RoyalFlushGG
    - website: http://royalflush.gg
    - email: mailto:support@royalflush.gg
clans:
  - name: RoyalFlush™
    tag: 89UJ8J2J
  - name: RF™ eSports
    tag: 8UP08G2Y
  - name: RoyalFlush
    tag: Y0JPU9Y
  - name: RoyalFlush II
    tag: CPVV9QJ
  - name: RoyalFlush III
    tag: CJLUGRG
  - name: RoyalFlush IV
    tag: GVYRY2G
  - name: RoyalFlush V
    tag: 98J2RPUU
  - name: RF™ Meteor
    tag: PYC2YVUC
  - name: RF™ Galaxies
    tag: PVVGRRUY
  - name: RoyalFlush USA
    tag: 8GY0L0LU
  - name: RoyalFlush CA
    tag: 9PYG0QL0
  - name: RoyalFlush PER
    tag: 92L0RPRU
  - name: RoyalFlush IND
    tag: 8Q0YPP0C
  - name: RoyalFlush™ DE
    tag: P0CJUG28
  - name: RoyalFlush DE 2
    tag: 088LCG0      
  - name: RoyalFlush UK
    tag: 8GVPLCUY
  - name: RoyalFlush SA
    tag: P92G0JQ8
  - name: RoyalFlush SG
    tag: 8U98U9QG  
  - name: RoyalFlush AUS
    tag: 8LV0GRRR                    
```
