### ISSUE TITLE
Invicto eSports Family

### ISSUE THREAD

**Issue by Korneljaworski** [RoyaleAPI/family-config#400]
```yaml

name: Invicto eSports
key: invicto
color: red
emblem: no_clan
info:
  logo: https://invicto.games/3d-mockup-2.png
  description: >
    **Invicto eSports** is an international gaming organization with a focus in the North America, Latin America, and Europe divisions. We pride ourselves on our family-first policy, keeping a toxic-free environment in the clans that call Invicto eSports home. For more information on joining, please follow us on Twitter @InvictoCR. **We hope to meet you soon!**


  social:
    - twitter: https://twitter.com/InvictoCR
    - discord: https://discord.io/Invicto
    - website: https://invicto.games
clans:
  - name: Invincible Eyes
    tag: 8QUPU00P
  - name: I Got Witches
    tag: Y09228VG
  - name: Asgard
    tag: LL2C8PCP
…
```
