### ISSUE TITLE
Clash Family

### ISSUE THREAD

**Issue by Tera-ClashFamily** [RoyaleAPI/family-config#401]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Clash Family
key: clash
color: black
emblem: Crown_04
info:
  logo: https://www.facebook.com/groups/248968486660327/?ref=share
  description: >
     **Clash Family** is a clash royale clan family consisting of 5 clans. Our first clan was created when the game launched in 2016. The Clash Family was established in 2020.
     Our mission is to help our members grow and achieve their clash royale goals. We offer well managed clans, seasoned and knowledgeable members and a friendly online community.
    

  social:
    - discord: https://discord.gg/pv3Y2ts
clans:
  - name: Clash Canada
    tag: V2U9JLY 
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clash Mortals
    tag: LVLCQR2C
  - name: Clash Rebels
    tag: LP9GRQ92
  - name: Clash Pandas
    tag: YJJR8YR0
```

**Comment by smlbiobot** [comment]
```yml
name: Clash Family
key: clash
color: black
emblem: Crown_04
info:
  logo: /static/img/brands/logo/clash.png
  description: >
     **Clash Family** is a clash royale clan family consisting of 5 clans. Our first clan was created when the game launched in 2016. The Clash Family was established in 2020.
     Our mission is to help our members grow and achieve their clash royale goals. We offer well managed clans, seasoned and knowledgeable members and a friendly online community.


  social:
    - discord: https://discord.gg/pv3Y2ts
clans:
  - name: Clash Canada
    tag: V2U9JLY
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clash Mortals
    tag: LVLCQR2C
  - name: Clash Rebels
    tag: LP9GRQ92
  - name: Clash Pandas
    tag: YJJR8YR0
```
