### ISSUE TITLE
Team Demonic Update Family

### ISSUE THREAD

**Issue by TeamDemonic** [RoyaleAPI/family-config#402]
```yaml
name: Team Demonic
key: TeamDemonic
color: red
track: true
emblem:Skull_06
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    **Team Demonic** : Located in Italian Area.
Main Clans: Demonic Elite, Demonic Pride. Academies: Demonic 4.0, I CLandestini, Demonic Army. Demonic 2.0, Demonic 3.0 abandoned.
  
 clans:
  - name: Demonic Elite
    tag: P082G990
  - name: Demonic Pride
    tag: 2G8LYY0R  
  - name: Demonic 4.0
    tag: 9VG89LG9
  - name: I Clandestini
    tag: CG2YQLL 
  - name: Demonic Army
    tag: YGRL20JQ 
  - name: Demonic 2.0
    tag: Y0PC28PG
  - name: Demonic 3.0
    tag: 9LU2LG0C



  
```

**Comment by smlbiobot** [comment]
```yml
name: Team Demonic
key: TeamDemonic
color: red
emblem: Skull_06
info:
  description: >
    **Team Demonic** : Located in Italian Area.


    Main Clans: Demonic Elite, Demonic Pride. Academies: Demonic 4.0, I CLandestini, Demonic Army. Demonic 2.0, Demonic 3.0 abandoned.

clans:
  - name: Demonic Elite
    tag: P082G990
  - name: Demonic Pride
    tag: 2G8LYY0R
  - name: Demonic 4.0
    tag: 9VG89LG9
  - name: I Clandestini
    tag: CG2YQLL
  - name: Demonic Army
    tag: YGRL20JQ
  - name: Demonic 2.0
    tag: Y0PC28PG
  - name: Demonic 3.0
    tag: 9LU2LG0C

```
