### ISSUE TITLE
Soul Stars Gaming™ Registration as Clan Family

### ISSUE THREAD

**Issue by ANINDA-P-ROY** [RoyaleAPI/family-config#403]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: **Soul Stars Gaming™**
key: **SSGA**
color: teal
emblem: Star_Shine_02
info:
  logo: https://ibb.co/MPwRV05
  description: >
    **Soul Stars Gaming™ was Founded On the 3rd Of April 2017.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small, and, we are entirely built on out HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have spoken to our opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clanmates come from all around the Globe; from *Casual To Competitive, Young To Old* and so on.


**WE HAVE TAKEN THE OATH, TO BECOME THE FINEST & OUTSTANDING CLAN FAMILY IN CLASH ROYALE.** Join Us & *SHINE LIKE A STAR* !


**Creator:: Gladiator, Manager:: CLASHMASTERanin**
  social:
    - discord: http://discord.gg/vdnbTVPDwn
    - twitter: http://twitter.com/SoulStarsGaming
    - email: mailto:anin.gamingmanager@gmail.com
    - reddit: http://www.reddit.com/user/CLASHMASTERanin
    - youtube: https://www.youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsgaming/
    - facebook: https://www.facebook.com/Soul-Stars-Gaming-101666121932381/

clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```

**Comment by smlbiobot** [comment]
@ANINDA-P-ROY You can’t use SSG as key as that’s taken by Space Station Gaming already

**Comment by smlbiobot** [comment]
Also all of your “clans” are empty. Don’t try to cheat the system

**Comment by smlbiobot** [comment]
I will allow for this instance so I can close this issue.

```yml
name: Soul Stars Gaming™
key: soulstarsgaming
color: teal
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/soul-stars.png
  description: >
    **Soul Stars Gaming™ was Founded On the 3rd Of April 2017.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small, and, we are entirely built on out HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have spoken to our opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clanmates come from all around the Globe; from *Casual To Competitive, Young To Old* and so on.


    **WE HAVE TAKEN THE OATH, TO BECOME THE FINEST & OUTSTANDING CLAN FAMILY IN CLASH ROYALE.** Join Us & *SHINE LIKE A STAR* !


    **Creator:: Gladiator, Manager:: CLASHMASTERanin**
  social:
    - discord: http://discord.gg/vdnbTVPDwn
    - twitter: http://twitter.com/SoulStarsGaming
    - email: mailto:anin.gamingmanager@gmail.com
    - reddit: http://www.reddit.com/user/CLASHMASTERanin
    - youtube: https://www.youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsgaming/
    - facebook: https://www.facebook.com/Soul-Stars-Gaming-101666121932381/

clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```
