### ISSUE TITLE
#FresherThanYou Family Update

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/family-config#404]
```yaml
name: #FresherThanYou Family
key: FTY
color: black
emblem: 
        Freeze_01
info:
  logo: https://i.imgur.com/aZMprdZ

description: >
We are a very active german Clash Royale Clan focused on clan wars.
   The main language in our chat is german.

**Loyalty, diligence and reliability are the cornerstones of the #FresherThanYou family.**
From this a whole clan family has developed from a single clan. We are a very active family that primarily focused on Clan Wars. Within the family, we use a ranking system, which distributes the members into the appropriate clans based on skill, win rate and resources. 
Our rotation system ensures the family's full potential in the right places. 
The goal is to create an internal top list that will enable our strongest and most ambitious family members to compete in the clash royale esports scene. The everyday life of the clan is clearly structured and set out in a set of rules. If you are not a loner, but a team player and want to make a difference in the CW League, apply on our Discord Server and become part of the family!

  social:
    - discord: https://discord.gg/tHMCmQG
    - twitter: https://twitter.com/FTY_CR
    - instagram: http://www.instagram.com/fresherthanyou_family
    - email: ftycommunity@gmail.com
clans:
  - name: #FresherThanYou (I)
    tag: GJ9G9R
  - name: FresherThanYou (II)
    tag: P009PY9C 
  - name: #SmarterThanYou (III)
    tag: Y0VV9YR8
  - name: SmarterThanYou (IV)
    tag: LYLC89PR
  - name: #FasterThanYou (V)
    tag: LY0VYRJV

```

**Comment by smlbiobot** [comment]
Please edit this config in the future. Your family requires special handling because it has lots of # which are auto-removed in YML.

```yml
name: "#FresherThanYou Family"
key: FTY
color: black
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/fty.png
  description: >
    We are a very active german Clash Royale Clan focused on clan wars.
       The main language in our chat is german.

    **Loyalty, diligence and reliability are the cornerstones of the #FresherThanYou family.**
    From this a whole clan family has developed from a single clan. We are a very active family that primarily focused on Clan Wars. Within the family, we use a ranking system, which distributes the members into the appropriate clans based on skill, win rate and resources.
    Our rotation system ensures the family's full potential in the right places.
    The goal is to create an internal top list that will enable our strongest and most ambitious family members to compete in the clash royale esports scene. The everyday life of the clan is clearly structured and set out in a set of rules. If you are not a loner, but a team player and want to make a difference in the CW League, apply on our Discord Server and become part of the family!

  social:
    - discord: https://discord.gg/tHMCmQG
    - twitter: https://twitter.com/FTY_CR
    - instagram: http://www.instagram.com/fresherthanyou_family
    - email: mailto:ftycommunity@gmail.com
clans:
  - name: "#FresherThanYou (I)"
    tag: GJ9G9R
  - name: FresherThanYou (II)
    tag: P009PY9C
  - name: "#SmarterThanYou (III)"
    tag: Y0VV9YR8
  - name: SmarterThanYou (IV)
    tag: LYLC89PR
  - name: "#FasterThanYou (V)"
    tag: LY0VYRJV
```
