### ISSUE TITLE
LeGeND Family Update

### ISSUE THREAD

**Issue by Link471** [RoyaleAPI/family-config#406]
This is an update to the existing family entry https://royaleapi.com/clan/family/legend/clans.

We have added a new clan and have changed our description accordingly. We also have a new website, and different email, and needed to update those. Finally, we have a new clan called Legend Prime.

```yaml
name: LeGeND Family
key: legend
color: yellow
emblem: Flame_03
info:
  logo: /static/img/brands/logo/legend.png
  description: >
    The Legend family is one of the oldest and biggest families in Clash Royale
    with our 700 members and 15 clans!
    Since creation, we as a family and individual players have grown immensely
    and continue to today.
    We believe that’s the reason why we have come so far.
    **The family is a place for everyone, as our members come from all around the world,
    from casual to competitive players, old to young,
    active to very active and so on.**
    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join the Family. Become a Legend. **
  social:
    - discord: https://discord.me/legendfamily
    - website: https://legendgaming.me/
    - twitter: https://twitter.com/TheLegendClans
    - facebook: https://www.facebook.com/LegendClans
    - instagram: https://www.instagram.com/legendclans
    - youtube: https://www.youtube.com/channel/UCU-_xxoQeJlXx1kJcH1CoBQ
    - reddit: https://www.reddit.com/user/LegendClans
    - email: mailto:board@legendgaming.me
clans: 
  - name: LeGeND Empire!
    tag: 9P2PQULQ
  - name: Dragons Eight
    tag: 29YPJYY
  - name: LeGeND Legion!
    tag: VJQ0GJ0
  - name: LeGeND Dynasty!
    tag: 99R2PQVR
  - name: LeGeND Squad!
    tag: 80CC8
  - name: LeGeND Rising!
    tag: RY9QJU2
  - name: LeGeND Titan!
    tag: 9PJYVVL2
  - name: Dragons Eight 2
    tag: Y8G9C09
  - name: LeGeND eSports!
    tag: P9GG9QQY
  - name: LeGeND Phantom!
    tag: 2CJ88808 
  - name: White Plague
    tag: J0CQ9R9
  - name: Dragons Eight 3
    tag: PRCRJYCR
  - name: LeGeND Academy!
    tag: 8QRQQ8RG
  - name: LeGeND Pride!
    tag: YLULCRQJ
  - name: LeGeND Prime!
    tag: Q0JJ2GG2
```
