### ISSUE TITLE
Bravefighters clan family

### ISSUE THREAD

**Issue by themighty182** [RoyaleAPI/family-config#407]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yml
name: Bravefighters
key: Brave
color: Black
emblem: Skull_05
info: Come and play with the Bravest. Active war clan hoping to expand.
  logo:
  description: >
Bravefighters is a new, active war clan hoping to grow and expand.


    
clans:
  - name: Bravefighters
    tag: LYCQGQUC
  - name:Elitefighters
    tag:L8CYG9CQ
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
```yml
name: Bravefighters
key: brave
color: black
emblem: Skull_05
info:
  description: >
    Come and play with the Bravest. Active war clan hoping to expand.

    Bravefighters is a new, active war clan hoping to grow and expand.
clans:
  - name: Bravefighters
    tag: LYCQGQUC
  - name: Elitefighters
    tag: L8CYG9CQ

```
