### ISSUE TITLE
[Family Update] Aktiv Family

### ISSUE THREAD

**Issue by Anton3** [RoyaleAPI/family-config#41]
```yaml
name: Aктив СНГ
key: aktiv
color: blue
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/aktiv.jpg
  description: >
    **Актив СНГ** — семейство, состоящее из 5 кланов, которые борются за топ России.
    Основной клан держит топ-20 местных и занимает верхние строчки местного рейтинга КВ.
    Клан основан 27.03.2016 и является домом для участников CCGS, CRL, нескольких команд RRL.
    Неактивные игроки проходят мимо. Только Актив, только Хардкор!
  social:
    - twitch: https://www.twitch.tv/vanco_youtube
    - youtube: https://www.youtube.com/channel/UCcSeRO05Ju8vkkuWpV9Lrmw
clans:
  - name: Актив СНГ
    tag: U0UR2L
  - name: Актив СНГ II
    tag: P29J208
  - name: Актив СНГ III
    tag: PRPJP282
  - name: Актив СНГ IV
    tag: 2V08CU8V
  - name: Актив СНГ V
    tag: 80J0R9R2
```
