### ISSUE TITLE
WinterGuard Family

### ISSUE THREAD

**Issue by WinterGuardOP** [RoyaleAPI/family-config#410]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: WinterGuard Family
key: WinterGuard
color: blue
emblem:Freeze_01
info:
  logo:
![image](https://user-images.githubusercontent.com/77805480/105403738-23c38d00-5bf7-11eb-85dc-f56b051db034.png)

  description: >
  Official WinterGuard Clan Family. Established November 2020. We offer ladder rewards for our main Clan. Competitive spirit throughout the Family
 

 social:
    - twitter: http://twitter.com/WinterguardGG
    - discord: http://discord.gg/jyWRU6sCjk
 
clans:
  - name: WinterGuard
    tag: YGU8RJVC
  - name: FlameGuard
    tag:LYRVRQLC
 
```

**Comment by WinterGuardOP** [comment]
not Shure if the logo is correct

**Comment by WinterGuardOP** [comment]
like the link is how its supposed to be. Also, how will do i edit it in the future?

**Comment by smlbiobot** [comment]
```yml
name: WinterGuard Family
key: winterguard
color: blue
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/winter-guard.png
  description: >
    Official WinterGuard Clan Family. Established November 2020. We offer ladder rewards for our main Clan. Competitive spirit throughout the Family
  social:
    - twitter: http://twitter.com/WinterguardGG
    - discord: http://discord.gg/jyWRU6sCjk

clans:
  - name: WinterGuard
    tag: YGU8RJVC
  - name: FlameGuard
    tag: LYRVRQLC
```

If you need to update in the future — use the config above, edit it and submit new issue
