### ISSUE TITLE
ComeBack

### ISSUE THREAD

**Issue by EyesTv** [RoyaleAPI/family-config#411]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: ComeBack
key: CB
color: Blue
emblem: Bolt_03
sort: trophy
info:
  logo: ![CB_logo](https://user-images.githubusercontent.com/69396421/105639545-495fc900-5e79-11eb-8803-e0ef258bcf77.png)
  description: >
    The **ComeBack** clan was created the 03/21/2018 by [big ouf](https://royaleapi.com/player/9UR9GPCQ). 
    It started out as a clan of friends, then we quickly revealed great potential across the world rankings as well as in competition. 
    After the success of the clan, other clans were created later ComeBack 2, ComeBack 3 and ComeBack 4.


  social:
   - discord: https://discord.gg/dB9pKDVVYS
   - twitter: https://twitter.com/comeback__cr/ 
       
clans:
  - name: ComeBack
    tag: LCVUYCR
  - name: ComeBack 2
    tag: 9LY2RCUQ
  - name: ComeBack 3
    tag: Y0RYYL8J 
  - name: ComeBack 4
    tag: Y2LPVVGG
```
