### ISSUE TITLE
Soul Star's Gaming, Changing Name & Few More Updates And Modifications

### ISSUE THREAD

**Issue by ANINDA-P-ROY** [RoyaleAPI/family-config#412]
Only these mentioned tags have been updated:
name, key, logo, description and social (The Reddit Link is Removed).
```yaml
name: Soul Stars E-Sports™
key: SSEsports
color: teal
emblem: Star_Shine_02
  info:
  logo: https://ibb.co/C746NCQ
  description: >
    **Soul Stars E-Sports™ was Founded On the 3rd Of April 2018.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have Spoken to our Opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clan Mates come from all around the Globe; from *Casual To Competitive* & from *Young To Old*; We all stay united with **Zero Toxicity**.


**WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE.**


**Leader/ Creator:: Gladiator, Manager/ Community Administrator:: CLASHMASTERanin**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: http://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
  clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: Clash Australia
    tag: YVURGRCV
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```

I hope that you will consider these changes as soon as possible. Thanks !

**Comment by ANINDA-P-ROY** [comment]
PLEASE DO INFORM ME IF ANYTHING IS WRONG IN THE LINE OF CODE OR YOU WANT SOMETHING EXTRA TO BE MENTIONED.

**Comment by smlbiobot** [comment]
please don’t type in caps. name and key shouldn’t have `**surrounding**` them. Instead of usnig your own text, can you just use our CONFIG:


```yml
name: Soul Stars Gaming™
key: soulstarsgaming
color: teal
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/soul-stars.png
  description: >
    **Soul Stars Gaming™ was Founded On the 3rd Of April 2017.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small, and, we are entirely built on out HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have spoken to our opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clanmates come from all around the Globe; from *Casual To Competitive, Young To Old* and so on.


    **WE HAVE TAKEN THE OATH, TO BECOME THE FINEST & OUTSTANDING CLAN FAMILY IN CLASH ROYALE.** Join Us & *SHINE LIKE A STAR* !


    **Creator:: Gladiator, Manager:: CLASHMASTERanin**
  social:
    - discord: http://discord.gg/vdnbTVPDwn
    - twitter: http://twitter.com/SoulStarsGaming
    - email: mailto:anin.gamingmanager@gmail.com
    - reddit: http://www.reddit.com/user/CLASHMASTERanin
    - youtube: https://www.youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsgaming/
    - facebook: https://www.facebook.com/Soul-Stars-Gaming-101666121932381/

clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```
we corrected a lot of your mistakes and you should use ours as starting point.

**Comment by ANINDA-P-ROY** [comment]
https://ibb.co/C746NCQ

**Comment by ANINDA-P-ROY** [comment]
Is "SSE" tag used by ANYONE? Please do inform me.

**Comment by smlbiobot** [comment]
@ANINDA-P-ROY no, you can use SSE

**Comment by smlbiobot** [comment]
Hey please don’t edit old comments and assume that I will see them. WHAT EXACTLY IS DIFFERENT NOW?

**Comment by smlbiobot** [comment]
please just post your latest config. I can’t read your mind. You now have 3 different configs in this thread

**Comment by ANINDA-P-ROY** [comment]
Okay sir.

**Comment by ANINDA-P-ROY** [comment]
I have written the entire issue once again and have mentioned the tags that have been modified. Please contact me any other issues @smlbiobot . Thanks !

**Comment by smlbiobot** [comment]
can you POST the config as a NEW COMMENT?

**Comment by smlbiobot** [comment]
you can’t have TM in keys. they must be all lower case alphanumeric characters

**Comment by ANINDA-P-ROY** [comment]
Only these mentioned tags have been updated:
name, key, logo, description, social (The Reddit Link is Removed) & clans
```yaml
name: Soul Stars E-Sports™
key: SSEsports
color: teal
emblem: Star_Shine_02
  info:
  logo: https://ibb.co/C746NCQ
  description: >
    **Soul Stars E-Sports™ was Founded On the 3rd Of April 2018.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have Spoken to our Opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clan Mates come from all around the Globe; from *Casual To Competitive* & from *Young To Old*; We all stay united with **Zero Toxicity**.


**WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE.**


**Leader/ Creator:: Gladiator, Manager/ Community Administrator:: CLASHMASTERanin**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: http://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
  clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: Clash Australia
    tag: YVURGRCV
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```

**Comment by smlbiobot** [comment]
please in the future use this:

```yml
name: Soul Stars E-Sports™
key: SSEsports
color: teal
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/soul-stars.png
  description: >
    **Soul Stars E-Sports™ was Founded On the 3rd Of April 2018.** We decided to Open An Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION AND FRIENDSHIP.** Since then, our performances have Spoken to our Opponents in the Arena and thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clan Mates come from all around the Globe; from *Casual To Competitive* & from *Young To Old*; We all stay united with **Zero Toxicity**.


    **WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE.**


    **Leader/ Creator:: Gladiator, Manager/ Community Administrator:: CLASHMASTERanin**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: http://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: Clash Australia
    tag: YVURGRCV
  - name: SSG NIGHTWOLF®
    tag: QLY00PVC
  - name: SSG EYE EAGLES®
    tag: YU8PPOV8
  - name: SSG FLY FAIRY
    tag: LQ8J9Y0J
```

spacing is wrong
