### ISSUE TITLE
TheDTSS Clan Family (Update)

### ISSUE THREAD

**Issue by CookieGamer1** [RoyaleAPI/family-config#416]
Just a new issue in order to update and add more clans to our clan family and also update a few things. Also first time updating so I have a quick question: what would I need to include into the issue (e.g. Do I still need the social links if I'm not updating them?).

Edit (February 7th): Added TheDTSS Third clan that we were planning to use. Just to make it so I don't need to update it again so soon in the future.

```yaml
name: TheDTSS Clan Family
key: TheDTSS
color: blue
emblem: Coin_03
info: 
  logo: https://cdn.royaleapi.com/static/img/brands/logo/thedtss.png?t=7590867bc
  description: >
    TheDTSS is a fun and friendly environment of active and skilled Clash Royale players. Officially started in November of 2020, the clan family is a steadily growing and positive place for anyone who enjoys playing the game. We have a great selection of clans and also have a few notable players. Dedicated to helping out everyone and leaving no one behind, we pride ourselves on making sure every member is satisfied even though we may not be the best! Be selfless and humble: that is TheDTSS way!
    
    
clans:
  - name: TheDTSS
    tag: LL8P0GJY
  - name: TheDTSS Second
    tag: LPL9QPJU
  - name: TheDTSS Third
    tag: YC9YLRC9
  - name: Ghost House
    tag: YJGL92VU
  - name: Budski
    tag: YJPCJ9QQ
  - name: Old Trafford
    tag: 2JQCLPQ
  - name: TheSwishies
    tag: YGU0JCGU
```
