### ISSUE TITLE
Olympus Royale Family

### ISSUE THREAD

**Issue by xKardio** [RoyaleAPI/family-config#419]
```yaml
name: Olympus Royale Family
key: olympusroyale
color: teal
emblem: Tower_01
info:
  logo: 
  description: >
    The **Olympus Royale Family** is a ESP/ENG speaking family focused on **improving our gameplay** by **constant sparring sessions** and **game analysis** by coaches, We have our own competitive team representing our family in prestigious competitive leagues.

 social:
    - website: https://royalefamily.wixsite.com/olympusroyale
    - twitter: https://twitter.com/OlympusRoyaleCR
    - instagram: https://www.instagram.com/olympusroyalecr
    - discord: https://discord.com/N3sysXN

clans:
  - name: Chess Royale
    tag: YY8JR0G2
  - name: Lab Royale
    tag: YQGG0LV2
  - name: Academy Royale
    tag: YQR0YRQ8
  - name: Phoenix Royale
    tag: LQQC8V9Y
    
   ```
