### ISSUE TITLE
Swedish Wolves Clan Family

### ISSUE THREAD

**Issue by Darkleonard** [RoyaleAPI/family-config#42]
```yaml
name: Swedish Wolves
key: swedish
color: blue
emblem: flag_d_03
sort: trophy
info:
  logo: 
  description: >
    **Welcome to the Swedish Wolves family.**
If you want to become part of this family, you need to speak Swedish.
If you are, feel free to request to join any of the clans!
If you want your clan to join our clan family, contact us on our Discord server.
We require your clan to speak Swedish and we'd like it to have a name related to our current ones.
Enjoy your stay at the Swedish Wolves family!
  social:
    - discord: https://discord.gg/FFXMXA8

clans:
  - name: Swedish Wolves
    tag: 8RRJL2YY
  - name: Svenska Valpar
    tag: Y0Q20VRC
  - name: Swedish Puppies
    tag: PYLVVC29```

**Comment by smlbiobot** [comment]
- for multi-line tests you need to indent more

```yml
name: Swedish Wolves
key: swedish
color: blue
emblem: flag_d_03
sort: trophy
info:
  logo:
  description: >
    **Welcome to the Swedish Wolves family.**
    If you want to become part of this family, you need to speak Swedish.
    If you are, feel free to request to join any of the clans!
    If you want your clan to join our clan family, contact us on our Discord server.
    We require your clan to speak Swedish and we'd like it to have a name related to our current ones.
    Enjoy your stay at the Swedish Wolves family!
  social:
    - discord: https://discord.gg/FFXMXA8

clans:
  - name: Swedish Wolves
    tag: 8RRJL2YY
  - name: Svenska Valpar
    tag: Y0Q20VRC
  - name: Swedish Puppies
    tag: PYLVVC29
```
