### ISSUE TITLE
Familia Death Warrior

### ISSUE THREAD

**Issue by DWIDestructor** [RoyaleAPI/family-config#421]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Familia Death Warrior
key: deathwarrior
color: red
emblem: Skull_03
info: 
  logo: 
![DEATH_WARRIOR](https://user-images.githubusercontent.com/78897442/107609332-9dee9c80-6c0c-11eb-8caa-5693373717b2.png)

  description: 
Death Warrior es una familia formada por jugadores casuales y fieles. El clan principal ©® Death Warrior se mantiene vigente en el top ladder local peruano. Recientemente se ha creado un equipo competitivo 'Death Warrior', el cuál participará en las diferentes ligas.

    
  social:
    - twitter: https://twitter.com/DeathWarriorCR?s=09
    - facebook: https://www.facebook.com/1989530294693184/
    - youtube: https://www.facebook.com/Painted102/
    - discord: https://discord.gg/xBJgCzYG
    
clans:
  - name: ©®Death Warrior
    tag: 899LGYVJ
  - name: ¡FutureShadows!
    tag: 8LVCP9Y8
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/deathwarrior

**Comment by smlbiobot** [comment]
```yml
name: Familia Death Warrior
key: deathwarrior
color: red
emblem: Skull_03
info:
  logo: /static/img/brands/logo/death-warrior.png
  description: >
    Death Warrior es una familia formada por jugadores casuales y fieles. El clan principal ©® Death Warrior se mantiene vigente en el top ladder local peruano. Recientemente se ha creado un equipo competitivo 'Death Warrior', el cuál participará en las diferentes ligas.


  social:
    - twitter: https://twitter.com/DeathWarriorCR?s=09
    - facebook: https://www.facebook.com/1989530294693184/
    - youtube: https://www.facebook.com/Painted102/
    - discord: https://discord.gg/xBJgCzYG

clans:
  - name: ©®Death Warrior
    tag: 899LGYVJ
  - name: ¡FutureShadows!
    tag: 8LVCP9Y8
```
