### ISSUE TITLE
PEKKA's Playhouse

### ISSUE THREAD

**Issue by jmarino153** [RoyaleAPI/family-config#422]
```yaml
name: PEKKA's Playhouse
key: pekka
color: purple
emblem: A_Char_Pekka_02
info:
  logo: https://ibb.co/SNPy3K3
  description: >
    PEKKA Players Unite! **PEKKA's Playhouse** is the best discord server for anyone interested in learning PEKKA Bridgespam. We have PEKKA Coaches, matchup guides, and Bi-Weekly tournaments, and a clan for PEKKA players or anyone who wants to join our community. We are also the 
  social:
    - twitter: https://twitter.com/PEKKA_CRL
    - discord: https://discord.gg/kCFKAnC
clans:
  - name: ClashHeads
    tag: YYJU
  - name: ThrashHeads
    tag: Q80GRVYP

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/pekka

**Comment by smlbiobot** [comment]
```yml
name: PEKKA's Playhouse
key: pekka
color: purple
emblem: A_Char_Pekka_02
info:
  logo: /static/img/brands/logo/pekkas-playhouse.png
  description: >
    PEKKA Players Unite! **PEKKA's Playhouse** is the best discord server for anyone interested in learning PEKKA Bridgespam. We have PEKKA Coaches, matchup guides, and Bi-Weekly tournaments, and a clan for PEKKA players or anyone who wants to join our community. We are also the
  social:
    - twitter: https://twitter.com/PEKKA_CRL
    - discord: https://discord.gg/kCFKAnC
clans:
  - name: ClashHeads
    tag: YYJU
  - name: ThrashHeads
    tag: Q80GRVYP
```
