### ISSUE TITLE
Afonsinhos Family

### ISSUE THREAD

**Issue by Narcotico** [RoyaleAPI/family-config#423]
```yaml
name: Afonsinhos Clan Family
key: Afonsinhos
color: blue
emblem: Skull_01
info:
  logo: https://i.ibb.co/KzKHzds/logo-transparent.png
  description: >
     The **Afonsinhos Clan Family*** was born in 2016 with **Afonsinhos** clan.
    Afonsinhos is a top portuguese war clan, finishing top 10 at Clan Wars 1.
    In 2021 we decided to expand our clan by adding **Sanchinhos**, a new born clan, to our family.
    Everyone shares the same goal: Improve our individual skills together and the clan position 
    on different leaderboards.
    If you are daily active and you think you can help us improve our clan on wars, join us now!
  social:
    - discord: https://discord.gg/mt3usZU
clans:
  - name: Afonsinhos
    tag: 2PRL2RV8
  - name: Sanchinhos
    tag: LQC8999Q
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/alfonsinhos

**Comment by smlbiobot** [comment]
```yml
name: Afonsinhos Clan Family
key: afonsinhos
color: blue
emblem: Skull_01
info:
  logo: /static/img/brands/logo/afonsinhos.png
  description: >
    The **Afonsinhos Clan Family*** was born in 2016 with **Afonsinhos** clan.
    Afonsinhos is a top portuguese war clan, finishing top 10 at Clan Wars 1.
    In 2021 we decided to expand our clan by adding **Sanchinhos**, a new born clan, to our family.
    Everyone shares the same goal: Improve our individual skills together and the clan position
    on different leaderboards.
    If you are daily active and you think you can help us improve our clan on wars, join us now!
  social:
    - discord: https://discord.gg/mt3usZU
clans:
  - name: Afonsinhos
    tag: 2PRL2RV8
  - name: Sanchinhos
    tag: LQC8999Q
```
