### ISSUE TITLE
"SUPERNATURAL"

### ISSUE THREAD

**Issue by mattvncg** [RoyaleAPI/family-config#426]
```yaml
name: SUPERNATURAL Clan Family
key: supernatural 
color: red
emblem: flag_k_04
 description: >
"SUPERNATURAL" è un team competitivo italiano composto da 3 clan
    
sociale :
    - telegram: https://t.me/joinchat/IcEdTJxHOTu7cUjJ

    clans:
  - name: "SUPERNATURAL"
    tag: G8YVLR 
  - name: "SUPERNATURAL"
    tag: YOUG20
  - name: "SUPERNATURAL"
    tag: 22YCVV2U 
```
