### ISSUE TITLE
Soul Stars Esports, Few Modifications !

### ISSUE THREAD

**Issue by ANINDA-P-ROY** [RoyaleAPI/family-config#428]
Modifications made in:: Key, Logo & Description and Clans.

```yml
name: Soul Stars E-Sports™
key: SSEsports
color: orange
emblem: Star_Shine_02
info:
  logo: https://ibb.co/PrQdhxY
  description: >
    **Soul Stars E-Sports™ was founded on the 3rd Of April 2018.** We decided to open an Organization, after most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have spoken to our opponents in the arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our clan mates come from all around the Globe; from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.



**WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !**


**Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin, Leader:: GLADIATOR**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: abo lhol legend
    tag: 22GVLP92
  - name: lebanese elite
    tag: 2Y0UJ82
  - name: LEB SPAMMERS⚡️ 
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: T.I.K.I.L.A
    tag: R9P2LG
  - name: zo3ran l royal
    tag: 2280LU99
  - name: The Originals
    tag: 9YYVY80L
  - name: LegendsReborn™
    tag: PQVC89CC
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Tamizh fantasy™
    tag: 2R2QJ92
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: VRMMORPG
    tag: 28VRU80Q
  - name: NePros Freeze
    tag: 9V8YY8PL
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV

```
Please give me a copy of this issue so that I can use it in future.
If you face any issue, Please contact me.

**Comment by ANINDA-P-ROY** [comment]
The clan ​name​: ​Tamizh fantasy™​
    ​tag​: ​2R2QJ92​ , is not yet added. Rest everything is fine till now.

Thanks for your hardwork. @smlbiobot

**Comment by ANINDA-P-ROY** [comment]
Modifications made in:: Logo & Description.

```yml
name: Soul Stars E-Sports™
key: SSEsports
color: orange
emblem: Star_Shine_02
info:
  logo: https://ibb.co/PrQdhxY
  description: >
    **Soul Stars E-Sports™ was Founded On the 3rd Of April 2018.** We decided to open an Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have Spoken to our Opponents in the Arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clan Mates come from all around the Globe; from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.


*We are one of the* ***Biggest Clan Families*** *inside Clash Royale with* ***40 active clans*** *on board & We are constantly* ***Growing Everyday***.


**WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !**


**Leader:: GLADIATOR, Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin**


*You can contact us with any of these social links given below(discord is preferred)*
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: abo lhol legend
    tag: 22GVLP92
  - name: lebanese elite
    tag: 2Y0UJ82
  - name: LEB SPAMMERS⚡️ 
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: T.I.K.I.L.A
    tag: R9P2LG
  - name: zo3ran l royal
    tag: 2280LU99
  - name: The Originals
    tag: 9YYVY80L
  - name: LegendsReborn™
    tag: PQVC89CC
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Tamizh fantasy™
    tag: 2R2QJ92
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: VRMMORPG
    tag: 28VRU80Q
  - name: NePros Freeze
    tag: 9V8YY8PL
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV

```
Please give me a copy of this issue so that I can use it in future.
If you face any issue, Please contact me.

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/SSEsports

**Comment by smlbiobot** [comment]
```yml
name: Soul Stars E-Sports™
key: SSEsports
color: orange
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/soul-stars.png
  description: >
    **Soul Stars E-Sports™ was Founded On the 3rd Of April 2018.** We decided to open an Organization, after Most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have Spoken to our Opponents in the Arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, our Clan Mates come from all around the Globe; from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.


    *We are one of the* ***Biggest Clan Families*** *inside Clash Royale with* ***40 active clans*** *on board & We are constantly* ***Growing Everyday***.


    **WE HAVE TAKEN THE OATH, TO BECOME THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !**


    **Leader:: GLADIATOR, Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: abo lhol legend
    tag: 22GVLP92
  - name: lebanese elite
    tag: 2Y0UJ82
  - name: LEB SPAMMERS⚡️
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: T.I.K.I.L.A
    tag: R9P2LG
  - name: zo3ran l royal
    tag: 2280LU99
  - name: The Originals
    tag: 9YYVY80L
  - name: LegendsReborn™
    tag: PQVC89CC
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: VRMMORPG
    tag: 28VRU80Q
  - name: NePros Freeze
    tag: 9V8YY8PL
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV
```

**Comment by ANINDA-P-ROY** [comment]
Can clans be sorted in war trophies?? If it can be done, Please do it and send me the latest issue copy so that I can use it in future.

Thanks

**Comment by ANINDA-P-ROY** [comment]
Please update these Modifications made in:: Key, Logo & Description and Clans.

```yml
name: Soul Stars E-Sports™
key: SSEsports
color: orange
emblem: Star_Shine_02
info:
  logo: https://ibb.co/PrQdhxY
  description: >
    **Soul Stars E-Sports™ was founded on the 3rd Of April 2018.** We decided to open an Organization, after most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have spoken to our opponents in the arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.


***WE HAVE TAKEN THE OATH, TO BECOME THE BIGGEST & THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !***


**Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin, Leader:: GLADIATOR**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: abo lhol legend
    tag: 22GVLP92
  - name: lebanese elite
    tag: 2Y0UJ82
  - name: LEB SPAMMERS⚡️ 
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: T.I.K.I.L.A
    tag: R9P2LG
  - name: zo3ran l royal
    tag: 2280LU99
  - name: The Originals
    tag: 9YYVY80L
  - name: LegendsReborn™
    tag: PQVC89CC
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Tamizh fantasy™
    tag: 2R2QJ92
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: VRMMORPG
    tag: 28VRU80Q
  - name: NePros Freeze
    tag: 9V8YY8PL
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV

```
Can clans be sorted in war trophies?? If it can be done, Please do it
Please give me a copy of this issue so that I can use it in future.
If you face any issue, Please contact me.

**Comment by smlbiobot** [comment]
please re-open issues in the future, and use my config for logo please.

**Comment by smlbiobot** [comment]
Add `sort: war_trophy` for clan war trophies sort

Here’s your updated config. Menu cannot be sorted and will always be in the order of the config, but the main page can and I’ve set it to sort by war trophies

```ymlname: Soul Stars E-Sports™
key: SSEsports
color: orange
emblem: Star_Shine_02
sort: war_trophy
info:
  logo: /static/img/brands/logo/soul-stars-esports.png
  description: >
    **Soul Stars E-Sports™ was founded on the 3rd Of April 2018.** We decided to open an Organization, after most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have spoken to our opponents in the arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.


    ***WE HAVE TAKEN THE OATH, TO BECOME THE BIGGEST & THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !***


    **Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin, Leader:: GLADIATOR**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: abo lhol legend
    tag: 22GVLP92
  - name: lebanese elite
    tag: 2Y0UJ82
  - name: LEB SPAMMERS⚡️
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: T.I.K.I.L.A
    tag: R9P2LG
  - name: zo3ran l royal
    tag: 2280LU99
  - name: The Originals
    tag: 9YYVY80L
  - name: LegendsReborn™
    tag: PQVC89CC
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Tamizh fantasy™
    tag: 2R2QJ92
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: VRMMORPG
    tag: 28VRU80Q
  - name: NePros Freeze
    tag: 9V8YY8PL
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV
```
