### ISSUE TITLE
Asian Assassins Family

### ISSUE THREAD

**Issue by LL12345CR** [RoyaleAPI/family-config#429]
name: Asian Assassins Clan Family
key: asianassassins
color: blue
emblem: flag_c_01
info: 
  logo: https://cdn.royaleapi.com/static/img/badge/silver-1/flag_c_01.png?t=32677d51c
  description: >
The Asian Assassins Clan Family is a growing family based in the United States. Established in 2021, we look towards the future as we keep improving. We welcome players who are friendly, active, and looking to have fun. So far we have two clans, but we will add more once they are all full. 
    social:
    - discord: https://discord.com/channels/816012068704616539/816012072457732147
    - twitch: https://www.twitch.tv/ll12345_gaming
    - youtube: https://www.youtube.com/channel/UCaZWkWW15Zh-TWiwlVJpAng
   clans:
  - name: Asian Assassins
    tag: L800QGGR
  - name: Asian Assassin2
    tag: LQ9LJ2QU

**Comment by smlbiobot** [comment]
```yml
name: Asian Assassins Clan Family
key: asianassassins
color: blue
emblem: flag_c_01
info:
  logo: /static/img/badge/silver-1/flag_c_01.png
  description: >
    The Asian Assassins Clan Family is a growing family based in the United States. Established in 2021, we look towards the future as we keep improving. We welcome players who are friendly, active, and looking to have fun. So far we have two clans, but we will add more once they are all full.
  social:
    - discord: https://discord.com/channels/816012068704616539/816012072457732147
    - twitch: https://www.twitch.tv/ll12345_gaming
    - youtube: https://www.youtube.com/channel/UCaZWkWW15Zh-TWiwlVJpAng
clans:
- name: Asian Assassins
  tag: L800QGGR
- name: Asian Assassin2
  tag: LQ9LJ2QU



```
https://royaleapi.com/f/asianassassins
