### ISSUE TITLE
Modification to family clan KatzClans Gaming - DELETE AND REPLACE BY THIS ISSUE 

### ISSUE THREAD

**Issue by Eriksor-KatzClans** [RoyaleAPI/family-config#430]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: HC eSports | KatzClans™
key: katzclans
color: black
emblem: Bolt_01
info:
  logo:
![Logo Gradient_Blue](https://user-images.githubusercontent.com/73300998/109879095-23c99a80-7c43-11eb-8191-b2d21d715e2c.png)
 description: >
**HARD COUNTER ESPORTS | KATZCLANS™** is an **English Speaking Gaming organization** focused on the Supercell game **Clash Royale**. We are **specialized** in developing and building **semi-pro eSports teams and competitive clans**.
  social:
    - twitter: http://twitter.com/HCesportsGG
    - discord: http://discord.gg/fzWXdWF
    - website: https://789ethan.wixsite.com/website
clans:
  - name: PhatKatz
    tag: G9LGQR
  - name: StrayKatz
    tag: LUVLQ92U 
  - name: AlleyKatz
    tag: YG8U2U8Q
```
