### ISSUE TITLE
New clan

### ISSUE THREAD

**Issue by jsagno** [RoyaleAPI/family-config#431]
```yaml
name: ARGENTINA ROYAL
key:argentinaroyal
color:purple
emblem:A_Char_Knight_01.png
info: ✅ Grupo de Whatsapp. ⭐️ Obligatorio jugar guerras ⭐️ Idioma Español
  logo: https://drive.google.com/file/d/1A8x4mdqY_DhWzDjV_uOHB9SRQ5LqSVhA/view?usp=sharing
  description: Bienvenidos a el nuevo Argentina ROYALE: *Torneos*-*Premios*-*Recompensas*-*Posibilidad de ascender* 
clans:
  - name: ARGENTINA ROYAL
    tag: 92GUGLLQ
```
