### ISSUE TITLE
Clash Royale Clan Listing

### ISSUE THREAD

**Issue by JohnTrench** [RoyaleAPI/family-config#433]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Barbs Royale
key: barbs
color: yellow
emblem: A_Char_Barbarian_03
info:
  logo: /static/img/brands/logo/barbs.jpg
  description: >
    We are an upcoming competitive clan, who are
    currently looking for talented and passionate 
    players within the Clash Royale community. We
    provide the opportunity for you to increase your
    skill level and offer a friendly community, as the
    main principles within our clan.


    
  social:
    - instagram: https://instagram.com/beneto_a
    - email: mailto: terrylongaggin@gmail.com
clans:
  - name: Barbs Royale
    tag: LP8YLPUP
  - name:
    tag:
  - name:
    tag:
```
