### ISSUE TITLE
Família Los Magnatas

### ISSUE THREAD

**Issue by Fuklaw** [RoyaleAPI/family-config#435]
```yaml
name: Família Los Magnatas
key: Los Magnatas
color: black
emblem: coin_03
info:
  logo: ![Untitled19](https://user-images.githubusercontent.com/78038208/111548405-945bd580-8772-11eb-8a93-8e9d9ecefcff.jpg)

  description: >
        Dizem que **a união faz a força** e a Família **Los Magnatas** é a prova disso.
    Fundado a 8-4-2019 o clã **Los Magnatas** alcançou a liga lendária na CW1. Com o advento da CW2 foi forjada uma aliança com o clã, que também alcançou a liga lendária na CW1, **LITERATUS**.
    Com este influxo de novos membros e o esforço, criatividade e organização da liderança os resultados estão à vista de todos, **Nr 1 em Portugal nas guerras de clãs**.
    Para podermos continuar a receber novos jogadores aceitamos novos clãs na familia **Penn State** e para os jogadores de nível mais baixo **Magnatus**. 
    O que esperamos de ti: Esforço, dedicação e respeito.
    O que te oferecemos: Bons resultados nas guerras e torneios e mais importante, **uma família**.
    
**valete frates**

    
  social:
    - discord: http://discord.gg/7p3WqQ8
    - twitch: https://www.twitch.tv/castanhoclash
    - youtube: https://www.youtube.com/channel/UCO_Utzg7xX_fUtYwA6_pqPQ
    - website: https://losmagfam.wixsite.com/losmagnatas
    - instagram: https://www.instagram.com/losmagnatasesports/
    - facebook: https://www.facebook.com/groups/literatusesports
    - twitch: https://www.twitch.tv/sirpaivalot
    - application: http://discord.gg/7p3WqQ8
clans:
  - name: Los Magnatas
    tag: PQPPPPUY
  - name: LITERATUS
    tag: 9R280VGY
  - name: Penn State
    tag: CU8JJY
  - name: Magnatus
    tag: L8CQJ2JV
```
