### ISSUE TITLE
Royal Family - New

### ISSUE THREAD

**Issue by JackClack** [RoyaleAPI/family-config#437]
```yaml
name: Royal Family
key: royal
color: black
emblem: Diamond_Star_01
info:
  logo:
  description: >
   Присоединяйтесь к Королевской Семье!
Ищем хороших людей для сотрудничества и 
дальнейшего создания целой сети 
Королевских кланов!
Наша первая академия добилась успеха в 
кратчайший срок - топ 180 Украины за месяц!
  social:
    - website: https://t.me/royal_HSU
    - email: mailto:royal.family.cl.ro@gmail.com
clans:
  - name: Royal Harmony
    tag: QUVCQ9
  - name: Royal Symphony
    tag: LQ0VYV0P
  - name: Royal Unity
    tag: YV22QG9V
```
