### ISSUE TITLE
Update to "Lotus" family.

### ISSUE THREAD

**Issue by Alpha-Jam** [RoyaleAPI/family-config#438]
```yaml
name: AU - The Lotus Family
key: lotus
color: black
emblem: Lotus_01
info: 
  logo:
  description: >
    Clans of the Lotus
  social:
    - discord: http://discord.gg/SEFMnzZyy5
clans:
  - name: Black Lotus
    tag: PCVYYYYY
  - name: White Lotus
    tag: PCOU2222
```
