### ISSUE TITLE
Center Court Family

### ISSUE THREAD

**Issue by atyStar** [RoyaleAPI/family-config#439]
```yaml
name: Center Court
key: CC
color: green
emblem: Clover_02
info:
    description: >
    Teamgeist, Respekt und eine aktive Teilnahme am Clankrieg sollten selbstverständlich sein!
    Wir sind ein CW Clan und bei uns steht die Gemeinschaft über dem einzelnen.
    Wir heißen jeden Willkommen, der bereit ist 100% für den Clan zu geben.
    Tritt der Familie bei und werdet ein Teil von Center Court.

social:
    - https://discord.gg/wZu9Z9P9JA

clans:
  - name: Center Court
    tag: 898P08VR
  - name: Center Court 2
    tag: LV8GYP0U
```

**Comment by smlbiobot** [comment]
```yml
name: Center Court
key: CC
color: green
emblem: Clover_02
info:
  description: >
    Teamgeist, Respekt und eine aktive Teilnahme am Clankrieg sollten selbstverständlich sein!
    Wir sind ein CW Clan und bei uns steht die Gemeinschaft über dem einzelnen.
    Wir heißen jeden Willkommen, der bereit ist 100% für den Clan zu geben.
    Tritt der Familie bei und werdet ein Teil von Center Court.

  social:
    - discord: https://discord.gg/wZu9Z9P9JA

clans:
  - name: Center Court
    tag: 898P08VR
  - name: Center Court 2
    tag: LV8GYP0U
```
