### ISSUE TITLE
CR小隊

### ISSUE THREAD

**Issue by crlittleteam** [RoyaleAPI/family-config#44]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: CR小隊
key: crlittleteam
color: purple
emblem: Crown_03
info: 
  logo: https://royaleapi.com/static/img/badge/legendary/Crown_03.png?t=1533013025.8310428
  description: >
    香港業餘實力公會 超乎你想像的技術型訓練牌組 實力人士集中地 定期discord 100石牌組教學 每月定期有的直播友誼賽 專業團隊監察clan war訓練 想進步既必選公會 聯絡telegram dlam0823申請入會
clans:
  - name: CR小隊
    tag: PY9PR822
  - name: CR小分隊
    tag: P9GJ2R8P
```
