### ISSUE TITLE
"SUPERNATURAL" Family

### ISSUE THREAD

**Issue by mattvncg** [RoyaleAPI/family-config#440]
```yaml
name: "SUPERNATURAL"
key: spn
color: black
emblem: flag_k_04
 description: >
"SUPERNATURAL" è uno dei migliori team competitivi italiani composto da 3 clan. La famiglia è stata fondata da Pennywise nel Febbraio 2016 e dopo 5 anni siamo sempre più uniti e in espansione. I 3 clan stabili nella Top 100 italiana, scalano sempre di più la classifica, arrivando col primo clan fino alla Top 3 Ita. 

    social:
    - telegram: https://t.me/MattVncg

    clans:
  - name: "SUPERNATURAL"
    tag: G8YVLR 
  - name: "SUPERNATURAL" 2
    tag: YOUG20
  - name: "SUPERNATURAL" 3
    tag: 22YCVV2U 
```

**Comment by smlbiobot** [comment]
what is changed?

**Comment by smlbiobot** [comment]
please edit this config in the future. Because your name contains all these quotes, they need to be escaped properly:

```yml
name: '"SUPERNATURAL"'
key: spn
color: black
emblem: flag_k_04
info:
  description: >
    "SUPERNATURAL" è uno dei migliori team competitivi italiani composto da 3 clan. La famiglia è stata fondata da Pennywise nel Febbraio 2016 e dopo 5 anni siamo sempre più uniti e in espansione. I 3 clan stabili nella Top 100 italiana, scalano sempre di più la classifica, arrivando col primo clan fino alla Top 3 Ita.


  social:
    - telegram: https://t.me/MattVncg

clans:
  - name: '"SUPERNATURAL"'
    tag: G8YVLR
  - name: '"SUPERNATURAL"'
    tag: YOUG20
  - name: '"SUPERNATURAL"'
    tag: 22YCVV2U
```

**Comment by mattvncg** [comment]
The name of the family. It's "SUPERNATURAL" Family.The link of telegram is wrong and add the number of other clan "SUPERNATURAL" 2 and "SUPERNATURAL" 3. Please.Il 23 Mar 2021 17:38, SML ***@***.***> ha scritto:
what is changed?

**Comment by smlbiobot** [comment]
ok

**Comment by smlbiobot** [comment]
then use this:

```yml
name: '"SUPERNATURAL"'
key: spn
color: black
emblem: flag_k_04
info:
  description: >
    "SUPERNATURAL" è uno dei migliori team competitivi italiani composto da 3 clan. La famiglia è stata fondata da Pennywise nel Febbraio 2016 e dopo 5 anni siamo sempre più uniti e in espansione. I 3 clan stabili nella Top 100 italiana, scalano sempre di più la classifica, arrivando col primo clan fino alla Top 3 Ita.


  social:
    - telegram: https://t.me/MattVncg

clans:
  - name: '"SUPERNATURAL"'
    tag: G8YVLR
  - name: '"SUPERNATURAL" 2'
    tag: YOUG20
  - name: '"SUPERNATURAL" 3'
    tag: 22YCVV2U
```

**Comment by smlbiobot** [comment]
just note that even though we can update the clan name as you wrote them in the menu, it will still show up as three `"SUPERNATURAL"` clans on the main page because we can’t change the clan names in-game and we would only display the names used in the game.

**Comment by smlbiobot** [comment]
also your clan tag for 2 is wrong so this one is corrected:

```yml
name: '"SUPERNATURAL"'
key: spn
color: black
emblem: flag_k_04
info:
  description: >
    "SUPERNATURAL" è uno dei migliori team competitivi italiani composto da 3 clan. La famiglia è stata fondata da Pennywise nel Febbraio 2016 e dopo 5 anni siamo sempre più uniti e in espansione. I 3 clan stabili nella Top 100 italiana, scalano sempre di più la classifica, arrivando col primo clan fino alla Top 3 Ita.


  social:
    - telegram: https://t.me/MattVncg

clans:
  - name: '"SUPERNATURAL"'
    tag: G8YVLR
  - name: '"SUPERNATURAL" 2'
    tag: Y0UG20
  - name: '"SUPERNATURAL" 3'
    tag: 22YCVV2U
```
