### ISSUE TITLE
Warriors Faction

### ISSUE THREAD

**Issue by SHoTS619** [RoyaleAPI/family-config#441]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Warriors Faction
key: warriorsfaction 
color: red
emblem: sword_04
info:
logo:https://cdn.discordapp.com/icons/379736679784775681/6f7635ea1457f6c287d292590b004583.png)
  description: >
   **Gladiators** was created on June 26th, 2017. Clan Wars 1: Veteran Trophies 29,916. Clan Wars 2: Sights are aimed at being top clan of the global war leaderboards. Our mission is to provide an environment based on communication, transparency and accountability. Where respect is given, trust is earned and awareness is the greatest agent of change.  

    Add new line with 2 line breaks as above.
  social:
discord: https://Discord.gg/H3BwnX3
clans:
  - name: gladiators
    tag: 2RC8UCR8
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: Ready Reserves
    tag: L9RGU90V
  - name: BATTLE HEALER
    tag: PCJ0Q802
```
