### ISSUE TITLE
Czech alliance

### ISSUE THREAD

**Issue by cenekp74** [RoyaleAPI/family-config#442]
```
name: Czech alliance
key: czalliance
color: red
emblem: A_Char_Hammer_02
info:
  logo: https://i.ibb.co/8DPnmzt/726742754272739338.png
  description: >
    Hi, welcome to the Czech alliance
                We have 3 clans - Czech lords
                                - Czech Beasts
                                - Czech Eagles
        Czech Lords
            We are active, 1 year+ old clan, Requirement trophies - 4000+
            Rules: Donate cards, Be active in CW, 5 days off = kick
        Czech Beats
            We are clan that is searching for new active players on any level.
            Rules: 7 days off kick, 
        Czech Eagles
            Newest clan, we are searching for players on any level
            Rules: 10 days off kick 
  social:
    - discord: https://discord.gg/qeFyBFnh
    - website: https://www.deckshop.pro/spy/clan/LVVJGJRG
clans:
  - name: Czech Lords
    tag: LVVJGJRG
  - name: Czech Beasts
    tag: YRP2QGCP
  - name: Czech Eagles
    tag: YV2Q8GG9
```

**Comment by smlbiobot** [comment]
You can’t format text like that. This is the best I can do for you:

```yml
name: Czech alliance
key: czalliance
color: red
emblem: A_Char_Hammer_02
info:
  logo: /static/img/brands/logo/czech-alliance.png
  description: >
    Hi, welcome to the Czech alliance


    We have 3 clans: Czech lords, Czech Beasts, Czech Eagles


    ## Czech Lords


    - We are active, 1 year+ old clan, Requirement trophies - 4000+

    - Rules: Donate cards, Be active in CW, 5 days off = kick


    ## Czech Beats


    - We are clan that is searching for new active players on any level.

    - Rules: 7 days off kick


    ## Czech Eagles


    - Newest clan, we are searching for players on any level
    
    - Rules: 10 days off kick
  social:
    - discord: https://discord.gg/qeFyBFnh
    - website: https://www.deckshop.pro/spy/clan/LVVJGJRG
clans:
  - name: Czech Lords
    tag: LVVJGJRG
  - name: Czech Beasts
    tag: YRP2QGCP
  - name: Czech Eagles
    tag: YV2Q8GG9
```
