### ISSUE TITLE
Fury UA Family

### ISSUE THREAD

**Issue by kostyan190** [RoyaleAPI/family-config#443]
name: Fury UA Family
key: furyua
color: red
emblem: Flame_03
info:
  https://ibb.co/KX9WGGS
  description: >
   Привет всем! Мы семья кланов Fury UA! В основном упор на КВ. Если ты активный игрок, Clash Royale часть твоей жизни, добро пожаловать к нам! Тебя ждёт лучший коллектив, победы и слава!
                У нас 5 кланов
                                - Fury UA
                                - Fury UA Light
                                - Fury UA Dynasty
                                - Fury UA academ
                                - Fury UA Dark
        Fury UA
            Активный клан, воюем, побеждаем ✌️
            Правила:отыгрывать все колоды в речной гонке, 13 уровень короля, без мата, оскорблений, адекватность)
        Fury UA Light правила такие же
        Fury UA Dynasty, Fury UAacadem открыты для всех!
        social:
  - Телеграм канал : Fury UA Family
  - name: Fury UA
    tag: #8LGJC8J0
  - name: Fury UA Light
    tag: #8RYVYJLU
  - name: Fury UA Dynasty
    tag: #LLCPJ80J
  - name: Fury UA Dark
    tag: #PUL8LC0U
- name: Fury UA academ
    tag: #YRYV0CV2

**Comment by smlbiobot** [comment]
unsupported text format detected. This is the best I can do:

```yml
name: Fury UA Family
key: furyua
color: red
emblem: Flame_03
info:
  logo: /static/img/brands/logo/fury-ua.png
  description: >

    Привет всем! Мы семья кланов Fury UA! В основном упор на КВ. Если ты активный игрок, Clash Royale часть твоей жизни, добро пожаловать к нам! Тебя ждёт лучший коллектив, победы и слава!


    У нас 5 кланов


    - Fury UA

    - Fury UA Light

    - Fury UA Dynasty

    - Fury UA academ

    - Fury UA Dark

    Fury UA

        Активный клан, воюем, побеждаем ✌️

        Правила:отыгрывать все колоды в речной гонке, 13 уровень короля, без мата, оскорблений, адекватность)

    Fury UA Light правила такие же


    Fury UA Dynasty, Fury UAacadem открыты для всех!

clans:
  - name: Fury UA
    tag: 8LGJC8J0
  - name: Fury UA Light
    tag: 8RYVYJLU
  - name: Fury UA Dynasty
    tag: LLCPJ80J
  - name: Fury UA Dark
    tag: PUL8LC0U
  - name: Fury UA academ
    tag: YRYV0CV2
```
