### ISSUE TITLE
Cobras Family

### ISSUE THREAD

**Issue by KingGangesh** [RoyaleAPI/family-config#446]
name: Cobras Family
key: Cobras
color: yellow
emblem: Flame_03
info:
  logo: /static/img/brands/logo/cobras.png
  description: >
    The Cobras family is an upcoming clan with 4 clans & 135 members
    Since creation, we as a family and individual players have grown immensely
    and continue to today.
    We believe that’s the reason why we have come so far.
    **The family is a place for everyone, as our members come from all around the world,
    from casual to competitive players, old to young,
    active to very active and so on.**
    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join the Family. Become a Cobra. **

**Comment by KingGangesh** [comment]
Gold Cobras #YR98CQQL
Black Cobras #YQPC0UQG
White Cobras #YJ2YG080
Pink Cobras #YCJUC0Q9

**Comment by smlbiobot** [comment]
You must follow the YAML format and POST THE ENTIRE YAML FILE. Look at other issues if you don’t know what to do

**Comment by smlbiobot** [comment]
```yml
name: Cobras Family
key: cobras
color: yellow
emblem: Flame_03
info:
  description: >
    The Cobras family is an upcoming clan with 4 clans & 135 members
    Since creation, we as a family and individual players have grown immensely
    and continue to today.
    We believe that’s the reason why we have come so far.
    **The family is a place for everyone, as our members come from all around the world,
    from casual to competitive players, old to young,
    active to very active and so on.**
    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join the Family. Become a Cobra. **
clans:
  - name: Gold Cobras
    tag: YR98CQQL
  - name: Black Cobras
    tag: YQPC0UQG
  - name: White Cobras
    tag: YJ2YG080
  - name: Pink Cobras
    tag: YCJUC0Q9
```
