### ISSUE TITLE
Deadly Warfare

### ISSUE THREAD

**Issue by rdemmler** [RoyaleAPI/family-config#449]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Deadly Warfare
key: DW
color: red
emblem: A_Char_Bomb_02
info: 🔥 Deadly Warfare Family 🔥 
https://discord.gg/hNQhq8uHkU 
⚔️ Respekt ⚔️ Loyalität ⚔️ Aktivität ⚔️
E-Sports-Team, Discordserver und vieles mehr.
Werde ein Teil der DW Family und join uns auf Discord!


  social:
      - discord: http://discord.gg/hNQhq8uHkU 
    

clans:
  - name: Deadly Warfare
    tag: QLQCUPUL
  - name: Dark Warfare
    tag: Q2RQCG2U
  - name: Doomed Warfare
    tag: LQUQRR2Q
```

**Comment by smlbiobot** [comment]
```yml
name: Deadly Warfare
key: DW
color: red
emblem: A_Char_Bomb_02
info:
  description: >
    🔥 Deadly Warfare Family 🔥


    https://discord.gg/hNQhq8uHkU


    ⚔️ Respekt ⚔️ Loyalität ⚔️ Aktivität ⚔️


    E-Sports-Team, Discordserver und vieles mehr.
    Werde ein Teil der DW Family und join uns auf Discord!


  social:
  - discord: https://discord.gg/hNQhq8uHkU


clans:
  - name: Deadly Warfare
    tag: QLQCUPUL
  - name: Dark Warfare
    tag: Q2RQCG2U
  - name: Doomed Warfare
    tag: LQUQRR2Q
```
