### ISSUE TITLE
[Update] #FresherThanYou Family

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/family-config#45]
```yaml
name: #FresherThanYou Family
key: FTY
color: black
emblem: 
        Freeze_01
info:
  logo: https://www.dropbox.com/s/harc5ny3dfmpox3/IMG_2957.jpg?dl=0
description: >
We are a very active german Clash Royale Clan focused on clan wars.
   The main language in our chat is german.

**Loyalität, Fleiß und Zuverlässigkeit sind die Grundpfeiler der #FresherThanYou Clan Familie.** Daraus hat sich aus einem einzelnen Clan eine ganze Clan Familie entwickelt. Wir sind eine sehr aktive Familie, die sich primär auf Clan Wars fokussiert hat.
Innerhalb der Familie nutzen wir ein Rankingsystem, welches basierend auf Skill, Winrate und Kartenressourcen, die Mitglieder in die jeweiligen passenden Clans verteilt. Unser Rotationssystem ermöglicht es, das volle Potential der Familie auszuschöpfen.
Das Ziel ist eine interne Topliste zu formen, die es unseren stärksten und ehrgeizigsten Mitgliedern der Familie ermöglicht, wettbewerbsfähig in der CW Liga sich durchzusetzen.
Der Clan-Alltag ist bei uns klar strukturiert und in einem Regelwerk festgehalten.
Wenn du kein Einzelgänger, sondern ein Teamspieler bist und in der CW Liga etwas bewirken möchtest, bewirb dich auf unserem Discord Server und werde ein Teil der Familie!
  social:
    - discord: https://discord.gg/zYzDQGb
clans:
  - name: #FresherThanYou (HQ)
    tag: GJ9G9R
  - name: FresherThanYou 
    tag: P009PY9C
  - name: #SmarterThanYou
    tag: Y0VV9YR8
```

**Comment by smlbiobot** [comment]
- please quote the names if your names have non-alphabetical characters

```yml
name: "#FresherThanYou Family"
key: FTY
color: black
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/fresher-than-you.jpg
  description: >
    We are a very active german Clash Royale Clan focused on clan wars.
       The main language in our chat is german.

    **Loyalität, Fleiß und Zuverlässigkeit sind die Grundpfeiler der #FresherThanYou Clan Familie.** Daraus hat sich aus einem einzelnen Clan eine ganze Clan Familie entwickelt. Wir sind eine sehr aktive Familie, die sich primär auf Clan Wars fokussiert hat.
    Innerhalb der Familie nutzen wir ein Rankingsystem, welches basierend auf Skill, Winrate und Kartenressourcen, die Mitglieder in die jeweiligen passenden Clans verteilt. Unser Rotationssystem ermöglicht es, das volle Potential der Familie auszuschöpfen.
    Das Ziel ist eine interne Topliste zu formen, die es unseren stärksten und ehrgeizigsten Mitgliedern der Familie ermöglicht, wettbewerbsfähig in der CW Liga sich durchzusetzen.
    Der Clan-Alltag ist bei uns klar strukturiert und in einem Regelwerk festgehalten.
    Wenn du kein Einzelgänger, sondern ein Teamspieler bist und in der CW Liga etwas bewirken möchtest, bewirb dich auf unserem Discord Server und werde ein Teil der Familie!
  social:
    - discord: https://discord.gg/zYzDQGb
clans:
  - name: "#FresherThanYou (HQ)"
    tag: GJ9G9R
  - name: FresherThanYou
    tag: P009PY9C
  - name: "#SmarterThanYou"
    tag: Y0VV9YR8
```
