### ISSUE TITLE
QT Familie

### ISSUE THREAD

**Issue by matze0705** [RoyaleAPI/family-config#450]
```yaml
name: QT Clan Familie
key: QT
color: purple
emblem: flag_k_3

info:
  logo: ![QT](https://user-images.githubusercontent.com/82063780/113785612-c8099a00-9737-11eb-93c7-dcb5bd2a8b4b.jpg)

  description: >
 Die QT Familie gibt es seit 2016 und gehört zu den stärksten
 Clankriegs-Familien in Deutschland. Über 100 Mitglieder, Spaß
 am Spiel, viel Humor, große Erfolge und noch höhere Ziele. 
 Aktiv und motiviert, in guten und in schlechten Zeiten immer ein 
 Team und jeder zieht mit. Einer für alle, alle für einen.

  social:
 
clans:
  - name: QT Elite
    tag: 9JRVYQQT
  - name: Quittenturm
    tag: 9L2ORGUL
  - name: Quittentürmchen
    tag: P9UCVPUQ
```

**Comment by smlbiobot** [comment]
make sure your clan tags are correct in the future.

```yml
name: QT Clan Familie
key: QT
color: purple
emblem: flag_k_3

info:
  logo: /static/img/brands/logo/qt.png

  description: >
     Die QT Familie gibt es seit 2016 und gehört zu den stärksten
     Clankriegs-Familien in Deutschland. Über 100 Mitglieder, Spaß
     am Spiel, viel Humor, große Erfolge und noch höhere Ziele.
     Aktiv und motiviert, in guten und in schlechten Zeiten immer ein
     Team und jeder zieht mit. Einer für alle, alle für einen.


clans:
  - name: QT Elite
    tag: 9JRVYQQC
  - name: Quittenturm
    tag: 9L20RGUL
  - name: Quittentürmchen
    tag: P9UCVPUQ
```
