### ISSUE TITLE
[New Update #314] Guerrilheiros Family

### ISSUE THREAD

**Issue by Acidgirlcode** [RoyaleAPI/family-config#451]
```yaml
name: Familia Guerrilheiros
key: guerrilheiros
color: black
emblem: Skull_01.png
sort: trophy
info:
  logo: https://uploaddeimagens.com.br/imagens/Q-LoKxU
  description: >
    Bem-vindo à **Familia Guerrilheiros** é uma equipe da comunidade de jogadores de Clash Royale & Brawl Stars competindo no Brasil. fundado em 2016.

    Atualmente estamos em **12 clans no Clash Royale**, cada um com seu próprio foco: do clã de guerra bem-sucedida para jogadores exigentes e orientados para a Vitória, a clãs de guerra bem-sucedidos, mas relaxados na liga lendária, clãs absolutamente orientados para a comunidade, incluindo clans de treinamento coordenados (para iniciantes e jogadores de nível médio) e nosso sem clanwar - clã para jogadores ativos que não gostam de guerra: a paz da montanha.

    Além de **eventos de eSports**, como **torneios e eventos, com premiações de Gift card e Pass Royale**, estamos com Club no Brawl Stars, Clash Of Clans e Free Fire entre outros jogos. 

    Na **Familia Guerrilheiros**, você encontrará o canto certo. E sempre há algo acontecendo aqui. Dê uma olhada em nosso servidor **Discord**! Não fique por fora! Aproveite o jogo! =D
    
  social:
    - website: https://beacons.page/osguerrilheiros
    - discord: https://discord.gg/QUhmsvs
    - application: https://chat.whatsapp.com/FXTgqFGNSOZ4Lr7ysHxsIN
    - instagram: https://www.instagram.com/osguerrilheiros/
    - twitter: https://twitter.com/osguerrilheiros

clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
  - name: Guerrilheiros 6
    tag: YQQRY2UU
  - name: Guerrilheiros 7
    tag: YQJV0LC9
  - name: Guerrilheiros 8
    tag: YG0C208Q
  - name: Guerrilheiros 9
    tag: Q82ULJJL
  - name: Guerrilheiros 10
    tag: Q2Q9CYQG
  - name: Guerrilheiros 11
    tag: QLCJ2JJ8
  - name: Guerrilheiros 12
    tag: YJCRJPJR
```

**Comment by smlbiobot** [comment]
specify what was changed in the future, especially if the logo hasn’t changed. if the logo hasn’t changed please make sure to use this format:

```yml
name: Familia Guerrilheiros
key: guerrilheiros
color: black
emblem: Skull_01
info:
  logo: /static/img/brands/logo/guerrilheiros.png
  description: >
    Bem-vindo à **Familia Guerrilheiros** é uma equipe da comunidade de jogadores de Clash Royale & Brawl Stars competindo no Brasil. fundado em 2016.


    Atualmente estamos em **12 clans no Clash Royale**, cada um com seu próprio foco: do clã de guerra bem-sucedida para jogadores exigentes e orientados para a Vitória, a clãs de guerra bem-sucedidos, mas relaxados na liga lendária, clãs absolutamente orientados para a comunidade, incluindo clans de treinamento coordenados (para iniciantes e jogadores de nível médio) e nosso sem clanwar - clã para jogadores ativos que não gostam de guerra: a paz da montanha.


    Além de **eventos de eSports**, como **torneios e eventos, com premiações de Gift card e Pass Royale**, estamos com Club no Brawl Stars, Clash Of Clans e Free Fire entre outros jogos.


    Na **Familia Guerrilheiros**, você encontrará o canto certo. E sempre há algo acontecendo aqui. Dê uma olhada em nosso servidor **Discord**! Não fique por fora! Aproveite o jogo! =D

  social:
    - website: https://beacons.page/osguerrilheiros
    - discord: https://discord.gg/QUhmsvs
    - application: https://chat.whatsapp.com/FXTgqFGNSOZ4Lr7ysHxsIN
    - instagram: https://www.instagram.com/osguerrilheiros/
    - twitter: https://twitter.com/osguerrilheiros

clans:
  - name: Guerrilheiros
    tag: PP0J8RPY
  - name: Guerrilheiros 2
    tag: Y2V9LVG8
  - name: Guerrilheiros 3
    tag: YVUURCPR
  - name: Guerrilheiros 4
    tag: YQ80YC2Y
  - name: Guerrilheiros 5
    tag: YLJ02VJV
  - name: Guerrilheiros 6
    tag: YQQRY2UU
  - name: Guerrilheiros 7
    tag: YQJV0LC9
  - name: Guerrilheiros 8
    tag: YG0C208Q
  - name: Guerrilheiros 9
    tag: Q82ULJJL
  - name: Guerrilheiros 10
    tag: Q2Q9CYQG
  - name: Guerrilheiros 11
    tag: QLCJ2JJ8
  - name: Guerrilheiros 12
    tag: YJCRJPJR
```
