### ISSUE TITLE
IKYY AR Family

### ISSUE THREAD

**Issue by Avin1732** [RoyaleAPI/family-config#456]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: IKYY AR Family
key: jawa
color: black
emblem: flag_e_02
sort: trophy
info:
  logo: https://drive.google.com/file/d/10enDGo63hlzqQ8g4xScXPA080deNgcLS/view?usp=sharing
  description: >
    ** Family Team Clash Royale from Indonesia**


    We accept players from beginner-to-high level experience who qualify (Active Donation,Daily Clan Wars).We Start by familiarizing players with the rules according to the standards of large clans.We also teach beginners by opening frequently asked questions about Clash Royale in clan conversations,open the test-assessment-suggestion deck on clan conversations. 
social:
- instagram: https://www.instagram.com/vinx177/
- facebook: https://www.facebook.com/AvinPalilingDC13/

clans:
  - name: JAWA SQUADS
    tag: 9GR9QPRJ
  - name: Indo KYY ARMY
    tag: Q8CJCCCY

```
