### ISSUE TITLE
OBEY

### ISSUE THREAD

**Issue by dafa981** [RoyaleAPI/family-config#457]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: OBEY
key: obey
color: blue
emblem: lotus_01
info:
  logo: https://cdn.discordapp.com/attachments/794567854270971974/828039251010519050/image0.jpg
  description: >
   **Willkommen bei OBEY!**
Wir bestehen aus 3 Clash Royale Clans, welche in der lokalen als auch in der globalen Rangliste vorhanden sind. Auch in der eSport Szene ist **OBEY** mit zwei erfolgreichen Teams aktiv. 
Zusätzlich sind wir auch in Spielen, wie **Clash of Clans** vertreten. 
Falls du dich der **OBEY Community** anschließen willst, join unserem Discord oder kontaktier uns auf Instagram!


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/QvF5snt
    - instagram: https://www.instagram.com/obey_cr_/
clans:
  - name: OBEY
    tag: #YJLYYQJL
  - name: OBEY 2
    tag: #YGLRUO82
  - name: OBEY 3
    tag: #YURCJQGU
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/obey

**Comment by dafa981** [comment]
Thank you <3. I won’t add hashtags in the future but why is there no emblem. I wrote “lotus_01”.

**Comment by smlbiobot** [comment]
Because emblems are CaSe SenSitIve.

I’ve fixed it for you

```yml
name: OBEY
key: obey
color: blue
emblem: Lotus_01
info:
  logo: /static/img/brands/logo/obey.png
  description: >
    **Willkommen bei OBEY!**


    Wir bestehen aus 3 Clash Royale Clans, welche in der lokalen als auch in der globalen
    Rangliste vorhanden sind. Auch in der eSport Szene ist **OBEY** mit zwei erfolgreichen
    Teams aktiv.
    Zusätzlich sind wir auch in Spielen, wie **Clash of Clans** vertreten.
    Falls du dich der **OBEY Community** anschließen willst, join unserem Discord
    oder kontaktier uns auf Instagram!
  social:
  - discord: https://discord.gg/QvF5snt
  - instagram: https://www.instagram.com/obey_cr_/
clans:
- name: OBEY
  tag: YJLYYQJL
- name: OBEY 2
  tag: YGLRU082
- name: OBEY 3
  tag: YURCJQGU

```
