### ISSUE TITLE
Devils eSports

### ISSUE THREAD

**Issue by Siriogv** [RoyaleAPI/family-config#459]
```yaml
name: Devils eSports
key: Devils
color: red
emblem: flag_k_04
sort: trophy
info:
  logo: https://dvlarena.com/gg/noclub/wp-content/uploads/sites/2/2021/03/logodevils.png
  description: >
       **Devils eSports è una community italiana di videogamers, fondata nel lontano 1998. Il progetto è attualmente fase di sviluppo ed è molto ambizioso. **
   Nel 2020 siamo approdati in Clash Royale, siamo partiti da niente ma puntiamo a tutto! Scherzi a parte, ci impegniamo seriamente a far crescere il clan e i nostri player con l'obiettivo di scalare la classifica e farci conoscere.
   Condividiamo tutti la passione per il gioco, siamo amichevoli, doniamo sempre,  cerchiamo di aiutarci a vicenda con lo stesso obiettivo: migliorare sempre le nostre capacità e divertirci!
     Unisciti alla famiglia e ricorda che: **"Quando sei all'inferno solo il diavolo potrà aiutarti **
  social:
    - website: https://www.dvlarena.com/
    - twitter: https://twitter.com/DevilsEsports98
    - instagram: https://www.instagram.com/devils_esport_official/
    - facebook: https://www.facebook.com/devilsesportsofficial
    - twitch: https://www.twitch.tv/devilsesports98
    - discord: https://discord.gg/8BMV5MHC68
    - email: mailto:info@dvlarena.com
clans:
  - name: Legio X Gemina
    tag: YU99VUPV
  - name: Legio Dilectus
    tag: YRPJY9PR
  ```

**Comment by smlbiobot** [comment]
```yml
name: Devils eSports
key: devils
color: red
emblem: flag_k_04
sort: trophy
info:
  logo: /static/img/brands/logo/devils.png
  description: >
    **Devils eSports è una community italiana di videogamers, fondata nel lontano 1998. Il progetto è attualmente fase di sviluppo ed è molto ambizioso.**


    Nel 2020 siamo approdati in Clash Royale, siamo partiti da niente ma puntiamo a tutto! Scherzi a parte, ci impegniamo seriamente a far crescere il clan e i nostri player con l'obiettivo di scalare la classifica e farci conoscere.


    Condividiamo tutti la passione per il gioco, siamo amichevoli, doniamo sempre,  cerchiamo di aiutarci a vicenda con lo stesso obiettivo: migliorare sempre le nostre capacità e divertirci!


    Unisciti alla famiglia e ricorda che: **"Quando sei all'inferno solo il diavolo potrà aiutarti"**
  social:
    - website: https://www.dvlarena.com/
    - twitter: https://twitter.com/DevilsEsports98
    - instagram: https://www.instagram.com/devils_esport_official/
    - facebook: https://www.facebook.com/devilsesportsofficial
    - twitch: https://www.twitch.tv/devilsesports98
    - discord: https://discord.gg/8BMV5MHC68
    - email: mailto:info@dvlarena.com
clans:
  - name: Legio X Gemina
    tag: YU99VUPV
  - name: Legio Dilectus
    tag: YRPJY9PR
```
