### ISSUE TITLE
Fedeltà Family

### ISSUE THREAD

**Issue by Fedelta** [RoyaleAPI/family-config#46]
```yaml
name: Fedeltà Family
key: Fedeltà
color: red
emblem: Star_Shine_03
info:
  logo: https://www.onlinelogomaker.com/applet_userdata/version2/4/9/22227788/projects/22227788.png
![Fedeltà Family](https://user-images.githubusercontent.com/49613287/56094251-8f30e480-5ed2-11e9-9886-8543c25b0e08.png)
  description: >
    The Fedeltà Family is a big group of players, in which the human component is fundamental. Our goal is to create an always bigger group of people that love the game and that respect each other, in order to create a healthy and constructive atmosphere. No matter in which of Our clan You are, Our goal is to become better and better both on clan trophies and in war trophies, through the "helping each other" system and the respect of the clan's rules. So what are You waiting, come and join Us!
  social:
clans:
  - name: Fedeltà♡
    tag: RLPCRY
  - name: Fedeltà♡ Alpha
    tag: 9CGG02RR  
  - name: Fedeltà♡ Beta
    tag: P0VL8J92
  - name: Fedeltà♡ Gamma
    tag: PVJUPGQQ
```

**Comment by smlbiobot** [comment]
-key cannot have accented characters

```yml
name: Fedeltà Family
key: Fedelta
color: red
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/fedelta.png
  description: >
    The Fedeltà Family is a big group of players, in which the human component is fundamental. Our goal is to create an always bigger group of people that love the game and that respect each other, in order to create a healthy and constructive atmosphere. No matter in which of Our clan You are, Our goal is to become better and better both on clan trophies and in war trophies, through the "helping each other" system and the respect of the clan's rules. So what are You waiting, come and join Us!
  social:
clans:
  - name: Fedeltà♡
    tag: RLPCRY
  - name: Fedeltà♡ Alpha
    tag: 9CGG02RR
  - name: Fedeltà♡ Beta
    tag: P0VL8J92
  - name: Fedeltà♡ Gamma
    tag: PVJUPGQQ
```
