### ISSUE TITLE
Némésis Quebec Clan Family - update

### ISSUE THREAD

**Issue by RagnarLothbrok77** [RoyaleAPI/family-config#463]
name:   Némésis Quebec Clan Family
--
key: nemesisquebec
color: black
emblem: flag_j_03
info:
logo:   /static/img/badge/bronze-1/flag_j_03.png
description: >
Bienvenue dans la famille Némésis Québec!
4 Clans où la guerre est Obligatoire.
Nous pouvons vous ajouter sur notre groupe Messenger sur demande.
Welcome in the Némésis Québec Clan Family !
4 Clans where war is Mandatory.
We can add you on our messenger group conversation on demand.
 
clans:
- name: Némésis Quebec
tag: YU0JV9QV
- name: Némésis Qc2
tag: YQURV2CR
- name: Némésis Qc3
tag: YLGV9LGL
- name: Némésis QcC4
tag: LQLCVQVC

**Comment by smlbiobot** [comment]
note formatting

```yml
name: Némésis Quebec Clan Family
key: nemesisquebec
color: black
emblem: flag_j_03
info:
  logo: /static/img/badge/bronze-1/flag_j_03.png
  description: >
    Bienvenue dans la famille Némésis Québec!
    4 Clans où la guerre est Obligatoire.
    Nous pouvons vous ajouter sur notre groupe Messenger sur demande.
    Welcome in the Némésis Québec Clan Family !
    4 Clans where war is Mandatory.
    We can add you on our messenger group conversation on demand.
clans:
- name: Némésis Quebec
  tag: YU0JV9QV
- name: Némésis Qc2
  tag: YQURV2CR
- name: Némésis Qc3
  tag: YLGV9LGL
- name: Némésis QcC4
  tag: LQLCVQVC
```
