### ISSUE TITLE
MultiCampeones 

### ISSUE THREAD

**Issue by fabi0M** [RoyaleAPI/family-config#465]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
   social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
```

**Comment by fabi0M** [comment]
https://github.com/RoyaleAPI/family-config/issues/465#issue-866290253

**Comment by smlbiobot** [comment]
```yml
name: MultiCampeones Family
key: MultiCampeones
color: pink
emblem: Tower_01
info:
  logo: /static/img/brands/logo/campeones.png
  description: >
      Familia y clanes recién creados

      # vamos por más
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones
    tag: YJPVV0Q2
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/MultiCampeones

**Comment by fabi0M** [comment]
Incorporar un nuevo clan a la familia 

nombre : MultiCampeones 
Clave de familia : MultiCampeones 
color : rosa 
emblema : Tower_01 
info :
   logo : /static/img/brands/logo/campeones.png 
  descripción : > 
      Familia y clanes recién creados

      # vamos por más
clanes :
  - nombre : Supercampeones 
    la etiqueta : YP99Y088 
  - Nombre : UltraCampeones 
    etiqueta : YJPVV0Q2
  - Nombre : MegaCampeones 
    etiqueta : QLJVP9QV

**Comment by fabi0M** [comment]
> nombre: MultiCampeones
> Clave de familia : MultiCampeones
> color: rosa
> emblema: Tower_01
> info:
> logo: /static/img/brands/logo/campeones.png
> descripción:>
> Familia y clanes recién creados
> 
> ```
>   # vamos por más
> ```
> 
> clanes:
> 
> * nombre: SuperCampeones 
>   Etiqueta: YP99Y088
> * nombre: UltraCampeones 
>   etiqueta: YJPVV0Q2
> * nombre: MegaCampeones 
>   etiqueta: QLJVP9QV

@smlbiobot.Esto esta correcto???

**Comment by fabi0M** [comment]
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
   social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV

**Comment by fabi0M** [comment]
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
   social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV

**Comment by fabi0M** [comment]
```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
   social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV
```

**Comment by fabi0M** [comment]
```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV
```
