### ISSUE TITLE
Campeones

### ISSUE THREAD

**Issue by fabi0M** [RoyaleAPI/family-config#466]
```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
   social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
```
