### ISSUE TITLE
LEGIONS Esports

### ISSUE THREAD

**Issue by yohanesliang** [RoyaleAPI/family-config#469]
name: LEGIONS Esports
key: legions
color: red
emblem: Skull_01
sort: trophy
info:
  logo: ![legions](https://user-images.githubusercontent.com/71421720/116663915-f2aae380-a9c1-11eb-8c87-f74928874b83.jpg)

  description: >
    **Were Are Incubus Family Clans of Clash Royale** 
	Sub clans : Succubus, Succubus 2.0, Cambions, Cambions 2.0, Cambions 3.0, Forneus
  social:
    - instagram: https://www.instagram.com/legions.esports_royale/
clans:
  - name: Incubus
    tag: 22P0R0YP
  - name: Succubus
    tag: PGQR9YQ0
  - name: Succubus 2.0
    tag: Q9L9PUG9
  - name: Cambions
    tag: LPGLRPYP
  - name: Cambions 2.0
    tag: Q0UV92G0
  - name: Cambions 3.0
    tag: YCGU0QU9
  - name: Forneus
    tag: LGURUGQ8

**Comment by smlbiobot** [comment]
```yml
name: LEGIONS Esports
key: legions
color: red
emblem: Skull_01
sort: trophy
info:
  logo: /static/img/brands/logo/legion-esports.png
  description: '
    **Were Are Incubus Family Clans of Clash Royale**


	Sub clans : Succubus, Succubus 2.0, Cambions, Cambions 2.0, Cambions 3.0, Forneus'
  social:
    - instagram: https://www.instagram.com/legions.esports_royale/
clans:
  - name: Incubus
    tag: 22P0R0YP
  - name: Succubus
    tag: PGQR9YQ0
  - name: Succubus 2.0
    tag: Q9L9PUG9
  - name: Cambions
    tag: LPGLRPYP
  - name: Cambions 2.0
    tag: Q0UV92G0
  - name: Cambions 3.0
    tag: YCGU0QU9
  - name: Forneus
    tag: LGURUGQ8

```
