### ISSUE TITLE
Delta eSports Family Clan 

### ISSUE THREAD

**Issue by THEBoosOfAll** [RoyaleAPI/family-config#47]
```yaml
name: Delta eSports
key: DeltaeSports
color: Blue
emblem: Lotus_01.png
sort: trophy
info:
  description: >
    Welcome to Delta eSports, be part of our family clan. If you are looking for a competetive clan with some banter and chill people, THEN THIS IS THE CLAN FOR YOU!!
 social:
   - discord: https://discord.gg/Hqxs4us
clans:
  - name: Delta eSports
    tag: #PRYJJCY9  
  - name: Delta Junior
    tag: #PPCUYLR2
```

**Comment by smlbiobot** [comment]
- don’t include png in emblem
- don’t use hashtags in tags
- note spacing on social

```yml
name: Delta eSports
key: DeltaeSports
color: Blue
emblem: Lotus_01
sort: trophy
info:
  description: >
    Welcome to Delta eSports, be part of our family clan. If you are looking for a competetive clan with some banter and chill people, THEN THIS IS THE CLAN FOR YOU!!
  social:
   - discord: https://discord.gg/Hqxs4us
clans:
  - name: Delta eSports
    tag: PRYJJCY9  
  - name: Delta Junior
    tag: PPCUYLR2
```
