### ISSUE TITLE
No Pants Adults Family

### ISSUE THREAD

**Issue by SeatownJay** [RoyaleAPI/family-config#470]
```yaml
name: No Pants Adults Family
key: nopants
color: blue
emblem: flag_n_04
info:
  logo: https://imgur.com/a/RHJC4KY
  description: >
    We are the **No Pants Adults Family**! We have an international membership of active **21+** adults who enjoy tasteless 
    jokes and baseless insults. We have clans **Locally Ranked** in the top 200 for serious war enthusiasts and more casual clans 
    for those that don't care about Internet Points.
    
    We also offer these super "fun" benefits
    - Free **Pass Royales** every season
    - **Tournaments** of various flavors pretty much constantly
    - **Trivia Nights, Uno games, Movie parties** and more on our Discord
    - **Candy** in our **van**!!
    
    If you're interested in joining our family, ditch your pants and visit our Discord server.
  social:
    - discord: https://discord.gg/sWV2eAY
clans:
  - name: No Pants Adults
    tag: LRV22G
  - name: SansPantsAdults
    tag: YGQ9JY9R
  - name: AntiPantsAdults
    tag: Q9U9YPC8
```
