### ISSUE TITLE
Arcadia Family

### ISSUE THREAD

**Issue by the-comp0ser** [RoyaleAPI/family-config#471]
```yaml
name: Arcadia Family
key: arcadiafamily
color: orange
emblem: Twin_Peaks_02
info:
  logo: ![Arcadia](https://user-images.githubusercontent.com/83553058/116825250-67198a00-ab5c-11eb-8b67-4800bf8f5b1c.png)
  description: >
    **[Est. 7.14.2020]** The Arcadia Family consists of two friendly, active Clash Royale clans. Arcadia is a war-focused and competitive clan, while Zenith is a casual clan in which war is encouraged but not mandatory. Please join our Discord server below to learn more about our members, clans, and requirements to join.


  social:
    - discord: https://discord.gg/4W78d95vjZ
    - youtube: https://www.youtube.com/channel/UC8WNNx7q-G9gu8HtV15MiUw
clans:
  - name: Arcadia
    tag: YPPGRYPY
  - name: Zenith
    tag: LRRLP200
```

**Comment by smlbiobot** [comment]
```yml
name: Arcadia Family
key: arcadiafamily
color: orange
emblem: Twin_Peaks_02
info:
  logo: /static/img/badge/gold-1/Twin_Peaks_02.png
  description: >
    **[Est. 7.14.2020]** The Arcadia Family consists of two friendly, active Clash Royale clans. Arcadia is a war-focused and competitive clan, while Zenith is a casual clan in which war is encouraged but not mandatory. Please join our Discord server below to learn more about our members, clans, and requirements to join.


  social:
    - discord: https://discord.gg/4W78d95vjZ
    - youtube: https://www.youtube.com/channel/UC8WNNx7q-G9gu8HtV15MiUw
clans:
  - name: Arcadia
    tag: YPPGRYPY
  - name: Zenith
    tag: LRRLP200
```
