### ISSUE TITLE
Epic Clan Family (updated)

### ISSUE THREAD

**Issue by nelly-jay** [RoyaleAPI/family-config#472]
name: -Epic- Clan Family
key: epic
color: black
emblem: Skull_03
sort: trophy
info:
description: >
Epic is family of 7 clans in New Zealand but with members
from around the world. We all share a passion for the game,
we’re a friendly bunch with a happy vibe. The Epic way is
about both casual and competitive playing styles
and we value both. Show us what you got.
clans:

name: -Epic-
tag: LGGVV
name: -Epic- Thunder
tag: 2U0QJLQR
name: -Epic- Bootcamp
tag: P8UJG9L
name: -Epic- Empire
tag: Y0Q9VLYC
name: -Epic- Adventure
tag: YYVLGQG0
name: -Epic- Victory
tag: #LVGRUUJL
name: -Epic- Legends
tag: #YVCV2G0J
…

**Comment by smlbiobot** [comment]
Can you please KEEP the spacing and format in the config. I can’t reformat it for you every time.

Update the config here:

```yml
name: -Epic- Clan Family
key: epic
color: black
emblem: Skull_03
sort: trophy
info:
  description: >
    Epic is family of 6 clans in New Zealand but with members
    from around the world. We all share a passion for the game,
    we’re a friendly bunch with a happy vibe. The Epic way is
    about both casual and competitive playing styles
    and we value both. Show us what you got.
clans:
- name: -Epic-
  tag: LGGVV
- name: -Epic- Thunder
  tag: 2U0QJLQR
- name: -Epic- Bootcamp
  tag: P8UJG9L
- name: -Epic- Empire
  tag: Y0Q9VLYC
- name: -Epic- Adventure
  tag: YYVLGQG0
- name: -Epic- Victory
  tag: LVGRUUJL
```

I can’t update this for you if you remove everything
