### ISSUE TITLE
For Soul Stars Esports. Few Modifications !

### ISSUE THREAD

**Issue by ANINDA-P-ROY** [RoyaleAPI/family-config#475]
```yml
name: Soul Stars E-Sports™
key: SSEsports
color: green
emblem: Star_Shine_02
sort: war_trophy
info:
  logo: /static/img/brands/logo/soul-stars-esports.png
  description: >
    **Soul Stars E-Sports™ was founded on the 3rd Of April 2018.** We decided to open an Organization, after most of our Experienced & Super Passionate Players wanted to expand in the Competitive Scenario of Clash Royale. **We started out very small & we are entirely built on our HARDWORK, CONSISTENCY, LOYALITY, DETERMINATION, STRONG MOTIVATION & FRIENDSHIP.** Since then, our performances have spoken to our opponents in the arena & thus; WE STAND **UNIQUE & SPECIAL** from others. **This family, is a place FOR EVERYONE**, from ***Casual To Competitive*** & from ***Young To Old***; We all stay united with ***Zero Toxicity***.


    ***WE HAVE TAKEN THE OATH, TO BECOME THE BIGGEST & THE FINEST CLAN FAMILY IN CLASH ROYALE. JOIN US & SHINE LIKE A STAR !***


    **Creator/ Manager/ Analyst/ Community Administrator:: CLASHMASTERanin, Leader:: GLADIATOR**
  social:
    - discord: https://discord.gg/VDTcUTwFxn
    - twitter: https://twitter.com/SoulStarsEsport
    - email: mailto:anin.gamingmanager@gmail.com
    - youtube: https://youtube.com/channel/UCfEtjj-l_Q_v7L_aMJfF53Q
    - instagram: https://instagram.com/soulstarsesports/
    - facebook: https://www.facebook.com/SoulStarsEsports/
clans:
  - name: LEBANESE CLAN
    tag: L8G9VY8
  - name: SSE NIGHTWOLF
    tag: QPV8P8VV
  - name: SSE EYE EAGLES
    tag: YCQ9Y8L0
  - name: SSE FLY FAIRY
    tag: YV98LLUL
  - name: ChillZonE
    tag: LCCGPC08
  - name: The Lebanese
    tag: 292YGQ2
  - name: BackBencher
    tag: 2V9028GY
  - name: Indian warriors
    tag: LGR28QG0
  - name: LEB SPAMMERS⚡️
    tag: PUG9V0GU
  - name: sparta
    tag: 28R9JU8
  - name: creeps
    tag: 20PGCQC
  - name: LEB eSports
    tag: 8VL2GGCL
  - name: zo3ran l royal
    tag: 2280LU99
  - name: NEPALESE CLAN
    tag: YQVPUQL8
  - name: Lebanese Empire
    tag: 8YGRPGLL
  - name: The Mad Kings
    tag: 2LLLCVCP
  - name: lebanon
    tag: 228J9LG
  - name: LEBANONIA™
    tag: PJ9GRP0Y
  - name: Beirut Lebanon
    tag: 29P2UGCR
  - name: Tripolis
    tag: UGGRGU
  - name: DELHI ROYALS
    tag: P0UJLCP0
  - name: INDIAN SLAYERS
    tag: PQLVP99Y
  - name: Uprising Rivals
    tag: 9LCCLRCJ
  - name: Meow
    tag: 9JR920PR
  - name: Rising Unicorns
    tag: 29V9YPU9
  - name: Indian
    tag: 9UYC8JLY
  - name: Tamizh fantasy™
    tag: 2R2QJ92
  - name: attitudekillers
    tag: LVV0RJY
  - name: BRAVE INDIANS
    tag: PQ0VQL09
  - name: INDIA
    tag: 98YVUUQ
  - name: $ YADAV $
    tag: 99Q98G0V
  - name: C.I.V.I.L WAR
    tag: 8P29UCR
  - name: $U!¢iD$ $QU@D
    tag: 299RY8CJ
  - name: Royal Knights
    tag: 89R92R0
  - name: Indian Boyz
    tag: 8V2G9P9Q
  - name: INDIAN ARMY
    tag: RG9C8Y0
  - name: Aerial SPIRITS™
    tag: PC9PLP8L
  - name: BD PreDaToRs
    tag: QQ0YCY
  - name: VIKINGS OF BD
    tag: 9YQ8R9
  - name: RED RIOT
    tag: Y0VQUCU8
  - name: Rebel
    tag: 8J29QYV0
  - name: SKY LEB
    tag: PC09J02Y
  - name: LEBANESE STARS
    tag: LQYRCC82
  - name: $ YADAV-2 $
    tag: L0PQRCPV
```
