### ISSUE TITLE
[Update] Born2Royale

### ISSUE THREAD

**Issue by danielcow17** [RoyaleAPI/family-config#476]
```yaml
name: Born2Royale Clan Family
key: born2royale
color: blue
emblem: A_Char_King_01
info:
  logo:
  description: >
    **Born2Royale** is the head of the Born2Royale Family clans, which is a part of the larger gaming organization: Born2 Gaming. Founded by brothers **Snoop King** and **Grind Erb**, our clans are consistently in the top leaderboards in North America. Our top two clans are the strongest and our other clans are there for the lower trophy rangers. See which clan works best for you and climb the clans!
  social:
    - discord: http://discord.gg/4vQusVP
    - twitter: http://twitter.com/born2esports
    - instagram: https://instagram.com/born2esports
clans:
  - name: Born2Royale
    tag: RUCGUVC
  - name: Born2Royale2
    tag: UU9V8JP
  - name: Born2Royale3
    tag: Q8LGRJYQ
```
