### ISSUE TITLE
Royal Family. Update.

### ISSUE THREAD

**Issue by JackClack** [RoyaleAPI/family-config#481]
```yaml
name: Royal Family
key: royal
color: black
emblem: Diamond_Star_01
info:
  logo: https://ibb.co/9p1dWwC
  description: >
   Присоединяйтесь к Королевской Семье!
Ищем хороших людей для сотрудничества и 
дальнейшего создания целой сети 
Королевских кланов!
  social:
    - email: mailto:royal.family.cl.ro@gmail.com
clans:
  - name: Royal Harmony
    tag: QUVCQ9
  - name: Royal Symphony
    tag: LQ0VYV0P
  - name: Royal Unity
    tag: YV22QG9V
  - name: Royal Melody
    tag: YV8Q002R
```
