### ISSUE TITLE
VJ's Puppets

### ISSUE THREAD

**Issue by benjemon** [RoyaleAPI/family-config#483]
```yaml
name: VJ's Puppets
key: vjpuppets
color: green
emblem: Flag_j_01
info:
  logo:
  description: > 
    This family of clans takes pride in reminding player VLAD the Great #8UP220VU that he is only but a worm, watching his children's futures go up in cheap smoke.  Make sure to nudge him and mock him in battle.  VLAD has shown us which is the path to greatness by not choosing it.  


clans:
  - name: High Times OG
    tag: 2U8R8GVV
  
```
