### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by JackClack** [RoyaleAPI/family-config#485]
Hello!  Could you resize the logo on the site?  I downloaded a large size, but it turned out to be small🤷‍♂️ https://royaleapi.com/clan/family/royal/clans
![7D1AD685-9A61-41CF-AE07-150CBD25B476](https://user-images.githubusercontent.com/80987182/120075576-80a1e900-c0aa-11eb-8610-6c23f7f16482.jpeg)

**Comment by smlbiobot** [comment]
All logos are resized to fit 256x256. No exceptions. If you want it “bigger” then turn it into a square.

**Comment by JackClack** [comment]
square 256x256?  After that, should I create a new config with an updated logo link?

**Comment by smlbiobot** [comment]
You can open issue or post here.

**Comment by JackClack** [comment]
```yaml
name: Royal Family
key: royal
color: black
emblem: Diamond_Star_01
info:
  logo: https://ibb.co/Jp69yXn
  description: >
   Присоединяйтесь к Королевской Семье!
Ищем хороших людей для сотрудничества и 
дальнейшего создания целой сети Королевских кланов!
  social:
    - email: mailto:royal.family.cl.ro@gmail.com
clans:
  - name: Royal Harmony
    tag: QUVCQ9
  - name: Royal Symphony
    tag: LQ0VYV0P
  - name: Royal Unity
    tag: YV22QG9V
  - name: Royal Melody
    tag: YV8Q002R
```
