### ISSUE TITLE
SILVER⭐️STARS

### ISSUE THREAD

**Issue by ThomasFierus** [RoyaleAPI/family-config#487]
```yaml
name: SILVER⭐️STARS Family
key: SILVER⭐️STARS
color: grey
 emblem: traditional_silver_03-fs8
  info:
logo: https://media.discordapp.net/attachments/760870093772816384/849608048217030686/SILVERSTARS.png
description: > Wir sind eine CLAN-FAMILIE und ein eSports-Team, bei der Treue noch mehr zählt als irgendwelche Trophäen.  Die SILVER⭐️STARS und TWIN⭐️STARS. In unseren Clans respektieren wir DICH und DEINE Entscheidung CLASH zu spielen! Unser Team begleitet Dich auf Deinem Weg und bietet Dir dafür die best mögliche Unterstützung. Komm zu uns und werde ein STAR
social:
- discord: https://DISCORD.gg/vYRqtkUAqU
- facebook: https://www.facebook.com/Silver-Stars-Clash-Royale
- instagram: https://www.instagram.com/silver_stars_clashroyale
- twitter: https://twitter.com/TwinStars
- tiktok: https://www.tiktok.com/@twinstarsofficial
- twitch: https://www.twitch.tv/twinstars_cr
clans:
- name: SILVER⭐️STARS-1
    tag: YR9U8VJL
- name: SILVER⭐️STARS-2 
   tag: YVV98PY9 
- name: SILVER⭐️STARS-3 
   tag: YQY29P2J
- name: SILVER⭐️STARS-4
    tag: YQR2VORO
- name: SILVER⭐️STARS-HL 
   tag: QGC8QQJO
- name: SILVER⭐️STARS-ML 
   tag: QPLLGPPV
- name: SILVER⭐️STARS-LL
   tag: LOOOUGY9

```
