### ISSUE TITLE
I want to refresh information from the AlmasDeFuego family

### ISSUE THREAD

**Issue by Campaner2001** [RoyaleAPI/family-config#488]
```yaml
name: AlmasDeFuego family
key: almasdefuego
color: red
emblem: Flame_01
info:
   description: >
   The AlmasDeFuego family is now a reference in the Spanish and global leaderboards as a clan with experienced and good players. As we create the clan in May 2016, we have grown since then all together. Join us and you will have a clan with great trophy marks and great results on war.
   La familia de clanes AlmasDeFuego es ahora un referente en las clasificaciones española y global siendo un clan de jugadores experimentados y hábiles. Desde que creamos el clan en Mayo de 2016, hemos ido creciendo poco a poco todos juntos. Únete y tendrás a un clan con buenos trofeos y con muy buen rendimiento en guerra.


clans:
   -name: AlmasDeFuego
   tag: GGU8QY
   -name: Almasdefuego2
   tag: P2YU8U2
   -name: Almasdefuego3
   tag: YQUJ09L0
…
```
