### ISSUE TITLE
SOLICITUD ROYAL ANARCHY

### ISSUE THREAD

**Issue by Sagh12** [RoyaleAPI/family-config#489]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Royal Anarchy
key: royal
color: violet
emblem: A_Char_King_02
info:
  logo: https://media.discordapp.net/attachments/680789230586429492/850074408809791489/REMAKE_LOGO_RA_2.png?width=840&height=473

  description: > "Más Que un Clan, Una Familia" Bienvenido a Royal Anarchy - Somos Un clan que viene trabajando desde 2018 con el único fin de agrandar nuestra familia y divertirse todos juntos. A lo largo de nuestra historia hemos logrado permanecer en el TOP 10 de Perú Constantemente RECORD: #01 Perú  #18 Mundo . ¡Respeto, Pasión y Perseverancia son los únicos requisitos para unirse! QUE LA FAMILIA SIGA CRECIENDO #RAForever

  social:
    - Twitter: https://twitter.com/RoyalAnarchyCR
    - Discord: https://discord.gg/gzqmzu4 

clans:
  - name: Royal Anarchy
    tag: 9JRCG9RG
  - name: Ink'arax Gaming
    tag: P89JQG8V
```
