### ISSUE TITLE
Silk Dynasty Clan Family

### ISSUE THREAD

**Issue by CD-398** [RoyaleAPI/family-config#49]
name: The Silk Dynasty Clan Family
key: royaleapi
color: purple
emblem: Bolt_01
info:
  description: >
    The **Silk Dynasty** is a clan family that wants to produce the best members it can and send them to the best clan, Silk Dragons.  It started off as one clan, which has now turned into five, because of the leaders.  The leaders wanted to keep their members that were good but did not have the levels required to compete in the Legendary League.  In turn, more clans were created to give them a home and to expand the community for better players.
clans:
  - name: Silk Dragons
    tag: P8QQQ9UG
  - name: Silk Tigers
    tag: P9Y0Q8QJ
  - name: Silk Samurai
    tag: P8C89C99
  - name: Silk Sharks
    tag: P2YUVJUR

**Comment by smlbiobot** [comment]
- your key is invalid. updated to silkdynasty

```yml
name: The Silk Dynasty Clan Family
key: silkdynasty
color: purple
emblem: Bolt_01
info:
  description: >
    The **Silk Dynasty** is a clan family that wants to produce the best members it can and send them to the best clan, Silk Dragons.  It started off as one clan, which has now turned into five, because of the leaders.  The leaders wanted to keep their members that were good but did not have the levels required to compete in the Legendary League.  In turn, more clans were created to give them a home and to expand the community for better players.
clans:
  - name: Silk Dragons
    tag: P8QQQ9UG
  - name: Silk Tigers
    tag: P9Y0Q8QJ
  - name: Silk Samurai
    tag: P8C89C99
  - name: Silk Sharks
    tag: P2YUVJUR
```
