### ISSUE TITLE
SG Alliance - new family

### ISSUE THREAD

**Issue by cheapmonk2003** [RoyaleAPI/family-config#490]
```yaml
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, but yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Lion Wardens
    tag: 29PQ299
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8
```
