### ISSUE TITLE
Psycho

### ISSUE THREAD

**Issue by Shaman75** [RoyaleAPI/family-config#491]
```yaml
name: Psycho
key: psycho
color: blue
emblem: flag_k_01
info: 
  logo: ![logo_Psycho](https://user-images.githubusercontent.com/73484864/120823942-39a76e00-c558-11eb-8026-d44e6d07c10c.png)

  description: >
    La famille Psycho regroupe les deux clans Clash Royale officiels de la @TEAM_PSYCHO_FR.
    Détermination, maturité, esprit d'équipe et performance.
    Go Psycho !


    - discord: https://t.co/3nMbpTwQ0M
    - twitter: https://twitter.com/TEAM_PSYCHO_FR
    - website: https://teampsycho.fr/


clans:
  - name: Psycho Clash
    tag: 9QPQR28
  - name: Psycho Knights
    tag: QRUV9CRU

```
