### ISSUE TITLE
Stars Family

### ISSUE THREAD

**Issue by LtsLotus** [RoyaleAPI/family-config#495]
```yaml
name: Stars Family
key: Star
color: Red
emblem: Traditional_Star_01
info: 
  logo:
  description: >
Stars Family este una dintre cea mai mare comunitate de Clash Royale din Romania cu peste 100 membrii si 3 clanuri! Cu totii ne aratam pasiunea pentru joc, suntem prietenosi, activi, donam, iar cu totii avem un singur obiectiv: sa devenim mai buni!
**Be like stars! always high!**
  social:
    - discord: http://discord.gg/NMVYpYK
clans:
  - name: StarAlliance RO
    tag: PUVY2PUY
  - name: StarAcademy RO
    tag: LLJV20QR
  - name: StarAcademy RO2
    tag: LQ2VPQGG
```
