### ISSUE TITLE
LaTroncoFamiglia

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#498]
```yaml
name: LaTroncoFamiglia
key: latronco
color: grey
emblem: Bamboo_03
info:
  logo: https://i.postimg.cc/L6yTBxq1/8-FA42457-B397-48-A3-BC7-E-0-AF9-A7-CD6-F01.png
  description: >
    LaTroncoFamiglia, un insieme di clan in comunicazione tra loro per divertirsi in un ambiente tranquillo puntando al primo posto in ogni guerra.
Abbiamo delle regole generali nei clan per il quieto vivere, siate persone civili, nessun comportamento infantile, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.
Comunichiamo atttaverso Telegram, entrate in uno dei clan per info.
clans:
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoradice
    tag: YV2UJ0GV
  - name: La Troncoseme
    tag: QQLVQ20V
  - name: La Troncospizio
    tag: L229VYRG
```
