### ISSUE TITLE
OKS Family of Clans Update

### ISSUE THREAD

**Issue by oksd2k** [RoyaleAPI/family-config#499]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: OKS Family of Clans
key: OKS
color: green
emblem: pine_03
info: 
  logo: https://photos.app.goo.gl/uoX3i3NuSLKL4dZx9
  description: >
    **OKS Family of Clans** prides itself in providing a positive, fun, and competitive environment for players of all levels of experience and activity. Monthly cash prize tournaments. Founded in June 2018 and still growing!


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/oksfamilyclans
    - twitch: https://www.twitch.tv/oks_familyofclans?sr=a
    - reddit: https://www.reddit.com/u/OKSFamilyOfClans?utm_medium=android_app&utm_source=share
    - youtube: https://www.youtube.com/channel/508D2K
    - instagram: https://instagram.com/oksfamilyofclans?igshid=19y4g51fpbnmr
    - application: https://url/
    - email: mailto: dmartinho24@gmail.com
clans:  
  - name: Kush Squad
    tag: 9G2LYURV
  - name: Kush2TheLimit
    tag: PQ989RC8
  - name: KushIsMyCologne
    tag: PL9V2RJQ
  - name: Clash4Kush
    tag: PRVYVCG8
  - name: 5-0!HideTheKush
    tag: YLUULLOY
  - name: OKS 6 God
    tag: YRYJYYOP
  - name: 24/7 Kush
    tag: PRY92VJY
  - name: OKS 8-Ball Kush
    tag: PCPPUCR8
  - name: OKS Cloud 9
    tag: LGYYRR88
  - name: OKS FamilyClans
    tag: LGQCRQGU
  - name: OKS Clannabis
     tag: L29YJURR
```
