### ISSUE TITLE
Add: Slovakia Royale Family

### ISSUE THREAD

**Issue by branoduris** [RoyaleAPI/family-config#5]
```yaml
name: Slovakia Royale Family
key: slovakia
color: blue
emblem: Pine_01
info:
  logo: https://cdn.countryflags.com/thumbs/slovakia/flag-round-250.png
  description: >
     Aliancia Slovenských klanov v Clash Royale, ktoré spolupracujú navzájom. Výmena informácií, diskusie a turnaje. Sme otvorená komunita klanov a radi privítame dalšie klany, ktoré chcú byť súčasťou našej skupiny.


  social:
    - discord: https://discord.gg/JEHFAqz
    - youtube: https://www.youtube.com/channel/UCk1ZX7fqhqpZiNaKMYXBDrQ
    - application: https://discord.gg/JEHFAqz
clans:
  - name: Slovakia Clan
    tag: GQ0RR
  - name: LegendárnaCrew2
    tag: 9GY8U2UG
  - name: Legendárna crew
    tag: 99RGPRU2
  - name: Angels & Demons
    tag: PQRJRLR
```
