### ISSUE TITLE
Fools Paradise Family

### ISSUE THREAD

**Issue by dekuFP** [RoyaleAPI/family-config#501]
```yaml
name: Fools Paradise Family
key: FoolsParadise
color: green
emblem: Bamboo_03
sort: trophy
info:
  logo: https://user-images.githubusercontent.com/86777064/124110099-2a88e280-da68-11eb-8876-75a7c87456a9.png
  description: >
🌴Fool‘s Paradise Familie🌴

Aktiv 🌴 Loyal 🌴 Respektvoll 🌴 E-Sport 🌴
since 21.07.2020
Werde auch du ein Teil von uns 
social:
- discord: https://discord.gg/Egh65r8x
clans:
  - name: Fool‘s Paradise
    tag: Q0U2VQQQ
  - name: Paradise Lounge
    tag: YUL8PPYQ
  - name: Fool‘s 德库尔米❤️
    tag: L0U0UJY8
  - name: ParadiseEsports
    tag: L8QYUPGY
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/FoolsParadise

**Comment by dekuFP** [comment]
HEy i wont to do some changes on the royal api Family how xan i do that?

**Comment by dekuFP** [comment]
name: Fools Paradise Family
key: FoolsParadise
color: green
emblem: Bamboo_03
sort: trophy

info:
  logo: https://user-images.githubusercontent.com/86777064/124110099-2a88e280-da68-11eb-8876-75a7c87456a9.png
  description: >
🌴Fool‘s Paradise Familie🌴
Aktiv 🌴 Loyal 🌴 Respektvoll 🌴 E-Sport 🌴
since 21.07.2020
Werde auch du ein Teil unserer Familie!

social:
- discord: https://discord.gg/3SRYrABc2t

clans:
  - name: Fool‘s Paradise
    tag: Q0U2VQQQ
  - name: Fool‘s Heaven
    tag: #LGLP0UQC 
  - name: Paradise Lounge
    tag: YUL8PPYQ
  - name: 
    tag:

**Comment by dekuFP** [comment]
```yaml
name: Fools Paradise Family
key: FoolsParadise
color: green
emblem: Bamboo_03
sort: trophy

info:
  logo: https://user-images.githubusercontent.com/86777064/124110099-2a88e280-da68-11eb-8876-75a7c87456a9.png
  description: >
🌴Fool‘s Paradise Familie🌴
Aktiv 🌴 Loyal 🌴 Respektvoll 🌴 E-Sport 🌴
since 21.07.2020
Werde auch du ein Teil unserer Familie!

social:
- discord: https://discord.gg/3SRYrABc2t

clans:
  - name: Fool‘s Paradise
    tag: Q0U2VQQQ
  - name: Fool‘s Heaven
    tag: #LGLP0UQC 
  - name: Paradise Lounge
    tag: YUL8PPYQ
  ```
