### ISSUE TITLE
Kush Royale

### ISSUE THREAD

**Issue by penchito** [RoyaleAPI/family-config#502]
```yaml
name: Kush Royale
key: Kush Royale
color: blue
emblem:skull_4
info:
  logo:
  description: >
Kush Royale is a 100% Venezuelan clan looking to be at the top.

    Add new line with 2 line breaks as above.
  social:
    - instagram: https://www.instagram.com/kushroyale1/
 

    - email: mailto: KUSHROYALEINFO@gmail.com
clans:
  - name: Kush Royale
    tag: YCURLOP 
 
```
