### ISSUE TITLE
ShenYang/familyconfig

### ISSUE THREAD

**Issue by Super77777** [RoyaleAPI/family-config#505]
```yaml
name: ShenYang
key: ShenYang
color: teal
emblem:  A_Char_Rocket_02
info: 明月满山坡，沈阳有部落
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - email: mailto:530305297@qq.com
clans:
  - name: 沈阳
    tag: 9Q9GVY
  - name:东北一家人团结一心
    tag: 9YVUJLGR
  - name:沈阳闷倒驴大联盟
    tag: YCP2UQQ2
  - name:3000family
    tag:PU0UCYU0
  - name: 短小精悍(ง •̀_•́)ง
    tag: 2LLQ2GY

```
