### ISSUE TITLE
Update Milkyway family information 

### ISSUE THREAD

**Issue by HBR8** [RoyaleAPI/family-config#51]
name: MILKYWAY
key: milkyway
color: red
track: false
emblem: Twin_Peaks_02
feature: true
info:
logo: /static/img/brands/logo/milkyway.jpg
description: >
We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
social:
- discord: https://discord.gg/JzmvHTj
clans:

name: E A R T H
tag: 9VQ8V8YC
name: J U P I T E R
tag: P829Q822
name: S A T U R N
tag: P2P9VR02
name: M A R S
tag: 9RURCVRR
name: N E P T U N E
tag: P0JJ9RVJ
name: G A N Y M E D E
tag: PGY0G8GL

**Comment by smlbiobot** [comment]
- remember to quote your configs.

```yml
name: MILKYWAY
key: milkyway
color: red
emblem: Twin_Peaks_02
info:
  logo: /static/img/brands/logo/milkyway.jpg
  description: >
    We are first and foremost a community. We prize respect and great sporting spirit amongst our members above all else. Whether your goal is competitive eSports or simply having a good time with your friends - we can accommodate you. We strive for excellence in all of our endeavors. Our members come from all walks of life, time zones, and locales. We are one big competitive family. Make Milkyway your way!
  social:
  - discord: https://discord.gg/JzmvHTj
clans:
  - name: E A R T H
    tag: 9VQ8V8YC
  - name: J U P I T E R
    tag: P829Q822
  - name: S A T U R N
    tag: P2P9VR02
  - name: M A R S
    tag: 9RURCVRR
  - name: N E P T U N E
    tag: P0JJ9RVJ
  - name: G A N Y M E D E
    tag: PGY0G8GL

```
