### ISSUE TITLE
Clash Kids Clan Family

### ISSUE THREAD

**Issue by TommyUHD** [RoyaleAPI/family-config#510]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Clash Kids Clan Family
key: clashkids
color: purple
emblem: Bolt_01
info:
  logo: /static/img/badge/silver-2/Bolt_01.png
  description: >
   The **Clash Kids Clan Family** (CKCF) is made up of competitive and active players who strive to get better at the game. We form close ties with people who join our clans and encourage them to push ladder and reach their goals. We are looking for players who donate and participate in wars. 
  social:
clans:
  - name: Clash Kids
    tag: YJ8YVGRQ
  - name: Clash Kids 2.0
    tag: LL8V0Y9U
  - name:
    tag:
```
