### ISSUE TITLE
Fallens Family

### ISSUE THREAD

**Issue by ManthanVaja25** [RoyaleAPI/family-config#511]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Fallens Family
key: fallens
color: black
emblem: Skull_01
info:
  logo: /static/img/brands/logo/fallens.png
  description: >
    Welcome to the FALLENS Family! We are a competitive clan family that focuses on War and Player Progression and eSports . We are looking for players that are War focused ! 
FALLENS Family is a indian family which created at 2017 by Straw hat luffy . 
Within 3 years our clan reached Top #40 Global clan war and Top #1 in Local clan war . We also started our eSports in 2021 named Empire eSports™ . Now we are enriched with skilled and competetive players 
We FALLEN never bow to anyone ! 
#FALLENSforever


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/bCydaqbnA9
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: FALLENS
    tag: YCV2QRJ9
  - name: FallenEmpire™
    tag: YJQUP0YJ
  - name: FALLENS2
    tag:YVY0LGR9
```
