### ISSUE TITLE
update to SG Alliance family - added 3 new clans

### ISSUE THREAD

**Issue by cheapmonk2003** [RoyaleAPI/family-config#512]
```yaml
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
sort: trophy
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Lion Wardens
    tag: 29PQ299
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: Blitz Force
    tag: RCL2QC
  - name: Blitz Lodge
    tag: 9R88Q982
```
