### ISSUE TITLE
Fallens Family

### ISSUE THREAD

**Issue by ManthanVaja25** [RoyaleAPI/family-config#513]
```yaml
name: Fallens Family
key: FALLENS
color: black
emblem: Skull_01
info:
  logo:
  description: >
    Welcome to the FALLENS Family! We are a competitive clan family that focuses on War and Player Progression and eSports . We are looking for players that are War focused ! 
FALLENS Family is a Indian family which created at 2017 by Straw hat luffy . 
Within 3 years our clan reached Top 40 Global clan war and Top 1 in Local clan war . We also started our eSports in 2021 named Empire eSports™ . Now we are enriched with skilled and competetive players 
We FALLEN never bow to anyone ! 
*FALLENSforever*

  social:
    - discord: http://discord.gg/bCydaqbnA9
  
clans:
  - name: FALLENS
    tag: YCV2QRJ9
  - name: FallenEmpire™
    tag: YJQUP0YJ
  - name: FALLENS2
    tag: YVY0LGR9
```
