### ISSUE TITLE
Rebels 叛军

### ISSUE THREAD

**Issue by Cutlie333** [RoyaleAPI/family-config#514]
```yaml
name: Rebels 叛军 Family
key: Rebels 叛军
color: yellow
emblem: flag_j_03
info: 
logo: https://user-images.githubusercontent.com/87021793/125558698-538bc990-713f-4427-995e-5210e84e33c3.jpeg
 description: Rebels were established on March 16 by a group of Singapore adults. Together with Nova SG, we have a total of 7 clans. We hosting monthly Pass Royale Tournaments, a Scrim Team and clans which regularly top in war and ladder. Join us today!


 
social
- Discord: https://discord.gg/QYdQfUZ7
- Instagram: https://www.instagram.com/rebels.sg/
- Facebook: https://www.facebook.com/sgrebels/
- YouTube: https://www.youtube.com/channel/UCaqaMl-E33dOfVlww3pjxwQ

clans:
  - name: Rebels⚡叛军一营
    tag: 9Q8Q0PUY
  - name: Nova l SG
    tag: 2QRCQVPR
  - name: Rebels⚡叛军二营
    tag: 8UP9288U
  -name: Rebels⚡叛军三营
    tag: 8UYJYQ8L
  -name: Rebels⚡叛军四营
   tag: 9RG2C0GU
  -name: Rebels⚡Academy
   tag: PJ9QL2RQ
  -name: Notval SG
   tag: QYCJPYR2
```
