### ISSUE TITLE
Updated to Family MultiCampeones ~ add 1 new clan

### ISSUE THREAD

**Issue by fabi0M** [RoyaleAPI/family-config#518]
```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: SuperCampeones
    tag: YP99Y088
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV
```

**Comment by fabi0M** [comment]
Add MegaCampeones #QLJVP9QV

**Comment by smlbiobot** [comment]
```yml
name: MultiCampeones Family
key: MultiCampeones
color: pink
emblem: Tower_01
info:
  logo: /static/img/brands/logo/campeones.png
  description: >
    Familia y clanes recién creados

    # vamos por más
clans:
- name: SuperCampeones
  tag: YP99Y088
- name: UltraCampeones
  tag: YJPVV0Q2
- name: MegaCampeones
  tag: QLJVP9QV
```
