### ISSUE TITLE
Family Team WolfPack

### ISSUE THREAD

**Issue by danielhernandss** [RoyaleAPI/family-config#52]
```yaml
nombre : Team WolfPack Clan Family
key : teamwolfpackgg 
color : black 
emblema : Twin_Peaks_01
info :
  descripción : > 
    Familia WolfPack es un grupo de clanes de México, enfocados en ladder y competitivo, nuestro clan principal se encuentra top local, clanes activos y con buenos jugadores.
Ofrecemos un buen ambiente y oportunidades para mejorar en el juego.
  sociales :
    - twitter : https://twitter.com/TeamWolfPackGG 
    - facebook : https://www.facebook.com/Team-WolfPack-574045946425606/
clans :
  - Nombre : WolfPack
    etiqueta : PP0PCJLC 
  - Nombre : WolfPack Army 
    etiqueta : PP9V0CPC 
```

**Comment by smlbiobot** [comment]
- please don’t modify the field names to another language:

```yml
name: Team WolfPack Clan Family
key: teamwolfpackgg
color: black
emblem: Twin_Peaks_01
info:
  description: >
    Familia WolfPack es un grupo de clanes de México, enfocados en ladder y competitivo, nuestro clan principal se encuentra top local, clanes activos y con buenos jugadores.
    Ofrecemos un buen ambiente y oportunidades para mejorar en el juego.
  social:
    - twitter: https://twitter.com/TeamWolfPackGG
    - facebook: https://www.facebook.com/Team-WolfPack-574045946425606/
clans:
  - name: WolfPack
    tag: PP0PCJLC
  - name: WolfPack Army
    tag: PP9V0CPC
```
