### ISSUE TITLE
Clash Family 

### ISSUE THREAD

**Issue by Tera-ClashFamily** [RoyaleAPI/family-config#520]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Clash Family
key: CF
color: purple
emblem: crown_04
info:
  logo: https://www.facebook.com/groups/148913203857438/
  description: >
    **Clash Family** is a Clash Royale community and clan family consisting of 6 clans. Our mission is to help our members learn, grow and have fun together. We offer well managed clans, seasoned leadership and a friendly online community. Our community consists of clan members, other clan families and independent players who work together to provide the best environment possible.


      social:
    - discord: http://discord.gg/pv3Y2ts
    
clans:
  - name: Clash Canada
    tag: V2U9JLY
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clash Mortals
    tag: LVLCQR2C
  - name: Clash Rebels
  - tag: LP9GRQ92
  - name: Clash Pandas
  - tag: YJJR8YRO
  - name: Clash Koalas
  - tag: L2R0RYCC


```

**Comment by smlbiobot** [comment]
don’t randomly add `-` dashes

```yml
name: Clash Family
key: CF
color: purple
emblem: Crown_04
info:
  logo: /static/img/brands/logo/clash-family.png
  description: >
    **Clash Family** is a Clash Royale community and clan family consisting of 6 clans. Our mission is to help our members learn, grow and have fun together. We offer well managed clans, seasoned leadership and a friendly online community. Our community consists of clan members, other clan families and independent players who work together to provide the best environment possible.



  social:
  - discord: https://discord.gg/pv3Y2ts
clans:
  - name: Clash Canada
    tag: V2U9JLY
  - name: Clash Legends
    tag: Q2QUQC2C
  - name: Clash Mortals
    tag: LVLCQR2C
  - name: Clash Rebels
    tag: LP9GRQ92
  - name: Clash Pandas
    tag: YJJR8YRO
  - name: Clash Koalas
    tag: L2R0RYCC

```
