### ISSUE TITLE
OpstersEmpire Needs Updated on RoyaleAPI Clan Families

### ISSUE THREAD

**Issue by OpstersEmpire** [RoyaleAPI/family-config#521]
Hello there I have written all of mine in Yaml on word. I want to send it in a word document so that it does not mess up the formatting so that you can see how it should look. 

Here is the old Config-  https://gist.github.com/smlbiobot/ef0fc6086003ec264482fe28ebc3d6a0 

The word document is an update to my old one. Thank you :)
[Opsters Empire RoyaleAPI Yaml Coding.docx](https://github.com/RoyaleAPI/family-config/files/6873263/Opsters.Empire.RoyaleAPI.Yaml.Coding.docx)

PDF if it is easier- 
[Opsters Empire RoyaleAPI Yaml Coding.pdf](https://github.com/RoyaleAPI/family-config/files/6874453/Opsters.Empire.RoyaleAPI.Yaml.Coding.pdf)

**Comment by smlbiobot** [comment]
Hey you can’t send us word docs. Yaml requires formatting that’s very specific…

**Comment by smlbiobot** [comment]
please just type it in text in the future.


```yml
name: Opsters Empire Clans Family
key: OpstersEmpire
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/opsters-empire.png
  description: >
    Opsters Empire is a large family of clans. We have clans in many games as listed below:


    - Clash Royale: Opsters, Opsters2, Opsters4, Opsters5, Opsters Dormant & Opsters Timeout

    - Brawl Stars: Opsters, Opsters2 & Opsters3

    - Clash of Clans: OpstersArmy and Opsters Dormant

    - Boom Beach: OpstersArmy

    - Call of Duty Mobile: Opsters Empire
    
    - WWE Supercard: Opsters Empire


    The Opsters Empire is a family of clans that expands out through a multitude of games. We primarily concentrate on Supercell games, these consisting currently of- Clash Royale, Brawl Stars, Clash of Clans and Boom Beach. We are also currently looking to grow in other games such as Call of Duty Mobile and WWE Supercard.


    The first ever Opsters clan came about in March 2018. This clan was created in Clash Royale and was at the time led by Black Op who is the creator of the Opsters Empire. Over time we have grown to unimaginable lengths far past what we ever expected when we first started. As we started to grow in Clash Royale with one of the people who started the Opsters Empire alongside Black Op- Spousalchip being asked to create a second clan (Opsters2) in Clash Royale. We started to look at other games that we could create clans in and as a result started to create clans in games like Brawl Stars and Call of Duty Mobile.


    **Opsters in Clash Royale has massively exceeded all original expectations with the clan not only reaching over 15,000 trophies in Clan Wars 1 and reaching #17 UK on Ladder. But also, now being at it’s best ever reaching top 5 United Kingdom in Clan Wars 2 and getting into the top 300 Global Leader boards. The only way is up for the Opsters Empire, and the clans will only keep on improving and learning as we reach new heights in the gaming industry.**


    The feeder clan to Opsters which is Opsters2 has also done very well for a feeder clan with it reaching top 100 UK in the past on Ladder and War. A lot of players from the main clan originally were members of Opsters2 as they worked their way up to the main clan proving themselves worthy and becoming loyal members of the Opsters Empire. We also have Opsters Dormant and Opsters Timeout which count as clans for members who are taking breaks and members that are leaving the game to put their accounts into to hopefully come back to our main clans in future if they ever return to the game.


    The Opsters Empire is a community of clans that anyone can join, throughout our clans we have lots of players from all around the globe. These ranging from young to old and casual to competitive.
    Our clans in games outside of Clash Royale have also been very successful with Opsters main clan in Brawl Stars just hitting top 50 United Kingdom for the first time ever! Opsters2 in Brawl Stars is a newly created clan this year and has already gotten into top 300 UK. Our clans are always looking to thrive in any game we have them in and we always want to give everything our very best.
    We have a highly active Community Discord server which we use as our main form of contact for the clans. We have over 100+ members now and accept people from all games and clans. Whether they are from Opsters clans or not does not matter as we accept everyone in our server!
    If you want to check out Opsters clan and talk to leaders and members first, we recommend joining our community Discord Server as that is the best representation of our clans and has all the tools you will need.


    **Join The #OpstersEmpire and Become Part of Greatness!**



  social:
    - discord: https://discord.gg/zsKDmq8hTa
    - instagram: https://discord.gg/zsKDmq8hTa
    - facebook: https://www.facebook.com/OpstersEmpireUK
    - twitter: https://twitter.com/OpstersE
    - reddit: https://twitter.com/OpstersE

    - email: mailto:opstersempire@gmail.com
    - application: https://forms.gle/8bLPwZ5gey3hahQc9



clans:
- name: Opsters™️
  tag: 9VRJ028J
- name: Opsters2
  tag: PLUCUJ9J
- name: The good ones
  tag: L9P02P2G
- name: Opsters Dormant
  tag: YGJJJ2LU
- name: Opsters4
  tag: PQRUQ88U
- name: Opsters5™️
  tag: L8Y0Y0V0

#    - tumblr: https://opstersempire.tumblr.com
#    - fandom wiki: https://opstersempire.fandom.com/wiki/Opsters_Empire-_Clans_Family_Wiki
#    - disboard: https://disboard.org/server/568564248926486538
```

some social links have no icons and we can’t produce them at this time. remind me to add them later

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/OpstersEmpire

**Comment by OpstersEmpire** [comment]
Hello there, thank you for updating the RoyaleApi for Opsters Empire.

Certain things were not updated that I listed on the new Yaml. Here are the
things I need updated below-

Logo: https://i.imgur.com/tFatQiG.png

clans:
- name: Opsters™️
   tag: #9VRJ028J
- name: Opsters2
   tag: #PLUCUJ9J
- name: Opsters4
   tag: #PQRUQ88U
- name: Opsters5™️
   tag: #L8Y0Y0V0
- name: Opsters Dormant
   tag: #YGJJJ2LU
- name: Opsters Timeout
   tag: #L09VLYGG

These are the things that you missed off on the new Yaml. Thank you

**Comment by OpstersEmpire** [comment]
Hello there, a follow up from my previous email. The social media links you
put Down on the RoyaleApi. The Instagram and Twitter take me to the wrong
Web pages. I have had multiple people test it and same result. When looking
at the Yaml you sent me, I see that it has been put into it incorrectly.
Please fix this issue. Thank you, also don't forget the logo and Clans that
I mentioned on the previous email that also need fixed on it :)

**Comment by smlbiobot** [comment]
The links are wrong because YOU put in the wrong links.

Don’t use Word to format YAML because you CAN’T. If you need a text editor, use https://gist.github.com

<img width="547" alt="Screen Shot 2021-07-31 at 8 49 23 PM" src="https://user-images.githubusercontent.com/25040297/127740392-b80ff474-a0e1-4f7e-b610-f3ece6098f26.png">

**Comment by smlbiobot** [comment]
your clan config is incorrect.

- do not include `#`
- do not randomly add space

I can’t update these things for you if I have to read and try to interpret what you want to say. They need to be formatted CORRECTLY.

Don’t align the `:` colons for the name/tag to make it look “pretty”

this is the correct format:

```yml
clans:
- name: Opsters™️
  tag: 9VRJ028J
- name: Opsters2
  tag: PLUCUJ9J
- name: Opsters4
  tag: PQRUQ88U
- name: Opsters5™️
  tag: L8Y0Y0V0
- name: Opsters Dormant
  tag: YGJJJ2LU
- name: Opsters Timeout
  tag: L09VLYGG
```

**Comment by OpstersEmpire** [comment]
Sorry about that, I have only just noticed that it was a fault on my part.
I will update the links asap. Please update the clans and logo in the mean
time, thank you :)

**Comment by smlbiobot** [comment]
Don’t send PDF / DOCS at all. Send TEXT. YAML is a text format. Binary formats mess everything up.

**Comment by smlbiobot** [comment]
Please update this INLINE AS IS:

```yml
name: Opsters Empire Clans Family
key: OpstersEmpire
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/opsters-empire-2.png
  description: >
    Opsters Empire is a large family of clans. We have clans in many games as listed below:


    - Clash Royale: Opsters, Opsters2, Opsters4, Opsters5, Opsters Dormant & Opsters Timeout

    - Brawl Stars: Opsters, Opsters2 & Opsters3

    - Clash of Clans: OpstersArmy and Opsters Dormant

    - Boom Beach: OpstersArmy

    - Call of Duty Mobile: Opsters Empire

    - WWE Supercard: Opsters Empire


    The Opsters Empire is a family of clans that expands out through a multitude of games. We primarily concentrate on Supercell games, these consisting currently of- Clash Royale, Brawl Stars, Clash of Clans and Boom Beach. We are also currently looking to grow in other games such as Call of Duty Mobile and WWE Supercard.


    The first ever Opsters clan came about in March 2018. This clan was created in Clash Royale and was at the time led by Black Op who is the creator of the Opsters Empire. Over time we have grown to unimaginable lengths far past what we ever expected when we first started. As we started to grow in Clash Royale with one of the people who started the Opsters Empire alongside Black Op- Spousalchip being asked to create a second clan (Opsters2) in Clash Royale. We started to look at other games that we could create clans in and as a result started to create clans in games like Brawl Stars and Call of Duty Mobile.


    **Opsters in Clash Royale has massively exceeded all original expectations with the clan not only reaching over 15,000 trophies in Clan Wars 1 and reaching #17 UK on Ladder. But also, now being at it’s best ever reaching top 5 United Kingdom in Clan Wars 2 and getting into the top 300 Global Leader boards. The only way is up for the Opsters Empire, and the clans will only keep on improving and learning as we reach new heights in the gaming industry.**


    The feeder clan to Opsters which is Opsters2 has also done very well for a feeder clan with it reaching top 100 UK in the past on Ladder and War. A lot of players from the main clan originally were members of Opsters2 as they worked their way up to the main clan proving themselves worthy and becoming loyal members of the Opsters Empire. We also have Opsters Dormant and Opsters Timeout which count as clans for members who are taking breaks and members that are leaving the game to put their accounts into to hopefully come back to our main clans in future if they ever return to the game.


    The Opsters Empire is a community of clans that anyone can join, throughout our clans we have lots of players from all around the globe. These ranging from young to old and casual to competitive.
    Our clans in games outside of Clash Royale have also been very successful with Opsters main clan in Brawl Stars just hitting top 50 United Kingdom for the first time ever! Opsters2 in Brawl Stars is a newly created clan this year and has already gotten into top 300 UK. Our clans are always looking to thrive in any game we have them in and we always want to give everything our very best.
    We have a highly active Community Discord server which we use as our main form of contact for the clans. We have over 100+ members now and accept people from all games and clans. Whether they are from Opsters clans or not does not matter as we accept everyone in our server!
    If you want to check out Opsters clan and talk to leaders and members first, we recommend joining our community Discord Server as that is the best representation of our clans and has all the tools you will need.


    **Join The #OpstersEmpire and Become Part of Greatness!**



  social:
    - discord: https://discord.gg/zsKDmq8hTa
    - instagram: https://discord.gg/zsKDmq8hTa
    - facebook: https://www.facebook.com/OpstersEmpireUK
    - twitter: https://twitter.com/OpstersE
    - reddit: https://twitter.com/OpstersE

    - email: mailto:opstersempire@gmail.com
    - application: https://forms.gle/8bLPwZ5gey3hahQc9



clans:
- name: Opsters™️
  tag: 9VRJ028J
- name: Opsters2
  tag: PLUCUJ9J
- name: Opsters4
  tag: PQRUQ88U
- name: Opsters5™️
  tag: L8Y0Y0V0
- name: Opsters Dormant
  tag: YGJJJ2LU
- name: Opsters Timeout
  tag: L09VLYGG

#    - tumblr: https://opstersempire.tumblr.com
#    - fandom wiki: https://opstersempire.fandom.com/wiki/Opsters_Empire-_Clans_Family_Wiki
#    - disboard: https://disboard.org/server/568564248926486538
```
