### ISSUE TITLE
Star Peru

### ISSUE THREAD

**Issue by REDSLINGER2005** [RoyaleAPI/family-config#522]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: STAR PERU
key: sp2021
color: rojo
emblem: Tower_02
info:
  logo: https://i.ibb.co/yXTnvG9/SP.png
  description: > Bienvenido a STAR PERU, una familia conformada en su totalidad por jugadores peruanos, aunque no cerramos las puertas a ningún otro miembro extranjero, siempre y cuando hable y/o entienda español. Con el tu tiempo y con tu apoyo se que lograremos grandes cosas, así que UNETE!!!
    Long paragraphs with markdown syntax.

    - discord: http://discord.gg/XNnERBqp
   
clans:
  - name: STAR PERU
    tag: YVPUJCQJ
  - name: STAR PERU II
    tag: QLJY8VVU
```

**Comment by smlbiobot** [comment]
```yml
name: STAR PERU
key: sp2021
color: rojo
emblem: Tower_02
info:
  logo: /static/img/brands/logo/sp.png
  description: >
    Bienvenido a STAR PERU, una familia conformada en su totalidad por jugadores peruanos, aunque no cerramos las puertas a ningún otro miembro extranjero, siempre y cuando hable y/o entienda español. Con el tu tiempo y con tu apoyo se que lograremos grandes cosas, así que UNETE!!!


  social:
    - discord: http://discord.gg/XNnERBqp

clans:
  - name: STAR PERU
    tag: YVPUJCQJ
  - name: STAR PERU II
    tag: QLJY8VVU
```
