### ISSUE TITLE
Família Los Magnatas

### ISSUE THREAD

**Issue by ELbarito** [RoyaleAPI/family-config#526]
```yaml
name: Família Los Magnatas
key: Los Magnatas
color: black
emblem: coin_03
info:
  logo: 
  ![228698548_966392260820817_3683291567339044975_n](https://user-images.githubusercontent.com/88329426/128765856-63f9e049-7b5f-4442-baea-f2a887cf2595.png)

  description: >
        Dizem que **o sucesso vem do trabalho** e a Família **Los Magnatas** é a prova disso.
    Fundado a 8-4-2019 o clã **Los Magnatas** alcançou a liga lendária na CW1. Com a chegada da CW2 o clã foi evoluíndo e a família foi crescendo com o esforço, criatividade e organização da liderança e de todos os membros que foram participando ativamente no clã. Os resultados falam por si, **Nº 1 em Portugal nas guerras de clãs**.
    Foram criadas alianças com os clãs **Penn State**, **Portugal**, e para os jogadores iniciantes **Magnatus**. 
    O que esperamos de ti: Esforço, Dedicação e Respeito.
    O que te oferecemos: Bons resultados nas guerras, torneios internos e mais importante, **uma família**.
    
    Se achas que tens *perfil* para te juntares a esta família, o que estás à espera? Entra em contacto via *discord*
 
    
  social:
    - discord: http://discord.gg/kuuqh9kTBy
    - website: https://losmagfam.wixsite.com/losmagnatas
    - instagram: https://www.instagram.com/losmagnatasesports/
  
clans:
  - name: Los Magnatas
    tag: PQPPPPUY
  - name: Penn State
    tag: CU8JJY
  - name: Portugal
    tag: 2JL2PR0R    
  - name: Magnatus
    tag: L8CQJ2JV
    ```

**Comment by ELbarito** [comment]
@smlbiobot

**Comment by smlbiobot** [comment]
no need to tag. we read everything

**Comment by smlbiobot** [comment]
edit from this in the future:

```yml
name: Família Los Magnatas
key: los-magnatas
color: black
emblem: Coin_03
info:
  logo: /static/img/brands/logo/los-magnatas-2.png
  description: >
    Dizem que **o sucesso vem do trabalho** e a Família **Los Magnatas** é a prova disso.
    Fundado a 8-4-2019 o clã **Los Magnatas**, **focado na guerra**, alcançou a liga lendária na CW1. Com a chegada da CW2 o clã foi evoluíndo e a família foi crescendo com o esforço, criatividade e organização da liderança e de todos os membros que foram participando ativamente no clã. Os resultados falam por si, **Nº 1 em Portugal nas guerras de clãs**.
    Foram criadas alianças com os clãs **Penn State**, **Portugal**, e para os jogadores iniciantes **Magnatus**.
    O que esperamos de ti: Esforço, Dedicação e Respeito.
    O que te oferecemos: Bons resultados nas guerras, torneios internos e mais importante, **uma família**.


    Se achas que tens *perfil* para te juntares a esta família, o que estás à espera? Entra em contacto via *discord*


  social:
    - discord: https://discord.gg/kuuqh9kTBy
    - website: https://losmagfam.wixsite.com/losmagnatas
    - instagram: https://www.instagram.com/losmagnatasesports/
clans:
  - name: Los Magnatas
    tag: PQPPPPUY
  - name: Penn State
    tag: CU8JJY
  - name: Portugal
    tag: 2JL2PR0R
  - name: Magnatus
    tag: L8CQJ2JV

```
