### ISSUE TITLE
Add new clan to x6tence clan family

### ISSUE THREAD

**Issue by txedo** [RoyaleAPI/family-config#527]
Please update **x6tence** clan family already created on RoyaleAPI [1] by adding the clan listed below:

```yaml
clans:
  - name: x6tence Yellow
    tag: L88VG8V2
```

Thank you.

[1] https://royaleapi.com/clan/family/x6tence/
