### ISSUE TITLE
EuroElite Family

### ISSUE THREAD

**Issue by LucaFox1** [RoyaleAPI/family-config#528]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: EuroElite Family
key: eue
color: orange
emblem: Fugi_03.png
info:
  logo: https://photos.app.goo.gl/P2zYa2MwrY7AmuFu6
  description: >
🦉Wir sind die EuroElite🦉

Eine 🇩🇪 Gaming Community. 
Im Bereich Clash Royale sind wir sehr Ambitioniert
und wollen in der Szene Fuß fassen.
Mit 3 Clans, unser eSports Team EuroElite Spirit 
und einer riesen Discord Community, haben wir 
den perfekten Grundstein gelegt.

Du hast Interesse ein Teil davon zu sein? 
Dann schaue dich doch gerne bei uns um! :)

social:
    - website: https://euroelite.online/
    - discord: https://discord.gg/AvjX3tB
    - instagram:
    https://www.instagram.com/eue.euroelite/
    - twitch: https://twitch.tv/euroelite
    - twitch: https://twitch.tv/foexelchen

clans:
  - name: EuroElite
    tag: Q99JC8PU
  - name: EuroElite Maxi
    tag: QQ2CRCGQ
  - name: EuroElite Mini
    tag: L2QLU9LJ
  - name: EuroElite Event
    tag: LU98UPUC

```

**Comment by LucaFox1** [comment]
is all correct?

**Comment by smlbiobot** [comment]
```yml
name: EuroElite Family
key: eue
color: orange
emblem: Fugi_03
info:
  logo: /static/img/brands/logo/euro-elite.png
  description: >
    🦉Wir sind die EuroElite🦉


    Eine 🇩🇪 Gaming Community.
    Im Bereich Clash Royale sind wir sehr Ambitioniert
    und wollen in der Szene Fuß fassen.
    Mit 3 Clans, unser eSports Team EuroElite Spirit
    und einer riesen Discord Community, haben wir
    den perfekten Grundstein gelegt.


    Du hast Interesse ein Teil davon zu sein?
    Dann schaue dich doch gerne bei uns um!:)

  social:
  - website: https://euroelite.online/
  - discord: https://discord.gg/AvjX3tB
  - instagram: https://www.instagram.com/eue.euroelite/
  - twitch: https://twitch.tv/euroelite
  - twitch: https://twitch.tv/foexelchen

clans:
- name: EuroElite
  tag: Q99JC8PU
- name: EuroElite Maxi
  tag: QQ2CRCGQ
- name: EuroElite Mini
  tag: L2QLU9LJ
- name: EuroElite Event
  tag: LU98UPUC

```
