### ISSUE TITLE
Bar Raiz

### ISSUE THREAD

**Issue by lucaslipay** [RoyaleAPI/family-config#529]
```yaml
name: Família Bar Raiz
key: Bar Raiz
color: red
emblem: Bamboo_01
info:
  logo: https://ibb.co/DYvwN7y
  description: > Família Bar Raiz: 100% focados em War 2.0
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/rcTJ3zt7C2
 
clans:
  - name: Bar Raiz
    tag: 2CVGGP28
  - name: Bar Raiz II
    tag: Q0YRVYC0
  - name: Bar Raiz III
    tag: Q0YRVYC0
```

**Comment by smlbiobot** [comment]
```yml
name: Bar Raiz Família
key: barraiz
color: red
emblem: Bamboo_01
info:
  logo: /static/img/brands/logo/bar-raiz.png
  description: >
    Família Bar Raiz: Clãs BR 100% focados em War 2.0
  social:
  - discord: https://discord.gg/rcTJ3zt7C2

clans:
- name: Bar Raiz
  tag: 2CVGGP28
- name: Bar Raiz II
  tag: Q0YRVYC0
- name: Bar Raiz III
  tag: Q0YRVYC0

```

**Comment by lucaslipay** [comment]
Can I fix the Bar Raiz III? The tag is wrong, the right is L8CVUGQP 😬

**Comment by smlbiobot** [comment]
updated

**Comment by smlbiobot** [comment]
```yml
name: Bar Raiz Família
key: barraiz
color: red
emblem: Bamboo_01
info:
  logo: /static/img/brands/logo/bar-raiz.png
  description: >
    Família Bar Raiz: Clãs BR 100% focados em War 2.0
  social:
  - discord: https://discord.gg/rcTJ3zt7C2

clans:
- name: Bar Raiz
  tag: 2CVGGP28
- name: Bar Raiz II
  tag: Q0YRVYC0
- name: Bar Raiz III
  tag: L8CVUGQP

```
