### ISSUE TITLE
Actualizar la familia de clanes 

### ISSUE THREAD

**Issue by fabi0M** [RoyaleAPI/family-config#530]
```yaml
name: MultiCampeones Family
key: MultiCampeones 
color: pink
emblem: Tower_01
info:
  logo: ![20210331_214819](https://user-images.githubusercontent.com/83083991/115906090-0fc93a80-a435-11eb-9de1-062b1c0bc61a.jpg)
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: SuperCampeones
    tag: LCCVGR2
  - name: UltraCampeones 
    tag: YJPVV0Q2
  - name: MegaCampeones
    tag: QLJVP9QV
```

**Comment by fabi0M** [comment]
Se cambio el clan SuperCampeones por otro

**Comment by smlbiobot** [comment]
`LCCVGR2` is not a valid clan tag. Just gonna assume you meant `LCCVLGR2`

**Comment by smlbiobot** [comment]
```yml
name: MultiCampeones Family
key: MultiCampeones
color: pink
emblem: Tower_01
info:
  logo: /static/img/brands/logo/campeones.png
  description: >
    Familia y clanes recién creados

    # vamos por más
clans:
- name: SuperCampeones
  tag: LCCVLGR2
- name: UltraCampeones
  tag: YJPVV0Q2
- name: MegaCampeones
  tag: QLJVP9QV

```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/MultiCampeones

**Comment by fabi0M** [comment]
```yaml
name: OlimposEsports Family
key: OlimposEsports
color: [pink]
emblem: Tower_01
 info:
  logo: ![Picsart_22-10-20_22-06-55-434](https://user-images.githubusercontent.com/83083991/215850391-fd4f4320-e107-4183-bf46-53bd37a5db4b.png)
social:
    - website: https://mifaxp.webnode.es
    - twitter: https://twitter.com/mifaxp
    - discord: https://discord.gg/TceEpJbuhe
    - twitter: https://twitter.com/OlimposClanes
    - discord: https://discord.gg/Up4uyuPd7j
    - twitter: https://twitter.com/OlimposEsports
    - discord: https://discord.gg/5v6VYGW4Ta
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: OlimposEsports
    tag: Q2V8V0QL
  - name: Colusiom prime 
    tag: LCJC2P0R
  - name: MegaCampeones
    tag: QLJVP9QV
```
