### ISSUE TITLE
update SG Alliance family - add Lion Kia Mini, remove Blitz Force, remove Blitz Lodge

### ISSUE THREAD

**Issue by cheapmonk2003** [RoyaleAPI/family-config#532]
```yaml
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0Q
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8Y
```

**Comment by cheapmonk2003** [comment]
we also changed the order of listing of the clans, to list GummyBear at 3rd place, and inserting Lion Kia Mini at 7th place.

There is a problem for GummyBear, When looking at GummyBear in royaleapi, it reflects the old clan family of GummyBear.

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/sgalliance

**Comment by smlbiobot** [comment]
Submitted clan tag for gummy bear is invalid

**Comment by cheapmonk2003** [comment]
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Altitude
    tag: L9QGG299
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8Y

**Comment by cheapmonk2003** [comment]
corrected the gummybear clan tag
added a new clan Altitude

**Comment by cheapmonk2003** [comment]
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
description: >
SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
to help each other, and yet remain independent.
social:
- email: mailto:cheapmonk2003@hotmail.com
clans:

name: TEDDYBEAR
tag: PLJ9CL9R
name: Lion City Kia
tag: C2JQUUG
name: GUMMYBEAR
tag: 8URJ0QY
name: SG TITANS
tag: GVYJ0P
name: SG Black Hawks
tag: C8JY
name: Altitude
tag: L9QGG299
name: Lion Wardens
tag: 29PQ299
name: Lion Kia Mini
tag: YQVQ22R8
name: SG Bruschettas
tag: 8VLPYGJL
name: Marus Vengeance
tag: JR0CQ8

**Comment by cheapmonk2003** [comment]
found a mistake in the Marus Vengeance clan tag, this is the corrected one

**Comment by cheapmonk2003** [comment]
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8

**Comment by cheapmonk2003** [comment]
found a mistake in the Marus vengeance clan tag as well, corrected it.

**Comment by cheapmonk2003** [comment]
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Altitude
    tag: L9QGG299
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8

**Comment by cheapmonk2003** [comment]
name: SG Alliance
key: sgalliance
color: red
emblem: Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR 
    tag: PLJ9CL9R
  - name: Lion City Kia 
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Altitude
    tag: L9QGG299
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8

**Comment by smlbiobot** [comment]
Your emblem config is wrong btw. it’s `A_Char_Prince_03` and not `Prince_03`


```yml
name: SG Alliance
key: sgalliance
color: red
emblem: A_Char_Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore clans who are struggling,
    to help each other, and yet remain independent.
  social:
  - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR
    tag: PLJ9CL9R
  - name: Lion City Kia
    tag: C2JQUUG
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: SG TITANS
    tag: GVYJ0P
  - name: SG Black Hawks
    tag: C8JY
  - name: Altitude
    tag: L9QGG299
  - name: Lion Wardens
    tag: 29PQ299
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8
```
