### ISSUE TITLE
AeroDynamix

### ISSUE THREAD

**Issue by NymaXD** [RoyaleAPI/family-config#533]
```yaml
name: AeroDynamix
key: aerodynamix
color: orange
emblem: flag_h_02
info:
  description: >
    Familia ⭐AeroDynamix⭐ TOP Colombia 🇨🇴 Clanes Competitivos
    No eSports
  social:
    - discord: https://discord.gg/Z5zzfkReej
clans:
  - name: AeroDynamix
    tag: QQY89U2J
  - name: AeroDynamix 2
    tag: QU0UGLJU
```
