### ISSUE TITLE
LaTronco info update

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#534]
Hi, I've just edit some info, thank you for your service!

__Originally posted by @LaTronco in https://github.com/RoyaleAPI/family-config/issues/498#issuecomment-900276374__

**Comment by smlbiobot** [comment]
In the future, please open NEW issue with config.

You can update this in the future (your config is invalid but the errors are corrected):

```yml
name: LaTroncoFamiglia
key: latronco
color: green
emblem: Bamboo_03
sort: trophy
info:
  logo: /static/img/brands/logo/latronco-2.png
  description: >
    LaTroncoFamiglia, un insieme di clan in comunicazione tra loro per divertirsi in un ambiente tranquillo puntando al primo posto in ogni guerra.
    Abbiamo delle regole generali nei clan per il quieto vivere, siate persone civili, nessun comportamento infantile, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.
    I primi 6 clan sono incentrati sulla guerra, con La Nuova Tronco clan primario, quindi si chiedono 4 attacchi su 4 ogni giorno di guerra.
    Comunichiamo atttaverso un canale Telegram e due gruppi.
  social:
    - telegram: https://t.me/LaTroncoFamiglia
    - telegram: https://t.me/LaNuovaTronco
clans:
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoradice
    tag: YV2UJ0GV
  - name: La Troncoseme
    tag: QQLVQ20V
  - name: La Troncospizio
    tag: L229VYRG
```
