### ISSUE TITLE
10.8 Return 2

### ISSUE THREAD

**Issue by lolodeglingo** [RoyaleAPI/family-config#536]
```yaml
name: **10.8 Return Family**
key: 10.8
color: purple
emblem: Star_Shine_03.png
info:
  logo: /static/img/brands/logo/Star_Shine_03.png
  description: >
   La famille 10.8 Return est l'une des plus anciennes, l'une des plus performantes et des plus grandes familles de Clash Royale
     avec nos 400 membres et 8 clans orientés principalement sur les GUERRES DE CLANS !
     Notre devise est " Fun et Performance " dans l'esprit convivial et participatif, l'entraide et la fraternité est notre raison de jouer et c'est ce qui nous motive jusqu'à aujourd'hui!
     Nous pensons que c'est la raison pour laquelle nous sommes allés si loin.
     **Nous sommes pratiquement la seule team AU MONDE à avoir trois clans en ligue légendaire 2!
     Du joueur occasionnel aux joueurs compétitifs, des vieux aux jeunes, actif à très actif , nous sommes la pour être les meilleurs en s'amusant!
     Nous partageons tous une passion commune pour le jeu, sommes amicaux, donnons toujours,
     s'entraider avec le même objectif : toujours se perfectionner et passer un bon moment !
     **Rejoignez la famille. Deviens une étoile. ** 
  social:
    - discord: https://discord.me/10.8 Return - Clash Royale
    - line: https://line.me/lolodeglingo

clans:
  - name: 10.8 Return 2
    tag: GGJCC20
  - name: 10.8 Return 4
    tag: 289RGRYR
  - name: 10.8 Return 3
    tag: RGJPP9V
  - name: 10.8 Return
    tag: 2QRCYLV
  - name: 10.8 Return War
    tag: 9QC9UPY8
  - name: 10.8 Return V2
    tag: L0U8CQ9C
  - name: 10.8 Ret Club
    tag: LY9ULJRY
  - name: 10.8 Return Fun
    tag: Y2C98JR9
  
```

**Comment by lolodeglingo** [comment]
la meilleur team au monde!:-)

**Comment by smlbiobot** [comment]
please use this in the future:

```yml
name: 10.8 Return Family
key: 10.8
color: purple
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/Star_Shine_03.png
  description: >
    La famille 10.8 Return est l'une des plus anciennes, l'une des plus performantes et des plus grandes familles de Clash Royale
   avec nos 400 membres et 8 clans orientés principalement sur les GUERRES DE CLANS !
   Notre devise est " Fun et Performance " dans l'esprit convivial et participatif, l'entraide et la fraternité est notre raison de jouer et c'est ce qui nous motive jusqu'à aujourd'hui!
   Nous pensons que c'est la raison pour laquelle nous sommes allés si loin.
   **Nous sommes pratiquement la seule team AU MONDE à avoir trois clans en ligue légendaire 2!
   Du joueur occasionnel aux joueurs compétitifs, des vieux aux jeunes, actif à très actif , nous sommes la pour être les meilleurs en s'amusant!
   Nous partageons tous une passion commune pour le jeu, sommes amicaux, donnons toujours,
   s'entraider avec le même objectif : toujours se perfectionner et passer un bon moment!
   **Rejoignez la famille. Deviens une étoile.**
  social:
    - line: https://line.me/lolodeglingo

clans:
  - name: 10.8 Return 2
    tag: GGJCC20
  - name: 10.8 Return 4
    tag: 289RGRYR
  - name: 10.8 Return 3
    tag: RGJPP9V
  - name: 10.8 Return
    tag: 2QRCYLV
  - name: 10.8 Return War
    tag: 9QC9UPY8
  - name: 10.8 Return V2
    tag: L0U8CQ9C
  - name: 10.8 Ret Club
    tag: LY9ULJRY
  - name: 10.8 Return Fun
    tag: Y2C98JR9
```
