### ISSUE TITLE
Ancient Clan Family

### ISSUE THREAD

**Issue by w1spe0n** [RoyaleAPI/family-config#540]
```yaml
name: Ancient Clan Family
key: ancient
color: purple
emblem: A_Char_Pekka_01
info:
  social:
      - discord: https://discord.io/ancient
clans:
  - name: Ancient Paladin
    tag: QRUJRVL
  - name: Ancient Legion
    tag: LLV9290R
```

**Comment by smlbiobot** [comment]
note formatting


```yml
name: Ancient Clan Family
key: ancient
color: purple
emblem: A_Char_Pekka_01
info:
  social:
      - discord: https://discord.io/ancient
clans:
  - name: Ancient Paladin
    tag: QRUJRVL
  - name: Ancient Legion
    tag: LLV9290R
```
