### ISSUE TITLE
BandiZ

### ISSUE THREAD

**Issue by IvMisticos** [RoyaleAPI/family-config#541]
```yaml
name: BandiZ
key: bandiz
color: violet
emblem: Skull_04.png
sort: trophy
info:
  description: >
    **[EN] #1 in Ukraine by CW.**
    Most skilled players get rewarded with a Pass Royale.
    Irresponsible and inadequate players go to our academy or get kicked.
    **[RU] Лучший клан Украины по КВ.**
    Самые опытные игроки награждаются Pass Royale.
    Безответственные и неадекватные игроки отправляются в академию либо изгоняются.
  social:
    - telegram: t.me/BandiZCR
    - discord: discord.gg/5hE42t3
clans:
  - name: BandiZ
    tag: 2G2QRQRP
  - name: BandiZ Academy
    tag: YGGQCLC0
  - name: BandiZ 2
    tag: QUPQYLJP
```

**Comment by smlbiobot** [comment]
note URLs + formatting

```yml
name: BandiZ
key: bandiz
color: violet
emblem: Skull_04
sort: trophy
info:
  description: >
    **[EN] #1 in Ukraine by CW.**
    Most skilled players get rewarded with a Pass Royale.
    Irresponsible and inadequate players go to our academy or get kicked.


    **[RU] Лучший клан Украины по КВ.**
    Самые опытные игроки награждаются Pass Royale.
    Безответственные и неадекватные игроки отправляются в академию либо изгоняются.
  social:
    - telegram: https://t.me/BandiZCR
    - discord: https://discord.gg/5hE42t3
clans:
  - name: BandiZ
    tag: 2G2QRQRP
  - name: BandiZ Academy
    tag: YGGQCLC0
  - name: BandiZ 2
    tag: QUPQYLJP
```
