### ISSUE TITLE
CZ Royal Family

### ISSUE THREAD

**Issue by pepall594** [RoyaleAPI/family-config#542]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Klánová rodina CZ
key: CZ
color: blue
emblem: flag_m_01
info:
  logo:
  description: > POUZE AKTIVNÍ A POHODOVÍ HRÁČI !!
  Jsem aktivní,pohodová Klanová rodina, která ráda uvítá nové hráče a každému ráda poradí. Pravidla jsou jednoduchá a to plnit limity ve War a v donatech.

  social:
    - email: nasklancz@seznam.cz
clans:
  - name: CZ
    tag: 80V9UV
  - name: CZ
    tag: Y0JV08JL
  - name: Cz Barbarians
    tag: 9UYPQ2P0
```

**Comment by smlbiobot** [comment]
```yml
name: Klánová rodina CZ
key: CZ
color: blue
emblem: flag_m_01
info:
  description: >
    POUZE AKTIVNÍ A POHODOVÍ HRÁČI !!
    Jsem aktivní,pohodová Klanová rodina, která ráda uvítá nové hráče a každému ráda poradí. Pravidla jsou jednoduchá a to plnit limity ve War a v donatech.

  social:
    - email: mailto:nasklancz@seznam.cz
clans:
  - name: CZ
    tag: 80V9UV
  - name: CZ
    tag: Y0JV08JL
  - name: Cz Barbarians
    tag: 9UYPQ2P0
```
