### ISSUE TITLE
Update Zero Gemme Family - Added Zero Gemme 1.5 and changed discord link

### ISSUE THREAD

**Issue by ToninoTT** [RoyaleAPI/family-config#543]
name: Zero Gemme Family
key: zerogemme
color: green
emblem: Gem_01
info:
  logo:
  description: > 
Famiglia italiana di Zero Gemme. Il nostro obiettivo è creare un gruppo stabile e raggiungere risultati importanti sia in ladder sia nelle guerre. Siamo stabilmente nella top 100 italiana per entrambe le modalità
 
  social:
    - discord: https://discord.gg/PuJTe2Wvz2
    - telegram: https://t.me/ZeroGemme

clans:
  - name: Zero Gemme
    tag: G8YVLJ
  - name: Zero Gemme 2.0
    tag: 2880RPVY
  - name: Zero Gemme 3.0
    tag: Q8UUVRUC
  - name: Zero Gemme 1.5
    tag: LGC9PRRR

**Comment by smlbiobot** [comment]
please make sure that all URLs start with `https://`

```yml
name: Zero Gemme Family
key: zerogemme
color: green
emblem: Gem_01
info:
  description: >
    Famiglia italiana di Zero Gemme. Il nostro obiettivo è creare un gruppo stabile
    e raggiungere risultati importanti sia in ladder sia nelle guerre. Siamo stabilmente
    nella top 100 italiana per entrambe le modalità

  social:
  - discord: https://discord.gg/PuJTe2Wvz2
  - telegram: https://t.me/ZeroGemme

clans:
- name: Zero Gemme
  tag: G8YVLJ
- name: Zero Gemme 2.0
  tag: 2880RPVY
- name: Zero Gemme 3.0
  tag: Q8UUVRUC
- name: Zero Gemme 1.5
  tag: LGC9PRRR

```
