### ISSUE TITLE
Klever Family 

### ISSUE THREAD

**Issue by WollkerYT** [RoyaleAPI/family-config#545]
```yaml
name: Klever Family
key: Klever
color: green
emblem: clover_01
info:
               logo: /static/img/branding/Klever-White/png
description: >
🇷🇺Klever is ready to accept good player to our big family
we are also have a competitive team so join us
become better play wars and
we are waiting execly for you :)
        social:
                - twitter: https://twitter.com/KleverWhite
                - discord: https://discord.gg/Yp2A945Ned
                - instagram: https://instagram.com/wollkeryt
              clans:
                       - name: Klever White
                         tag: 98YG9V2C
                       - name: Klever Black
                         tag: QGYVJ2J0
                       - name: Golden Elite
                         tag: POYGJVOC
                       - name: Reliance
                         tag: P8YU288U
```

**Comment by smlbiobot** [comment]
Please upload logo as a comment

**Comment by smlbiobot** [comment]
- formatting matters
- Supercell tags are numbers `0` and not letters `O`

```yml
name: Klever Family
key: Klever
color: green
emblem: clover_01
info:
  description: >
    🇷🇺Klever is ready to accept good player to our big family
    we are also have a competitive team so join us
    become better play wars and
    we are waiting execly for you :)
  social:
    - twitter: https://twitter.com/KleverWhite
    - discord: https://discord.gg/Yp2A945Ned
    - instagram: https://instagram.com/wollkeryt
clans:
  - name: Klever White
    tag: 98YG9V2C
  - name: Klever Black
    tag: QGYVJ2J0
  - name: Golden Elite
    tag: P0YGJV0C
  - name: Reliance
    tag: P8YU288U
```
