### ISSUE TITLE
Alpha Esports™️ COC

### ISSUE THREAD

**Issue by Jhussain1** [RoyaleAPI/family-config#547]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Alpha Esports™️ (CR)
key: AlphaEsportsCOC
color: green
emblem: sword_02
info: 
logo: (https://media.discordapp.net/attachments/526461203007012865/886259871937363998/image0.jpg)

  description: > 
    **Alpha Esports™️ (CR) is the 3rd official new game branch we have expanded into. Alpha Esports is a gaming community which we wish to expand and grow the community into a safe place for people to join, play different games, make friends and also most importantly have fun.


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/Hv6sCSnSny 
clans:
  - name: Alpha
    tag: L8UR990I
  - name: Alpha Phoenix
    tag: 9GUUR8LP
```

**Comment by smlbiobot** [comment]
your clan tags are wrong

```yml
name: Alpha Esports™️ (CR)
key: AlphaEsportsCOC
color: green
emblem: sword_02
info:
  logo: /static/img/brands/logo/alpha-esports.png

  description: >
    **Alpha Esports™️ (CR)** is the 3rd official new game branch we have expanded into. Alpha Esports is a gaming community which we wish to expand and grow the community into a safe place for people to join, play different games, make friends and also most importantly have fun.

  social:
    - discord: https://discord.gg/Hv6sCSnSny
clans:
  - name: Alpha
    tag: L8UR990U
  - name: Alpha Phoenix
    tag: 9GUUR8LP
```
