### ISSUE TITLE
[Update] Caverna do Guxo Family : (name family - key- description - new clan- add social facebook/instagram)

### ISSUE THREAD

**Issue by CavernaDoGuxo** [RoyaleAPI/family-config#548]
```yaml
name: Guxos Community
key: guxos
color: black
emblem: Clover_02
info:
logo: /static/img/brands/logo/cavernadoguxo
description: >

**Comunidade dos Guxos**
_A melhor comunidade portuguesa de Clash Royale!_

Somos *focados* em *Guerras!*
A competitividade está no coração da nossa família, por isso, temos os nossos próprios *torn€ios int€rnos* e participamos em torneios externos relevantes.
Num ambiente amigável e competitivo, motivamos os nossos jogadores a progredir em todos os quadrantes!

Se achares que tens o _perfil_ para te juntares a nós, entra no nosso _Discord_ e *Guxa muito!*

social:

discord: https://discord.gg/Te5uTG99up
twitter: https://www.twitter.com/CavernaDoGuxo
facebook: https://www.facebook.com/Caverna-do-Guxo
instagram: https://instagram.com/cavernadoguxo
email: cavernadoguxo@gmail.com

clans:

name: Caverna do Guxo
tag: YGCC9JJL
name: Gruta do Guxo
tag: GL8UY9Y
name: guxos evo
tag: LVCUQULY
```

**Comment by smlbiobot** [comment]
please keep FORMAT. SPACING and HYPHENS are IMPORTANT.

we don’t just need the text. we need the correct structure so that config can be parsed

```yml
name: Caverna do Guxo Family
key: guxos
color: black
emblem: Clover_02
info:
  logo: /static/img/brands/logo/cavernadoguxo.png
  description: >2

    **Caverna do Guxo**


     A **6 de Setembro de 2019** nasceu o melhor clã _Português!_
    Somos focados em **guerras!**


    A competitividade está no coração da nossa família, por isso temos os nossos próprios
    _torneio$_ internos e participamos de torneios externos relevantes.
    Num ambiente amigável e competitivo, motivamos nossos jogadores a bater seus próprios
    recordes na ladder.


    Se achas que tens o _perfil_ para te juntares a nós, entra em contacto via _discord._

  social:
    - discord: https://discord.gg/Te5uTG99up
    - twitter: https://www.twitter.com/CavernaDoGuxo
    - facebook: https://www.facebook.com/Caverna-do-Guxo
    - instagram: https://instagram.com/cavernadoguxo
    - email: mailto:cavernadoguxo@gmail.com
clans:
- name: Caverna do Guxo
  tag: YGCC9JJL
- name: guxos evo
  tag: LVCUQULY

```
