### ISSUE TITLE
Elysium Family

### ISSUE THREAD

**Issue by Elysium-Netzwerk** [RoyaleAPI/family-config#549]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Elysium 
key: elysium
color: red
emblem: flag_k_03
sort: trophy
info:
  logo: https://ibb.co/5Wv3Wj1
  description: >
   Willkommen bei **Elysium**. Einer der aktivsten Clash Royale Familien im deutschsprachigen Raum. Wir sind seit den Anfängen von Clash Royale vertreten und bestehen mittlerweile aus 7 Clans und auch im eSports Bereich sind wir mit 2 Teams vertreten. Wir setzen auf Aktivität & Freundlichkeit, sollte dies auf euch zutreffen, so seid ihr jederzeit bei uns willkommen. Checkt doch dafür gerne einfach unseren Discord Server oder Instagram Account ab!


Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/YXfRKfPYRq
    - instagram: https://www.instagram.com/elysium.cr/
    - email: mailto:elysiumnetzwerk.cr@gmail.com
clans:
  - name: ELYSIUM
    tag: LOGO29
  - name: Elysium 2 
    tag: 2G88PYY
  - name: Elysium Elite
    tag: LJCPQPU2
- name: Elysium eSports
    tag: YVOUJYJ9
- name: Elysium 3
    tag: UULOU2C
- name: Elysium Academy
    tag: YCUQVRJV
- name: Elysium Austria
    tag: LGC9JQVG
```
