### ISSUE TITLE
[Update] Ancient Clan Family - added 2 clans - updated discord invite 

### ISSUE THREAD

**Issue by w1spe0n** [RoyaleAPI/family-config#550]
```yaml
name: Ancient Clan Family
key: ancient
color: purple
emblem: A_Char_Pekka_01
info:
  social:
      - discord: https://discord.gg/6zW4XPGTkh
clans:
  - name: Ancient Paladin
  tag: QRUJRVL
  - name: Ancient Legion
  tag: LLV9290R
  - name: Ancient Legacy
  tag: PGLR2R2
  - name: Ancient Wolves
  tag: QCUGVLU
```

**Comment by smlbiobot** [comment]
```yml
name: Ancient Clan Family
key: ancient
color: purple
emblem: A_Char_Pekka_01
info:
  social:
  - discord: https://discord.gg/6zW4XPGTkh
clans:
- name: Ancient Paladin
  tag: QRUJRVL
- name: Ancient Legion
  tag: LLV9290R
- name: Ancient Legacy
  tag: PGLR2R2
- name: Ancient Wolves
  tag: QCUGVLU

```
