### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JackClack** [RoyaleAPI/family-config#552]
```yaml
name: Royal Family
key: royal
color: black
emblem: Diamond_Star_01
info:
  logo: https://ibb.co/Jp69yXn
  description: >
   **Присоединяйтесь к Королевской Семье!
Ищем хороших людей для сотрудничества и 
дальнейшего создания целой сети Королевских кланов!**
  social:
    - email: mailto:royal.family.cl.ro@gmail.com
    - telegram: @royal_HSUM
    - discord: discord.gg/tjHyVZqR6n
clans:
  - name: Royal Harmony
    tag: QUVCQ9
  - name: Royal Symphony
    tag: LQ0VYV0P
  - name: Royal Unity
    tag: YV22QG9V
  - name: Royal Melody
    tag: YV8Q002R
```
