### ISSUE TITLE
Alpha Esports

### ISSUE THREAD

**Issue by Jhussain1** [RoyaleAPI/family-config#553]
```yaml
name: Alpha Esports
key: alpha
color: red
emblem: flame_03
info:
  logo: 
![image](https://user-images.githubusercontent.com/41232618/135333285-b194fad2-dca7-4c8f-a9af-cc0bb38ebd3f.png)

  description: >
 Alpha Esports is a gaming community with a goal to create a safe and learning place for people to nurture, make friends, and learn. 




  social:
    - discord: http://discord.gg/yNUhuVPMrn

clans:
  - name: Alpha Phoenix
    tag: 9GUUR8LP
  - name: Alpha Divine
    tag: LP8UL8V9
```
