### ISSUE TITLE
Family of Legends: Discord

### ISSUE THREAD

**Issue by mondalsushant** [RoyaleAPI/family-config#556]
```yaml
name: Discord
key: discord
color: purple
emblem: Skull_05
info:
    logo: https://imgur.com/a/bjNf0rn
    description:  >
        We are partnered with Discord and Team Liquid. If you want to join our official clan please become a
        part of our family. **Join our Clans. Become a solid player in Clash Royale.**
    social:
    - instagram: https://instagram.com/iamsushantmusic
    - twitch: https://twitch.tv/susmonn
clans:
    - name: Discordd
     tag: L8LYQJPU
```
