### ISSUE TITLE
CR ADULTES FR Family

### ISSUE THREAD

**Issue by AnkoWCR** [RoyaleAPI/family-config#557]
```yaml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
logo: ![cradultesfrlogo](https://user-images.githubusercontent.com/92339610/136866769-668ba10c-affe-4eae-9007-717070db3e07.png)
description: >
La **Famille CR ADULTES FR** rassemble des clans d'adultes français actifs en GDC.
Esprit d'équipe, fun & entraide.


clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: L0VCYRJ8
```
