### ISSUE TITLE
Caverna do Guxo - Please Update NAME (Guxos Community) and DESCRIPTION. Thanks

### ISSUE THREAD

**Issue by CavernaDoGuxo** [RoyaleAPI/family-config#559]
```yaml
name: Guxos Community
key: guxos
color: black
emblem: Clover_02
info:
  logo: /static/img/brands/logo/cavernadoguxo.png
  description: >2

    **Comunidade dos Guxos**

   _A melhor comunidade portuguesa de Clash Royale!_

   Somos *focados* em *Guerras!*
A competitividade está no coração da nossa família, por isso, temos os nossos próprios *torn€ios int€rnos* e participamos em torneios externos relevantes.
   Num ambiente amigável e competitivo, motivamos os nossos jogadores a progredir em todos os quadrantes!

   Se achares que tens o _perfil_ para te juntares a nós, entra no nosso _Discord_ e *Guxa muito!*

  social:
    - discord: https://discord.gg/Te5uTG99up
    - twitter: https://www.twitter.com/CavernaDoGuxo
    - facebook: https://www.facebook.com/Caverna-do-Guxo
    - instagram: https://instagram.com/cavernadoguxo
    - email: mailto:cavernadoguxo@gmail.com
clans:
  - name: Caverna do Guxo
    tag: YGCC9JJL
  - name: Gruta do Guxo
    tag: GL8UY9Y
  - name: guxos evo
    tag: LVCUQULY
```
