### ISSUE TITLE
Banana Family  - new Clan + new text for the description of the family and new website

### ISSUE THREAD

**Issue by darkskyboy** [RoyaleAPI/family-config#56]
Dear royalapi team, please replace our old families description by this description: -
Willkommen in der Banana Family. Eine der größten Clash Royale Familien im deutschsprachigen Raum. Uns gibt es seit dem 19.02.2016! Wir sind damit seit den Anfängen im Clash Royale Universum vertreten. Von Hardcore bis Chiller, von Clanwars-Suchti bis Fun-Gamer. Von Junior bis Senior, von Einsteiger bis global-tops-Spieler. Bei uns findest Du Deinen passenden Clan! Discord.me/banane  und www.banana-family.de – jump in und clash on!

Please also replace the link to our website by the following link: www.banana-family.de.  Finally, please add our new clan.

Name of the clan: Fermium Bananen (#PRR89CLJ)
Please add this clan to our families overview.  Thank you - have a nice evening.

**Comment by smlbiobot** [comment]
```yml
name: Banana Family
key: banana
color: yellow
emblem: Arrow_04
sort: trophy
info:
  logo: /static/img/brands/logo/banana.png
  description: >
    Willkommen in der Banana Family. Eine der größten Clash Royale Familien im deutschsprachigen Raum. Uns gibt es seit dem 19.02.2016! Wir sind damit seit den Anfängen im Clash Royale Universum vertreten. Von Hardcore bis Chiller, von Clanwars-Suchti bis Fun-Gamer. Von Junior bis Senior, von Einsteiger bis global-tops-Spieler. Bei uns findest Du Deinen passenden Clan! Discord.me/banane und www.banana-family.de – jump in und clash on!
  social:
    - discord: https://discord.gg/9rN9qUQ
    - twitch: https://www.twitch.tv/r3dzen
    - website: http://www.banana-family.de
clans:
  - name: Titan Bananen
    tag: 8Y9LY8CC
  - name: Reife Bananen
    tag: 99VVJPL0
  - name: Uran Bananen
    tag: 8V09Q88C
  - name: Aurum Bananen
    tag: 9900ULUC
  - name: Neodym Bananen
    tag: 8QGQGRP0
  - name: Chilli Bananen
    tag: Q9Q8QJQ
  - name: Cobalt Bananen
    tag: P9U9RYGP
  - name: Titanit Bananen
    tag: PGV98LJJ
  - name: Betafit Bananen
    tag: P8URRP0G
  - name: Gallium Bananen
    tag: 9VYY8RLP
  - name: Helium Bananen
    tag: P9YUG99R
  - name: Stream Bananen
    tag: P9QU00GR
  - name: Wolfram Bananen
    tag: PYR0QQUQ
  - name: Krypton Bananen
    tag: PC9JYGQJ
  - name: Argon Bananen
    tag: 9CU9PVQV
  - name: Fermium Bananen
    tag: PRR89CLJ
```
