### ISSUE TITLE
Robert’s Army

### ISSUE THREAD

**Issue by RobertsArmy** [RoyaleAPI/family-config#562]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Robert's Army
key: Robert's Army
color: blue
emblem: Skull_06
info:
  logo: 
  description: Clan top 1 México en guerra y ladder, contamos con 3 canteras. 


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/robertsarmy_cr?s=21
    - discord:
    - twitch:
    - reddit: 
    - youtube:
    - website:
    - instagram: https://instagram.com/robertsarmycr?utm_medium=copy_link
    - facebook: https://www.facebook.com/101543748774324/posts/191529839775714/
    - twitch:
    - youtube:
    - application:
    - email:mailto:robertsarmytm@gmail.com
clans:
  - name: Robert's Army2 ™️
    tag: Y2PLQ989
  - name: Robert's Army3™️
    tag: Q892R020
  - name: Robert's Army4 ™️
    tag: LC22OCO8
```

**Comment by smlbiobot** [comment]
wrong clan tag

```yml
name: Robert's Army
key: robertsarmy
color: blue
emblem: Skull_06
info:
  description: Clan top 1 México en guerra y ladder, contamos con 3 canteras.
  social:
    - twitter: https://twitter.com/robertsarmy_cr?s=21
    - instagram: https://instagram.com/robertsarmycr?utm_medium=copy_link
    - facebook: https://www.facebook.com/101543748774324/posts/191529839775714/
    - email: mailto:robertsarmytm@gmail.com
clans:
  - name: Robert's Army2 ™️
    tag: Y2PLQ980
  - name: Robert's Army3™️
    tag: Q892R020
  - name: Robert's Army4 ™️
    tag: LC22OCO8

```
