### ISSUE TITLE
Famille "(paradise)"

### ISSUE THREAD

**Issue by Grandpivert** [RoyaleAPI/family-config#563]
```yaml
name: "(paradise)"
key: paradise
color: blue
emblem: flag_k_01
info:
   logo: https://user-images.githubusercontent.com/92825774/137988168-7d4351e4-12bb-4502-8e28-b2106c73b8b9.jpg
   description: >
   La famille du **paradise** est le royaume du bon jeu où la bonne ambiance et l'entraide règnent. Actifs en GDC, rejoignez-nous !


clans:
  - name: "(paradise)"
    tag: 29UJV8 
  - name: "(paradise)"2
    tag: L9CULC9U
  - name: "(paradise)"3
    tag: VUUJUG
```

**Comment by smlbiobot** [comment]
```yml
name: '"(paradise)"'
key: paradise
color: blue
emblem: flag_k_01
info:
   logo: /static/img/brands/logo/paradise.jpg
   description: >
     La famille du **paradise** est le royaume du bon jeu où la bonne ambiance et l'entraide règnent. Actifs en GDC, rejoignez-nous !


clans:
  - name: '"(paradise)"'
    tag: 29UJV8
  - name: '"(paradise)"2'
    tag: L9CULC9U
  - name: '"(paradise)"3'
    tag: VUUJUG

```
