### ISSUE TITLE
ULTRA LATAM

### ISSUE THREAD

**Issue by JunmaUltra24** [RoyaleAPI/family-config#564]
```yaml
name: ULTRA LATAM
key:  ULTRAS
color: pink
emblem:
info: somos una familia...estamos orgullos de nuestra familia, somos competitivos a lvl local, todos son bienvenidos 


  logo: flag_h_02.png
  description: >
   somos una familia...estamos orgullos de nuestra familia, somos competitivos a lvl local, todos son bienvenidos 


    
clans:
  - name: ULTRA LATAM
    tag: YVV0VC8J
  - name: ULTRA LATAM/2
    tag: QCQLJRLG
 
```

**Comment by smlbiobot** [comment]
```yml
name: ULTRA LATAM
key:  ultras
color: pink
emblem: flag_h_02
info:
  description: >
   somos una familia...estamos orgullos de nuestra familia, somos competitivos a lvl local, todos son bienvenidos

clans:
  - name: ULTRA LATAM
    tag: YVV0VC8J
  - name: ULTRA LATAM/2
    tag: QCQLJRLG
```
