### ISSUE TITLE
#FTY Update

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/family-config#565]
```yaml
name: "#FresherThanYou Family"
key: FTY
color: black
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/fresher-than-you.jpg
description: >
   **Loyalty, diligence and reliability are the cornerstones of the # FresherThanYou clan family.**

    We are a very active family that primarily focused on Clan Wars.
    We use a ranking system, which distributes the members into the appropriate clans based on skill, win rate and card resources. The goal is to form an internal top list that enables our strongest and most ambitious members of the family to assert themselves competitively in the CW league.
    If you are not a loner, but a team player and want to make a difference in the CW League, apply on our Discord Server and become part of the family!
  social:
    - discord: https://discord.gg/sCrryNy
    - instagram: https://www.instagram.com/fresherthanyou_family
    - tiktok: https://www.tiktok.com/@fty_clash_royale
    - twitter: https://twitter.com/FTY_CR
    - email: ftycommunity@gmail.com
clans:
  - name: FresherThanYou (CW)
    tag: P009PY9C
 - name: "#SmarterThanYou (CW)"
    tag: Y0VV9YR8
  - name: "#FresherThanYou" (CW)
    tag: GJ9G9R
  - name: "#FasterThanYou (CW)"
    tag: #LY0VYRJV
  - name: "#HigherThanYou (Ladder)"
    tag: #YVJU8YRV
  - name: StrongerThanYou (casual)
    tag: #L9002RUU
  - name: LowerThanYou (casual)
    tag: #L9RRG8C9
```

**Comment by smlbiobot** [comment]
```yml
name: '#FresherThanYou Family'
key: FTY
color: black
emblem: Freeze_01
info:
  logo: /static/img/brands/logo/fty.png
  description: >
    **Loyalty, diligence and reliability are the cornerstones of the # FresherThanYou clan family.**


    - We are a very active family that primarily focused on Clan Wars.

    - We use a ranking system, which distributes the members into the appropriate clans based on skill, win rate and card resources. The goal is to form an internal top list that enables our strongest and most ambitious members of the family to assert themselves competitively in the CW league.

    - If you are not a loner, but a team player and want to make a difference in the CW League, apply on our Discord Server and become part of the family!


  social:
    - discord: https://discord.gg/sCrryNy
    - instagram: https://www.instagram.com/fresherthanyou_family
    - tiktok: https://www.tiktok.com/@fty_clash_royale
    - twitter: https://twitter.com/FTY_CR
    - email: mailto:ftycommunity@gmail.com
clans:
- name: FresherThanYou (CW)
  tag: P009PY9C
- name: "#SmarterThanYou (CW)"
  tag: Y0VV9YR8
- name: "#FresherThanYou (CW)"
  tag: GJ9G9R
- name: "#FasterThanYou (CW)"
  tag: LY0VYRJV
- name: "#HigherThanYou (Ladder)"
  tag: YVJU8YRV
- name: StrongerThanYou (casual)
  tag: L9002RUU
- name: LowerThanYou (casual)
  tag: L9RRG8C9
```
