### ISSUE TITLE
aliance

### ISSUE THREAD

**Issue by 1stDarthdaVer** [RoyaleAPI/family-config#567]
```yaml
name: 1st Cz Family
key: 1stDarthdaVer
color: yellow
emblem: Clover_02.png
info:


  description: >
    Jsme cesi tak staci napsat hlavni je aktivita
  social:  
    - facebook: https://www.facebook.com/klan1stCz
   
clans:
  - name: 1St Cz
    tag: 	9CPQ08L0
```
