### ISSUE TITLE
Arcadia Family Config (Edit)

### ISSUE THREAD

**Issue by the-comp0ser** [RoyaleAPI/family-config#571]
```yaml
name: Arcadia Family
key: arcadiafamily
color: orange
emblem: Twin_Peaks_02
info:
  logo: /static/img/badge/gold-1/Twin_Peaks_02.png
  description: >
    **[Est. 7.14.2020]** The Arcadia Family consists of two friendly, active Clash Royale clans: Arcadia & Gallardo. Please join our Discord server below to learn more about our members, clans, and requirements to join.


  social:
    - discord: https://discord.gg/4W78d95vjZ
    - youtube: https://www.youtube.com/channel/UC8WNNx7q-G9gu8HtV15MiUw
clans:
  - name: Arcadia
    tag: YPPGRYPY
  - name: Gallardo
    tag: 9YPG0JCU
```
Changes: We replaced one of our old clans (Zenith) with a new one (Gallardo) and also changed the description.
