### ISSUE TITLE
Clan Fi

### ISSUE THREAD

**Issue by lukaskans** [RoyaleAPI/family-config#573]
```yaml
name: The 4Sweden’s
key: 4Sweden
color: blue
emblem: Arrow_01
info:
  logo: (https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/badges/Arrow_01.png)

  description: >
    Välkommen till 4Swedens clan familj, vi är suuper aktiva, donarar såklart och kör tournaments 2 gånger varje vecka!!, är du redo att ta clash royale till nästa nivå?? I så fall Välkommen

clans:
  - name: 4Sweden
    tag: LC29GRUJ
  - name: 4Sweden #2
    tag: PC8CLVCV
  - name: 4Sweden #3
    tag: G00CQ0GY
```

**Comment by smlbiobot** [comment]
```yml
name: The 4Sweden’s
key: 4Sweden
color: blue
emblem: Arrow_01
info:
  logo: /static/img/badge/Arrow_01.png

  description: >
    Välkommen till 4Swedens clan familj, vi är suuper aktiva, donarar såklart och kör tournaments 2 gånger varje vecka!!, är du redo att ta clash royale till nästa nivå?? I så fall Välkommen

clans:
  - name: 4Sweden
    tag: LC29GRUJ
  - name: '4Sweden #2'
    tag: PC8CLVCV
  - name: '4Sweden #3'
    tag: G00CQ0GY
```
