### ISSUE TITLE
AR

### ISSUE THREAD

**Issue by AncientRussia** [RoyaleAPI/family-config#574]
```yaml
name: AncientRUSSIA
key: AR
color: yellow
emblem: Pine_03
info:
  logo:
  description: >
    Альянс AR готов принять каждого активного игрока,
    Желающегося сражаться в Войне Кланов
    Все кланы AR входят в топ 100 кланов СНГ 
  social:
clans:
  - name: AncientRUSSIA
    tag: PGGPJPU8
  - name: AncientRUSSIA 2
    tag: 20VUPLO2
  - name: AncientRUSSIA 3
    tag: 8Y029LUC
  - name: AncientRussia 4
    tag: 9R99ULP8
```

**Comment by smlbiobot** [comment]
- Can’t give you `AR` as key because it’s already taken
- Wrong clan tag for one of your clans. Corrected it for you

```yml
name: AncientRUSSIA
key: ancientrussia
color: yellow
emblem: Pine_03
info:
  description: >
    Альянс AR готов принять каждого активного игрока,
    Желающегося сражаться в Войне Кланов
    Все кланы AR входят в топ 100 кланов СНГ
  social:
clans:
  - name: AncientRUSSIA
    tag: PGGPJPU8
  - name: AncientRUSSIA 2
    tag: 20VUPL02
  - name: AncientRUSSIA 3
    tag: 8Y028LUC
  - name: AncientRussia 4
    tag: 9R99ULP8
```
