### ISSUE TITLE
Update Tesle Italiane Family Config

### ISSUE THREAD

**Issue by alexior92** [RoyaleAPI/family-config#575]
name: Tesle Italiane
key: tesle
color: blue
emblem: Star_Bolt_03
sort: trophy
info:
  logo: https://pbs.twimg.com/profile_images/1423929985857896448/uShyJw0L_400x400.jpg
  description: >
    **Competitive and Ladder excellence through community-driven values.**
    Tesle Italiane is a mobile-focused eSports organization committed to empowering
    individuals through a supportive team environment.
    We look for talent that has the character to back it up.
    That talent is cultivated and supported through team-based growth strategies and
    passionate staff that care about player outcomes.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
    - twitter: https://twitter.com/TesleItaliane
    - twitch: https://www.twitch.tv/tesleontwitch
    - email: mailto:alessio.meomartini@gmail.com
clans:
  - name: Tesle Italiane
    tag: 2R8U0CR0
  - name: Tesle Academy
    tag: YCLP98UU
  - name: Tesle Academy 2
    tag: LVR0URRV
  - name: Tesle Academy 3
    tag: Q028RU09
  - name: Tesle Academy 4
    tag: YVYYC8P0
  - name: Tesle Academy 5
    tag: L8JV0QCC
  - name: Tesle Academy 6
    tag: LUYPJVLV
  - name: Tesle Academy 7
    tag: L8QLLOUV

**Comment by alexior92** [comment]
We have to update the config because we've created a new Academy (7). Thank you very much

**Comment by smlbiobot** [comment]
please use my config in the future. also are you sure that you want to use the logo you sent because your existing one looks better and has a transparent background.

```yml
name: Tesle Italiane
key: tesle
color: blue
emblem: Bolt_03
sort: trophy
info:
  logo: /static/img/brands/logo/tesle.png
  description: >
    **Competitive and Ladder excellence through community-driven values.**
    Tesle Italiane is a mobile-focused eSports organization committed to empowering
    individuals through a supportive team environment.
    We look for talent that has the character to back it up.
    That talent is cultivated and supported through team-based growth strategies and
    passionate staff that care about player outcomes.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
  - twitter: https://twitter.com/TesleItaliane
  - twitch: https://www.twitch.tv/tesleontwitch
  - email: mailto:alessio.meomartini@gmail.com
clans:
- name: Tesle Italiane
  tag: 2R8U0CR0
- name: Tesle Academy
  tag: YCLP98UU
- name: Tesle Academy 2
  tag: LVR0URRV
- name: Tesle Academy 3
  tag: Q028RU09
- name: Tesle Academy 4
  tag: YVYYC8P0
- name: Tesle Academy 5
  tag: L8JV0QCC
- name: Tesle Academy 6
  tag: LUYPJVLV
- name: Tesle Academy 7
  tag: L8QLL0UV
```
