### ISSUE TITLE
Demon™ ITA Family

### ISSUE THREAD

**Issue by CRAVI0** [RoyaleAPI/family-config#577]
```yaml
name: Demon™ ITA Family
key: Demon™ ITA
color: Black
emblem: A_Char_Pekka_02
info: 
  logo: 
  description: >
In **Demon™ ITA Family** crediamo che il rispetto dei nostri giocatori sia la cosa più importante.
2 clan competitivi: DemonStorm™ ITA (WAR Clan, Top 115 classifica italiana War) e DemoSoul™ ITA (LADDER Clan, Top 70 classifica italiana Ladder)
2 accademie: DemonHell ™ ITA e DemonCrew™ ITA.. 
- GRUPPI TELEGRAM della famiglia e dei singoli clan (info @CRAVI8) 
- Lingue parlate nel clan: Italiano, Inglese e Spagnolo.
Insomma non hai più scuse, unisciti a noi!

At **Demon ™ ITA Family** we believe that the respect of our players is the most important thing.
2 competitive clans: DemonStorm ™ ITA (WAR Clan, Top 115 Italian War ranking) and DemoSoul ™ ITA (LADDER Clan, Top 70 Italian Ladder ranking)
2 academies: DemonHell ™ ITA and DemonCrew ™ ITA ..
TELEGRAM GROUPS of the family and single clans (info @CRAVI8)
Languages ​​spoken in the clan: Italian, English and Spanish.
In short, you have no more excuses, join us!

  social:
    - telegram: https://t.me/CRAVI8
clans:
  - name: DemonStorm™ ITA
    tag: 9Q8QQ880
  - name: DemonSoul™️ ITA
    tag: LP0RQ2CJ
  - name: DemonHell ™ ITA
    tag: LP0P8RR9
  - name: DemonCrew™️ ITA
    tag: #LYR2C8QV
```

**Comment by smlbiobot** [comment]
can you just attach logo in a comment here?

**Comment by CRAVI0** [comment]
![DemonStorm™ ITA logo](https://user-images.githubusercontent.com/93670790/141266773-d3a762ed-9b64-4c07-a729-a52a8994a1c3.png)

**Comment by CRAVI0** [comment]
Good evening, I opened my request to add my family 8 days ago but it is not yet present along with the other families on RoyaleApi.
I would like to know why and if it depends on something that I am wrong in the request.
Thanks for your attention, I'm waiting for your reply.

**Comment by smlbiobot** [comment]
takes time

**Comment by smlbiobot** [comment]
```yml
name: Demon™ ITA Family
key: demon-ita
color: Black
emblem: A_Char_Pekka_02
info:
  logo: /static/img/brands/logo/demon-ita.png
  description: >
    In **Demon™ ITA Family** crediamo che il rispetto dei nostri giocatori sia la cosa più importante.


    2 clan competitivi: DemonStorm™ ITA (WAR Clan, Top 115 classifica italiana War) e DemoSoul™ ITA (LADDER Clan, Top 70 classifica italiana Ladder)


    2 accademie: DemonHell ™ ITA e DemonCrew™ ITA..


    - GRUPPI TELEGRAM della famiglia e dei singoli clan (info @CRAVI8)
    
    - Lingue parlate nel clan: Italiano, Inglese e Spagnolo.


    Insomma non hai più scuse, unisciti a noi!


    At **Demon ™ ITA Family** we believe that the respect of our players is the most important thing.
    2 competitive clans: DemonStorm ™ ITA (WAR Clan, Top 115 Italian War ranking) and DemoSoul ™ ITA (LADDER Clan, Top 70 Italian Ladder ranking)
    2 academies: DemonHell ™ ITA and DemonCrew ™ ITA ..
    TELEGRAM GROUPS of the family and single clans (info @CRAVI8)
    Languages ​​spoken in the clan: Italian, English and Spanish.
    In short, you have no more excuses, join us!

  social:
    - telegram: https://t.me/CRAVI8
clans:
  - name: DemonStorm™ ITA
    tag: 9Q8QQ880
  - name: DemonSoul™️ ITA
    tag: LP0RQ2CJ
  - name: DemonHell ™ ITA
    tag: LP0P8RR9
  - name: DemonCrew™️ ITA
    tag: #LYR2C8QV
```

**Comment by smlbiobot** [comment]
```yml
name: Demon™ ITA Family
key: demon-ita
color: black
emblem: A_Char_Pekka_02
info:
  logo: /static/img/brands/logo/demon-ita.png
  description: >
    In **Demon™ ITA Family** crediamo che il rispetto dei nostri giocatori sia la
    cosa più importante.


    2 clan competitivi: DemonStorm™ ITA (WAR Clan, Top 115 classifica italiana War)
    e DemoSoul™ ITA (LADDER Clan, Top 70 classifica italiana Ladder)


    2 accademie: DemonHell ™ ITA e DemonCrew™ ITA..


    - GRUPPI TELEGRAM della famiglia e dei singoli clan (info @CRAVI8)

    - Lingue parlate nel clan: Italiano, Inglese e Spagnolo.


    Insomma non hai più scuse, unisciti a noi!


    At **Demon ™ ITA Family** we believe that the respect of our players is the most
    important thing.
    2 competitive clans: DemonStorm ™ ITA (WAR Clan, Top 115 Italian War ranking)
    and DemoSoul ™ ITA (LADDER Clan, Top 70 Italian Ladder ranking)
    2 academies: DemonHell ™ ITA and DemonCrew ™ ITA ..
    TELEGRAM GROUPS of the family and single clans (info @CRAVI8)
    Languages ​​spoken in the clan: Italian, English and Spanish.
    In short, you have no more excuses, join us!

  social:
  - telegram: https://t.me/CRAVI8
clans:
- name: DemonStorm™ ITA
  tag: 9Q8QQ880
- name: DemonSoul™️ ITA
  tag: LP0RQ2CJ
- name: DemonHell ™ ITA
  tag: LP0P8RR9
- name: DemonCrew™️ ITA
  tag: LYR2C8QV

```
