### ISSUE TITLE
CR Adultes CR Change

### ISSUE THREAD

**Issue by AnkoWCR** [RoyaleAPI/family-config#578]
```yaml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: ![cradfrfantome](https://user-images.githubusercontent.com/92339610/141078386-0f213f22-01ae-44c0-8739-4eb6026742aa.png)
description: >
La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en GDC**.
Esprit d'équipe, fun & entraide.
**Rejoignez-nous**

clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: L0VCYRJ8
```

**Comment by AnkoWCR** [comment]
![cradfrfantome](https://user-images.githubusercontent.com/92339610/141078386-0f213f22-01ae-44c0-8739-4eb6026742aa.png)

**Comment by smlbiobot** [comment]
How is this different? the image seems correct.

Can you update with this config here:

```yml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: /static/img/brands/logo/cr-adultes-fr.png
  description: >
    La **Famille CR ADULTES FR** rassemble des clans d'adultes français **actifs en
    GDC**. Esprit d'équipe, fun & entraide. **Rejoignez-nous!**

    Lien icône Maison **Decks méta** (meilleurs decks influencés par l'équilibrage
    de la saison).

  social:
  - website: https://royaleapi.com/decks/popular?type=TopLadder&time=7d

clans:
- name: CR ADULTES FR
  tag: 9JV9GGC0
- name: CR ADULTES FR 2
  tag: YJVVPR98
- name: CR ADULTES FR 3
  tag: L00CYCQV
- name: CR ADULTES FR 4
  tag: L0VCYRJ8

```
