### ISSUE TITLE
Clan Family

### ISSUE THREAD

**Issue by PlaceForDarkness** [RoyaleAPI/family-config#579]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:    
key: unnamed
color: grey
emblem: Twin_Peaks_02
info:
  logo:
  description: >
    Clan attempt formed by a small group of friends, after unsuccessful attempts to access a "competitive" clan with a vision to form something more than a simple clan (There was one previously but it was dissolved due to the moderation of it) ~ CC / Darkness.


   
  social:
  
    - discord: https://discord.gg/uGkk8SzEqV
 
    - instagram: https://instagram.com/placefordarkness

    - application: https://t.me/UnnamedCR

clans:
  - name:    
    tag: L8YUJG29
```
