### ISSUE TITLE
[Update] Team Liquid NA

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/family-config#58]
```yaml
name: Team Liquid NA
key: liquidna
color: blue
emblem: flag_d_04
info:
  logo: https://www.dropbox.com/sh/egbtgmh5lkgbobx/AAAQZtRRjdBA78tqlyDNLC3Ua/Style%20Guides%20%26%20Logos/Team%20Liquid/Logos/png?dl=0&preview=1_primary_logo_icon.png&subfolder_nav_tracking=1
  description: >
    *Join us in [discord](https://tl.gg/mobile) for an active environment, tournaments, events, and more!*


    With **more than 40 top clans across the globe**, Team Liquid has established itself as one of the most prominent clan families in Clash Royale. Our broad approach to the game allows all kinds of players to enjoy our activities; even Brawl Stars, Critical Ops and other game's fans have a spot in our community! **#LetsGoLiquid**
  social:
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - discord: https://tl.gg/mobile
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - instagram: https://www.instagram.com/teamliquid/
    - facebook: https://www.facebook.com/teamliquid/
    - twitter: https://twitter.com/TeamLiquid
clans:
  - name:  Team Liquid
    tag: 9YU2PQRV
  - name: Team Liquid 2
    tag: V8GRLCQ
  - name: TL Inferno
    tag: 9CJ9YGPL
  - name: TL DREADNOUGHT
    tag: P00Q0VUV
  - name: TL Cyclone
    tag: 9QVYYYV0
  - name: TL Smash Elite
    tag: 820QC80V
  - name: TL Nitro
    tag: 9YYLQ99L
  - name: TL Plasma
    tag: PGQY9Q9C
  - name: TL Titans
    tag: PGPQQ8UV
sort: trophy
```
