### ISSUE TITLE
Nova QC

### ISSUE THREAD

**Issue by Poup1017** [RoyaleAPI/family-config#581]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Nova QC
key:(https://royaleapi.com/clan/8J9YU9CC)
color: blue
emblem: https://cdn.royaleapi.com/static/img/badge/legendary-1/Star_Shine_02.png?t=075d42e6c
info: Guerre de clan
  logo:   ![received_958718884987514](https://user-images.githubusercontent.com/93715501/141685345-9ee6b932-0a42-4c41-bf4c-7ec937737d1e.gif)

description: >Nova QC est une grande famille qui est axé sur les guerres de clan. Très actif et compétitif. Fr/An. Top local en classement de guerre. Nova QC is a clan where clan war are mandatory. Active and competitive. Fr/En. Top local in war clan.    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.com/channels/678831964123430925/678831964123430934

clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
![received_958718884987514](https://user-images.githubusercontent.com/93715501/141685731-66ffb547-5e35-4fa4-9d93-b5a613979f4a.gif)

```

**Comment by smlbiobot** [comment]
Your discord link won’t work. it should be in this format: ```https://discord.gg/vfoijasdoiuf``` (invite link) channel links won’t link

**Comment by smlbiobot** [comment]
```yml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: Nova QC est une grande famille qui est axé sur les guerres de clan. Très actif et compétitif. Fr/An. Top local en classement de guerre. Nova QC is a clan where clan war are mandatory. Active and competitive. Fr/En. Top local in war clan.

clans:
- name: Nova QC
  tag: 8J9YU9CC
- name: Nova QC ☆ École
  tag: PPJQQ8YJ
- name: Nova QC ☆ 3
  tag: LPL282UQ
- name: Nova QC ☆ 4
  tag: Y2V29L8L
- name: Nova QC ☆ 5
  tag: YV0YLUGL
- name: Nova QC ☆ 6
  tag: Q20UYLG9

```
