### ISSUE TITLE
Royale Con Queso

### ISSUE THREAD

**Issue by MiniGregoriio** [RoyaleAPI/family-config#582]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Royale Con Queso
key: queso
color: blue
emblem: Crown_02
info:
  description: >
  Somos una família de clanes de Clash Royale que nació el 5 de 
  enero de 2016, un día después del lanzamiento en fase Beta 
  del juego. Desde ese momento hemos tenido una presencia 
  constante en el ranking local de clanes por trofeos y algunos 
  de nuestros miembros son jugadores destacados en los 
  rankings locales individuales de diversos países.
  social:
  - discord: https://discord.gg/rcq
  - twitter: https://twitter.com/RoyaleQueso
  - instagram: https://instagram.com/royale_queso
  - website: https://royaleconqueso.com
clans:
- name: RoyaleConQueso
  tag: PQJ2Y
- name: RoyaleSinQueso
  tag: '929092'
- name: RoyaleConBBQ
  tag: 2802GPP9
- name: RoyaleJalapeño
  tag: 8V2C0RL2
- name: RoyaleConHuevo
  tag: RLU9URP
- name: RoyalePepinillo
  tag: LJQLJGR
- name: RoyaleConBacon
  tag: 22QUCG0
- name: RoyaleConJamon
  tag: CJQGQ8R
- name: RoyaleConPollo
  tag: L2JCUL99
- name: RoyaleConZEN
  tag: LCLR00RV 
- name: Arena Quesito
  tag: 8PQQ0RVP
- name: Estadio Quesito
  tag: YUGUJ0JQ 
```

**Comment by smlbiobot** [comment]
```yml
name: Royale Con Queso
key: queso
color: blue
emblem: Crown_02
info:
  description: >
    Somos una família de clanes de Clash Royale que nació el 5 de
    enero de 2016, un día después del lanzamiento en fase Beta
    del juego. Desde ese momento hemos tenido una presencia
    constante en el ranking local de clanes por trofeos y algunos
    de nuestros miembros son jugadores destacados en los
    rankings locales individuales de diversos países.
  social:
  - discord: https://discord.gg/rcq
  - twitter: https://twitter.com/RoyaleQueso
  - instagram: https://instagram.com/royale_queso
  - website: https://royaleconqueso.com
clans:
- name: RoyaleConQueso
  tag: PQJ2Y
- name: RoyaleSinQueso
  tag: '929092'
- name: RoyaleConBBQ
  tag: 2802GPP9
- name: RoyaleJalapeño
  tag: 8V2C0RL2
- name: RoyaleConHuevo
  tag: RLU9URP
- name: RoyalePepinillo
  tag: LJQLJGR
- name: RoyaleConBacon
  tag: 22QUCG0
- name: RoyaleConJamon
  tag: CJQGQ8R
- name: RoyaleConPollo
  tag: L2JCUL99
- name: RoyaleConZEN
  tag: LCLR00RV
- name: Arena Quesito
  tag: 8PQQ0RVP
- name: Estadio Quesito
  tag: YUGUJ0JQ
```
