### ISSUE TITLE
The expendables family clan

### ISSUE THREAD

**Issue by Gilby271** [RoyaleAPI/family-config#583]
Consumer https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: The Expendables family clan
key:Expendables 
color:pink 
emblem:bolt_02
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    We are The Expendables… we are growing clan and are starting to branch out into having many clans we are casual base clan but we do take part in wars and only really looking to recruit players who will take part in wars as we build stronger together individually and as a clan. Must also be active and donate cards aswell. 


clans:
  - name: The Expendables 
    tag: PGQJVV2C
  - name: Expendables#2
    tag:QJ9LOYLG
  
```

**Comment by smlbiobot** [comment]
```yml
name: The Expendables family clan
key: expendables
color: pink
emblem: bolt_02
info:
  description: >
    We are The Expendables… we are growing clan and are starting to branch out into having many clans we are casual base clan but we do take part in wars and only really looking to recruit players who will take part in wars as we build stronger together individually and as a clan. Must also be active and donate cards aswell.


clans:
  - name: The Expendables
    tag: PGQJVV2C
  - name: Expendables#2
    tag: QJ9LOYLG
```
