### ISSUE TITLE
Update to #FightClub Family / YAML Config

### ISSUE THREAD

**Issue by Mutoi1** [RoyaleAPI/family-config#584]
```yaml
name: #FightClub Family
key: fightclub
color: purple
emblem: Skull_01
info:
  logo:
  description: >
    A drama free group of fun loving folks, focused on warring. From casual to competitive, there's something for everyone!
  social:
    - discord: http://discord.gg/SuM7BgNck6
clans:
  - name: #FightClub
    tag: 8JP082C
  - name: #FightClub2
    tag: 2CLVG9V9
  - name: #FightClub3
    tag: 9YVJ98CV
  - name: #FightClub4
    tag: PJYPUVGJ
  - name: #FightClub69
    tag: PCP929JU
```

**Comment by smlbiobot** [comment]
you have to quote your names because `#` is a special character in yaml

```yml
name: '#FightClub Family'
key: fightclub
color: purple
emblem: Skull_01
info:
  description: >
    A drama free group of fun loving folks, focused on warring. From casual to competitive, there's something for everyone!
  social:
    - discord: http://discord.gg/SuM7BgNck6
clans:
- name: '#FightClub'
  tag: 8JP082C
- name: '#FightClub2'
  tag: 2CLVG9V9
- name: '#FightClub3'
  tag: 9YVJ98CV
- name: '#FightClub4'
  tag: PJYPUVGJ
- name: '#FightClub69'
  tag: PCP929JU
```
