### ISSUE TITLE
Upper Echelon

### ISSUE THREAD

**Issue by Sauce4068** [RoyaleAPI/family-config#587]
```yaml
name: Upper Echelon
key: ue
color: yellow
emblem: flag_j_03
info: 
  description: >
    **Upper Echelon** is a newly formed, mature, ladder focused Clash Royale clan. With war being optional, but encouraged, we strive to landing a spot on the gloal leaderboard.
 social:
    - twitter: https://twitter.com/UpperEchelonCR
    - discord: https://discord.gg/FsPBrXdq2d
clans:
  - name: Upper Echelon
    tag: Q8P89RGG
```
