### ISSUE TITLE
Platzhirsche

### ISSUE THREAD

**Issue by pampelsine** [RoyaleAPI/family-config#588]
```yaml
name: Platzhirsche
key: platzhirsche
color: red
emblem: fugi_04
info:
  logo: 
![5E6D86FE-3E76-4448-AA5B-7BA1ED9626FF](https://user-images.githubusercontent.com/95136210/143686460-8a46107b-32c6-43d1-81d3-619cd0b6969a.png)

  description: >
Die Platzhirsche wurden Anfang 2021 gegründet und wir wachsen seit dem vor allem in der Gemeinschaft. Bei uns wird das GEMEINSAM noch groß geschrieben. Hier gibts jeden Tag was zu lachen und wenn auch du eine Tasche voll Humor mitbringst, dann schließe dich uns an. 

clans:
  - name: Platzhirsche
    tag: YCGUCJR9
  - name: Platzhirsche2.0
    tag:  #LPPPG80J

**Comment by smlbiobot** [comment]
```yml
name: Platzhirsche
key: platzhirsche
color: red
emblem: fugi_04
info:
  logo: /static/img/brands/logo/platzhirsche.png
  description: >
    Die Platzhirsche wurden Anfang 2021 gegründet und wir wachsen seit dem vor allem in der Gemeinschaft. Bei uns wird das GEMEINSAM noch groß geschrieben. Hier gibts jeden Tag was zu lachen und wenn auch du eine Tasche voll Humor mitbringst, dann schließe dich uns an.
clans:
  - name: Platzhirsche
    tag: YCGUCJR9
  - name: Platzhirsche2.0
    tag:  3LPPPG80J
```

**Comment by smlbiobot** [comment]
```yml
name: Platzhirsche
key: platzhirsche
color: red
emblem: fugi_04
info:
  logo: /static/img/brands/logo/platzhirsche.png
  description: >
    Die Platzhirsche wurden Anfang 2021 gegründet und wir wachsen seit dem vor allem in der Gemeinschaft. Bei uns wird das GEMEINSAM noch groß geschrieben. Hier gibts jeden Tag was zu lachen und wenn auch du eine Tasche voll Humor mitbringst, dann schließe dich uns an.
clans:
  - name: Platzhirsche
    tag: YCGUCJR9
  - name: Platzhirsche2.0
    tag:  LPPPG80J
```
