### ISSUE TITLE
The Realms

### ISSUE THREAD

**Issue by Willmatt27** [RoyaleAPI/family-config#589]
```yaml
name: The Realms
key: realms
color: red
emblem: A_Char_MiniPekka_02
info:
  logo: https://www.google.com/search?q=marvel+realms&rlz=1C1RXQR_enUS968US969&sxsrf=AOaemvIgEBApAKltEiRGw02tZtyf6DBo7A:1638200350879&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiVjvDv8730AhWysDEKHd9kCgMQ_AUoA3oECAIQBQ&biw=767&bih=704&dpr=1.25#imgrc=v3wFj61EIVY34M
    
  social:
    - twitch: https://www.twitch.tv/moneymitch2198
clans:
  - name: #PLAN£T!£A
    tag: LG8PRJ2Y
  - name: #PLAN£T!CŁA§H
    tag: Q2UYP8PP
  - name: #PLAN£T!MΦΦИ
    tag: QQU2JLC8
  - name: #PLAN£T!TØWERS
    tag: QJUR9VOL
```

**Comment by smlbiobot** [comment]
google search is not a valid logo

**Comment by smlbiobot** [comment]
```yml
name: The Realms
key: realms
color: red
emblem: A_Char_MiniPekka_02
info:
  social:
    - twitch: https://www.twitch.tv/moneymitch2198
clans:
  - name: "#PLAN£T!£A"
    tag: LG8PRJ2Y
  - name: "#PLAN£T!CŁA§H"
    tag: Q2UYP8PP
  - name: "#PLAN£T!MΦΦИ"
    tag: QQU2JLC8
  - name: "#PLAN£T!TØWERS"
    tag: QJUR9VOL
```
