### ISSUE TITLE
[Update] Team Liquid LATAM (No more LAN & LAS)

### ISSUE THREAD

**Issue by Zehntry** [RoyaleAPI/family-config#59]
```yaml
name: Team Liquid LATAM
key: liquidla
color: blue
emblem: flag_d_04
info:
  logo: https://www.dropbox.com/sh/egbtgmh5lkgbobx/AAAQZtRRjdBA78tqlyDNLC3Ua/Style%20Guides%20%26%20Logos/Team%20Liquid/Logos/png?dl=0&preview=1_primary_logo_icon.png&subfolder_nav_tracking=1
  description: >
    *¡Únete a nuestro [discord](https://tl.gg/mobile) para disfrutar de una comunidad activa, tener eventos semanales, torneos, y mucho más!*


    Con **más de 40 clanes top alrededor del mundo**, Team Liquid se ha establecido como una de las familias de clanes más prominentes en Clash Royale. Nuestro amplio enfoque del juego permite a todo tipo de jugadores disfrutar de nuestras actividades; incluso fans de Brawl Stars, Critical Ops y otros juegos ¡encontrarán un lugar en nuestra comunidad! **#LetsGoLiquid**
  social:
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - discord: https://tl.gg/mobile
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - instagram: https://www.instagram.com/teamliquid/
    - facebook: https://www.facebook.com/teamliquid/
    - twitter: https://twitter.com/TeamLiquid
clans:
  - name:  TeamLiquid ARG
    tag: P22C00YR
  - name: TeamLiquid CO
    tag: 9QLLG92U
  - name: TeamLiquid SV
    tag: 8JG8Y20R
  - name: TeamLiquid SV2
    tag: 99UL0CRJ
  - name: TeamLiquid SV3
    tag: 9LPJUVYJ
  - name: TeamLiquid CUBA
    tag: 9QL02L9U
  - name: TeamLiquid VE
    tag: VOGL8C8
  - name: TeamLiquid VE2
    tag: 889CQU88
  - name: TeamLiquid EC
    tag: PCJ9800L
  - name: TeamLiquid PE X
    tag: 9YR8L8R8
  - name: TeamLiquid MX
    tag: 8URY28UC
  - name: TeamLiquid MX2
    tag: 92J9RY9C
  - name: TeamLiquid MX F
    tag: P2PP8L80
  - name: TeamLiquid MX R
    tag: 9PPJJVLQ
  - name: TeamLiquid MX Z
    tag: 9Q88CP22
  - name: TeamLiquid UY
    tag: PC89QUPC
```

**Comment by smlbiobot** [comment]
updated

**Comment by Zehntry** [comment]
```yaml
name: Team Liquid LATAM
key: liquidla
color: blue
emblem: flag_d_04
info:
  logo: /static/img/brands/logo/team-liquid-icon.png
  description: >
    *¡Únete a nuestro [discord](https://tl.gg/mobile) para disfrutar de una comunidad activa, tener eventos semanales, torneos, y mucho más!*


    Con **más de 40 clanes top alrededor del mundo**, Team Liquid se ha establecido como una de las familias de clanes más prominentes en Clash Royale. Nuestro amplio enfoque del juego permite a todo tipo de jugadores disfrutar de nuestras actividades; incluso fans de Brawl Stars, Critical Ops y otros juegos ¡encontrarán un lugar en nuestra comunidad! **#LetsGoLiquid**
  social:
    - website: https://www.teamliquid.com/
    - twitch: https://www.twitch.tv/teamliquid
    - discord: https://tl.gg/mobile
    - youtube: https://www.youtube.com/teamliquid
    - reddit: https://www.reddit.com/r/TeamLiquid/
    - instagram: https://www.instagram.com/teamliquid/
    - facebook: https://www.facebook.com/teamliquid/
    - twitter: https://twitter.com/TeamLiquid
clans:
  - name:  TeamLiquid ARG
    tag: P22C00YR
  - name: TeamLiquid CO
    tag: 9QLLG92U
  - name: TeamLiquid SV
    tag: 8JG8Y20R
  - name: TeamLiquid SV2
    tag: 99UL0CRJ
  - name: TeamLiquid SV3
    tag: 9LPJUVYJ
  - name: TeamLiquid CUBA
    tag: 9QL02L9U
  - name: TeamLiquid VE
    tag: V0GL8C8
  - name: TeamLiquid VE2
    tag: 889CQU88
  - name: TeamLiquid EC
    tag: PCJ9800L
  - name: TeamLiquid PE X
    tag: 9YR8L8R8
  - name: TeamLiquid MX
    tag: 8URY28UC
  - name: TeamLiquid MX2
    tag: 92J9RY9C
  - name: TeamLiquid MX F
    tag: P2PP8L80
  - name: TeamLiquid MX R
    tag: 9PPJJVLQ
  - name: TeamLiquid MX Z
    tag: 9Q88CP22
  - name: TeamLiquid UY
    tag: PC89QUPC
```
