### ISSUE TITLE
Nova QC

### ISSUE THREAD

**Issue by Poup1017** [RoyaleAPI/family-config#591]
```yml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: Axé sur les GDC (TOP MONDE), Nova QC est constitué de 7 clans pour tous les niveaux. 350 membres actifs et unis contribuent à la croissance constante de cette grande famille. Respect, entraide et plaisir garantis. Facebook/Messenger/Discord.

Focus on Clan Wars (TOP WORLD), Nova QC is made up of 7 clans for all levels. 350 active and united members contribute to the constant growth of this large familly. Respect, help between members and pleasure guaranteed. Facebook/Messenger/Discord.

clans:
- name: Nova QC
  tag: 8J9YU9CC
- name: Nova QC ☆ École
  tag: PPJQQ8YJ
- name: Nova QC ☆ 3
  tag: LPL282UQ
- name: Nova QC ☆ 4
  tag: Y2V29L8L
- name: Nova QC ☆ 5
  tag: YV0YLUGL
- name: Nova QC ☆ 6
  tag: Q20UYLG9
- name: Nova QC ☆ 7
  tag: LCQJRP2Q

_Originally posted by @smlbiobot in https://github.com/RoyaleAPI/family-config/issues/581#issuecomment-980489048_

**Comment by Poup1017** [comment]
Already send you an issue for Nova QC and it was close. I wanted to add a clan and change the description. Hope this will be alright!

**Comment by smlbiobot** [comment]
```yml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: >
    Axé sur les GDC (TOP MONDE), Nova QC est constitué de 7 clans pour tous les niveaux. 350 membres actifs et unis contribuent à la croissance constante de cette grande famille. Respect, entraide et plaisir garantis. Facebook/Messenger/Discord.


    Focus on Clan Wars (TOP WORLD), Nova QC is made up of 7 clans for all levels. 350 active and united members contribute to the constant growth of this large familly. Respect, help between members and pleasure guaranteed. Facebook/Messenger/Discord.

clans:
- name: Nova QC
  tag: 8J9YU9CC
- name: Nova QC ☆ École
  tag: PPJQQ8YJ
- name: Nova QC ☆ 3
  tag: LPL282UQ
- name: Nova QC ☆ 4
  tag: Y2V29L8L
- name: Nova QC ☆ 5
  tag: YV0YLUGL
- name: Nova QC ☆ 6
  tag: Q20UYLG9
- name: Nova QC ☆ 7
  tag: LCQJRP2Q
```
