### ISSUE TITLE
Clash Royale Clan Family Crying Fire application

### ISSUE THREAD

**Issue by adamlam980** [RoyaleAPI/family-config#592]
Fill in the configuration below:

name: Crying Fire Dynasty
key: Crying Fire
color: blue
emblem: Flame_04
info:
  logo: ![Flame_04](https://user-images.githubusercontent.com/84809573/144702326-a31b21e6-5f0c-4d48-b1e5-62bb8aa7866b.png)
  description: >
The Crying Fire Dynasty made of 5 clans has been dominating Clash Royale for many years. Home to renowned war players our promise is that players joining us will be sure to flourish in their time here. We all share the exact same values: Honesty, Fair Play,  Perserverance and Passion. We will always be looking out for each other making sure we all improve as a family and most importantly have fun! Make sure you join our dynasty right now and become a Crying Fire Legend!

  social:
    - discord: http://discord.gg/TxPFfcsURy
    - application: http://discord.gg/TxPFfcsURy
    - email: mailto: CryingFireDynasty@gmail.com
clans:
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Lava axes
    tag: LGQVGVGL
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Premium
    tag: LJCRCRCP
```
![Flame_04 (1)](https://user-images.githubusercontent.com/84809573/144702599-250b5767-8ef0-43ed-9b1b-9829ee0063a1.png)

**Comment by smlbiobot** [comment]
```yml
name: Crying Fire Dynasty
key: crying-fire
color: blue
emblem: Flame_04
info:
  logo: /static/img/badge/legendary-1/Flame_04.png
  description: >
      The Crying Fire Dynasty made of 5 clans has been dominating Clash Royale for many years. Home to renowned war players our promise is that players joining us will be sure to flourish in their time here. We all share the exact same values: Honesty, Fair Play,  Perserverance and Passion. We will always be looking out for each other making sure we all improve as a family and most importantly have fun! Make sure you join our dynasty right now and become a Crying Fire Legend!


  social:
    - discord: https://discord.gg/TxPFfcsURy
    - application: https://discord.gg/TxPFfcsURy
    - email: mailto:CryingFireDynasty@gmail.com
clans:
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Lava axes
    tag: LGQVGVGL
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Premium
    tag: LJCRCRCP



```
