### ISSUE TITLE
ComeBack family update

### ISSUE THREAD

**Issue by EyesTv** [RoyaleAPI/family-config#593]
name: ComeBack
key: CB
color: Blue
emblem: Bolt_03
sort: trophy
info:
  logo: ![CB_logo](https://user-images.githubusercontent.com/69396421/105639545-495fc900-5e79-11eb-8803-e0ef258bcf77.png)
  description: >
    ComeBack is a French clan family. The first clan, **ComeBack** was created the 03/21/2018 by [big ouf](https://royaleapi.com/player/9UR9GPCQ). 
    It started out as a clan of friends, then we quickly revealed great potential across the world rankings as well as in competition. 
    After the success of the clan, other clans were created later ComeBack 2, ComeBack 3 and ComeBack 4, ComeBack 5 et Comebackademie.

  social:
   - discord: https://discord.gg/dB9pKDVVYS
   - twitter: https://twitter.com/comeback__cr/ 
        
clans:
  - name: ComeBack
    tag: 989VGGV8
  - name: ComeBack 2
    tag: 9LY2RCUQ
  - name: ComeBack 3
    tag: Y0RYYL8J 
  - name: ComeBack 4
    tag: Y2LPVVGG
  - name: ComeBack 5
    tag: LVG9QCP9
  - name: ComeBackacademie
    tag: QGPU2GCP

**Comment by smlbiobot** [comment]
use this in the future:

```yml
name: ComeBack
key: CB
color: blue
emblem: Bolt_03
sort: trophy
info:
  logo: /static/img/brands/logo/come-back.png
  description: >
    The **ComeBack** clan was created the 03/21/2018 by [big ouf](https://royaleapi.com/player/9UR9GPCQ).
    It started out as a clan of friends, then we quickly revealed great potential
    across the world rankings as well as in competition.
    After the success of the clan, other clans were created later ComeBack 2, ComeBack
    3 and ComeBack 4.

  social:
  - discord: https://discord.gg/dB9pKDVVYS
  - twitter: https://twitter.com/comeback__cr/

clans:
  - name: ComeBack
    tag: 989VGGV8
  - name: ComeBack 2
    tag: 9LY2RCUQ
  - name: ComeBack 3
    tag: Y0RYYL8J
  - name: ComeBack 4
    tag: Y2LPVVGG
  - name: ComeBack 5
    tag: LVG9QCP9
  - name: ComeBackacademie
    tag: QGPU2GCP
```
