### ISSUE TITLE
ADD MIF Clan Family

### ISSUE THREAD

**Issue by eleconte13** [RoyaleAPI/family-config#595]
Hi !
Can you add our clan family please ?
Thanks.

```yaml
name: Made in France Family
key: mif
color: blue
emblem: flag_k_01
info:
  logo: /static/img/badge/flag_k_01.png
  description: >
    Le clan Made in France a été créé le premier jour du jeu et il est toujours dirigé par son créateur. Depuis le temps la famille s'est agrandie, structurée et compte parmi les grandes familles françaises. Résolument tourné vers les GDC, nous rassemblons des joueurs adultes - 30/40 ans en moyenne - qui souhaites s’impliquer et performer tout en conservant une ambiance familiale ! Notre structure permet d'accueillir des joueurs de tous niveaux : Du combattant expérimenté au novice qui souhaite se former auprès des meilleurs joueurs pour intégrer à terme nos clan principaux. Alors si l'aventure vous dit, rejoignez-nous !
  social:
    - discord: https://discord.gg/k97B9ngAtp
clans:
  - name: Made In France
    tag: 8JG0RGU
  - name: Les Gaulois
    tag: 8C02UC9Q
  - name: Made iin France
    tag: Q2QRJC88
  - name: Made 3in France
    tag: Q9CCGCGJ
```
