### ISSUE TITLE
Update EuroElite Family

### ISSUE THREAD

**Issue by Lufoxy** [RoyaleAPI/family-config#597]
```yaml
name: EuroElite
key: euroelite
color: orange
emblem: Twin_Peaks_01
info:
  logo: https://drive.google.com/file/d/1hzHA5DCY9MSYTlxzJ6vlh7bjOHm6X7GZ/view?usp=sharing
  description: >
🔰 **EuroElite • Clash Royale** 🔰
Hinter EuroElite steckt ein großes Mobile Gaming Unternehmen aus Deutschland 🇩🇪, 
welches im Bereich CR besonders glänzt.
Wir sind mit 2 Clans und einem eSports Team perfekt ausgestattet. 
Mit dem 1. Clan wollen wir immer weiter die 🇩🇪 Rangliste erklimmen 
und uns mit unserem Team EuroElite Spirit auf Profiebene beweisen.

Werde doch ein Teil von uns und Bewirb dich auf Discord. 👍
 social:
    - website: https://clashroyale.euroelite.online/
    - discord: http://discord.gg/EuroElite
    - twitter: https://twitter.com/EuE_Spirit
    - twitch: https://twitch.tv/neon_pheonix_
    clans:
  - name: EuroElite
    tag: Q99JC8PU
  - name: EuroElite 2
    tag: LL800J89
```
