### ISSUE TITLE
LoSt Clan

### ISSUE THREAD

**Issue by MandalaCR** [RoyaleAPI/family-config#598]
```yaml
name: LoSt Clan Family
key: lostclan
color: blue
emblem: Sword_01
info:
  description: >
Welcome to the LoSt Clan family! Founded in March of 2016, LoSt Clan welcomes in a community of players of all skill levels! LoSt Clan is currently expanding with 1 competitive clan and 1 casual clan, with more to come in the future! 
  social:
    - discord: https://discord.gg/k42nBtAGvN
clans:
    - name: LoSt Clan 
    - tag: R20CCU
    - name: LoSt Clan Minis
    - tag: LJLROQGO
'''

**Comment by smlbiobot** [comment]
```yml
name: LoSt Clan Family
key: lostclan
color: blue
emblem: Sword_01
info:
  description: >
    Welcome to the LoSt Clan family! Founded in March of 2016, LoSt Clan welcomes in a community of players of all skill levels! LoSt Clan is currently expanding with 1 competitive clan and 1 casual clan, with more to come in the future!
  social:
    - discord: https://discord.gg/k42nBtAGvN
clans:
  - name: LoSt Clan
    tag: R20CCU
  - name: LoSt Clan Minis
    tag: LJLR0QG0
```
