### ISSUE TITLE
[UPDATE] Nova UK

### ISSUE THREAD

**Issue by Ahek** [RoyaleAPI/family-config#599]
```yaml
name: Nova UK
key: novauk
color: purple
emblem: Star_Shine_03
info:
  logo: https://cdn.discordapp.com/attachments/717730991187427368/902264402391236648/IMG_0145.jpg
  description: >
      A group of (mostly) Europeans enjoying the royal clash. Check out or clans or apply for an esports team tryout in our discord
  social:
    - twitter: https://twitter.com/NovaEsportsUKB
    - discord: https://discord.gg/N66ExB4Ugh
clans:
  - name: Nova l UK
    tag: 2JVJRYP
  - name: Nova UK 2
    tag: RY89JRY
  - name: Nova UK 3
    tag: PJYUC0CU
  - name: Nova UK 4
    tag: L89L8RPG
```
