### ISSUE TITLE
royalapi.yml

### ISSUE THREAD

**Issue by CRTarg** [RoyaleAPI/family-config#601]
```yaml
name: CRTarg - Clash Royale Team Argentina
key: crtarg
color: blue
emblem: Star_Shine_02
info:
  logo: https://drive.google.com/file/d/11sGFw5Y6LNG8IYV9RRr22jlbFMGdXloz/view?usp=sharing
  description: >
    Este clan reúne a los jugadores de todo el territorio argentino.
    Quedan invitados a participar de modo activo en nuestro clan para sumar medallas y honor.
    **Únete al clan, por honor y gloria.**
  social:
    - twitter: http://twitter.com/@CRT_arg
    - youtube: https://www.youtube.com/channel/UCIUBUb5A2ElIfFIGQupfDoQ
    - website: https://linktr.ee/crtarg
    - facebook: https://www.facebook.com/ClashRoyaleTeamArgentina/
    - email: mailto:crtarg@gmail.com
    - discord: https://discord.gg/uDwDSVj9Vb
clans:
  - name: argentina
    tag: YV2PCLUC
```
