### ISSUE TITLE
AnZuSrRhANe Family Clan

### ISSUE THREAD

**Issue by AnZuSrRhANe** [RoyaleAPI/family-config#602]
```yaml


name: AnZuSrRhANe Clan Family
key: AnZuSrRhANe
color: blue
emblem: Flame_04


info: 
  logo: https://www.nicepng.com/png/detail/133-1332061_cold-cool-blue-flame-logo.png
  description: >
    The AnZuSrRhANe clan family is an Australian network of clans. Since creation, we as clans and individual players have grown immensely and continue to today. Our clans are friendly with high donations and active war participation. We most importantly enjoy ourselves!


  social:
 
    - discord: https://discord.com/invite/tR6ABnwC 
 

clans:
  - name: AnZuSRhAn
    tag: L20RQLJL
  - name: AnZuSRhANe
    tag: L8280PG0
  - name: AnZuSrRhANe
    tag: G2R8YRGP


```
