### ISSUE TITLE
QLASH Pro 

### ISSUE THREAD

**Issue by CriGio** [RoyaleAPI/family-config#603]
```yaml
name: QLASH Pro
key: qlash-pro
color: orange
emblem: Diamond_Star_01
info:
  logo: /static/img/brands/logo/qlash.png
  description: >
	QLASH is an international Esports company focused on the Community.
        We are working on Clash Royale since 5 years, discovering talents and supporting lots of players around the World!


  social:
    - discord: https://discord.com/invite/qlash-clashroyale
    - website: https://qlash.gg
    - twitter: https://twitter.com/QLASHcr
    - facebook: https://www.facebook.com/QLASHItalia
    - instagram: https://www.instagram.com/qlash_clashroyale
    - application: https://deeplink.qlash.gg/3Txo2trPZDeo1dh48
    - email: mailto:cristiano.spada@qlash.gg
clans:
  - name: QLASH Eclipse
    tag: P0LLG9RG
  - name: QLASH Sentry
    tag: 9QY9JG09
  - name: QLASH Hades
    tag: 9U2UYRQU
  - name: QLASH Power
    tag: YQ2Q9VGG
  - name: QLASH Reality
    tag: LY2LGR29
  - name: QLASH Danger
    tag: 98PL02LC
```

![qlash](https://user-images.githubusercontent.com/6716792/147855178-40f35962-d8a1-4db7-baa5-3539be927efb.png)
