### ISSUE TITLE
Undefined - Update

### ISSUE THREAD

**Issue by C00ls0ul** [RoyaleAPI/family-config#604]
```yaml
name: Undefined
key: undefined
color: black
emblem: flag_j_03
info:
  logo: https://media.discordapp.net/attachments/296493772383191040/741071441331748904/Undefined_Logo.png
  description: >
    🌟🌟Active, Loyal, & Respectful🌟🌟<br/>

    ⭐Clan Family Discord - UND⭐Esports <br/>

    Team Discord - K7VPRM2⭐Twitter - <br/>

    @Undefined_CR⭐🌠4#1⭐<br/>
  social:
    - discord: https://discord.gg/UND
    - discord: https://discord.gg/K7VPRM2
    - twitter: https://twitter.com/Undefined_CR
    - youtube: https://www.youtube.com/channel/UCz6I6EIXh_T9mMD-8_RiZgA
clans:
  - name: Undefined
    tag: 8GQGUJ
  - name: Defined
    tag: QLRGRU9P
  - name: Redefined
    tag: YGGPRUCU
  - name: Predefined
    tag: 9VVLL09G
  - name: Misdefined
    tag: L28G2UV0
```
