### ISSUE TITLE
Center Court Clanfamilie

### ISSUE THREAD

**Issue by MamaMuc** [RoyaleAPI/family-config#605]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Center Court Clanfamilie
key: CC
color: green
emblem: Clover_02
info:
  description: >
      Die **Center Court Clanfamilie** wurde im Oktober 2017 mit dem Main Clan Center Court       
      gegründet und ist aufgrund des Zusammenhalts und der damit einhergehenden Erfolge stetig 
      gewachsen. Im Fokus befinden sich seither die Clankriege. Teamgeist sowie zuverlässige 
      Teilnahme sind dabei gleichermaßen grundlegend wie der respektvolle Umgang miteinander. 
      Ob Clankrieg oder Ladder, jedes Mitglied der Familie wird im Chat oder auch bei Discord gern 
      dabei unterstützt, eigene Ziele zu erreichen und sich weiterzuentwickeln. Die Clanfamilie bietet 
      im Rahmen der Clanstruktur ebenso die Möglichkeit von Pausen beim CK oder gar einer 
      generellen Auszeit, wenn dies erforderlich ist (Urlaub, Familie, RL, Beruf).
      Egal welcher unserer Clans, bei Center Court ist alles im Fluss. Alle Clans betrachten wir als 
      gleichwertig. Unterschiedliche Ligen bedeuten kein besser oder schlechter. Jedes Mitglied kann 
      dort einsteigen, wo es von den Anforderungen her am ehesten Erfolg haben kann. Ein Wechsel     
      ist nie ausgeschlossen und ein Austausch mit allen Membern der Clanfamilie über Discord 
      jederzeit möglich.


      Wir heißen jeden Willkommen, der bereit ist, mit uns 100% zu geben. Tritt einem unserer Clans     
      bei und werde ebenso Teil der Center Court Clanfamilie

  social:
    - discord: https://discord.com/invite/J2RPhNPVPF

clans:
  - name: Center Court
     tag: 898P08VR
  - name: Titan clan 1
     tag: 9UPQJYVU
  - name: uN Rated
     tag: 88VGYLJ
  - name: Center Court 2
     tag: LV8GYP0U
  - name: Center Court 3
     tag: YCVUQQY0
  - name: CC Familie
     tag: QPYCPUJR
```
