### ISSUE TITLE
Team Lunatic

### ISSUE THREAD

**Issue by Europaco** [RoyaleAPI/family-config#606]
- `color`: teal
- `key`: team lunatic
- `emblem`: Flame_03
- `description` and `links`: 🔷️Team Lunatic Family (TL)🔷️ Top 2🇪🇸~~Top 11🌍
- `tag`:  dYYU82JG9

Fill in the configuration below:

```yaml
name: Team Lunatic eSports
key: Team Lunatic
color: teal
emblem: Flame_03
info:
  logo: https://i.ibb.co/PtMPZq8/Team-Lunatic.jpg
  description: >
    ¡Familia Team Lunatic, fundada en agosto de 2.019, con más de 300 miembros y 6 clanes activos!
    Desde nuestra creación, hemos formado valores familiares e impulsado un nivel competitivo, que nos ha llevado al top mundial.
    Miembros de cualquier parte del mundo, con gran nivel de actividad.

    Somos un equipo con carácter en busqueda continua de talento y compromiso, al que aportar nuestras estrategias de mejora.

    ¡Las guerras de clanes están en nuestro ADN!

    
  social:
    - twitter: https://twitter.com/TeamLunaticCR?t=8yJu8KwR-SiifX0V02cgAg&s=08  
    - instagram: https://www.instagram.com/teamlunaticcr/
  
  
clans:
  - name: Team Lunatic
    tag: YYU82JG9
  - name: IMPERIUM DIPEP™
    tag: 8UJRJUG8
  - name: imP.E.K.K.Ables
    tag: CVYCQR9  
  - name: Team Lunatic II
    tag: YRGV289J
  - name: Team Lunatic 3
    tag: L8GQJ8G9
  - name: Team Lunatic IV
    tag: QPVPYGYV
 
```
