### ISSUE TITLE
[Update] Malta CR

### ISSUE THREAD

**Issue by uXerty** [RoyaleAPI/family-config#61]
```yaml
name: Malta CR
key: maltacr
color: red
emblem: Skull_06
sort: trophy
info:
  logo: /static/img/brands/logo/maltacr.png
  description: >
    Welcome to **Malta CR**, we are a clan based in Malta with players from all corners of the world. Malta CR is made up of 3 trophy-pushing clans, and we take clan wars seriously!
    This clan family consists of some of the **most** skilled players in Malta.
    Having all 3 clans on the **local leaderboard** with **Malta CR** being **1st**, and our feeders **Malta CR 2** and **Malta CR 3** consistently being the top 5.
    We are a very competitive clan, seeking skilled players. We are accepting any Maltese and English speakers! Jekk titħol magħna, żgur ha tgħid "x'clan organizzata!". Toqgħodx taħsibha biex tieħu ċans magħna! - anke jekk għadek qed tibda, post insibulek zgur - kellimna permezz ta' discord jekk interessat :)
  social:
    - discord: http://discord.gg/TA5J3rc
clans:
  - name: Malta CR
    tag: 8QGVQ9P8
  - name: Malta CR 2
    tag: 8RRL9PGR
  - name: Malta CR 3
    tag: 8RPQJPUU
```
