### ISSUE TITLE
SWARM Add

### ISSUE THREAD

**Issue by SiRTWiStEd** [RoyaleAPI/family-config#611]
```yaml
name: Swarm War Family Clans
key: swarm
color: purple
emblem: Bolt_01

info:
  logo: https://i.imgur.com/odLZqtm.jpg
  description: >
    Swarm is a war focused family of five clans committed to empowering individuals through a supportive team environment. We have some of the friendliest people with great banter, laughs, and with all different types of ages and ethnicities! We as a family and individual players have grown immensely and continue to each day. We help each other with deck creation and adjustments, practice in clan constantly, hold tournaments to strengthen our skills with war decks, and participate in top war tournaments between clans. If you’d like to learn more please join our Discord!

  social:
    - discord: https://discord.gg/YNJg6B2U
    - website: swarmcr.com
clans:
  - name: SWARM
    tag: 2LR92YQV
  - name: Epic Elite
    tag: PJ2YR2P2
  - name: X-USA
    tag: 2UVGVVLJ
  - name: Swarm jr. 
    tag: L9UY8P0P
  - name: Apollo’s MIGHT™️
    tag: 8022LQGU

…
```
