### ISSUE TITLE
Family Clan: ZLY GAMING

### ISSUE THREAD

**Issue by Brauni9** [RoyaleAPI/family-config#612]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: ZLY GAMING
key: zly
color: violet
emblem: Elixir_02
info: 
  logo: /static/img/brands/logo/zly_logo.png

  description: >
![zly_logo](https://user-images.githubusercontent.com/98294630/150715472-abfa45eb-76df-468f-829c-58fd3c74c9f6.png)

    C⚡️ZLY⚡️
⚔️Clan Semi Profesional ⚔️

🏆 Top 1 Malawi, aspirantes para top Mexico 🏆



    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://www.instagram.com/zly_esports/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:


clans:
  - name: ZLY
    tag: PVPQJ88Q
  - name: ZLY 2
    tag: LQL2V9Q0
  - name: ZLY 3
    tag: G09C9CY2
```
