### ISSUE TITLE
Update config Family: Mage Knights

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#614]
```yaml
name: Mage Knights
key: mageknights
color: violet
emblem: A_Char_Knight_01
info:
  logo: static/img/brands/logo/mage-knights.png?t=393c9e38c
  description: >
    The **Mage Knights** are a family of clans, which is primarily war-focused 
    and a community based on Clash Royale and Brawl Stars, playing both competitively and casually. 
    We value the entire card collection, not just your ladder deck, 
    but our family accepts players of all skill and card levels. 
    We also value practice and constructive criticism; there is always room for improvement. 
    _Mage Knights’ main clan is currently top 50 in U.S. clan war rankings_. 
  social:
    - discord: https://discord.gg/UZFbhZf8x7
    - youtube: https://www.youtube.com/channel/UC1R-b1AET3-eLGQNed6TYzA
clans:
    - name: Mage Knights
       tag: 2V28Y88Q
    - name: Mage Knights 2
       tag: YR00L2LY
    - name: Mage Knights 3
       tag: YLRJ8LUP
```
