### ISSUE TITLE
Unnamed

### ISSUE THREAD

**Issue by 101-10-0-1** [RoyaleAPI/family-config#615]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:    
key: Unnamed
color: red
emblem: Twin_Peaks_02.png
info:
  logo:
  description: >
    Unnamed attempt to form a family of clans, forged by a small group of friends since 2017 :D 


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/ 101_10_0_1
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name:     
    tag: L8YUJG29
  - name: ⠀⠀⠀⠀
    tag: QV9V880C
  - name:
    tag:
```
