### ISSUE TITLE
Config Royale API Blue Foxes™

### ISSUE THREAD

**Issue by Bingo02** [RoyaleAPI/family-config#616]
```yaml
name: Blue Foxes Family
key: BlueFoxesFamily
color: blue
emblem: Heart_04
info: 
  logo: https://drive.google.com/file/d/1xt4JvPJdiTuf2IbT4-CzCnPeXwY4K9BY/view?usp=drivesdk
  description:  >
    Eres bienvenido a nuestra familia, te esperamos. Clan top local y equipo competitivo.

social:
    - twitter: https://twitter.com/foxestm

clans:
  - name: Blue Foxes™
    tag: 8JGJ89PR
  - name: Blue Foxes™ Jr
    tag: QPV02YV8
```
