### ISSUE TITLE
00 ~ King's Family ~ 00

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#617]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 00 ~ King's Family ~ 00
key: king
color: purple
emblem: Crown_04
sort: trophy
info:
  logo: https://drive.google.com/file/d/1S30qToN79xtkcL0HU04p-PX_4d6_sfXg/view
  description: >
**We are here to win!**

Please join our Discord.


  social:
    - discord: https://discord.gg/RkdrBAbXeN
clans:
  - name: Galactic Kings
    tag: Y9202P9U 
  - name: Thunder Buddies
    tag: GL0J0R
  - name: M for Mature
    tag: 2909VP
  - name:  League of Kings
    tag: LO9UQL9Y
```
