### ISSUE TITLE
YAML Issue for Elder Dragons clan

### ISSUE THREAD

**Issue by J3H4M970N** [RoyaleAPI/family-config#618]
```yaml
name: ELDER DRAGONS
key: edrag
color: blue
emblem: YinYang_02
info:
  logo: https://ibb.co/d0Rnh8Y
  description:


🐉Elder Family🐉WAR participation required🐉Adult Clan🐉discord.gg/y95gctkcFg🐉


    - discord: https://discord.gg/y95gctkcFg

clans:
  - name: Elder Dragons
    tag: 2VP89RP

```
