### ISSUE TITLE
1º ORO NEGR0 Familia!

### ISSUE THREAD

**Issue by ElDante7Z** [RoyaleAPI/family-config#62]
```yaml
name: 1º ORO NEGR0 Familia!
key: 1-on
color: black
emblem: Coin_03
info:
  logo: https://ibb.co/kSv5zG1
  description: >
Solo Gente Activa 24/7 Ó Expulsión. Clan VIP En “Trofeos” Top Local 200. Clan VIP En “Donaciones” Top Local 1. 70% De Las Guerras las Ganamos De 1. Grupo De WhatsApp.
  social:
    - application: https://chat.whatsapp.com/JojxNi92hvICDRaegbUqgy
clans:
  - name: ORO NEGR0 ♥VIP♥
    tag: PCY2CYY9
  - name: ORO NEGR0 ❤
    tag: P8GP0VQ8
```

**Comment by ElDante7Z** [comment]
```yaml
name: 1º ORO NEGR0 Familia!
key: 1-on
color: black
emblem: Coin_03
info:
  logo: https://ibb.co/kSv5zG1
  description: >
Solo Gente Activa 24/7 Ó Expulsión. Clan VIP En “Trofeos” Top Local 200. Clan VIP En “Donaciones” Top Local 1. 70% De Las Guerras las Ganamos De 1. Grupo De WhatsApp.
  social:
    - application: https://chat.whatsapp.com/JojxNi92hvICDRaegbUqgy
clans:
  - name: ORO NEGR0 ♥VIP♥
    tag: PCY2CYY9
  - name: ORO NEGR0 ❤
    tag: P8GP0VQ8
```
