### ISSUE TITLE
beginner's clan

### ISSUE THREAD

**Issue by KEN06105** [RoyaleAPI/family-config#622]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:beginner's clan Family
key:beginner's clan
color:yellow
emblem: A_Char_King_01.png


info:
  logo: ![10FA3B4B-212B-48EA-9CCC-6BDF3E5DD58E](https://user-images.githubusercontent.com/98637008/151729236-4be3ff7d-6183-4e03-b785-3001fcb3e486.png)
  description: >
    日本🇯🇵の代表的なクランの一つです！　　うちのクランはクラン対戦に力を入れてます
一人一人がこのクランをより強くするという意志を持っています❤️‍🔥 
このクランの理念として、
👑みんなの平等な努力で上位を目指し常勝する🔥を掲げてます！
積極的な方だったらトロフィー関係なく入隊可能❣️詳しくはクランに入ってから説明します。
支部クランのWinner's Clanも是非来てください🥰


    Add new line with 2 line breaks as above.
  social:
    - twitter:https://twitter.com/beginners_clan
    - discord: http://discord.gg/sDWKMuWy
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: beginner's clan
    tag: C9RORYQ
  - name:Winner's Clan
    tag:LGJ99R2C
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
```yml
name: beginner's clan Family
key: beginners
color: yellow
emblem: A_Char_King_01


info:
  logo: /static/img/brands/logo/beginners.png
  description: >
    日本🇯🇵の代表的なクランの一つです！　　うちのクランはクラン対戦に力を入れてます
    一人一人がこのクランをより強くするという意志を持っています❤️‍🔥
    このクランの理念として、
    👑みんなの平等な努力で上位を目指し常勝する🔥を掲げてます！
    積極的な方だったらトロフィー関係なく入隊可能❣️詳しくはクランに入ってから説明します。
    支部クランのWinner's Clanも是非来てください🥰


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/beginners_clan
    - discord: http://discord.gg/sDWKMuWy
clans:
  - name: beginner's clan
    tag: C9RORYQ
  - name: Winner's Clan
    tag: LGJ99R2C

```
