### ISSUE TITLE
PressPinpinte yml file

### ISSUE THREAD

**Issue by Merluchon** [RoyaleAPI/family-config#626]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: PressPinpinte
key: presspinpinte
color: red
emblem: A_Char_Pekka_02

info:
  logo: https://i.ibb.co/SQP9SHv/press1.png
  description: >
    La **Presspinpinte** est une communauté familiale. Composés de 7 clans, ceux-ci ont différents objectifs.
    La Pression, FrenchBlood, PerlinPinpinte et les Spartiates sont axés Guerres de Clans.
    RushPinpinte est notre clan ladder.
    BabyPinpinte est notre clan école (level 11 max).
    ChillPinpinte est notre clan repos.
    Nous organisons un tournoi interclans chaque mois ainsi que de nombreux autres évènements ! Les meilleurs guerriers sont récompensés en goodies et pass Clash Royale.
    Rejoignez-nous vite sur Discord !
  social:
    - Discord: https://discord.gg/g4d5p9zSP4
    - Website: https://la-presspinpinte.hubside.fr/
    - Instagram: https://www.instagram.com/presspinpinte_clash/
    - Facebook: https://www.facebook.com/dylan.presspinpinte
    - Twitch: https://www.twitch.tv/presspinpinte
    - Youtube: https://www.youtube.com/channel/UCTSlG4PNy7v_nA57d1A75Pw
    - Tik Tok: https://www.tiktok.com/@presspinpintecr
clans:
  - name: la PRESSION
    tag: 9VL9L9YQ
  - name: FrenchBlood
    tag: 9VJ0J9
  - name: perlinpinpinte
    tag: P2RUP90G
  - name: Les spartiates
    tag: YL2GJ9PY
  - name: RushPinpinte
    tag: L82YYGCU
  - name: Chillpinpinte
    tag: LGVJU0RY
  - name: BabyPinpinte
    tag: G0UR08JY
```

**Comment by smlbiobot** [comment]
```yml
name: PressPinpinte
key: presspinpinte
color: red
emblem: A_Char_Pekka_02

info:
  logo: /static/img/brands/logo/presspinpinte.png
  description: >
    La **Presspinpinte** est une communauté familiale. Composés de 7 clans, ceux-ci ont différents objectifs.
    La Pression, FrenchBlood, PerlinPinpinte et les Spartiates sont axés Guerres de Clans.
    RushPinpinte est notre clan ladder.
    BabyPinpinte est notre clan école (level 11 max).
    ChillPinpinte est notre clan repos.
    Nous organisons un tournoi interclans chaque mois ainsi que de nombreux autres évènements ! Les meilleurs guerriers sont récompensés en goodies et pass Clash Royale.
    Rejoignez-nous vite sur Discord !
  social:
    - discord: https://discord.gg/g4d5p9zSP4
    - website: https://la-presspinpinte.hubside.fr/
    - instagram: https://www.instagram.com/presspinpinte_clash/
    - facebook: https://www.facebook.com/dylan.presspinpinte
    - twitch: https://www.twitch.tv/presspinpinte
    - youtube: https://www.youtube.com/channel/UCTSlG4PNy7v_nA57d1A75Pw
    - tiktok: https://www.tiktok.com/@presspinpintecr
clans:
  - name: la PRESSION
    tag: 9VL9L9YQ
  - name: FrenchBlood
    tag: 9VJ0J9
  - name: perlinpinpinte
    tag: P2RUP90G
  - name: Les spartiates
    tag: YL2GJ9PY
  - name: RushPinpinte
    tag: L82YYGCU
  - name: Chillpinpinte
    tag: LGVJU0RY
  - name: BabyPinpinte
    tag: G0UR08JY
```
