### ISSUE TITLE
Arka Sokaklar

### ISSUE THREAD

**Issue by NHardwclsn** [RoyaleAPI/family-config#627]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:lizard yamlyam
key:
color:Grey
emblem:
info:
  logo:
  description: >nooblar ordusu sikici lizardd
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/mrlizardd1
    - discord: http://discord.gg/HvmaUPjBaE
    - twitch: https://www.twitch.tv/bylizardd
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Thrashers
    tag: LRQ2P0VC
  - name: TEŞKİLAT
    tag: QVQ9LGUJ
  - name: JP_ASTRAY
    tag: QVR0QVJ9
- name: TEAM ASTRAY
    tag: #L9R8JG0P
  - name: TEAM ASTRAY V2
    tag: #LJLUUR2J
  - name: TEAM ASTRAY V3
    tag: #LLR9GGJL
- name: Alayına Yeteriz
-    tag: LJ82ULJP
```

**Comment by smlbiobot** [comment]
```yml
name: Lizard
key: lizard
color: grey
emblem: Moon_01
info:
  description: >
    nooblar ordusu sikici lizardd
  social:
    - twitter: https://twitter.com/mrlizardd1
    - discord: https://discord.gg/HvmaUPjBaE
    - twitch: https://www.twitch.tv/bylizardd
clans:
  - name: Thrashers
    tag: LRQ2P0VC
  - name: TEŞKİLAT
    tag: QVQ9LGUJ
  - name: JP_ASTRAY
    tag: QVR0QVJ9
  - name: TEAM ASTRAY
    tag: L9R8JG0P
  - name: TEAM ASTRAY V2
    tag: LJLUUR2J
  - name: TEAM ASTRAY V3
    tag: LLR9GGJL
  - name: Alayına Yeteriz
    tag: LJ82ULJP
```
