### ISSUE TITLE
OTA Clan Family

### ISSUE THREAD

**Issue by nineroro** [RoyaleAPI/family-config#629]
```yaml
name: OTA family
key: ota
color: purple
emblem: Moon_02
info:
  logo: https://cdn.royaleapi.com/static/img/badge/legendary-2/Moon_02.png?t=6fa4b5b7c
  description: >
Turkish war clans. We are looking for skilled war inclined warriors. Please apply in our discord by typing your account tag and we will respond as soon as possible!
  social:
    - discord: https://discord.gg/yYc43wxmXC
clans:
  - name: OSMANLI TÜRK AK
    tag: PYL900GJ
  - name: TR TURKIYE
    tag: PQGYPV8Y
  - name: Special Forces
    tag: QCC98QYG
```
