### ISSUE TITLE
Skillless

### ISSUE THREAD

**Issue by page118** [RoyaleAPI/family-config#632]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Skillless™️
key: skillless
color: violet
emblem: Sword_01
info:
  logo: ![3219261251d041d7a300fa3eebca8ecd (1)](https://user-images.githubusercontent.com/100172939/155069114-f1a836cd-6cc3-4b50-aba3-18d4791b1482.png)


  description: >
 Welcome to Skillless! We’re a new clan family recruiting for members that add to a great community :) We're active and focus mostly on helping players and bringing joy to the game through communication and companionship.
  social:
      - discord: https://discord.gg/Vw3dMMTq3v
  clans:
  - name: Skillless™️
    tag: LRLU2JQV
  - name: NoSkill™️
    tag: G0LQVG0J
 
```
