### ISSUE TITLE
France family

### ISSUE THREAD

**Issue by BurningZeRoad** [RoyaleAPI/family-config#633]
```yaml
name: France
key: France
color: blue
emblem: flag_k_01
info:
  logo: https://c.tenor.com/PXvIwoO9xdYAAAAj/clash-royale.gif
  description: >
    France est une famille de 3 clans essentiellement orientés GDC.
    Bonne ambiance, esprit d'équipe, respect et entraide.
    On est là pour jouer... pas pour se prendre la tête !
    Système de montée/descente entre les clans en fonction des résultats en GDC.
    Records actuels en GDC : 8e fr / 101e monde
  social:
    - discord: https://discord.gg/Y8zSyQpeMN
clans:
  - name: France
    tag: 9U9Q9GYG
  - name: France Bis
    tag: L999UJ9P
  - name: France Ter
    tag: LJ99982G
```
