### ISSUE TITLE
Add clan to HC eSports KatzClans family

### ISSUE THREAD

**Issue by katzclans** [RoyaleAPI/family-config#634]
```yaml
clans:
  - name: Hard Counter™️
    tag: LGU2JP9C
  - name: Hard Counter™️2
    tag: QYPYQ800 
```
