### ISSUE TITLE
Add a clan family

### ISSUE THREAD

**Issue by invisebl** [RoyaleAPI/family-config#635]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Dutch Corps Family
key: Dutch Corps
color: Black
emblem:[
](https://github.com/RoyaleAPI/cr-api-assets/blob/1864a38bb4a76d75ccd5fd1c34b98854c221daab/badges/Skull_05.png)  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social: 
    - Youtube: [
](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazBvN3BhRTFWYWJQRVFiSTlIenpJMFdIV3RKZ3xBQ3Jtc0tuY1YxcEdrVU1rUGxBRF9VeHVFMFBSb1RjcTY3M1p4RGtzdnRIOFY3UTMyS1ZEek5oRmhJX0F6QVFNMVFmNXRqTm1JUmFIdl9vMVFrNlVzMHE1SlEtVkRoWXIxcEZGSWRWYWZYM1J6U1JGSlhZaWcwaw&q=http%3A%2F%2Fbit.ly%2FAbonneerFloris)    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans: 
  - name: Dutch Corps
    tag: PQUC20
  - name: Dutch Corps 2
    tag: PY9G2CCV
  - name: Dutch Corps 3
    tag: PLC2VULC
  - name: Dutch Corps 4
    tag: PGY8UJYG
 - name: Dutch Corps Jr
   tag: LVL0QVC9
```

**Comment by smlbiobot** [comment]
that’s not a valid youtube URL. please provide a LINK

**Comment by smlbiobot** [comment]
```yml
name: Dutch Corps Family
key: dutch-corps
color: black
emblem: Skull_05
clans:
- name: Dutch Corps
  tag: PQUC20
- name: Dutch Corps 2
  tag: PY9G2CCV
- name: Dutch Corps 3
  tag: PLC2VULC
- name: Dutch Corps 4
  tag: PGY8UJYG
- name: Dutch Corps Jr
  tag: LVL0QVC9
```
