### ISSUE TITLE
Adding clan family

### ISSUE THREAD

**Issue by invisebl** [RoyaleAPI/family-config#636]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Dutch Corps Family
key: Dutch Corps
color: Orange
emblem: Skull_05
info:
  logo: badges/Skull_05.png
  description: > 
    The Dutch Corps Family Is the best clan in the Netherlands.We have the best ladder clan, The best warclan and more feeders for the lower players. You are on the right place if you’re looking for a great community.
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social: 
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://youtube.com/c/Corpsroyale
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Dutch Corps
    tag: PQUC20
  - name: Dutch Corps 2
    tag: PY9G2CCV
  - name: Dutch Corps 3
    tag: PLC2VULC
  - name: Dutch Corps 4
    tag: PGY8UJYG
  - name: Dutch Corps Jr
    tag: LVL0QVC9
```
