### ISSUE TITLE
[UPDATE] Removed CremaCatalana 7

### ISSUE THREAD

**Issue by lluisd** [RoyaleAPI/family-config#64]
```yaml
name: Crema Catalana
key: cc
color: orange
emblem: Flame_01
info:
  logo: https://pbs.twimg.com/profile_images/925754797545967616/5UnqhQez_400x400.jpg
  description: >
    **Crema Catalana** és un clan apolític format per gent de parla catalana. Actualment 
    està format per 6 clans, el clan principal i 5 pedreres. Tots aquests clans s’estructuren 
    pel nivell de copes dels seus membres. Cada 6/8 dies es faran moviments verticals 
    entre tots els clans. Paral·lelament, tenim 2 equips competitius professionals 
    ([Cream eSports](https://creamesports.com/) i ColiseoCream EU)
  social:
    - twitter: https://twitter.com/cremacatalanacr
    - discord: http://discord.gg/jz9wMwF
    - email: cremacatalanacr@gmail.com
clans:
  - name: Crema Catalana
    tag: 2JYGCRLL
  - name: CremaCatalana 2
    tag: 8P9VQPCY
  - name: CremaCatalana 3
    tag: 2UYCQC29
  - name: CremaCatalana 4
    tag: 2CCRRV9R
  - name: CremaCatalana 5
    tag: 2JYC029U
  - name: CremaCatalana 6
    tag: 89YG2GU0
```
