### ISSUE TITLE
Update Family ComeBack

### ISSUE THREAD

**Issue by EyesTv** [RoyaleAPI/family-config#640]
```yaml
name: ComeBack
key: CB
color: blue
emblem: Bolt_03
sort: trophy
info:
  logo: /static/img/brands/logo/come-back.png
  description: >
    **ComeBack** is a French clan family.The first clan was created the 03/21/2018 by [big ouf](https://royaleapi.com/player/9UR9GPCQ).
    It started out as a clan of friends, then we quickly revealed great potential across the world rankings as well as in competition.
    After the success of the clan, other clans were created later ComeBack 2, ComeBack 3 and ComeBack 4, ComeBack5, ComeBack 6, ComeBack INT and Comebackademie.

  social:
  - discord: https://discord.gg/dB9pKDVVYS
  - twitter: https://twitter.com/comeback__cr/

clans:
  - name: ComeBack
    tag: 989VGGV8
  - name: ComeBack 2
    tag: 9LY2RCUQ
  - name: ComeBack 3
    tag: Y0RYYL8J
  - name: ComeBack 4
    tag: Y2LPVVGG
  - name: ComeBack 5
    tag: LVG9QCP9
  - name: ComeBack 6
    tag: Q2P8VQ0Y
  - name: ComeBack INT
    tag: GYQURRUJ
  - name: ComeBackacademie
    tag: QGPU2GCP
```
