### ISSUE TITLE
Clash Dinasty

### ISSUE THREAD

**Issue by Miguel1174** [RoyaleAPI/family-config#642]
name: Clash Dinasty
key: cd
color: blue
emblem: Fugi_03.
info:
  logo: https://media.discordapp.net/attachments/869280005966946344/912145835859542026/IMG_3559.png
  description: >
_Clash Dynasty_ We’re an ambitious, leading family of global clans driven by team-spirit & will to win. Our members work together to learn, excel and make a difference in ladder & wars. Clash Dynasty clans are global, English speaking and driven by an ethos of equality, diversity & inclusion. Our leaders ensure you’re part of a safe, non-toxic environment that focuses on achievement, self-improvement and clan spirit.
  social:
    - discord: https://discord.gg/s5vPkCbu
clans:
  - name: Clash of Duty
    tag: Y80C2UJR
  - name: Clash of Honour
    tag: YCL8RY82
  - name: Clash of Titans
    tag: LQGJ0QLV
  -name: Clash of Glory
    tag: L8Q8GPGU
  -name: Clash of Realms
    tag: L9JV99PP
  -name: Clash of Fury
    tag: Q2RL22U2

**Comment by smlbiobot** [comment]
```yml
name: Clash Dynasty
key: cd
color: blue
emblem: Fugi_03
info:
  logo: /static/img/brands/logo/clash-dynasty.png
  description: >
    _Clash Dynasty_ We’re an ambitious, leading family of global clans driven by team-spirit & will to win. Our members work together to learn, excel and make a difference in ladder & wars. Clash Dynasty clans are global, English speaking and driven by an ethos of equality, diversity & inclusion. Our leaders ensure you’re part of a safe, non-toxic environment that focuses on achievement, self-improvement and clan spirit.
  social:
    - discord: https://discord.gg/s5vPkCbu
clans:
  - name: Clash of Duty
    tag: Y80C2UJR
  - name: Clash of Honour
    tag: YCL8RY82
  - name: Clash of Titans
    tag: LQGJ0QLV
  - name: Clash of Glory
    tag: L8Q8GPGU
  - name: Clash of Realms
    tag: L9JV99PP
  - name: Clash of Fury
    tag: Q2RL22U2

```
