### ISSUE TITLE
Undead Clan Family

### ISSUE THREAD

**Issue by SkullazerCR** [RoyaleAPI/family-config#643]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Undead Clan Famimly
key: undead
color: black
emblem: Skull_02
info:
  logo: 
  description: >
    The **Undead Clan Family** (UCF) Is a new clan family which focuses on wars.


clans:
  - name: Undead Kingdom
    tag: LQJP9LJR
```
