### ISSUE TITLE
Add Mercadians Family

### ISSUE THREAD

**Issue by CRS-WBR** [RoyaleAPI/family-config#646]
```yaml
name: Mercadians Family
key: mrc
color: blue
emblem: Flame_04
info:
  logo: https://imagizer.imageshack.com/img923/4305/9R4bPR.jpg
  description: > 
    **Willkommen bei Mercadians.** Unsere Clanfamilie existiert seit 2018 und wächst von Jahr zu Jahr weiter. Aktuell umfasst unsere Clanfamilie 6 Clans mit über 250 Member. Von Ladder (MRC I & MRC E-Sports) und CW fokussierten Top Clans (MRC II, III, IV) über Nachwuchs-Clans ohne Verpflichtungen (MRC V) bis hin zu einem eigenen E-Sports Team, sind wir deutschlandweit vertreten.

    Wir bieten jedem Spieler ein semiprofessionelles Management, einen gepflegten Discord Server (bei Bedarf WhatsApp Gruppen) für eine bessere Vernetzung untereinander, grafische Analysen im CW Clan und lukrativen Preisgeld-Turniere mit außergewöhnlichen Formaten. 

    Uns verbindet ein ausgeklügeltes Netzwerk von jungen erfolgshungrigen Membern, sowie erfahrenen und konsequenten Führungsspielern. In unserem Main Clan bieten wir Ladder-Rewards zum Seasonend für die Top 3 Player und im unserem CW-Main für den Top CW-Spieler an und zeichnen uns kontinuierlich mit Loyalität und Ehrgeiz aus. Unser E-Sports Team „Disturbed Gaming“ spielt aktiv in internationalen Ligen und ist immer heiß auf neue zuverlässige Spieler, die zu unserer Elite gehören wollen.

    In Social-Media präsentieren wir uns auf Twitter, Facebook und Instagram.

    Kontakt über Discord:
Mercadians I - VI: quaan78#0896 & Dalex1605#4557
MRC E-Sports: SHB I zorro#3277

  social:
    - twitter: http://twitter.com/disturbedcr?s=21
    - twitch: https://www.twitch.tv/gamefreaktv_cr
    - twitch: https://www.twitch.tv/bennetf2p
    - instagram: https://instagram.com/dist.urbed_gaming/?utm_medium=copy_link
    - facebook: https://facebook.com/CRMercadians
clans:
  - name: Mercadians
    tag: 22PQUY0U
  - name: MRC E-Sports
    tag: G0J8JYPV
  - name: Mercadians II
    tag: PP0VRGV0
  - name: Mercadians III
    tag: PYVUP9J2
  - name: Mercadians IV
    tag: PYG89YV8
  - name: Mercadians V
    tag: Y8GR8LGG

```

**Comment by smlbiobot** [comment]
```yml
name: Mercadians Family
key: mrc
color: blue
emblem: Flame_04
info:
  logo: /static/img/brands/logo/mercadians.png
  description: >
    **Willkommen bei Mercadians.** Unsere Clanfamilie existiert seit 2018 und wächst von Jahr zu Jahr weiter. Aktuell umfasst unsere Clanfamilie 6 Clans mit über 250 Member. Von Ladder (MRC I & MRC E-Sports) und CW fokussierten Top Clans (MRC II, III, IV) über Nachwuchs-Clans ohne Verpflichtungen (MRC V) bis hin zu einem eigenen E-Sports Team, sind wir deutschlandweit vertreten.


    Wir bieten jedem Spieler ein semiprofessionelles Management, einen gepflegten Discord Server (bei Bedarf WhatsApp Gruppen) für eine bessere Vernetzung untereinander, grafische Analysen im CW Clan und lukrativen Preisgeld-Turniere mit außergewöhnlichen Formaten.


    Uns verbindet ein ausgeklügeltes Netzwerk von jungen erfolgshungrigen Membern, sowie erfahrenen und konsequenten Führungsspielern. In unserem Main Clan bieten wir Ladder-Rewards zum Seasonend für die Top 3 Player und im unserem CW-Main für den Top CW-Spieler an und zeichnen uns kontinuierlich mit Loyalität und Ehrgeiz aus. Unser E-Sports Team „Disturbed Gaming“ spielt aktiv in internationalen Ligen und ist immer heiß auf neue zuverlässige Spieler, die zu unserer Elite gehören wollen.


    In Social-Media präsentieren wir uns auf Twitter, Facebook und Instagram.


    Kontakt über Discord:


    - Mercadians I - VI: quaan78#0896 & Dalex1605#4557

    
    - MRC E-Sports: SHB I zorro#3277

  social:
    - twitter: https://twitter.com/disturbedcr?s=21
    - twitch: https://www.twitch.tv/gamefreaktv_cr
    - twitch: https://www.twitch.tv/bennetf2p
    - instagram: https://instagram.com/dist.urbed_gaming/?utm_medium=copy_link
    - facebook: https://facebook.com/CRMercadians
clans:
  - name: Mercadians
    tag: 22PQUY0U
  - name: MRC E-Sports
    tag: G0J8JYPV
  - name: Mercadians II
    tag: PP0VRGV0
  - name: Mercadians III
    tag: PYVUP9J2
  - name: Mercadians IV
    tag: PYG89YV8
  - name: Mercadians V
    tag: Y8GR8LGG
```
