### ISSUE TITLE
Update to https://royaleapi.com/f/kings

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#647]
```yaml
name: King's Family
key: king
color: pink
emblem: Heart_01
info:
  logo: https://drive.google.com/file/d/1S30qToN79xtkcL0HU04p-PX_4d6_sfXg/view
  description: >
Kings is competitive Clash Royale Family of clans looking for active members who are able to be on everyday.


In order to stay you must have a minimum of 2800 war fame by the end of the river race or demote, any miss/partial attacks demoted. Promotions are based off overall war performance during your wars with us.


Only level 14 players with level 14 cards are allowed to put in boat defense.

social:
    - discord: https://discord.gg/RkdrBAbXeN
clans:
  - name: BLOOD N BONES
    tag: 2PQY2VQR
  - name:  League of Kings
    tag: LO9UQL9Y
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Galactic Kings
    tag: Y9202P9U 
```

**Comment by smlbiobot** [comment]
```yml
name: King's Family
key: kings
color: pink
emblem: Heart_01
info:
  logo: /static/img/brands/logo/kings.png
  description: >
    Kings is competitive Clash Royale Family of clans looking for active members who are able to be on everyday.


    In order to stay you must have a minimum of 2800 war fame by the end of the river race or demote, any miss/partial attacks demoted. Promotions are based off overall war performance during your wars with us.


    Only level 14 players with level 14 cards are allowed to put in boat defense.

social:
    - discord: https://discord.gg/RkdrBAbXeN
clans:
  - name: BLOOD N BONES
    tag: 2PQY2VQR
  - name:  League of Kings
    tag: LO9UQL9Y
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Galactic Kings
    tag: Y9202P9U
```
