### ISSUE TITLE
Family config for Apex Aussies

### ISSUE THREAD

**Issue by barxnet** [RoyaleAPI/family-config#648]
```yaml
name: Apex Aussies Clash Royale Family
key: ApexAussies
color: blue
emblem: flag_b_03
info:
  logo: http://alanoconnell.com/apex/Apex_Aussies.jpg
  description: >
    Welcome to Apex Aussies Clash Royale Family.  We are a family clan made up of 10 clans.  We cater to all levels of players, from our top level clans where all players must complete all war battles every week to more casual river race clans and non river race clans.  We have a strong Discord community with something for everyone.  Most importantly, we enjoy the game!
  social:
    - discord: https://Discord.gg/Xc28XcwWQ2
clans:
  - name: Apex Aussies
    tag: 9LYCV200
  - name: Apex Aussies 2
    tag: LQLP0R0L
  - name: Apex Aussies 3
    tag: YUVUQUPV
  - name: Apex Aussies 4
    tag: YJJCLGY0
  - name: Apex Aussies 5
    tag: LQUPR00J
  - name: Apex Aussies 6
    tag: QRGG8Q82
  - name: Apex Aussies 7
    tag: L82GR9LG
  - name: Apex Aussies 8
    tag: LP0G8YYV
  - name: Apex Aussies 9
    tag: QRJRYPG9
  - name: Apex Aussies 10
    tag: LUVYUCQQ

'''

**Comment by barxnet** [comment]
@selfish @smlbiobot @alpe123 @Arcey-bot 

Hi All,

I was wondering if this issue could be actioned, I believe I have the format correct.

Not sure if I am reaching out the the right people but trying my luck

Cheers,
Al

**Comment by smlbiobot** [comment]
```ymlname: Apex Aussies Clash Royale Family
key: ApexAussies
color: blue
emblem: flag_b_03
info:
  logo: /static/img/brands/logo/apex-aussies.png
  description: >
    Welcome to Apex Aussies Clash Royale Family.  We are a family clan made up of 10 clans.  We cater to all levels of players, from our top level clans where all players must complete all war battles every week to more casual river race clans and non river race clans.  We have a strong Discord community with something for everyone.  Most importantly, we enjoy the game!
  social:
    - discord: https://discord.gg/Xc28XcwWQ2
clans:
  - name: Apex Aussies
    tag: 9LYCV200
  - name: Apex Aussies 2
    tag: LQLP0R0L
  - name: Apex Aussies 3
    tag: YUVUQUPV
  - name: Apex Aussies 4
    tag: YJJCLGY0
  - name: Apex Aussies 5
    tag: LQUPR00J
  - name: Apex Aussies 6
    tag: QRGG8Q82
  - name: Apex Aussies 7
    tag: L82GR9LG
  - name: Apex Aussies 8
    tag: LP0G8YYV
  - name: Apex Aussies 9
    tag: QRJRYPG9
  - name: Apex Aussies 10
    tag: LUVYUCQQ
```
