### ISSUE TITLE
Family config for Team Kingfisher

### ISSUE THREAD

**Issue by Spherical-Pegasus** [RoyaleAPI/family-config#649]
```yaml
name: Team Kingfisher
key: kingfisher
color: blue
emblem: Gem_02
info:
  logo: https://media.discordapp.net/attachments/828931544117805096/900045458221703238/Kingfisher_Logo.png?width=300&height=300
  description: >
    ㅤ**Team Kingfisher** is a growing Gaming community with ambitious Supercell Clans. We have been extending our limits since the day we were created and now we have achieved a dream that we had days ago! We house a lot of people of all ages from all parts of the world today and we haven't stopped ourselves ro present new and interesting stuff to our Gaming mates. We have periodic Events and Tournaments also a YouTube channel, fun based Discord and Clans in Clash Royale and Clash of Clans. We expect your presious support to grow bigger. Thank you!
ㅤTeam Kingfisher ~ Aim to Glory!
ㅤSince 2020
  social:
    - discord: https://discord.com/invite/CBzYcZqD8D
    - youtube: https://www.youtube.com/channel/UCdcnP2M1aTj58z5cTiwAYTg
    - email: kingfisher.kc@gmail.com
clans:
  - name: Kingfisher
    tag: QOJJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R
```

**Comment by smlbiobot** [comment]
```yml
name: Team Kingfisher
key: kingfisher
color: blue
emblem: Gem_02
info:
  logo: /static/img/brands/logo/kingfisher.png
  description: >
    **Team Kingfisher** is a growing Gaming community with ambitious Supercell Clans. We have been extending our limits since the day we were created and now we have achieved a dream that we had days ago! We house a lot of people of all ages from all parts of the world today and we haven't stopped ourselves ro present new and interesting stuff to our Gaming mates. We have periodic Events and Tournaments also a YouTube channel, fun based Discord and Clans in Clash Royale and Clash of Clans. We expect your presious support to grow bigger. Thank you!
    ㅤ

    Team Kingfisher ~ Aim to Glory!
    ㅤ

    Since 2020
  social:
    - discord: https://discord.com/invite/CBzYcZqD8D
    - youtube: https://www.youtube.com/channel/UCdcnP2M1aTj58z5cTiwAYTg
    - email: mailto:kingfisher.kc@gmail.com
clans:
  - name: Kingfisher
    tag: QOJJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R
```
