### ISSUE TITLE
Icy Clan Family

### ISSUE THREAD

**Issue by Q-w-e-r** [RoyaleAPI/family-config#65]
```yaml
name: Icy Clan Family
key: ice
color: blue
emblem: Freeze_01
info:
  logo:
  description: >
    The **Icy Clan Family** is clan family dedicated to creating a positive community that wants 
    to improve. Home to newer players and more experienced players alike. That seek to help 
    each other and grow, individually and as a community. Our clans can be home to casual and 
    competitive players alike.
  social:
    - discord: https://discord.gg/abTduPC
clans:
  - name: Ice Eaters
    tag: PQ2GC2YJ
  - name: Ice Eaters 2
    tag: PPJPUYCO
  - name: Ice I One
    tag: YYQL8Q80
```
