### ISSUE TITLE
Family config for QT Clan Familie

### ISSUE THREAD

**Issue by mameit06** [RoyaleAPI/family-config#650]
name: QT Family
key: QT
color: purple
emblem: flag_k_3

info:
  logo: ![QT](https://user-images.githubusercontent.com/82063780/113785612-c8099a00-9737-11eb-93c7-dcb5bd2a8b4b.jpg)

  description: >
QT Elite gibt es seit 2016 und wir gehören seit langer Zeit zu den stärksten Clans in Deutschland. Seit März 2022 sind wir, als QT Elite, eigenständig, und haben unseren Zweitclan QT Elite Jr. gegründet. Spaß am Spiel, viel Humor, große Erfolge und noch höhere Ziele, als die bisher schon erreichten, haben bei uns oberste Priorität. 
Aktiv und motiviert, in guten und in schlechten Zeiten immer ein Team, und jeder zieht mit. Einer für alle, alle für einen, dafür stehen wir als QT Family.

  social:
 
clans:
 - name: QT Elite
    tag: 9JRVYQQT
- name: QT Elite Jr.
-  tag: #LUY9J2JG

**Comment by smlbiobot** [comment]
- Please say that you are UPDATING the family if you are updating it. 
- Also make sure that your clan tags are correct.
in the future update this instead:

```yml
name: QT Family
key: QT
color: purple
emblem: flag_k_03

info:
  logo: /static/img/brands/logo/qt.png

  description: >
    QT Elite gibt es seit 2016 und wir gehören seit langer Zeit zu den stärksten Clans in Deutschland. Seit März 2022 sind wir, als QT Elite, eigenständig, und haben unseren Zweitclan QT Elite Jr. gegründet. Spaß am Spiel, viel Humor, große Erfolge und noch höhere Ziele, als die bisher schon erreichten, haben bei uns oberste Priorität.
    Aktiv und motiviert, in guten und in schlechten Zeiten immer ein Team, und jeder zieht mit. Einer für alle, alle für einen, dafür stehen wir als QT Family.

clans:
- name: QT Elite
  tag: 9JRVYQQC
- name: QT Elite Jr.
  tag: LUY9J2JG
```
