### ISSUE TITLE
OKS Family of Clans Update

### ISSUE THREAD

**Issue by oksd2k** [RoyaleAPI/family-config#651]
```yaml
name: OKS Family of Clans
key: oks
color: green
emblem: pine_03
info:
  logo: https://photos.app.goo.gl/uoX3i3NuSLKL4dZx9
  description: >
    OKS Family of Clans prides itself in providing a positive, fun, and competitive environment for players of all levels of experience and activity. Monthly cash prize tournaments. Founded in June 2018 and still growing!

  social:
    - instagram: https://instagram.com/oksfamilyofclans?igshid=19y4g51fpbnmr
    - twitter: http://twitter.com/oksfamilyclans
    - discord: https://discord .gg/x77EaTq
    - OmletArcade: https://omlet.gg/profile/oksd2k
    - youtube: https://www.youtube.com/channel/508D2K
    
    - application: https://url/
    - email: mailto: dmartinho24@gmail.com
clans:
  - name: Kush Squad
    tag: 9G2LYURV
  - name: Kush2TheLimit
    tag: PQ989RC8
  - name: KushIsMyCologne
    tag: PL9V2RJQ
  - name: Clash4Kush
    tag: PRVYVCG8
  - name: 5-0!HideTheKush
    tag: YLUULLOY
  - name: OKS 6 God
    tag: YRYJYYOP
  - name: 24/7 Kush
    tag: PRY92VJY
  - name: OKS 8-Ball Kush
    tag: PCPPUCR8
  - name: OKS Cloud 9
    tag: LGYYRR88
  - name: OKS FamilyClans
    tag: LGQCRQGU
  - name: OKS Clannabis
     tag: L29YJURR
  - name: OKS 12 Apostles
     tag: LCCL2888
  - name: OKS 13 Ghosts
     tag: LLG89LV2
  - name: KooLKidssKluB
     tag: LGL8L92G
```

**Comment by smlbiobot** [comment]
note spacing. don’t try to align the colons for the name/tag:

```yml
name: OKS Family of Clans
key: oks
color: green
emblem: pine_03
info:
  logo: /static/img/brands/logo/oks-family.png
  description: >
    OKS Family of Clans prides itself in providing a positive, fun, and competitive environment for players of all levels of experience and activity. Monthly cash prize tournaments. Founded in June 2018 and still growing!

  social:
    - instagram: https://instagram.com/oksfamilyofclans?igshid=19y4g51fpbnmr
    - twitter: https://twitter.com/oksfamilyclans
    - discord: https://discord.gg/x77EaTq
    - website: https://omlet.gg/profile/oksd2k
    - youtube: https://www.youtube.com/channel/508D2K
    - email: mailto:dmartinho24@gmail.com
clans:
  - name: Kush Squad
    tag: 9G2LYURV
  - name: Kush2TheLimit
    tag: PQ989RC8
  - name: KushIsMyCologne
    tag: PL9V2RJQ
  - name: Clash4Kush
    tag: PRVYVCG8
  - name: 5-0!HideTheKush
    tag: YLUULLOY
  - name: OKS 6 God
    tag: YRYJYYOP
  - name: 24/7 Kush
    tag: PRY92VJY
  - name: OKS 8-Ball Kush
    tag: PCPPUCR8
  - name: OKS Cloud 9
    tag: LGYYRR88
  - name: OKS FamilyClans
    tag: LGQCRQGU
  - name: OKS Clannabis
    tag: L29YJURR
  - name: OKS 12 Apostles
    tag: LCCL2888
  - name: OKS 13 Ghosts
    tag: LLG89LV2
  - name: KooLKidssKluB
    tag: LGL8L92G
```
