### ISSUE TITLE
ImPEKKAble - Family Application

### ISSUE THREAD

**Issue by TKclash** [RoyaleAPI/family-config#652]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: ImPEKKAble
key: impekkable
color: red
emblem: A_Char_Pekka_02
info:
  social:
    - discord: http://discord.gg/Gtsj3XzFRd
clans:
  - name: ImPEKKAble
    tag: 20J20GC
  - name: #North America
    tag: PRVJ0PY
  - name: ImPEKKAble 2
    tag: 9J8J8G2R
```

**Comment by smlbiobot** [comment]
```yml
name: ImPEKKAble
key: impekkable
color: red
emblem: A_Char_Pekka_02
info:
  social:
    - discord: https://discord.gg/Gtsj3XzFRd
clans:
  - name: ImPEKKAble
    tag: 20J20GC
  - name: "#North America"
    tag: PRVJ0PY
  - name: ImPEKKAble 2
    tag: 9J8J8G2R
```
