### ISSUE TITLE
Crimson Imperium request

### ISSUE THREAD

**Issue by shz0a0** [RoyaleAPI/family-config#653]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Crimson Imperium
key: crimsonimperium
color: blue
emblem: Bolt_03
info:
  logo:
  description: >
    Crimson Imperium is an old clan family from the days of Clan Chests. Our clans are always high in donations and are active in Clan Wars. If you're a player you could join one of our clans. You can join your clan in our family regardless of your trophies or active players. We will help you to get your clan in top. If you wish to join your clan with us send a message on discord at SHZ#3057. JOIN US & PORSPER
  social:
    - discord: http://discord.gg/mq9maTfu
    - email: mailto: shzali0a0@gmail.com
clans:
  - name: Royal Fighters
    tag: 2UJG9082
  - name: Dark Blade
    tag: 90V2QYL8
  - name: ŚuPÉr ŠqÛÁdß
    tag: 2UCPOUGY
```

**Comment by smlbiobot** [comment]
```yml
name: Crimson Imperium
key: crimsonimperium
color: blue
emblem: Bolt_03
info:
  description: >
    Crimson Imperium is an old clan family from the days of Clan Chests. Our clans are always high in donations and are active in Clan Wars. If you're a player you could join one of our clans. You can join your clan in our family regardless of your trophies or active players. We will help you to get your clan in top. If you wish to join your clan with us send a message on discord at SHZ#3057. JOIN US & PORSPER
  social:
    - discord: https://discord.gg/mq9maTfu
    - email: mailto:shzali0a0@gmail.com
clans:
  - name: Royal Fighters
    tag: 2UJG9082
  - name: Dark Blade
    tag: 90V2QYL8
  - name: ŚuPÉr ŠqÛÁdß
    tag: 2UCPOUGY
```
