### ISSUE TITLE
HELLAS clan family

### ISSUE THREAD

**Issue by jimred81** [RoyaleAPI/family-config#654]
```yaml
name: HELLAS clan family
key: hellas
color: Blue
emblem:flag_d_04
info: 
  logo:
  description: >
Gathered in 2020. Reached 100 on the regional leaderboard. We are a family and enjoy the game most of all...
code: RoyaleAPI
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: HELLAS
    tag: LPOC2UC9
  - name:
    tag:
  - name:
    tag:
```
