### ISSUE TITLE
DragonSynn Family

### ISSUE THREAD

**Issue by Dridrizerozerosept** [RoyaleAPI/family-config#655]
```yaml
name: DragonSynn Family
key: DragonSynn 
color: yellow
emblem: Twin_Peaks_02
info:
  logo: https://images4.alphacoders.com/998/998422.jpg

  description: >
    Bienvenue dans la famille de clan française : DragonSynn Family.
Cette famille compte 5 clans ;
DragonSynn 
DragonSynn ll
DragonSynn lll
DragonSynn lvl1 ( clan pour les comptes niveaux 1 du roi)
DragonSynn 0 tr ( clan pour tout les comptes à 0 trophées ).

  social:
    - discord: http://discord.gg/QQ95bRnYx5
    - webpage: : https://DragonSynn.com
clans:
  - name: DragonSynn 
    tag: Q8P99U82
  - name: DragonSynn ll
    tag: QP8JOLCU
  - name: DragonSynn lll
    tag: GLURGQRL
  - name: DragonSynn lvl1
    tag: GLVGJLOL
  - name: DragonSynn 0tr
    tag: QVCCRGRV
```

**Comment by smlbiobot** [comment]
```yml
name: DragonSynn Family
key: DragonSynn
color: yellow
emblem: Twin_Peaks_02
info:
  logo: /static/img/brands/logo/dragon-synn.png
  description: >
    Bienvenue dans la famille de clan française : DragonSynn Family.
    Cette famille compte 5 clans ;


    - DragonSynn


    - DragonSynn ll


    - DragonSynn lll


    - DragonSynn lvl1 ( clan pour les comptes niveaux 1 du roi)


    - DragonSynn 0 tr ( clan pour tout les comptes à 0 trophées ).

  social:
    - discord: https://discord.gg/QQ95bRnYx5
    - website: https://DragonSynn.com
clans:
  - name: DragonSynn
    tag: Q8P99U82
  - name: DragonSynn ll
    tag: QP8JOLCU
  - name: DragonSynn lll
    tag: GLURGQRL
  - name: DragonSynn lvl1
    tag: GLVGJL0L
  - name: DragonSynn 0tr
    tag: QVCCRGRV
```

**Comment by smlbiobot** [comment]
```yml
name: DragonSynn Family
key: DragonSynn
color: yellow
emblem: Twin_Peaks_02
info:
  logo: /static/img/brands/logo/dragon-synn.png
  description: >
    Bienvenue dans la famille de clan française: DragonSynn Family.
    Cette famille compte 5 clans ;


    - DragonSynn


    - DragonSynn ll


    - DragonSynn lll


    - DragonSynn lvl1 ( clan pour les comptes niveaux 1 du roi)


    - DragonSynn 0 tr ( clan pour tout les comptes à 0 trophées ).

  social:
  - discord: https://discord.gg/QQ95bRnYx5
  - website: https://DragonSynn.com
clans:
- name: DragonSynn
  tag: Q8P99U82
- name: DragonSynn ll
  tag: QP8J0LCU
- name: DragonSynn lll
  tag: GLURGQRL
- name: DragonSynn lvl1
  tag: GLVGJL0L
- name: DragonSynn 0tr
  tag: QVCCRGRV

```
