### ISSUE TITLE
Edit in the Family config of Team Kingfisher

### ISSUE THREAD

**Issue by Spherical-Pegasus** [RoyaleAPI/family-config#658]
```yaml
name: Team Kingfisher
key: kingfisher
color: blue
emblem: Gem_02
info:
  logo: https://cdn.discordapp.com/attachments/818112712328347679/962306568685248512/IMG_20210613_092247.jpg
  description: >
    ㅤ**Team Kingfisher** is a growing Gaming community with ambitious Supercell Clans. We have been extending our limits since the day we were created and now we have achieved a dream that we had days ago! We house a lot of people of all ages from all parts of the world today and we haven't stopped ourselves to present new and interesting stuff to our Gaming mates. We have periodic Events and Tournaments also a YouTube channel, fun based Discord and Clans in Clash Royale and Clash of Clans. We expect your presious support to grow better. Thank you!
ㅤTeam Kingfisher ~ Aim to Glory!
ㅤSince 2020
  social:
    - discord: https://discord.com/invite/CBzYcZqD8D
    - youtube: https://www.youtube.com/channel/UCdcnP2M1aTj58z5cTiwAYTg
    - email: mailto:teamkingfisher.kc@gmail.com
clans:
  - name: Kingfisher
    tag: QOJJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R
```

**Comment by smlbiobot** [comment]
whats the change?
note that emails must be written this way:

```yml
  social:
    - discord: https://discord.com/invite/CBzYcZqD8D
    - youtube: https://www.youtube.com/channel/UCdcnP2M1aTj58z5cTiwAYTg
    - email: mailto:teamkingfisher.kc@gmail.com
```

ie you must put `mailto:` immediately in front of the email
