### ISSUE TITLE
INDIAN LIFE ✊

### ISSUE THREAD

**Issue by indianlifecr** [RoyaleAPI/family-config#659]
```yaml
name: INDIAN LIFE CLAN FAMILY
key: Indian Life
color: Blue
emblem: Skull_05
info:
  description: >
   The INDIAN LIFE CLAN FAMILY is a pure war zone .We NEVER lose War.We are a friendly bunch.
  social:
    - discord: https://discord.gg/6AXthZ95
    - twitter: https://twitter.com/indianlifecr
    - youtube: https://www.youtube.com/channel/UCcrxLKDsq1xFcw4N4cd5hpQ
    - Instagram:https://instagram.com/indianlifecr?igshid=YmMyMTA2M2Y=
    - email: Indianlifecr@gmail.com
    - whatsapp:https://chat.whatsapp.com/CUYUSjIhhIa70p6Tx7Lj4d
    - twitch:https://m.twitch.tv/indianlifecr/home
    - reddit:https://www.reddit.com/user/indianlifecr/
clans:
  - name: Boiled in Blood
    tag: LPJU8LCL
  - name: Hitmen
    tag: 9YGLOLYV
  - name: I FOR INDIAN
    tag: #289RQOL
  - name: AVENGERS
    tag: YUOUYUOQ
  - name: LOL INDIA
    tag: LPVRVQLU
  - name: INDIAN LIFE
    tag: YVJU2YLG
  - name: The Elite
    tag: L28QUJQP
  - name: Assasin's Hood
    tag: 2CJRGL
```

**Comment by smlbiobot** [comment]
https://royaleapi.com/f/indian-life

```yml
name: INDIAN LIFE CLAN FAMILY
key: indian-life
color: blue
emblem: Skull_05
info:
  description: >
    The INDIAN LIFE CLAN FAMILY is a pure war zone .We NEVER lose War.We are a friendly
    bunch.
  social:
  - discord: https://discord.gg/6AXthZ95
  - twitter: https://twitter.com/indianlifecr
  - youtube: https://www.youtube.com/channel/UCcrxLKDsq1xFcw4N4cd5hpQ
  - Instagram: https://instagram.com/indianlifecr?igshid=YmMyMTA2M2Y=
  - email: mailto:Indianlifecr@gmail.com
  - whatsapp: https://chat.whatsapp.com/CUYUSjIhhIa70p6Tx7Lj4d
  - twitch: https://m.twitch.tv/indianlifecr/home
  - reddit: https://www.reddit.com/user/indianlifecr/
clans:
- name: Boiled in Blood
  tag: LPJU8LCL
- name: Hitmen
  tag: 9YGL0LYV
- name: I FOR INDIAN
  tag: 289RQ0L
- name: AVENGERS
  tag: YU0UYU0Q
- name: LOL INDIA
  tag: LPVRVQLU
- name: INDIAN LIFE
  tag: YVJU2YLG
- name: The Elite
  tag: L28QUJQP
- name: Assasin's Hood
  tag: 2CJRGL
```
