### ISSUE TITLE
Chicken Winners

### ISSUE THREAD

**Issue by Asbleider117** [RoyaleAPI/family-config#66]
```yaml
name : Chicken Winners
key : Chicken Winners
color : orange
emblem : flag_j_03
sort : trophy
info :
   logo : 
![Logo eSports - PNG](https://user-images.githubusercontent.com/39997228/58515998-2d6bc780-816c-11e9-9965-abf8bc5c3875.png)
  description : > 
    **Competitive excellence through community-driven values.** Chicken Winners is a mobile eSports organization committed to empowering individuals through a supportive team environment. We look for talent that has the character to back it up. That talent is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes.
  sociales :
    - discord: https://discord.gg/mKtZ94J
    - twitter : https://twitter.com/ChickenWinners
    - youtube : http://www.youtube.com/channel/UCfxBAENi8BHQgvk26bV4IMw
    - email : mailto: contacto.chickenwinners@gmail.com
  clans :
  - name : Chicken Winners
     tag : PQU2CR2P
```
