### ISSUE TITLE
101% Canadian

### ISSUE THREAD

**Issue by SaskBadger** [RoyaleAPI/family-config#662]
```yaml
name: 101% Canadian Clan Family
key: canadian
color: red
emblem: https://github.com/RoyaleAPI/cr-api-assets/blob/master/badges/flag_j_02
info: 101% Canadian is Canada's premier Clan wars clan. Us, along with our family of clans strive to provide a positive, competive, fun and quality Clash Royale expeince, while focusing on Clan Wars.
  logo: https://cdn.britannica.com/68/7068-004-7848FEB4/Flag-Canada.jpg
  social:
    - discord: http://discord.gg/3evH8tJVam
clans:
  - name: 101% Canadian
    tag: 9UCRJG8V
  - name: 99.9% Canadian
    tag: 2QVJPQJG
  - name: DarkAlliance
    tag: 99VR0G2
  - name: Upheaval
    tag: PLL2LJQ2
  - name: 102% Canadian
    tag: LGCYVUCJ
  - name: 99.9%Stressfree
    tag: Y2L9QY08

```
