### ISSUE TITLE
Epikion Family Config Submission

### ISSUE THREAD

**Issue by AeroLMS** [RoyaleAPI/family-config#664]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Epikion
key: epk
color: blue
emblem: Heart_02
info:
  logo:
![EPKlogo](https://user-images.githubusercontent.com/103725460/163552019-4884b490-8dc8-4d16-a13c-7256d71ebbcf.jpg)

  description: >
     **Epikion** is a _Philippine-based Clash Royale Community_ created for every player; newbie, casual, or competitive to join and thrive in. The group's connections around the locality will serve as a way for everyone to enjoy, bond, learn, and strive for what's more to come.
  social:
    - discord: https://discord.gg/AfTwuWpDPu
 clans:
  - name: Epikion
    tag: YVGLQ22U
  - name: Epikion-II
    tag: LCRR9UJ2
```
