### ISSUE TITLE
Nova QC

### ISSUE THREAD

**Issue by Poup1017** [RoyaleAPI/family-config#666]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: > Axé sur les GDC (TOP MONDE), Nova QC est constitué de 9 clans pour tous les niveaux. 350 membres actifs et unis contribuent à la croissance constante de cette grande famille. Respect, entraide et plaisir garantis. Facebook/Messenger/Discord.
Focused on Clan Wars (TOP WORLD), Nova QC is made up of 9 clans for all levels. 350 active and united members contribute to the constant growth of this large familly. Respect, help between members and pleasure guaranteed. Facebook/Messenger/Discord.
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
  - name: Nova QC ☆ 7
    tag: LCQJRP2Q
  - name: Nova QC ☆ 8
    tag: QP8G8LLR
  - name: Nova QC ☆ 9
    tag: G0GVRCR8
```
