### ISSUE TITLE
Familia del Clan D£str☆y£r's

### ISSUE THREAD

**Issue by CarlosGMM6** [RoyaleAPI/family-config#668]
```yaml
name: Familia del Clan D£str☆y£r's
key: D£str☆y£r's
color: Black
emblem: A_Char_King_02.png
info:
  logo: ![War_Shield](https://user-images.githubusercontent.com/104025137/164089952-5b7dfceb-bafe-473e-b946-dee4ea15e9b5.png)
 description: > 
   ¡Bienvenidos a la Familia D£str☆y£r's !  Somos una familia de clanes competitiva que se enfoca en la guerra y la progresión del jugador.  Estamos buscando jugadores que estén enfocados en la guerra y que busquen un clan a largo plazo. 
Tenemos un clan disponible para muchos niveles de jugadores.  Nuestros miembros son muy activos y están dispuestos a ayudar a todos en nuestra familia a tener éxito. 
social:
      - discord: https://discord.gg/SAvYmWfjEM
  clans:
  - name: D£str☆y£r's
    tag: PGCPCLU8
  - name: D£str☆y£r's
    tag: G9UCV8LP
  - name: D£str☆y£r's 3
    tag: LC99VJGR 
clans sort: trophy
```

**Comment by smlbiobot** [comment]
you can’t have `D£str☆y£r's` as key. I will just use `destroyers`

**Comment by smlbiobot** [comment]
```yml
name: Familia del Clan D£str☆y£r's
key: destroyers
color: black
emblem: A_Char_King_02
sort: trophy
info:
  logo: /static/img/brands/logo/destroyers.png
  description: >
    ¡Bienvenidos a la Familia D£str☆y£r's !  Somos una familia de clanes competitiva que se enfoca en la guerra y la progresión del jugador.  Estamos buscando jugadores que estén enfocados en la guerra y que busquen un clan a largo plazo.
    Tenemos un clan disponible para muchos niveles de jugadores.  Nuestros miembros son muy activos y están dispuestos a ayudar a todos en nuestra familia a tener éxito.
  social:
  - discord: https://discord.gg/SAvYmWfjEM
clans:
- name: D£str☆y£r's
  tag: PGCPCLU8
- name: D£str☆y£r's
  tag: G9UCV8LP
- name: D£str☆y£r's 3
  tag: LC99VJGR

```

**Comment by smlbiobot** [comment]
```ymlname: Familia del Clan D£str☆y£r's
key: destroyers
color: black
emblem: A_Char_King_02
sort: trophy
info:
  logo: /static/img/brands/logo/destroyers.png
  description: >
    ¡Bienvenidos a la Familia D£str☆y£r's !  Somos una familia de clanes competitiva
    que se enfoca en la guerra y la progresión del jugador.  Estamos buscando jugadores
    que estén enfocados en la guerra y que busquen un clan a largo plazo.
    Tenemos un clan disponible para muchos niveles de jugadores.  Nuestros miembros
    son muy activos y están dispuestos a ayudar a todos en nuestra familia a tener
    éxito.
  social:
  - discord: https://discord.gg/SAvYmWfjEM
clans:
- name: D£str☆y£r's
  tag: PGCPCLU8
- name: D£str☆y£r's
  tag: G9UCV8LP
- name: D£str☆y£r's 3
  tag: LC99VJGR
```

https://royaleapi.com/f/destroyers
