### ISSUE TITLE
Issue dk'ogres family clan

### ISSUE THREAD

**Issue by AlbanDelaby** [RoyaleAPI/family-config#670]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Les Ogres DKpsuleurs
key: dk'ogres
color: green
emblem: A_Char_Goblin_02
info: 
  logo: 
![Logo discord CR](https://user-images.githubusercontent.com/104254032/164912202-56220106-9ee1-4995-ba19-5cdbf3fcbf4c.png)

  description: >
    La famille des **Ogres DKpsuleurs** est composée de 6 clans axés sur le ladder ou les gdc en fonction du clan, chacun sa spécialité. Nous accueillons des joueurs expérimentés comme des débutants, à partir de 2.000-2.300 trophées. Le recrutement se fait via discord : https://discord.gg/FAfEnsRjgT.  


    
  social:
    - discord: https://discord.gg/FAfEnsRjgT
clans:
  - name: Dk'ogres
    tag: L20VR9PC
  - name: DK'OGRES 2
    tag: LGQUGGY9
   - name: Dk'ogres 3
    tag: LRQ0JVRP
   - name: Dk'ogres Push
    tag: GP8CPY0Q
   - name: DK'ogres Bolly
    tag: LJV0LLPJ
   - name: DK'Ogres Onyx
    tag: G0VJ8L9P
```

**Comment by smlbiobot** [comment]
```yml
name: Les Ogres DKpsuleurs
key: dk-ogres
color: green
emblem: A_Char_Goblin_02
info:
  logo: /static/img/brands/logo/dk-ogres.png

  description: >
    La famille des **Ogres DKpsuleurs** est composée de 6 clans axés sur le ladder ou les gdc en fonction du clan, chacun sa spécialité. Nous accueillons des joueurs expérimentés comme des débutants, à partir de 2.000-2.300 trophées. Le recrutement se fait via discord : https://discord.gg/FAfEnsRjgT.



  social:
    - discord: https://discord.gg/FAfEnsRjgT
clans:
- name: Dk'ogres
  tag: L20VR9PC
- name: DK'OGRES 2
  tag: LGQUGGY9
- name: Dk'ogres 3
  tag: LRQ0JVRP
- name: Dk'ogres Push
  tag: GP8CPY0Q
- name: DK'ogres Bolly
  tag: LJV0LLPJ
- name: DK'Ogres Onyx
  tag: G0VJ8L9P
```
