### ISSUE TITLE
LOS MATA FURROS

### ISSUE THREAD

**Issue by Juliank9** [RoyaleAPI/family-config#671]
```yaml
name: LOS MATA FURROS
key: furros
color: red
emblem: flag_h_04
info: 
  logo: https://media.discordapp.net/attachments/929028101713821726/967513420884750436/Logo_del_ClanSin_fondo.png
  description: >
 !La familia de **LOS MATA FURROS** es una de las más grandes y antiguas de Clash Royale! Desde un principio, hemos crecido enormemente todo unidos como una familia y creemos que esa es la razón por la que hemos llegado tan lejos. Y es que los clanes son lugar para todos, desde jugadores casuales hasta jugadores competitivos, mayores a jóvenes, activos a muy activos. Todos compartimos una pasión por el juego, somos amigos, siempre donamos, nos ayudamos mutuamente con el mismo objetivo: ¡mejorar siempre nuestras habilidades y pasar un buen rato. **!Vamos FURROS!**

 *Clanes: LOS MATA FUROS, próximamente...*
  social:
    - discord: http://discord.gg/z3heD9ewy6
clans:
  - name: LOS MATA FURROS
    tag: L0YV8Q0Q
```
