### ISSUE TITLE
WNSE Crew

### ISSUE THREAD

**Issue by Suecobo** [RoyaleAPI/family-config#673]
```yaml
name: WNSE Crew
key: WNSE
color: blue
emblem: A_Char_King_03
info:
  logo: https://github.com/RoyaleAPI/cr-api-assets/blob/master/badges/A_Char_King_03.png
  description: >
    Familia de clanes creada el 6/11/2016, enfocados tanto en ladder como en guerra. Únete a nosotros si eres activo y te gusta un clan con buen rollo. 
 
clans:
  - name: West Royale
    tag: 22UCCPPY
  - name: North Royale
    tag: L8Y92UY
  - name: South Royale
    tag: LYPVPGR8
  - name: East Royale
    tag: G0J8J8JU
```
