### ISSUE TITLE
Diamonds

### ISSUE THREAD

**Issue by Ranallo94** [RoyaleAPI/family-config#674]
```yaml
name: Diamonds
key: diamonds
color: blue
emblem: Diamond_03
description: >
La Famiglia Diamonds è una delle migliori famiglie di clan in Italia, formata da 4 clan e 200 giocatori. Gli obiettivi principali sono la guerra, la scalata, la squadra competitiva, la crescita dei giocatori e l'amicizia. Ci sono anche tornei mensili con diverse modalità di gioco e premi.

social:
- twitch: twitch.com/klais28
- telegram: https://telegram.me/fabiocipriani
- telegram: https://telegram.me/MiTiCo87
- instagram: https://instagram.com/diamonds.clashroyale 

clans:
name: Diamonds 
tag: P0LGP80U
name: Diamonds II
tag: 9QCVJLJ2
name: Diamonds III
tag: P2QGRLPV
name: Diamonds IV
tag: P0LRLQC9
```
