### ISSUE TITLE
Liverpool

### ISSUE THREAD

**Issue by Liverpool-Clan** [RoyaleAPI/family-config#676]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Liverpool Family
key: liverpool
color: red
emblem: flag_f_02
info:
  logo:
  description: >
    This is Anfield. For Liverpool fans By Liverpool fans.


    YNWA
  social:
    
clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool™️
    tag: QGJ0YGPP
```
