### ISSUE TITLE
Inquisitors Clash Royale Family

### ISSUE THREAD

**Issue by Harsh-Bajpai1194** [RoyaleAPI/family-config#678]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: InquisitorsClashRoyaleFamily
key: fire
color: black
emblem: Skull_01

info: WE ARE NOT A GOOD CLAN BECAUSE WE ARE THE BEST CLAN! --By FIRE 🔥 royaleapi.com and be active for clan war
  logo: https://drive.google.com/file/d/1S30qToN79xtkcL0HU04p-PX_4d6_sfXg/view
  description: > We are a war clan.
    We are the best family! 

  social:
    - email: gjdyvjff@gmail.com
clans:
  - name: THE INQUISITORS
    tag: PRQ88POO
  - name: INDIAN CLAN
    tag: YPQPLJ9L
```
