### ISSUE TITLE
Inquisitors update to royaleapi family configuration

### ISSUE THREAD

**Issue by Harsh-Bajpai1194** [RoyaleAPI/family-config#679]
name: InquisitorsClashRoyaleFamily
key: fire
color: black
emblem: Skull_01

info: WE ARE NOT A GOOD CLAN BECAUSE WE ARE THE BEST CLAN! --By FIRE 🔥 royaleapi.com and be active for clan war
  logo: https://drive.google.com/file/d/1S30qToN79xtkcL0HU04p-PX_4d6_sfXg/view
  description: > We are a war clan.
    We are the best family! 

  social:
    - email: gjdyvjff@gmail.com
clans:
  - name: THE INQUISITORS
    tag: PRQ88POO
  - name: INDIAN CLAN
    tag: YPQPLJ9L

**Comment by smlbiobot** [comment]
```yml
name: Inquisitors Family
key: inquisitors
color: black
emblem: Skull_01

info:
  logo: /static/img/brands/logo/inquisitors.png
  description: >
    WE ARE NOT A GOOD CLAN BECAUSE WE ARE THE BEST CLAN! --By FIRE 🔥 royaleapi.com and be active for clan war
    
    
    We are a war clan. We are the best family!

  social:
    - email: mailto:gjdyvjff@gmail.com
clans:

  - name: THE INQUISITORS
    tag: PRQ88POO
  - name: INDIAN CLAN
    tag: YPQPLJ9L
```
