### ISSUE TITLE
Westwall Family on Royale Api

### ISSUE THREAD

**Issue by WWEChishiya** [RoyaleAPI/family-config#681]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Westwall Eifel Familie
key: WWE
color: black
emblem: Skull_05
info:
  logo: 
  description: >
  Die Westwall Eifel Familie hat sich mit ganzem Herzen dem Clankrieg verschrieben.
  Egal ob Anfänger oder bereits CW-erfahrener Spieler, für jeden ist der passende Clan dabei.
  **Westwall 2:** Für top Spieler mit starkem Level und guter Statistik (4/4 Pflicht)
  **Westwall 4:** Trainingscamp für WWE2, beweise dich und steige auf (4/4 Pflicht)
 ** Westwall 5:** Entspannter Clan für Urlauber aus den oberen Clans oder Just-4-Fun-Spieler
  social:
    - discord: https://discord.com/invite/RJ6ryaEPfH
clans:
  - name: WestwallEifel 2
    tag: 80CRJJ98
  - name: WestwallEifel 4
    tag: YG80VPLQ
  - name: WestwallEifel 5
    tag: LVG9YP0R
```
