### ISSUE TITLE
Watanka

### ISSUE THREAD

**Issue by Elsaca70** [RoyaleAPI/family-config#684]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Fondati il 6 dicembre 2021 i Watanka sono clan dove si gioca senza stress divertendosi con rispetto ed educazione.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: 
    - facebook: https://www.facebook.com/troupe/1535997746774101/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Watanka
    tag: LL9C0JJ0
  - name: Watanka||
    tag: LGCRCVOC
  - name:
    tag:
```
