### ISSUE TITLE
Clan Family Update add new clans

### ISSUE THREAD

**Issue by shz0a0** [RoyaleAPI/family-config#685]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Crimson Imperium
key: crimsonimperium
color: blue
emblem: Bolt_03
info:
  description: >
    The **Crimson Imperium** is an old clan family from the days of Clan Chests. Our clans are always high in donations and are active in Clan Wars. If you're a player you could join one of our clans. You can also join your clan in our family regardless of your trophies or active players. We will help you to get your clan in top. If you wish to join your clan with us send a message on discord at SHZ#3057. JOIN US & PROSPER!!
  social:
    - discord: http://discord.gg/WqgddRWBKj
    - email: mailto: shzali0a0@gmail.com
clans:
  - name: Royal Fighters
    tag: 2UJG9082
  - name: Dark Blade
    tag: 90V2QYL8
  - name: Clash King
    tag: Q02GCUP8
  - name: Stoned Ninjas
    tag: 9VPRQ0L0
  - name: Bear Mafia
    tag: 8J22PGUV
  - name: Crimson Tide
    tag: Y2U9LLUV
  - name: 无双_名将阁
    tag: PJ22QJ2L
```
