### ISSUE TITLE
EURO I UNION

### ISSUE THREAD

**Issue by PavlonatorGR** [RoyaleAPI/family-config#687]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: EURO I UNION
key: EURO I UNION
color: blue
emblem: Traditional_Star_05
info:
  description: >
    Willkommen bei der EURO I UNION! Wir sind eine Clanfamilie welche mit dem Clan "king for ever" im Jahr 2017 ihre Leidenschaft für Clash Royale gefunden hat. In den Clankriegen beweist EUROPEAN ELITE, wer hier wirklich die ELITE ist und EURO I LEAGUE, auf welcher Liga unser Niveau und Skill sich befindet. "king for ever" ist der Hauptsitz der beiden Clan's da unsere gemeinsame Geschichte hier ihren Anfang fand. Unser Motto: "WIR SEHEN UNS IN DER ARENA!!!"
  social:
    -discord: https://discord.gg/HJd385NdzC
clans:
  - name: king for ever
    tag: YPLRGRPL
  - name: EUROPEAN ELITE
    tag: LQP0U2GR
  - name: EURO I LEAGUE
    tag: QU22J809
```

**Comment by smlbiobot** [comment]
do you want this or not? if you want it then don’t close it.

**Comment by PavlonatorGR** [comment]
That's my First time using GitHub. Sorry for closing the issue.

**Comment by smlbiobot** [comment]
```yml
name: EURO I UNION
key: euro-i-union
color: blue
emblem: Traditional_Star_05
info:
  description: >
    Willkommen bei der EURO I UNION! Wir sind eine Clanfamilie welche mit dem Clan
    "king for ever" im Jahr 2017 ihre Leidenschaft für Clash Royale gefunden hat.
    In den Clankriegen beweist EUROPEAN ELITE, wer hier wirklich die ELITE ist und
    EURO I LEAGUE, auf welcher Liga unser Niveau und Skill sich befindet. "king for
    ever" ist der Hauptsitz der beiden Clan's da unsere gemeinsame Geschichte hier
    ihren Anfang fand. Unser Motto: "WIR SEHEN UNS IN DER ARENA!!!"
  social:
  - discord: https://discord.gg/HJd385NdzC
clans:
- name: king for ever
  tag: YPLRGRPL
- name: EUROPEAN ELITE
  tag: LQP0U2GR
- name: EURO I LEAGUE
  tag: QU22J809

```

https://royaleapi.com/f/euro-i-union
