### ISSUE TITLE
Epikion Family Config Update (Added Clan)

### ISSUE THREAD

**Issue by AeroLMS** [RoyaleAPI/family-config#691]
Changes:
- Added Aergion to the clan list.

```yaml
name: Epikion
key: epk
color: blue
emblem: Heart_02
info:
  logo:
![EPKlogo](https://user-images.githubusercontent.com/103725460/163552019-4884b490-8dc8-4d16-a13c-7256d71ebbcf.jpg)

  description: >
     **Epikion** is a _Philippine-based Clash Royale Community_ created for every player; newbie, casual, or competitive to join and thrive in. The group's connections around the locality will serve as a way for everyone to enjoy, bond, learn, and strive for what's more to come.
  social:
    - discord: https://discord.gg/AfTwuWpDPu
 clans:
  - name: Epikion
    tag: YVGLQ22U
  - name: Epikion-II
    tag: LCRR9UJ2
  - name: Aergion
    tag: Q9U998GR
```

**Comment by smlbiobot** [comment]
please edit this in the future:

```yml
name: Epikion
key: epk
color: blue
emblem: Heart_02
info:
  logo: /static/img/brands/logo/epikion.png
  description: >
    **Epikion** is a _Philippine-based Clash Royale Community_ created for every player;
    newbie, casual, or competitive to join and thrive in. The group's connections
    around the locality will serve as a way for everyone to enjoy, bond, learn, and
    strive for what's more to come.
  social:
    - discord: https://discord.gg/AfTwuWpDPu
clans:
  - name: Epikion
    tag: YVGLQ22U
  - name: Epikion-II
    tag: LCRR9UJ2
  - name: Aergion
    tag: Q9U998GR
```
