### ISSUE TITLE
Tactical Edge 

### ISSUE THREAD

**Issue by page118** [RoyaleAPI/family-config#692]
```yaml
name: Tactical Edge
key: tactical
color: green
emblem: goblin
info:
 logo: ![54cf8b569a094897ae4daf37509dd332](https://user-images.githubusercontent.com/100172939/170893266-6d958900-f191-45c7-9c86-03843e53930c.png)
description: > Welcome to Tactical Edge! We are a top war clan focused on bringing a competitive, close community that supports each and every one of our members. Our main clan focuses on war, while our newer clans hope to expand the family and attributes that make us us.
social:
   - discord: https://discord.gg/eVrvm7u2Vt
clans:
  - name: Tactical Edge
    tag: 8CVUG80L 
  - name: Tactical Aspect
    tag: G9GPR0VP
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
update this in the future:

```yml
name: Tactical Edge
key: tactical
color: green
emblem: A_Char_Goblin_01
info:
  logo: /static/img/brands/logo/tactical-edge.png
  description: Welcome to Tactical Edge! We are a top war clan focused on bringing a competitive, close community that supports each and every one of our members. Our main clan focuses on war, while our newer clans hope to expand the family and attributes that make us us.
  social:
    - discord: https://discord.gg/eVrvm7u2Vt
clans:
  - name: Tactical Edge
    tag: 8CVUG80L
  - name: Tactical Aspect
    tag: G9GPR0VP

```
