### ISSUE TITLE
Guards

### ISSUE THREAD

**Issue by aZekea** [RoyaleAPI/family-config#693]
```yaml
name: Гвардия Clan Family
key:  гвардия
color: blue
emblem: flag_j_03.png
info:
  description: >
    **Семья кланов Гвардия** Ждет активных, общительных игроков.
  social:
    - discord: https://discord.gg/aFN5UWuvmE
clans:
  - name: Белая Гвардия
    tag: YUV2Y2R
  - name: Темная Гвардия
    tag: QRJ8LJC9
  - name: Красная Гвардия
    tag: QV9U0LGV
```

**Comment by smlbiobot** [comment]
can’t use cyrillic keys

```yml
name: Гвардия Clan Family
key: guards
color: blue
emblem: flag_j_03.png
info:
  description: >
    **Семья кланов Гвардия** Ждет активных, общительных игроков.
  social:
    - discord: https://discord.gg/aFN5UWuvmE
clans:
  - name: Белая Гвардия
    tag: YUV2Y2R
  - name: Темная Гвардия
    tag: QRJ8LJC9
  - name: Красная Гвардия
    tag: QV9U0LGV
```
