### ISSUE TITLE
Update Center Court Family

### ISSUE THREAD

**Issue by MamaMuc** [RoyaleAPI/family-config#694]
```yaml
name: Center Court Clanfamilie
key: CC
color: green
emblem: Clover_02
info:
   logo: https://cdn.discordapp.com/attachments/925816480048767016/979101697773297684/logo4_1_233618-2.png
   description: >
        Die **Center Court Clanfamilie** wurde im Oktober 2017 mit dem Main Clan Center Court gegründet und ist aufgrund des 
        Zusammenhalts und der damit einhergehenden Erfolge stetig gewachsen. Im Fokus stehen seither vor allem die Clankriege. Aber 
        auch die individuellen Ziele im Bereich Ladder können bei uns verfolgt werden. Wer darauf sein besonderes Augenmerk richten 
        möchte, kann dem in unserem Ladderclan CC Grand Slam nachgehen. 
        Ob Clankrieg oder Ladder, jedes Mitglied der Familie wird im Chat oder auch bei Discord gern dabei unterstützt, eigene Ziele zu 
        erreichen und sich weiterzuentwickeln. Insbesondere unser umfangreicher Discordserver bietet neben der Vernetzung aller Clans 
        der Clanfamilie dazu verschiedene Möglichkeiten.
        Sollte eine Pause oder eine generelle Auszeit aus verschiedenen Gründen erforderlich sein (Urlaub, Familie, RL, Beruf), sind 
        durch unsere Clanstruktur auch dafür Optionen vorhanden.

        Wir heißen alle willkommen, die mit uns 100% geben möchten!
        Tritt einem unserer Clans bei und werde ebenso Teil der Center Court Clanfamilie!


  social:
    - discord: https://discord.gg/v3nxSfZ2Gb
    
clans:
  - name: Center Court
     tag: 898P08VR
  - name: Titan clan 1
     tag: 9UPQJYVU
  - name: Center Court 2
     tag: LV8GYP0U
  - name: Center Court 3
     tag: YCVUQQY0
  - name: CC Grand Slam
     tag: GYVJYU8Q 
  - name: CC Familie
     tag: QPYCPUJR
```

**Comment by smlbiobot** [comment]
don’t use your own formatting

```yml
name: Center Court
key: CC
color: green
emblem: Clover_02
info:
  logo: /static/img/brands/logo/center-courte.png
  description: >
    Die **Center Court Clanfamilie** wurde im Oktober 2017 mit dem Main Clan Center Court gegründet und ist aufgrund des 
    Zusammenhalts und der damit einhergehenden Erfolge stetig gewachsen. Im Fokus stehen seither vor allem die Clankriege. Aber 
    auch die individuellen Ziele im Bereich Ladder können bei uns verfolgt werden. Wer darauf sein besonderes Augenmerk richten 
    möchte, kann dem in unserem Ladderclan CC Grand Slam nachgehen. 
    Ob Clankrieg oder Ladder, jedes Mitglied der Familie wird im Chat oder auch bei Discord gern dabei unterstützt, eigene Ziele zu 
    erreichen und sich weiterzuentwickeln. Insbesondere unser umfangreicher Discordserver bietet neben der Vernetzung aller Clans 
    der Clanfamilie dazu verschiedene Möglichkeiten.
    Sollte eine Pause oder eine generelle Auszeit aus verschiedenen Gründen erforderlich sein (Urlaub, Familie, RL, Beruf), sind 
    durch unsere Clanstruktur auch dafür Optionen vorhanden.


    Wir heißen alle willkommen, die mit uns 100% geben möchten!
    Tritt einem unserer Clans bei und werde ebenso Teil der Center Court Clanfamilie!

  social:
    - discord: https://discord.gg/v3nxSfZ2Gb

clans:
  - name: Center Court
    tag: 898P08VR
  - name: Titan clan 1
    tag: 9UPQJYVU
  - name: Center Court 2
    tag: LV8GYP0U
  - name: Center Court 3
    tag: YCVUQQY0
  - name: CC Grand Slam
    tag: GYVJYU8Q
  - name: CC Familie
    tag: QPYCPUJR
```
