### ISSUE TITLE
Add family Serenity

### ISSUE THREAD

**Issue by Eivlys59** [RoyaleAPI/family-config#695]
```yaml
name: ⚔️ SerenitY ⚔️
key: serenity
color: Blue
emblem: Sword_01
info:
  logo: https://imgur.com/a/Xyj8BzY
  description: >
  **SerenitY** est né de la volonté de jouer et avancer en toute sérénité dans un clan où chacun se sent bien, 
  où l'on prend plaisir à se retrouver.
  Bonne humeur, bienveillance, convivialité, solidarité, maturité, **gestion rigoureuse**.

  **3 clans**, pour convenir à tous. Que tu aimes beaucoup, un peu ou pas du tout les gdc, ou selon  
  tes envies et disponibilités du moment...

  ⚔️ **SerenitY** ⚔️ pour les warriors, les winners, les plus assidus   
  en gdc! **4 decks/jour**, un esprit collectif et un max de points avec en ligne de mire **être et  
  rester 1ers**, rafler le plus gros coffre, **devenir clan légendaire et classé**. Ici on ne laisse pas  
  ramer les autres à sa place.

  ⚓ **SerenitY** ⚓ notre clan **"gdc soft"**, pour ceux dont l'envie de gdc est plus  
  modérée, pour un coffre **sans contraintes ni pression**, en combat ou attaque de bateau, 
  **tant que tu ne restes pas à 0**. Pas d'objectif de clan. Tu auras le coffre que vous serez allé chercher.

  ☀️ **SerenitY** ☀️ clan **sans gdc imposée** et ouvert à tous. Pour jouer en toute tranquillité.
   
**N'hésite pas à nous contacter!** ⚔️ ⚓ ☀️


  social:
    - discord: https://discord.gg/6AczMBBdJG
    - facebook: https://www.facebook.com/profile.php?id=100004265896127
clans:
  - name: ⚔️ SerenitY ⚔️
    tag: QJ9URG9V
  - name: ⚓ SerenitY ⚓
    tag: LV29LVRV
  - name: ☀️ SerenitY ☀️
    tag: LCR9VLL0
```

**Comment by smlbiobot** [comment]
edit this in the future:

```yml
name: ⚔️ SerenitY ⚔️
key: serenity
color: Blue
emblem: Sword_01
info:
  logo: /static/img/brands/logo/serenity.png
  description: >
    **SerenitY** est né de la volonté de jouer et avancer en toute sérénité dans un clan où chacun se sent bien, 
    où l'on prend plaisir à se retrouver.
    Bonne humeur, bienveillance, convivialité, solidarité, maturité, **gestion rigoureuse**.
    
    **3 clans**, pour convenir à tous. Que tu aimes beaucoup, un peu ou pas du tout les gdc, ou selon  
    tes envies et disponibilités du moment...
    
    ⚔️ **SerenitY** ⚔️ pour les warriors, les winners, les plus assidus   
    en gdc! **4 decks/jour**, un esprit collectif et un max de points avec en ligne de mire **être et  
    rester 1ers**, rafler le plus gros coffre, **devenir clan légendaire et classé**. Ici on ne laisse pas  
    ramer les autres à sa place.
    
    ⚓ **SerenitY** ⚓ notre clan **"gdc soft"**, pour ceux dont l'envie de gdc est plus  
    modérée, pour un coffre **sans contraintes ni pression**, en combat ou attaque de bateau, 
    **tant que tu ne restes pas à 0**. Pas d'objectif de clan. Tu auras le coffre que vous serez allé chercher.
    
    ☀️ **SerenitY** ☀️ clan **sans gdc imposée** et ouvert à tous. Pour jouer en toute tranquillité.

    **N'hésite pas à nous contacter!** ⚔️ ⚓ ☀️


  social:
    - discord: https://discord.gg/6AczMBBdJG
    - facebook: https://www.facebook.com/profile.php?id=100004265896127
clans:
  - name: ⚔️ SerenitY ⚔️
    tag: QJ9URG9V
  - name: ⚓ SerenitY ⚓
    tag: LV29LVRV
  - name: ☀️ SerenitY ☀️
    tag: LCR9VLL0
```
