### ISSUE TITLE
Update the Inquisitors Family

### ISSUE THREAD

**Issue by Harsh-Bajpai1194** [RoyaleAPI/family-config#696]
```yml
name: Inquisitors Family
key: inquisitors
color: black
emblem: Skull_01

info:
  logo: /static/img/brands/logo/inquisitors.png
  description: >
    **INQUISITORS** is a growing Gaming community with ambitious Supercell Clans. We have been extending our limits since the day we were created and now we have achieved a dream that we had days ago! We house a lot of people of all ages from all parts of the world today and we haven't stopped ourselves to present new and interesting stuff to our Gaming mates. We have periodic Events and Tournaments also a YouTube channel, fun based Discord and Clans in Clash Royale and Clash of Clans. We expect your presious support to grow better. Thank you!
ㅤTeam Kingfisher ~ Aim to Glory!
ㅤSince 2020
    WE ARE NOT A GOOD CLAN BECAUSE WE ARE THE BEST CLAN! --By FIRE 🔥 royaleapi.com and be active for clan war
    
    
    We are a war clan. We are the best family!

  social:
    - email: mailto:gjdyvjff@gmail.com
clans:

  - name: THE INQUISITORS
    tag: PRQ88POO
  - name: INDIAN CLAN
    tag: YPQPLJ9L
```

**Comment by smlbiobot** [comment]
```yml
name: Inquisitors Family
key: inquisitors
color: black
emblem: Skull_01

info:
  logo: /static/img/brands/logo/inquisitors.png
  description: >
    **INQUISITORS** is a growing Gaming community with ambitious Supercell Clans. We have been extending our limits since the day we were created and now we have achieved a dream that we had days ago! We house a lot of people of all ages from all parts of the world today and we haven't stopped ourselves to present new and interesting stuff to our Gaming mates. We have periodic Events and Tournaments also a YouTube channel, fun based Discord and Clans in Clash Royale and Clash of Clans. We expect your presious support to grow better. Thank you!
    ㅤ
    
    Team Kingfisher ~ Aim to Glory!
    
    
    Since 2020
    
    
    WE ARE NOT A GOOD CLAN BECAUSE WE ARE THE BEST CLAN! --By FIRE 🔥 royaleapi.com and be active for clan war
    
    
    We are a war clan. We are the best family!

  social:
    - email: mailto:gjdyvjff@gmail.com
clans:

  - name: THE INQUISITORS
    tag: PRQ88P00
  - name: INDIAN CLAN
    tag: YPQPLJ9L

```
