### ISSUE TITLE
BD Heroes

### ISSUE THREAD

**Issue by tahxin** [RoyaleAPI/family-config#697]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: BD Heroes
key: BD
color: Red
emblem: flag_i_01
info:
  logo: https://cdn.royaleapi.com/static/img/badge/silver-1/flag_i_01.png?t=ac553486c
  description: >
 One of the first few and original Clan Family of Bangladesh.




  social:

    - email: mailto:satahsin6@gmail.com
clans:
  - name: BD Heroes
    tag: 80Q2R8
  - name: BD Heroes II
    tag: UJYQCC0
```
