### ISSUE TITLE
Update needed for Liverpool Family

### ISSUE THREAD

**Issue by Liverpool-Clan** [RoyaleAPI/family-config#698]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Liverpool Family
key: liverpool
color: red
emblem: flag_f_02
info:
  logo: 
  description: >
    This is Anfield. We are Liverpool. Global international Liverpool F.C. supporters into clash royale. Top 50 International Clan War clan. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!
  social:

clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
```

**Comment by smlbiobot** [comment]
```yml
name: Liverpool Family
key: liverpool
color: red
emblem: flag_f_02
info:
  description: >
    This is Anfield. We are Liverpool. Global international Liverpool F.C. supporters into clash royale. Top 50 International Clan War clan. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!



clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool™️
    tag: QGJ0YGPP

```
