### ISSUE TITLE
3 Crown Family (Update)

### ISSUE THREAD

**Issue by csimpson11** [RoyaleAPI/family-config#7]
```yaml
name: 3 Crown Family
key: 3Crown
color: blue
emblem: Crown_03
logo: https://imgur.com/a/ZFU8gVs
info:
  description: >
    Welcome to the **3 Crown Family**! We are a competitive clan family that focuses on War and Player Progression. We are looking for players that are War focused and looking for a long-term clan.


    We have a clan available for many levels of players. Our members are very active and willing to help everyone in our family succeed. Our Discord has 100+ members so it’s a great way for everyone to communicate about war, trades, or just to socialize.
  social:
    - discord: https://discord.gg/v4azkxj
    - reddit: https://www.reddit.com/message/compose/?to=3C_Coleslaw
clans:
  - name: 3 Crown N' Down
    tag: 2R89V00G
  - name: 3 Crown Bravo
    tag: PRG9CJ90
  - name: 3 Crown Charlie
    tag: P8L8VUCV
```
