### ISSUE TITLE
NICECLAN

### ISSUE THREAD

**Issue by Data-1979** [RoyaleAPI/family-config#700]
```yaml
name: #NiceClan Family
key: #NC
color: red
emblem: https://images.app.goo.gl/s1ogy9KzMGNTyL6J8
info:
  logo: Sword_04
  description: >
Einst,` im Februar anno 2016, kurz nach Entstehung der CR Welt, zog ein stolzer Jüngling aus, um dieser Welt Frieden und Gerechtigkeit zu bringen. Bald musste er einsehen, dass er das alleine nicht vollbringen konnte, und so scharte er aufrechte und tapfere Recken um sich, und gemeinsam und treu kämpften sie  gegen dunkle Mächte und das Böse. Um allen zu zeigen, wofür sie standen und kämpften, nannten sie sich **NiceClan**!

CW Clan - Treue, Respekt, Loyalität


100% CW Teilnahmepflicht


Liga - Legendary 2


Leader - Guru 
(in Vertretung - Saphira )




Im Laufe der Zeit hatten sich Ruhm und Erfolg des Niceclan in der CR Welt herumgesprochen und immer mehr tapfere Recken wollten den Clan in seinem Kampf für das Gute unterstützen. Doch da die Größe der Tafel des legendären Trupps beschränkt ist, mussten viele tapfere Krieger abgewiesen werden, was wiederum zu Hadern und Unmut bei unseren Helden führte, solch wacker Recken wegschicken zu müssen. Und so kam es zur Gründung des **Niceclan 2** !

CW Clan im Aufbau - Treue, Respekt, Loyalität


Liga - Bronze 2


Leader - Cram 
  social:
    - discord: https://discord.gg/gMhqFewaav
clans:
  - name: #NiceClan
    tag: YUU8VR
  - name: #NiceClan 2
    tag: Q2CG2RCJ
  - name: #NC Chilloutzon
    tag: LC99G8Y8
```

**Comment by smlbiobot** [comment]
stop opening and closing. do you want this or not?

**Comment by smlbiobot** [comment]
Keep this open if you want this

**Comment by Data-1979** [comment]
Oh, I didn't know, if I have to open it or close. So I testen both. Excuse me. Yes, I want it. I want to choose another logo later, but for now its ok

**Comment by smlbiobot** [comment]
```yml
name: ""#NiceClan Family"
key: NC
color: red
emblem: Sword_04
info:
  logo: /static/img/brands/logo/nice-clan.png
  description: >
    Einst,` im Februar anno 2016, kurz nach Entstehung der CR Welt, zog ein stolzer Jüngling aus, um dieser Welt Frieden und Gerechtigkeit zu bringen. Bald musste er einsehen, dass er das alleine nicht vollbringen konnte, und so scharte er aufrechte und tapfere Recken um sich, und gemeinsam und treu kämpften sie  gegen dunkle Mächte und das Böse. Um allen zu zeigen, wofür sie standen und kämpften, nannten sie sich **NiceClan**!
    
    
    CW Clan - Treue, Respekt, Loyalität
    
    
    100% CW Teilnahmepflicht
    
    
    Liga - Legendary 2
    
    
    Leader - Guru
    (in Vertretung - Saphira )
    
    
    Im Laufe der Zeit hatten sich Ruhm und Erfolg des Niceclan in der CR Welt herumgesprochen und immer mehr tapfere Recken wollten den Clan in seinem Kampf für das Gute unterstützen. Doch da die Größe der Tafel des legendären Trupps beschränkt ist, mussten viele tapfere Krieger abgewiesen werden, was wiederum zu Hadern und Unmut bei unseren Helden führte, solch wacker Recken wegschicken zu müssen. Und so kam es zur Gründung des **Niceclan 2** !
    
    
    CW Clan im Aufbau - Treue, Respekt, Loyalität
    
    
    Liga - Bronze 2
    
    
    Leader - Cram
  social:
    - discord: https://discord.gg/gMhqFewaav
clans:
  - name: "#NiceClan"
    tag: YUU8VR
  - name: "#NiceClan 2"
    tag: Q2CG2RCJ
  - name: "#NC Chilloutzon"
    tag: LC99G8Y8
```
