### ISSUE TITLE
Update needed for Mage Knights family

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#701]
name: Mage Knights
key: mageknights
color: violet
emblem: A_Char_Knight_01
info:
logo: static/img/brands/logo/mage-knights.png?t=393c9e38c
description: >
The **Mage Knights** are a family of clans, which is primarily war-focused
and a community based on Clash Royale and Brawl Stars, playing both competitively and casually.
We value the entire card collection, not just your ladder deck,
but our family accepts players of all skill and card levels.
We also value practice and constructive criticism and there's always room for improvement.
Mage Knights’ main clan is currently top 50 in U.S. clan war rankings.
social:
- website: https://www.secondlightband.com/
- facebook: https://www.facebook.com/SecondLightBand/
- instagram: https://www.instagram.com/secondlightband/
- discord: https://dsc.gg/mageknights
- reddit: https://www.reddit.com/user/Mage_Knights/
- youtube: https://www.youtube.com/channel/UC1R-b1AET3-eLGQNed6TYzA
clans:
- name: Mage Knights
tag: 2V28Y88Q
- name: Mage Knights 2
tag: YR00L2LY
- name: Mage Knights 3
tag: YLRJ8LUP

**Comment by WhizGaming360** [comment]
Just updated the following links and the Discord server invite link.

**Comment by smlbiobot** [comment]
please keep formatting in the future. it’s impossible to edit with all the space removed. We don’t just need the info — we need the format

```yml
name: Mage Knights
key: mageknights
color: violet
emblem: A_Char_Knight_01
info:
  logo: /static/img/brands/logo/mage-knights.png
  description: >
    The **Mage Knights** are a family of clans, which is primarily war-focused
    and a community based on Clash Royale and Brawl Stars, playing both competitively
    and casually.
    We value the entire card collection, not just your ladder deck,
    but our family accepts players of all skill and card levels.
    We also value practice and constructive criticism; there is always room for improvement.
    _Mage Knights’ main clan is currently top 50 in U.S. clan war rankings_.

  social:
    - website: https://www.secondlightband.com/
    - facebook: https://www.facebook.com/SecondLightBand/
    - instagram: https://www.instagram.com/secondlightband/
    - discord: https://dsc.gg/mageknights
    - reddit: https://www.reddit.com/user/Mage_Knights/
    - youtube: https://www.youtube.com/channel/UC1R-b1AET3-eLGQNed6TYzA
clans:
  - name: Mage Knights
    tag: 2V28Y88Q
  - name: Mage Knights 2
    tag: YR00L2LY
  - name: Mage Knights 3
    tag: YLRJ8LUP

```
