### ISSUE TITLE
OTA Clan Family

### ISSUE THREAD

**Issue by nineroro** [RoyaleAPI/family-config#704]
name: OTA family
key: ota
color: purple
emblem: Moon_02
info:
  logo: https://cdn.royaleapi.com/static/img/badge/legendary-3/Moon_02.png?t=beb6fc0bc
  description: >
Turkish war clans. We are looking for skilled war inclined warriors. Please apply in our discord by typing your account tag and we will respond as soon as possible!
  social:
    - discord: https://discord.gg/yYc43wxmXC
clans:
  - name: OSMANLI TÜRK AK
    tag: PYL900GJ
  - name: TR TURKIYE
    tag: PQGYPV8Y
  - name: ***Ready2Die***
    tag: 8J2RQRYC
  - name: PERU ROYALE
    tag: PC2PYL2R

**Comment by smlbiobot** [comment]
```yml
name: OTA family
key: ota
color: purple
emblem: Moon_02
info:
  logo: /static/img/badge/legendary-3/Moon_02.png
  description: >
    Turkish war clans. We are looking for skilled war inclined warriors. Please apply in our discord by typing your account tag and we will respond as soon as possible!
  social:
    - discord: https://discord.gg/yYc43wxmXC
clans:
  - name: OSMANLI TÜRK AK
    tag: PYL900GJ
  - name: TR TURKIYE
    tag: PQGYPV8Y
  - name: "***Ready2Die***"
    tag: 8J2RQRYC
  - name: PERU ROYALE
    tag: PC2PYL2R
```
