### ISSUE TITLE
Dear Royalapi team,

### ISSUE THREAD

**Issue by AkaNovaEsports** [RoyaleAPI/family-config#705]
I wright you here for update our family groupe. Here is the actual statement: https://royaleapi.com/clan/family/novauk/clans?lang=en
May you add #GGRGYJJ2 and #LVJGL0PR in our family please.
Thank you for your help
Best regards
Nova Esports AE/UK Owner

**Comment by smlbiobot** [comment]
You need to update your config. We have removed a ton of your clans in your config because they all went to 0.

**Comment by smlbiobot** [comment]
```yml
name: Nova UK
key: novauk
color: purple
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/nova-uk.png
  description: >
    Competitive excellence through community-driven values.

    Nova is a mobile-focused eSports organization committed to empowering individuals through 
    a supportive team environment.

    We look for talent that has the character 
    to back it up. That talent is cultivated and supported through team-based growth 
    strategies and passionate staff that care about player outcomes. Community is 
    the foundation of those outcomes and is the core of player dedication.
  social:
    - twitter: https://twitter.com/NovaEsportsUKB
    - discord: https://discord.gg/N66ExB4Ugh
clans:
  - name: Nova UK 2
    tag: RY89JRY

```

**Comment by AkaNovaEsports** [comment]
> You need to update your config. We have removed a ton of your clans in your config because they all went to 0.

Yup i ve told you last time my managers were doing bad stuff, they has nuked 3of my clans. For be fair with my players i have create 2new ones.

**Comment by AkaNovaEsports** [comment]
name: Nova Esports AE/UK
key: novauk
color: purple
emblem: Star_Shine_03
info:
  logo:[image](https://user-images.githubusercontent.com/105395583/174192710-e94252a3-da67-4d48-9602-8e63235a5fb9.png)
  description: >
    **Competitive excellence through community-driven values.**

    Nova Esports All Empire is a mobile-focused eSports organization committed to empowering individuals through 
    a supportive team environment.

    We look for talent that has the character 
    to back it up. That talent is cultivated and supported through team-based growth 
    strategies and passionate staff that care about player outcomes. Community is 
    the foundation of those outcomes and is the core of player dedication.
  social:
    - twitter: https://twitter.com/NovaEsportsUKB
    - discord: https://discord.gg/N66ExB4Ugh
clans:
  - name: Nova UK 2
    tag: RY89JRY
  - name: Nova I AE
    tag: GGRGYJJ2
  - name: Nova I AE 2
    tag: LVJGL0PR

**Comment by AkaNovaEsports** [comment]
> ```yml
> 
> name: Nova Esports AE/UK
> 
> key: novauk
> 
> color: purple
> 
> emblem: Star_Shine_03
> 
> info:
> 
>   logo: ![image](https://user-images.githubusercontent.com/105395583/174287314-18530392-947c-4192-bb91-ae1912a49bca.png)
> 
>   description: >
> 
>     **Competitive excellence through community-driven values.**
> 
> 
> 
>     Nova Esports AE is a mobile-focused eSports organization committed to empowering individuals through 
> 
>     a supportive team environment.
> 
> 
> 
>     We look for talent that has the character 
> 
>     to back it up. That talent is cultivated and supported through team-based growth 
> 
>     strategies and passionate staff that care about player outcomes. Community is 
> 
>     the foundation of those outcomes and is the core of player dedication.
> 
>   social:
> 
>     - twitter: https://twitter.com/NovaEsportsUKB
> 
>     - discord: https://discord.gg/kJQABQDBSB
> 
> clans:
> 
>   - name: Nova UK 2
> 
>     tag: RY89JRY
> 
>   - name: Nova I AE
>   
>     tag: GGRGYJJ2
>
>   - name: Nova I AE 2
>   
>     tag: LVJGL0PR
>
> ```

**Comment by smlbiobot** [comment]
```yml
name: Nova UK
key: novauk
color: purple
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/nova-uk.png
  description: >
    Competitive excellence through community-driven values.

    Nova is a mobile-focused eSports organization committed to empowering individuals through 
    a supportive team environment.

    We look for talent that has the character 
    to back it up. That talent is cultivated and supported through team-based growth 
    strategies and passionate staff that care about player outcomes. Community is 
    the foundation of those outcomes and is the core of player dedication.
  social:
    - twitter: https://twitter.com/NovaEsportsUKB
    - discord: https://discord.gg/N66ExB4Ugh
clans:
  - name: Nova UK 2
    tag: RY89JRY
  - name: Nova I AE
    tag: GGRGYJJ2
  - name: Nova I AE 2
    tag: LVJGL0PR
```
