### ISSUE TITLE
Please update our family config NICECLAN https://royaleapi.com/clan/family/NC/clans

### ISSUE THREAD

**Issue by Data-1979** [RoyaleAPI/family-config#706]
```yaml
name: #NiceClan Familie
key: #NiceClan Familie
color: red
emblem: https://1drv.ms/u/s!AvfvAFY4YF1Jnk5iugzdoeO-FVzz?e=TFqEW3
info:
  logo: Sword_04
  description: >
**NICECLAN FAMILIE**


Einst, im Februar anno 2016, kurz nach Entstehung der CR Welt, zog ein stolzer Jüngling aus, um dieser Welt Frieden und Gerechtigkeit zu bringen. Bald musste er einsehen, dass er das alleine nicht vollbringen konnte. So scharte er aufrechte und tapfere Recken um sich und gemeinsam und treu kämpften sie gegen dunkle Mächte und das Böse. Um allen zu zeigen, wofür sie standen und kämpften, nannten sie sich **#NiceClan**!

CW Clan - Treue, Respekt, Loyalität

100% CW Teilnahmepflicht

Liga - Legendary 2

Leader - Guru (in Vertretung - Saphira )




Im Laufe der Zeit hatten sich Ruhm und Erfolg des NiceClan in der CR Welt herumgesprochen und immer mehr tapfere Recken wollten den Clan in seinem Kampf für das Gute unterstützen. Doch da die Größe der Tafel des legendären Trupps beschränkt ist, mussten viele tapfere Krieger abgewiesen werden, was wiederum zu Hadern und Unmut bei unseren Helden führte, solch wacker Recken wegschicken zu müssen. Und so kam es zur Gründung des **#Niceclan 2** !

CW Clan im Aufbau - Treue, Respekt, Loyalität

Liga - Bronze 2

Leader - Lore


**Besucht uns auf Discord!** 
  social:
    - discord: https://discord.gg/gMhqFewaav
    - email: mailto: doktor.soong@gmail.com
clans:
  - name: #NiceClan
    tag: YUU8VR
  - name: #NiceClan 2
    tag: Q2CG2RCJ
  - name: #NC Chilloutzon
    tag: LC99G8Y8

```
