### ISSUE TITLE
LaTronco Update

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#707]
Thank you for your service!

```yaml

name: LaTroncoFamiglia
key: latronco
color: green
emblem: Bamboo_03
sort: trophy
info:
  logo: /static/img/brands/logo/latronco-2.png
  description: >
    LaTroncoFamiglia, un insieme di clan in comunicazione tra loro per divertirsi in un ambiente tranquillo.
    Abbiamo delle regole generali per il quieto vivere valide in ogni clan, siate persone civili, nessun comportamento infantile, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.
    I clan incentrati sulla guerra sono: La Nuova Tronco; La Troncopoli; La SuperTronco e La Troncobase. Per far parte di uno di questi clan è necessario utilizzare tutti i deck ogni giorno di guerra da giovedì a domenica.
    Chi invece non è interessato alla guerra o comunque non garantisce i 4 attacchi giornalieri, può andare nel clan La Troncoradice, dove invece pensiamo ai trofei.
    Comunichiamo atttaverso Telegram, in basso ci sono i link per entrare.

  social:
    - telegram: https://t.me/LaTroncoFamiglia
    - telegram: https://t.me/LaNuovaTronco

clans:
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoradice
    tag: YV2UJ0GV

```
