### ISSUE TITLE
Westwall Family Update

### ISSUE THREAD

**Issue by WWEChishiya** [RoyaleAPI/family-config#709]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Westwall Eifel Family
key: Westwall
color: black
emblem: Skull_05
info:
  logo: 
  description: >
  Die Westwall Eifel Familie hat sich mit ganzem Herzen dem Clankrieg verschrieben.
  Egal ob Anfänger oder bereits CW-erfahrener Spieler, für jeden ist der passende Clan dabei.
 **Westwall 2:** Main Clan - 4/4 Pflicht - mind. 2.600 Fame - KT 13/14
 **Westwall 4:** Feeder für Westwall 2 - 4/4 Pflicht - mind. 2.000 Fame - KT 12
 **Westwall 5:** Feeder für Westwall 4 - mind. 1.000 Fame - KT 10
 **Westwall Agency:** Feeder für Westwall 5 - mind. 400 Fame - KT 6


  social:
    - discord: https://discord.com/invite/RJ6ryaEPfH
clans:
  - name: WestwallEifel 2
    tag: 80CRJJ98
  - name: WestwallEifel 4
    tag: YG80VPLQ
  - name: WestwallEifel 5
    tag: LVG9YP0R
  - name: Westwall Agency
    tag: LVUQP2PQ
```
