### ISSUE TITLE
*Russia* Clan Family

### ISSUE THREAD

**Issue by klpavel** [RoyaleAPI/family-config#710]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: *Russia* Clan Family
key: *Russia*
color: red
emblem: flag_h_01.png
info: 
  logo:
  description: Семейство Кланов * Russia * готово принять в свои ряды активных участников клановых войн для успешного похода в топ РФ 
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - Telegram: https://t.me/+J2baw_PVnx4yNWE6
clans:
  - name: *Russia*
    tag: #2YGVRUY
  - name: Russian Wolf
    tag: #YVYYL8VY
  - name: *Russia* 2
    tag: #LL0829G0
```
