### ISSUE TITLE
2 Inch Punisher  Family RoyaleAPI

### ISSUE THREAD

**Issue by YouFuleGaming** [RoyaleAPI/family-config#714]
```yaml
name:  2 Inch Punisher  Family
key: 2InchPunisher
color: orange
emblem: bamboo_04
info:
  description: >
    ( CommunityStrong ) First, Most Importantly... Have Fun :) 
2 Inch Punisher 's community is at an uprising. 
Full of talkative, active, talented, and diverse people.
Everyone is welcome from Casual to Competitive. 
We are English/United States based. 
Looking for strong players as we are constantly growing. 
We give the Full 2 Inches ! 


  social:
    - discord: http://discord.gg/XesXnSPnEf 
clans:
  - name: 2 Inch Punisher
    tag: YCR9LPYU
  - name: 2 Inch Punisher 
    tag: GYC288PG
```
