### ISSUE TITLE
New family ✨Home of Clash✨

### ISSUE THREAD

**Issue by godofclash** [RoyaleAPI/family-config#716]
```yaml
name: ✨Home of Clash✨
key: HOC
color: Grey
emblem: traditional_star-05
info:
  logo: https://ibb.co/NWLXxx5
  description: >
**Welcome to ✨Home of Clash✨**

We are a ladder focused clan that quickly became the **best clan in Germany**. In our main clan we recently startet to give out **rewards** too to our best players to reward them for their good performance.
We are a clan family where **chemistry** and **loyalty** plays an important role.

Also we have an **eSports team**, which lately has become very successful.
We participate in the **biggest team tournaments** and compete with the best teams in the world.
Recently we started offering contracts to our players to make the team as professional as possible.

We are a clan with **high goals** and we want to be very successful in our hobby.
  social:
    - twitter: https://twitter.com/Home_of_Clash
    - discord: https://discord.gg/HvXSjMHyf2
    - instagram: https://www.instagram.com/home_of_clash/
clans:
  - name: ✨Home of Clash✨
    tag: Q0UYG8R9
  - name: ✨Home of Grind✨
    tag: QYVP2JQP
```
