### ISSUE TITLE
World Lands Family

### ISSUE THREAD

**Issue by silvestreber** [RoyaleAPI/family-config#718]
```yaml
name: World Lands Family
key: worldlands
color: black
emblem: Skull_01
info:
  description: >
    Bienvenidos a la familia de clanes World Lands.
    Tenemos 4 clanes para que puedas elegir el que más se ajuste a tus necesidades, dos de ellos están enfocados a guerras, uno está enfocado a ladder y el último es para relax y desconectar. 
    ¡Pásate por discord y pide más información!
    
    
  social:
    - discord: https://discord.gg/scwBYYP
    - twitter: https://twitter.com/LandsWorld
clans:
  - name: "Clu Clu" Land
    tag: 9C0RYJ2U
  - name: "Zip Zap" Land
    tag: PCPCRPJY
  - name: "Blu Blu" Land
    tag: Q0LLG2QC
  - name: "Go Go" Island
    tag: L0YQYQY9 
```
