### ISSUE TITLE
Siberia Family

### ISSUE THREAD

**Issue by MrKostya01** [RoyaleAPI/family-config#719]
```yaml
name: Содружество "Сибирия"
key: siberia
color: blue
emblem: Star_Shine_02
info:
  description: >
    Содружество кланов Сибирия объединяет в себя основной клан и его подорганизации - академию Сибирия-2:Тайга, молодежку Сибирия-3:Тьма и юниорку Сибирия-4:Икар (Сибирия-99:Зима для игроков в "спячке").
    Наш клан входит в топ 20 кланов РФ и участвует в межклановых РФ турнирах, а также соревнованиях по КВ.
    Мы стараемся поддерживать дисциплину наших игроков, помогать друг-другу донатом и советами, всегда работать на результат нашей команды.
clans:
  - name: Сибирия
    tag: P222QCQU
  - name: Сибирия-2:Тайга
    tag: PRUGRQ0C
  - name: Сибирия-3:Тьма
    tag: YJVG0RYU
  - name: Сибирия-4:Икар
    tag: YCGP09Y0
  - name: Сибирия-99:Зима
    tag: Q98Q088U
```
