### ISSUE TITLE
Hammer Time Family Update - Thank you!

### ISSUE THREAD

**Issue by NUFC7** [RoyaleAPI/family-config#721]
```yaml
name: Hammer Time Family
key: hammertime
color: blue
emblem: A_Char_Hammer_01
info: 
  logo:
  description: >  We are an active clan focusing primarily on clan wars.  Active clan members only.  Top medal earners each week are promoted while the lowest are moved down to our feeder clans promoting a healthy/competitive/fun environment!

clans:
  - name: Hammer Time
    tag: YPQ20RRV
  - name: Mallet Time
    tag: QGP08L89
  - name: Gavel Time
    tag: QR08VJPJ
```
