### ISSUE TITLE
Reborn family clans

### ISSUE THREAD

**Issue by 177cj** [RoyaleAPI/family-config#722]
```yaml
name: Reborn clan family
key: reborn
color: blue
emblem: Twin_Peaks_01
  description: >
    Est. 01.06.22. Risen from the dead. Active war clans. 


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/RZP3JxVU
    
clans:
  - name: Reborn Creed
    tag: LVCVV8R9
  - name: Reborn Legacy
    tag: LV98Y0QQ
  - name: Reborn Phaze
    tag: LV8LV0YY
  - name: Reborn Fusion
    tag: QYPQ92R2
```
