### ISSUE TITLE
けんとまながいかーん❣️7

### ISSUE THREAD

**Issue by KEN06105** [RoyaleAPI/family-config#723]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:けんとまながいかーん❣️7
key:けんとまながいかーん❣️7
color:red
emblem: Heart_01.png
info:
  logo: https://github.com/RoyaleAPI/cr-api-assets/blob/master/badges/Heart_01.png?raw=true
  description: >
    このクランはクラン対戦に力を入れているクランです❣️
メンバー同士とても仲が良く、面白い人が多いです❣️
入っていただけたら改めて詳しくルールを説明します❣️
discordも、LINEのオープンチャットもやっています❣️
気なった方は是非エントリーしてくださいねー❣️

    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/VTAFB9y5
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: けんとまながいかーん❣️7
    tag: #G2YQYRUO
  - name:beginners clan
    tag:#C9RORYQ
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
```yml
name: けんとまながいかーん❣️7
key: kento-mana
color: red
emblem: Heart_01
info:
  logo: /static/img/badges/Heart_01.png
  description: >
    このクランはクラン対戦に力を入れているクランです❣️
    メンバー同士とても仲が良く、面白い人が多いです❣️
    入っていただけたら改めて詳しくルールを説明します❣️
    discordも、LINEのオープンチャットもやっています❣️
    気なった方は是非エントリーしてくださいねー❣️

    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/VTAFB9y5

clans:
  - name: けんとまながいかーん❣️7
    tag: G2YQYRUO
  - name: beginners clan
    tag: C9RORYQ

```
