### ISSUE TITLE
INDIA

### ISSUE THREAD

**Issue by legend84yt** [RoyaleAPI/family-config#725]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: INDIA
key: INDIA
color: red
emblem: Star_Shine_03.png
info:
  logo:
  description: >
    our clans main goal is to represent INDIA globally 
    we have over 70 members and two cans
    our clan provide training to the new members and help them to improve
    our clan since creation had been active so on....
    *join our clan to feel proud of yourself*


    Add new line with 2 line breaks as above.
  social:
    - discord: https://discord.gg/s8K3m2tzhu
    - youtube: https://www.youtube.com/channel/UCxMPOPBQwF1AyAKZXDFNMeA/featured
    - email: mailto: sarodeyash84@gmail,com
clans:
  - name: INDIA
    tag: LQ8VCCGL
  - name: INDIAN ARMY
    tag: LUVV9J20
 ```
