### ISSUE TITLE
Belarus4

### ISSUE THREAD

**Issue by SlevinKelevr** [RoyaleAPI/family-config#726]
```yaml
name: Семья кланов Беларусь4
key: belarus4
color: green
emblem: A_Char_King_02
info:
  logo: https://media.discordapp.net/attachments/691339812510367784/1001901063412138024/image-edit-20220727200936.jpg
  description: >Мы рады приветствовать тебя в семье кланов **Беларусь 4**. Вместе мы сделаем наши кланы лучше и сможем увеличить наши трофеи.    
  social:
    - discord: https://discord.gg/yy4SArjq
    - telegram: https://t.me/OLES_BELARUS_CLASH
clans:
  - name: Беларусь4
    tag: 9U0JVQYQ
  - name: Беларусь4 Акк
    tag: Y2U29C9V
  - name: Беларусь4 А2к
    tag: Q8J2R8YU
```
