### ISSUE TITLE
Famille QC-ÉLITE

### ISSUE THREAD

**Issue by KassandraQc-Elite** [RoyaleAPI/family-config#730]
```yaml
name: Famille QC-ÉLITE
key: qc-élite
color: blue
emblem: Crown_04
info:
  logo: https://photos.app.goo.gl/oJg28Wb2Mwd8BAkL9
  description: >
    QC-ÉLITE est une famille de 6 clans accueillante et chaleureuse prônant le respect et l'entraide.
Principalement axé guerre de clan, dans la famille il y a de la place pour tout les types de joueurs.
Nos clans sont constitués de membres des 4 coins de la planète, parlant majoritairement français mais également anglais.
Au sein de QC-ÉLITE ''Le jeu c'est du sérieux'' mais le plaisir y est garanti.
Rejoignez-nous; discord / messenger 

QC-ÉLITE is a welcoming and warm family of 6 clans who preach respect and mutual aid.
Mainly focused on clan war, in the family there is room for all types of players.
Our clans are made up of members from the 4 corner of the planet, speaking mainly french but also english.
Within Qc-élite ''the game is serious'' but fun is guaranteed.
Join us; discord / messenger 


  social:
    - discord: http://discord.gg/8hAdKUXdx5
    - facebook: https://www.facebook.com/profile.php?id=100081518052273
clans:
  - name: QC-ÉLITE
    tag: J9YG0
  - name: Qc-Élite2
    tag: C99CUQ0
  - name: Qc-Élite3
    tag: QP2RCLUJ
- name: Qc-Élite4
    tag: Q8UVL2UV
  - name: Qc-Élite5
    tag: GQUL8LRJ
  - name: Qc-Élite6
    tag: LUJQJ9LV
```
