### ISSUE TITLE
WarxUnion & Rugbyman Clan Family

### ISSUE THREAD

**Issue by page118** [RoyaleAPI/family-config#733]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: WarxUnion
key: warxunion
color: red
emblem: Sword_01
info:
  logo:
  description: >
We are WarxUnion. Our clans are consistently well above the 4k barrier and strive for the leaderboards, with our main clan being top in the world. We are looking for strong, lvl 14 players to do war and support us to be the best we can be.

  social:
    - instagram: https://instagram.com/warxunion2_cr/
clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: #CRF
    tag: YPYGYYYR
  - name: Hell Fish VIP
     tag: 9Q0JP29
```
