### ISSUE TITLE
Dark Cloudy

### ISSUE THREAD

**Issue by Revampikk** [RoyaleAPI/family-config#734]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 0.6 Dark Cloudy 
key: darkcloudy
color: blue
emblem: Bolt_03
info:
  logo: https://i.imgur.com/Rd13j0E.jpg
  description: >
**Witamy w Dark Cloudy**. Jesteśmy klanem wojennym. Musisz brać udział we wszystkich wojnach i używać **WSZYSTKICH** swoich ataków od czwartku do niedzieli.
Oferujemy największy w Polsce serwer discord dla polskiej społeczności CR (każdy może dołączyć nawet spoza klanu) oraz nasz klanowy. Zapewniamy również turnieje, aktywny czat z miłą atmosferą i wiele więcej!

  social:
    - discord: https://discord.gg/NAVHPZvfsP
    - discord: https://discord.gg/X4tJ55H82v
clans:
  - name: Dark Cloudy :cloud:
    tag: QYP2PV28
  - name: Dark Cloudy II
    tag: LV2G8LR0
  - name: Dark Cloudy III
    tag: LG2002Q2
  - name: Dark Cloudy IV
    tag: GYPCCY02
  - name: Dark Cloudy V
    tag: Q8RYCV0V
  - name: Dark Cloudy VI
    tag: LCJLQV8R
```
