### ISSUE TITLE
Add Mostri Family

### ISSUE THREAD

**Issue by xspacejump** [RoyaleAPI/family-config#738]
```yaml
name: I Mostri family
key: mostri
color: black
emblem: Skull_06
info:
  logo:
![photo_2021-10-24_21-33-20](https://user-images.githubusercontent.com/111538717/185706239-9a5350c5-c5be-44f2-9969-8d508a15dba3.jpg)

  description: >
La **Mostri family** nasce come un gruppo di individui che si unisce allo scopo di **divertirsi** e dare il meglio di se. 
Qui troverete clan competitivi war e ladder, oltre ad un gruppo di persone pronte a passare del bel tempo insieme.


Contattateci su _telegram_ per essere aggiunti al gruppo della family.
  social:
    - telegram: https://telegram.me/Ange3k
    - telegram: https://telegram.me/Alemostri
    - discord: http://discord.gg/qXcFAmkcTr
    - instagram: https://instagram.com/mostriclashroyale
clans:
  - name: I mostri
    tag: QQY08QV
  - name: I Mostri Family
    tag: QLP9RQJJ
  - name: Allstar Mostri
    tag: GPUVVVJC
  - name: 28040⛓
    tag: QQV9YUC9
```

**Comment by smlbiobot** [comment]
```yml
name: I Mostri family
key: mostri
color: black
emblem: Skull_06
info:
  logo: /static/img/brands/logo/mostri.png
  description: >
    La **Mostri family** nasce come un gruppo di individui che si unisce allo scopo di **divertirsi** e dare il meglio di se.
    Qui troverete clan competitivi war e ladder, oltre ad un gruppo di persone pronte a passare del bel tempo insieme.
    
    
    Contattateci su _telegram_ per essere aggiunti al gruppo della family.
  social:
    - telegram: https://telegram.me/Ange3k
    - telegram: https://telegram.me/Alemostri
    - discord: http://discord.gg/qXcFAmkcTr
    - instagram: https://instagram.com/mostriclashroyale
clans:
  - name: I mostri
    tag: QQY08QV
  - name: I Mostri Family
    tag: QLP9RQJJ
  - name: Allstar Mostri
    tag: GPUVVVJC
  - name: 28040⛓
    tag: QQV9YUC9
```
