### ISSUE TITLE
Add "Ad Family" as a family

### ISSUE THREAD

**Issue by MoneyCr** [RoyaleAPI/family-config#739]
```yaml
name: Ad Family
key: adfamily
color: blue
emblem: Traditional_Star_05
info:
  logo: https://cdn.royaleapi.com/static/img/team/logo/ad-esports.png?t=bf998894c
  description: >
    La **Ad Family** est une famille de clans créée en 2016 par Ashtax et Elishouille, qui ont réussi à faire grimper les clans dans le top français dès le début du jeu. Aujourd’hui, la famille est toujours là et est composée de 6 clans : Ad Vitam, Astra, Gloriam, Lucem, Honoris et Eternam.
social:
    - twitter: https://twitter.com/Ad_Esport
clans:
  - name: Ad Vitam
    tag: 82UV9LV
  - name: Ad Astra
    tag: LP2LCGVG
- name: Ad Gloriam
    tag: 28C82PU
  - name: Ad Lucem
    tag: LPQJJ8C9
  - name: Ad Honoris
    tag: LG9CPJLY
  - name: Ad Eternam
    tag: LL90QQC0
```

**Comment by smlbiobot** [comment]
```yml
name: Ad Family
key: adfamily
color: blue
emblem: Traditional_Star_05
info:
  logo: /static/img/team/logo/ad-esports.png
  description: >
    La **Ad Family** est une famille de clans créée en 2016 par Ashtax et Elishouille, qui ont réussi à faire grimper les clans dans le top français dès le début du jeu. Aujourd’hui, la famille est toujours là et est composée de 6 clans : Ad Vitam, Astra, Gloriam, Lucem, Honoris et Eternam.
  social:
    - twitter: https://twitter.com/Ad_Esport
clans:
  - name: Ad Vitam
    tag: 82UV9LV
  - name: Ad Astra
    tag: LP2LCGVG
  - name: Ad Gloriam
    tag: 28C82PU
  - name: Ad Lucem
    tag: LPQJJ8C9
  - name: Ad Honoris
    tag: LG9CPJLY
  - name: Ad Eternam
    tag: LL90QQC0
```
