### ISSUE TITLE
HC eSports | KatzClans™️ (delete 2 clans)

### ISSUE THREAD

**Issue by katzclans** [RoyaleAPI/family-config#740]
```yaml
name: HC eSports | KatzClans™️
  - name: Hard Counter™️
    tag: LGU2JP9C
  - name: Hard Counter™️2
    tag: QYPYQ800
```
