### ISSUE TITLE
[UPDATE] 300

### ISSUE THREAD

**Issue by windias** [RoyaleAPI/family-config#741]
name: 300
key: 300
color: black
emblem: flag_j_03
info:
  description: >
International clan family based in China. Multilingual friendly. Team spirit and positive attitudes valued as well as competitive skills.

clans:
  - name: 300
    tag: 9GP88
  - name: 3000 Skies
    tag: PGPJV9QU
  - name: 3000 Kingdoms
    tag: G9JGYRUY
  - name: 3000 Oceans
    tag: 9R0RQPCQ
  - name: 3000 Worlds
    tag: 22Y2RU9R
  - name: 3000 Rivers
    tag: 9Y9QLUV9
  - name: 3000 Thrones
    tag: QG0Y0GPQ

**Comment by smlbiobot** [comment]
```yml
name: '300'
key: '300'
color: black
emblem: flag_j_03
info:
  description: >
    International clan family based in China. Multilingual friendly. Team spirit and
    positive attitudes valued as well as competitive skills.

clans:
  - name: 300
    tag: 9GP88
  - name: 3000 Skies
    tag: PGPJV9QU
  - name: 3000 Kingdoms
    tag: G9JGYRUY
  - name: 3000 Oceans
    tag: 9R0RQPCQ
  - name: 3000 Worlds
    tag: 22Y2RU9R
  - name: 3000 Rivers
    tag: 9Y9QLUV9
  - name: 3000 Thrones
    tag: QG0Y0GPQ
```
