### ISSUE TITLE
Update to : Némésis Quebec Clan Family

### ISSUE THREAD

**Issue by RagnarLothbrok77** [RoyaleAPI/family-config#743]
name: Némésis Quebec Clan Family
key: nemesisquebec
color: black
emblem: flag_j_03
info:
  logo: /static/img/badge/bronze-1/flag_j_03.png
  description: >
    
    Bienvenue dans la famille Némésis Quebec!
    Nous avons 6 clans qui ont tous comme objectif la domination totale en guerre.
    En plus d'offrir des récompenses en argent pour nos 2 premiers clans, nous organisons plusieurs ligues et tournois internes.
    Si vous désirez faire partie de notre grande famille, je vous invite à rejoindre notre discord.
    
    Welcome in the Némésis Quebec Clan Family!
    We have 6 clans with all the same objective, which is war total domination.
    In addition to offering cash rewards for our first 2 clans, we run several internal leagues and tournaments. 
    If you want to be part of our big family, I invite you to join our discord.

social:
    - discord: http://discord.gg/RPujnqbSqA

clans:
- name: Némésis Quebec
  tag: YU0JV9QV
- name: Némésis Qc2
  tag: YQURV2CR
- name: Némésis Qc3
  tag: YLGV9LGL
- name: Némésis Qc4
  tag: LQLCVQVC
- name: Némésis Qc5
  tag: QPJUC2RJ
- name: Némésis Qc6
  tag: G20PYV8V

Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```
