### ISSUE TITLE
BD Heroes

### ISSUE THREAD

**Issue by tahxin** [RoyaleAPI/family-config#744]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: BD Heroes 
key: bd_heroes
color: green
emblem: Flag_I_01
info:
  description: >
    **Welcome to BD Heroes Family.Stay active and Enjoy**
  **One of the first clans of Clash Royale**
    **Competitive excellence through community-driven values.**
    We look for talent that has the character to back it up.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
    - email: mailto:[shahjalaltahsin@gmail.com](mailto:shahjalaltahsin@gmail.com)
    - discord: https://discord.gg/gCQbMxWdjb
clans:
  - name: BD Heroes
    tag: 8OQ2R8
  - name: BD Heroes II
    tag: UJYQCCO
  - name: BD Heroes IV
    tag: 0290YCPC
…
```
