### ISSUE TITLE
Clan family configuration

### ISSUE THREAD

**Issue by denis-oliveira** [RoyaleAPI/family-config#745]
I attached the logo as instructed on the royaleapi forum because I don't know how to create the URL of the logo. 

logo:
![Logo Fpreto](https://user-images.githubusercontent.com/29293640/188768537-14428912-ef08-4dc8-b7c1-5efb4f914981.jpg)

logo link: https://user-images.githubusercontent.com/29293640/188768537-14428912-ef08-4dc8-b7c1-5efb4f914981.jpg

Configuration below:

```yaml
name: 《ArmageddoN》
key: armageddon
color: red
emblem: Fugi_04
info:
  description: >
    The 《ArmageddoN》 clan family is relatively new but we have got already very far. 
    We have never lost clan wars with the main clan since it was created (20-May-2021) and we aim to get to legendary league undefeated. 
    We have got to the Top 20 push clans in Brazil. 
    We have 3 clans to welcome players from all levels from low arenas up to more skilled players, from casual to competitive, young to old and so on. 
    Come join one of our 3 clans and come have fan. If you decide to join us, contact us on our Instagram page.
    Since creation, we as a family and as individual players have grown immensely and continue.
    We believe that it is the reason why we have come so far.
    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join the Family. Become part of 《ArmageddoN》 family. Because this is what we are, a family.**


   social:
    - discord: https://discord.gg/nCBSysWBSr
    - instagram: https://www.instagram.com/amd_cr_clan/
    - youtube: https://www.youtube.com/channel/UCYNCuQLMckw4T1WbDtP1wYw
    - email: mailto:armageddon.cr.clan@gmail.com
clans:
  - name: 《ArmageddoN》
    tag: QQ00QQRL
  - name: 《ArmageddoN》 II
    tag: L0C90P9R
  - name: 《ArmageddoN》 III
    tag: GYLLC0Q0
  - name: 《ArmageddoN》Int
    tag: #Q0QR8VQC
```
