### ISSUE TITLE
Aftermath Militia

### ISSUE THREAD

**Issue by eggb0y** [RoyaleAPI/family-config#746]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Aftermath Militia
key: aftermath
color: purple
emblem: A_Char_Pekka_02
info: 
  description: >
    Aftermath, our flagship clan, was formed right at the start of the beta release and has always attracted high calibre players
    Since CW1, war has always been our main focus but it was when CW2 was introduced that we decided we should push on from being a talented but semi-casual clan to become the most dominant UK based war clan in the game.
    We are the proud holders of the UK record war scores and highest points and look to remain in the upper echelons of the global war rankings.
    Aftershock is home to many former Aftermath members and are a good war clan in their own right. Progression is possible and members regularly move between the clans. This is a place to hone your skills before making the step up to Aftermath.
    Afterlife is mainly used by current Aftermath members to take a break or work on their war decks without the pressure of playing against the best in the world but is also a place for less experienced players to get help with deck building and gameplay advice.
    Afterglow is open to anyone that is a keen war player, regardless of their levels,
    We have a real passion for war and whilst around 70% of our members are UK based we welcome players from all over the world
  social:
    - discord: https://discord.gg/gWRDcvcMRG
clans:
  - name: Aftermath
    tag: 8CYR2V
  - name: Aftershock
    tag: YC8R0RJ0
  - name: Afterlife
    tag: L2RRRGVG
  - name: Afterglow
    tag: LUYLLQJR
```
