### ISSUE TITLE
Warriors Faction Clan Family

### ISSUE THREAD

**Issue by Reaper5607** [RoyaleAPI/family-config#748]
Fill in the configuration below:

name: Warriors Faction
key: warriorsfaction
color: red
emblem: Star_Shine_03
info:
  description: >
The **Warriors Faction** is a family of multiple elite war clans! Our clans have been dominating wars for many years and our players are passionate about war. Join our discord to be in the best clan family in the US!

  social:
    - twitter: https://twitter.com/cr_warfaction
    - discord: https://discord.gg/warriorsfaction
    - instagram: https://instagram.com/cr_warfaction
clans:
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: CRL eSports PRO
    tag: 9UV202Q2
  - name: Bay Warea Beta
    tag: 9JJCQURV
  - name: Elixir Elites
    tag: PP00JCRV
  - Crying Fire
    tag: 8Y2LVVQ9
  - Midwinter Fire
    tag: 29J9V9PU
  - Divine Wind
    tag: 2CJY2008
  - BEWO Pro
    tag: YY89R8RG
  - Hawaiian Beast
    tag: P2RPJQ9R
  - Elixir Thieves™
    tag: YG2LUQLC
  - Alpha Steel
    tag: 9PV9JL
  - Ready Reserves
    tag: L9RGU90V
  - No Clan
    tag: YC8CJV9G
  - monkey mafia 2
    tag: 2CYLGU8R
  - Thunder Harbor
    tag: YRGJ0QYV
  - Fiery Embers
    tag: QCC9C8UR
  - Crying Fire™
    tag: LQQJQULG
  - PRO ERA
    tag: LYUL0Y2V
  - gladiators
    tag: LQJQUQ2G
  - Crying Fire 2
    tag: GYUJYJJP
  - MK 4PLaY
    tag: QQLJJ8YP
  - Mini Knights
    tag: GG8UJC29
  - CRL Tournaments
    tag: LYYC0GJY
  - Elixir Empire
    tag: LUQY2JPY
```

**Comment by smlbiobot** [comment]
```yml
name: Warriors Faction
key: warriorsfaction
color: red
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/warriorsfaction.png
  description: >
    The **Warriors Faction** is a family of multiple elite war clans! Our clans have been dominating wars for many years and our players are passionate about war. Join our discord to be in the best clan family in the US!


  social:
    - twitter: https://twitter.com/cr_warfaction
    - discord: https://discord.gg/warriorsfaction
    - instagram: https://instagram.com/cr_warfaction
clans:
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: CRL eSports PRO
    tag: 9UV202Q2
  - name: Bay Warea Beta
    tag: 9JJCQURV
  - name: Elixir Elites
    tag: PP00JCRV
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Midwinter Fire
    tag: 29J9V9PU
  - name: Divine Wind
    tag: 2CJY2008
  - name: BEWO Pro
    tag: YY89R8RG
  - name: Hawaiian Beast
    tag: P2RPJQ9R
  - name: Elixir Thieves™
    tag: YG2LUQLC
  - name: Alpha Steel
    tag: 9PV9JL
  - name: Ready Reserves
    tag: L9RGU90V
  - name: No Clan
    tag: YC8CJV9G
  - name: monkey mafia 2
    tag: 2CYLGU8R
  - name: Thunder Harbor
    tag: YRGJ0QYV
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Crying Fire™
    tag: LQQJQULG
  - name: PRO ERA
    tag: LYUL0Y2V
  - name: gladiators
    tag: LQJQUQ2G
  - name: Crying Fire 2
    tag: GYUJYJJP
  - name: MK 4PLaY
    tag: QQLJJ8YP
  - name: Mini Knights
    tag: GG8UJC29
  - name: CRL Tournaments
    tag: LYYC0GJY
  - name: Elixir Empire
    tag: LUQY2JPY

```

don’t miss stuff
