### ISSUE TITLE
101% Canadian - clan list update and fix typo

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#749]
```yaml
name: 101% Canadian Clan Family
key: canadian
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/canadian.png
  description: >
    101% Canadian is Canada's **premier Clan Wars Clan**. Us, along with our family
    of clans strive to provide a positive, competitive,
    fun and quality Clash Royale experience, while focusing on Clan Wars.
  social:
  - discord: discord.gg/pttBsyqYH7
  clans:
- name: 101% Canadian
  tag: 9UCRJG8V
- name: 99.9% Canadian
  tag: 2QVJPQJG
- name: CHAMPIONS 3.0
  tag: 28UVG00Y
- name: Upheaval
  tag: PLL2LJQ2
- name: '#Awesomesauce'
  tag: R2QLR8
- name: 102% Canadian
  tag: LGCYVUCJ
- name: 99.9%Stressfree
  tag: Y2L9QY08
```
