### ISSUE TITLE
AlphaGo Family

### ISSUE THREAD

**Issue by LuminousForMe** [RoyaleAPI/family-config#751]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: AlphaGo Family
key: AlphaGo
color: blue
emblem: Crown_03
info:
  logo: https://st.depositphotos.com/32634758/53029/v/450/depositphotos_530299196-stock-illustration-logo-monogram-triangle-hexagon-shape.jpg
  description: >
    Welcome to AlphaGo Family.
We are the best clans in Korea.

    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/egestone99?s=21&t=Pp5twR9pkh_3k_k-OJoTuA
    - youtube: https://youtube.com/channel/UCaECad3wyre_fRToi8EN52A
    - kakaotalk: https://open.kakao.com/o/ssrNvCAc
    - kakaotalk: https://open.kakao.com/o/syVMn70d
    - application: https://open.kakao.com/o/g4JMIzvc

clans:
  - name: AlphaGo
    tag: 2QG8QQR
  - name: BetaGo
    tag: LRC29YY0
  - name: ZetaGo 
    tag: Q8VC9CRJ
  - name: AlphaGo 쉼터
    tag: L8R90VCP
```
