### ISSUE TITLE
Rebels

### ISSUE THREAD

**Issue by Cutlie333** [RoyaleAPI/family-config#753]
name: Rebels 叛军 Family
key: Rebels 叛军
color: yellow
emblem: flag_j_03
info:
logo: https://user-images.githubusercontent.com/87021793/125456716-5c06d200-7567-46c5-8724-345735e58b32.jpeg)
description: >
Rebels were established on March 16 by a group of Singapore adults. Together with Nova SG, we have a total of 7 clans. We hosting monthly Pass Royale Tournaments, a Scrim Team and clans which regularly top in war and ladder. Join us today!
social:
- Discord: https://discord.gg/QYdQfUZ7
- Instagram: https://www.instagram.com/rebels.sg/
- Facebook: https://www.facebook.com/sgrebels/
- YouTube: https://www.youtube.com/channel/UCaqaMl-E33dOfVlww3pjxwQ
clans:

name: Rebels⚡叛军一营
tag: 9Q8Q0PUY
name: Nova l SG
tag: 2QRCQVPR
name: OP Ace
tag: #PJ9UPQP
name: Rebels⚡叛军二营
tag: 8UP9288U
name: Rebels⚡叛军三营
tag: 8UYJYQ8L
name: Rebels⚡叛军四营
tag: 9RG2C0GU
name: Rebels⚡Academy
tag: PJ9QL2RQ
name: Notva l SG
tag: #QYCJPYR2
name: Rebels⚡️叛軍五營
tag: #Q2YU9CCJ
name: scared or wut
tag: #GP02RGRV

**Comment by smlbiobot** [comment]
Don’t miss dashes. These are not just for data entry — these are CODE

```yml
name: Rebels 叛军 Family
key: rebels
color: yellow
emblem: flag_j_03
info:
  logo: /static/img/brands/logo/rebels.png
  description: Rebels were established on March 16 by a group of Singapore adults. Together with Nova SG, we have a total of 7 clans. We hosting monthly Pass Royale Tournaments, a Scrim Team and clans which regularly top in war and ladder. Join us today!
  social:
    - discord: https://discord.gg/QYdQfUZ7
    - instagram: https://www.instagram.com/rebels.sg/
    - facebook: https://www.facebook.com/sgrebels/
    - youtube: https://www.youtube.com/channel/UCaqaMl-E33dOfVlww3pjxwQ

clans:
  - name: Rebels⚡叛军一营
    tag: 9Q8Q0PUY
  - name: Nova l SG
    tag: 2QRCQVPR
  - name: OP Ace
    tag: PJ9UPQP
  - name: Rebels⚡叛军二营
    tag: 8UP9288U
  - name: Rebels⚡叛军三营
    tag: 8UYJYQ8L
  - name: Rebels⚡叛军四营
    tag: 9RG2C0GU
  - name: Rebels⚡Academy
    tag: PJ9QL2RQ
  - name: Notva l SG
    tag: QYCJPYR2
  - name: Rebels⚡️叛軍五營
    tag: Q2YU9CCJ
  - name: scared or wut
    tag: GP02RGRV

```
