### ISSUE TITLE
UPDATE EXISTING clan family configuration:《ArmageddoN》

### ISSUE THREAD

**Issue by denis-oliveira** [RoyaleAPI/family-config#755]
Please update clan page. 

Current page is the one in the link below:
https://royaleapi.com/clan/family/armageddon/clans

Updated configuration listed is below (changed name, logo and description):

```yaml
name: 01º《ArmageddoN》Family
key: armageddon
color: black
emblem: Fugi_04
info:
  logo: https://bit.ly/amd_logo
  description: >
    The **《ArmageddoN》** clan family is relatively new but we have got already very far. 
    We have **never lost clan wars with the main clan since it was created (20-May-2021)** and we aim to get to legendary league undefeated. 
    We have got to the **ladder local top 20 clans in Brazil**. 
    We have 4 clans to welcome players from all levels from low arenas up to more skilled players, from casual to competitive, young to old, Brazilian to internacional community and so on. 


    Come join one of our 3 clans and come have fan. If you decide to join us, contact us on our Instagram page.
    Since the creation we, as a family and as individual players, have grown immensely and continue to do so.
    We believe that it is the reason why we have come so far.


    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join us and become part of 《ArmageddoN》 family. Because this is what we are, a family.**

   social:
    - discord: https://discord.gg/nCBSysWBSr
    - instagram: https://www.instagram.com/amd_cr_clan/
    - youtube: https://www.youtube.com/channel/UCYNCuQLMckw4T1WbDtP1wYw
    - email: mailto:armageddon.cr.clan@gmail.com
    - 
clans:
  - name: 《ArmageddoN》
    tag: QQ00QQRL
  - name: 《ArmageddoN》 II
    tag: L0C90P9R
  - name: 《ArmageddoN》 III
    tag: GYLLC0Q0
  - name: 《ArmageddoN》Int
    tag: Q0QR8VQC
```
