### ISSUE TITLE
UPDATE EXISTING clan family configuration

### ISSUE THREAD

**Issue by denis-oliveira** [RoyaleAPI/family-config#757]
Current page is the one in the link below:
https://royaleapi.com/clan/family/armageddon/clans

Updated configuration settings is listed below (change name, descriptions, color and logo).

Note: There is a minor typo on the description.

On last request it was refused to change the name because of the numbers in front of the name but I noticed there are clans with this:
![image](https://user-images.githubusercontent.com/29293640/190949805-069c577d-3423-4e91-a490-9206a4c7f2b8.png)

```yaml
name: 01º《ArmageddoN》Family
key: armageddon
color: black
emblem: Fugi_04
info:
  logo: https://bit.ly/amd_logo
  description: >
    The **《ArmageddoN》** clan family is relatively new but we have got already very far. 
    We have **never lost clan wars with the main clan since it was created (20-May-2021)** and we aim to get to legendary league undefeated. 
    We have got to the **ladder local top 20 clans in Brazil**. 
    We have 4 clans to welcome players from all levels from low arenas up to more skilled players, from casual to competitive, young to old, Brazilian to internacional community and so on. 


    **Come join one of our clans and have fan. If you decide to join us, contact us on our Instagram page.**
    Since our foundation we, as a family and as individual players, have grown immensely and continue to do so.
    We believe that it is the reason why we have come so far.


    We all share a fellow passion for the game, are friendly, always donate,
    help each other out with the same goal: to always improve our skills and have a great time!
    **Join us and become part of 《ArmageddoN》 family. Because this is what we are, a family.**

   social:
    - discord: https://discord.gg/nCBSysWBSr
    - instagram: https://www.instagram.com/amd_cr_clan/
    - youtube: https://www.youtube.com/channel/UCYNCuQLMckw4T1WbDtP1wYw
    - email: mailto:armageddon.cr.clan@gmail.com
    - 
clans:
  - name: 《ArmageddoN》
    tag: QQ00QQRL
  - name: 《ArmageddoN》 II
    tag: L0C90P9R
  - name: 《ArmageddoN》 III
    tag: GYLLC0Q0
  - name: 《ArmageddoN》Int
    tag: Q0QR8VQC
```ower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```
