### ISSUE TITLE
[UPDATE] LaTronco

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#758]
Thanks for your service!
I changed logo, description and sort fields.

```yaml

name: LaTroncoFamiglia
key: latronco
color: green
emblem: Bamboo_03
info:
  logo: https://ibb.co/SKCB7MP
  description: >
    **LaTroncoFamiglia**, un insieme di clan in comunicazione tra loro per divertirsi in un ambiente tranquillo.

    Abbiamo delle regole generali per il quieto vivere valide in ogni clan, siate persone civili, nessun comportamento infantile, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.

    **War Clans:** La Nuova Tronco; La Troncopoli e La SuperTronco. Per far parte di uno di questi clan è necessario utilizzare tutti i deck ogni giorno di guerra da giovedì a domenica.

    **No War Clans:** La Troncoradice; La Troncobase.

    Comunichiamo le notizie più importanti sul canale Telegram, ma possiamo parlare tra di noi tramite il gruppo, qui sotto ci sono i link per entrare.

  social:
    - telegram: https://t.me/LaTroncoFamiglia
    - telegram: https://t.me/LaNuovaTronco

clans:
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoradice
    tag: YV2UJ0GV

sort: trophy

```
