### ISSUE TITLE
Request for creation of the Rock Family

### ISSUE THREAD

**Issue by Shubzalow** [RoyaleAPI/family-config#760]
Thank you in advance for creating our family.

```yaml
name: Rock Family
key: rock
color: black
emblem: flag_k_01
info:
  description: >Sous la bannière **Rock**, nous combattons pour les mêmes valeurs: respect et convivialité. 
>Si tu te retrouves dans ces 2 mots, ta place est parmi nous.
>Seule condition pour rejoindre **Rock Fort**: participation totale aux guerres de clans, aucun combat non fait toléré.
>**Rock Amadour** suit la tendance de son grand frère et grimpe dans le classement français.
>**Rocking Chair** est un lieu où le seul mot d'ordre est Carpe Diem.
>Nous ne formons qu'un, nous sommes un **Rock** !

clans:
  - name: Rock Fort
    tag: 8JLRLG0
  - name: Rock Amadour
    tag: L2J8JQQC
  - name: Rocking Chair
    tag: LVCRGGVQ
```

**Comment by smlbiobot** [comment]
```yml
name: Rock Family
key: rock
color: black
emblem: flag_k_01
info:
  description: >
    Sous la bannière **Rock**, nous combattons pour les mêmes valeurs: respect et convivialité. 
    Si tu te retrouves dans ces 2 mots, ta place est parmi nous.
    Seule condition pour rejoindre **Rock Fort**: participation totale aux guerres de clans, aucun combat non fait toléré.
    **Rock Amadour** suit la tendance de son grand frère et grimpe dans le classement français.
    **Rocking Chair** est un lieu où le seul mot d'ordre est Carpe Diem.
    Nous ne formons qu'un, nous sommes un **Rock** !

clans:
  - name: Rock Fort
    tag: 8JLRLG0
  - name: Rock Amadour
    tag: L2J8JQQC
  - name: Rocking Chair
    tag: LVCRGGVQ
```
