### ISSUE TITLE
Mukans Family

### ISSUE THREAD

**Issue by ermonnezza** [RoyaleAPI/family-config#762]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Mukans Family
key: mukans
color: red
emblem: flag_k_04
info:
  logo: https://i.ibb.co/GRbWHFm/Toro.png
  description: >**Join The Mukans Family** TOP WORLD WAR CLAN
    Famiglia molto unita e pronta a conquistare le vette mondiali war in clash royale.
    Cerchiamo talenti attivi in war, pronti ad essere guidati e sostenuti dal nostro team di appassionati dediti al clan
    La nostra comunità si basa su valori come rispetto, serietà, dedizioe e competitività 
    se anche tu ti rispecchi in questi valori e ambisci ad essere al TOP
    allora è giunto il momento di staccarsi dal gregge e diventare anche tu un toro con noi!
    Long paragraphs with markdown syntax.


  social:
    - twitter: https://twitter.com/mukans6
    - instagram: https://www.instagram.com/mukans_official
    - facebook: https://www.facebook.com/Mukans_official
clans:
  - name: #MuUuKaNs!!
    tag: 8UJ2UUJ8
  - name: MuKaNs!Academy!
    tag: 9G00R8RR
  - name: MuKaNs Darkness
    tag: LV2CLY8U
  - name: MuKaNs Legends
    tag: Q9C9QJQ9
```

**Comment by smlbiobot** [comment]
```yml
name: Mukans Family
key: mukans
color: red
emblem: flag_k_04
info:
  logo: /static/img/brands/logo/mukans.png
  description: >
    **Join The Mukans Family** TOP WORLD WAR CLAN
    Famiglia molto unita e pronta a conquistare le vette mondiali war in clash royale.
    Cerchiamo talenti attivi in war, pronti ad essere guidati e sostenuti dal nostro team di appassionati dediti al clan
    La nostra comunità si basa su valori come rispetto, serietà, dedizioe e competitività 
    se anche tu ti rispecchi in questi valori e ambisci ad essere al TOP
    allora è giunto il momento di staccarsi dal gregge e diventare anche tu un toro con noi!
    Long paragraphs with markdown syntax.


  social:
    - twitter: https://twitter.com/mukans6
    - instagram: https://www.instagram.com/mukans_official
    - facebook: https://www.facebook.com/Mukans_official
clans:
  - name: '#MuUuKaNs!!'
    tag: 8UJ2UUJ8
  - name: MuKaNs!Academy!
    tag: 9G00R8RR
  - name: MuKaNs Darkness
    tag: LV2CLY8U
  - name: MuKaNs Legends
    tag: Q9C9QJQ9
```
