### ISSUE TITLE
GPAS

### ISSUE THREAD

**Issue by CaneSciortoGPAS** [RoyaleAPI/family-config#763]
```yaml
name: GPAS FAMILY
key: gpas
color: orange
emblem: flag_k_04
info:
 logo: 
![logo](https://user-images.githubusercontent.com/115510314/195476140-829cf00a-7d21-405d-98df-3b87796c909c.png)
 description: >
          La Famiglia **GPAS**, fondata il **02/06/2018**, è costituita da un principale top clan italiano e 2 accademie fondate da _CaneSciorto_ su solide basi e veri valori quali unione, fratellanza ed educazione.
La War è il nostro principale obbiettivo, con ottimi risultati raggiunti nella storia del primo glorioso clan: Top **#3** Italia e Top **#49** Globale.
A disposizione ci sono gruppi _Telegram_ dedicati ai clan, canale _Telegram_ ed il canale _Discord_ per rimanere sempre aggiornati sull'andamento dei clan e sulle nostre iniziative.
Eventi e tornei a premi sempre ben organizzati, per poter mostrare le proprie abilità e competere con top player.
Premi per i migliori in war ogni season!
Fondamentale il rispetto del regolamento, affinché si mantenga il clima di FAMIGLIA che ci ha sempre contraddistinto.
Per entrare anche tu a far parte della Famiglia **GPAS** contatta i link qui sotto...ti aspettiamo!
 social:	
  - application: https://t.me/CaneSciorto
  - telegram: https://t.me/NicolaGpas
  - telegram: https://t.me/CicciogamerGPAS	
  - discord: https://discord.gg/PwDZFzFX8J
 clans:	
  - name: GPAS ACADEMY
    tag: L8LRGQCJ
  - name: GPAS ACADEMY 2
    tag: QQQLGRVQ
sort: trophy
…
```

**Comment by smlbiobot** [comment]
```yml
name: GPAS FAMILY
key: gpas
color: orange
emblem: flag_k_04
info:
  logo: /static/img/brands/logo/gpas.png
  description: >
    La Famiglia **GPAS**, fondata il **02/06/2018**, è costituita da un principale top clan italiano e 2 accademie fondate da _CaneSciorto_ su solide basi e veri valori quali unione, fratellanza ed educazione.
    La War è il nostro principale obbiettivo, con ottimi risultati raggiunti nella storia del primo glorioso clan: Top **#3** Italia e Top **#49** Globale.
    A disposizione ci sono gruppi _Telegram_ dedicati ai clan, canale _Telegram_ ed il canale _Discord_ per rimanere sempre aggiornati sull'andamento dei clan e sulle nostre iniziative.
    Eventi e tornei a premi sempre ben organizzati, per poter mostrare le proprie abilità e competere con top player.
    Premi per i migliori in war ogni season!
    Fondamentale il rispetto del regolamento, affinché si mantenga il clima di FAMIGLIA che ci ha sempre contraddistinto.
    Per entrare anche tu a far parte della Famiglia **GPAS** contatta i link qui sotto...ti aspettiamo!
  social:
    - application: https://t.me/CaneSciorto
    - telegram: https://t.me/NicolaGpas
    - telegram: https://t.me/CicciogamerGPAS
    - discord: https://discord.gg/PwDZFzFX8J
clans:
  - name: GPAS ACADEMY
    tag: L8LRGQCJ
  - name: GPAS ACADEMY 2
    tag: QQQLGRVQ
sort: trophy

```
