### ISSUE TITLE
ten.yml

### ISSUE THREAD

**Issue by ExtraLargeNoob** [RoyaleAPI/family-config#764]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Everestin Nepal
key: ten
color: red
emblem: Twin_Peaks_02
info: 
  logo: 
  description: > 
  Everestin Nepal 's premier Clan Wars Clan. Us, along with our family of clans strive to provide a positive, competitive, fun and quality Clash Royale experience, while focusing on Clan Wars.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/TUNmobile_GG
    - discord: https://discord.gg/3dgfgSayeK
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/UCHsJ7VcCPRd6nzEX2vppKgA
    - website: http://docs.redditalpha.com
    - instagram: https://www.instagram.com/tunmobile_gg/
    - facebook: https://www.facebook.com/TUNmobileGG
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Everestin Nepal
    tag: Y28RCY9V 
  - name: EVEREST NEPAL 2
    tag: YGULCL8U
  - name:
    tag:
```

**Comment by ExtraLargeNoob** [comment]
name: Everestin Nepal
key: ten
color: red
emblem: Twin_Peaks_02
info: 
  logo: 
  description: > 
  Everestin Nepal 's premier Clan Wars Clan. Us, along with our family of clans strive to provide a positive, competitive, fun and quality Clash Royale experience, while focusing on Clan Wars.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/TUNmobile_GG
    - discord: https://discord.gg/3dgfgSayeK
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/UCHsJ7VcCPRd6nzEX2vppKgA
    - website: http://docs.redditalpha.com
    - instagram: https://www.instagram.com/tunmobile_gg/
    - facebook: https://www.facebook.com/TUNmobileGG
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Everestin Nepal
    tag: Y28RCY9V 
  - name: EVEREST NEPAL 2
    tag: YGULCL8U
  - name:
    tag:

**Comment by smlbiobot** [comment]
```yml
name: Everestin Nepal
key: ten
color: red
emblem: Twin_Peaks_02
info:
  description: >
    Everestin Nepal 's premier Clan Wars Clan. Us, along with our family of clans strive to provide a positive, competitive, fun and quality Clash Royale experience, while focusing on Clan Wars.

  social:
    - twitter: https://twitter.com/TUNmobile_GG
    - discord: https://discord.gg/3dgfgSayeK
    - youtube: https://www.youtube.com/channel/UCHsJ7VcCPRd6nzEX2vppKgA
    - instagram: https://www.instagram.com/tunmobile_gg/
    - facebook: https://www.facebook.com/TUNmobileGG
clans:
  - name: Everestin Nepal
    tag: Y28RCY9V
  - name: EVEREST NEPAL 2
    tag: YGULCL8U

```
