### ISSUE TITLE
adding m4m

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#766]
```yaml
name: King's Family
key: kings
color: pink
emblem: Heart_01
info:
  logo: /static/img/brands/logo/kings.png
  description: >
    ⚠️🔥WAR⚔️MACHINES⚔️ONLY🔥⚠️


social:
    - discord: https://discord.gg/Ezt4MyE9Na
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Newbie Farm
    tag: RGJC28
  - name: The Revolution
    tag: PJ82LVCG
  - name: StillLegendary
    tag: 9CGYVG92
  - name: M for Mature
    tag: 2909VP
  - name: League of Kings
    tag: LO9UQL9Y
  - name: M for Mature 2
    tag: LQQPGG29
```
