### ISSUE TITLE
Requests update: add clan in the Illuminati Family

### ISSUE THREAD

**Issue by Kakadinha** [RoyaleAPI/family-config#767]
```yaml
name: ILLUMINATI
key: illuminati
color: purple
emblem: Star_Shine_03
info:
description: >
**Bem-vindo(a) à Família ILLUMINATI!** O nosso foco é a guerra de clãs. Os clãs da família são formados por jogadores comprometimentos com o jogo e que prezam pelo respeito, união e amizade. Vamos crescer juntos? Se junte a nós.
social:
- discord: https://discord.gg/TtKuSemW
clans:
- name: ILLUMINATI
  tag: CUPQC88
- name: SALVADORES
  tag: VYLGYC2
- name: Flangos Brasil
  tag: 2PUPRVRQ
- name: Coalizão Brasil
  tag: JV0V8LQ
- name: Pr0GamErs
  tag: CL9YOU
- name: ILLUMINATI 2.0
  tag: YV8JLPC2
- name: Winterfell_BR
  tag: PRP2UCY8
```
