### ISSUE TITLE
FREE ELVES Clan Family

### ISSUE THREAD

**Issue by TheMotherElf** [RoyaleAPI/family-config#77]
name: FREE ELVES Clan Family
key: freeelves
color: blue
emblem:
info:
  logo:
  description: >
    Official FREE ELVES tm Clan Family 
    We have no Master. We are ruled by spells and charms.

   All Clan Members are raised by elfs and are free of demanding dementors. 
   We appreciate more socks to get more elfs free.
   The sorting hat sorts the players into one of the FREE ELVES clans, depending on the players 
   card evolution.
   The Patronus is the Mother Elf that also provides help to the players in need
   Our house is built in discord. 
   Helps us free more elfs like Dobby and restore happiness in the elves family
   
   Come and use our spells in the arena
   The Mother ELF

  social:
        - discord: https://discord.gg/TcF7MGf
   
clans:
  - name: FREE ELVES
    tag: PYLYGPLV
  - name: FREE ELVES #2
    tag: Y2CLLYYG
  - name: Gavetas Charlie
    tag: 8ULQJG0G  
  - name: Gavetas Tango
    tag: P9Q9L89P
  - name: Gavetas Zen
    tag: P0RGGR20  
  - name: TOP ELITE PT
    tag: 8CVYRRP2

**Comment by TheMotherElf** [comment]
![image](https://user-images.githubusercontent.com/51665412/59268604-f9e96c80-8c44-11e9-80ee-eb8eabb04d23.png)
our badge doesn't appear in the badge list.

**Comment by TheMotherElf** [comment]
our logo 
![image](https://user-images.githubusercontent.com/51665412/59268907-a592bc80-8c45-11e9-929f-32e4d2afa31b.png)
if you need any further information please ask SML

**Comment by smlbiobot** [comment]
this is your badge: Bolt_03

**Comment by TheMotherElf** [comment]
name: FREE ELVES Clan Family
key: freeelves
color: blue
emblem:
info:
logo: Bolt_03
description: >
Official FREE ELVES tm Clan Family
We have no Master. We are ruled by spells and charms.

All Clan Members are raised by elfs and are free of demanding dementors.
We appreciate more socks to get more elfs free.
The sorting hat sorts the players into one of the FREE ELVES clans, depending on the players
card evolution.
The Patronus is the Mother Elf that also provides help to the players in need
Our house is built in discord.
Helps us free more elfs like Dobby and restore happiness in the elves family

Come and use our spells in the arena
The Mother ELF

social:
- discord: https://discord.gg/TcF7MGf

clans:

name: FREE ELVES
tag: PYLYGPLV
name: FREE ELVES #2
tag: Y2CLLYYG
name: FREE ELVES #3
tag: PYJ0880G
name: Gavetas Charlie
tag: 8ULQJG0G
name: Gavetas Tango
tag: P9Q9L89P
name: Gavetas Zen
tag: P0RGGR20
name: TOP ELITE PT
tag: 8CVYRRP2

**Comment by TheMotherElf** [comment]
name: FREE ELVES Clan Family
key: freeelves
color: blue
emblem:
info:
logo: Bolt_03
description: >
Official FREE ELVES tm Clan Family
We have no Master. We are ruled by spells and charms.

All Clan Members are raised by elfs and are free of demanding dementors.
We appreciate more socks to get more elfs free.
The sorting hat sorts the players into one of the FREE ELVES clans, depending on the players
card evolution.
The Patronus is the Mother Elf that also provides help to the players in need
Our house is built in discord.
Helps us free more elfs like Dobby and restore happiness in the elves family

Come and use our spells in the arena
The Mother ELF

social:

discord: https://discord.gg/TcF7MGf
clans:

name: FREE ELVES
tag: PYLYGPLV
name: FREE ELVES #2
tag: Y2CLLYYG
name: FREE ELVES #3
tag: PYJ0880G
name: FREE ELVES #4
tag: PJYJGGVQ
name: Gavetas Charlie
tag: 8ULQJG0G
name: Gavetas Tango
tag: P9Q9L89P
name: Gavetas Zen
tag: P0RGGR20
name: TOP ELITE PT
tag: 8CVYRRP2

**Comment by TheMotherElf** [comment]
as the update of our clan family, our family clans are increasing. Please use this last comment with all the actual clans.

**Comment by smlbiobot** [comment]
your config is complicated because it requires special formatting. pls use this updated config for future submissions:

```yml
name: FREE ELVES Clan Family
key: freeelves
color: blue
emblem: Bolt_03
info:
  logo: /static/img/brands/logo/free-elves.png
  description: >
    Official FREE ELVES tm Clan Family
    We have no Master. We are ruled by spells and charms.


    All Clan Members are raised by elfs and are free of demanding dementors.
    We appreciate more socks to get more elfs free.
    The sorting hat sorts the players into one of the FREE ELVES clans, depending on the players
    card evolution.


    The Patronus is the Mother Elf that also provides help to the players in need
    Our house is built in discord.
    Helps us free more elfs like Dobby and restore happiness in the elves family


    Come and use our spells in the arena
    The Mother ELF

  social:
  - discord: https://discord.gg/TcF7MGf
clans:

  - name: FREE ELVES
    tag: PYLYGPLV
  - name: "FREE ELVES #2"
    tag: Y2CLLYYG
  - name: "FREE ELVES #3"
    tag: PYJ0880G
  - name: "FREE ELVES #4"
    tag: PJYJGGVQ
  - name: Gavetas Charlie
    tag: 8ULQJG0G
  - name: Gavetas Tango
    tag: P9Q9L89P
  - name: Gavetas Zen
    tag: P0RGGR20
  - name: TOP ELITE PT
    tag: 8CVYRRP2
```
