### ISSUE TITLE
Wi and Fi

### ISSUE THREAD

**Issue by p3rkkr** [RoyaleAPI/family-config#770]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Wi and Fi(위앤피) Family
key: WiandFi
color: blue
emblem: Freeze_01
info:
  logo: https://drive.google.com/file/d/1V9LuvJXr5z2jt_KgAkggsV1jnMZOrHP-/view
  description: >
    ESTD 16.1.7 • ❄️위앤피🎖 • 제10회 KeG 클래시로얄 부문 1,2,3,4위👑

    Contact US : http://linktr.ee/wiandfi

  social:
    - website: https://linktr.ee/wiandfi
    - discord: https://discord.com/invite/Zk74fmsYzE
    - facebook: https://www.facebook.com/ClashRoyaleWiandFiClan/
clans:
  - name: Wi and Fi
    tag: YLYJ8
  - name: Wi and Fi 2nd
    tag: PYPJU0
```
