### ISSUE TITLE
Request for skill issue to be added

### ISSUE THREAD

**Issue by SmileMan1235** [RoyaleAPI/family-config#771]
File for Skill Issue family to be added.
```yaml
name: Skill Issue
key: skillissue
color: red
emblem: A_Char_Hammer_02
info:
  description: >
    Have severe skill issue? Join one of our clans and participate in clan wars!
  social:
    - discord: https://discord.gg/4C48dU3yXD
clans:
  - name: skill issue
    tag: Q02LU89P
  - name: finesse issue
    tag: QQ2R0GYL
```
