### ISSUE TITLE
Clan Family Arbeitsamt

### ISSUE THREAD

**Issue by fabio287890** [RoyaleAPI/family-config#772]
```yaml
name: Arbeitsamt Family
key: arbeitsamt
color: black
emblem: A_Char_King_01.png
info:
  logo:
  description: >
    Herzlich Willkommen im **Arbeitsamt!** Wir sind eine freundliche und aktive Clan-Family mit Fokus auf den **Clankrieg**. 
    Unsere Clans sind sehr chillig und immer freundlich! WhatsApp-Gruppe vorhanden, Discord coming soon! 
    Falls dich das Interesse gepackt hat, schau gerne bei uns vorbei! Wir freuen uns auf dich!
  social:
    - instagram: https://www.instagram.com/arbeitsamt_2.0/?next=%2F
    - discord: https://discord.gg/nKY4qfZR
clans:
  - name: Arbeitsamt 2.0
    tag: P8JVQ02C
  - name: Arbeitsamt 3.0
    tag: G089V9C0
  - name: Arbeitsamt 4.0
    tag: QJQCLY9Q
  - name: Sunʳⁱˢᵉ❄️Shadow
    tag: Q2LRCQPL
```
