### ISSUE TITLE
Royale2Success

### ISSUE THREAD

**Issue by OverproEH** [RoyaleAPI/family-config#773]
```yaml
name: Royale2Success
key: royal2success
color: blue
emblem: Star_Shine_01
info: 
  logo: ![Royal2Success_logo](https://user-images.githubusercontent.com/105162382/198141873-29936ab5-3901-4c8e-b553-92c82af7c388.png)
  description: >
    Competitive ClanWar-Clan consisting of just **two** guys with a combined total of **50+** Accounts. 
  social:
    - github: https://github.com/OverproEH  
    - email: mailto:overproeh@gmail.com
clans:
  - name: Fטck ladder
    tag: LJYQ0J9G
 
```
