### ISSUE TITLE
Nova QC

### ISSUE THREAD

**Issue by Poup1017** [RoyaleAPI/family-config#774]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:Nova QC
key:nova-qc
color:blue
emblem:![Star_Shine_02](https://user-images.githubusercontent.com/93715501/199257535-e6c13c83-b769-465e-8f32-baf6621a2b82.png)
info:
logo: /static/img/brands/logo/nova-qc.png
  description: >Axé sur les GDC (TOP MONDE), Nova QC est constitué de 24 clans pour tous les niveaux. 1100 membres actifs et unis contribuent à la croissance constante de cette grande famille. Respect, entraide et plaisir garantis. Facebook/Messenger/Discord.
Focused on Clan Wars (TOP WORLD), Nova QC is made up of 24 clans for all levels. 1100 active and united members contribute to the constant growth of this large familly. Respect, help between members and pleasure guaranteed. Facebook/Messenger/Discord. Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord:[ ](https://discord.gg/J66DCmhR)
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://www.facebook.com/groups/546237565896704/?ref=share
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
  - name: Nova QC ☆ 7
    tag: LCQJRP2Q
  - name: Nova QC ☆ 8
    tag: QP8G8LLR
  - name: Nova QC ☆ 9
    tag: G0GVRCR8
  - name: Nova QC ☆ 10
    tag: LUQP0UG8
  - name: Nova QC ☆ 11
    tag: Q2ULYQRY
  - name: Nova QC ☆ 12
    tag: QJCJ989C
  - name: Nova QC ☆ 13
    tag: QJ2R229R
  - name: Nova QC ☆ 14
    tag: GJ9L9VJQ
  - name: Nova QC ☆ 15
    tag: QLJ00U8V
  - name: Nova QC ☆ 16
    tag: QC02V2VP
  - name: Nova QC ☆ 17
    tag: GQJVV0RL
  - name: Nova QC ☆ 18
    tag: GJYQ9PCU
  - name: Nova QC ☆ 19
    tag: Q2LPURYR
  - name: Nova QC ☆ 20
    tag: Q08CJR0G
  - name: Nova QC ☆ 21
    tag: QJ9RPLGQ
  - name: Nova QC ☆ 22
    tag: GQUVJQJ0
  - name: Nova QC ☆ LVL 1
    tag: LUC8C2CQ
  - name: Nova QC ☆ Libre
    tag: Q02RJLYR
```

**Comment by Poup1017** [comment]
I hope that everything is okay and that we could work together in peacefull mind if there is something wrong. (sorry again for my english and if I dont get everything because I am french).
Thanks in advance!!

**Comment by smlbiobot** [comment]
```yml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: >
    Axé sur les GDC (TOP MONDE), Nova QC est constitué de 24 clans pour tous les niveaux. 1100 membres actifs et unis contribuent à la croissance constante de cette grande famille. Respect, entraide et plaisir garantis. Facebook/Messenger/Discord.
    Focused on Clan Wars (TOP WORLD), Nova QC is made up of 24 clans for all levels. 1100 active and united members contribute to the constant growth of this large familly. Respect, help between members and pleasure guaranteed. Facebook/Messenger/Discord. Long paragraphs with markdown syntax.

  social:
    - discord: https://discord.gg/J66DCmhR
    - facebook: https://www.facebook.com/groups/546237565896704/

clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
  - name: Nova QC ☆ 7
    tag: LCQJRP2Q
  - name: Nova QC ☆ 8
    tag: QP8G8LLR
  - name: Nova QC ☆ 9
    tag: G0GVRCR8
  - name: Nova QC ☆ 10
    tag: LUQP0UG8
  - name: Nova QC ☆ 11
    tag: Q2ULYQRY
  - name: Nova QC ☆ 12
    tag: QJCJ989C
  - name: Nova QC ☆ 13
    tag: QJ2R229R
  - name: Nova QC ☆ 14
    tag: GJ9L9VJQ
  - name: Nova QC ☆ 15
    tag: QLJ00U8V
  - name: Nova QC ☆ 16
    tag: QC02V2VP
  - name: Nova QC ☆ 17
    tag: GQJVV0RL
  - name: Nova QC ☆ 18
    tag: GJYQ9PCU
  - name: Nova QC ☆ 19
    tag: Q2LPURYR
  - name: Nova QC ☆ 20
    tag: Q08CJR0G
  - name: Nova QC ☆ 21
    tag: QJ9RPLGQ
  - name: Nova QC ☆ 22
    tag: GQUVJQJ0
  - name: Nova QC ☆ LVL 1
    tag: LUC8C2CQ
  - name: Nova QC ☆ Libre
    tag: Q02RJLYR

```
