### ISSUE TITLE
Update CR ADULTES FR Family 

### ISSUE THREAD

**Issue by AnkoWCR** [RoyaleAPI/family-config#775]
```yaml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: ![cr-adultes-fr](https://user-images.githubusercontent.com/92339610/199293088-5185b73b-4743-42be-a9c4-c763563679dd.png)
description: >
La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en GDC.**
Esprit d'équipe, fun & entraide.
**Rejoignez-nous**
social:
    - website: https://www.cradultesfr.site
clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: Q0VJ9YRJ 
```
