### ISSUE TITLE
WarxUnion & rugbyman Family

### ISSUE THREAD

**Issue by MIKO1976** [RoyaleAPI/family-config#777]
```yaml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: https://www.canva.com/design/DAFRILzeA-I/eQeE-jF9hYzP_SvaC6NGIw/view?utm_content=DAFRILzeA-I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
  description: >
    The **WarxUnion & rugbyman Family**

    Little presentation of our WarxUnion & rugbyman Family because it is important that everyone knows our story! And if you ever want to change clans or try something else in agreement with your leaders, that's possible! We are a family of 8 clans!
    Our family fosters an environment where casual and competitive styles of play can both flourish
  social:
    - discord: https://discord.gg/8cvV6xUWZU
clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: Hell Fish VIP
    tag: 9Q0JP29
  - name: #CRF
    tag: YPYGYYYR
  - name: bang bang bang!
    tag: 9VPRG2V2
  - name: 10000 guerriers
    tag: JQ0QJ0
  - name: #Team guerrier
    tag: UC2JGR
  - name: bang bang bang2
    tag: L0R9GRG8
```
