### ISSUE TITLE
Family 18

### ISSUE THREAD

**Issue by Antonimys13** [RoyaleAPI/family-config#778]
name: FAMILY 18
key: FAMILY18
color: Red
emblem: Crown_01
info:
  logo: https://sun9-72.userapi.com/c854224/v854224251/175537/RNqmt1LmNew.jpg
  description: >
Присоединяйся к нашей дружной семье кланов!
Турниры, призы, обучение, общение и многое другое!
Всегда рады принять новых участников в нашу семью!

  social:
    - telegram: https://t.me/Antonimys
clans:
  - name: "FORMAT 18"
    tag: 2PC908LY
  - name: ACADEMY 18
    tag: YQLVQPCG
  - name: SCHOOL 18
    tag: GJVU0PR0
 - name: FAMILY 18
    tag: GC2RCPOY

**Comment by Antonimys13** [comment]
name: FAMILY 18
key: FAMILY18
color: Red
emblem: Crown_01
info:
  logo: https://sun9-72.userapi.com/c854224/v854224251/175537/RNqmt1LmNew.jpg
  description: >
Присоединяйся к нашей дружной семье кланов!
Турниры, призы, обучение, общение и многое другое!
Всегда рады принять новых участников в нашу семью!
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - telegram: https://t.me/Antonimys
clans:
  - name: "FORMAT 18"
    tag: 2PC908LY
  - name: ACADEMY 18
    tag: YQLVQPCG
  - name: SCHOOL 18
    tag: GJVU0PR0

**Comment by smlbiobot** [comment]
```yml
name: FAMILY 18
key: FAMILY18
color: Red
emblem: Crown_01
info:
  logo: /static/img/brands/logo/family18.png
  description: >
    Присоединяйся к нашей дружной семье кланов!
    Турниры, призы, обучение, общение и многое другое!
    Всегда рады принять новых участников в нашу семью!

  social:
    - telegram: https://t.me/Antonimys
clans:
  - name: "FORMAT 18"
    tag: 2PC908LY
  - name: ACADEMY 18
    tag: YQLVQPCG
  - name: SCHOOL 18
    tag: GJVU0PR0
  - name: FAMILY 18
    tag: GC2RCPOY
```
