### ISSUE TITLE
QLF ARMY

### ISSUE THREAD

**Issue by ScubaSlavvo** [RoyaleAPI/family-config#779]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: QLF ARMY
key: QLF
color: purple
emblem: Elixir_01
info: Group of 3 clan war orientated clans. 
  logo: https://cdn.royaleapi.com/static/img/badge/legendary-2/Elixir_01.png?t=9959c9e6c
  description: > Family of 3 clan war clans. Based in france.
    Long paragraphs with markdown syntax.


  social:
    - discord: https://discord.gg/v24YTfYteU
clans:
  - name: 'qlf' army
    tag: C9LRQRJ
  - name: 974Nova e-sport
    tag: Y8JGJL90
  - name: "QLF" legion
    tag: Q2JR22RQ
```

**Comment by smlbiobot** [comment]
```yml
name: QLF ARMY
key: QLF
color: purple
emblem: Elixir_01
info:
  logo: /static/img/badge/legendary-2/Elixir_01.png
  description: >
    Family of 3 clan war clans. Based in france.
  
  

  social:
    - discord: https://discord.gg/v24YTfYteU
clans:
  - name: "'qlf' army"
    tag: C9LRQRJ
  - name: 974Nova e-sport
    tag: Y8JGJL90
  - name: '"QLF" legion'
    tag: Q2JR22RQ
```
