### ISSUE TITLE
[UPDATE] Team CMC Clan Family

### ISSUE THREAD

**Issue by lukefiasco** [RoyaleAPI/family-config#78]
```yaml
name: Team CMC
key: cmc
color: red
emblem: Fugi_04
info:
  logo: https://royaleapi.com/static/img/brands/logo/cmc.png
  description: >
    **Team CMC (Chan Mali Chan)**, home of teamcmcbot, royalepros.com and competitive team CMC Blizzard. We take pride as a family of 6 clans that lasted the test of time and in playing respectfully. Join us and check out our internal CMCompetitions (CMChampionship and CMCup).


  social:
    - website: https://royalepros.com
    - twitter: https://twitter.com/teamcmcbot
    - twitter: https://twitter.com/TeamCMCGG
    - facebook: https://www.facebook.com/TeamChanMaliChan
    - instagram: https://www.instagram.com/teamchanmalichan
    - application: https://royalepros.com/join
clans:
  - name: CMC Blizzard
    tag: 98R8GU2R
  - name: CMC Quake
    tag: 9RG9G98Q
  - name: CMC Tempest
    tag: P0UGY9Y0
  - name: CMC Blaze
    tag: 98R0JV0Q
  - name: CMC Whirlwind
    tag: 9L2UC9Y9
  - name: CMC Breeze
    tag: PPJCQRCJ
```
