### ISSUE TITLE
Update new tag clan 4 and new logo for CR ADULTES FR Family

### ISSUE THREAD

**Issue by AnkoWCR** [RoyaleAPI/family-config#780]
```yaml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: ![tortugalogofavicon2](https://user-images.githubusercontent.com/92339610/201041668-4bb53990-cbcc-4d8c-a997-41f472164bb3.png)
description: >
La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en GDC.**
Esprit d'équipe, fun & entraide.
**Rejoignez-nous**
social:
    - website: https://www.cradultesfr.site
clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: Q0VJ9YRJ 
```

**Comment by AnkoWCR** [comment]
![tortugalogofavicon](https://user-images.githubusercontent.com/92339610/201032464-ade03457-439d-4b8e-b258-29a2d7f52152.png)

**Comment by AnkoWCR** [comment]
New tag clan 4 and new logo

**Comment by smlbiobot** [comment]
```yml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: /static/img/brands/logo/cr-adultes-fr-2.png
  description: >
    La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en
    GDC.**
    Esprit d'équipe, fun & entraide.
    **Rejoignez-nous**
  social:
    - website: https://www.cradultesfr.site

clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: Q0VJ9YRJ

```
