### ISSUE TITLE
JonkaWonka's & vlaamse duivels Family

### ISSUE THREAD

**Issue by MelihOzcanPXL** [RoyaleAPI/family-config#782]
name: JonkaWonka's & vlaamse duivels Family
key: jonkawonka's
color: yellow
emblem: flag_k_02
info:
  logo: https://www.canva.com/design/DAFRILzeA-I/eQeE-jF9hYzP_SvaC6NGIw/view?utm_content=DAFRILzeA-I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
  description: >
    The **JonkaWonka's & vlaamse duivels Family**

    Little presentation of our JonkaWonka's & vlaamse duivels Family because it is important that everyone knows our story! And if you ever want to change clans or try something else in agreement with your leaders, that's possible! We are a family of 2 clans!
    Our family fosters an environment where casual and competitive styles of play can both flourish
  social:
    - discord: https://discord.gg/2MGYJEY
clans:
  - name: JonkaWonka's
    tag: 82829Y2V
  - name: vlaamse duivels
    tag: PQ229

**Comment by smlbiobot** [comment]
Don’t use other people’s logo

**Comment by smlbiobot** [comment]
```yml
name: JonkaWonka's & vlaamse duivels Family
key: jonkawonka
color: yellow
emblem: flag_k_02
info:
  description: >
    The **JonkaWonka's & vlaamse duivels Family**


    Little presentation of our JonkaWonka's & vlaamse duivels Family because it is important that everyone knows our story! And if you ever want to change clans or try something else in agreement with your leaders, that's possible! We are a family of 2 clans!
    Our family fosters an environment where casual and competitive styles of play can both flourish
  social:
    - discord: https://discord.gg/2MGYJEY
clans:
  - name: "JonkaWonka's"
    tag: 82829Y2V
  - name: vlaamse duivels
    tag: PQ229
```
