### ISSUE TITLE
Update #Fresher

### ISSUE THREAD

**Issue by Maxigon** [RoyaleAPI/family-config#783]
```yaml
name: Fresher Family
key: FTY
color: black
emblem: Freeze_01
info:
  logo: https://media.discordapp.net/attachments/711971183276326991/1012480609102344303/7_OG.png

  description: >
    **Loyalty, diligence and reliability are the cornerstones of the Fresher family.**

    - We use a ranking system, which distributes the members into the appropriate
    clans based on skill, win rate and card level. The goal is to form an internal
    top list that enables our strongest and most ambitious members of the family to
    assert themselves competitively in the CW and Ladder League.

    - Visit us on discord!

  social:
  - discord: https://discord.gg/sCrryNy
  - instagram: https://www.instagram.com/fresherthanyou_family
  - tiktok: https://www.tiktok.com/@fty_clash_royale
  - twitter: https://twitter.com/FTY_CR
  - email: mailto:ftycommunity@gmail.com
clans:
- name: FresherThanYou (CW)
  tag: P009PY9C
- name: '#SmarterThanYou (CW)'
  tag: Y0VV9YR8
- name: '#FresherThanYou (CW)'
  tag: GJ9G9R
- name: SmarterThanYou (CW)
  tag: LYLC89PR
- name: '#FasterThanYou (Casual)'
  tag: LY0VYRJV
- name: Legends™ (Ladder)
  tag: LUL0R90Q
```
