### ISSUE TITLE
Modification de la présentation et ajout de lien social pour la famille WarxUnion & rugbyman 

### ISSUE THREAD

**Issue by MIKO1976** [RoyaleAPI/family-config#786]
```yaml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: https://www.canva.com/design/DAFRILzeA-I/eQeE-jF9hYzP_SvaC6NGIw/view?utm_content=DAFRILzeA-I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
  description: >
    "WarxUnion & rugbyman Family is composed of 8 clans.
Here you can progress in a World Top gaming environment with a professional organization.
Do not hesitate to apply, surely your profile is suitable for one of our clans.
Friendly and cooperative atmosphere in our family!"
  

  social:
    - discord: https://discord.gg/8cvV6xUWZU
    - instagram: https://www.instagram.com/invites/contact/?i=1crzoppa8b6xl&utm_content=nrttktc
   - youtube: https://m.youtube.com/@miami54cr96?itct=CC0QoTAYASITCPLzn_eWwvsCFeVBTwQd_IwBrQ%3D%3D
 
  
  clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: Hell Fish VIP
    tag: 9Q0JP29
  - name: #CRF
    tag: YPYGYYYR
  - name: bang bang bang!
    tag: 9VPRG2V2
  - name: 10000 guerriers
    tag: JQ0QJ0
  - name: #Team guerrier
    tag: UC2JGR
  - name: bang bang bang2
    tag: L0R9GRG8
```

**Comment by smlbiobot** [comment]
- not a valid instagram link

 in the future if you didn’t update logo please just update this:

```yml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: /static/img/brands/logo/warxunion.png
  description: >
    "WarxUnion & rugbyman Family is composed of 8 clans.
    Here you can progress in a World Top gaming environment with a professional organization.
    Do not hesitate to apply, surely your profile is suitable for one of our clans.
    Friendly and cooperative atmosphere in our family!"
  social:
    - discord: https://discord.gg/8cvV6xUWZU
    - youtube: https://www.youtube.com/@miami54cr96


clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: Hell Fish VIP
    tag: 9Q0JP29
  - name: '#CRF'
    tag: YPYGYYYR
  - name: bang bang bang!
    tag: 9VPRG2V2
  - name: 10000 guerriers
    tag: JQ0QJ0
  - name: '#Team guerrier'
    tag: UC2JGR
  - name: bang bang bang2
    tag: L0R9GRG8
```
