### ISSUE TITLE
Edit for Team Kingfisher

### ISSUE THREAD

**Issue by Spherical-Pegasus** [RoyaleAPI/family-config#790]
```yaml

key: kingfisher
color: blue
emblem: Gem_02
info:
logo: https://i.imgur.com/Mri7nob.png


description: > 
     Hello Gamers! This is **Team Kingfisher**, an ambitious growing Gaming Community with Clans, Tournaments and E-Sports for Supercell Games. We are an English speaking community, originated from India but house people from all parts of the world. We have been extending our limits since the day and we haven't stopped from entertaining our Gaming mates with new and exciting stuff.

We started as a small Clan in Clash Royale on 19th July 2020, which was just to seek some fun out of the game. The wishes of our Community is our main aim. We have achieved it all with the help of our trust worthy Staff and Managers who aim to be the best. We are grateful to everyone who has ever been a part of the Community. Do follow our socials to stay updated.

Thank you,
Team Kingfisher ~ Aim to Glory
Since 2020


social:
  - webpage: https://teamkingfisher.netlify.app/
  - discord: https://discord.gg/QeKbKN2FmK
  - twitter: https://twitter.com/team_kingfisher
  - email: mailto:teamkingfisher.kc@gmail.com
    
    
 clans:
  - name: Kingfisher
    tag: QOJJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R
 ```

**Comment by smlbiobot** [comment]
```yml
name: Team Kingfisher
key: kingfisher
color: blue
emblem: Gem_02
info:
  logo: /static/img/brands/logo/kingfisher-2.png
  description: >
    Hello Gamers! This is **Team Kingfisher**, an ambitious growing Gaming Community with Clans, Tournaments and E-Sports for Supercell Games. We are an English speaking community, originated from India but house people from all parts of the world. We have been extending our limits since the day and we haven't stopped from entertaining our Gaming mates with new and exciting stuff.


    We started as a small Clan in Clash Royale on 19th July 2020, which was just to seek some fun out of the game. The wishes of our Community is our main aim. We have achieved it all with the help of our trust worthy Staff and Managers who aim to be the best. We are grateful to everyone who has ever been a part of the Community. Do follow our socials to stay updated.


    Thank you,<br>
    Team Kingfisher ~ Aim to Glory<br>
    Since 2020
  social:
    - website: https://teamkingfisher.netlify.app/
    - discord: https://discord.gg/QeKbKN2FmK
    - twitter: https://twitter.com/team_kingfisher
    - email: mailto:teamkingfisher.kc@gmail.com
clans:
  - name: Kingfisher
    tag: QOJJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R

```
