### ISSUE TITLE
MrBoom Clan Family

### ISSUE THREAD

**Issue by MrBoomAPI** [RoyaleAPI/family-config#792]
```yaml
name: Mr Boom Clan Family
key: mrboom
color: red
emblem: A_Char_Bomb_02
info:
  logo: https://vignette.wikia.nocookie.net/clashofclans/images/2/21/Bomber_info.png/revision/latest?cb=20170927155412
  description: >
    The **Mr Boom clan family** is a pair of top war clans! 
    **Mr Boom** is a top global and UK clan, focused on pushing high. 
    **Baby Boomers** is our feeder clan but is competitive in its own right. 
    Please join our discord or request in-game to join!
  social:
    - discord: https://discord.gg/WCSSraK8sY
    - twitter: https://twitter.com/MrBoom1996?t=AHtJXzxIFDps8J0Pdh1UYA&s=09 
clans:
  - name: Mr Boom
    tag: Y8Y2YLJG
  - name: Baby Boomers
    tag: LPYCYRJC
```

**Comment by smlbiobot** [comment]
```yml
name: Mr Boom Clan Family
key: mrboom
color: red
emblem: A_Char_Bomb_02
info:
  logo: /static/img/brands/logo/mrboom.png
  description: >
    The **Mr Boom clan family** is a pair of top war clans! 
    **Mr Boom** is a top global and UK clan, focused on pushing high. 
    **Baby Boomers** is our feeder clan but is competitive in its own right. 
    Please join our discord or request in-game to join!
  social:
    - discord: https://discord.gg/WCSSraK8sY
    - twitter: https://twitter.com/MrBoom1996?t=AHtJXzxIFDps8J0Pdh1UYA&s=09
clans:
  - name: Mr Boom
    tag: Y8Y2YLJG
  - name: Baby Boomers
    tag: LPYCYRJC
```
