### ISSUE TITLE
M.A.D

### ISSUE THREAD

**Issue by HexB1ade** [RoyaleAPI/family-config#793]
```yaml
name: M.A.D
key: shorturl.at/pT058
color: red
emblem: Crown_01
info: 
  logo: With our unstoppable 😡 RAGES 💢 , our toxic decks, and our reckless lumberjacks, we dominate clan wars easily! 
  description: > 

Our clan was inspired by the thousands of players who smash their devices due to getting **3 crowned** too many times. 
In our clan though, our rage doesn't go to our devices we play Clash Royale with, but to dominating wars, and gaining trophies. 

If you ever remember seeing a clan called "M.A.D" in a war, you most likely have recalled that your boat defences were destroyed on the first or second day.

  social:
    - discord: https://discord.gg/FXHmaUKU54
    
clans:
  - name: M.A.D
    tag: Q0RY2UR0
```
