### ISSUE TITLE
The Nova Stars

### ISSUE THREAD

**Issue by Aidwyd** [RoyaleAPI/family-config#794]
```yaml
name: Nova Stars 
key: Nova Family
color: purple
emblem: Moon_03
info:
  logo:  
  description: >
 *The Nova Stars* is a clan family that is a great serious clan, We have 3 clans that support casual, and serious clans, were also friendly and also a humorous clan. The main clan,  (N ø v a I V ) is the war clan that has global players and pro players that were a part of larger organizations.

  social:
    - discord: http://discord.gg/TEb22CQsF

clans:
  - name: N ø v a I V
    tag: QC0QQ2CJ 
  - name: Glory P.E.K.K.A
    tag: YG2YCUPQ
  - name: BIA4
    tag: YVVCJG0L
```
