### ISSUE TITLE
Update config Family: Mage Knights

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#795]
```yaml
name: Mage Knights
key: mageknights
color: violet
emblem: A_Char_Knight_01
info:
  logo: /static/img/brands/logo/mage-knights.png
  description: >
    The **Mage Knights** is a family of clans whose primary focus is war 
    and a community based on Brawl Stars and Clash Royale, playing competitively and casually. 
    We value practice and constructive criticism based on the entire card collection, 
    not just your ladder deck, but our clan family accepts players of all skills and card levels
    since there's always room for improvement. 
    _Mage Knights' main clan is currently in the top 50 in U.S. clan war rankings_. 
  social:
    - discord: https://dsc.gg/mageknights
    - youtube: https://www.youtube.com/channel/UC1R-b1AET3-eLGQNed6TYzA
clans:
  - name: Mage Knights
    tag: 2V28Y88Q
  - name: Mage Knights 2
    tag: YR00L2LY
  - name: Mage Knights 3
    tag: YLRJ8LUP
```
