### ISSUE TITLE
Add the One Punch Man Family

### ISSUE THREAD

**Issue by FelixLusseau** [RoyaleAPI/family-config#798]
```yaml
name: One Punch Man Family
key: opm_family
color: red
emblem: flag_k_01
info:
  description: >
    Clasheurs, Clasheuses, Amateurs de mangas, de foot, d’exorcisme, de botanique, d’études sur les cétacés, les 5 clans de la OPM Family sont là pour vous accueillir à bras ouverts ! En effet vous trouverez aisément un clan à votre niveau parmi ceux que nous plaçons sous l’étendard du clan fondateur One Punch Man ! L’ambition de nos clans a toujours été et restera de se hisser parmi les plus grands, à savoir les clans du top France et du top Monde en guerres de clans. Contribuez à cet ambitieux projet de ce pas en intégrant notre tribu, composée de toutes sortes de personnes, strictes mais compréhensives, détendues mais performantes, discrètes mais néanmoins toujours présentes. Il y aura toujours une place pour vous (oui, même si vous aimez les licornes)... **venez découvrir quel genre de Clasheur/e vous êtes en embarquant pour l’aventure à nos côtés !**
clans:
  - name: one punch man
    tag: YRLJGL9
  - name: Netherfriends
    tag: L2L8V08
  - name: The Deadly Sins
    tag: LVQ8P8YG
  - name: 100% Fr
    tag: LLUC90PP
  - name: Two Punch Man
    tag: G2CY2PPL
```
