### ISSUE TITLE
Add Night Fear

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#799]
```yaml
name: King's Family
key: kings
color: pink
emblem: Heart_01
info:
  logo: /static/img/brands/logo/kings.png
  description: >
    ⚠️🔥WAR⚔️MACHINES⚔️ONLY🔥⚠️


social:
    - discord: https://discord.gg/Ezt4MyE9Na
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Newbie Farm
    tag: RGJC28
  - name: The Revolution
    tag: PJ82LVCG
  - name: NIGHT FEAR
    tag: LPRJQP
  - name: M for Mature
    tag: 2909VP
  - name: StillLegendary
    tag: 9CGYVG92
  - name: League of Kings
    tag: LO9UQL9Y
```

**Comment by smlbiobot** [comment]
can’t use “kings” — someone had it. you had nothing to do with it. Your discord is named `Galactic Kings` so I will give you `Galactic Kings`

```yml
name: Galactic Kings
key: galactic-kings
color: pink
emblem: Heart_01
info:
  description: >
    ⚠️🔥WAR⚔️MACHINES⚔️ONLY🔥⚠️


social:
  - discord: https://discord.gg/Ezt4MyE9Na
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Newbie Farm
    tag: RGJC28
  - name: The Revolution
    tag: PJ82LVCG
  - name: NIGHT FEAR
    tag: LPRJQP
  - name: M for Mature
    tag: 2909VP
  - name: StillLegendary
    tag: 9CGYVG92
  - name: League of Kings
    tag: LO9UQL9Y
```
