### ISSUE TITLE
(UPDATED) apex predator clan family info (yaml)

### ISSUE THREAD

**Issue by J3H4M970N** [RoyaleAPI/family-config#8]
```yaml
name: Apex Predator Gaming [APG]™
key: APG
color: Blue
emblem: Crown_03
     info:
        logo: https://imgur.com/a/aM7Wetg
        description:
**"Come join the pride, greatness lies within!”**

**Apex Predator Gaming [APG]** is a mobile-focused gaming organization established in 2015.  We are aggressively pursuing our goal of becoming an esports organization as well as a home for causal and hardcore gamers!

Our goal is to empower **YOU** to **GIT GUD!**
 social:
    - website: https://apexpredatorgaming.com
    - discord: http://discord.gg/WJaPTfv
    - youtube: https://m.youtube.com/channel/UC4VCvb6lVjIZNjmRyMQn8mA
    - email: thelions.clashroyale@gmail.com mailto: Admin
clans:
    - name: The Lions
    tag: 2Q2ULLQ
    - name: The Wolves
    tag: 9Q98JQCV
    - name: The Cosmos
    tag: 9QUGUPUG
```

**Comment by smlbiobot** [comment]
- pls be extra careful with your spacing + formatting.
- Also wrong clan tags again. 
- note email url syntax

```yml
name: Apex Predator Gaming [APG]™
key: APG
color: Blue
emblem: Crown_03
info:
  logo: /static/img/brands/logo/apex-predator-a.jpg
  description: >
      **“Come join the pride, greatness lies within!”**

      **Apex Predator Gaming [APG]** is a mobile-focused gaming organization established in 2015.  We are aggressively pursuing our goal of becoming an esports organization as well as a home for causal and hardcore gamers!

      Our goal is to empower **YOU** to **GIT GUD!**
  social:
    - website: https://apexpredatorgaming.com
    - discord: http://discord.gg/WJaPTfv
    - youtube: https://m.youtube.com/channel/UC4VCvb6lVjIZNjmRyMQn8mA
    - email: mailto:thelions.clashroyale@gmail.com
clans:
  - name: The Lions
    tag: 2Q2ULLQ
  - name: The Wolves
    tag: 9Q98JQCV
  - name: The Cosmos
    tag: PQUGUPUG
```
