### ISSUE TITLE
Mise à jour WarxUnion et Rugbyman Family 

### ISSUE THREAD

**Issue by MIKO1976** [RoyaleAPI/family-config#801]
```yaml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: /static/img/brands/logo/warxunion.png
  description: >
    "WarxUnion & rugbyman Family is composed of 8 clans.
Here you can progress in a World Top gaming environment with a professional organization.
Do not hesitate to apply, surely your profile is suitable for one of our clans.
Friendly and cooperative atmosphere in our family!"
  

  social:
    - discord: https://discord.gg/8cvV6xUWZU
    - instagram: https://instagram.com/warxunion2_cr?igshid=YmMyMTA2M2Y=
   - youtube: https://m.youtube.com/@miami54cr96?itct=CC0QoTAYASITCPLzn_eWwvsCFeVBTwQd_IwBrQ%3D%3D
 
  
  clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: Hell Fish VIP
    tag: 9Q0JP29
  - name: #CRF
    tag: YPYGYYYR
  - name: bang bang bang!
    tag: 9VPRG2V2
  - name: 10000 guerriers
    tag: JQ0QJ0
  - name: #Team guerrier
    tag: UC2JGR
  - name: bang bang bang2
    tag: L0R9GRG8 
  - name: Les s@uv@ges
    tag: YVU9U00R
```
