### ISSUE TITLE
Add New familly Furia Royale II

### ISSUE THREAD

**Issue by furiaroyaleii** [RoyaleAPI/family-config#804]
```yaml
name: Furia Royale II
key: frii
color: purple
emblem: badges/Heart_01.png
info:
  logo:
  description: >
    Somos os melhores!


    Add new line with 2 line breaks as above.
  social:
    - instagram: https://instagram.com/furiaroyale2?igshid=YmMyMTA2M2Y=
    - facebook:https://www.facebook.com/profile.php?id=100086334054937
 
clans:
  - name: Furia Royale II
    tag: 9CVJ9CLJ
  - name: Bloodyhands
    tag: 9CVVG9
 - name: Akatsuki Br
    tag: 928VR909
  -name: FRII
    tag: QYJ9800C
 

```
