### ISSUE TITLE
Warriors Faction Update

### ISSUE THREAD

**Issue by toddlilly** [RoyaleAPI/family-config#806]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Warriors Faction
key: warriorsfaction
color: red
Emblem: star_shine_03
sort: trophy
info:
  description: >
Warriors Faction is a family of elite war clans including 2 that rank at the top globally! Our clans have been dominating wars for many years and our players are passionate about war. Join our discord to be in the best clan family in the US!
  social:
    - discord: https://discord.gg/warriorsfaction
    - twitter: https://twitter.com/cr_warfaction
    - instagram: https://twitter.com/cr_warfaction
clans:
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: CRL eSports PRO
    tag: 9UV202Q2
  - name: Elixir Elites
    tag: PP00JCRV
  - name: Divine Wind
    tag: 2CJY2008
  - name: BEWO Pro
    tag: YY89R8RG
  - name: Hawaiian Beast
    tag: P2RPJQ9R
  - name: Elite Assassins
    tag: 8QCRCU2L
  - name: Alpha Steel
    tag: 9PV9JL
  - name: Ready Reserves
    tag: L9RGU90V
  - name: No Clan
    tag: YC8CJV9G
  - name: monkey mafia 2
    tag: 2CYLGU8R
  - name: Thunder Harbor
    tag: YRGJ0QYV
  - name: PRO ERA
    tag: LYUL0Y2V
  - name: gladiators
    tag: LQJQUQ2G
  - name: MK 4PLaY
    tag: QQLJJ8YP
  - name: Mini Knights
    tag: GG8UJC29
  - name: CRL Tournaments
    tag: LYYC0GJY
  - name: Elixir Empire
    tag: LUQY2JPY
```
