### ISSUE TITLE
[UPDATE] TheSupremeTeam

### ISSUE THREAD

**Issue by shivalsookay** [RoyaleAPI/family-config#81]
```yaml
name: TheSupremeTeam
key: ST
color: blue
emblem: Arrow_03
info:
  logo: https://static.wixstatic.com/media/a97b56_0232640558b8456fb0329c7d9588276a~mv2.gif/v1/fill/w_800,h_600,al_c,q_90/file.jpg
  description: >
 **TheSupremeTeam** is one of the newest and greatest families of Clash Royale and Brawl Stars! We are a casual and friendly family but competitive when it comes to wars! We share decks, 1v1 and spam emotes to achieve victory! If you decide to join us in war then we have high expectations noble warrior! If not, donate and enjoy your stay!
  social:
    - discord: https://discord.gg/4Dcrw5p
    - reddit: https://www.reddit.com/user/gray_sama_4958
    - disboard: https://disboard.org/dashboard/servers
clans:
   - name: TheSupremeTeam
     tag: P9VUUPRV
   - name: SupremeTeam #2
     tag: P89C0VY0
   - name: SupremeTeam #3
     tag: Y8J9Q8U9
```

**Comment by smlbiobot** [comment]
- disboard is not a valid destination.

**Comment by smlbiobot** [comment]
```yml
name: TheSupremeTeam
key: ST
color: blue
emblem: Arrow_03
info:
  logo: /static/img/brands/logo/supreme-team.gif
  description: >
    **TheSupremeTeam** is one of the newest and greatest families of Clash Royale and Brawl Stars! We are a casual and friendly family but competitive when it comes to wars! We share decks, 1v1 and spam emotes to achieve victory! If you decide to join us in war then we have high expectations noble warrior! If not, donate and enjoy your stay!
  social:
    - discord: https://discord.gg/4Dcrw5p
    - reddit: https://www.reddit.com/user/gray_sama_4958
clans:
   - name: TheSupremeTeam
     tag: P9VUUPRV
   - name: "SupremeTeam #2"
     tag: P89C0VY0
   - name: "SupremeTeam #3"
     tag: Y8J9Q8U9
```
