### ISSUE TITLE
Update Clash Dynasty family information 

### ISSUE THREAD

**Issue by GaretJaxxx** [RoyaleAPI/family-config#810]
Hi GiTHub, this configuration below replaces the previous Clash Dynasty GiTHub configuration.

————————————————————

```yaml
name: Clash Dynasty War Group
key: CLASHDYNASTY
color: blue
emblem: Star_Shine_03
info:
  logo: 
https://cdn.discordapp.com/attachments/869280005966946344/1033747189421318144/90B49554-0602-4118-8C20-8994AD62F43A.png

  description:
**CLASH DYNASTY** is one of the top **War Groups** in the game. Established in 2019, we have rapidly grown to now encompass 7 war & ladder focused clans that embody team spirit, passion for the game and a will to succeed. 

Our clans range from top global & local, to mid level and progressing. We’re always looking for determined and ambitious **TEAM** players to join us across our family. In return we offer skills development, non-toxic playing environment and an opportunity to progress through our Discord connected clans. 

Come onboard and build your journey with us! 

  social:
    - discord: http://discord.gg/YwkzcJSHV7
  
clans:
  - name: Clash of Duty
    tag: Y80C2UJR
  - name: Clash of Honour
    tag: YCL8RY82
  - name: Clash of Titans
    tag: LQGJ0QLV
  - name: Clash of Glory
    tag: L8Q8GPGU
  - name: Clash of Realms
    tag: L9JV99PP
  - name: Clash of Fury
    tag: Q2RL22U2
  - name: Clash of Kings
    tag: LY9LJGGC
```

Thank you so much as ever :)
GJ
