### ISSUE TITLE
dudes united

### ISSUE THREAD

**Issue by robotdoggo** [RoyaleAPI/family-config#812]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Dudes United
key: dudesunited
color: black
emblem: Skull_06
info:
  logo:
  description: > we're looking for European, English speaking players that want to grow with the family trophy push. apply on discord: discord.gg/edyQXqC2yB

    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: Dudes Reunited
    tag: L0PQ2ULQ
  - name:Dudes academy
    tag:GQYY2R82
  - name:
    tag:
```
