### ISSUE TITLE
Add clan family: Occasus™

### ISSUE THREAD

**Issue by OccasusCR** [RoyaleAPI/family-config#814]
```yaml
name: 01. Familia Occasus™
key: occasus
color: black
emblem: Fugi_03
info:
  logo: https://media.discordapp.net/attachments/1060291028415946765/1060293553504399471/Logo_Occasus1.png
  description: >
    Bienvenido(a) a la **Familia Occasus™**


    Clan enfocado en guerra de clanes, con miembros activos, muy unidos, comprometidos en el juego y en apoyar el desarrollo de cada jugador.


    Somos top 10 de **Venezuela** y estamos presentes en el ranking global. Nuestro equipo competitivo participa en diferentes ligas.
   

    **Siempre tenemos lugar para jugadores activos, responsables con la guerra de clanes, que compartan la pasión por el Clash y que busquen permanecer por largo plazo en nuestra hermandad.** Ven y únete.
    
  social:
    - discord: https://discord.gg/s3kt5PDF
    - twitter: https://twitter.com/occasus_cr
    - website: https://www.occasuscr.com
    - email: mailto:OccasusCR@gmail.com
clans:
  - name: Occasus™
    tag: 9C8J8QCL
  - name: Occasus™ II
    tag: YQCQLPG0
  - name: Occasus™ III
    tag: QCJGVYGL

```
