### ISSUE TITLE
Avenging Souls

### ISSUE THREAD

**Issue by UncleMikeAS** [RoyaleAPI/family-config#815]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Avenging Souls
key: avengingsouls
color: purple
emblem: skull_05.png
info:
  logo: https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/badges/Skull_05
  description: > 
Rising clan in the United States looking to continue to grow and expand. Contact our leaders to join today!
  social:
    - discord: http://discord.gg/PMQzfzaX
    - application: http://discord.gg/PMQzfzaX
clans:
  - name: Avenging Souls
    tag: PCPGLYY0
  - name: Avenging II
    tag: QUQR8Q90
```
