### ISSUE TITLE
Please add FURY family config

### ISSUE THREAD

**Issue by ilvez** [RoyaleAPI/family-config#816]
Here is our YAML:
```yaml
name: FURY
key: fury
color: blue
emblem: Traditional_Star_03
info:
  description: >
    Fury is an international war focused clan from the earliest days of CR.
    We offer a stable, mature place for players looking to grow their skills or compete with a clan.
    War participation is required.
  social:
    - discord: https://discord.gg/GpEPf4cf6W
clans:
  - name: FURY
    tag: GQCCPR
  - name: FURIOUS
    tag: LYRC0G9U
```
