### ISSUE TITLE
Raid and Run

### ISSUE THREAD

**Issue by ShenoPowel** [RoyaleAPI/family-config#818]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Raid and Run
key: raid01801
color: red
emblem: Arrow_02
info:
  logo:
  description: >
     **Raid and Run** is a clan that is mainly focused on War. 
We have grown strong in the past year and we will continue to grow. We are a group of highly
motivated people. If you want to join us, Apply in our discord below.

    Add new line with 2 line breaks as above.
  social:
    - discord: http://discord.gg/vx3HAAkxMF
    
clans:
  - name: Raid and Run
    tag: LQLQV2
  - name: Raid and Run Jr
    tag: QPVL2JRR
  - name: Raid and Run AR
    tag: Q22VUY82
```
