### ISSUE TITLE
Belgian Reborn Family

### ISSUE THREAD

**Issue by Adagio4strings** [RoyaleAPI/family-config#819]
```yaml
name: Belgian Reborn Family
key: reborn
color: blue
emblem: A_Char_Goblin_01
info:
  description: >
    Belgian Reborn est un clan présent sur Clash Royale depuis de nombreuses années. Nous avons toujours été actifs et sur le devant de la scène
	en guerre de clans. La famille s'est peu à peu agrandie et compte aujourd'hui quatre clans et environ 150 membres.
	Rejoignez-nous dans l'un de nos clans!

clans:
  - name: Belgian Reborn
    tag: 9J8UU8J0
  - name: Reborn School
    tag: PGVJVGCQ
  - name: Belgian lvl 1
    tag: LUJ9QJRY
  - name : Reborn Pause
    tag : LVC2G929
```
