### ISSUE TITLE
Belgique one - new family

### ISSUE THREAD

**Issue by SOAD04** [RoyaleAPI/family-config#82]
```yaml
name: Belgique one
key: Belgique_one
color: blue
emblem: A_Char_King_03
sort: trophy
info:
  logo: /static/img/badge/A_Char_King_03.png
  description: >
    **Belgique one** est une famille de clans francophones pour adultes.
    Des guerres de clan sont organisées en continu.
    Si vous êtes motivés, n'hésitez pas à nous rejoindre !
  social:
    - discord: http://discord.gg/sT6ewxH
clans:
  - name: Belgique one
    tag: Q022QV
  - name: Belgique one II
    tag: PLLUJUP0
```
