### ISSUE TITLE
Les Balles FR

### ISSUE THREAD

**Issue by louishppe** [RoyaleAPI/family-config#821]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Les Balles FR
key: #LRG98
color: Red
emblem: Flag_d_01
info: 
  logo: /static/img/brands/logo/nova.svg
  description: > Salut! Clan bonne ambiance, entraide et respect. Axés gdc -> 1600 points/semaine obligatoires. Since 03/2016 Code: RoyaleAPI
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/HppeLouis
    - email: mailto: lhappeal@gmail.com
clans:
  - name: Les Balles FR
    tag: #LRG98
```
