### ISSUE TITLE
update to galactic-kings, add #Destructium

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#822]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Galactic Kings
key: galactic-kings
color: pink
emblem: Heart_01
info:
  description: >
    ⚠️🔥WAR⚔️MACHINES⚔️ONLY🔥⚠️


social:
  - discord: https://discord.gg/Ezt4MyE9Na
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Newbie Farm
    tag: RGJC28
  - name: The Revolution
    tag: PJ82LVCG
  - name: NIGHT FEAR
    tag: LPRJQP
  - name: StillLegendary
    tag: 9CGYVG92
  - name: '#Destructium'
    tag: Q0VQLQ9R
  - name: League of Kings
    tag: LO9UQL9Y
  - name: M for Mature
    tag: 2909VP
```
