### ISSUE TITLE
Request to add - Purjehdus Community

### ISSUE THREAD

**Issue by HexHeikki** [RoyaleAPI/family-config#824]
```yaml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: https://drive.google.com/file/d/1fWz2sJg_lz9uUxG3AEQPH2auFtQwLOlF/view?usp=share_link
  description: >
**Purjehdus Community**


Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus Community is meant for Finnish speaking players from all ages.


**Ladder Clans:** Purjehdus, Seilaus, Veneily
**War Clans:** NC Finland, Suomi Soturit, Laivanupotus
  social:
    - discord: http://discord.gg/vjeUGTApzf
    - twitch: https://twitch.tv/purjehdus
clans:
  - name: Purjehdus
    tag: QRPQCUQU
  - name: Seilaus
    tag: LQ2PL8Y8
  - name: Veneily
    tag: G9YCPUYL
  - name: NC Finland
    tag: 8LP0Y9YP
  - name: ✨SUOMI SOTURIT✨
    tag: 9YY9QL2Y
  - name: Laivanupotus
    tag: Q99CPQYR
```
