### ISSUE TITLE
New Clan Family - Quittenturm Family

### ISSUE THREAD

**Issue by Stevvv64** [RoyaleAPI/family-config#825]
```yaml
name: Quittenturm Clan Family
key: qt
color: blue
emblem: Tower_03
info: 
  description: >
    Aktive und zuverlässige Krieger*innen sind Herzlich Willkommen! Discord & WhatsApp vorhanden. 
  social:
    - discord: https://discord.gg/dHxtPkbaHt
clans:
  - name: Quittenturm
    tag: 9L20RGUL 
  - name: BinaryBandits
    tag: 9L2U0GL2
  - name: QT Fighters
    tag: G882YVG
```
