### ISSUE TITLE
The Beast’s Domain

### ISSUE THREAD

**Issue by Jengerr** [RoyaleAPI/family-config#826]
```yaml
name: The Beast’s Domain
key: beastmode
color: blue
emblem: skull_05
info:
  logo:
  description: >
The Beast’s Domain is a family of competitive and active war players with the goal of improving and moving up on the leaderboards.


social:
    - discord: https://discord.gg/JqpzEGeeJS
clans:
  - name: #Beastmode2.0 
    tag: 9YYRQVGP
- name: #FeedTheBeast 
    tag: LQRPC0QP
  - name: Team Aqua
    tag: L280QQUR
  - name: #tameTheBeast
    tag: Q202VCG9
  - name: #wakeTheBeast
    tag: QQJQ2CRG
  - name: #FearTheBeast
    tag: GGULP0QL
```
