### ISSUE TITLE
Edit for Team Kingfisher

### ISSUE THREAD

**Issue by Spherical-Pegasus** [RoyaleAPI/family-config#827]
```yaml
name: Team Kingfisher
key: kingfisher
color: blue
emblem: Gem_02
info:
  logo: /static/img/brands/logo/kingfisher-2.png
  description: >
ㅤWe are **Team Kingfisher**, an international gaming Organization with Clans, Tournaments and E-Sports, mainly focused on Supercell Games. We are an English speaking community, originally from India but house people from all parts of the world. We started as a small clan in Clash Royale on 19th July 2020, which was just to seek some fun out of the game. Now, we are one of the most renowned Clan Families in Clash Royale with our Main Clan nearing #1k globally in Clan Wars, and Clans in multiple games running successfully along with regular tournaments for Clash Royale. We have earned this position just because of the support by our clanmates and the community, along with the help of our worthy Staff. We are grateful to everyone who has ever been a part of us. You can follow us on <Twitter> to stay updated.
Keep Clashing ;)

ㅤTeam Kingfisher ~ Aim to Glory
ㅤSince 2020
  social:
    - website: https://teamkingfisher.netlify.app/
    - discord: https://discord.gg/QeKbKN2FmK
    - twitter: https://twitter.com/team_kingfisher
    - email: mailto:teamkingfisher.kc@gmail.com
clans:
  - name: Kingfisher
    tag: Q0JJQVYU
  - name: Kingfisher
    tag: QLJYCVPY
  - name: Kingfisher
    tag: LC9RPP9R
```
