### ISSUE TITLE
ACTUALIZACIÓN DE LA FAMILIA DE CLANES

### ISSUE THREAD

**Issue by fabi0M** [RoyaleAPI/family-config#830]
```yaml
name: OlimposEsports Family
key: OlimposEsports
color: [pink]
emblem: Tower_01
 info:
  logo: ![Picsart_22-10-20_22-06-55-434](https://user-images.githubusercontent.com/83083991/215850391-fd4f4320-e107-4183-bf46-53bd37a5db4b.png)
social:
    - website: https://mifaxp.webnode.es
    - twitter: https://twitter.com/mifaxp
    - discord: https://discord.gg/TceEpJbuhe
    - twitter: https://twitter.com/OlimposClanes
    - discord: https://discord.gg/Up4uyuPd7j
    - twitter: https://twitter.com/OlimposEsports
    - discord: https://discord.gg/5v6VYGW4Ta
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: OlimposEsports
    tag: Q2V8V0QL
  - name: Colusiom prime 
    tag: LCJC2P0R
  - name: MegaCampeones
    tag: QLJVP9QV
```

_Originally posted by @smlbiobot in https://github.com/RoyaleAPI/family-config/issues/530#issuecomment-903622596_
