### ISSUE TITLE
DFAC Clan Family

### ISSUE THREAD

**Issue by cameronmelo** [RoyaleAPI/family-config#832]
```yaml
name: DFAC Family
key: dfac
color: black
emblem: Skull_06
info:
  logo: https://www.shutterstock.com/image-vector/vector-cartoon-skull-isolated-on-white-1054656815
  description: >
    **WE TAKING OVER** Our clan family has been gaming since the 2000s, we are competitive and active players looking to expand to multiple clans to fit everyone's needs, whether that be casual or competitive.
    - discord: http://discord.gg/znfY5CQFzT
clans:
  - name: DFAC
    tag: QLCCUCVC
  - name: DFAC II
    tag: GCVU9YYV
  - name: Les Oufffs
    tag: 2JJ9L8YV
```
