### ISSUE TITLE
Familia Gallinero

### ISSUE THREAD

**Issue by EGEevee** [RoyaleAPI/family-config#833]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: red
- `key`: Gallinero
- `emblem`: https://cdn.royaleapi.com/static/img/badge/gold-3/Sword_01.png?t=13fee2b4c
- `description` and `links`: Bienvenidos a la Familia Gallinero. Para uniros es necesario jugar de jueves a domingo la guerra de clanes con los 4 mazos. Dando guerra desde el 09/08/21.
- `tag`:  #L99R99U9

Fill in the configuration below:

```yaml
name: El Gallinero
key: #L99R99U9
color: red
emblem: 
![image](https://user-images.githubusercontent.com/124502288/216817667-8772bccf-83fa-4572-9552-2c2129b42dc6.png)

info: Bienvenidos al clan principal de la Familia Gallinero. Para estar en el clan hay que jugar guerra de jueves a domingo los 4 mazos.
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: https://discord.gg/UvgaWsswb3
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://www.instagram.com/el_gallinero_royale/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: El Gallinero
    tag: #L99R99U9
  - name: As Burgas
    tag: #GYLGGQ0V
  - name: El Gallinero2
    tag: #GLVRCCQU
```

**Comment by smlbiobot** [comment]
follow format pls.

```yml
name: El Gallinero
key: gallinero
color: red
emblem: Sword_01
info:
  description: >
    Bienvenidos al clan principal de la Familia Gallinero. Para estar en el clan hay que jugar guerra de jueves a domingo los 4 mazos.
  social:
    - discord: https://discord.gg/UvgaWsswb3
    - instagram: https://www.instagram.com/el_gallinero_royale/
clans:
  - name: El Gallinero
    tag: L99R99U9
  - name: As Burgas
    tag: GYLGGQ0V
  - name: El Gallinero2
    tag: GLVRCCQU
```
