### ISSUE TITLE
Clan Family Update

### ISSUE THREAD

**Issue by Stevvv64** [RoyaleAPI/family-config#836]
```yaml
name: Quittenturm Clan Family
key: qt
color: blue
emblem: Tower_03
info: 
  description: >
    Aktive und zuverlässige Krieger*innen sind Herzlich Willkommen! Discord & WhatsApp vorhanden. 
  social:
    - discord: https://discord.gg/dHxtPkbaHt
clans:
  - name: Quittenturm
    tag: 9L20RGUL 
  - name: BinaryBandits
    tag: 9L2U0GL2
  - name: QT Fighters
    tag: GG882YVG
```

**Comment by smlbiobot** [comment]
actually we found an issue why your family is not displayed — the `qt` key is already taken so best I could do is give you `quittenturm`


```yml
name: Quittenturm Clan Family
key: quittenturm
color: blue
emblem: Tower_03
info:
  description: >
    Aktive und zuverlässige Krieger*innen sind Herzlich Willkommen! Discord & WhatsApp vorhanden. 
  social:
  - discord: https://discord.gg/dHxtPkbaHt
clans:
- name: Quittenturm
  tag: 9L20RGUL
- name: BinaryBandits
  tag: 9L2U0GL2
- name: QT Fighters
  tag: G882YVG

```

**Comment by Stevvv64** [comment]
This is our existing clan family. We just need to change the last tag: GG882YVG - there is a wrong clan in our family at the moment

**Comment by smlbiobot** [comment]
This is the QT family. that’s what I meant:
```yml
name: QT Family
key: QT
color: purple
emblem: flag_k_03

info:
  logo: /static/img/brands/logo/qt.png

  description: >
    QT Elite gibt es seit 2016 und wir gehören seit langer Zeit zu den stärksten Clans
    in Deutschland. Seit März 2022 sind wir, als QT Elite, eigenständig, und haben
    unseren Zweitclan QT Elite Jr. gegründet. Spaß am Spiel, viel Humor, große Erfolge
    und noch höhere Ziele, als die bisher schon erreichten, haben bei uns oberste
    Priorität.
    Aktiv und motiviert, in guten und in schlechten Zeiten immer ein Team, und jeder
    zieht mit. Einer für alle, alle für einen, dafür stehen wir als QT Family.

clans:
- name: QT Elite
  tag: 9JRVYQQC
- name: QT Elite Jr.
  tag: LUY9J2JG
```

**Comment by smlbiobot** [comment]
so you can only use the long form.

```yml
name: Quittenturm Clan Family
key: quittenturm
color: blue
emblem: Tower_03
info:
  description: >
    Aktive und zuverlässige Krieger*innen sind Herzlich Willkommen! Discord & WhatsApp vorhanden.
  social:
  - discord: https://discord.gg/dHxtPkbaHt
clans:
- name: Quittenturm
  tag: 9L20RGUL
- name: BinaryBandits
  tag: 9L2U0GL2
- name: QT Fighters
  tag: GG882YVG
```
