### ISSUE TITLE
Update The Beast’s Domain

### ISSUE THREAD

**Issue by Jengerr** [RoyaleAPI/family-config#837]
```yaml
name: #BeastDomain
key: Beast
color: purple
emblem: skull_05
info:
logo:
description: >
 #BeastDomain is a family of competitive and active war players with the goal of improving and moving up on the leaderboards. We have 6 different clans, for all different skill and levels. Join us today and become a beast!


social:
    - discord: https://discord.gg/JqpzEGeeJS
clans:
  - name: #Beastmode2.0 
    tag: 9YYRQVGP
- name: #FeedTheBeast 
    tag: LQRPC0QP
  - name: #TameTheBeast
    tag: Q202VCG9
  - name: #WakeTheBeast
    tag: QQJQ2CRG
  - name: #FearTheBeast
    tag: GGULP0QL 
  - name: Team Aqua
    tag: L280QQUR
```

**Comment by Jengerr** [comment]
Please don’t forget to add the discord link in the socials, last time it wasn’t added for some reason, thanks.

**Comment by smlbiobot** [comment]
Hash `#` is a special character in yml and so you must quote them.

The yaml you submitted is invalid. Please use the following for your config moving forward. 

```yml
name: '#BeastDomain'
key: Beast
color: blue
emblem: Skull_05
info:
  description: >
    \#BeastDomain is a family of competitive and active war players with the goal of improving and moving up on the leaderboards. We have 6 different clans, for all different skill and levels. Join us today and become a beast!
  social:
  - discord: https://discord.gg/JqpzEGeeJS
clans:
- name: '#Beastmode2.0'
  tag: 9YYRQVGP
- name: '#FeedTheBeast'
  tag: LQRPC0QP
- name: '#TameTheBeast'
  tag: Q202VCG9
- name: '#WakeTheBeast'
  tag: QQJQ2CRG
- name: '#FearTheBeast'
  tag: GGULP0QL
- name: Team Aqua
  tag: L280QQUR
```
