### ISSUE TITLE
Update Clan Family Record for 101% Canadian

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#838]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 101% Canadian Clan Family
key: canadian
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/canadian.png
  description: >
    101% Canadian is Canada's **premier Clan Wars Clan**. Us, along with our family
    of clans strive to provide a positive, competitive,
    fun and quality Clash Royale experience, while focusing on Clan Wars.
social:
- discord: discord.gg/pttBsyqYH7
clans:
- name: 101% Canadian
  tag: 9UCRJG8V
- name: 99.9% Canadian
  tag: 2QVJPQJG
- name: Upheaval
  tag: PLL2LJQ2
- name: 102% Canadian
  tag: LGCYVUCJ
- name: 99.9%Stressfree
  tag: Y2L9QY08
- name: The Immortals
  tag: 2QU092
sort: trophy
```

**Comment by smlbiobot** [comment]
```yml
name: 101% Canadian Clan Family
key: canadian
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/canadian.png
  description: >
    101% Canadian is Canada's **premier Clan Wars Clan**. Us, along with our family
    of clans strive to provide a positive, competitive,
    fun and quality Clash Royale experience, while focusing on Clan Wars.
  social:
  - discord: discord.gg/pttBsyqYH7
clans:
- name: 101% Canadian
  tag: 9UCRJG8V
- name: 99.9% Canadian
  tag: 2QVJPQJG
- name: Upheaval
  tag: PLL2LJQ2
- name: 102% Canadian
  tag: LGCYVUCJ
- name: 99.9%Stressfree
  tag: Y2L9QY08
- name: The Immortals
  tag: 2QU092
sort: trophy
```
