### ISSUE TITLE
Aliança Lusa Family

### ISSUE THREAD

**Issue by cubernix** [RoyaleAPI/family-config#839]
Aliança Lusa Clan Family

https://royaleapi.com/clan/family/aliancalusa

aliancalusa.yml

```yaml
name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_02
info:
  logo: https://ibb.co/Kh801VZ
  description: >
A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022 e secundário a 21/10/2022, está já no TOP15 do Ranking de Portugal no que toca a troféus. Somos também clã ativo de guerra, com Discord, grupo no whatsapp e com constantes Torneios Internos! ATREVE-TE! The Aliança Lusa Family, whose main clan was created on 09/18/2022 and secondary on 10/21/2022, is already in the TOP15 of the Portugal Ranking when it comes to trophies. We are also an active war clan, with a Discord server, WhatsApp group, and frequent internal tournaments! DARE TO JOIN US! 
clans:
  - name: Aliança Lusa
    tag: Q0R08YLJ
  - name: Aliança Lusa 2
    tag: Q20GUCV8
 ```

**Comment by smlbiobot** [comment]
```yml
name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_02
info:
  logo: /static/img/brands/logo/aliancalusa.png
  description: >
    A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022 e secundário a 21/10/2022, está já no TOP15 do Ranking de Portugal no que toca a troféus. Somos também clã ativo de guerra, com Discord, grupo no whatsapp e com constantes Torneios Internos! ATREVE-TE! The Aliança Lusa Family, whose main clan was created on 09/18/2022 and secondary on 10/21/2022, is already in the TOP15 of the Portugal Ranking when it comes to trophies. We are also an active war clan, with a Discord server, WhatsApp group, and frequent internal tournaments! DARE TO JOIN US!
clans:
  - name: Aliança Lusa
    tag: Q0R08YLJ
  - name: Aliança Lusa 2
    tag: Q20GUCV8
```
