### ISSUE TITLE
[UPDATE - ONE CLAN ADDED TO THE FAMILY] - Fedeltà Family

### ISSUE THREAD

**Issue by Fedelta** [RoyaleAPI/family-config#84]
name: Fedeltà Family
key: fedeltà

clans:
   - name: Fedeltà♡
     tag: RLPCRY
   - name: Fedeltà♡ Alpha
     tag: 9CGG02RR  
   - name: Fedeltà♡ Beta
     tag: P0VL8J92
  - name: Fedeltà♡ Gamma
     tag: PVJUPGQQ
  - name: Fedeltà♡ Delta
     tag: Y2GUJORQ

**Comment by smlbiobot** [comment]
- can’t use accents for keys

```yml
name: Fedeltà Family
key: Fedelta
color: red
emblem: Star_Shine_03
info:
  logo: /static/img/brands/logo/fedelta.png
  description: >
    The Fedeltà Family is a big group of players, in which the human component is fundamental. Our goal is to create an always bigger group of people that love the game and that respect each other, in order to create a healthy and constructive atmosphere. No matter in which of Our clan You are, Our goal is to become better and better both on clan trophies and in war trophies, through the "helping each other" system and the respect of the clan's rules. So what are You waiting, come and join Us!
  social:
clans:
  - name: Fedeltà♡
    tag: RLPCRY
  - name: Fedeltà♡ Alpha
    tag: 9CGG02RR
  - name: Fedeltà♡ Beta
    tag: P0VL8J92
  - name: Fedeltà♡ Gamma
    tag: PVJUPGQQ
  - name: Fedeltà♡ Delta
    tag: Y2GUJORQ
```
