### ISSUE TITLE
MAGIC FORCE CLAN

### ISSUE THREAD

**Issue by ARREGUIN1997** [RoyaleAPI/family-config#840]
```yaml
name: MAGIC FORCE FAMILY
key: magicforce
color: naranja
emblem: Traditional_Star_04
info:
  logo: ![MAGICFORCE](https://user-images.githubusercontent.com/125780102/219915741-32bd731a-6246-4093-bb99-0d33d5695353.)

  description: >
    (MFF) Por su siglas en ingles MAGIC FORCE FAMILY, un clan solido y perseverante de habla hispana fundado por ZELLO ROYALE en Enero del 2023. El concepto (MAGIC FORCE) o en español FUERZA MAGICA Proviene del mundo ficticio y a su vez mágico de Clash Royale agregando la fuerza conseguida en unión, como la fuerza que ejerce un clan, una familia!. 


    Add new line with 2 line breaks as above.
  social:
    - facebook: https://www.facebook.com/MagicForceClanOficial/
   
clans:
  - name: MAGIC FORCE
    tag: Q9CL988G
…
```
