### ISSUE TITLE
Family Clan Update

### ISSUE THREAD

**Issue by RagnarLothbrok77** [RoyaleAPI/family-config#842]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Némésis Quebec Clan Family
key: nemesisquebec
color: black
emblem: flag_j_03
info:
  logo: /static/img/badge/bronze-1/flag_j_03.png
  description: >
    Bienvenue dans la famille Némésis Québec!
    Nous avons un total de 8 clans qui ont tous comme objectif principal la guerre.
    En plus d'offrir des récompenses en argent pour nos 2 premiers clans, nous organisons plusieurs tournois et ligues internes.
    Si vous désirez faire partie de notre grande famille, je vous invite à rejoindre notre discord: 6YQBfbaYYw
    
    Welcome in the Némésis Quebec Clan Family!
    We have a total of 8 clans with all the same objective, which is war total domination.
    In addition to offering cash rewards for our first 2 clans, we run several internal leagues and tournaments. 
    If you want to be part of our big family, I invite you to join our discord: 6YQBfbaYYw
    
  social:
    - discord: http://discord.gg/6YQBfbaYYw

  clans:
   - name: Némésis Quebec
      tag: YU0JV9QV
   - name: Némésis Qc2
      tag: YQURV2CR
   - name: CHAMPIONS 3.0
      tag: 28UVG00Y
   - name: Némésis Qc3
      tag: YLGV9LGL
   - name: #Awesomesauce
      tag: R2QLR8
   - name: Némésis Qc4
      tag: LQLCVQVC
   - name: Némésis Qc5
      tag: QPJUC2RJ
   - name: Némésis QC6
      tag: G20PYV8V

```
