### ISSUE TITLE
CHPS Clan

### ISSUE THREAD

**Issue by rchan98** [RoyaleAPI/family-config#843]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: CHPS Clan Family
key: chps
color: red
emblem: Skull_06
info:
  description: >
    Welcome to CHPS Clan Family! 
clans:
  - name: CHPS Clan
    tag: 2GCQP82Q
  - name: CC#青龍
    tag: QGR2L2JC
  - name: CC#朱雀
    tag: QP0Y9CUU
  - name: CC#玄武
    tag: QUVR0GJJ
  ```
