### ISSUE TITLE
Nova QC

### ISSUE THREAD

**Issue by NovaQc** [RoyaleAPI/family-config#844]
```yaml
name: Nova QC
key: nova-qc
color: blue
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/nova-qc.png
  description: >
    Axée sur les GDC (TOP MONDE), Nova QC est constituée de 33 clans pour tous les niveaux.
    1500 membres actifs et unis contribuent à la croissance constante de cette grande famille.
    Respect, entraide et plaisir garantis! Facebook/Messenger/Discord.


    Focused on Clan Wars (TOP WORLD), Nova QC is made up of 33 clans for all levels.
    1500 active and united members contribute to the constant growth of this large familly.
    Respect, help among members and fun guaranteed! Facebook/Messenger/Discord.
  social:
    - discord: https://discord.gg/J66DCmhR
    - facebook: https://www.facebook.com/groups/546237565896704
clans:
  - name: Nova QC
    tag: 8J9YU9CC
  - name: Nova QC ☆ École
    tag: PPJQQ8YJ
  - name: Nova QC ☆ 3
    tag: LPL282UQ
  - name: Nova QC ☆ 4
    tag: Y2V29L8L
  - name: Nova QC ☆ 5
    tag: YV0YLUGL
  - name: Nova QC ☆ 6
    tag: Q20UYLG9
  - name: Nova QC ☆ 7
    tag: LCQJRP2Q
  - name: Nova QC ☆ 8
    tag: QP8G8LLR
  - name: Nova QC ☆ 9
    tag: G0GVRCR8
  - name: Nova QC ☆ 10
    tag: LUQP0UG8
  - name: Nova QC ☆ 11
    tag: Q2ULYQRY
  - name: Nova QC ☆ 12
    tag: QJCJ989C
  - name: Nova QC ☆ 13
    tag: QJ2R229R
  - name: Nova QC ☆ 14
    tag: GJ9L9VJQ
  - name: Nova QC ☆ 15
    tag: QLJ00U8V
  - name: Nova QC ☆ 16
    tag: QC02V2VP
  - name: Nova QC ☆ 17
    tag: GQJVV0RL
  - name: Nova QC ☆ 18
    tag: GJYQ9PCU
  - name: Nova QC ☆ 19
    tag: Q2LPURYR
  - name: Nova QC ☆ 20
    tag: Q08CJR0G
  - name: Nova QC ☆ 21
    tag: QJ9RPLGQ
  - name: Nova QC ☆ 22
    tag: GQUVJQJ0
  - name: Nova QC ☆ 23
    tag: Q99V0JV9
  - name: Nova QC ☆ 24
    tag: Q808JUJ0
  - name: Nova QC ☆ 25
    tag: GU8VUQCG
  - name: Nova QC ☆ 26
    tag: GRR80Y2R
  - name: Nova QC ☆ 27
    tag: Q898JQVJ
  - name: Nova QC ☆ 28
    tag: GQLLULCP
  - name: Nova QC ☆ 29
    tag: QV22QRRC
  - name: Nova QC ☆ 30
    tag: Q890PGQC
  - name: Nova QC ☆ 31
    tag: Q88CCGRJ
  - name: Nova QC ☆ 32
    tag: QGCRJRLY
  - name: Nova QC ☆ Libre
    tag: Q02RJLYR
```

Thank you!
