### ISSUE TITLE
Addicted Family Configuration

### ISSUE THREAD

**Issue by apeck14** [RoyaleAPI/family-config#846]
```yaml
name: Addicted Family
key: afam
color: purple
emblem: Bamboo_04
info:
  logo: https://i.imgur.com/WJA7eJZ.png
  description: >
    ##### The #1 U.S. War Clan in history!
    **U.S. Colosseum Record Holders: 167,550**
    Our family is comprised of 7 highly competitive and engaging war clans. We take pride in winning, and strive to continuously serve our members as best we can. Our Discord community is unparalleled: constant activity, $$ tournaments, deck help from top-tier players, memes, and more. Apply in-game or via Discord to join us!
  social:
    - discord: http://discord.gg/aFWbQKyc7R
    - youtube: https://www.youtube.com/@theaddictedones
clans:
  - name: TheAddictedOnes
    tag: 9U82JJ0Y 
  - name: Clash of Clams
    tag: V2GQU
  - name: AddictedChill
    tag: P0C90LCL
  - name: AddictedIII
    tag: 9UP00V8Q
  - name: AddictedPanda
    tag: PJQRLQPQ
  - name: addictedfamhero
    tag: PLLOULOR
  - name: Clash of Clamz
    tag: QYVJGVV2
```
