### ISSUE TITLE
3д-шники

### ISSUE THREAD

**Issue by APTEM7** [RoyaleAPI/family-config#847]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 3д-шники
key: 3д-шники
color: blue
emblem: flag_e_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
   Сім'я кланів 3д-шники – це сім'я українських кланів які прагнуть стати кращими в Україні та світі.  Перший головний клан був створений 14.09.2020 р. , але вже давно знаходиться в легендарній лізі. А все тому, що в клані зібралися дуже гарні гравці  Clash Royale і ми завжди перші в війні! Українці завжди перемагають! Слава Україні!
    The family of clans 3D-Skrillers is a family of Ukrainian clans that strive to become the best in Ukraine and the world.  The first main clan was created on 09/14/2020, but has long been in the legendary league. And all because the clan has gathered very good Clash Royale players and we are always the first in the war! Ukrainians always win! Glory to Ukraine!
  social:
clans:
  - name: 3д-шники
    tag: L8CY0L2C
  - name: 3д-шники #2
    tag: YJR9R809
  - name: 3д-шники #3
    tag: YJP9CPLP
```
