### ISSUE TITLE
Add Arcanum CR Family

### ISSUE THREAD

**Issue by isaacmg00** [RoyaleAPI/family-config#85]
```yaml
name: Arcanum
key: arcanum
color: purple
emblem: Elixir_02
sort: trophy
info:
  logo: https://cdn.discordapp.com/icons/451193103748038666/da9020e9488655f70486036527c3eed3.webp?%22
  description: >
    We are a competitive ladder and war clan system that strives to ascend the leaderboard.
    We are all friends and treat each other like family. If you're looking for an active player
    base that can help you become a better player this is the place for you.
  social:
  - discord: https://discord.gg/tNzDsfa
  - twitter: https://twitter.com/arcanumcr
clans:
- name: Arcanum
  tag: GCRV2
- name: Arcanum NA
  tag: 9Q98LLP8
- name: Arcanum 2
  tag: 90QGG2Q9
- name: Arcanum NA 2
  tag: 92R8QVL2
- name: Arcanum NA 3
  tag: 9LQRL8RV
- name: Arcanum NA 4
  tag: P8C99VV9
- name: Arcanum 3
  tag: P2GJQP89
- name: Arcanum NA 5
  tag: 9CP2RL9P
```

**Comment by smlbiobot** [comment]
- can’t use webp for images. webp won’t show up on iOS devices. Converted to PNG.

```yml
name: Arcanum
key: arcanum
color: purple
emblem: Elixir_02
sort: trophy
info:
  logo: /static/img/brands/logo/arcanum.png
  description: >
    We are a competitive ladder and war clan system that strives to ascend the leaderboard.
    We are all friends and treat each other like family. If you're looking for an active player
    base that can help you become a better player this is the place for you.
  social:
    - discord: https://discord.gg/tNzDsfa
    - twitter: https://twitter.com/arcanumcr
clans:
  - name: Arcanum
    tag: GCRV2
  - name: Arcanum NA
    tag: 9Q98LLP8
  - name: Arcanum 2
    tag: 90QGG2Q9
  - name: Arcanum NA 2
    tag: 92R8QVL2
  - name: Arcanum NA 3
    tag: 9LQRL8RV
  - name: Arcanum NA 4
    tag: P8C99VV9
  - name: Arcanum 3
    tag: P2GJQP89
  - name: Arcanum NA 5
    tag: 9CP2RL9P
```
