### ISSUE TITLE
Add Apéro?! Family clans

### ISSUE THREAD

**Issue by Jaws3m** [RoyaleAPI/family-config#851]
```yaml
name: Apéro?! Family
key: apero
color: blue
emblem: flag_k_01
info:
  logo: https://cdn.discordapp.com/attachments/1019904556466978860/1082979310052323358/logoVF5.png
  description: >
    Pour ceux qui aiment l'Apéro et ont l'âge de le boire
    Famille de 4 clans
    Ouvert à tous ceux qui veulent jouer la guerre à fond dans un esprit soudé, compétitif et bienveillant
    Axé sur l'entraide, l'engagement et fidélité dans le clan, Apéro mise sur Les joueurs - leur envie de progresser plus que sur le palmarès
    Rejoignez l'Apéro Family !
  social:
    - discord: https://discord.gg/SGrFqACAER
clans:
  - name: Apéro ?!
    tag: YLJCRY2
  - name: Actif Royale 68
    tag: 9YRCVRGG
  - name: Rebellion
    tag: YY8JVGGG
  - name: Bordeaux Royal
    tag: 88Q09C
```
