### ISSUE TITLE
#GUARDS Family

### ISSUE THREAD

**Issue by aZekea** [RoyaleAPI/family-config#852]
```yaml
name: 0 GUARDS Family - Семья ГВАРДИЙ 0
key:  guards
color: red
emblem: flag_j_03.png
info:
logo: https://i.ibb.co/qCrsd3s/Pngegg-1.png
  description: >
    **Семья ГВАРДИЙ** Кланы с приятной атмосферой. Сплоченный, дружный коллектив. Грамотное ведение клановых войн. 100+ участников в телеграмм-чате.  **▼▼ВСТУПАЙ прямо сейчас!▼▼** 
  social:
   - telegram: https://t.me/al90808
   - discord: https://discord.gg/aFN5UWuvmE
clans:
  - name: Белая Гвардия
    tag: YUV2Y2R
  - name: Темная Гвардия
    tag: QRJ8LJC9
  - name: Красная Гвардия
    tag: QV9U0LGV
  - name: Светлая Гвардия
    tag: Q8Y99YR0
```
