### ISSUE TITLE
Alpenkommando

### ISSUE THREAD

**Issue by TwitchViruxcrew** [RoyaleAPI/family-config#854]
name: Alpenkommando Family
key: Alpenkommando
color: white
emblem: Skull_06
info:
  logo: https://dkfdf.px.media/media/overview/file/38
  description: >
    We are a strong War based Clan familiy in Austria. We offer War Clans for everyone. Trophies doesnt matter. We got our own discord server with lots of members in it.
    Also we have regular tournaments and much more. So what are you waiting for. Join Now !!
  social:
    - discord: https://discord.gg/jxH4RNMwwc
clans:
  - name: Alpenkommando
    tag: LGP0G8
  - name: Alpenkommando 2
    tag: P8CGCYV2
  - name: Alpenkommando 3
    tag: L0RYG02U
  - name: Alpenkommando 4
    tag: GGCVYG09
  - name: gelber blitz
    tag: QCPCJ9Y0
[Alpenkommando Familie.txt](https://github.com/RoyaleAPI/family-config/files/10982666/Alpenkommando.Familie.txt)

**Comment by smlbiobot** [comment]
```yml
name: Alpenkommando Family
key: alpenkommando
color: white
emblem: Skull_06
info:
  logo: /static/img/brands/logo/alpenkommando.png
  description: >
   Wir sind eine starke Clankriegsorientierte Familie aus Österreich. Wir haben für jeden Spieler einen Clan ob Anfänger oder Erfahren spielt keine Rolle. Wir bieten außerdem einen aktiven discord server und regelmäßige Clanturniere.
  social:
    - discord: https://discord.gg/jxH4RNMwwc
clans:
  - name: Alpenkommando
    tag: LGP0G8
  - name: Alpenkommando 2
    tag: P8CGCYV2
  - name: Alpenkommando 3
    tag: L0RYG02U
  - name: Alpenkommando 4
    tag: GGCVYG09
  - name: gelber blitz
    tag: QCPCJ9Y0
```
