### ISSUE TITLE
Temptations Gaming Clan Family Request

### ISSUE THREAD

**Issue by TemptationsGaming** [RoyaleAPI/family-config#855]
```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```

**Comment by smlbiobot** [comment]
don}t send invalid yamls in the future.

```yml
name: Temptations Gaming Clan Family
key: tmpgaming
color: black
emblem: A_Char_Pekka_01
info:
  logo: /static/img/brands/logo/temptations.png
  description: Official Temptations Gaming Clan Family, Join our discord to apply!
  social:
    - twitter: https://twitter.com/@tmpgaming11
    - discord: https://discord.gg/VFR4Rh2tM9
clans:
  - name: Tickle My Pekka
    tag: G2Y9JP8Q
  - name: Pathogen X
    tag: LCCYG0CQ
  - name: 2 ラダーキラー
    tag: Q2VVCU0J
  - name: I NORRENI
    tag: L9QCGY28
  - name: Elixir Cult
    tag: Q2C00GJY

```
