### ISSUE TITLE
Andromeda Descendants application RAPI

### ISSUE THREAD

**Issue by MarceloBRC** [RoyaleAPI/family-config#862]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Andromeda Descendants
key: Andromeda-Descendants
color: black
emblem: Star_Shine_02
info: We are a strong family comprised mostly of 4k and 5k clans. We focus on clan wars, tournaments and FUN! 
So if you want to be in a highly competitive setting and meet some of the best players the community has to show, I invite you to come to our discord page to say hi and maybe find yourself a spot in one of our clans.
  logo: https://drive.google.com/file/d/1fySCwFDMuUN1knavCNd8D8yY_SY9IQMI/view?usp=share_link
  description: >
   We are a strong family comprised mostly of 4k and 5k clans. We focus on clan wars, tournaments and FUN! 
   So if you want to be in a highly competitive setting and meet some of the best players the community has to show, I invite you to come to our discord page to say hi and maybe find yourself a spot in one of our clans. You can apply via Discord!


  social:
   
    - discord: http://discord.gg/umgRhbG8G4
 
clans:
  - name: Elixir Elites
    tag: PP00JCRV
  - name: Divine Wind
    tag: 2CJY2008
  - name: Hawaiian Beast
    tag: P2RPJQ9R
  - name: Avenging Souls
    tag: PCPGLYY0
  - name: Thunder Harbor
    tag: YRGJ0QYV
  - name: DulcedeLeche
    tag: Y099P8GU
  - name: Elixir Empire
    tag: LUQY2JPY   
  - name: Avenging II
    tag: QUQR8Q90 
  - name: AD Tourneys
    tag: #QVQ0CJUC
```

**Comment by smlbiobot** [comment]
```yml
name: Andromeda Descendants
key: andromeda-descendants
color: black
emblem: Star_Shine_02
info:
  logo: /static/img/brands/logo/andromeda-descendants.png
  description: >
    We are a strong family comprised mostly of 4k and 5k clans. We focus on clan wars, tournaments and FUN! 
    So if you want to be in a highly competitive setting and meet some of the best players the community has to show, I invite you to come to our discord page to say hi and maybe find yourself a spot in one of our clans. You can apply via Discord!


  social:
    - discord: http://discord.gg/umgRhbG8G4

clans:
  - name: Elixir Elites
    tag: PP00JCRV
  - name: Divine Wind
    tag: 2CJY2008
  - name: Hawaiian Beast
    tag: P2RPJQ9R
  - name: Avenging Souls
    tag: PCPGLYY0
  - name: Thunder Harbor
    tag: YRGJ0QYV
  - name: DulcedeLeche
    tag: Y099P8GU
  - name: Elixir Empire
    tag: LUQY2JPY
  - name: Avenging II
    tag: QUQR8Q90
  - name: AD Tourneys
    tag: QVQ0CJUC
```
