### ISSUE TITLE
AriZona Family

### ISSUE THREAD

**Issue by XtremeSanti** [RoyaleAPI/family-config#863]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: AriZona Family
key: AriZona
color: black
emblem: cherry_blossom_01
info: 
  logo: ![](https://cutewallpaper.org/24/arizona-iced-tea-png/arizona-iced-tea-logo-png-arizona-tea-logo-png-clipart-1429600-pikpng.png)

  description: >

Welcome, to the AriZona Family! Come join us! We are We are a fun, active, semi-competitive clans. We all share a fellow passion for the game, are friendly, always donate, help each other out with the same goal: to always improve our skills and have a great time!

clans:
  - name: AriZona
    tag: LCRLVOU9
  - name: AriZona [2]
    tag: QR9CVURQ
```
