### ISSUE TITLE
Famille Gauloise !

### ISSUE THREAD

**Issue by MiniTheKing** [RoyaleAPI/family-config#865]
```yaml
name: Famille Gauloise !
key: famillegauloise
color: dark
emblem: A_Char_Barbarian_03
info:
     logo: https://discord.com/channels/929108970520596540/929125874878541904/1092887388272988241
     description: >
        La **FAMILLE GAULOISE !** est l'une des plus grande communauté francophone du jeu avec nos 10 clans. 
        Entre clan familial, bonne ambiance mais aussi un peu de tryhard, on se retrouve tous ensemble 
        pour jouer et progresser sur le jeu ! Pas moins de 500 membres nous ont déjà 
        rejoints pour faire partie de notre Grande Famille !
        Avec pas moins de 7 de nos 10 clans en Legendaire 2 en GDC, nous sommes la communauté française 
        la plus équilibré sur ce mode du jeu avec tous nos clans actifs et disponible pour tous ! 
        Ensemble, progressons vers la victoire et continuons de nous éclater !!!
     social:
    - discord : http://discord.gg/48MSRy4Xcw
clans:
    - clan: 100% Gaulois! 
    tag: 9VYCYPU2
    - clan: 200% gaulois!!!
    tag: PJRRPRGC
    - clan: 300% Gaulois!!!
    tag: Y89Q0YY2 
    - clan: 400% gaulois!!!
    tag: GRQUQCJJ
    - clan: 500% Gaulois!!!
    tag: PVLJV9Q0
    - clan: 600% gaulois 
    tag: YLJG2YQY
    - clan: 700% gaulois 
    tag: PUQ0C8RV
    - clan: 800% gaulois
    tag: LYQQLV2C
    - clan: 900% Gaulois!!!
    tag: QV2GR82G
    - clan: 1000% GAULOIS
    tag: L9JRGJVQ
```

**Comment by smlbiobot** [comment]
invalid logo link

**Comment by smlbiobot** [comment]
note spelling of fields please. these are for the machines. 

```yml
name: Famille Gauloise !
key: famillegauloise
color: dark
emblem: A_Char_Barbarian_03
info:
  logo:
  description: >
    La **FAMILLE GAULOISE !** est l'une des plus grande communauté francophone du jeu avec nos 10 clans. 
    Entre clan familial, bonne ambiance mais aussi un peu de tryhard, on se retrouve tous ensemble 
    pour jouer et progresser sur le jeu ! Pas moins de 500 membres nous ont déjà 
    rejoints pour faire partie de notre Grande Famille !
    Avec pas moins de 7 de nos 10 clans en Legendaire 2 en GDC, nous sommes la communauté française 
    la plus équilibré sur ce mode du jeu avec tous nos clans actifs et disponible pour tous ! 
    Ensemble, progressons vers la victoire et continuons de nous éclater !!!
  social:
  - discord : https://discord.gg/48MSRy4Xcw
clans:
  - name: 100% Gaulois! 
    tag: 9VYCYPU2
  - name: 200% gaulois!!!
    tag: PJRRPRGC
  - name: 300% Gaulois!!!
    tag: Y89Q0YY2 
  - name: 400% gaulois!!!
    tag: GRQUQCJJ
  - name: 500% Gaulois!!!
    tag: PVLJV9Q0
  - name: 600% gaulois 
    tag: YLJG2YQY
  - name: 700% gaulois 
    tag: PUQ0C8RV
  - name: 800% gaulois
    tag: LYQQLV2C
  - name: 900% Gaulois!!!
    tag: QV2GR82G
  - name: 1000% GAULOIS
    tag: L9JRGJVQ
```
