### ISSUE TITLE
CaniRozzi 

### ISSUE THREAD

**Issue by Shudoh85** [RoyaleAPI/family-config#867]
... yaml
Name: Famiglia cani rozzi
Key: cani rozzi
Color: purple
Emblem: skull_06
Info:
Logo: https://postimg.cc/wyYCJSGR
Description: >
    Cagnacci since 2018 - Rozzi since 2019
    Unione di due grandi famiglie dopo il furto e l'espulsione di tutti i fondatori dell'Armata Rozza.
    *Dog Rider* clan principale competitivo in war
    *PesciolinoRozzo* accademia
    *PettiRozzo*  clan per inattivi temporanei in war e secondi/terzi account per le coperture
    
    
Social:
- Telegram: https://t.me/armatarozza
Clans:
- name: Dog Rider
tag: RP889JU
- name: PesciolinoRozzo
tag: LQCPJLC0
- name: PettiRozzo
tag: Q0L29QVL
...

**Comment by smlbiobot** [comment]
please follow correct structure

```yml
name: Famiglia cani rozzi
key: cani-rozzi
color: purple
emblem: skull_06
info:
  logo: /static/img/brands/logo/cani-rozzi.png
  description: >
      Cagnacci since 2018 - Rozzi since 2019
      Unione di due grandi famiglie dopo il furto e l'espulsione di tutti i fondatori dell'Armata Rozza.
      *Dog Rider* clan principale competitivo in war
      *PesciolinoRozzo* accademia
      *PettiRozzo*  clan per inattivi temporanei in war e secondi/terzi account per le coperture
      

  social:
  - telegram: https://t.me/armatarozza
clans:
- name: Dog Rider
  tag: RP889JU
- name: PesciolinoRozzo
  tag: LQCPJLC0
- name: PettiRozzo
  tag: Q0L29QVL
```
don’t captilize fields etc.
