### ISSUE TITLE
Temptations Gaming Clan Family Edit Request

### ISSUE THREAD

**Issue by TemptationsGaming** [RoyaleAPI/family-config#868]
```yaml
name: Temptations Gaming
key: temptationsgaming
color: Black
emblem: A_Char_Pekka_01
info: 
  logo: https://share.creavite.co/5Iyu2S0B2wTFQNJd.png
  description: > Top NA Ladder and War Clan Family! Active, Chill, and More! Check out our Discord to Apply!
 


  social:
    - twitter: http://twitter.com/@TPgamingGG
    - discord: https://discord.gg/f6kAryRMSp
 
clans:
  - name: Tickle My Pekka
    tag: G2Y9JP8Q
  - name: Pathogen X
    tag: LCCYG0CQ 
  - name: 2 ラダーキラー
    tag: Q2VVCU0J
  - name: I NORRENI
    tag: L9QCGY28
  - name: Elixir Cult
    tag: #Q2C00GJY
  - name: OiaForce 
    tag: YGL28JPV
  - name: NorCal™️
    tag: L0LP0RCQ
  - name: D¹—VISION
    tag: P9CQL99
  - name: TopUnited™️
    tag: Q0C22RYL
  -name: Acid Snowfall
    tag: 2YRVGQ
```

**Comment by smlbiobot** [comment]
your twitter account does not exist

**Comment by smlbiobot** [comment]
fixed this for you but please input correct data

```yml
name: Temptations Gaming Clan Family
key: tmpgaming
color: black
emblem: A_Char_Pekka_01
info:
  logo: /static/img/brands/logo/tmpgaming.png
  description: Top NA Ladder and War Clan Family! Active, Chill, and More! Check out our Discord to Apply!
  social:
  - twitter: https://twitter.com/TGesportsOP
  - discord: https://discord.gg/f6kAryRMSp
clans:
  - name: Tickle My Pekka
    tag: G2Y9JP8Q
  - name: Pathogen X
    tag: LCCYG0CQ 
  - name: 2 ラダーキラー
    tag: Q2VVCU0J
  - name: I NORRENI
    tag: L9QCGY28
  - name: Elixir Cult
    tag: Q2C00GJY
  - name: OiaForce 
    tag: YGL28JPV
  - name: NorCal™️
    tag: L0LP0RCQ
  - name: D¹—VISION
    tag: P9CQL99
  - name: TopUnited™️
    tag: Q0C22RYL
  - name: Acid Snowfall
    tag: 2YRVGQ
```
