### ISSUE TITLE
FFR-Reborn

### ISSUE THREAD

**Issue by Wild0it** [RoyaleAPI/family-config#869]
name: FFR-Reborn
key: auron1st
color: Red
emblem: https://cdn.discordapp.com/attachments/1044248464579641364/1094998908930883646/logoauron.png
info:
  logo: Lotus_02
  description: Famille de clans axés sur la Guerre. Rejoint nos rangs, grandit au seins d'une famille que tu feras avancer et qui te le rendra. 
"Quand la neige tombe et que les vents glacés soufflent, le loup solitaire meurt, mais la meute survit." 
⚔️Bienvenue dans la meute ! ⚔️

  social:
    - discord: https://discord.gg/M5GnqEyYx2
    - twitter: https://twitter.com/auron1st
    - youtube: https://www.youtube.com/channel/UCY52ItNfzBe4vF_ptCK_9QQ
    - tiktok: [http://tiktok.com/@wildocr](https://t.co/KNMzXInihX)
    
clans:
  - name: FFR-Auron
    tag: PCY8LQP2
  - name: FFR-Wakka
    tag: PJGRRRUC
  - name: FFR-Lumina
    tag: YULGVGGQ
  - name: FFR-Rikku
    tag: PYP9Y0J2

**Comment by Wild0it** [comment]
We were in an old family but we separated, so I’d like our clans to be listed in a new flat family and more in the old one, thank

**Comment by smlbiobot** [comment]
```yml
name: FFR-Reborn
key: auron1st
color: red
emblem: Lotus_02
info:
  logo: /static/img/brands/logo/logoauron.png
  description: >
    Famille de clans axés sur la Guerre. Rejoint nos rangs, grandit au seins d'une famille que tu feras avancer et qui te le rendra. 
    "Quand la neige tombe et que les vents glacés soufflent, le loup solitaire meurt, mais la meute survit." 
    ⚔️Bienvenue dans la meute ! ⚔️

  social:
    - discord: https://discord.gg/M5GnqEyYx2
    - twitter: https://twitter.com/auron1st
    - youtube: https://www.youtube.com/channel/UCY52ItNfzBe4vF_ptCK_9QQ
    - tiktok: https://tiktok.com/@wildocr

clans:
  - name: FFR-Auron
    tag: PCY8LQP2
  - name: FFR-Wakka
    tag: PJGRRRUC
  - name: FFR-Lumina
    tag: YULGVGGQ
  - name: FFR-Rikku
    tag: PYP9Y0J2
```
