### ISSUE TITLE
Guilds Family

### ISSUE THREAD

**Issue by pallebone** [RoyaleAPI/family-config#87]
```yaml
name: Clash Royale Guilds
key: Guilds
color: blue
emblem: A_Char_Goblin_01
info:
  logo:
  description: >
The official guilds family of Clash Royale, is clan family dedicated to helping players become competative in leagues. We have a lower ranked clan (Mages Guild) where we teach new players and our main competative guild (Thieves Guild) where we steal your cups! We also have a 1v1 guild for 1v1 accounts.
  social:
    - discord: https://discord.gg/4CVwVgd
clans:
  - name: TheThievesGuild
    tag: 9YJ89P9C
  - name: TheMagesGuild
    tag: Y29982G8
  - name: LVL1
    tag: PQPUG9OU
```
