### ISSUE TITLE
Update our Clan Family

### ISSUE THREAD

**Issue by IndyCA** [RoyaleAPI/family-config#870]
Hi, i am CL from Czech Active and we need to add a new clan to our Czech Active Family. I added a new clan to the configuration file that i am attaching below. Thx.
 
```yaml
name: Czech Active Family
key: CA
color: Blue
emblem: Star_Shine_02.png
info:
  logo:
  description: >
    Společenství klanů Czech Active (1-17). Přidej se k nám, 
jsme aktivní komunita a nejrychleji se rozšiřující klan v ČR. 
Klany máme napříč všemi ligami a určitě se tu pro tebe najde místo.

  social:
    - twitter: http://twitter.com/CzechActive
    - discord: http://discord.gg/invite/Zz6s3AC
    - twitch: https://www.twitch.tv/mcslina
    - website: http://czechactive.blogspot.cz/
    - facebook: https://facebook.com/czechactive

clans:
 - name: Czech Active
    tag: 8CL9LCPJ
 - name: CA akademie
    tag: Q9PLL9PV
 - name: Czech Active 1
    tag: 88PC8QJ8
 - name: Czech Active 2
    tag: 8CVVPVQJ
 - name: Czech Active 3
    tag: 8CVGPL2G
 - name: Czech Active 4
    tag: 8RQQ908C
 - name: Czech Active 5
    tag: 8PGPQJ8R
 - name: Czech Active 6
    tag: 890ULG29
 - name: Czech Active 7
    tag: 9U00RLGL
 - name: Czech Active 8
    tag: 8UGJJU9Y
 - name: Czech Active 9
    tag: 8UR2YGRC
 - name: Czech Active 10
    tag: 8JL8PGPR
 - name: Czech Active 11
    tag: 8UVVQ29C
 - name: CzechActive11.2
    tag: 9PJGPRC8
 - name: Czech Active 12
    tag: 92CCQYPY
 - name: Czech Active 13
    tag: 89RP298V
 - name: Czech Active 14
    tag: 90Y9URC8
 - name: Czech Active 15
    tag: 8L0QPJJV
 - name: Czech Active 16
    tag: 99YY2UL0
 - name: Czech Active 17
    tag: 98LYLCVU 
```

**Comment by smlbiobot** [comment]
please don’t add extra space before tag to line up the colons in the future. Space is important in programming and it breaks everything.

```yml
name: Czech Active Family
key: CA
color: blue
emblem: Star_Shine_02
info:
  description: "Společenství klanů Czech Active (1-17). Přidej se k nám, jsme aktivní\
    \ komunita a nejrychleji se rozšiřující klan v ČR. Klany máme napříč všemi ligami\
    \ a určitě se tu pro tebe najde místo.\n"
social:
- twitter: https://twitter.com/CzechActive
- discord: https://discord.gg/invite/Zz6s3AC
- twitch: https://www.twitch.tv/mcslina
- website: https://czechactive.blogspot.cz/
- facebook: https://facebook.com/czechactive
clans:
 - name: Czech Active
   tag: 8CL9LCPJ
 - name: CA akademie
   tag: Q9PLL9PV
 - name: Czech Active 1
   tag: 88PC8QJ8
 - name: Czech Active 2
   tag: 8CVVPVQJ
 - name: Czech Active 3
   tag: 8CVGPL2G
 - name: Czech Active 4
   tag: 8RQQ908C
 - name: Czech Active 5
   tag: 8PGPQJ8R
 - name: Czech Active 6
   tag: 890ULG29
 - name: Czech Active 7
   tag: 9U00RLGL
 - name: Czech Active 8
   tag: 8UGJJU9Y
 - name: Czech Active 9
   tag: 8UR2YGRC
 - name: Czech Active 10
   tag: 8JL8PGPR
 - name: Czech Active 11
   tag: 8UVVQ29C
 - name: CzechActive11.2
   tag: 9PJGPRC8
 - name: Czech Active 12
   tag: 92CCQYPY
 - name: Czech Active 13
   tag: 89RP298V
 - name: Czech Active 14
   tag: 90Y9URC8
 - name: Czech Active 15
   tag: 8L0QPJJV
 - name: Czech Active 16
   tag: 99YY2UL0
 - name: Czech Active 17
   tag: 98LYLCVU 
```
