### ISSUE TITLE
India family update

### ISSUE THREAD

**Issue by legend84yt** [RoyaleAPI/family-config#871]
```yaml
name: INDIA
key: IND
color: Red
emblem: flag_n_06.png
info:
  logo: 
  description: >
    our clans main goal is to represent **INDIA** globally we have over 150 members and three clans. our clan provide training to the new members and help them to improve our clan since creation had been active so on.... join our clan to feel proud of yourself we gave some achievements like we ae already reached in top 40 in local leaderboards in ladder and top 300 in local leaderboards in clan wars
  social:
    - discord: https://discord.gg/hZYcfrsNhJ
    - YouTube: https://www.youtube.com/channel/UCxMPOPBQwF1AyAKZXDFNMeA
    - Instagram: https://www.instagram.com/yash8.4/
    - email: mailto: sarodeyash84@gmail.com
clans:
  - name: India
    tag: #LQ8VCCGJ
  - name: INDIAN ARMY
    tag: #LUVV9J20
  - name: Indians
    tag: #Q92CQU2Y
```

**Comment by legend84yt** [comment]
when will this get completed?

**Comment by smlbiobot** [comment]
don}t add hash to tags,fix stuff please

```yml
name: INDIA
key: IND
color: red
emblem: flag_n_06
info:
  logo: 
  description: >
    our clans main goal is to represent **INDIA** globally we have over 150 members and three clans. our clan provide training to the new members and help them to improve our clan since creation had been active so on.... join our clan to feel proud of yourself we gave some achievements like we ae already reached in top 40 in local leaderboards in ladder and top 300 in local leaderboards in clan wars
  social:
    - discord: https://discord.gg/hZYcfrsNhJ
    - YouTube: https://www.youtube.com/channel/UCxMPOPBQwF1AyAKZXDFNMeA
    - Instagram: https://www.instagram.com/yash8.4/
    - email: mailto:sarodeyash84@gmail.com
clans:
  - name: India
    tag: LQ8VCCGJ
  - name: INDIAN ARMY
    tag: LUVV9J20
  - name: Indians
    tag: Q92CQU2Y
```
