### ISSUE TITLE
[Update] LaTroncoFamiglia

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#872]
Thanks as usual for your great service! 💪🏼

```yaml

name: LaTroncoFamiglia
key: latronco
color: green
emblem: Bamboo_03
info:
  logo: /static/img/brands/logo/latronco-3.png
  description: >
    **LaTroncoFamiglia**, un insieme di clan in comunicazione tra loro per divertirsi in un ambiente tranquillo, no comportamenti infantili, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.

**D**opo anni abbiamo deciso di chiudere i nostri war clan per unirci alla famiglia Elites⚡️Royale e continuare insieme la nostra avventura!
**T**roncoradice e Troncopoli rimarranno aperte ma senza obbligo di war.

**C**omunichiamo le notizie più importanti sul canale Telegram, ma possiamo parlare tra di noi tramite il gruppo, qui sotto ci sono i link per entrare.

  social:
    - telegram: https://t.me/LaTroncoFamiglia
    - telegram: https://t.me/LaNuovaTronco

clans:
  - name: La Nuova Tronco
    tag: LVVQQ2L8
  - name: La Troncopoli
    tag: LYV0PGR9
  - name: La SuperTronco
    tag: L8YVLJG8
  - name: La Troncobase
    tag: QR9Y8028
  - name: La Troncoradice
    tag: YV2UJ0GV
  - name: La Troncoseme
    tag: QQLVQ20V

sort: trophy

```
