### ISSUE TITLE
BREIZH UNION

### ISSUE THREAD

**Issue by sergenthartman** [RoyaleAPI/family-config#873]
```yaml
name: BREIZH UNION
key: BREIZH
color: Black
emblem: Star_Shine_03
info:
  logo: https://zupimages.net/up/23/16/lvyr.jpeg
  description: >
    **La famille « BREIZH UNION » est une union  de clans, dont la prédilection première est la guerre de clan.**
    
    Notre **famille de 6 clans** est née de l’union principale de deux irréductibles clans Français: BREIZH, clan dans le top 10 Gdc en ligue légendaire 3, et tt elite, dans le top 100
    
    Ce rapprochement a permis de se développer d’avantage, de se solidifier, pour devenir l’une des plus grandes familles française ; **1 clan en légendaire 3, 3 clans en légendaire 2**

    **Nos 6 clans permettent à tous d’y trouver son compte, de la compétition, du fun, de l’entraide, des vieux briscards, des plus jeunes, le tout dans une très bonne ambiance, afin de devenir pourquoi pas, la plus importante famille dans le monde de Clash Royale.
    Rejoignez la famille BREIZH UNION**
  
  social:
    - discord: https://discord.gg/5n2rtysxrN

clans:
  - name: BREIZH
    tag: LGJYYP
  - name: tt elite
    tag: 82CGLUYL
  - name: Carpi
    tag: GVYL2J
  - name: «KLASH»
    tag: 8PPJJL88
  - name: BREIZH II
    tag: LJJQ9JCL
  - name: BREIZH III
    tag: GQGUC9R2
```
