### ISSUE TITLE
Woodland Clans

### ISSUE THREAD

**Issue by thomaskeig** [RoyaleAPI/family-config#874]
```yaml
name: Woodland
key: woodland
color: red
emblem: Pine_02
info:
  logo: https://media.discordapp.net/attachments/818205662332452956/1097947673660751995/WLUpdated.png
  description: 'The **Woodland Clans** are one of Sweden's most Dominant Top set of Clans since 2018! We are proud to have many of the Best Players in the Country call us their Home.'
  social:
    - discord: https://dsc.gg/woodland
clans:
  - name: 'Woodland'
    tag: 29Y2UL82
  - name: 'Woodland 2'
    tag: 2GQ90YLG
  - name: 'Woodland Academy'
    tag: L28CL2QU
```
