### ISSUE TITLE
Warriors & Soldiers

### ISSUE THREAD

**Issue by eabueno** [RoyaleAPI/family-config#875]
```yaml
name: Warriors & Soldiers
key: warriorsandsoldiers
color: brown
emblem: Skull_03
info:
  logo: https://encurtador.com.br/jsxAP
  description: >
    Fundada em Maio de 2020, a **Warriors & Soldiers** é uma família formada por 3 clãs com verdadeiros guerreiros e diferentes objetivos para todos os tipos de jogadores. O espírito de equipe, bravura e honra é a nossa inspiração. Lutamos com estratégia e coragem em todas as batalhas que enfrentamos, estamos sempre determinados a enfrentar desafios e conquistar troféus em batalhas épicas nas arenas.

    Se você é um player habilidoso e está em busca de uma equipe dedicada, venha se juntar a nós na Warriors & Soldiers ! Vamos lutar juntos em busca de glória, camaradagem e muita diversão nas batalhas. Prepare sua espada, ajuste sua armadura e vamos à batalha!

    
  social:
    - email: mailto: joseitalopaiares42@gmail.com
clans:
  - name: Brasil Warrior
    tag: LG8Y20Q8
  - name: Dark Soldiers
    tag: LLQCVPG9
  - name: Warrior Academy
    tag: Q90Q9U0C
```
