### ISSUE TITLE
WarriorsFaction Upate

### ISSUE THREAD

**Issue by WarriorsFaction** [RoyaleAPI/family-config#877]
```yaml
name: Warriors Faction
key: warriorsfaction
color: red
Emblem: star_shine_03
info:
  description: >
Warriors Faction is a family of elite war clans including 2 that rank at the top globally! Our clans have been dominating wars for many years and our players are passionate about war. Join our discord to be in the best clan family in the US!
  social:
    - discord: https://discord.gg/warriorsfaction
    - twitter: https://twitter.com/cr_warfaction
    - instagram: https://twitter.com/cr_warfaction
clans:
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: CRL eSports PRO
    tag: 9UV202Q2
  - name: BEWO Pro
    tag: YY89R8RG
  - name: Elite Assassins
    tag: 8QCRCU2L
  - name: Alpha Steel
    tag: 9PV9JL
  - name: No Clan
    tag: YC8CJV9G
  - name: Assert Dominance
    tag: P8028YL9
  - name: monkey mafia 2
    tag: 2CYLGU8R
  - name: False Logic V
    tag: CVRP2YQ
  - name: Rogue Kingdom
    tag: YVVC0JJU
  - name: PRO ERA
    tag: LYUL0Y2V
  - name: gladiators
    tag: LQJQUQ2G
  - name: MK 4PLaY
    tag: QQLJJ8YP
  - name: Mini Knights
    tag: GG8UJC29
  - name: CRL Tournaments
    tag: LYYC0GJY
```
