### ISSUE TITLE
Aliança Lusa - UPDATE - Add some changes on desceription, emblem and logo

### ISSUE THREAD

**Issue by cubernix** [RoyaleAPI/family-config#878]
Aliança Lusa Clan Family

https://royaleapi.com/clan/family/aliancalusa

aliancalusa.yml

name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_04
info:
logo: https://ibb.co/YBWYNcJ
description: >
A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022 e secundário a 21/10/2022, está já no TOP10 do Ranking de Portugal no que toca a troféus. Somos também clã ativo de guerra, com Discord, grupo no whatsapp e com constantes Torneios Internos, assim como um terceiro clã para férias! ATREVE-TE! The Aliança Lusa Family, whose main clan was created on 18/09/2022 and secondary on 21/10/2022, is already in the TOP10 of the Portugal Ranking when it comes to trophies. We are also an active war clan, with a Discord server, WhatsApp group, and frequent internal tournaments as well as a third clan for vacations! DARE TO JOIN US!

clans:
•	name: Aliança Lusa
tag: Q0R08YLJ
•	name: Aliança Lusa 2
tag: Q20GUCV8
•	name:: 『AL』3º Piso 金
tag: GQUYQQ0

**Comment by smlbiobot** [comment]
use YML. gave me the wrong tag.

```yml
name: Aliança Lusa Family
key: aliancalusa
color: red
emblem: Arrow_04
info:
  logo: /static/img/brands/logo/aliancalusa.png
  description: >
    A Família Aliança Lusa, cujo clã principal foi criado a 18/09/2022 e secundário a 21/10/2022, está já no TOP10 do Ranking de Portugal no que toca a troféus. Somos também clã ativo de guerra, com Discord, grupo no whatsapp e com constantes Torneios Internos, assim como um terceiro clã para férias! ATREVE-TE! The Aliança Lusa Family, whose main clan was created on 18/09/2022 and secondary on 21/10/2022, is already in the TOP10 of the Portugal Ranking when it comes to trophies. We are also an active war clan, with a Discord server, WhatsApp group, and frequent internal tournaments as well as a third clan for vacations! DARE TO JOIN US!
clans:
- name: Aliança Lusa
  tag: Q0R08YLJ
- name: Aliança Lusa 2
  tag: Q20GUCV8
- name: 『AL』3º Piso 金
  tag: GV0UJY8V
```
