### ISSUE TITLE
Andromeda Descendants update

### ISSUE THREAD

**Issue by MarceloBRC** [RoyaleAPI/family-config#883]
```yaml

change emblem to: https://drive.google.com/file/d/1E1RJwv4pW9mR12L6BDClScWIRQx-VXdC/view?usp=sharing



   

add clans:
  - name: dementiods
    tag: LJYJLPPQ
  - name: FIGHT CLUB USA
    tag: JGU2YLR
  - name: AD eSports
    tag: QPVJ92UP
```
