### ISSUE TITLE
warriors clan family

### ISSUE THREAD

**Issue by 177cj** [RoyaleAPI/family-config#884]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Warriors family clan
key: Warriors empire 
color: red
emblem: flag_j_02
info:
  logo:
  description: >
    The warriors clan family has 3 war based clans, we are looking for more active and war based members
  social : 
        - discord : https://discord.gg/uUHVkZhJt7
clans:
  - name: #77 Warriors
    tag: 28L0QLP
  - name: #76 Warriors
    tag: L9CYGJY
  - name: #75 Warriors
    tag: VVPL9UC
```
