### ISSUE TITLE
☆. La Resistance

### ISSUE THREAD

**Issue by RicoSoft3000** [RoyaleAPI/family-config#885]
```yaml
name: ☆. La Resistance
key: la_resistance
color: orange
emblem: Traditional_Star_01.png
info:
  logo: https://ibb.co/tsMY5Bj
  description: >
    **☆. La Resistance** famille de 3 clans orientés GDC avec pour ambition de progresser dans le top monde. 
Bonne humeur obligatoire !!!
  social:
    - discord: https://discord.gg/kPdQN8zfjM
clans:
  - name: La Resistance
    tag: Y8JUPC9C
  - name: Les Resistants
    tag: LRQP20V9
  - name: La Treve
    tag: QUV220GJ
```
