### ISSUE TITLE
Warriors empire

### ISSUE THREAD

**Issue by 177cj** [RoyaleAPI/family-config#887]
```yaml
name: Warriors Empire
key: Warriors
color: blue
emblem: flag_j_02
  description: >
    active family of war clans looking for active members.


social:
    - discord: http://discord.gg/HBhzug4jBf
clans:
  - name: #77 Warriors
    tag: 28L0QLP
  - name: #76 Warriors
    tag: L9CYGJY
  - name: #75 Warriors 
    tag: VVPL9UC
  - name: #74 Warriors
    tag: 90YCCURY
```
