### ISSUE TITLE
[New family] Elites⚡️Royale

### ISSUE THREAD

**Issue by LaTronco** [RoyaleAPI/family-config#888]
Hi, i’m registering a friend’s family, thanks as always for your service!

```yaml

name: Elites⚡️Royale
key: elites
color: green
emblem: flag_k_04
info:
  logo: https://postimg.cc/GBMdM5wR
  description: >
   Benvenuti nella famiglia **Elites⚡️Royale** !

Nei nostri primi due clan chiudiamo le giornate con 200 attacchi, la guerra è la nostra priorità.
Il terzo clan è ancora indietro ma un giorno raggiungerà il livello dei primi due.


No comportamenti infantili, no spam, no bestemmie e NESSUN tipo di discriminazione religiosa, razziale o di genere.


Abbiamo un gruppo Telegram per il primo clan ed uno per il secondo, qui sotto i link per entrare.

  social:
    - telegram: https://t.me/+j7Xn6_ckBuplZjNk
    - telegram: https://t.me/+1mk2Fee6ucEzOTk8

clans:
  - name: Elites⚡Royale™
    tag: LLGQQ8C2
  - name: Elites⚡Royale2™
    tag: LLU8RGQ8
  - name: ELITES⚡LEGION™
    tag: QRQG202Y

sort: trophy

```
