### ISSUE TITLE
Flying Whales

### ISSUE THREAD

**Issue by manuelsmonteiro** [RoyaleAPI/family-config#891]
```yaml
name: Flying Whales
key: flyingwhales
color: red
emblem: Freeze_02
info:
  description: >
    **Flying Whales** is a portuguese clan family based on three clans: **Flying Whales**, the best all around portuguese clan; **Wild Coyotes** and **FW Academy**. 
  social:
    - discord: https://discord.gg/AKGatrP57z
clans:
  - name: Flying Whales
    tag: QP80RPQL
  - name: Wild Coyotes
    tag: QCQL0PL2
  - name: FW Academy
    tag: QGVYLRVG
```
