### ISSUE TITLE
 Update Family Peru War

### ISSUE THREAD

**Issue by Edi1232001** [RoyaleAPI/family-config#893]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: PERU WAR Family
key: peruwar
color: red
emblem: Bamboo_04
info:
  logo:
  description: >
    Unete a la familia de clanes, jugadores activos y con ganas de mejorar que esperas únete, familia de clanes, cofre de guerra primer lugar asegurado gracias a una estrategia de guerra

    
clans:
  - name: Fuerza Peru
    tag: L00YURP9
  - name: teamMancos
    tag: 9LCVYVP0
  - name: Jóvenes Titanes
    tag: Y8JJVG9V
  - name: PIRIMIDINA
    tag: LRQJVGV8
  - name: InKa eSports
    tag: 8G2Y90VR
  - name: EC DOMINATION
    tag: YRPG9RL8
  - name: DARKSIDERS
    tag: YCVUL0QP
  - name: Angels Of Death
    tag: P8CRGCPY
  - name: TNC GAMING
    tag: LLC8GJR2
  - name: ILuminaty Team
    tag: 9VRGY0LR
  - name: GIGANTE 2
    tag: LVLPPVJP
  - name: FAMILIA PERUANA
    tag: LLC2LGQY
  - name: BARRIO FINO
    tag: LGU88JY9
  - name: LOS MEJORES
    tag: GPGUJU20
  - name: Team Sero
    tag: QRL0VY0L
  - name: PROYECTO 2022
    tag: QLGPCCJ8
  - name: 4 DE JUNIO 2022
    tag: LUY9Q990
  - name: los pros aqui
    tag: QPG9GL2L
  - name: mijo
    tag: GY0LUR0L
  - name: AKATSUKI
    tag: LUPJ9QQ9
  - name: CHAVOLANDIA
    tag: LVRCJP0L
  - name: PE Revolucion23
    tag: Q9LLJV09
```
