### ISSUE TITLE
Gobliniffygang Clan Family Profile 

### ISSUE THREAD

**Issue by Gobliniffygang** [RoyaleAPI/family-config#894]
```yaml
name: Gobliniffygang Cartel™ 
key: Gobliniffy
color: red
emblem: A_Char_Goblin_01
info:
  logo: [
![image](https://github.com/RoyaleAPI/family-config/assets/135651163/93d45515-c137-401f-9a9a-e0aff8f3fab2)
](url)

  description: >
  Based & founded just outside of Dallas, Texas in da 903, Gobliniffygang reps both the 903 & the 214. 
  Gobliniffygang is a serious war clan looking for members who are willing to do war and contribute to
  the clan. Although we have most of our members are located in Texas, we are an inclusive clan that 
  welcomes everyone regardless of location and language. For our lower level friends, please consider 
  joining Gobliniffygang2

-   Gobliniffy on top. 

-   903 Tx on top 📍

-   214 Tx on top 📍

  **Join Gobliniffygang Cartel™ & Be A Part Of One Of Our Dominant War Clans** 

 
  social:
    - tiktok : https://www.tiktok.com/@gobliniffygang
    - email: Gobliniffygang@gmail.com
clans:
  - name: Gobliniffygang
    tag: P9LU2Q98
  - name: Gobliniffygang2
    tag: QV0UG8L9

```
