### ISSUE TITLE
巅峰大家庭

### ISSUE THREAD

**Issue by as953211272** [RoyaleAPI/family-config#898]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: 巅峰大家庭
key: 巅峰
color: red
emblem: Traditional_Star_04
info:
  logo: https://pbs.twimg.com/media/FygqoE5akAMEkTn?format=jpg&name=small
  description: >
    这里是**巅峰大家庭**，我们国际服有5个部落2个友盟，国服有3个部落
    我们部落非常友好，也非常活跃，不定期会举办部落比赛，相信来我们部落你会有家的感觉
    Q群734478032，欢迎各位小伙伴的加入！！
    **巅峰！！所向披靡！！！**
  social:
    - website: https://space.bilibili.com/24292931?spm_id_from=333.999.0.0
clans:
  - name: 巅峰丿圣域
    tag: YQUUP89V
  - name: 巅峰丿神域
    tag: Q22UYJG2
  - name: 巅峰丿圣御
    tag: Q208JY90
  - name: 巅峰丿阖域
    tag: QCR9QQQG
  - name: 巅峰丿煙域
    tag: Q8QJRJ8G
```
