### ISSUE TITLE
OsDeSorte Family (Update)

### ISSUE THREAD

**Issue by RikeRodrigues** [RoyaleAPI/family-config#9]
```yaml
name: OsDeSorte
key: ODS
color: green
emblem: Clover_02
info:
  logo: https://pbs.twimg.com/profile_images/1046600878738853888/Va9BKg_f_400x400.jpg
  description: >
   **Brazilian Competitive Team.** OsDeSorte (LuckyOnes): Established on June 21st, 2017, OsDeSorte established its competitive team on December/2017 and reached Top 10 Brazilian Clan Ranking on April/18. We are what the very best is. We are the very best we can do. Luck is the result of intense work and dedication. Love and Passion in everything we do. Excellence archieved with hard work and dedication.
  social:
    - twitter: https://twitter.com/osdesorteteam
    - facebook: https://www.facebook.com/milena.anchieta.79
    - discord: https://discord.gg/75xXWu3
    - whatsapp: +55 11 95399 6856    
clans:
  - name: OsDeSorte
    tag: 2CRP0URJ
  - name: OsDeSorte 2
    tag: 8Q9CQCJL
  - name: OsDeSorte 3
    tag: 8QR892QP
  - name: OsDeSorte 4
    tag: P8JCVQRP
```

**Comment by smlbiobot** [comment]
- I can’t add Whatsapp because it has no web URL. I moved it to clan description

```yml
name: OsDeSorte
key: ODS
color: green
emblem: Clover_02
info:
  logo: /static/img/brands/logo/osdesorte-2.jpg
  description: >
   **Brazilian Competitive Team.** OsDeSorte (LuckyOnes): Established on June 21st, 2017, OsDeSorte established its competitive team on December/2017 and reached Top 10 Brazilian Clan Ranking on April/18. We are what the very best is. We are the very best we can do. Luck is the result of intense work and dedication. Love and Passion in everything we do. Excellence archieved with hard work and dedication.

    
   - whatsapp: +55 11 95399 6856
  social:
    - twitter: https://twitter.com/osdesorteteam
    - facebook: https://www.facebook.com/milena.anchieta.79
    - discord: https://discord.gg/75xXWu3

clans:
  - name: OsDeSorte
    tag: 2CRP0URJ
  - name: OsDeSorte 2
    tag: 8Q9CQCJL
  - name: OsDeSorte 3
    tag: 8QR892QP
  - name: OsDeSorte 4
    tag: P8JCVQRP
```
