### ISSUE TITLE
top clan

### ISSUE THREAD

**Issue by as953211272** [RoyaleAPI/family-config#900]
thank you
```yaml
name: 巅峰大家庭
key: 巅峰
color: red
emblem: Traditional_Star_04
info:
  logo: https://pbs.twimg.com/media/FygqoE5akAMEkTn?format=jpg&name=small
  description: >
    这里是**巅峰大家庭**，我们国际服有6个部落2个友盟，国服有3个部落。
    我们部落非常友好，也非常活跃，不定期会举办部落比赛，部落战也是长期稳定第一，来我们部落你会有家的感觉。
     **Q群734478032**，欢迎各位小伙伴的加入！！
   
    国服部落：①老司機開車了，趕緊上車#L2PQ2RQ9   ；②巅峰丿武統中華#LPR0JV09；
    国际服友盟：①皮卡超人#Y2292PGJ   ；②中國香港~戰鬥軍團#YJYPC0RJ；

    **巅峰！！所向披靡！！！**    
  social:
    - website: https://space.bilibili.com/24292931
clans:
  - name: 巅峰丿圣域
    tag: YQUUP89V
  - name: 巅峰丿神域
    tag: Q22UYJG2
  - name: 巅峰丿圣御
    tag: Q208JY90
  - name: 巅峰丿阖域
    tag: QCR9QQQG
  - name: 巅峰丿煙域
    tag: Q8QJRJ8G
  - name: 巅峰丿禹域
    tag: QYJ29PYJ
```
