### ISSUE TITLE
CNHK clan

### ISSUE THREAD

**Issue by as953211272** [RoyaleAPI/family-config#901]
thank you very much
```yaml
name: 中國香港
key: 中國香港
color: red
emblem: Traditional_Star_04
info:
  logo: http://p9.itc.cn/q_70/images03/20201029/b4c10451002b4e87b24f621d15fb987e.jpeg
  description: >
   我哋係中國香港🇨🇳🇭🇰，設有三個部落，歡迎各位加入
  social:
clans:
  - name: 中國香港~戰鬥軍團
    tag: YJYPC0RJ
  - name: 中國香港
    tag: PJ2088U9
  - name: 戰鬥軍團 * 什伐赤
    tag: QY9Y2L2J
```
