### ISSUE TITLE
WickedFamily

### ISSUE THREAD

**Issue by DennisHvA** [RoyaleAPI/family-config#902]
```yaml
name: WickedFamily
key: wicked
color: blue
emblem: Crown_02
info:
  logo: https://raw.githubusercontent.com/DennisHvA/clash-royale/main/images/Crown_02.png
  description:  >
Welkom in onze familie 💛


    Wij zijn een fanatieke clan in de top van Nederland. Al sinds clanwars 1 hebben wij een vaste plek op de ranglijsten voor zowel ladder als clanwars.
  social:
    - discord: http://discord.gg/Z8R84HCBSr
clans:
  - name: WickedFamily
    tag: 9PCPQ9LQ
  - name: WickedFamily 2
    tag: GVQLQ0QY
```
