### ISSUE TITLE
Diamonds [Update]

### ISSUE THREAD

**Issue by Ranallo94** [RoyaleAPI/family-config#906]
name: Diamonds
key: diamonds
color: blue
emblem: Diamond_03
description: >
La Famiglia Diamonds è una delle migliori famiglie di clan in Italia, formata da 4 clan e 200 giocatori. Gli obiettivi principali sono la guerra, la scalata, la squadra competitiva, la crescita dei giocatori e l'amicizia. Ci sono anche tornei mensili con diverse modalità di gioco e premi.

social:
- twitch: twitch.com/klais28
- telegram: https://telegram.me/fabiocipriani
- instagram: https://instagram.com/diamonds.clashroyale 

clans:
name: Diamonds 
tag: P0LGP80U
name: Diamonds II
tag: 9QCVJLJ2
name: Diamonds III
tag: P2QGRLPV
name: Diamonds IV
tag: P0LRLQC9
name: Diamonds Élite
tag: Q2YVJ9CY
name: Diamonds Stars
tag: GGRVPL0U

**Comment by smlbiobot** [comment]
if you are not gonna FORMAT this i will not update in the future.

**Comment by smlbiobot** [comment]
you MUST enter this instead:
```yml
name: Diamonds
key: diamonds
color: blue
emblem: Diamond_03
info:
  description: >
    La Famiglia Diamonds è una delle migliori famiglie di clan in Italia, formata
    da 4 clan e 200 giocatori. Gli obiettivi principali sono la guerra, la scalata,
    la squadra competitiva, la crescita dei giocatori e l'amicizia. Ci sono anche
    tornei mensili con diverse modalità di gioco e premi.

  social:
  - twitch: https://twitch.com/klais28
  - telegram: https://telegram.me/fabiocipriani
  - instagram: https://instagram.com/diamonds.clashroyale

clans:
- name: Diamonds
  tag: P0LGP80U
- name: Diamonds II
  tag: 9QCVJLJ2
- name: Diamonds III
  tag: P2QGRLPV
- name: Diamonds IV
  tag: P0LRLQC9
- name: Diamonds Élite
  tag: Q2YVJ9CY
- name: Diamonds Stars
  tag: GGRVPL0U

```
