### ISSUE TITLE
Config: Phantom Shadows

### ISSUE THREAD

**Issue by IvMisticos** [RoyaleAPI/family-config#909]
```yaml
name: Phantom Shadows
key: phantomshadows
color: blue
emblem: flag_e_01
info:
  social:
    - telegram: https://t.me/PhantomShadows
clans:
  - name: Phantom Shadows
    tag: YGGQCLC0
  - name: Night Terror
    tag: GVYLJY98
```

P.S. Please delete `bandiz` family as it is obsolete. I've submitted it earlier as well FYI, so shouldn't be an issue.
