### ISSUE TITLE
The Pillars Family 

### ISSUE THREAD

**Issue by THEBoosOfAll** [RoyaleAPI/family-config#91]
```
name: The Pillars
key: thepillars
color: Teal 
emblem: Bamboo_04
  logo: 
  description: >
           **Welcome to The Pillars!!!**
           The Pillar is a friendly family, we are a casual family. We accept anyone and everyone, we have multiple clans so everyone can be with their own trophy range of players. Hope to see you on board. 
  social:
    - discord: http://discord.gg/bR3J7FM
clans:
  - name: The Pillars
    tag: PYCC2GCQ
  - name: Fire Pillar
    tag: Y299UQJC
  - name:
    tag:
```
