### ISSUE TITLE
```yaml name: Crying Fire Dynasty™ key: crying-fire color: blue emblem: Flame_04```

### ISSUE THREAD

**Issue by cfdsirluke** [RoyaleAPI/family-config#911]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name:
key:
color:
emblem:
info:
  logo:
  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: http://twitter.com/
    - discord: http://discord.gg/
    - twitch: https://www.twitch.tv/
    - reddit: http://www.reddit.com/
    - youtube: https://www.youtube.com/channel/
    - website: http://docs.redditalpha.com
    - instagram: https://instagram.com/
    - facebook: https://facebook.com/
    - twitch: https://twitch.tv/
    - youtube: https://www.youtube.com/channel/
    - application: https://url/
    - email: mailto:
clans:
  - name: 100T Alpha
    tag: 9PJ82CRC
  - name:
    tag:
  - name:
    tag:
```

**Comment by cfdsirluke** [comment]
```yaml
name: Crying Fire Dynasty™
key: crying-fire
color: blue
emblem: Flame_04
```

**Comment by cfdsirluke** [comment]
```yaml
  logo: https://cdn.discordapp.com/attachments/1125940805060804718/1128149256692310076/BlueFlame.png
  description: >
    **Crying Fire Dynasty™** is made up of 11 war clans and over 400 Clan War Warriors and have been dominating Clash Royale since July 2017. We strive for ultimate Clan Wars 2 success and run one of the top War clans in America: **Crying Fire**. 


Our goal is to be one of the most successful local and global war clans in Clash Royale. We are committed to teamwork and player development so we can rise together. 


Join now to become a Crying Fire Legend with us!!
```

**Comment by cfdsirluke** [comment]
```yaml
name: Crying Fire Dynasty™
key: crying-fire
color: blue
emblem: Flame_04
info:
  logo: https://cdn.discordapp.com/attachments/1125940805060804718/1128149256692310076/BlueFlame.png
  description: >
    **Crying Fire Dynasty™** is made up of 11 war clans and over 400 Clan War Warriors and have been dominating Clash Royale since July 2017. We strive for ultimate Clan Wars 2 success and run one of the top War clans in America: **Crying Fire**. 

Our goal is to be one of the most successful local and global war clans in Clash Royale. We are committed to teamwork and player development so we can rise together. 

**Join now to become a Crying Fire Legend with us!!**
  social:
    - discord: https://discord.gg/c7WhggVTsW
clans:
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: Elixir Thieves™
    tag: YG2LUQLC
  - name: Fiery Embers
    tag: QCC9C8UR
  - name: Ruthless
    tag: Y8PCPYPY
  - name: Bonecrushers
    tag: 20YLRYU
  - name: Crying Fire™
    tag: LQQJQULG
  - name: RedStorm
    tag: 2Q8JGYP
  - name: Crying Fire 2
    tag: GYUJYJJP
  - name: Crying Fire 3
    tag: Q0PL9VRR
  - name: Tears of Fire
    tag: QCPGQCQV
  - name: Embers of Fire
    tag: Q8QQ90L0
```
