### ISSUE TITLE
Русский Клан ▪️ Family🚀

### ISSUE THREAD

**Issue by vI1nekto** [RoyaleAPI/family-config#912]
```yaml
name: Русский Клан ▪️ Family🚀
key: RusClan
color: blue
emblem: A_Char_Rocket_01
info:
  logo: i.postimg.cc/Bv1nF6PS/image.png
  description: >
    **Русский Клан** - клан для приверженцев европейско-традиционного пути России🇷🇺🗽
    Крупная Tg-беседа, высокий актив (как и места в глобале😏), приятные собеседники, а также ценные призы🤩
    
    P.S. Состоит из _флагманского💜, основного👑, академического🎓_ и дружественных кланов соответственно😉
  social:
    - telegram: https://t.me/RusClan_CR
clans:
  - name: Vertical
    tag: JC9JC9P
  - name: Русский Клан
    tag: LRVPQJRR
  - name: Русский клан
    tag: PY0JRL8Q
  - name: Vertical II
    tag: YC08PPVC
```

**Comment by vI1nekto** [comment]
```yaml
name: Русский Клан • Union🚀
key: RusClan
color: blue
emblem: A_Char_Rocket_01
info:
  logo: https://github.com/RoyaleAPI/family-config/assets/118662333/5a4e794b-112b-49a4-a812-f1eb6bc0b34f
  description: |
    **Русский Клан** - клан для приверженцев евро-традиционного пути России🇷🇺🗽
    Высокий актив, крупная Tg-беседа, приятные собеседники, а также ценные призы:)
    
    P.S. Состоит из _флагманского💜, основного👑, академического🎓_ и дружественных кланов соответственно!
  social:
    - telegram: https://t.me/RusClan_CR/1642
    - telegram: https://t.me/CR_Resume/6
clans:
  - name: Vertical
    tag: JC9JC9P
  - name: Русский Клан
    tag: LRVPQJRR
  - name: Русский клан
    tag: PY0JRL8Q
  - name: Vertical II
    tag: YC08PPVC
  - name: Newlenders
    tag: QY8L9V0G
```
