### ISSUE TITLE
Warriors Faction clan family update

### ISSUE THREAD

**Issue by bwat124** [RoyaleAPI/family-config#913]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Warriors Faction
key: warriorsfaction
color: red
emblem: Star_Shine_02
info:
  logo: https://twitter.com/cr_warfaction/photo
  description: >
    The **Warriors Faction** clan family is a group of elite war clans including several globally ranked clans! Our family has been dominating the Clan Wars II space for years and our players are passionate about war! Join one of our 20+ clans or join our discord to start your journey with the best clan family in the US!
  social:
    - twitter: https://twitter.com/cr_warfaction
    - discord: https://discord.gg/H3BwnX3
    - website: https://discord.com/servers/warriors-faction-379736679784775681
clans:
  - name: CRL Esports PRO
    tag: 9UV202Q2
  - name: Mega Knights
    tag: 9GQ8R29Y
  - name: Elixir Elites
    tag: PP00JCRV
  - name: BEWO Pro
    tag: YY89R8RG
  - name: Avenging Souls
    tag: PCPGLYY0
  - name: Alpha Steel
    tag: 9PV9JL
  - name: Divine Wind
    tag: 2CJY2008
  - name: Ready Reserves
    tag: L9RGU90V
  - name: DulcedeLeche
    tag: Y099P8GU
  - name: No Clan
    tag: YC8CJV9G
  - name: monkey mafia 2
    tag: 2CYLGU8R
  - name: Elite Assassins
    tag: 8QCRCU2L
  - name: False Logic V
    tag: 2CVRP2YQ
  - name: Rogue Kingdom
    tag: YVVC0JJU
  - name: Thunder Harbor
    tag: YRGJ0QYV
  - name: gladiators
    tag: LQJQUQ2G
  - name: PRO ERA
    tag: LYUL0Y2V
  - name: Elixir Empire
    tag: LUQY2JPY
  - name: MK 4PLaY
    tag: QQLJJ8YP
  - name: Mini Knights
    tag: GG8UJC29
  - name: AssertDominance
    tag: P8028YL9
  - name: Iron Made
    tag: Q9Q9R8RL
```

  
[wf.zip](https://github.com/RoyaleAPI/family-config/files/12062429/wf.zip)
