### ISSUE TITLE
TOP-CLAN [UPDATE]

### ISSUE THREAD

**Issue by as953211272** [RoyaleAPI/family-config#914]
remove 1 clan(巅峰丿禹域 #QYJ29PYJ),add 2 clan (巅峰丿龍域#GRGGU9RR、巅峰丿禹域#G0JCUV8L)

```yaml
name: 巅峰大家庭
key: 巅峰
color: red
emblem: Traditional_Star_04
info:
  logo: https://pbs.twimg.com/media/FygqoE5akAMEkTn?format=jpg&name=small
  description: >
    **縱橫馳騁任征途，巔峰巍峨志不枯！**

    欢迎您加入我们**巅峰大家庭**，我们国际服有7个部落2个友盟，国服有3个部落。
    这里汇聚志同道合的伙伴，携手追求卓越。巅峰，不仅是目标，更是起点，我们共同走向成功巅峰的征程。让我们一起学习、成长、共享，创造无限可能，迎接光辉未来！

     **Q群734478032**，欢迎各位小伙伴的加入！！
     
     **巅峰！！所向披靡！！！**    
  social:
    - website: https://space.bilibili.com/24292931
clans:
  - name: 巅峰丿圣域
    tag: YQUUP89V
  - name: 巅峰丿神域
    tag: Q22UYJG2
  - name: 巅峰丿圣御
    tag: Q208JY90
  - name: 巅峰丿阖域
    tag: QCR9QQQG
  - name: 巅峰丿煙域
    tag: Q8QJRJ8G
  - name: 巅峰丿龍域
    tag: GRGGU9RR
  - name: 巅峰丿禹域
    tag: ROCPYRYU

```
