### ISSUE TITLE
Tide Family Update

### ISSUE THREAD

**Issue by JJCTheGamer** [RoyaleAPI/family-config#915]
name: Tide Family
key: tide
color: black
emblem: Moon_03
info:
  logo:
![https://media.discordapp.net/attachments/1036060800374292593/1116903635486515220/Screenshot_2023-06-09_213337-removebg-preview_1.png]
  description: >

  We aspire to be great and show the world who we are! Together we grow and have fun! We shine at ladder, trophy road, and war! We are also in the competitive esports scene and rising! Join us today as we rise to the top!

    Add new line with 2 line breaks as above.
  social:

twitter: http://twitter.com/@TideEsport
discord: http://discord.gg/KhFRrHSBbx
twitch: https://www.twitch.tv/jjcthegamer
youtube: https://www.youtube.com/channel/@jjcthegamer
instagram: https://instagram.com/tideesport
email: mailto: tideesports9@gmail.com
clans:

name: Tide Of Dawn
  tag: #LRJ2Q9UO
name: Tides Vengeance 
tag: #Q8P9RLYP
name: MiActivoTorre
tag: #LUUOUR22
name: replays
tag: GOCVPLPQ

**Comment by smlbiobot** [comment]
hey i can’t format this for you. Please always post in the correct format. I won’t reformat for you anymore.

```yml
name: Tide Family
key: tide
color: yellow
emblem: Moon_03
info:
  logo_cdn: /static/img/family/logo/tide-family.png

  description: >2

    We aspire to be great and show the world who we are! Together we grow and have
    fun! We shine at ladder, trophy road, and war! We are also in the competitive
    esports scene and rising! Join us today as we rise to the top!


  social:
  - twitter: https://twitter.com/TideEsport
  - discord: https://discord.gg/KhFRrHSBbx
  - twitch: https://www.twitch.tv/jjcthegamer
  - youtube: https://www.youtube.com/channel/UCT8YtwImX2VPAMB_mMcsmlg
  - instagram: https://instagram.com/tideesport
  - twitch: https://twitch.tv/jjcthegamer
clans:
- name: Tide Of Dawn
  tag: LRJ2Q9U0
- name: Tides Vengeance
  tag: Q8P9RLYP
- name: MiActivoTorre
  tag: LUU0UR22

```
