### ISSUE TITLE
Família Deltas

### ISSUE THREAD

**Issue by Clodoaldo472** [RoyaleAPI/family-config#916]
name: Família Deltas
key: deltas
color: purple
emblem: Star_Shine_03
info:
  logo: https://prnt.sc/R4lt_WhK4K3T
  description: >
	Nossos clãs têm regras próprias, visando garantir um ambiente competitivo, mas também amigável e colaborativo para todos os membros. Trabalhamos em equipe, compartilhando estratégias e dicas para ajudar uns aos outros a alcançar o melhor desempenho nas Guerras de Clãs.
	Além do jogo em si, também temos um grupo ativo no WhatsApp, onde os membros podem interagir, discutir estratégias, compartilhar replays e manter-se atualizados sobre eventos e novidades no clã. A comunicação é fundamental para o nosso sucesso como família de clãs.
	Se você é um jogador competitivo, apaixonado por Guerras de Clãs e busca um grupo comprometido com o progresso coletivo, junte-se a nós!	 Independentemente do seu nível de habilidade ou experiência, oferecemos um ambiente acolhedor e oportunidades para crescer e se destacar no Clash Royale.
	Para ingressar na nossa Família de Clãs, entre em contato conosco através do jogo ou visite nosso discord para obter mais informações sobre os requisitos de ingresso em cada clã e para conhecer melhor nossa comunidade. Estamos ansiosos para lutar ao seu lado nas Guerras de Clãs e alcançar grandes conquistas juntos!
  social:
    - discord: https://discord.com/invite/qRhAQDMTxt
clans:
  - name: Deltas PE
    tag: RGGC90V
  - name: Deltas Academy
    tag: QLU8R8RL
  - name: Deltas Troop
    tag: G9RRVVUY

**Comment by smlbiobot** [comment]
```yml
name: Família Deltas
key: deltas
color: purple
emblem: Star_Shine_03
info:
  logo: /static/img/family/logo/deltas.jpg
  description: >
    Nossos clãs têm regras próprias, visando garantir um ambiente competitivo, mas também amigável e colaborativo para todos os membros. Trabalhamos em equipe, compartilhando estratégias e dicas para ajudar uns aos outros a alcançar o melhor desempenho nas Guerras de Clãs.
    
    
    Além do jogo em si, também temos um grupo ativo no WhatsApp, onde os membros podem interagir, discutir estratégias, compartilhar replays e manter-se atualizados sobre eventos e novidades no clã. A comunicação é fundamental para o nosso sucesso como família de clãs.
    
    
    Se você é um jogador competitivo, apaixonado por Guerras de Clãs e busca um grupo comprometido com o progresso coletivo, junte-se a nós!	 Independentemente do seu nível de habilidade ou experiência, oferecemos um ambiente acolhedor e oportunidades para crescer e se destacar no Clash Royale.
    
    
    Para ingressar na nossa Família de Clãs, entre em contato conosco através do jogo ou visite nosso discord para obter mais informações sobre os requisitos de ingresso em cada clã e para conhecer melhor nossa comunidade. Estamos ansiosos para lutar ao seu lado nas Guerras de Clãs e alcançar grandes conquistas juntos!
  social:
    - discord: https://discord.com/invite/qRhAQDMTxt
clans:
  - name: Deltas PE
    tag: RGGC90V
  - name: Deltas Academy
    tag: QLU8R8RL
  - name: Deltas Troop
    tag: G9RRVVUY
```
