### ISSUE TITLE
India[UPDATE]

### ISSUE THREAD

**Issue by legend84yt** [RoyaleAPI/family-config#917]
```yaml
name: INDIAN CLASHERS LEAUGE
key: icl
color: gold
emblem: Skull_03.png
info:
  logo:
  description: >
    our clans main goal is to represent INDIA globally we have over 700 members and 14. our clan provide training to the new members and help them to improve our clan since creation had been active so on.... join our clan to feel proud of yourself we gave some achievements like we ae already reached in top 4 in local leaderboards in ladder and top 14 in local leaderboards in clan wars



  social:
    - discord: http://discord.gg/dxWhkJ5UxT


    - youtube: https://www.youtube.com/@user-legendyt84

    - instagram: https://instagram.com/icl_yt




    - email: mailto: sarodeyash84@gmail.com
clans:
  - name: India
    tag: LQ8VCCGJ
  - name: Indians
    tag: Q92CQU2Y
  - name: INDIAN ARMY
    tag: LUVV9J20
  -name: Telegu united
    tag: LGQPL920
  -name: bhandari
    tag: YLRGUQUG
  -name: First spell
   tag: YLRVLQVY
   -name: ELITE INDIANS
   tag: GGOUJ2R2
   -name: SUPERCELL
    tag: QYPPCL9R
    -name: KERELA
    tag: QRGLVL8G
    -name: Phoenix
     tag: QR9PPGGU
    -name: Clan wars 1
     tag: LYJ8UU2U
    -name: EmBeRs RiSiNg
     tag: GGLJ2UQU
    -name: TEAM INDIA
     tag: QV8QJV89
```

**Comment by smlbiobot** [comment]
please format properly. next time i won’t fix it until you format properly.

```yml
name: INDIAN CLASHERS LEAUGE
key: icl
color: gold
emblem: Skull_03
info:
  logo:
  description: >
    our clans main goal is to represent INDIA globally we have over 700 members and 14. our clan provide training to the new members and help them to improve our clan since creation had been active so on.... join our clan to feel proud of yourself we gave some achievements like we ae already reached in top 4 in local leaderboards in ladder and top 14 in local leaderboards in clan wars

  social:
    - discord: http://discord.gg/dxWhkJ5UxT
    - youtube: https://www.youtube.com/@user-legendyt84
    - instagram: https://instagram.com/icl_yt
    - email: mailto:sarodeyash84@gmail.com
clans:
  - name: India
    tag: LQ8VCCGJ
  - name: Indians
    tag: Q92CQU2Y
  - name: INDIAN ARMY
    tag: LUVV9J20
  - name: Telegu united
    tag: LGQPL920
  - name: bhandari
    tag: YLRGUQUG
  - name: First spell
    tag: YLRVLQVY
  - name: ELITE INDIANS
    tag: GGOUJ2R2
  - name: SUPERCELL
    tag: QYPPCL9R
  - name: KERELA
    tag: QRGLVL8G
  - name: Phoenix
    tag: QR9PPGGU
  - name: Clan wars 1
    tag: LYJ8UU2U
  - name: EmBeRs RiSiNg
    tag: GGLJ2UQU
  - name: TEAM INDIA
    tag: QV8QJV89
```
