### ISSUE TITLE
Update QLF Family info. Old is: https://royaleapi.com/clan/family/QLF/clans

### ISSUE THREAD

**Issue by kaikito** [RoyaleAPI/family-config#918]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Famille 'QLF'
key: qlf
color: purple
emblem: Elixir_01
info:
  logo: https://cdn.discordapp.com/attachments/877168725885865985/1080532044460855296/IMG_2254.png
  description: >
    Rejoins la famille 'QLF'! Record Top 6 (FR). Plusieurs Clans!
  social:
    - discord: https://discord.gg/VgQPCkcehD
clans:
  - name: 'QLF' Army
    tag: C9LRQRJ
  - name: 'QLF' Compagny
    tag: Y8JGJL90
  - name: 'QLF' Legion
    tag: Q2JR22RQ
  - name: 'QLF' Battalion
    tag: G0R9L9GQ
```

**Comment by smlbiobot** [comment]
your family config requires special handling. please edit this config in the future:

```yml
name: "Famille 'QLF'"
key: qlf
color: purple
emblem: Elixir_01
info:
  logo: /static/img/family/logo/qlf.png
  description: >
    Rejoins la famille 'QLF'! Record Top 6 (FR). Plusieurs Clans!
  social:
    - discord: https://discord.gg/VgQPCkcehD
clans:
  - name: "'QLF' Army"
    tag: C9LRQRJ
  - name: "'QLF' Compagny"
    tag: Y8JGJL90
  - name: "'QLF' Legion"
    tag: Q2JR22RQ
  - name: "'QLF' Battalion"
    tag: G0R9L9GQ
```
