### ISSUE TITLE
Polish Soldiers Family

### ISSUE THREAD

**Issue by M0us3yy** [RoyaleAPI/family-config#919]
```yaml
name: 001 Polish Soldiers Clans
key: polishsoldiers
color: black
emblem: Flame_03
info:
  logo: /psold.files.wordpress.com/2019/02/logo_ps_sabbs
  description: >
    Polski / English. 
    Dołącz do największej i najbardziej zgranej grupy Klanów Wojennych w Polsce. 
    Kultura, wiedza, Discord - dobra zabawa! Join us to share experience, 
    communicate on Discord and have lots of fun playing the best Clan Wars ever.


  social:
    - discord: https://discord.gg/Z9TRYA4z7V
    - website: https://psold.wordpress.com
clans:
  - name: Polish Soldiers
    tag: 2CVY8GUG
  - name: PS2 Akademia
    tag: P0RU2CL8
  - name: PS3 Akademia
    tag: QPLCJPGV
  - name: PS4 Akademia
    tag: LVJLJRVJ
  - name: PS6 Akademia
    tag: LLCPCGVG
  - name: Polish Soldiers (Mini)
    tag: Q2J92UQQ
```
