### ISSUE TITLE
Blueberry Vine 

### ISSUE THREAD

**Issue by BlueberryVineCR** [RoyaleAPI/family-config#920]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Blueberry Vine 
key: bv
color: blue
emblem: Pine_01
info:
  logo: 
![7AF6810D-6B1B-470C-87CE-D809FB6BA4E2](https://github.com/RoyaleAPI/family-config/assets/140474198/a007d066-f720-4f8a-a88e-0e083634ec7c)

  description: >
COMPETITIVE WAR CLAN! Must use all attacks • Hate of any form is not tolerated • code: RoyaleAPI
  social:
    - discord: https://discord.gg/xsFvfkr8
clans:
  - name: Blueberry Vine
    tag: PRG02QUR
  - name:
    tag:
  - name:
    tag:

```
