### ISSUE TITLE
Suppression du clan Les s@uv@ges de la famille 

### ISSUE THREAD

**Issue by MIKO1976** [RoyaleAPI/family-config#922]
```yaml

```nom : WarxUnion & rugbyman Family
clé : warxunion
couleur : noir
emblème : Flame_03
info :
logo : /static/img/brands/logo/warxunion.png
description : >
"WarxUnion & rugbyman Family.
Ici, vous pouvez progresser dans un environnement de jeu de classe mondiale avec une organisation professionnelle.
N'hésitez pas à postuler, votre profil est sûrement adapté à l'un de nos clans.
Ambiance conviviale et coopérative dans notre famille !"

social :
- discorde : https://discord.gg/8cvV6xUWZU
- instagram : https://instagram.com/warxunion_family?r=nametag

Youtube : https://m.youtube.com/@miami54cr96?itct=CC0QoTAYASITCPLzn_eWwvsCFeVBTwQd_IwBrQ%3D%3D
tic : https://www.twitch.tv/mathysss2?sr=a
Clans:

nom : WarxUnion 2
balise : 2UQ2VCCC
nom: rugbyman 41
tag: 8RC2PJC2
nom : Hell Fish VIP
tag : 9Q0JP29
nom : #CRF
balise : YPYGYYYR
nom : bang bang bang!
balise : 9VPRG2V2
nom : 10000 guerriers
tag : JQ0QJ0
nom : #Team guerrier
tag : UC2JGR
nom : bang bang bang2
tag : L0R9GRG8

**Comment by smlbiobot** [comment]
i can’t work with this. you MUST follow our format guidelines.

```yml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: /static/img/brands/logo/warxunion.png
  description: >
    **WarxUnion & rugbyman Family**.
    Here you can progress in a World Top gaming environment with a professional organization.
    Do not hesitate to apply, surely your profile is suitable for one of our clans.
    Friendly and cooperative atmosphere in our family!
  social:
  - discord: https://discord.gg/8cvV6xUWZU
  - instagram: https://instagram.com/warxunion_family
  - youtube: https://www.youtube.com/@miami54cr96
  - twitch: https://www.twitch.tv/mathysss2?sr=a


clans:
- name: WarxUnion 2
  tag: 2UQ2VCCC
- name: rugbyman 41
  tag: 8RC2PJC2
- name: Hell Fish VIP
  tag: 9Q0JP29
- name: '#CRF'
  tag: YPYGYYYR
- name: bang bang bang!
  tag: 9VPRG2V2
- name: 10000 guerriers
  tag: JQ0QJ0
- name: '#Team guerrier'
  tag: UC2JGR
- name: bang bang bang2
  tag: L0R9GRG8
- name: Les s@uv@ges
  tag: YVU9U00R
```
