### ISSUE TITLE
Champions swe war clan

### ISSUE THREAD

**Issue by Barometern** [RoyaleAPI/family-config#923]
```yaml
name: Chamions Swe Klanfamilj
key: championswe
color: blue
emblem: flag_d_03
info: 
  logo: https://cdn.royaleapi.com/static/img/badge/legendary-2/flag_d_03.png?t=1561672ac
  description: >
    En av Sveriges ledande och stoltaste krigsklaner! Vi siktar högt och välkomnar dig som gillar War och är level 45+. Ansök i Clash Royale eller via Discorden: https://discord.gg/cJauCk3s





  social:
   
    - discord: https://discord.gg/cJauCk3s
    
clans:
  - name: champions swe
    tag: 2JP9QPLQ
  - name: Champions Swe 2
    tag: QYJPU9Q2

```

**Comment by smlbiobot** [comment]
```yml
name: Chamions Swe Klanfamilj
key: championswe
color: blue
emblem: flag_d_03
info:
  logo: /static/img/badge/legendary-2/flag_d_03.png
  description: >
    En av Sveriges ledande och stoltaste krigsklaner! Vi siktar högt och välkomnar dig som gillar War och är level 45+. Ansök i Clash Royale eller via Discorden: https://discord.gg/cJauCk3s

  social:
    - discord: https://discord.gg/cJauCk3s
clans:
  - name: champions swe
    tag: 2JP9QPLQ
  - name: Champions Swe 2
    tag: QYJPU9Q2
```
