### ISSUE TITLE
Clan Family Update

### ISSUE THREAD

**Issue by TemptationsGaming** [RoyaleAPI/family-config#925]
```yaml
name: Temptations Gaming Clan Family
key: tmpgaming
color: black
emblem: A_Char_Pekka_01
info: Official Temptations Gaming Clan Family, Join our discord to apply!
  logo: https://share.creavite.co/jOSsAv4C57DVHNAe.png
    social:
    - twitter: http://twitter.com/@tmpgaming11
    - discord: https://discord.gg/VFR4Rh2tM9
clans:
  - name: Tickle My Pekka
    tag: G2Y9JP8Q
  - name: Pathogen X
    tag: LCCYG0CQ
  - name: 2 ラダーキラー
    tag: #Q2VVCU0J
```yaml

**Comment by smlbiobot** [comment]
format correctly

```yml
name: Temptations Gaming Clan Family
key: tmpgaming
color: black
emblem: A_Char_Pekka_01
info:
  description: Official Temptations Gaming Clan Family, Join our discord to apply!
  logo: /static/img/family/logo/tmpgaming-v2.png
  social:
    - twitter: http://twitter.com/@tmpgaming11
    - discord: https://discord.gg/VFR4Rh2tM9
clans:
  - name: Tickle My Pekka
    tag: G2Y9JP8Q
  - name: Pathogen X
    tag: LCCYG0CQ
  - name: 2 ラダーキラー
    tag: Q2VVCU0J
```
