### ISSUE TITLE
Castle Point Family

### ISSUE THREAD

**Issue by jimdads** [RoyaleAPI/family-config#926]
```yaml
name: Castle Point Family
key: cp
color: blue
emblem: Crown_03
info: 
  logo (data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhETEhMWFRUXFxcXGBYVGBUXEBgWFxUWFxUVFRYYHSggGB0lHxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGBAQFyslHiUtLSstLSstLSsrLTUrLTAuLTcrLS0tKys3LS0tLS0xLTcrNis3LSsrLTUtKzctKy0tK//AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABQcDBAYCAQj/xABLEAABAwEDBwcGCQoGAwAAAAABAAIDEQQSIQUGMUFRYXEHEzJygZGxIiOCobLBCDM0QlJiwtHhFBdFU1RzkqLD8BUkQ2Oz0hYlRP/EABkBAQEAAwEAAAAAAAAAAAAAAAABAgMFBP/EACkRAQEAAwABAgMIAwAAAAAAAAABAgMRIQQxElGBM0FhkaGx4fATFCP/2gAMAwEAAhEDEQA/ALxREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERARCVXWefKpBZ70VkAtE2ioxgYd5HTO4Yb0FiovzHLnTlAWgWsznntGgUu1rcu0pd3K1syuVWC03YrXSCbAXj8Q87iegdxw3oLGRAUQEREBERAREQEREBERAREQEREBFoZbyvDZYXzzvusb3k6mtGsnYqftnLTai93M2aIMrhf5xz6by1wHqQXeior889v/AGez/wAM3/dPzzW/9ns/8M3/AHQXqoTOfOqzWFl+0SAEjyY24yu6rdm80CqGflgyg9pa2GFjjgHhj7zd4vOI7wuMtDnyPMs73SyONSXEk+tB0udmf1ryheY3/L2Y4XGnynj/AHHfO4YDjpXN2aADoDi4+7avbWV092rt2ressFcTgPWdzQspivGD8nbShFd50rStWT8KjEbdY4rdt1uja4MYRXW04ntdtW1ZpQ4Yadh0/isuSjdzP5RLVYLsb/P2fRccfKaP9t2rgcOGlXjmznRZrdHfs8gJHSYcJWdZvvGG9fn20ZPDsRgf5So2IS2eQSQvdFI3EFpp3HWNyws4nH6tRURZeWW2saGyQwyECl6jmuO0kNNO4BZvz2Wr9mh75PvUF4oqO/Pbaf2aHvk+9eoeW20XhessRbrDXPDqbiagdyC70UZm9l2G2QtngdVpwIPSa7W1w1EKTQEREBERAREQEREFR8v8hu5Pjr5LnykjeOaAPYHu71WtphuUDcArI5ftOTetN4wLhcvR05vfX3KwRXOHal87V7EJLXOHzdPDatMWtn0m96yVtVO1ZIm9/rWmLU3a3vWdtuaBhidg951BBvgNaLziMNvRH3qPtmU3PqGVa3b84jd9ELVme55q48B80cAvNFLTqSyHYGSNla9tejjrB8rEFebVZJIMTV8epw6TeK3c2P8AV9H7SnCF0dWjHZpx+fnz9XP2bste289v4Qliyi11LxGPztXpbFKzWUUDXCoIqN42tOvsUTb8hkEvgwOth6B4bP70L5krOIxNfFI1pbrilrRrtT43DFh4YHWCvJs15a7zJ7Ne7HZPDOcjM2uXz/CWfW71jdnAzYz+IrwcvN+p/EVr8Nnhn/wuPf3rbsmSYi2QlpNA3STTF1DVe7F5yJ8lQKFlAMbwdXGu6nrW1ZnUjm4M9tRUzyBSuE1ujBNy603dVQ5wB7irnVK8gnym3dRvtlXUsGIiIgIiICIiAiIgqHl+05N603jAuMzjGEXpe5dny/6cm9abxgXG5yaIuLvcsoRq5Lhvxztw6LtOjoFQYiFBgO5dFkEeTP1H/wDGSoYMwCZLWsYG/RHcEEYGgU4K3MwczrFarGyWaIukvPa433t0ONMAaaCFg5RcxILPZhPZWFtx3nBec6rXYA+UTShoPSU4x+JVd1fLqzXVcWafJ1ZXWWF9qjLpXtvny5G0DsWto0jQKdtVOFvFZ5st+N9H7SnKKz7LmHYI63ISK6fOSnRxdvUfnVmtDHA6SBha5pBOLnVboOknaCul6bfjjjML7vBv1XLK5RwN1eXQNOJaDxAWaisLN3NWzus8T5o7z3C8TeeMCfJwBpoovVt244TtaMNdyvIrcQN+iO4L66IUOA0bAu2z0yLZ4IozEy65z6VvPOAacPKJ10XHubgUwzmePxQyxuN5UNkT4imxjPaK3Iz5Mno+0sWboH5LaDrDIKdsxBX0HyXej4rjuynuQT5Tbuo32yrrVKcgfym3dRvtlXWtdYiIiAiIgIiICIiCoeX/AE5N603jAuOzk6MXF3gF2HwgNOTetN4wLjc5DhFxd4BZQjBkh1I5uDvWwhaDW4DgFuZMPmpuB9la8YwHAJktW5yOTVsszPoyk9jmN+4ruLdZGyxvieKte0tPAiirfkalo61M3RuH84PiFZ/Ykar7qXyVycWr8qjbNF5kP8p95hDmNx0B1fKoBo1q5wF9Sqshb18XieEPa5rhUOBBG4ihWRKoisHZqWgShvNm7fpfFKXa0vadmKsyOMNAAFABQL2i27N2WznWvDXMPZxHKPJjA3rnvugeBXFObgeC6zP99bQwbIx63OP3Ll3jA8F0NHjXHk2+c653IcpEMjdTmR19F9Qsl7A9nitXJZ836DfFZicD2Ll11XT8gfym3dRvtlXWqU5A/lNu6jfbKuta6giIgIiICIiAiIgqD4QOnJ3Wn/oLis43fF9vuXa/CB/R3Gf+guEzid8X2qwYcnnzcvb4JA4Fo14DwXmwHzcvb4KBY4jQVclq2uSSWlre36UTu8Ob+Kt6i/NWZGcf5Ja45pA97AHAtbQvNWkClSNdFaH5y5X/ABGS7TJ2OHsscpGvKeVi0KYqvRnhlR/QyS9vXcfeGr2MvZbOjJ8Y4vbX1yhVOO/xTFcZY8q5YN7nbHE3RSjmb66JjuWw7LGURpsYPAj3PK2467lOyz82vLOS8dXQpRcic5rY3pZPkPVLvc0r5/5sW/G2SZnZXxAWX+vn90/WJ/lxQmeLwbVJuDR/KPxUFM4AHgViy1lIzTSyCoa5xIBwIGoGijZTgeBXUw12YSX5PDln3K1EZOf5sdULIZFrWE+bHVCSP0LjV2Hb8gfym29RvtlXWqU5AvlFt6jfbKuta6giIgIiICIiAiIgqD4QX6O4z/0FX2cBxZwKsD4QX6O4z/0FXuXtLOBVgwWN3m5O3wUQApWxjyJO3wUaGq1a6nksb/7SycZP+GRfoqi/LmQcqyWSeO0RBpey9QPBLfKaWmoBB0OOtdHaOVDKTtErWdWNn2gVJWFnV/ovzhNn5lF2m1yejdb7IC1X5228/wD2WjslePAq9T4X6ZRfn3NvOK2O5y9ap3Uu0vSyGnS0Vcp1mcNqGi0SdrifFevV6W7MJlK82zfMMrjYuVfaKoWZ22waJz2tYfFq24s+bYNLmO4sH2aLK+i2fOMZ6nH8UTnEP81af3sntlRrxgeBWxbLQZJHyOpee4uNNFXGppXisLmmh4LpScx48d81zdjd5tvVCSHQvlmFI28AvjjoXBrtu+5AvlFt6jfbKutUnyBfKLb1G+2VdiwqCIiAiIgIiICIiCn/AIQX6O4z/wBBV7l8Yx8Cru5Ucz3ZQs7OaNJoS50YODXBwF5ldRN1tDu31VF260PDjDaWGORnkm8CCDtOw6NysGGx2i7XftxGihBClnPilHnmY6pYgBIOs3oyDudvUJJCRoxHrSGYt0d2pZK3bZkORrS+MiaMaXsrVv7xnSYeIpvKi7qnMm5Qo8FrjG/U4Gh79Y3HBSdpjhm+PZzbv10LcD+9hHi3TVY8OOQovlFM5QyDJG3nG0liOiWI3o9mOtuOGNFGXFES+bA+N9H7SnVD5st+N9H7SnLq7PpL/wAsfr+7l+p+0v8AfuY0opKzZLc5t95EcY0veaN7NZXh2V4osLKy+79fKPJ4xs18fWs892OLHDTln7PUOSiG85M4Qx/Sf0j1WaSujzbyc2UPdDSCJlL88tDOQQSbgPkxims9xXB2zKVHX5XmSTeauHDUwcFG5Sy7NMwROfdhBrzbcIyTrf8ATPFeDb6nLLxHu1+mxx81IZ2ssDJAzJ73vYBRxOMYI+g44urjU6Ni517tC+tBOjAbT7gtaaZtaMq5x8fevJa9KyeQH5Rbeo32yrsVb8jmaE1kjlntALJJgAIz0msBrV2wknRqp3WQsUEREBERAREQEREBc5nbmVZcoN8827IBRsrMJBsB1OG49lF0aIPzjnTmDbcn3ngc9AMecYCQB9dulnHRvXLiZrtx/vvX61IXAZ4cldltV6SClnmOPkjzLj9Zg0He3uKCiCFu2TKL2UHSGw6ewrJnBm7a7C+5aYyBoa8YxO6r/ccdyjGPB0LKVXW5MtYJvwyGJ5GNKY9dhwePWs2ULNA8VnYIHGgFohBNkc4jRJHpiOrUMDpXIMdQ7CprJ+X3MwkF9pFCfnU2EfOCvOieyFm5KwyVMZjIaRKHgwlvlY109lK7ls2nLNmgqIW/lEg+e7CFp3DWubtj4gzzJLWEkua1xDCdRLD0TjTDAqMNppg3++AW/HfccJjGi6Jc7lUxlHKckxvzyF2wfMHVb96j5coOODcBt1/gtK8SdpXiVwb0jU7FpuVvu3SSez3e2d+r8V4faGt+sfV+C3cg5Atdvfcs0ZIrRztEbeu84Dhp3K4sz+SizWa7JaaWiUY0I8w07mnpcXdwWForDNnMm25RIc1vNQ65H1DKfVGmQ8MN4Vz5o8n9ksNHNbzk362QAuHUGhnZjvXVtFMBgPUvqgIiICIiAiIgIiICIiAiIgIiIMNsskcrHRysa9jhQtcA5p4gqqM7+R4G9Lk9106eZefJ4RvOjg7vCt1EH5Kt1lls7zFaI3RvGkOFHcd43r4010Yr9RZfzfs1sj5u0RNeNR0SNO1jhiFTWd3JPaLNelsZM8em5/rtHV0P7MdyvRwbdlMdmtbHMUFZDdGzX3+4LFBbJAebbHV9aUob1dl3buXf5q8k1otBbLbnGFmnmxTnyNlNEfbU7k6OFskctoeIbLE57joDRV3HcN5VoZo8jwFJcoOvHA8yw+TwkeNPBveVZeQsg2eyR83Z4mxt1kdNx2uccXHipJQYLHZI4mNjiY1jG4BrAGtHYFnREBERAREQEREBERAREQEREBERAREQEREBERBhFkjvX7jb/wBK6L/fpWZEQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREH//Z)
  description: >
    The Castle Point Clan Family has clans spanning across a multitude of Supercell games, be it Clash Royale, Clash of Clans, Clash Mini, and Brawl Stars. We pride ourselves on having achieved a local ranking of top 50 US clans in war, and having an extremely active and humorous community. We prioritize dedication to the clan over self, as it leads to a higher sense of fulfillment. Now what are you waiting for, join up, and always remember: FOR THE GLORY OF CASTLE POINT
  social:
    - discord: http://discord.gg/48hePvZJYm
    -  twitter: http://twitter.com/Castle_PointCR
clans:
  - name: Castle Point
    tag: 9LUYGPGQ
  - name: Castle Point 2
    tag: LCYQGGJR
```

**Comment by smlbiobot** [comment]
don’t support data image. attach image to comment

**Comment by smlbiobot** [comment]
```yml
name: Castle Point Family
key: cp
color: blue
emblem: Crown_03
info:
  description: >
    The Castle Point Clan Family has clans spanning across a multitude of Supercell games, be it Clash Royale, Clash of Clans, Clash Mini, and Brawl Stars. We pride ourselves on having achieved a local ranking of top 50 US clans in war, and having an extremely active and humorous community. We prioritize dedication to the clan over self, as it leads to a higher sense of fulfillment. Now what are you waiting for, join up, and always remember: FOR THE GLORY OF CASTLE POINT
  social:
    - discord: https://discord.gg/48hePvZJYm
    - twitter: https://twitter.com/Castle_PointCR
clans:
  - name: Castle Point
    tag: 9LUYGPGQ
  - name: Castle Point 2
    tag: LCYQGGJR
```
