### ISSUE TITLE
Request to add Dark AlliancemX family 

### ISSUE THREAD

**Issue by Mikilol77** [RoyaleAPI/family-config#928]
...yaml
name: dark AllianceMX 
key: DAMX
color: purple
emblem: Star_Shine_03
info: 
     logo: 
     description:  >
     Famila  Dark AllianceMX contamos con 3 clanes, grupo de wats y alianza con otros clanes , en busca del top nacional 
     clans: 
     - name: Dark AllianceMX 
     tag: #92uu22jq
     - name: Dark Squad 
     tag: #9CVOPYVO
     - name: Mexico eSport
     tag: #98CLYUCL

...

**Comment by Mikilol77** [comment]
Hello Royaleapi team, I leave you this request to add my team to your page, thank you very much for your attention and a big hug

**Comment by smlbiobot** [comment]
you need to format this. i am not gonna format it for you.

please add spaces and not just dump a bunch of info here

**Comment by smlbiobot** [comment]
i will do it for you ONCE. no more

```yml
name: dark AllianceMX
key: DAMX
color: purple
emblem: Star_Shine_03
info:
  logo:
  description:  >
      Famila Dark AllianceMX contamos con 3 clanes, grupo de wats y alianza con otros clanes , en busca del top nacional
clans:
- name: Dark AllianceMX
  tag: 92uu22jq
- name: Dark Squad
  tag: 9CVOPYVO
- name: Mexico eSport
  tag: 98CLYUCL
```
