### ISSUE TITLE
Clan Family Update: Mage Knights

### ISSUE THREAD

**Issue by WhizGaming360** [RoyaleAPI/family-config#929]
```yaml
name: Mage Knights
key: mageknights
color: violet
emblem: A_Char_Knight_01
info:
  logo: https://cdn.discordapp.com/attachments/883063417064288276/1138725576543322232/MK_new_logo.jpg
  description: >
    **Welcome to the Mage Knights Clan Family!** Our main clan is primarily war focused, but there's always room for 
    improvement. Our Discord community is relatively unique based on Brawl Stars and Clash Royale playing competitively 
    and casually. Active, chill, friendly, mature, and organized. Apply in-game or check out our Discord to join us.
  social:
    - discord: https://dsc.gg/mageknights
clans:
  - name: Mage Knights
    tag: 2V28Y88Q
  - name: Mage Knights 2
    tag: YR00L2LY
```
