### ISSUE TITLE
Familia Gallinero

### ISSUE THREAD

**Issue by EGEevee** [RoyaleAPI/family-config#930]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: red
- `key`: Familia Gallinero
- `emblem`: https://cdn.royaleapi.com/static/img/badge/legendary-1/Sword_01.png?t=8b993eefc
- `description` and `links`: Somos la Familia Gallinero. Buscamos gente que se comprometa a jugar guerra de jueves a domingo con los 4 mazos. ¿Te unes a nosotros?
- `tag`:  L99R99U9

Fill in the configuration below:

```yaml
name: Familia Gallinero
key: Familia Gallinero
color: red
emblem: https://cdn.royaleapi.com/static/img/badge/legendary-1/Sword_01.png?t=8b993eefc
info: Somos la Familia Gallinero. Buscamos gente que se comprometa a jugar guerra de jueves a domingo con los 4 mazos. ¿Te unes a nosotros?
  logo: 
![image](https://github.com/RoyaleAPI/family-config/assets/124502288/01e3eb80-6dfc-4e32-8a1a-9efafba7defc)

  description: >
    Long paragraphs with markdown syntax.


    Add new line with 2 line breaks as above.
  social:
    - twitter: https://twitter.com/ElGallineroCR
    - instagram: https://www.instagram.com/el_gallinero_royale/
clans:
  - name: El Gallinero
    tag: L99R99U9
  - name: LOS GALACTICOS
    tag: LUJ89LQ
```

**Comment by smlbiobot** [comment]
format correctly in the future. not going to do it for you in the future.

```yml
name: Familia Gallinero
key: familia-gallinero
color: red
emblem: Sword_01
info:
  logo: /static/img/family/logo/familia-gallinero

  description: >
    Somos la Familia Gallinero. Buscamos gente que se comprometa a jugar guerra de jueves a domingo con los 4 mazos. ¿Te unes a nosotros?.
  social:
    - twitter: https://twitter.com/ElGallineroCR
    - instagram: https://www.instagram.com/el_gallinero_royale/
clans:
  - name: El Gallinero
    tag: L99R99U9
  - name: LOS GALACTICOS
    tag: LUJ89LQ
```
