### ISSUE TITLE
Dark Family

### ISSUE THREAD

**Issue by stormcloak4** [RoyaleAPI/family-config#931]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Dark Family
key: dark
color: purple
emblem: Skull_05
info:
  logo:
  description: >
    Top USA war and ladder clan - must come equipped with a twisted sense of humor
clans:
  - name: Dark Humor
    tag:2V2VRRLJ
  - name: Dark Vendetta
    tag:8UCRLJOJ
  - name: Dark Inception
    tag:8Y8UGOJJ
-name: Dark Disciples
tag:L2VCQOV8
-name: Dusted Compass
tag:Q8OYJGGG
-name: Dark Prestige
tag:QPY8OLRQ
-name: Dark Intentions
tag:YUYP9229
-name: Dark Paradox
tag:PC8YOQGY
```

**Comment by smlbiobot** [comment]
unacceptable format. 

```yml
name: Dark Family
key: dark
color: purple
emblem: Skull_05
info:
  logo:
  description: >
    Top USA war and ladder clan - must come equipped with a twisted sense of humor
clans:
- name: Dark Humor
  tag: 2V2VRRLJ
- name: Dark Vendetta
  tag: 8UCRLJOJ
- name: Dark Inception
  tag: 8Y8UGOJJ
- name: Dark Disciples
  tag: L2VCQOV8
- name: Dusted Compass
  tag: Q8OYJGGG
- name: Dark Prestige
  tag: QPY8OLRQ
- name: Dark Intentions
  tag: YUYP9229
- name: Dark Paradox
  tag: PC8YOQGY
```
