### ISSUE TITLE
Blablabla Familie

### ISSUE THREAD

**Issue by BlablablaMart** [RoyaleAPI/family-config#932]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: red
- `key`: blablabla_familie
- `emblem`: Flame_04

Fill in the configuration below:

```yaml
name: Blablabla Familie
key: blablabla_familie
color: red
emblem: Flame_04
info:
  logo: ![Flame_04](https://github.com/RoyaleAPI/family-config/assets/141874551/c24290a5-65b8-484a-a18e-13ce887efd61)
  description: >
    Willkommen bei  Blablabla. In unseren 4 unterschiedlichen Clans findet jeder leidenschaftliche Spieler das passende Zuhause. Als Team zu Sieg. Zusammenhalt und Spaß am Spiel werden bei uns GROSS geschrieben. Wir bieten zB. DC, Turniere,  Duos und Pass Royale. Wechsel innerhalb der Familie möglich. Das klingt gut? Unser Main Clan gehört zu den besten Kriegsclans in Deutschland oder doch lieber unsere gechillte Clanoase? Wir freuen uns über jeden aktiven Spieler
clans:
  - name: Blablabla
    tag: 98RVLCUY
  - name: Blablabla#2
    tag: LJGJV9YY
  - name: Blablabla#3
    tag: GL0JQR88
  - name: Blablabla4ever
    tag: QYR92VC8
```

**Comment by smlbiobot** [comment]
```yml
name: Blablabla Familie
key: blablabla_familie
color: red
emblem: Flame_04
info:
  logo: /static/img/family/logo/blablabla_familie.png
  description: >
    Willkommen bei  Blablabla. In unseren 4 unterschiedlichen Clans findet jeder leidenschaftliche Spieler das passende Zuhause. Als Team zu Sieg. Zusammenhalt und Spaß am Spiel werden bei uns GROSS geschrieben. Wir bieten zB. DC, Turniere,  Duos und Pass Royale. Wechsel innerhalb der Familie möglich. Das klingt gut? Unser Main Clan gehört zu den besten Kriegsclans in Deutschland oder doch lieber unsere gechillte Clanoase? Wir freuen uns über jeden aktiven Spieler
clans:
  - name: Blablabla
    tag: 98RVLCUY
  - name: Blablabla#2
    tag: LJGJV9YY
  - name: Blablabla#3
    tag: GL0JQR88
  - name: Blablabla4ever
    tag: QYR92VC8
```
