### ISSUE TITLE
clan addition to "dudes united"

### ISSUE THREAD

**Issue by robotdoggo** [RoyaleAPI/family-config#935]
CLAN ADDITION

name: Dudes United
key: dudesunited
color: black
emblem: Skull_06
info:
logo:
description: > we're looking for European, English speaking players that want to grow with the family trophy push. apply on discord.

social:
- twitter: http://twitter.com/
- discord: http://discord.gg/Gu7Bbsfwsd
- twitch: https://www.twitch.tv/
- reddit: http://www.reddit.com/
- youtube: https://www.youtube.com/channel/
- website: http://docs.redditalpha.com/
- instagram: https://instagram.com/
- facebook: https://facebook.com/
- twitch: https://twitch.tv/
- youtube: https://www.youtube.com/channel/
- application: https://url/
- email: mailto:
clans:

name: Dudes Reunited
tag: L0PQ2ULQ
name:Dudes academy
tag:GQYY2R82
name:#awesomesauce
tag:R2QLR8

**Comment by smlbiobot** [comment]
YOU MUST FORMAT IT NEXT TIME. i will do it for you once. no more.

```yml
name: Dudes United
key: dudesunited
color: black
emblem: Skull_06
info:
  description: >
    We're looking for European, English speaking players that want to grow with the
    family trophy push. apply on discord: discord.gg/edyQXqC2yB


clans:
- name: Dudes Reunited
  tag: L0PQ2ULQ
- name: Dudes academy
  tag: GQYY2R82
- name: '#awesomesauce'
  tag: R2QLR8
```
