### ISSUE TITLE
PTROYALEKINGS Family

### ISSUE THREAD

**Issue by jhorta01** [RoyaleAPI/family-config#936]
```yaml
name: PT ROYALE KINGS
key: pt-rk
color: black
emblem: A_Char_King_01
info:
  description: >
    The **PT ROYALE KINGS Family** is a Portuguese clan family and counts with 5 different clans. Each one for different types of players. **PT ROYALE KINGS** is our main ladder clan and **PT ROYALE KINGS 2** is our main clan focused on war. With the large influx of players we saw the need to create 3 more clans: **PT ROYALE KINGS 3** (War), **PT ROYALE KINGS 4** (War/Ladder) and **PT ROYALE KINGS 5** (Ladder).   
clans:
  - name: PT ROYALE KINGS
    tag: GG0YYCJ
  - name: PTROYALEKINGS 2
    tag: PVRCVY29
  - name: PTROYALEKINGS 3
    tag: GGRU0ULL
  - name: PTROYALEKINGS 4
    tag: Q9CL0GCQ
  - name: PTROYALEKINGS 5
    tag: GC0GYVLJ
```
