### ISSUE TITLE
Update: PhantomShadows

### ISSUE THREAD

**Issue by IvMisticos** [RoyaleAPI/family-config#937]
```yaml
name: Phantom Shadows
key: phantomshadows
color: blue
emblem: flag_e_01
info:
  social:
    - telegram: https://t.me/PhantomShadows
clans:
  - name: Phantom Shadows
    tag: YGGQCLC0
  - name: Revolte
    tag: 90L9YRCR
  - name: Night Terror
    tag: GVYLJY98
```
