### ISSUE TITLE
Andromeda Descendants

### ISSUE THREAD

**Issue by varelli01** [RoyaleAPI/family-config#939]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Andromeda Descendants
key: adfamily
color: purple
emblem: Diamond_Star_01
sort: trophy
info:
  logo: https://ibb.co/y0swWKN
  description: >
    Andromeda Descendants is the haven for those interested in an eSports
    environment and competetive war clan gameplay. We are an organized and
    aggresive clan family that has clans stretching over multiple levels of
    play. We offer professional coaching and community events for free in our
    Discord server. Come become an Andromeda Descendant today.
  social:
    - discord: https://discord.gg/adfamily
clans:
  - name: Hawaiian Beast
    tag: P2RPJQ2R
  - name: Fight Club USA
    tag: JGU2YLR
  - name: #active
    tag: 8PYL9U28
  - name: FUBAR
    tag: PGG2CYPG
  - name: dementiods
    tag: LJYJLPPQ
  - name: Andromeda L2W
    tag: GU8YJ28C
```

**Comment by varelli01** [comment]
We currently have an outdated family page (https://royaleapi.com/clan/family/andromeda-descendants/clans#) and would like to replace that one with a list of our current clans please!

**Comment by smlbiobot** [comment]
formatting

```yml
name: Andromeda Descendants
key: adfamily
color: purple
emblem: Diamond_Star_01
sort: trophy
info:
  logo: /static/img/family/logo/adfamily.png
  description: >
    Andromeda Descendants is the haven for those interested in an eSports
    environment and competetive war clan gameplay. We are an organized and
    aggresive clan family that has clans stretching over multiple levels of
    play. We offer professional coaching and community events for free in our
    Discord server. Come become an Andromeda Descendant today.
  social:
    - discord: https://discord.gg/adfamily
clans:
  - name: Hawaiian Beast
    tag: P2RPJQ2R
  - name: Fight Club USA
    tag: JGU2YLR
  - name: '#active'
    tag: 8PYL9U28
  - name: FUBAR
    tag: PGG2CYPG
  - name: dementiods
    tag: LJYJLPPQ
  - name: Andromeda L2W
    tag: GU8YJ28C
```
