### ISSUE TITLE
Aspect Family

### ISSUE THREAD

**Issue by Harneyg21** [RoyaleAPI/family-config#940]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Aspect Family
key: Aspect
color: blue
emblem: flag_l_03
info:
  description: >
  Originally founded on September 23rd, 2021. Aspect is a dedicated war family that values communication and teamwork amongst our members. Setting weekly requirements that vary amongst our clans. With dedicated leadership that is constantly looking to develop the clan family and help its members. We offer an active community, consistent 1st place in wars, donations, and more. If you're looking for a solid group of players, check us out.


  social:
    - discord: https://discord.gg/prztXwaxgs


clans:
  - name: Aspect
    tag: QVVRQRJL
  - name: Aspect v2
    tag: G2G8QL8G
```

**Comment by smlbiobot** [comment]
```yml
name: Aspect Family
key: Aspect
color: blue
emblem: flag_l_03
info:
  description: Originally founded on September 23rd, 2021. Aspect is a dedicated war family that values communication and teamwork amongst our members. Setting weekly requirements that vary amongst our clans. With dedicated leadership that is constantly looking to develop the clan family and help its members. We offer an active community, consistent 1st place in wars, donations, and more. If you're looking for a solid group of players, check us out.
  social:
    - discord: https://discord.gg/prztXwaxgs
clans:
  - name: Aspect
    tag: QVVRQRJL
  - name: Aspect v2
    tag: G2G8QL8G
```
