### ISSUE TITLE
added "Alpenkommando 7" and "#Liebe Freunde" to the Family. THX

### ISSUE THREAD

**Issue by TwitchViruxcrew** [RoyaleAPI/family-config#941]
```yaml
name: Alpenkommando Family
key: Alpenkommando
color: white
emblem: Skull_06
info:
  logo: https://ibb.co/cY0GJ5J
  description: >
   Wir sind eine starke Clankriegsorientierte Familie aus Österreich. Wir haben für jeden Spieler einen Clan ob Anfänger oder Erfahren spielt keine Rolle. Wir bieten außerdem einen aktiven discord server und regelmäßige Clanturniere und auch Turniere mit Preisgeldern
  social:
    - discord: https://discord.gg/jxH4RNMwwc
clans:
  - name: Alpenkommando
    tag: LGP0G8
  - name: die aktiven
    tag: PV82JJYQ
  - name: #Liebe Freunde
    tag: 82JQVVQQ
  - name: Clashvania
    tag: 8R22P9VY
  - name: Alpenkommando 2
    tag: P8CGCYV2
  - name: Alpenkommando 3
    tag: L0RYG02U
  - name: Alpenkommando 4
    tag: GGCVYG09
  - name: gelber blitz
    tag: QCPCJ9Y0
  - name: Alpenkommando 7
    tag: G2QLVQUG
  - name: Alpenkommando 5
    tag: Q8UPR9RL

**Comment by smlbiobot** [comment]
don’t change logo url if you didn’t upload new ones

```yml
name: Alpenkommando Family
key: alpenkommando
color: white
emblem: Skull_06
info:
  logo: /static/img/brands/logo/alpenkommando.png
  description: >
    Wir sind eine starke Clankriegsorientierte Familie aus Österreich. Wir haben für
    jeden Spieler einen Clan ob Anfänger oder Erfahren spielt keine Rolle. Wir bieten
    außerdem einen aktiven discord server und regelmäßige Clanturniere.
  social:
  - discord: https://discord.gg/jxH4RNMwwc
clans:
  - name: Alpenkommando
    tag: LGP0G8
  - name: die aktiven
    tag: PV82JJYQ
  - name: '#Liebe Freunde'
    tag: 82JQVVQQ
  - name: Clashvania
    tag: 8R22P9VY
  - name: Alpenkommando 2
    tag: P8CGCYV2
  - name: Alpenkommando 3
    tag: L0RYG02U
  - name: Alpenkommando 4
    tag: GGCVYG09
  - name: gelber blitz
    tag: QCPCJ9Y0
  - name: Alpenkommando 7
    tag: G2QLVQUG
  - name: Alpenkommando 5
    tag: Q8UPR9RL

```
