### ISSUE TITLE
Vengeance Clan Family

### ISSUE THREAD

**Issue by modesta3** [RoyaleAPI/family-config#942]
Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:

- `color`: should be all lower case
- `key`: will be used in the URL. Convention is to use all lower case
- `emblem`: do not include the file extension `.png`
- `description` and `links`: delete the lines if you have none
- `tag`:  do not include the `#` hash tag with the clan tags

Fill in the configuration below:

```yaml
name: Vengeance Clan Family
key: vengeance
color: blue
emblem: yingyang_01
Sort: trophy
info: 
  logo: https://cdn.discordapp.com/attachments/1151085793067143201/1151958478479441980/IMG_3687.png
  description: >
The Home for Everyone. We are a sanctuary for passionate gamers, a community where friendship thrives, and competitiveness reigns supreme. We open our doors to all, regardless of their skill level or experience. Here, you will find a haven for your competitive spirit and the opportunity to grow as a player.

We are one of the most respected and enduring communities in Clash Royale. From novice players to battle-hardened veterans, everyone has a place in our family. We invite you to become a part of this great community and discover a world of opportunities to improve your skills, forge new friendships, and be a part of something greater than yourself.
  social:
    - discord: https://discord.gg/RGKtbQXB3f
    - twitter: https://twitter.com/vengeance_CR
    - email: 21realvengeance@gmail.com
clans:
  - name: Vengeance 
    tag: PQRUQJ
  - name: KMKC BROS
    tag: 2PYV82Y0
  - name: 300 invencibles 
    tag: Y089U
  - name: Team Hunter
    tag: 92C09GR0
  - name: Vengeance II
    tag: 88G29YJ9
  - name: Anteiku™
    tag: LUC029R9
  - name: Plata o Plomo
    tag: 8P2J0PJ9
  - name: ETERNAL VEN 
    tag: QC9LVQ8R
  - name: kmkc bros 2
    tag: Q9G28PLC
  - name: kmkc bros 3 
    tag: QG0VLC8U
  - name: La Perla Negra
    tag: YV280PPP
  - name: Vengeance III
    tag: QCC2RGC8
  - name: Khazad-dûm
    tag: GYGUPYR0
```
