### ISSUE TITLE
Familia Gallinero

### ISSUE THREAD

**Issue by EGEevee** [RoyaleAPI/family-config#946]
### Family name

Familia Gallinero

### Family URL

https://royaleapi.com/clan/family/gallinero/clans

### Family configuration

```yaml
name: Familia Gallinero
key: familia-gallinero
color: red
emblem: Sword_01
info:
  logo: /static/img/family/logo/familia-gallinero

  description: >
    Somos la Familia Gallinero. Buscamos gente que se comprometa a jugar guerra de jueves a domingo con los 4 mazos. ¿Te unes a nosotros?.
  social:
    - twitter: https://twitter.com/ElGallineroCR
    - instagram: https://www.instagram.com/el_gallinero_royale/
clans:
  - name: El Gallinero
    tag: L99R99U9
  - name: LOS GALACTICOS
    tag: LUJ89LQP
```

### Additional Info

Hemos cerrado el clan As Burgas y hemos añadido el clan LOS GALACTICOS

**Comment by Zaop7** [comment]
```yml
name: Familia Gallinero
key: familia-gallinero
color: red
emblem: Sword_01
info:
  logo: /static/img/family/logo/familia-gallinero

  description: >
    Somos la Familia Gallinero. Buscamos gente que se comprometa a jugar guerra de jueves a domingo con los 4 mazos. ¿Te unes a nosotros?.
  social:
    - twitter: https://twitter.com/ElGallineroCR
    - instagram: https://www.instagram.com/el_gallinero_royale/
clans:
  - name: El Gallinero
    tag: L99R99U9
  - name: LOS GALACTICOS
    tag: LUJ89LQP
```
