### ISSUE TITLE
suppression de 2 clans de la famille

### ISSUE THREAD

**Issue by MIKO1976** [RoyaleAPI/family-config#947]
### Family name

Put your the current name here

### Family URL

Copy the link (URL address) from your browser and paste it here.

### Family configuration

```yaml
name: WarxUnion & rugbyman Family
key: warxunion
color: black
emblem: Flame_03
info:
  logo: /static/img/brands/logo/warxunion.png
  description: >
    "WarxUnion & rugbyman Family.
Here you can progress in a World Top gaming environment with a professional organization.
Do not hesitate to apply, surely your profile is suitable for one of our clans.
Friendly and cooperative atmosphere in our family!"


  social:
    - discord: https://discord.gg/8cvV6xUWZU
    - instagram: https://instagram.com/warxunion_family?r=nametag
    - youtube: https://m.youtube.com/@miami54cr96?itct=CC0QoTAYASITCPLzn_eWwvsCFeVBTwQd_IwBrQ%3D%3D
    - tic: https://www.twitch.tv/mathysss2?sr=a
 

  clans:
  - name: WarxUnion 2
    tag: 2UQ2VCCC
  - name: rugbyman 41
    tag: 8RC2PJC2
  - name: #CRF
    tag: YPYGYYYR
  - name: bang bang bang!
    tag: 9VPRG2V2
  - name: 10000 guerriers
    tag: JQ0QJ0
  - name: #Team guerrier
    tag: UC2JGR
  - name: bang bang bang2
    tag: L0R9GRG8 
…
```
