### ISSUE TITLE
[Update]: Purjehdus Community

### ISSUE THREAD

**Issue by HexHeikki** [RoyaleAPI/family-config#952]
### Family name

Purjehdus Community

### Family URL

https://royaleapi.com/clan/family/purjehdus/clans

### Family configuration

```yaml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, FB Esports, Laivanupotus, hikipaatti
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP
```

### Additional Info

One clan added (name: hikipaatti, tag: Q8CCU8UP)

**Comment by Zaop7** [comment]
```yml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, Laivanupotus
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP

```

**Comment by HexHeikki** [comment]
Issue edited ones more! One more clan added, hopefully not too late. 🤞🏼 New yaml below.

**Comment by HexHeikki** [comment]
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, Laivanupotus
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP

**Comment by HexHeikki** [comment]
```yaml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, Laivanupotus
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP
```

**Comment by HexHeikki** [comment]
```yaml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, FB Esports, Laivanupotus, hikipaatti
  social:
  - discord: http://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP
```

**Comment by Zaop7** [comment]
```yml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, Laivanupotus
  social:
  - discord: https://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP

```

**Comment by HexHeikki** [comment]
> ```yaml
> name: Purjehdus Community
> key: purjehdus
> color: red
> emblem: flag_j_02
> info:
>   logo: /static/img/brands/logo/purjehdus.png
>   description: >
>     **Purjehdus Community**
> 
> 
>     Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
>     Community is meant for Finnish speaking players from all ages.
> 
> 
>     **Ladder Clans:** Purjehdus, Seilaus, Veneily
>     **War Clans:** NC Finland, Suomi Soturit, Laivanupotus
>   social:
>   - discord: https://discord.gg/vjeUGTApzf
>   - twitch: https://twitch.tv/purjehdus
> clans:
> - name: Purjehdus
>   tag: QRPQCUQU
> - name: Seilaus
>   tag: LQ2PL8Y8
> - name: Veneily
>   tag: G9YCPUYL
> - name: NC Finland
>   tag: 8LP0Y9YP
> - name: ✨SUOMI SOTURIT✨
>   tag: 9YY9QL2Y
> - name: FB Esports
>   tag: Y0R22Y0V
> - name: Laivanupotus
>   tag: Q99CPQYR
> - name: hikipaatti
>   tag: Q8CCU8UP
> ```

This is still incorrect, description also got updated to include the new clans added. My original post and comment are both correct so please copy from there. 🙂

**Comment by Zaop7** [comment]
Sorry, i didn't notice. This should be correct now.
```yml
name: Purjehdus Community
key: purjehdus
color: red
emblem: flag_j_02
info:
  logo: /static/img/brands/logo/purjehdus.png
  description: >
    **Purjehdus Community**


    Purjehdus is the largest Finnish Clash Royale clan family and discord. Purjehdus
    Community is meant for Finnish speaking players from all ages.


    **Ladder Clans:** Purjehdus, Seilaus, Veneily
    **War Clans:** NC Finland, Suomi Soturit, FB Esports, Laivanupotus, hikipaatti
  social:
  - discord: https://discord.gg/vjeUGTApzf
  - twitch: https://twitch.tv/purjehdus
clans:
- name: Purjehdus
  tag: QRPQCUQU
- name: Seilaus
  tag: LQ2PL8Y8
- name: Veneily
  tag: G9YCPUYL
- name: NC Finland
  tag: 8LP0Y9YP
- name: ✨SUOMI SOTURIT✨
  tag: 9YY9QL2Y
- name: FB Esports
  tag: Y0R22Y0V
- name: Laivanupotus
  tag: Q99CPQYR
- name: hikipaatti
  tag: Q8CCU8UP

```
