### ISSUE TITLE
[Update]: Apex Aussies Update

### ISSUE THREAD

**Issue by barxnet** [RoyaleAPI/family-config#954]
### Family name

Apex Aussies Clash Royale Family

### Family URL

https://royaleapi.com/clan/family/ApexAussies/clans

### Family configuration

```yaml
name: Apex Aussies Clash Royale Family
key: ApexAussies
color: blue
emblem: flag_b_03
info:
  logo: http://alanoconnell.com/apex/Apex_Aussies.jpg
  description: >
    Welcome to Apex Aussies Clash Royale Family.  We are a family clan made up of 10 clans.  We cater to all levels of players, from our top level clans where all players must complete all war battles every week to more casual river race clans and non river race clans.  We have a strong Discord community with something for everyone.  Most importantly, we enjoy the game!
  social:
    - discord: https://Discord.gg/Xc28XcwWQ2
clans:
  - name: Apex Aussies
    tag: 9LYCV200
  - name: Apex Aussies 2
    tag: LQLP0R0L
  - name: Apex Aussies 3
    tag: YUVUQUPV
  - name: Apex Aussies 4
    tag: G9QV0UYQ
  - name: Apex Aussies 5
    tag: LQUPR00J
  - name: Apex Aussies 6
    tag: GG2Y0V20
  - name: Apex Aussies 7
    tag: Q9QG9V0U
  - name: Apex Aussies 8
    tag: Q8P08YPV
  - name: Apex Aussies 9
    tag: QRJRYPG9
  - name: Apex Aussies 10
    tag: LUVYUCQQ
```

**Comment by Zaop7** [comment]
```yml
name: Apex Aussies Clash Royale Family
key: ApexAussies
color: blue
emblem: flag_b_03
info:
  logo: /static/img/brands/logo/apex-aussies.png
  description: "Welcome to Apex Aussies Clash Royale Family.  We are a family clan\
    \ made up of 10 clans.  We cater to all levels of players, from our top level\
    \ clans where all players must complete all war battles every week to more casual\
    \ river race clans and non river race clans.  We have a strong Discord community\
    \ with something for everyone.  Most importantly, we enjoy the game!\n"
  social:
  - discord: https://Discord.gg/Xc28XcwWQ2
clans:
  - name: Apex Aussies
    tag: 9LYCV200
  - name: Apex Aussies 2
    tag: LQLP0R0L
  - name: Apex Aussies 3
    tag: YUVUQUPV
  - name: Apex Aussies 4
    tag: G9QV0UYQ
  - name: Apex Aussies 5
    tag: LQUPR00J
  - name: Apex Aussies 6
    tag: GG2Y0V20
  - name: Apex Aussies 7
    tag: Q9QG9V0U
  - name: Apex Aussies 8
    tag: Q8P08YPV
  - name: Apex Aussies 9
    tag: QRJRYPG9
  - name: Apex Aussies 10
    tag: LUVYUCQQ

```
