### ISSUE TITLE
[New]: War Seekers Clan Family

### ISSUE THREAD

**Issue by modesta3** [RoyaleAPI/family-config#955]
### Family configuration

```yaml
name: War Seekers Clan Family
key: warseekers
color: pink
emblem: Bolt_01
Sort: trophy
info:
  logo: https://cdn.discordapp.com/attachments/1118316432762089523/1160006046081876059/WSPanther_Static.jpg
  description: >
    War Seekers is a club of Tutti Frutti clans from far and wide. We strive to provide a unique, positive, competitive and fun clash royale experience; safe for players of all ages. Globally and locally ranked in both ladder and clan wars. Join our tournaments and eSports events! Use our coaches for guidance in game play and deck building. We also provide support for Clash of Clans.
  social:
    - discord: https://discord.gg/warseekers
    - email: warseekersfam@gmail.com
clans:
  - name: High Seekers
    tag: PGY8GY2
  - name: 204 boy scouts 
    tag: JGQPU8Q
  - name: Epic Elite
    tag: PJ2YR2P2
  - name: Blessed worthy
    tag: YR0UYR2L
  - name: AmericanEaglets
    tag: YYGV92UQ
  - name: K.O. Team 
    tag: 8CQPRYVV
  - name: Hail Dooms
    tag: 2090YG9J
  - name: BingePlayers 
    tag: L92JJ9Q0
  - name: Clan Canada
    tag: Q08P92VP
  - name: DAUNTLESS 
    tag: QV2C2R9U
  - name: the goods
    tag: Q9GVGLCC
  - name: Anarchy 
    tag: Q9JJJRLR
  - name: 90% Anarchy 
    tag: QYUPPVVV
  - name: Canada Inc
    tag: 992YUL
  - name: WS eSports
    tag: QPU2YU9L
  - name: Doom Seekers
    tag: QJPRGVLV
```

### Additional Info

Epic Elite (PJ2YR2P2) & K.O. Team (8CQPRYVV) are currently listed under the SWARM clan Family, but that family does not exist anymore. Please remove their page. https://royaleapi.com/clan/family/swarm/clans
![IMG_2181](https://github.com/RoyaleAPI/family-config/assets/145060032/f694beb8-5e6a-43a2-bbaa-c76a7bfeb767)
![IMG_2182](https://github.com/RoyaleAPI/family-config/assets/145060032/60d24d7f-55ab-454e-b7d0-08dbf7772130)
