### ISSUE TITLE
[New]: Kings of Fire

### ISSUE THREAD

**Issue by rizzo-M4M** [RoyaleAPI/family-config#956]
### Family configuration

```yaml
name: Kings of Fire War Family
key: kings-of-fire
color: black
emblem: Crown_04.png
info:
  logo: https://user-images.githubusercontent.com/98512123/280101943-ecf8f0d4-c5b9-471f-ad75-c17dd1b43e5b.gif
  
  description: >
🔥WAR⚔️MACHINES⚔️ONLY🔥

*Apply on discord*

  social:
    - discord: https://discord.gg/KingsOfFire
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: StillLegendary
    tag: 9CGYVG92
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Elixir Thieves™
    tag: YG2LUQLC
  - name: M for mature
    tag: 2909VP
  - name: League of Kings
    tag: LO9UQL9Y
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Bonecrushers
    tag: 20YLRYU
  - name: Fiery Embers
   tag: QCC9C8UR
  - name: War Clan
    tag: YVJR8C2G
  - name: Crying Fire 2
   tag: GYUJYJJP
  - name: Crying Fire 3
  tag: Q0PL9VRR
  - name: Embers of Fire
  tag: Q8QQ90L0
  - name: L Ξ G I O N
  tag: Q0UYQUC8
  - name: Newbie Farm
    tag: RGJC28
  - name: Bench
    tag: PUJ00YQJ
  - name: Second.2.None
    tag: Q2VCPVGV

```

### Additional Info

replacing the following two clan families:
galactic-kings
crying-fire

**Comment by Zaop7** [comment]
![image](https://github.com/RoyaleAPI/family-config/assets/107495129/64a7754f-5339-4adb-911a-62c6aa2ece61)

I think GIFs aren't supported.

**Comment by Zaop7** [comment]
```yml
name: Kings of Fire War Family
key: kings-of-fire
color: black
emblem: Crown_04.png
sort: trophy
info:
  logo: https://media.discordapp.net/attachments/916699111636467732/1164242935127216280/KOF20FINAL-2.gif?ex=654280ba&is=65300bba&hm=86a17ebb9d27be8c63f0eebc38f47964075e5eb138573c464f3293ffde776c8e&
  description: >
    🔥WAR⚔️MACHINES⚔️ONLY🔥

    *Apply on discord*

  social:
    - discord: https://discord.gg/KingsOfFire
clans:
  - name: Galactic Kings
    tag: Y9202P9U
  - name: Crying Fire
    tag: 8Y2LVVQ9
  - name: StillLegendary
    tag: 9CGYVG92
  - name: Alpha Steel
    tag: 9PV9JL
  - name: Blood N Bones
    tag: 2PQY2VQR
  - name: Thunder Buddies
    tag: GL0J0R
  - name: Elixir Thieves™
    tag: YG2LUQLC
  - name: Rogue Kingdom
    tag: YVVC0JJU
  - name: League of Kings
    tag: LO9UQL9Y
  - name: Crying Fire™
    tag: LQQJQULG
  - name: Bonecrushers
    tag: 20YLRYU
  - name: War Clan
    tag: YVJR8C2G
  - name: Iron Made
    tag: Q9Q9R8RL
  - name: Newbie Farm
    tag: RGJC28
  - name: Bench
    tag: PUJ00YQJ
  - name: Second.2.None
    tag: Q2VCPVGV

```
