### ISSUE TITLE
Kround

### ISSUE THREAD

**Issue by Baooooool** [RoyaleAPI/family-config#959]
```yaml
name: Kround
key: URL shortname
color: red
emblem: Crown_01
sort: trophy
info:
 description: >
  **Comunitatea Kround**, formata in jurul clanului **Kround** din top local(RO), contine 4 clanuri asociate. Mai mult de 100 de jucatori continua acum sa creasca mai departe in spiritul nostru. Te asteptam alaturi de noi!
     Clanuri: Kround, Kround Academy, Kround Academy 2, Kround Parking 
  social:
  - discord: https://discord.gg/xrZkS8kW
clans: 
  - name: Kround
    tag: 98UPQ0LC
  - name: Kround Academy
    tag: LRUQ90VV
  - name: Kround Academy2
    tag: Q9Y0YGUG
  - name: Kround Parking
    tag: G8PVGUQ2
…
```

**Comment by Zaop7** [comment]
```yml
name: Kround
key: kround
color: red
emblem: Crown_01
sort: trophy
info:
  description: >
    **Comunitatea Kround**, formata in jurul clanului **Kround** din top local(RO), contine 4 clanuri asociate. Mai mult de 100 de jucatori continua acum sa creasca mai departe in spiritul nostru. Te asteptam alaturi de noi!
    Clanuri: Kround, Kround Academy, Kround Academy 2, Kround Parking 
  social:
    - discord: https://discord.gg/xrZkS8kW
clans: 
  - name: Kround
    tag: 98UPQ0LC
  - name: Kround Academy
    tag: LRUQ90VV
  - name: Kround Academy2
    tag: Q9Y0YGUG
  - name: Kround Parking
    tag: G8PVGUQ2

```
