### ISSUE TITLE
Pushing to 6.3k Clan

### ISSUE THREAD

**Issue by Blackdeathcr** [RoyaleAPI/family-config#960]
```yaml
name: Pushing to 6.3k
key: https://royaleapi.com/clan/YU00V099
![IMG_7847](https://github.com/RoyaleAPI/family-config/assets/149338742/1c59bcd9-b4b9-4f63-8d4d-0df51bb421a7)

color: blue
emblem: 
![image](https://github.com/RoyaleAPI/family-config/assets/149338742/cad727fb-372d-407d-a97a-52b3ac8d2b05)

…
```
