### ISSUE TITLE
[New]: New clan family: TRTarmy

### ISSUE THREAD

**Issue by TheRodriguezTwins** [RoyaleAPI/family-config#961]
### Family configuration

```yaml
` YAML name: TRTarmy
key: TRTarmy
color: red
emblem: Skull_01
clans:
  - name: TRT Army
    tag: 88YVJYQC
`
```

**Comment by Zaop7** [comment]
```yml
name: TRTarmy
key: TRTarmy
color: red
emblem: Skull_01
clans:
  - name: TRT Army
    tag: 88YVJYQC

```
