### ISSUE TITLE
[Update]: 

### ISSUE THREAD

**Issue by vI1nekto** [RoyaleAPI/family-config#962]
### Family name

Русский Клан ▪️ Family🚀

### Family URL

https://royaleapi.com/clan/family/RusClan/clans

### Family configuration

```yaml
name: Русский Клан • Union🚀
key: RusClan
color: blue
emblem: A_Char_Rocket_01
info: 
  logo: https://github.com/RoyaleAPI/family-config/assets/118662333/2b6c8f8b-70a9-41ba-bf16-aa9e12f256a6
  description: |
    **Русский Клан** - клан для приверженцев евро-традиционного пути России🇷🇺🗽
    Высокий актив, крупная Tg-беседа, приятные собеседники, а также ценные призы:)
    
    P.S. Состоит из _флагманского💜, основного👑, академического🎓_ и дружественных кланов соответственно!
  social:
    - telegram: https://t.me/RusClan_CR/1642
    - telegram: https://t.me/CR_Resume/6
clans:
  - name: Vertical
    tag: JC9JC9P
  - name: Русский Клан
    tag: LRVPQJRR
  - name: Русский клан
    tag: PY0JRL8Q
  - name: Vertical II
    tag: YC08PPVC
  - name: Newlenders
    tag: QY8L9V0G
```

### Additional Info

I found a solution for the logo here: https://discuss.royaleapi.com/t/clan-family-logo/3857
Also made several other amendments:)

I hope I didn't mess up anything:) Thank you very much

**Comment by Zaop7** [comment]
```yml
name: Русский Клан ▪️ Union🚀
key: RusClan
color: blue
emblem: A_Char_Rocket_01
info:
  logo: https://github.com/RoyaleAPI/family-config/assets/118662333/2b6c8f8b-70a9-41ba-bf16-aa9e12f256a6
  description: >
    **Русский Клан** - клан для приверженцев евро-традиционного пути России🇷🇺🗽
    Высокий актив, крупная Tg-беседа, приятные собеседники, а также ценные призы:)
    
    P.S. Состоит из _флагманского💜, основного👑, академического🎓_ и дружественных кланов соответственно!
  social:
    - telegram: https://t.me/RusClan_CR/1642
    - telegram: https://t.me/CR_Resume/6
clans:
  - name: Vertical
    tag: JC9JC9P
  - name: Русский Клан
    tag: LRVPQJRR
  - name: Русский клан
    tag: PY0JRL8Q
  - name: Vertical II
    tag: YC08PPVC
  - name: Newlenders
    tag: QY8L9V0G

```
