### ISSUE TITLE
Adults Only UK 

### ISSUE THREAD

**Issue by matthewgtaylor999** [RoyaleAPI/family-config#963]
name: AdultsOnlyUK Clan Family
key: AdultsOnlyUK
color: red
emblem: Sword_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    Representing the UK and expanding our base actively, we're a family of War Clans looking for friendly competitors as we challenge for the top spot!
  social:
    - discord: https://discord.gg/c8x8YcnYV5
clans:
  - name: Adults Only UK
    tag: UQJJVP9
  - name: AOUK Feeder
    tag: Q98LCQQQ
  - name: AdultsOnlyUK 2
    tag: QP0QGRGJ
  - name: AdultsOnlyUK 3
    tag: R09UR9J2
  - name: AdultsOnlyUK5
    tag: GJ8CP2CY
  - name: AdultsOnlyUK6
    tag: QYG2GUYY

**Comment by Zaop7** [comment]
Next time, please format it like this:
```yml
name: AdultsOnlyUK Clan Family
key: AdultsOnlyUK
color: red
emblem: Sword_01
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
    Representing the UK and expanding our base actively, we're a family of War Clans looking for friendly competitors as we challenge for the top spot!
  social:
    - discord: https://discord.gg/c8x8YcnYV5
clans:
  - name: Adults Only UK
    tag: UQJJVP9
  - name: AOUK Feeder
    tag: Q98LCQQQ
  - name: AdultsOnlyUK 2
    tag: QP0QGRGJ
  - name: AdultsOnlyUK 3
    tag: R09UR9J2
  - name: AdultsOnlyUK5
    tag: GJ8CP2CY
  - name: AdultsOnlyUK6
    tag: QYG2GUYY

```
