### ISSUE TITLE
[Update]: CR Adultes FR (update website and mail link)

### ISSUE THREAD

**Issue by AnkoWCR** [RoyaleAPI/family-config#964]
### Family name

CR ADULTES FR Family

### Family URL

https://royaleapi.com/clan/family/cradultesfr/clans

### Family configuration

```yaml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: ![tortugalogofavicon2](https://github.com/RoyaleAPI/family-config/assets/92339610/7db17dc6-c737-4b4d-962e-91dd8ef60965)
description: >
La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en GDC.**
Esprit d'équipe, fun & entraide.
**Rejoignez-nous**
social:
    - website: https://www.cradultesfr.fr
    - email: mailto:cradultesfr@protonmail.com
clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: Q0VJ9YRJ
```

### Additional Info

![tortugalogofavicon2](https://github.com/RoyaleAPI/family-config/assets/92339610/7db17dc6-c737-4b4d-962e-91dd8ef60965)

**Comment by Zaop7** [comment]
```yml
name: CR ADULTES FR Family
key: cradultesfr
color: blue
emblem: flag_k_01
info:
  logo: /static/img/brands/logo/cr-adultes-fr-2.png
  description: >
    La Famille **CR ADULTES FR** rassemble des clans d'adultes français **actifs en GDC.**
    Esprit d'équipe, fun & entraide.
    **Rejoignez-nous**
  social:
    - website: https://www.cradultesfr.fr
    - email: mailto:cradultesfr@protonmail.com
clans:
  - name: CR ADULTES FR
    tag: 9JV9GGC0
  - name: CR ADULTES FR 2
    tag: YJVVPR98
  - name: CR ADULTES FR 3
    tag: L00CYCQV
  - name: CR ADULTES FR 4
    tag: Q0VJ9YRJ

```
