### ISSUE TITLE
[Update]: Liverpool

### ISSUE THREAD

**Issue by Liverpool-Clan** [RoyaleAPI/family-config#965]
### Family name

Liverpool

### Family URL

https://royaleapi.com/clan/family/liverpool/clans

### Family configuration

```yaml
name: Liverpool Family
key: liverpool
color: red
emblem: flag_f_02
info:
  logo: 
  description: >
    This is Anfield. We are Liverpool. Global international Liverpool F.C. supporters into clash royale. Top 50 International Clan War clan. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!
  social:

clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
  - name: Liverpool Spion
    tag: GJVG2V82
```

**Comment by Zaop7** [comment]
```yml
name: Liverpool Family
key: liverpool
color: red
emblem: flag_f_02
info:
  description:
    "This is Anfield. We are Liverpool. Global international Liverpool\
    \ F.C. supporters into clash royale. Top 50 International Clan War clan. Be a\
    \ part of our ever growing Liverpool family clans. You'll Never Walk Alone!\n"
clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
  - name: Liverpool Spion
    tag: GJVG2V82

```
