### ISSUE TITLE
[Update]: 

### ISSUE THREAD

**Issue by PokegetaTV** [RoyaleAPI/family-config#966]
### Family name

OlimposEsports Family

### Family URL

https://royaleapi.com/clan/family/OlimposEsports/clans

### Family configuration

```yaml
name: OlimposEsports Family
key: OlimposEsports
color: [pink]
emblem: ![Flame_01](https://user-images.githubusercontent.com/83083991/218118289-420feb83-ed23-4e27-98fe-7a44a21049e8.png)

 info:
  logo: ![Picsart_22-10-20_22-06-55-434](https://user-images.githubusercontent.com/83083991/215850391-fd4f4320-e107-4183-bf46-53bd37a5db4b.png)
social:
    - website: https://mifaxp.webnode.es
    - twitter: https://twitter.com/mifaxp
    - discord: https://discord.gg/TceEpJbuhe
    - twitter: https://twitter.com/OlimposClanes
    - discord: https://discord.gg/Up4uyuPd7j
    - twitter: https://twitter.com/OlimposEsports
    - discord: https://discord.gg/5v6VYGW4Ta
  description: > Familia y clanes recién creados # vamos por más
clans:
  - name: OlimposEsports
    tag: QLJ9Y9PL
  - name: OlimposEsports
     tag: R2R2ULY9
```

**Comment by Zaop7** [comment]
```yml
name: OlimposEsports Family
key: OlimposEsports
color: pink
emblem: Flame_01

info:
  logo: /static/img/brands/logo/olimpos-esports.png
  social:
    - website: https://mifaxp.webnode.es
    - twitter: https://twitter.com/mifaxp
    - discord: https://discord.gg/TceEpJbuhe
    - twitter: https://twitter.com/OlimposClanes
    - discord: https://discord.gg/Up4uyuPd7j
    - twitter: https://twitter.com/OlimposEsports
    - discord: https://discord.gg/5v6VYGW4Ta
  description: >
    Familia y clanes recién creados # vamos por más
clans:
  - name: OlimposEsports
    tag: QLJ9Y9PL
  - name: OlimposEsports
    tag: R2R2ULY9

```
