### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DucLeto8** [RoyaleAPI/family-config#968]
```yaml
name: Arrakis 
key: Arrakis
color: yellow
emblem: Diamond_Star_01
description: A new family created in October 2023. Well organized and friendly, we accept occasionally no french speakers.
clan:
- name: Arrakis
- tag: QPGUQJ2U
- name: Arrakis 2
- tag: GRJV2PC8
- name: Arrakis 3
- tag: QYPV0LLL
- name: Arrakis 4
- tag: QPVRUCJ2
- name: Arrakis 5
- tag: QY29V22C
- name: Arrakis 6
- tag: G2UY2YRR
- name: Arrakis 7 
- tag: QCRPQJ0J
- name: ! Arrakis 8 !
- tag: G8LV0C8V
- name: ! Arrakis 9 !
- tag: QLY8J90L
```

**Comment by Zaop7** [comment]
```yml
name: Arrakis
key: arrakis
color: yellow
emblem: Diamond_Star_01
info:
  description: A new family created in October 2023. Well organized and friendly, we accept occasionally no french speakers.
clans:
  - name: Arrakis
    tag: QPGUQJ2U
  - name: Arrakis 2
    tag: GRJV2PC8
  - name: Arrakis 3
    tag: QYPV0LLL
  - name: Arrakis 4
    tag: QPVRUCJ2
  - name: Arrakis 5
    tag: QY29V22C
  - name: Arrakis 6
    tag: G2UY2YRR
  - name: Arrakis 7
    tag: QCRPQJ0J
  - name: '! Arrakis 8 !'
    tag: G8LV0C8V
  - name: '! Arrakis 9 !'
    tag: QLY8J90L

```
