### ISSUE TITLE
正港台灣狼皇室戰隊

### ISSUE THREAD

**Issue by micsam1010** [RoyaleAPI/family-config#97]
name:正港台灣狼皇室戰隊
key:F.T.W.
color:red
emblem:Flame_03
info:
  logo:
  description: >
    我們是擁有5個部落的活耀戰隊，目前主部落為台灣前10大部落之一。不定時舉辦獎金挑戰戰賽，歡迎部落戰好手加入我們的大家庭。您值得擁有最好的隊友！

  social:
    - facebook: https://www.facebook.com/groups/2022150171175203/
clans:
  - name:正港台灣狼分部
    tag:P9JU9208
  - name:正港台灣狼第二分部
    tag:P2RCJP2P
  - name:正港台灣狼第三分部
    tag:PJQ8CYCV
  - name:正港台灣狼第四分部
    tag:PVYOUR2P
```

**Comment by smlbiobot** [comment]
updated

**Comment by micsam1010** [comment]
```yaml
name:正港台灣狼皇室戰隊
key:F.T.W.
color:red
emblem:Flame_03
info:
  logo:
  description: >
    我們是擁有5個部落的活耀戰隊，目前主部落為台灣前10大部落之一。不定時舉辦獎金挑戰戰賽，歡迎部落戰好手加入我們的大家庭。您值得擁有最好的隊友！

  social:
    - facebook: https://www.facebook.com/groups/2022150171175203/
clans:
  - name:正港台灣狼
    tag:2U2PUG
  - name:正港台灣狼分部
    tag:P9JU9208
  - name:正港台灣狼第二分部
    tag:P2RCJP2P
  - name:正港台灣狼第三分部
    tag:PJQ8CYCV
  - name:正港台灣狼第四分部
    tag:PVYOUR2P
```
