### ISSUE TITLE
Scottish Army Family request

### ISSUE THREAD

**Issue by geronimoisback** [RoyaleAPI/family-config#970]
[SA.CNF.txt](https://github.com/RoyaleAPI/family-config/files/13404263/SA.CNF.txt)

**Comment by Zaop7** [comment]
Please format your request as yaml file and attach it as an code in your request. Do not link some file. You can find the instructions [here](https://github.com/RoyaleAPI/family-config/blob/master/README.md) or take inspiration from other issues.

**Comment by geronimoisback** [comment]
```yaml
name: Scottish Army Family
key: scottisharmy
color: blue
emblem: flag_n_04
info:
  logo: https://postimg.cc/bS0YmYpM
  description: >
    Welcome to the Highlands of Elixir, where the Scots have gathered to wield
    their cards and clash with a touch of tartan flair. Welcome to the premier
    Scottish Clan on Clash Royale, our family that's as sharp as a claymore
    and as cheeky as a bagpipe serenade. Our clans are a blend of camaraderie
    and friendly banter from guys coming from all corners of the globe. Expect
    a steady stream of "Ach, ye missed that Fireball!" or "May yer arrows fly
    true, and yer opponents be as confused as a sheep in a cornfield." It's
    all in good fun, and victory is toasted with a virtual dram of the finest
    virtual Scotch.
  social:
clans:
  - name: Scottish army
    tag: 82CVQ2
  - name: Scottish army 2
    tag: L8V8RGGY
  - name: Scottish army 3
    tag: QY8LL8Q2
  - name: Scottish army X
    tag: QP2LJR9V`

```

**Comment by geronimoisback** [comment]
```yaml
name: Scottish Army Family
key: scottisharmy
color: blue
emblem: flag_n_04
info:
  logo: https://postimg.cc/bS0YmYpM
  description: >
    Welcome to the Highlands of Elixir, where the Scots have gathered to wield their cards and clash with a touch of tartan flair. Welcome to the premier Scottish Clan on Clash Royale, our family that's as sharp as a claymore and as cheeky as a bagpipe serenade. Our clans are a blend of camaraderie and friendly banter from guys coming from all corners of the globe. Expect a steady stream of "Ach, ye missed that Fireball!" or "May yer arrows fly true, and yer opponents be as confused as a sheep in a cornfield." It's all in good fun, and victory is toasted with a virtual dram of the finest virtual Scotch.
  social:
clans:
  - name: Scottish army
    tag: 82CVQ2
  - name: Scottish army 2
    tag: L8V8RGGY
  - name: Scottish army 3
    tag: QY8LL8Q2
  - name: Scottish army X
    tag: QP2LJR9V`

```

**Comment by Zaop7** [comment]
Thats better thank you

**Comment by Zaop7** [comment]
```yml
name: Scottish Army Family
key: scottisharmy
color: blue
emblem: flag_n_04
info:
  logo: scottisharmy.jpg
  description: >
    Welcome to the Highlands of Elixir, where the Scots have gathered to wield
    their cards and clash with a touch of tartan flair. Welcome to the premier
    Scottish Clan on Clash Royale, our family that's as sharp as a claymore
    and as cheeky as a bagpipe serenade. Our clans are a blend of camaraderie
    and friendly banter from guys coming from all corners of the globe. Expect
    a steady stream of "Ach, ye missed that Fireball!" or "May yer arrows fly
    true, and yer opponents be as confused as a sheep in a cornfield." It's
    all in good fun, and victory is toasted with a virtual dram of the finest
    virtual Scotch.
clans:
  - name: Scottish army
    tag: 82CVQ2
  - name: Scottish army 2
    tag: L8V8RGGY
  - name: Scottish army 3
    tag: QY8LL8Q2
  - name: Scottish army X
    tag: QP2LJR9V

```

**Comment by smlbiobot** [comment]
@Zaop7 you MUST  go to the page and download the image: https://postimg.cc/bS0YmYpM

I can’t use non images in the repo

**Comment by smlbiobot** [comment]
```yml
name: Scottish Army Family
key: scottisharmy
color: blue
emblem: flag_n_04
info:
  logo: scottisharmy-v2.png
  description: >
    Welcome to the Highlands of Elixir, where the Scots have gathered to wield
    their cards and clash with a touch of tartan flair. Welcome to the premier
    Scottish Clan on Clash Royale, our family that's as sharp as a claymore
    and as cheeky as a bagpipe serenade. Our clans are a blend of camaraderie
    and friendly banter from guys coming from all corners of the globe. Expect
    a steady stream of "Ach, ye missed that Fireball!" or "May yer arrows fly
    true, and yer opponents be as confused as a sheep in a cornfield." It's
    all in good fun, and victory is toasted with a virtual dram of the finest
    virtual Scotch.
clans:
  - name: Scottish army
    tag: 82CVQ2
  - name: Scottish army 2
    tag: L8V8RGGY
  - name: Scottish army 3
    tag: QY8LL8Q2
  - name: Scottish army X
    tag: QP2LJR9V
```
