### ISSUE TITLE
Familia AMIGOS SAIYAN 

### ISSUE THREAD

**Issue by andymod99** [RoyaleAPI/family-config#971]
```yaml
name: Familia AMIGOS SAIYAN
key: Familia A.S.
color: blue
emblem: Skull_05
description: Familia de 2 clanes, creados en 2019 y 2021. Somos clanes ladder y guerra, siempre en lucha por mejorar y superar cualquier adversidad. Si buscas un clan divertido y comprometido ¡ven a conocernos!
clans:

name: AMIGOS SAIYAN
tag: #Y2V9G02V
name: AMIGOS SAIYAN 2
tag: #YV0QUVY0

```

**Comment by Zaop7** [comment]
```yml
name: Familia AMIGOS SAIYAN
key: familiaas
color: blue
emblem: Skull_05
info:
  description: Familia de 2 clanes, creados en 2019 y 2021. Somos clanes ladder y guerra, siempre en lucha por mejorar y superar cualquier adversidad. Si buscas un clan divertido y comprometido ¡ven a conocernos!
clans:
- name: AMIGOS SAIYAN
  tag: Y2V9G02V
- name: AMIGOS SAIYAN 2
  tag: YV0QUVY0

```
