### ISSUE TITLE
[0 Force Belge]: 

### ISSUE THREAD

**Issue by Nuts250** [RoyaleAPI/family-config#972]
### Family configuration

```yaml
name: 0 Force Belge 
key: Force Belge
color: black
emblem: flag_k_02
info: 
  logo: https://cdn.discordapp.com/attachments/1163748998859984916/1173709006787838132/Untitled7.png?ex=6564f0b1&is=65527bb1&hm=901adf17b45c4a25a0005ff75456b902247e15c0b5ede34ecd73226cb44f9aed& 
  description: >
    Force Belge -  Premier clan gdc de Belgique 
    Force Belge 2 - Top clan ladder Belge
    Force Belge 3 - Clan de formation en gdc pour le clan 1
    Force Belge 4 - Clan de formation pour les clans 1, 2 et 3
    Force Belge 5 - Second clan ladder
  social:
    - discord: https://discord.gg/3qbR2m4NVe
clans: 
    - name: Force Belge
      tag: 9V0Q9V
    - name: Force Belge 2
      tag: QQV99U0P
    - name: Force Belge 3
      tag: LUVGPPP0
    - name: Force Belge 4
      tag: GCJRCP8Y
    - name: Force Belge 5
      tag: QYYCCPY0
```

**Comment by Zaop7** [comment]
```yml
name: 0 Force Belge 
key: force-belge
color: black
emblem: flag_k_02
info: 
  logo: force-belge.png
  description: >
    Force Belge -  Premier clan gdc de Belgique 
    Force Belge 2 - Top clan ladder Belge
    Force Belge 3 - Clan de formation en gdc pour le clan 1
    Force Belge 4 - Clan de formation pour les clans 1, 2 et 3
    Force Belge 5 - Second clan ladder
  social:
    - discord: https://discord.gg/3qbR2m4NVe
clans: 
    - name: Force Belge
      tag: 9V0Q9V
    - name: Force Belge 2
      tag: QQV99U0P
    - name: Force Belge 3
      tag: LUVGPPP0
    - name: Force Belge 4
      tag: GCJRCP8Y
    - name: Force Belge 5
      tag: QYYCCPY0

```

**Comment by Nuts250** [comment]
name: 0 Force Belge 
key: force-belge
color: black
emblem: flag_k_02
info: 
  logo: force-belge.png
  description: >
    Force Belge -  Premier clan gdc de Belgique 
    Force Belge 2 - Top clan ladder Belge
    Force Belge 3 - Clan de formation en gdc pour le clan 1
    Force Belge 4 - Clan de formation pour les clans 1, 2 et 3
    Force Belge 5 - Second clan ladder
  social:
    - discord: https://discord.gg/3qbR2m4NVe
clans: 
    - name: Force Belge
      tag: 9V0Q9V
    - name: Force Belge 2
      tag: QQV99U0P
    - name: Force Belge 3
      tag: LUVGPPP0
    - name: Force Belge 4
      tag: GCJRCP8Y
    - name: Force Belge 5
      tag: QYYCCPY0

**Comment by Nuts250** [comment]
where do I need to paste it?

**Comment by Nuts250** [comment]
@Zaop7

**Comment by Zaop7** [comment]
You do not have to do anything.  Please give us time to check everything and publish it on the website.

**Comment by Nuts250** [comment]
ok perfect thanks a lot for your work

**Comment by Nuts250** [comment]
It would be cool if y'all devs could add a thing to sort the clan families by the amount of trophies or most cumulated war trophies or best clan average of ...

**Comment by Zaop7** [comment]
There is `sort: trophy` option if you want to sort clans by their score.

**Comment by Nuts250** [comment]
yeah I know but I do not mean in the clan family itself but all the clans that participate in clan families

**Comment by Nuts250** [comment]
@Zaop7 when will you be ready? I'm just wondering

**Comment by Nuts250** [comment]
Sir @Zaop7,when will you be ready? I'm just wondering

**Comment by Zaop7** [comment]
I dont know when we will publish the changes on the web. We are pushing all issues together. Please be patient.

**Comment by Nuts250** [comment]
ok I'll wait

**Comment by smlbiobot** [comment]
@Zaop7 Do not allow people to randomly add numbers add before their family name without talking to me first.

```yml
name: Force Belge 
key: force-belge
color: black
emblem: flag_k_02
info: 
  logo: force-belge.png
  description: >
    Force Belge -  Premier clan gdc de Belgique 
    Force Belge 2 - Top clan ladder Belge
    Force Belge 3 - Clan de formation en gdc pour le clan 1
    Force Belge 4 - Clan de formation pour les clans 1, 2 et 3
    Force Belge 5 - Second clan ladder
  social:
    - discord: https://discord.gg/3qbR2m4NVe
clans: 
    - name: Force Belge
      tag: 9V0Q9V
    - name: Force Belge 2
      tag: QQV99U0P
    - name: Force Belge 3
      tag: LUVGPPP0
    - name: Force Belge 4
      tag: GCJRCP8Y
    - name: Force Belge 5
      tag: QYYCCPY0
```
