### ISSUE TITLE
[Update]: remove SG Titans, remove Clash or Crash!, reorder the sequence of clans

### ISSUE THREAD

**Issue by cheapmonk2003** [RoyaleAPI/family-config#975]
### Family name

SG Alliance

### Family URL

https://royaleapi.com/clan/family/sgalliance/clans

### Family configuration

```yaml
name: SG Alliance
key: sgalliance
color: red
emblem: A_Char_Prince_03
info:
description: >
SG Alliance is formed by a group of Singapore clans who want to revive other Singapore
clans who are struggling,
to help each other, and yet remain independent.
social:
- email: mailto:cheapmonk2003@hotmail.com
clans:

name: TEDDYBEAR
tag: PLJ9CL9R
name: GUMMYBEAR
tag: 8URJ0QY
name: Lion City Kia
tag: C2JQUUG
name: Prata Heroes
tag: PP8RYPP0
name: Smash! eSports
tag: P9Q9YULR
name: Altitude
tag: L9QGG299
name: Attitude
tag: GQ0CL0GL
name: Lion Kia Mini
tag: YQVQ22R8
name: SG Kakis
tag: 9P922V9L
name: SG Bruschettas
tag: 8VLPYGJL
name: Marus Vengeance
tag: JR0CQ8
name: Singapore.Bros
tag: 28YYPGGQ
```

**Comment by Zaop7** [comment]
This is copy of your config file. Please seve it for further editing.
```yml
name: SG Alliance
key: sgalliance
color: red
emblem: A_Char_Prince_03
info:
  description: >
    SG Alliance is formed by a group of Singapore clans who want to revive other Singapore
    clans who are struggling,
    to help each other, and yet remain independent.
  social:
    - email: mailto:cheapmonk2003@hotmail.com
clans:
  - name: TEDDYBEAR
    tag: PLJ9CL9R
  - name: GUMMYBEAR
    tag: 8URJ0QY
  - name: Lion City Kia
    tag: C2JQUUG
  - name: Prata Heroes
    tag: PP8RYPP0
  - name: Smash! eSports
    tag: P9Q9YULR
  - name: Altitude
    tag: L9QGG299
  - name: Attitude
    tag: GQ0CL0GL
  - name: Lion Kia Mini
    tag: YQVQ22R8
  - name: SG Kakis
    tag: 9P922V9L
  - name: SG Bruschettas
    tag: 8VLPYGJL
  - name: Marus Vengeance
    tag: JR0CQ8
  - name: Singapore.Bros
    tag: 28YYPGGQ

```
