### ISSUE TITLE
New Clan Family - 100% Stars In Sweden

### ISSUE THREAD

**Issue by XswezzyWasTaken** [RoyaleAPI/family-config#976]
### Family configuration

```yaml
name: 100% Swedish Stars
key: SwedishStars
color: Blue
emblem: Traditional_Star_05
info:
  logo: https://pbs.twimg.com/profile_images/606665132454723584/6xddGdug_400x400.pngska
  description: >
    Vi är en svensk klanfamilj där vänskap och lojalitet spelar en viktig roll. Alla våra klaner är länkade till en gemensam Discord-server. 

**Stars In Sweden** är vår huvudklan. Denna klan är reserverad för våra bästa krigare. 
Våra spelare förväntas få minst 2000 medaljer/vecka och spela alla fyra matcherna/dag. 
Kraven är höga då vårt mål är att vara en högpresterande warklan i Sverige. 

**Stars In Swed1** är vår mellanklan. Denna klan är öppen för alla spelare med +6000 trophéer. 
Det är där spelare som ännu inte uppfyller kraven för huvudklanen kan utvecklas och bevisa sin skicklighet. 
Ambitionen är bli en aktiv warklan.

**Stars In Swed2** är vår underklan.** Denna klan är öppen för alla spelare. Många av våra medlemmar i de övre klanerna har sina alts här. 
Vi sparkar bara de som inte dyker upp alls på mer än en vecka.

*Gå till https://discord.gg/d9umQ3kN6Z eller klicka på discord-loggan här nedanför.*
  social:
    - discord: https://discord.gg/d9umQ3kN6Z
clans: 
 - name: Stars In Sweden
    tag: LP88J9UV
  - name: Stars In Swed1
    tag: L9QPOCGC
  - name: Stars In Swed2
    tag: G29PPP20
…
```

**Comment by Zaop7** [comment]
This is copy of your config file. Please seve it for further editing.
```yml
name: 100% Swedish Stars
key: swedishstars
color: Blue
emblem: Traditional_Star_05
info:
  logo: schwedishstars.png
  description: >
    Vi är en svensk klanfamilj där vänskap och lojalitet spelar en viktig roll. Alla våra klaner är länkade till en gemensam Discord-server. 

    **Stars In Sweden** är vår huvudklan. Denna klan är reserverad för våra bästa krigare. 
    Våra spelare förväntas få minst 2000 medaljer/vecka och spela alla fyra matcherna/dag. 
    Kraven är höga då vårt mål är att vara en högpresterande warklan i Sverige. 

    **Stars In Swed1** är vår mellanklan. Denna klan är öppen för alla spelare med +6000 trophéer. 
    Det är där spelare som ännu inte uppfyller kraven för huvudklanen kan utvecklas och bevisa sin skicklighet. 
    Ambitionen är bli en aktiv warklan.

    **Stars In Swed2** är vår underklan.** Denna klan är öppen för alla spelare. Många av våra medlemmar i de övre klanerna har sina alts här. 
    Vi sparkar bara de som inte dyker upp alls på mer än en vecka.

    *Gå till https://discord.gg/d9umQ3kN6Z eller klicka på discord-loggan här nedanför.*
  social:
    - discord: https://discord.gg/d9umQ3kN6Z
clans: 
  - name: Stars In Sweden
    tag: LP88J9UV
  - name: Stars In Swed1
    tag: L9QP0CGC
  - name: Stars In Swed2
    tag: G29PPP20

```

**Comment by smlbiobot** [comment]
We don’t allow numbers in front of family name that have nothing to do with the family.

```yml
name: Swedish Stars
key: swedishstars
color: Blue
emblem: Traditional_Star_05
info:
  logo: schwedishstars.png
  description: >
    Vi är en svensk klanfamilj där vänskap och lojalitet spelar en viktig roll. Alla våra klaner är länkade till en gemensam Discord-server. 

    **Stars In Sweden** är vår huvudklan. Denna klan är reserverad för våra bästa krigare. 
    Våra spelare förväntas få minst 2000 medaljer/vecka och spela alla fyra matcherna/dag. 
    Kraven är höga då vårt mål är att vara en högpresterande warklan i Sverige. 

    **Stars In Swed1** är vår mellanklan. Denna klan är öppen för alla spelare med +6000 trophéer. 
    Det är där spelare som ännu inte uppfyller kraven för huvudklanen kan utvecklas och bevisa sin skicklighet. 
    Ambitionen är bli en aktiv warklan.

    **Stars In Swed2** är vår underklan.** Denna klan är öppen för alla spelare. Många av våra medlemmar i de övre klanerna har sina alts här. 
    Vi sparkar bara de som inte dyker upp alls på mer än en vecka.

    *Gå till https://discord.gg/d9umQ3kN6Z eller klicka på discord-loggan här nedanför.*
  social:
    - discord: https://discord.gg/d9umQ3kN6Z
clans: 
  - name: Stars In Sweden
    tag: LP88J9UV
  - name: Stars In Swed1
    tag: L9QP0CGC
  - name: Stars In Swed2
    tag: G29PPP20

```

DO NOT attempt to do this in the future. You can be:

- Stars in Sweden
- Swedish Stars

You CANNOT BE

- 100% Swedish Stars

I know that why you are doing this — any attempts to try to bypass this manual check in the future will be permanently banned from having your family represented on our site. 

This is your first and only warning.
