### ISSUE TITLE
[0 Force Belge]: 

### ISSUE THREAD

**Issue by Nuts250** [RoyaleAPI/family-config#978]
### Family configuration

```yaml
name: 0 Force Belge 
key: force-belge
color: black
emblem: flag_k_02
info: 
  logo: force-belge.png
  description: >
    Force Belge -  Premier clan gdc de Belgique 
    Force Belge 2 - Top clan ladder Belge
    Force Belge 3 - Clan de formation en gdc pour le clan 1
    Force Belge 4 - Clan de formation pour les clans 1, 2 et 3
    Force Belge 5 - Second clan ladder
  social:
    - discord: https://discord.gg/3qbR2m4NVe
clans: 
    - name: Force Belge
      tag: 9V0Q9V
    - name: Force Belge 2
      tag: QQV99U0P
    - name: Force Belge 3
      tag: LUVGPPP0
    - name: Force Belge 4
      tag: GCJRCP8Y
    - name: Force Belge 5
      tag: QYYCCPY0onfig here
```

### Additional Info

I do not know what I am supposed to do with the YAML you gave me so I just pasted it here
