### ISSUE TITLE
[UPDATE] PTROYALEKINGS Family

### ISSUE THREAD

**Issue by jhorta01** [RoyaleAPI/family-config#979]
Family URL https://royaleapi.com/clan/family/pt-rk/clans

```yaml
name: PT ROYALE KINGS
key: pt-rk
color: black
emblem: A_Char_King_01
info:
  logo: https://imgur.com/rxg3HuM 
  description: >
    The **PT ROYALE KINGS Family** is a Portuguese clan family and counts with 5 different clans. Each one for different types of players. **PT ROYALE KINGS** is our main ladder clan and **PT ROYALE KINGS 2** is our main clan focused on war. With the large influx of players we saw the need to create 3 more clans: **PT ROYALE KINGS 3** (War), **PT ROYALE KINGS 4** (War/Ladder) and **PT ROYALE KINGS 5** (Ladder). 
    
    **Apply on Discord**
 
   social:
     - discord: https://discord.gg/BRSRwJk
clans:
  - name: PT ROYALE KINGS
    tag: GG0YYCJ
  - name: PTROYALEKINGS 2
    tag: PVRCVY29
  - name: PTROYALEKINGS 3
    tag: GGRU0ULL
  - name: PTROYALEKINGS 4
    tag: Q9CL0GCQ
  - name: PTROYALEKINGS 5
    tag: GC0GYVLJname: PT ROYALE KINGS

```

_Originally posted by @jhorta01 in https://github.com/RoyaleAPI/family-config/issues/936#issuecomment-1824342051_

**Comment by Zaop7** [comment]
The last clan doesn't have tag, so i removed it.
This is copy of your config file. Please seve it for further editing.
```yml
name: PT ROYALE KINGS
key: pt-rk
color: black
emblem: A_Char_King_01
info:
  logo: py-royale.png
  description: >
    The **PT ROYALE KINGS Family** is a Portuguese clan family and counts with 5 different
    clans. Each one for different types of players. **PT ROYALE KINGS** is our main
    ladder clan and **PT ROYALE KINGS 2** is our main clan focused on war. With the
    large influx of players we saw the need to create 3 more clans: **PT ROYALE KINGS
    3** (War), **PT ROYALE KINGS 4** (War/Ladder) and **PT ROYALE KINGS 5** (Ladder). 
    
    **Apply on Discord**
  social:
    - discord: https://discord.gg/BRSRwJk
clans:
  - name: PT ROYALE KINGS
    tag: GG0YYCJ
  - name: PTROYALEKINGS 2
    tag: PVRCVY29
  - name: PTROYALEKINGS 3
    tag: GGRU0ULL
  - name: PTROYALEKINGS 4
    tag: Q9CL0GCQ
  - name: PTROYALEKINGS 5
    tag: GC0GYVLJ

```

**Comment by smlbiobot** [comment]
```yml
name: PT ROYALE KINGS
key: pt-rk
color: black
emblem: A_Char_King_01
info:
  logo: py-royale-v2.png
  description: >
    The **PT ROYALE KINGS Family** is a Portuguese clan family and counts with 5 different
    clans. Each one for different types of players. **PT ROYALE KINGS** is our main
    ladder clan and **PT ROYALE KINGS 2** is our main clan focused on war. With the
    large influx of players we saw the need to create 3 more clans: **PT ROYALE KINGS
    3** (War), **PT ROYALE KINGS 4** (War/Ladder) and **PT ROYALE KINGS 5** (Ladder). 
    
    **Apply on Discord**
  social:
    - discord: https://discord.gg/BRSRwJk
clans:
  - name: PT ROYALE KINGS
    tag: GG0YYCJ
  - name: PTROYALEKINGS 2
    tag: PVRCVY29
  - name: PTROYALEKINGS 3
    tag: GGRU0ULL
  - name: PTROYALEKINGS 4
    tag: Q9CL0GCQ
  - name: PTROYALEKINGS 5
    tag: GC0GYVLJ
```
