### ISSUE TITLE
[Family Update] Rocket Pong

### ISSUE THREAD

**Issue by blueblair** [RoyaleAPI/family-config#98]
```yaml
name: Rocket Pong
key: rocketpong
color: red
emblem: A_Char_Rocket_02
sort: trophy
info:
  logo:
  description: >
    Rocket Pong, the Top Clan of Korea
  social:
    - website: https://cafe.naver.com/rocketpong
clans:
  - name: "Rocket Pong #1"
    tag: RRQ2UCY
  - name: Rocket Warrior
    tag: PL8V2LVU
  - name: Rocket Galaxy
    tag: PJL9Q09P
  - name: Rocket Space
    tag: PP9CYYYU
  - name: Rocket Arena
    tag: 9Q9202Q8
  - name: "Rocket Pong #2"
    tag: C89L080
  - name: "Rocket Pong #3"
    tag: 82R8U2JP
  - name: Rocket Lunatic
    tag: PY2JL8RC
  - name: Rocket Squad
    tag: PRP9CJUY
```
