### ISSUE TITLE
[Update]: The Beast Domain

### ISSUE THREAD

**Issue by Jengerr** [RoyaleAPI/family-config#981]
### Family name

#BeastDomain

### Family URL

https://royaleapi.com/clan/family/Beast/clans?lang=en

### Family configuration

```yaml
name: 'The Beast Domain'
key: Beast
color: black
emblem: Skull_05
info:
  description: >
    The Beast Domain is a family of competitive and active war players with the goal of improving and moving up on the leaderboards. We have 4 different clans, for all different skill and levels. Join us today and become a beast!
  social:
    - discord: https://discord.gg/Wwrq7VMq6G
    - instagram: https://www.instagram.com/thebeastdomain/?hl=en
clans:
- name: '#Beastmode2.0'
  tag: 9YYRQVGP
- name: '#FeedTheBeast'
  tag: LQRPC0QP
- name: Team Aqua
  tag: L280QQUR
- name: '#ObeyTheBeast'
  tag: QL8YR0RJ
```

**Comment by Zaop7** [comment]
This is copy of your config file. Please seve it for further editing.
```yml
name: "The Beast Domain"
key: Beast
color: black
emblem: Skull_05
info:
  description: >
    The Beast Domain is a family of competitive and active war players with the goal
     of improving and moving up on the leaderboards. We have 4 different clans, for
    all different skill and levels. Join us today and become a beast!
  social:
    - discord: https://discord.gg/Wwrq7VMq6G
    - instagram: https://www.instagram.com/thebeastdomain
clans:
  - name: "#Beastmode2.0"
    tag: 9YYRQVGP
  - name: "#FeedTheBeast"
    tag: LQRPC0QP
  - name: Team Aqua
    tag: L280QQUR
  - name: "#ObeyTheBeast"
    tag: QL8YR0RJ

```
