### ISSUE TITLE
**You didn't make any changes. Can i close this issue?** @andymod99

### ISSUE THREAD

**Issue by andymod99** [RoyaleAPI/family-config#982]
**You didn't make any changes. Can i close this issue?** @andymod99 
This is copy of your family config file. Please save it.
```yml
name: Familia AMIGOS SAIYAN
key: FAMILIA-AS
color: blue
emblem: Skull_05
info:
  description: Familia de 2 clanes, creados en 2019 y 2021. Somos clanes ladder y guerra, siempre en lucha por mejorar y superar cualquier adversidad. Si buscas un clan divertido y comprometido ¡ven a conocernos!
clans:
- name: AMIGOS SAIYAN
  tag: Y2V9G02V
- name: AMIGOS SAIYAN 2
  tag: YV0QUVY0

```

_Originally posted by @Zaop7 in https://github.com/RoyaleAPI/family-config/issues/974#issuecomment-1827965390_
