### ISSUE TITLE
Update: Liverpool

### ISSUE THREAD

**Issue by Liverpool-Clan** [RoyaleAPI/family-config#984]
### Family name

Liverpool

### Family URL

https://royaleapi.com/clan/family/liverpool/clans

### Family configuration

```yaml
name: Liverpool Family Clans
key: liverpool
color: red
emblem: flag_f_02
info:
  logo: https://photos.app.goo.gl/rGC5ABthfDFsY6zNA
  description: >
    This is Anfield. We are Liverpool. Global international Liverpool F.C. supporters into Clash Royale. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!
  social:
  - email: mailto_crownprinceakacp@gmail.com

clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
  - name: Liverpool Spion
    tag: GJVG2V82
```

**Comment by Zaop7** [comment]
This is copy of your config file. Please seve it for further editing.
The logo link wasn't reacheable, so it has been removed.
```yml
name: Liverpool Family Clans
key: liverpool
color: red
emblem: flag_f_02
info:
  description: >
    This is Anfield. We are Liverpool. Global international Liverpool F.C. supporters into Clash Royale. Be a part of our ever growing Liverpool family clans. You'll Never Walk Alone!
  social:
    - email: mailto:crownprinceakacp@gmail.com
clans:
  - name: Liverpool
    tag: GL2PQGR
  - name: Liverpool Reds
    tag: LJUPUP9V
  - name: Liverpool Kop
    tag: LV2Y88C8
  - name: Liverpool Spion
    tag: GJVG2V82

```
