### ISSUE TITLE
[New] Clan Family Listing - Big Igloo

### ISSUE THREAD

**Issue by bmpfal** [RoyaleAPI/family-config#986]
```yaml
name: Big Igloo
key: Big_Igloo
color: blue
emblem: Flame_04
info:
  logo: https://cdn.discordapp.com/icons/757396574111268874/9688967c4702d2daecb409f1fad2d2c3.webp?size=240
  description: >
    **Become a part of the Big Igloo Empire** - Founded by **Tsar Kunz** - 
    War Clan established in June 2020.
    Come join us as we continue to show our might over our war enemies. 
    Now featuring Big Igloo II through VII to choose your entry point feeder.
    Talk your talk and back it up each week in War!
  social:
    - discord: https://discord.gg/tnfHrxDUQc
clans:
  - name: Big Igloo
    tag: YY0YU92V
  - name: Big Igloo II
    tag: LCCPV2LG
  - name: Big Igloo III
    tag: L90V2L9G
  - name: Big Igloo IV
    tag: LGJR09QG
  - name: Big Igloo V
    tag: Q8VLR9JV
  - name: Big Igloo VI
    tag: G2YYYPRC
  - name: Big Igloo VII
    tag: R2L9GU22
```

**Comment by Zaop7** [comment]
> [!NOTE]
> The logo link is not reachable.

> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Big Igloo
key: big-igloo
color: blue
emblem: Flame_04
info:
  description: >
    **Become a part of the Big Igloo Empire** - Founded by **Tsar Kunz** - 
    War Clan established in June 2020.
    Come join us as we continue to show our might over our war enemies. 
    Now featuring Big Igloo II through VII to choose your entry point feeder.
    Talk your talk and back it up each week in War!
  social:
    - discord: https://discord.gg/tnfHrxDUQc
clans:
  - name: Big Igloo
    tag: YY0YU92V
  - name: Big Igloo II
    tag: LCCPV2LG
  - name: Big Igloo III
    tag: L90V2L9G
  - name: Big Igloo IV
    tag: LGJR09QG
  - name: Big Igloo V
    tag: Q8VLR9JV
  - name: Big Igloo VI
    tag: G2YYYPRC
  - name: Big Igloo VII
    tag: R2L9GU22

```
