### ISSUE TITLE
[Update]:  actualización del código de clan 

### ISSUE THREAD

**Issue by Mikilol77** [RoyaleAPI/family-config#987]
### Family name

DAMX

### Family URL

Copy the link (URL address) from your browser and paste it here.

### Family configuration

```yaml
name: dark AllianceMX
key: DAMX
color: purple
emblem: Star_Shine_03
info:
  logo:
  description:  >
      Famila Dark AllianceMX contamos con 3 clanes, grupo de wats y alianza con otros clanes , en busca del top nacional
clans:
- name: Dark AllianceMX
  tag: 92uu22jq
- name: Dark Squad
  tag: 9CVOPYVO
- name: Mexico eSport
  tag: 98CLYULC
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: dark AllianceMX
key: DAMX
color: purple
emblem: Star_Shine_03
info:
  description: >
    Famila Dark AllianceMX contamos con 3 clanes, grupo de wats y alianza con otros
    clanes , en busca del top nacional
clans:
  - name: Dark AllianceMX
    tag: 92UU22JQ
  - name: Dark Squad
    tag: 9CV0PYV0
  - name: Mexico eSport
    tag: 98CLYULC

```
