### ISSUE TITLE
Pluizers.yml (Top Dutch Clan)

### ISSUE THREAD

**Issue by Frwf** [RoyaleAPI/family-config#990]
name: Pluizers
key: pluizers
color: blue
emblem: Twin_Peaks_01
sort: trophy
info:
  logo: https://media.discordapp.net/attachments/1176553807447080962/1182054923861512323/IMG-20231122-WA0006.jpg?ex=65834d6f&is=6570d86f&hm=125ef12b32a4d5fdb308b58d7c47778648578d7f3631d3b1eb7c4447eafc1225&=&format=webp
  description: >
    Gaat het op ladder niet zo pluis en heb je geen zin in al dat gespuis?
    Dan zit je hier wel pluis! Top 5 NL, ooit nummer 1 van de wereld.
  social:
    - twitter: https://twitter.com/Pluisboy_CR
    - discord: https://discord.gg/HN5qaBRvVw
    - instagram: https://www.instagram.com/pluisboy_cr/
    - youtube: https://www.youtube.com/channel/UCBIGlVAIt6wJSUzI-O8GTyw
clans:
  - name: Pluizers
    tag: LLU8R820
  - name: Pluizers Senior
    tag: QJVVYOQR
  - name: Pluizers Jr
    tag: YCCGYRPY
  - name: Pluizers Jr2
    tag: L8VQVGPG

**Comment by Zaop7** [comment]
Please reformat your text as .yml file. Take a look on other issues.

**Comment by Frwf** [comment]
> Please reformat your text as .yml file. Take a look on other issues.

How do i do that?

**Comment by Frwf** [comment]
name: Pluizers
key: pluizers
color: blue
emblem: Twin_Peaks_01
sort: trophy
info:
logo: https://media.discordapp.net/attachments/1176553807447080962/1182054923861512323/IMG-20231122-WA0006.jpg?ex=65834d6f&is=6570d86f&hm=125ef12b32a4d5fdb308b58d7c47778648578d7f3631d3b1eb7c4447eafc1225&=&format=webp
description: >
Gaat het op ladder niet zo pluis en heb je geen zin in al dat gespuis?
Dan zit je hier wel pluis! Top 5 NL, ooit nummer 1 van de wereld.
social:
- twitter: https://twitter.com/Pluisboy_CR
- discord: https://discord.gg/HN5qaBRvVw
- instagram: https://www.instagram.com/pluisboy_cr/
- youtube: https://www.youtube.com/channel/UCBIGlVAIt6wJSUzI-O8GTyw
clans:

name: Pluizers
tag: LLU8R820
name: Pluizers Senior
tag: QJVVYOQR
name: Pluizers Jr
tag: YCCGYRPY
name: Pluizers Jr2
tag: L8VQVGPG

**Comment by Frwf** [comment]
??????????

**Comment by Zaop7** [comment]
Please take a look at the [documentation](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Pluizers
key: pluizers
color: blue
emblem: Twin_Peaks_01
sort: trophy
info:
  logo: pluizers.png
  description: >
    Gaat het op ladder niet zo pluis en heb je geen zin in al dat gespuis?
    Dan zit je hier wel pluis! Top 5 NL, ooit nummer 1 van de wereld.
  social:
    - twitter: https://twitter.com/Pluisboy_CR
    - discord: https://discord.gg/HN5qaBRvVw
    - instagram: https://www.instagram.com/pluisboy_cr/
    - youtube: https://www.youtube.com/channel/UCBIGlVAIt6wJSUzI-O8GTyw
clans:
  - name: Pluizers
    tag: LLU8R820
  - name: Pluizers Senior
    tag: QJVVY0QR
  - name: Pluizers Jr
    tag: YCCGYRPY
  - name: Pluizers Jr2
    tag: L8VQVGPG
```
