### ISSUE TITLE
Elite Nation Family

### ISSUE THREAD

**Issue by Prince03r** [RoyaleAPI/family-config#991]
```yaml
name: Elite Nation Family 
key:  Nation
color: Blue
emblem: Fugi_03
info:
  logo: /static/img/branding/cr-api-logo.png
  description: >
The Elite Nation Family wants to become a strong nation for the century. 
We have built the clan and want to expand with more members around the world. 
This community are very friendly & consistently active. 
We want to be very competitive and united more players to be friendly and have fun as usual.  
Social: n/a 
Clans: 
- name: Arcane Nation 
  tag: Y90P88JR
- name: Newlands 
  tag: GCYOYOGO
- name: Elite Warriors 
  tag: QYUGQU2R
- name: Elite Prince 
  tag: G8UCCPRO

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Elite Nation Family
key: nation
color: Blue
emblem: Fugi_03
info:
  description: >
    The Elite Nation Family wants to become a strong nation for the century. 
    We have built the clan and want to expand with more members around the world. 
    This community are very friendly & consistently active. 
    We want to be very competitive and united more players to be friendly and have fun as usual.
clans:
  - name: Arcane Nation
    tag: Y90P88JR
  - name: Newlands
    tag: GCY0Y0G0
  - name: Elite Warriors
    tag: QYUGQU2R
  - name: Elite Prince
    tag: G8UCCPR0
```
