### ISSUE TITLE
[Update]: Forteresse

### ISSUE THREAD

**Issue by LeMeilleur66** [RoyaleAPI/family-config#992]
### Family name

! Forteresse

### Family URL

https://royaleapi.com/clan/family/forteresse/clans

### Family configuration

```yaml
name: '! Forteresse'
key: forteresse
color: purple
emblem: Sword_01
info:
  logo: /static/img/brands/logo/forteresse.png
  description: >
    !Forteresse est une famille de clans créée en décembre 2018. Nous cherchons à classer 1 clan GDC/ladder, 2 clans en GDC et 2 clans en ladder. Si jouer pour toi c'est te donner et gagner, alors ta place est avec nous ! Nous avançons avec un esprit d'équipe dans la bonne humeur et le respect. Parlons en ensemble en rejoignant notre Discord : Forteresse  

  social:
  - discord: https://discord.gg/forteresse
clans:
- name: '! Forteresse !'
  tag: PQ9GRCLR
- name: '! Forteresse 2'
  tag: P8QJR928
- name: '! Forteresse 3'
  tag: PLU8CR9Y
- name: '! Forteresse 4'
  tag: Y09J88YP
- name: '! Forteresse 5'
  tag: PGULJLQP
- name: '! Forteresse 6'
  tag: Q89L92PJ
- name: '! Forteresse FL'
  tag: LJV90LQQ
- name: '! Chez Mel'
  tag: LCCCL0VV
- name: '! GF Radicale™'
  tag: GUJRR0QY
- name: 'Great FR'
  tag: YGPLJ0C0
- name: 'New Great FR'
  tag: YPP9RYJL
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: "! Forteresse"
key: forteresse
color: purple
emblem: Sword_01
info:
  logo: /static/img/brands/logo/forteresse.png
  description: >
    !Forteresse est une famille de clans créée en décembre 2018. Nous cherchons à classer 1 clan GDC/ladder, 2 clans en GDC et 2 clans en ladder. Si jouer pour toi c'est te donner et gagner, alors ta place est avec nous ! Nous avançons avec un esprit d'équipe dans la bonne humeur et le respect. Parlons en ensemble en rejoignant notre Discord : Forteresse
  social:
    - discord: https://discord.gg/forteresse
clans:
  - name: "! Forteresse !"
    tag: PQ9GRCLR
  - name: "! Forteresse 2"
    tag: P8QJR928
  - name: "! Forteresse 3"
    tag: PLU8CR9Y
  - name: "! Forteresse 4"
    tag: Y09J88YP
  - name: "! Forteresse 5"
    tag: PGULJLQP
  - name: "! Forteresse 6"
    tag: Q89L92PJ
  - name: "! Forteresse FL"
    tag: LJV90LQQ
  - name: "! Chez Mel"
    tag: LCCCL0VV
  - name: "! GF Radicale™"
    tag: GUJRR0QY
  - name: "Great FR"
    tag: YGPLJ0C0
  - name: "New Great FR"
    tag: YPP9RYJL

```
