### ISSUE TITLE
Clan request for royale api

### ISSUE THREAD

**Issue by Pecr7** [RoyaleAPI/family-config#993]
```yaml
Name: Pro Extinction 
key: PE
color: Blue
emblem: A_Char_Goblin_01
sort: trophy
info:
    **Competitive excellence through community-driven values.**
    PE is a mobile-focused eSports organization committed to empowering
    individuals through a supportive team environment.
    We look for talent that has the character to back it up.
    That talent is cultivated and supported through team-based growth strategies and
    passionate staff that care about player outcomes.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
    - youtube: https://www.youtube.com/channel/@clashcr7
    - email: PEesports@gmail.com
clans:
  - name: Pro Extinction 
    tag: #Y8VQY0C9
```
