### ISSUE TITLE
[New]: clan verification request 

### ISSUE THREAD

**Issue by Pecr7** [RoyaleAPI/family-config#994]
### Family configuration

```yaml
Name: Pro Extinction 
key: PE
color: blue
emblem: A_Char_Goblin_01
sort: trophy
info:
    **Competitive excellence through community-driven values.**
    PE is a mobile-focused eSports organization committed to empowering
    individuals through a supportive team environment.
    We look for talent that has the character to back it up.
    That talent is cultivated and supported through team-based growth strategies and
    passionate staff that care about player outcomes.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
    - youtube: https://www.youtube.com/channel/@clashcr7
    - email: PEesports@gmail.com
clans:
  - name: Pro Extinction 
    tag:Y8VQY0C9
- name: proextinction.2
  tag : Q8QPV0YG
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Pro Extinction 
key: pe
color: blue
emblem: A_Char_Goblin_01
sort: trophy
info:
  description: >
    **Competitive excellence through community-driven values.**
    PE is a mobile-focused eSports organization committed to empowering
    individuals through a supportive team environment.
    We look for talent that has the character to back it up.
    That talent is cultivated and supported through team-based growth strategies and
    passionate staff that care about player outcomes.
    Community is the foundation of those outcomes and is the core of player dedication.
  social:
    - youtube: https://www.youtube.com/channel/@clashcr7
    - email: mailto:PEesports@gmail.com
clans:
  - name: Pro Extinction 
    tag: Y8VQY0C9
  - name: proextinction.2
    tag : Q8QPV0YG

```
