### ISSUE TITLE
[New]: scn

### ISSUE THREAD

**Issue by kucomaster** [RoyaleAPI/family-config#995]
name: Slovak Clan Network
key: SCN
color: red
emblem: flame_04
info:
  logo: https://cdn.discordapp.com/attachments/1185135225207013458/1185135426139340810/SCNlogo.png
  description: >
    Slovak Clan Network je slovenská klanová rodina, ktorá spája aktívne klany 

Podmienky prijatia klanu do SCN: klan musí byť aktívny, ochotný pomôcť vo war, zúčastňovať sa na akciách a eventoch, komunikatívny, location nastavenú na Slovakia.
 
Výhody členstva: pravidelné súťaže, pohodová široká komunita hráčov, šanca presadiť svoj klan do upovedomenia atď..

V linkoch nájdeš main Discord pomocou ktorého clan familly komunikuje a Discord pre registráciu klanu do SCN kde prípadne môžeš preriešiť všetky nejasnosti.

social:
    - discord:  https://discord.gg/DA39rsZJhr
    - discord: https://discord.gg/Yg7NyqWCtW
clans:
  - name: Psycord
    tag: P9YYV2CQ
  - name: Psycord II
    tag: G2C0PRGV
  - name: 300 Hrmenych_SK
    tag: 9CYGVGGL
  - name: Kladzivári
    tag: LG82LLLU
  - name: Kladzivári 2
    tag: LQYU008U  
  - name: SVK Elite team
    tag: 2QUYUPQ2
  - name: King Slovakia
    tag: QCCU88
  - name: SK veteráni CZ
    tag: GYGRR28Q
  - name: ANTI CIGOS
    tag: G0CPGQ8Q
  - name: Jednota
    tag: P8LPYC8J
  - name: Slovak Avengers
    tag: Q82QP
  - name: game Brothers
    tag: 8V2CUQLU
  - name: game bros sk/cz
    tag: L0VUL820
  - name: slovak power
    tag: CGJYLCU
  - name: Insane Streets
    tag:LCUVUVGG

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Slovak Clan Network
key: scn
color: red
emblem: Flame_04
info:
  logo: scn.png
  description: >
    Slovak Clan Network je začínajúca clan rodina ktorá víta všetky nové clany ktoré by sa chcú pridať.
    SCN sa oficiálne spúšťa 1.1.2024
    Podmienky a výhody:Clan musí byť ochotný pomáhať ostatným clanom ak o to požiadajú,aktívne kominikovať, súťaže a turnaje medzi clanmi
    Chceš sa pridať? Neváhaj napísať na discord
    SCN discord v príprave...
  social:
    - discord: https://discord.gg/pEKEVHmE9e
clans:
  - name: Psycord
    tag: P9YYV2CQ
  - name: Psycord II
    tag: G2C0PRGV
  - name: 300 Hrmenych_SK
    tag: 9CYGVGGL
  - name: Kladzivári
    tag: LG82LLLU
  - name: Kladzivári 2
    tag: LQYU008U
  - name: SVK Elite team
    tag: 2QUYUPQ2
  - name: King Slovakia
    tag: QCCU88
  - name: SK veteráni CZ
    tag: GYGRR28Q
  - name: ANTI CIGOS
    tag: G0CPGQ8Q
  - name: Jednota
    tag: P8LPYC8J
  - name: Slovak Avengers
    tag: Q82QP
  - name: game Brothers
    tag: 8V2CUQLU
  - name: game bros sk/cz
    tag: L0VUL820
  - name: slovak power
    tag: CGJYLCU

```
