### ISSUE TITLE
[New]: Persian Team

### ISSUE THREAD

**Issue by AliRafiee10** [RoyaleAPI/family-config#996]
### Family configuration

```yaml
name: Persian Team Clan Family
key: persianteam
color: purple
emblem: Skull_05
info:
  logo: https://i.postimg.cc/6QxxmWv8/dark-blue.png
  description: >
  Join us in the "Persian Team" 
  **Always be your best self**
  social:
    - telegram: https://t.me/persianteam_ir
clans:
  - name: Persian Royale
    tag: JQYL8YQ
  - name: Parvaz
    tag: L9PYCULL
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Persian Team Clan Family
key: persianteam
color: purple
emblem: Skull_05
info:
  logo: persianteam.png
  description: >
    Join us in the "Persian Team" 
    **Always be your best self**
  social:
    - telegram: https://t.me/persianteam_ir
clans:
  - name: Persian Royale
    tag: JQYL8YQ
  - name: Parvaz
    tag: L9PYCULL

```
