### ISSUE TITLE
Updated clan family with description, color and picture

### ISSUE THREAD

**Issue by XswezzyWasTaken** [RoyaleAPI/family-config#997]
```yaml
name: Stars In Sweden
key: SwedishStars
color: Yellow
emblem: Traditional_Star_05
info:
  logo: https://cdn.discordapp.com/attachments/1176419618915635221/1185847420677013524/IMG_1270.png?ex=65911979&is=657ea479&hm=4d891780657fb0b888f7b69c9c036e1db27759a249baf6aa8bb77d71b2ed571d& 
  description: >
    Vi är en svensk klanfamilj där vänskap och lojalitet spelar en viktig roll. Alla våra klaner är länkade till en gemensam Discord-server. 

**Stars In Sweden** är vår huvudklan. Denna klan är reserverad för våra bästa krigare. 
Våra spelare förväntas få minst 2000 medaljer/vecka och spela alla fyra matcherna/dag. 
Kraven är höga då vårt mål är att vara en högpresterande warklan i Sverige. 


**Stars In Swed1** är vår mellanklan. Denna klan är öppen för alla spelare med +6000 trophéer. 
Det är där spelare som ännu inte uppfyller kraven för huvudklanen kan utvecklas och bevisa sin skicklighet. 
Ambitionen är bli en aktiv warklan.


**Stars In Swed2** är vår underklan.** Denna klan är öppen för alla spelare. Många av våra medlemmar i de övre klanerna har sina alts här. 
Vi sparkar bara de som inte dyker upp alls på mer än en vecka.


*Gå till https://discord.gg/d9umQ3kN6Z eller klicka på discord-loggan här nedanför.*
  social:
    - discord: https://discord.gg/d9umQ3kN6Z
clans: 
 - name: Stars In Sweden
    tag: LP88J9UV
  - name: Stars In Swed1
    tag: L9QPOCGC
  - name: Stars In Swed2
    tag: G29PPP20
…
```

**Comment by Zaop7** [comment]
> [!IMPORTANT]
> This is copy of your config file. Please save it for further editing.
```yml
name: Stars In Sweden
key: swedishstars
color: Yellow
emblem: Traditional_Star_05
info:
  logo: schwedishstars.png
  description: >
    Vi är en svensk klanfamilj där vänskap och lojalitet spelar en viktig roll. Alla våra klaner är länkade till en gemensam Discord-server. 

    **Stars In Sweden** är vår huvudklan. Denna klan är reserverad för våra bästa krigare. 
    Våra spelare förväntas få minst 2000 medaljer/vecka och spela alla fyra matcherna/dag. 
    Kraven är höga då vårt mål är att vara en högpresterande warklan i Sverige. 


    **Stars In Swed1** är vår mellanklan. Denna klan är öppen för alla spelare med +6000 trophéer. 
    Det är där spelare som ännu inte uppfyller kraven för huvudklanen kan utvecklas och bevisa sin skicklighet. 
    Ambitionen är bli en aktiv warklan.


    **Stars In Swed2** är vår underklan.** Denna klan är öppen för alla spelare. Många av våra medlemmar i de övre klanerna har sina alts här. 
    Vi sparkar bara de som inte dyker upp alls på mer än en vecka.


    *Gå till https://discord.gg/d9umQ3kN6Z eller klicka på discord-loggan här nedanför.*
  social:
    - discord: https://discord.gg/d9umQ3kN6Z
clans:
  - name: Stars In Sweden
    tag: LP88J9UV
  - name: Stars In Swed1
    tag: L9QP0CGC
  - name: Stars In Swed2
    tag: G29PPP20

```
