### ISSUE TITLE
clan

### ISSUE THREAD

**Issue by silevrehelukhedu** [RoyaleAPI/family-config#998]
```yaml
name: Mero
key: mero 
color: Yellow
emblem: Lotus_02
info:
  logo: /static/img/branding/badges/Lotus_02.png
  description: >
    **An Emerging War Clan** 
 Need more competative players to reach legendary league. Currently Gold III.

clans:
  - name: Mero Clan
    tag: G9RCJ9QY

```
